### ISSUE TITLE
Blog on a different domain and Twitter

### ISSUE THREAD

**Issue by andrewshadura** [snarfed/bridgy#1000]
Hi,

I have a blog on a separate domain (blog.shadura.me) than the main website; Twitter doesn’t allow me to add more than one link to the profile. Despite both domains interlinking and the Atom feed specified in `<link rel="feed">`, Bridgy refuses to allow those. Can this restriction be lifted for situations like mine when I explicitly tell that the feed is elsewhere?

**Comment by armingrewe** [comment]
You can add the link to your blog in your Twitter bio, you can even add several. That's what I've done and it works for me (I'm twitter.com/Islayblog if you want to see how I've done it)

**Comment by andrewshadura** [comment]
Links in the description field have `rel="noopener noreferrer"` though, doesn’t that prevent them from working properly?

**Comment by andrewshadura** [comment]
[Added it](https://twitter.com/andrew_shadura) but  it didn’t work:
> Could not find Twitter account for blog.shadura.me. Check that your Twitter profile has blog.shadura.me in its *web site* or *link* field, then try signing up again.

**Comment by armingrewe** [comment]
Then I'm stumped. That's what @snarfed told me a while back and it worked for me.

**Comment by snarfed** [comment]
Apologies, this is indeed a non-obvious part of Bridgy. @andrewshadura, after you added it to your Twitter bio, did you log into Bridgy again, [as mentioned in the docs](https://brid.gy/about#profile-links)? That should do it.

**Comment by andrewshadura** [comment]
Thanks, it works now.
However, when I do a preview e.g. for https://blog.shadura.me/2020/12/22/vendoring-rust-in-debian-derivative/, it only shows a link to the index page, not the post — and it indeed posts it if I click confirm.

**Comment by snarfed** [comment]
@andrewshadura looks like microformats2 on your site isn't really set up yet: https://pin13.net/mf2/?url=https://blog.shadura.me/2020/12/22/vendoring-rust-in-debian-derivative/ . [Bridgy needs that to parse your posts.](https://brid.gy/about#microformats)

**Comment by andrewshadura** [comment]
I see, I messed up the markup. Thanks!
