### ISSUE TITLE
Fail to read syndication link of mastodon when more than one syndication

### ISSUE THREAD

**Issue by jackysee** [snarfed/bridgy#1005]
I'm using wordpress syndication link to try to syndicate to mastodon, but failed. 
The post url is https://jacky.seezone.net/2021/01/13/19328/ 
If I use 'Discover' at brid.gy, it would also fail to fetch. 

The log https://brid.gy/log?start_time=1610507656&key=agdicmlkLWd5clILEg1QdWJsaXNoZWRQYWdlIitodHRwczovL2phY2t5LnNlZXpvbmUubmV0LzIwMjEvMDEvMTMvMTkzMjgvDAsSB1B1Ymxpc2gYgICI3OCDkAoM 

In the html there are two syndication links (twitter & mastodon), twitter one can be read but not the mastodon one. Is there something wrong with the markup?

**Comment by jackysee** [comment]
Another one where I only tick post to mastodon, the syndication link can be read but the post to mastodon is 403. Don't know if it's server problem or bridgy problem?

https://brid.gy/log?start_time=1610514319&key=agdicmlkLWd5clILEg1QdWJsaXNoZWRQYWdlIitodHRwczovL2phY2t5LnNlZXpvbmUubmV0LzIwMjEvMDEvMTMvMTkzMzIvDAsSB1B1Ymxpc2gYgICInOTSgQoM

**Comment by jackysee** [comment]
Posting mastodon **alone** now works, after I have disabled publishing and then enable again.
Posting both twitter & mastodon doesn't work

**Comment by snarfed** [comment]
Sorry for the trouble, and thanks for all the details!

The consistent issue I'm seeing here is, when you use Bridgy Publish to syndicate a post to both Twitter and Mastodon, Bridgy sees the Twitter publish link (https://brid.gy/publish/twitter) but not the Mastodon publish link (https://brid.gy/publish/mastodon). I do see the Mastodon publish link later though, when I look in a browser.

https://jacky.seezone.net/2021/01/13/19346/ is a good example. The publish logs for both silos ([Twitter](https://brid.gy/log?start_time=1610532718&key=agdicmlkLWd5clILEg1QdWJsaXNoZWRQYWdlIitodHRwczovL2phY2t5LnNlZXpvbmUubmV0LzIwMjEvMDEvMTMvMTkzNDYvDAsSB1B1Ymxpc2gYgICIzI3vhAsM), [Mastodon](https://brid.gy/log?start_time=1610532523&key=agdicmlkLWd5clILEg1QdWJsaXNoZWRQYWdlIitodHRwczovL2phY2t5LnNlZXpvbmUubmV0LzIwMjEvMDEvMTMvMTkzNDQvDAsSB1B1Ymxpc2gYgICInImbnwoM)) only show the Twitter publish link.

Your site's markup is fine, and I'm pretty confident in Bridgy's HTML and mf2 parsing. Is your site maybe sending the webmentions to trigger Bridgy Publish before the Mastodon publish link gets included?

You might try turning off your automatic webmention sending, post a post, check that both publish links are there, and then send each publish webmention manually to see if they both work then.

**Comment by jackysee** [comment]
I tried to make a post contains both publish links and send webmention individually via https://telegraph.p3k.io . 
They all succeeded. (I also tried different orders, i.e. twitter first or mastodon first)

https://jacky.seezone.net/2021/01/14/19350/
https://telegraph.p3k.io/webmention/15NgaFyfzePG2oqYAX/details
https://telegraph.p3k.io/webmention/15NmYbmK472zFrfu8H/details

https://jacky.seezone.net/2021/01/14/19352/
https://telegraph.p3k.io/webmention/15B2NkrX7KjAg6R1Wf/details
https://telegraph.p3k.io/webmention/15etJIrXWKZBES3UYX/details

For the sending part in wordpress, it's handled by syndication links plugin, can't quite sure on whether the publish link  is intact when sending webmention. Here is the syndication_log it captured for the failed case:

```
array (
  0 => 
  array (
    'twitter-bridgy' => true,
    'mastodon-bridgy' => 
    WP_Error::__set_state(array(
       'errors' => 
      array (
        'mastodon-bridgy_publish_error' => 
        array (
          0 => 'Unknown Mastodon via Bridgy Error',
        ),
      ),
       'error_data' => 
      array (
        'mastodon-bridgy_publish_error' => 
        array (
          'status' => 400,
          'data' => 
          (object) array(
             'error' => 'Couldn\'t find link to brid.gy/publish/mastodon',
          ),
        ),
      ),
       'additional_data' => 
      array (
      ),
    )),
  ),
)
```

**Comment by snarfed** [comment]
> I tried to make a post contains both publish links and send webmention individually via https://telegraph.p3k.io .
> They all succeeded. (I also tried different orders, i.e. twitter first or mastodon first)

Thanks! That's a key clue. cc @dshanske for the Syndication Links plugin.

**Comment by snarfed** [comment]
Evidence seems to point to an issue with Syndication Links or similar on your site's side (friendly ping @dshanske), so I'm tentatively closing here. Feel free to reopen!

**Comment by jackysee** [comment]
For the record, I found that it's the cache busting problem.

https://github.com/dshanske/syndication-links/issues/140
