### ISSUE TITLE
Is Bridgy what I'm looking for?

### ISSUE THREAD

**Issue by leo60228** [snarfed/bridgy#1008]
I currently have Twitter, Mastodon, and Tumblr accounts, as well as a blog hosted on Netlify.
Twitter isn't really relevant here, I primarily use it just to interact with people I follow.
I use Mastodon for short-form content (microblogging).
I use my blog for long-form announcements I don't expect to get many direct responses to.
I use Tumblr for stuff that doesn't fit into Mastodon or my blog, like interacting with content on Tumblr or long series of many short posts that would take up too much space on my blog but would be confusing as a thread.
I'd like content from my blog to be automatically cross-posted to Mastodon, and it isn't a requirement but it would be nice if when I linked Tumblr posts from Mastodon that would be noted on the post itself.
Does Bridgy or Bridgy Fed do this? If not, is there a suitable alternative?

**Comment by Ryuno-Ki** [comment]
Hm, Bridgy is using WebMentions behind the scenes. So it could help you cross-post _comments_.

What you're describing sounds more like a case for [IFTTT](https://ifttt.com/) to me.

**Comment by snarfed** [comment]
IFTTT could definitely work! [Bridgy can automatically post from your blog to Mastodon too](https://brid.gy/about#webmentions), but @Ryuno-Ki is right, you automate it via webmention.

As for Mastodon to Tumblr, Bridgy won't send your toot itself, but [it will send likes, replies, etc.P](https://brid.gy/about#which) Your Tumblr will need to support [webmentions](https://webmention.net/) though. [Bridgy can do that for you too.](https://brid.gy/about#blogs)

**Comment by leo60228** [comment]
> Mastodon replies, favorites, boosts, mentions, and **links to your site**.

Is that not what I'm looking for? Anyway, it seems like Bridgy (non-Fed) is exactly what I'm looking for, so I'm closing this issue.
