### ISSUE TITLE
brid.gy publish to flickr: "Could not find content in h-entry or any other element!"

### ISSUE THREAD

**Issue by ScootRay** [snarfed/bridgy#1009]
I seem to be having this issue with Wordpress --> Flickr. I'm getting this error:

`D 2021-02-08 07:52:44.707342 Converted to ActivityStreams object: {
  "objectType": "article",
  "displayName": "Test photo",
  "content": "<p>for crossposting to Flickr again</p>\n<p><a href=\"https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro.jpg\"><img alt=\"\" class=\"u-photo alignnone wp-image-4541 size-full\"
  "tags": [
    {
      "objectType": "hashtag",
      "displayName": "meanderings"
    }
  ],
  "url": "https://alongtheray.com/meanderings/test-photo/";`

```
I 2021-02-08 07:52:44.805459 Object type(s) {'h-entry'} not supported; error=Cannot publish type=article to Flickr.; trying next.
I 2021-02-08 07:52:44.805753 Could not find content in <a href="http://microformats.org/wiki/h-entry">h-entry</a>; or any other element!

```
..even though I can confirm the image has the "u-photo" item in the img class:

`<img class="u-photo alignnone wp-image-4541 size-full" src="https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro.jpg" alt="" width="1598" height="1065" srcset="https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro.jpg 1598w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-300x200.jpg 300w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1024x682.jpg 1024w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1536x1024.jpg 1536w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-768x512.jpg 768w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1000x666.jpg 1000w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-500x334.jpg 500w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1400x933.jpg 1400w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1320x880.jpg 1320w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-300x200@2x.jpg 600w" sizes="(max-width: 1598px) 100vw, 1598px" loading="eager" style="opacity: 1;">`

Here's the logfile in full: https://brid.gy/log?start_time=1612770764&key=agdicmlkLWd5clYLEg1QdWJsaXNoZWRQYWdlIi9odHRwczovL2Fsb25ndGhlcmF5LmNvbS9tZWFuZGVyaW5ncy90ZXN0LXBob3RvLwwLEgdQdWJsaXNoGICAiL7qupwJDA

Is there anything else I can do to fix this?

Many thanks for providing a wonderful service!
Ray

**Comment by snarfed** [comment]
Hi Ray! Sorry the error message here isn't clearer. You need a [`u-photo` microformats2 class](https://indieweb.org/photo#How_to_markup) in your post on the image that you want to publish to Flickr. [Example here.](https://brid.gy/about#picture)

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
