### ISSUE TITLE
Pleroma (via Mastodon) publish: permission error

### ISSUE THREAD

**Issue by ScootRay** [snarfed/bridgy#1015]
(I'm not sure if the protocol is to open a new issue since this the referring one is closed, please feel free to slap me with a wet noodle if I breached etiquette.)

I noticed this error seems to have snuck back for Pleroma (version 2.2). It's reporting permission errors per my log:

https://brid.gy/log?start_time=1614298087&key=agdicmlkLWd5cmYLEg1QdWJsaXNoZWRQYWdlIj9odHRwczovL2Fsb25ndGhlcmF5LmNvbS9waG90b3Mvc3Vuc2V0LW9mZi1vZi1jYW1wb2JlbGxvLWlzbGFuZC8MCxIHUHVibGlzaBiAgIi52oaJCQw

I also looked at the logs for:

> woo, fixed! https://brid.gy/mastodon/@jk@social.nipponalba.scot looks good now, sent a bunch of wms.

...and I see the same errors, whoops.

Is there anything I can do to help fix this? 

Thanks,
Ray

_Originally posted by @ScootRay in https://github.com/snarfed/bridgy/issues/977#issuecomment-786319075_

**Comment by snarfed** [comment]
Thanks for filing! Not entirely sure what's going on, but one possible theory is that Pleroma permissions (scopes) aren't sticky, and it only keeps the permissions we ask for in the most recent OAuth request. So, if we ask for the read permissions we need for listen, then write permissions for publish, and then later read permissions again, it drops the write permissions entirely. ☹️

specifically, in this case, it's saying we don't have the `write:statuses` permission, but we explicitly request (and get) that when publish is enabled:

https://github.com/snarfed/bridgy/blob/b7aee05194fdc57d4884991cd66fd578cb3560b7/mastodon.py#L24

[from the log](https://brid.gy/log?start_time=1614298087&key=agdicmlkLWd5cmYLEg1QdWJsaXNoZWRQYWdlIj9odHRwczovL2Fsb25ndGhlcmF5LmNvbS9waG90b3Mvc3Vuc2V0LW9mZi1vZi1jYW1wb2JlbGxvLWlzbGFuZC8MCxIHUHVibGlzaBiAgIi52oaJCQw):

```
Params: [('source', 'https://alongtheray.com/photos/sunset-off-of-campobello-island/'), ('target', 'https://brid.gy/publish/mastodon'), ('bridgy_omit_link', 'maybe')]
Source: https://brid.gy/mastodon/@ray@alongtheray.social , features ['listen', 'publish'], status enabled, poll status ok
Publish entity: 'agdicmlk...'
...
requests.post https://alongtheray.social/api/v1/statuses {'json': {'status': 'Sunset off of Campobello Island: https://alongtheray.com/photos/sunset-off-of-campobello-island/'}, 'headers': {'Authorization': '...'}}
Received 403
Error 403, response body: '{"error":"Insufficient permissions: write:statuses."}'
```

Not sure though.

**Comment by ScootRay** [comment]
Ah, that makes sense. It's beyond the scope of my meager abilities though, wish I could help given all you've done for the community... 

Thank you!
Ray

**Comment by snarfed** [comment]
OK, I think this is fixed now. @ScootRay try logging into your Pleroma account on https://brid.gy/ again, and then see if publish works?
