### ISSUE TITLE
Pleroma changes to OAUTH handling cause brid.gy problems

### ISSUE THREAD

**Issue by jk-na** [snarfed/bridgy#1019]
Hello,

It seems that changes in the latest pleroma release result in brid.gy not being able to recognise my server using the mastodon API.

When clicking on the buttons to enable listening or publishing, the response is that my server (social.nipponalba.scot) does not look like a mastodon server, which of course it isn't but had been functioning as one for webmentions etc. prior to the update.

I've tried looking through the commit list to see if I can find the culprit but no luck.  Not sure if it will be easily fixable but thought I'd let you know.

**Comment by jk-na** [comment]
Possibly this one.. or one around there, seems to be a bit of a focus on oauth around that time: 

https://git.pleroma.social/pleroma/pleroma/-/commit/264cb2c77f51d0caacffa6e84f631cec1131eec5

**Comment by snarfed** [comment]
Interesting! Thanks for filing. We check Mastodon API compatibility by fetching the `/api/v1/instance` endpoint and checking that it returns 200 and JSON and isn't Pixelfed. Maybe they removed that endpoint?

https://github.com/snarfed/oauth-dropins/blob/2c2fc04503ef542ee443aeb5482642a9062583c0/oauth_dropins/mastodon.py#L221-L238

**Comment by snarfed** [comment]
Hmm, https://social.nipponalba.scot/api/v1/instance is currently returning 500. Maybe your instance is unhappy somehow?

**Comment by jk-na** [comment]
Maybe, it's working for my syndication script but I don't appear to call that API so that'd be why.  I'll have a check of the changelog again and see if I've missed some breaking change!

**Comment by jk-na** [comment]
It certainly looks like a pleroma end issue.. most of the apis appear functional but `/api/v1/instance` isn't playing ball.

Raised an issue with pleroma; https://git.pleroma.social/pleroma/pleroma/-/issues/2562

**Comment by jk-na** [comment]
Confirmed as pleroma issue, thanks for the pointer.
