### ISSUE TITLE
Question on publishing from a website to a silo

### ISSUE THREAD

**Issue by jpcaruana** [snarfed/bridgy#1030]
Question on publishing from a website to a silo
When bridgy publishes to a silo (say twitter), is it possible to have the address of the published tweet ? I use webmentions.

(Originally published at: https://jp.caruana.fr/notes/2021/04/16/question-on-publishing-from-a/)

**Comment by snarfed** [comment]
Definitely! Bridgy returns JSON in response to webmentions. The url field contains the syndicated post's URL: https://brid.gy/about#response
