### ISSUE TITLE
Disable link previews by default

### ISSUE THREAD

**Issue by chrisfinazzo** [snarfed/bridgy#1031]
Taking another look at this since #934, I realized that my `h-entry` markup was in fact incorrect, which meant it was not parsed correctly and webmentions were not sent automatically. The current version is [here][] and its parsed result is at [this][] URL.

Assuming this works, is there a way to disable the link previews by default? For simple reply contexts, it feels like noise.

[here]: https://chrisfinazzo.com/wm-test2

[this]: http://pin13.net/mf2/?url=https%3A%2F%2Fchrisfinazzo.com%2Fwm-test2

**Comment by snarfed** [comment]
Yes! https://brid.gy/about#omit-link
