### ISSUE TITLE
Port from webapp2 to Flask

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1037]
Bridgy (and granary and oauth-dropins) use [webapp2](https://github.com/GoogleCloudPlatform/webapp2) as their web framework. It's old, niche, and abandoned. 

We should migrate to Flask! Except webapp2 is entrenched pretty deeply in both the three codebases and the unit tests. It would be a significant project to migrate. We'd get some small wins, eg https://github.com/GoogleCloudPlatform/webapp2/issues/152, but ROI is definitely low.

--

This is largely done! Here's what's left.

Bugs to fix:
* If the silo profile doesn't have a web site, we re-ask the user even if we're eg adding publish.  
    Evidently this is intentional, so that you can remove web sites from your Bridgy user. Details in #623.
* [x] Publish XHR doesn't work, the HTML snippet gets loaded as a new page.
* [x] Preview XHR responses have ugly _Bad Request_ header and escaped HTML content.
* [x] `/indieauth/start` (for registering browser extension users) isn't working, it keeps running the user page view instead.
* [x] `/indieauth/callback` is redirecting to `/` with no message...? Aha, we shouldn't cache the front page if there's a cookie.
* [x] Error messages from `flask_util.error()` aren't showing up in logs, eg for `/publish/webmention` requests that 400.

Manual testing:

* [x] /about
* [x] /users
* [x] /log
* [x] /admin/...
* [x] /logout
* [x] retry
* Facebook
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
* Flickr
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
  * [x] publish: preview, interactive, via wm
* GitHub
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
  * [x] publish: preview, interactive, via wm
* Instagram
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
* Mastodon
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
  * [x] publish: preview, interactive, via wm
* Meetup
  * [x] login (decline and approve), disable/re-enable features
  * [ ] publish: preview, interactive, via wm
* Reddit
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
* Twitter
  * [x] login (decline and approve), disable/re-enable features
  * [x] poll, discover
  * [x] publish: preview, interactive, via wm
* Medium
  * [x] login (decline and approve), disable/re-enable features
  * [x] send blog wm
* Blogger
  * [x] login (decline and approve), disable/re-enable features
  * [x] send blog wm
  * [ ] receive blog wm
* Tumblr
  * [x] login (decline and approve), disable/re-enable features
  * [x] send blog wm
  * [ ] receive blog wm
* Wordpress.com
  * [x] login (decline and approve), disable/re-enable features
  * [x] send blog wm
  * [x] receive blog wm

Port, get tests to pass:

* [x] admin.py
* [x] app.py
* [x] appengine_config.py
* [x] blog_webmention.py
* [x] blogger.py
* [x] browser.py
* [x] config.py
* [x] cron.py
* [x] facebook.py
* [x] flickr.py
* [x] github.py
* [x] handlers.py
* [x] indieauth.py
* [x] instagram.py
* [x] mastodon.py
* [x] medium.py
* [x] meetup.py
* [x] models.py
* [x] original_post_discovery.py
* [x] publish.py
* [x] reddit.py
* [x] superfeedr.py
* [x] tasks.py
* [x] tumblr.py
* [x] twitter.py
* [x] util.py
* [x] webmention.py
* [x] wordpress_rest.py

**Comment by Ryuno-Ki** [comment]
Do you plan to use a „feature branch” to migrate in small steps?
You could allow others for checking it out locally in case they use a local deployment.

**Comment by snarfed** [comment]
Migrating in small steps is definitely a good idea! I generally avoid long-lived feature branches, they lead to divergence and skew and merge conflicts, but we could definitely switch individual endpoint URLs to Flask one by one while the rest are still served by webapp2.

I don't personally plan to work on this soon, but I'm definitely open to contributions!

**Comment by Ryuno-Ki** [comment]
Well, I guess, the first step would be adding a Flask dependency and set up a minimal configuration (to a different port).
I avoid Google services, so don't count on me for running it locally :-(

**Comment by snarfed** [comment]
I ported Bridgy Fed to Flask recently, went fine. Still not sure if I'll do it more widely though.

**Comment by snarfed** [comment]
I'm maybe halfway through this for Bridgy, in the `flask` branch, and it has been a massive pain. No particularly hard or interesting problems, just a ton of changes. Web frameworks tend to be pretty deeply embedded in web app code, go figure.

There are bits here and there that are nicer in Flask, and the code is a bit shorter, but overall, I was right, ROI is very low. I kind of regret starting it. I'll probably keep going though, sunk cost fallacy notwithstanding. 😭

**Comment by Ryuno-Ki** [comment]
Would it be possible to break apart the task and ask the community to PR against that branch?
Do you have a checklist somewhere of things needed for porting?

**Comment by snarfed** [comment]
Definitely! It's not fun or interesting work, so I wouldn't lead with it if I went out and solicited help, but I'd gladly accept PRs against that branch. At those point, I'm just getting tests to pass, one module at a time. `publish` and `original_post_discovery` would be good next candidates!

**Comment by Ryuno-Ki** [comment]
Oh, well. Working in the industry for several years by now, I am aware, that maintenance and refactorings can be cumbersome.

A checklist could serve two purposes: keeping an overview about what's still left to do & granting some motivational boost to tick off another item.

**Comment by snarfed** [comment]
Sure! Here's the list of modules to be ported and their current status in the [`flask` branch](https://github.com/snarfed/bridgy/tree/flask):

* [x] admin.py
* [x] app.py
* [x] appengine_config.py
* [x] blog_webmention.py
* [x] blogger.py
* [ ] browser.py
* [x] config.py
* [ ] cron.py
* [ ] facebook.py
* [ ] flickr.py
* [ ] github.py
* [x] handlers.py
* [ ] indieauth.py
* [ ] instagram.py
* [ ] mastodon.py
* [x] medium.py
* [ ] meetup.py
* [ ] models.py
* [x] original_post_discovery.py
* [ ] publish.py
* [ ] reddit.py
* [x] superfeedr.py
* [ ] tasks.py
* [x] tumblr.py
* [x] twitter.py
* [x] util.py
* [x] webmention.py
* [x] wordpress_rest.py

Some are partially but not completely done, eg `browser`, `facebook`, `instagram`.

**Comment by Ryuno-Ki** [comment]
Thanks.

Give me some time to study how the tests / code used to look like and what the target architecture is.

**Comment by Ryuno-Ki** [comment]
Are the tests Python3 compatible? (I replaced the paths below)

```
======================================================================
ERROR: test_site_lookup_fails (tests.test_wordpress_rest.WordPressTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$PROJECT_ROOT/tests/test_wordpress_rest.py", line 19, in setUp
    super().setUp()
  File "$PROJECT_ROOT/tests/testutil.py", line 285, in setUp
    super().setUp()
  File "$VIRTUAL_ENV/lib/python3.7/site-packages/oauth_dropins/webutil/testutil.py", line 266, in setUp
    self.mox.StubOutWithMock(requests, method, use_mock_anything=True)
  File "$VIRTUAL_ENV/lib/python3.7/site-packages/mox3/mox.py", line 321, in StubOutWithMock
    raise TypeError('Cannot mock a MockAnything! Did you remember to '
TypeError: Cannot mock a MockAnything! Did you remember to call UnsetStubs in your previous test?
```

The whole test suite is failing.

In other words: Are there parts I could work on without signing up with Google Cloud Platform?
I forked the repo and cloned it locally already.

**Comment by Ryuno-Ki** [comment]
I have accounts on GitHub, Twitter and Wordpress.com

**Comment by snarfed** [comment]
Thanks for looking! Bridgy is definitely Python 3, and you don't need a Google account to develop or run the tests, only to deploy it to production.

The Flask port requires the head version of oauth-dropins, which is probably why the tests are failing. Try the instructions starting with _There's a good chance you'll need to make changes to granary or oauth-dropins_ in the README.

...having said all that, I actually have all the tests passing right now, and I've moved on to manual testing. Details in the top level issue description here. I'm about to deploy a version to production, I'd love help with that manual testing! I'll keep you posted.

**Comment by Ryuno-Ki** [comment]
I've got closer:

```
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_create_comment_401_disables_source (tests.test_blog_webmention.BlogWebmentionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff09e4d9e50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$VIRTUALENV/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "$VIRTUALENV/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /reset (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff09e4d9e50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$PROJECT_ROOT/tests/test_blog_webmention.py", line 19, in setUp
    super().setUp()
  File "$PROJECT_ROOT/tests/testutil.py", line 299, in setUp
    self.clear_datastore()
  File "$PROJECT_ROOT/tests/testutil.py", line 472, in clear_datastore
    orig_requests_post(f'http://{ndb_client.host}/reset')
  File "$VIRTUALENV/lib/python3.7/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "$VIRTUALENV/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "$VIRTUALENV/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "$VIRTUALENV/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "$VIRTUALENV/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /reset (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff09e4d9e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

So something with DNS? Or localhost:8089?
The `gcloud` thingy is supposed to run there …

**Comment by snarfed** [comment]
Right! The datastore emulator, the `gcloud beta emulators ...` command [here](https://github.com/snarfed/bridgy#development). Is that running successfully and listening on port 8089?

**Comment by Ryuno-Ki** [comment]
It's not running. I avoid Google.
Oh well, I'm out of luck here, it seems.
(unittest ought to run in isolation. Running against a service would make them integration tests in my opinion)

**Comment by snarfed** [comment]
Sorry for the trouble! I figured `gcloud` would let you run the datastore emulator without logging into a Google account. Does it really require that first? Disappointing if so.

**Comment by snarfed** [comment]
Done!
