### ISSUE TITLE
Twitter Video Publish failing with “Not Valid Video” error

### ISSUE THREAD

**Issue by barnabywalters** [snarfed/bridgy#1043]
Already discussed a little in IRC, collecting links and info here for tracking.

Trying to publish [this video post](https://waterpigs.co.uk/notes/5D9NcJ/) to twitter fails, resulting in a [“Not a valid video” error](https://brid.gy/log?start_time=1623678010&key=agdicmlkLWd5ckwLEg1QdWJsaXNoZWRQYWdlIiVodHRwczovL3dhdGVycGlncy5jby51ay9ub3Rlcy81RDlOY0ovDAsSB1B1Ymxpc2gYgIDIjIz6xAgM).

Uploading the exact same file to twitter works fine, so it doesn’t seem to be related to the file format, size or video length. If Bridgy is downloading the file and splitting it into segments before uploading, perhaps there’s an issue with the segment offsets or order?

**Comment by snarfed** [comment]
Thanks for filing! I think the next step here is to poll the [`STATUS` API endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/get-media-upload-status) until it returns `succeeded`, and only then try to create the tweet. I'll do that.

**Comment by snarfed** [comment]
Tentatively closing. Not sure if we're past the persistent 503 issue from Twitter's API, but I've posted a couple videos like this successfully now, so I think at least the video upload part is ok.
