### ISSUE TITLE
Allow publishing bookmarks to Twitter (and others?)

### ISSUE THREAD

**Issue by anarchivist** [snarfed/bridgy#1045]
Hi there - thanks for Bridgy! I'm seeing issues with ~some notes~ *bookmarks* on my site not posting to Twitter, but successfully posting to Mastodon for the same post.

Example: https://matienzo.org/2021/166/hudson/ (there's a lingering syndication link for posting to the Bridgy publish endpoint for Twitter)
* [Log of failed Twitter post](https://brid.gy/log?start_time=1623953667&key=agdicmlkLWd5ckwLEg1QdWJsaXNoZWRQYWdlIiVodHRwczovL21hdGllbnpvLm9yZy8yMDIxLzE2Ni9odWRzb24vDAsSB1B1Ymxpc2gYgIDIrMm8iQsM)
* [Log of successful Mastodon post](https://brid.gy/log?start_time=1623817719&key=agdicmlkLWd5ckwLEg1QdWJsaXNoZWRQYWdlIiVodHRwczovL21hdGllbnpvLm9yZy8yMDIxLzE2Ni9odWRzb24vDAsSB1B1Ymxpc2gYgIDIrIH_xwgM)

What sticks out to me from the failed Twitter post is:

```
I 2021-06-17 18:14:27.505367+00:00 Object type(s) {'h-entry'} not supported; error=Cannot publish type=activity, verb=post to Twitter; trying next.
I 2021-06-17 18:14:27.505720+00:00 Could not find content in <a href="http://microformats.org/wiki/h-entry">h-entry</a> or any other element!
```

The `h-entry` seems to be recognized by the log, however.

**Edit**: This seems to specifically impact my posts that are marked up as bookmarks, because another recent post to Twitter succeeded through Bridgy.

**Comment by snarfed** [comment]
Thanks for filing, and for the detailed info! And sorry for the unhelpful error message. Looks like this is an inconsistency on our end, we currently let you publish bookmarks to Mastodon but not to Twitter. We should allow them to Twitter too. I'll do that!

**Comment by snarfed** [comment]
Deployed a fix, feel free to try again.

**Comment by anarchivist** [comment]
Worked like a charm. Thanks, @snarfed!
