### ISSUE TITLE
Twitter login failing with “There is no request token for this page.“

### ISSUE THREAD

**Issue by barnabywalters** [snarfed/bridgy#1047]
When I try to log in to Bridgy with twitter, it prompts me for a username+password, then shows this error message at https://api.twitter.com/oauth/authorize:

<img width="750" alt="Screenshot 2021-06-20 at 09 34 36" src="https://user-images.githubusercontent.com/968350/122665983-f3364e00-d1aa-11eb-9f55-443b18bc887d.png">

**Comment by snarfed** [comment]
Huh, I can't reproduce this. If I'm logged out of Twitter, and click the Twitter button on https://brid.gy/, it sends me to `https://api.twitter.com/oauth/authorize?oauth_token=...` to log in. When I do, it POSTs to `https://api.twitter.com/oauth/authorize`, which 200s and `meta http-equiv="refresh"` redirects me back to Bridgy, and everything works.

Does it consistently reproduce for you? Any idea what might be different in your environment or browser?

**Comment by barnabywalters** [comment]
I can reliably reproduce this on Firefox. It works fine on Chrome, so looks like it could be a firefox issue. I also can’t log into reddit on FF, although that issue seems to be somewhere slightly different:

<img width="811" alt="Screenshot 2021-06-22 at 18 01 24" src="https://user-images.githubusercontent.com/968350/122961118-621acf00-d384-11eb-8864-8c6dca73f9b0.png">

**Comment by barnabywalters** [comment]
I deleted all local data for *.twitter.com, and twitter worked. Did the same for reddit but got the same result. Want me to open a separate issue for that, or keep this one?

**Comment by snarfed** [comment]
Thanks! Separate issue, I started it already.
