### ISSUE TITLE
You need webmention support (Facebook only)

### ISSUE THREAD

**Issue by bekopharm** [snarfed/bridgy#1054]
I was delighted to see Facebook support again and installed the Plugin for Chrome.

FB:
* Switched to EN just to make sure

Plugin:
* Connection seems fine and Facebook Status is: `OK`
* It also did see 5 Posts and Reactions

Bridgy shows:
* Last syndication found XY minutes ago
* Web site crawled X minutes ago
*  `No responses.` below all
* And in yellow: `You need webmention support.`
![image](https://user-images.githubusercontent.com/5016428/124797132-3b4ac400-df52-11eb-8979-6ca40ef001df.png)

My WordPress page runs with the suggested IndieWeb bundle and Webmentions work just fine for Twitter and Mastodon. I get the yellow message _only_ for Facebook.

The Webmention URL entry in the DOM is only on an article/post page, *not* on the main/index website (and I wouldn't know where to activate this anyway, has always been like this)

That's all I know. Am I doing this wrong?

`https://brid.gy/facebook/100016878457642`

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! The _You need webmention support_ banner is expected if you don't advertise your webmention endpoint on your home page. Not sure why it's not sending you any wms though, I'll look into that.

**Comment by snarfed** [comment]
Actually I see on https://brid.gy/facebook/100016878457642 that it has now sent you wms. Yay!

**Comment by bekopharm** [comment]
Oh. It just started working minutes after the report? I guess I was to eager to try this 😅😅

The warning banner is gone too 🤔 Mebbe some queue hickup.

Awesome!
