### ISSUE TITLE
toot.jeena.net doesn't look like a Mastodon instance

### ISSUE THREAD

**Issue by jeena** [snarfed/bridgy#1060]
I have my own Mastodon instance but when I try to set it up in bridgy I only get this error message:

> toot.jeena.net doesn't look like a Mastodon instance.

Which is wrong. Any idea why and what I can do to be able to set it up?

**Comment by snarfed** [comment]
Hey, yes! Looks like your Mastodon instance is a bit unhappy, it's returning 500 to GET requests (unauthenticated) to `https://toot.jeena.net/api/v1/instance`, which is the first Mastodon API endpoint Bridgy hits, to confirm that it's Mastodon and grab a bit of metadata. Background: https://docs.joinmastodon.org/methods/instance/

**Comment by snarfed** [comment]
Looks like it's not just that API endpoint, other user-facing URLs are unhappy too, eg https://toot.jeena.net/about/more

**Comment by jeena** [comment]
Aah damn. Thanks then it has nothing to do with Bridgy, I'll close this one, thanks for pointing it out!
