### ISSUE TITLE
Decommission Meetup

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1065]
Meetup has a [new GraphQL API](https://www.meetup.com/api/general) that they're getting all developers to [migrate to](https://www.meetup.com/api/migrating). They say ["RESTful API support will stop in winter 2021,"](https://www.meetup.com/meetup_api/) so we'll need to migrate sometime soon ish. 😐 cc @jamietanna

**Comment by snarfed** [comment]
Oof, got it. That's...unfortunate.

**Comment by snarfed** [comment]
Hey @jamietanna, is the GraphQL API still broken here? (Not urgent!)

**Comment by jamietanna** [comment]
Turns out it's fine their docs just don't match what's needed by the API 😬 

https://gitlab.com/jamietanna/meetup-mf2/-/merge_requests/18 is what I've done for the other app that uses the API so I'll look at what Granary needs in the new year 👍🏽

**Comment by snarfed** [comment]
Woo, good news, nice sleuthing. Thanks! Happy holidays!

**Comment by jamietanna** [comment]
Thanks Ryan you too ☺

**Comment by jamietanna** [comment]
Update from Meetup:

> REST API Brownout Periods
> As we prepare to deprecate the REST API, we will be browning it out on January 19, 2022 from 12:00pm to 6:00pm EST and January 28, 2022 from 6:00am to 6:00pm EST. REST endpoints will not work during those times.


> Actions required
> Fully update all integrations built on Meetup’s current REST API to the new GraphQL API by January 31, 2022, to avoid any disruption. After that date, our current REST API will no longer be supported, and integrations using it will not work correctly. Our Migrating from REST documentation has all the information you need to start building on GraphQL.

I'll look to get this sorted soon 🤞🏽

**Comment by jamietanna** [comment]
So in an excellent not-at-all-user-hostile means (:roll_eyes:), the new API does not _appear_ to have the ability to apply RSVPs via the new API.

For instance, we can perform a GraphQL query:

<details>

<summary>GraphQL Query</summary>

Query:

```
query ($eventId: ID!) {
  event(id: $eventId) {
    id
    title
    rsvpState
  }
}
```

Variables:

```json
{
  "eventId":"276754274"
}
```

</details>

But performing a mutation:

<details>

<summary>GraphQL Mutation</summary>

Query: 

```
mutation($input: EditEventInput!) {
  editEvent(input: $input) {
    event {
      id
    }
    errors {
      message
      code
      field
    }
  }
}
```

Variables:

```json
{
	"input": {
		"eventId": "276754274",
		"rsvpState": "YES"
	}
}
```

</details>

Unfortunately yields an error:

```json
{
  "errors": [
    {
      "message": "Variable \"$input\" got invalid value { eventId: \"276754274\", rsvpState: \"YES\" }; Field \"rsvpState\" is not defined by type \"EditEventInput\". Did you mean \"rsvpSurvey\"?",
      "locations": [
        {
          "line": 1,
          "column": 10
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
```

I'll reach out to them, but it's likely this will mean we need to retire Granary's Meetup RSVP publishing, and subsequently in Bridgy.

**Comment by snarfed** [comment]
Ruh roh.

I looked through the mutation docs on https://www.meetup.com/api/schema/#p02-mutations-section , and you're right, lots of event and group editing, but no RSVPing. Same with examples and client libraries like https://github.com/tsuki42/graphql-meetup . Disappointing, but does make sense if they're aiming the API at businesses and event organizers.

Good call on asking them. Maybe also see if there are API developer groups or forums anywhere?

Otherwise, agreed, we can decommission it. Sad!

**Comment by jamietanna** [comment]
Do we know how many folks currently use it and would be affected, at least on Bridgy?

**Comment by snarfed** [comment]
Yes! I looked at this a few months ago, and it's pretty similar now. Not too many. 41 users, 9 have tried publish in some form, 3 have actually completed and published real RSVPs to Meetup: you (https://brid.gy/meetup/189380737), @chrisaldrich (https://brid.gy/meetup/5980250), and @ngm (https://brid.gy/meetup/14451814).

**Comment by snarfed** [comment]
@jamietanna any word back from Meetup people or other external developers on whether their GraphQL supports RSVPing?

**Comment by jamietanna** [comment]
Unfortunately not, and I'm still not getting responses to other requests, so I think let's proceed with the decommission :disappointed:

**Comment by snarfed** [comment]
Sad! But understood.

No hurry! I'm happy to leave it up and running until they actually turn off the REST API.

**Comment by snarfed** [comment]
Looks like Meetup is 401ing REST API requests now ([example](https://brid.gy/log?start_time=1647086414&key=agdicmlkLWd5ckwLEg1QdWJsaXNoZWRQYWdlIiVodHRwczovL3d3dy5qdnQubWUvbWYyLzIwMjIvMDMvamV5bzYvDAsSB1B1Ymxpc2gYgIDo2OTQiQkM)), guess it's time to start decommissioning.

**Comment by snarfed** [comment]
I took one last look at forums etc. The official mailing list has been defunct since 2019, https://groups.google.com/g/meetup-api . discussmeetup.com doesn't have anything on the API since 2019 either, https://www.discussmeetup.com/forum/search2/ .

**Comment by snarfed** [comment]
Disabled all existing Meetup accounts with:

```py
env APP_ID=brid-gy GOOGLE_APPLICATION_CREDENTIALS=service_account_creds.json python
...
from oauth_dropins.webutil import appengine_info
appengine_info.DEBUG = False
appengine_info.APP_ID = os.environ['GAE_APPLICATION'] = 'brid-gy'
import appengine_config
from oauth_dropins.webutil import appengine_config

from meetup import Meetup

with appengine_config.ndb_client.context():
  for m in Meetup.query():
    m.features = []
    m.put()
```
