### ISSUE TITLE
Twitter likes fail

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#1066]
Need a bit of help to understand if the issue is on my end or on bridgy's side. I'm not sure if it's a timing thing or related to my latest blog post, but either way, since this morning all webmentions to my latest post don't come through and show as failed on my listing: [https://brid.gy/twitter/islayblog](https://brid.gy/twitter/islayblog)

I had a look at the logs (eg [this one](https://brid.gy/log?start_time=1630243411&key=agdicmlkLWd5ck4LEghSZXNwb25zZSJAdGFnOnR3aXR0ZXIuY29tLDIwMTM6MTQzMTQ3NzY5NzM2OTI4MDUxM19mYXZvcml0ZWRfYnlfMzM4NjA0MzI5MQw)) but I'm not sure if the cannot find target link error 400 is on my side or on bridgy's end (unfortunately my coding and log reading skills are basic). The post on my blog does exist, as does the endpoint on my blog.

Any help/guidance appreciated.

**Comment by snarfed** [comment]
Thanks for the report, and sorry for the trouble! I see the problem, it's due to #1037. Should be a straightforward fix.

**Comment by snarfed** [comment]
OK, should be fixed. Thanks again for the heads up!

**Comment by armingrewe** [comment]
Yes, coming all through now, thanks for fixing so quickly!
