### ISSUE TITLE
Liking/replying my own tweet for one specific post doesn't send webmention

### ISSUE THREAD

**Issue by thiagomgd** [snarfed/bridgy#1081]
I have this post where I liked my own tweet, and the webmention worked fine: https://geekosaur.com/post/checking-your-anime-recs-and-favorites-oct.-2021/ (the tweet: https://twitter.com/FalconSensei/status/1453049051239362568)

But for this other post, I replied and liked, but didn't get a webmention. I liked it using another profile, and for that other, it worked. (post: https://geekosaur.com/post/horror-book-recommendations/, tweet: https://twitter.com/FalconSensei/status/1452339362935549965)

Both of the posts were created and shared in the same way, so there shouldn't be any difference in behaviour - either my own likes count as webmention, or they don't :/

**Comment by snarfed** [comment]
Hi! Interesting, looks like this may have been a webmention.io hiccough.

https://brid.gy/twitter/FalconSensei showed that Bridgy actually did send both likes on your second tweet. Here's the log of it originally sending the one from FalconSensei: https://brid.gy/log?start_time=1635653939&key=agdicmlkLWd5ck4LEghSZXNwb25zZSJAdGFnOnR3aXR0ZXIuY29tLDIwMTM6MTQ1MjMzOTM2MjkzNTU0OTk2NV9mYXZvcml0ZWRfYnlfMTgzNTg0ODcyMww

webmention.io returned 201, but it evidently didn't stick. https://webmention.io/api/mentions.jf2?target=https://geekosaur.com/post/horror-book-recommendations/ only returned the one like from weeb_sensei.

I clicked the retry button on https://brid.gy/twitter/FalconSensei for that like, and that evidently did the trick. I now see it on https://geekosaur.com/post/horror-book-recommendations/ . 🤷

**Comment by thiagomgd** [comment]
Oh, thanks. I just saw that now the like stuck there!

Now, regarding replies. Should those 2 tweets have triggered a webmention? I'm not sure if by default my own replies are ignored or not:
- Just text reply: https://twitter.com/FalconSensei/status/1454666716420526080
- Reply that includes link to another blog: https://twitter.com/FalconSensei/status/1454660222480388096

Bridgy marked both as having no webmention target:

![image](https://user-images.githubusercontent.com/12170252/139570445-3294b19b-91b9-46b3-be54-d4aed85486e4.png)

**Comment by snarfed** [comment]
Ah right, no, your replies to your own tweets aren't backfed. Your replies to other people are though!

You're welcome to backfeed them yourself if you want though, using Bridgy's rendering. Details: https://brid.gy/about#source-urls . eg here the source page is https://brid.gy/comment/twitter/FalconSensei/1452339362935549965/1454660222480388096

**Comment by snarfed** [comment]
(The common case here is that people POSSE posts as threads, so we avoid backfeeding replies that are likely to be _part_ of the original post, not responses to it.)

**Comment by thiagomgd** [comment]
Oh, thank you so much for your explanation!!!
