### ISSUE TITLE
How does publish work?

### ISSUE THREAD

**Issue by mark4409** [snarfed/bridgy#1087]
More of a support request I think rather than an issue. I'm using a blog with support for micropub and webmentions. I've set up webmentions and publishing on brid.gy to twitter and pleroma. On both, all it's publishing is the blog title and a link. Is this normal behaviour or should it also be posting a summary or description? If posting a micro post on my blog, I was hoping for the whole post to be published on Twitter. Am I missing something or is this not how brid.gy works?

**Comment by snarfed** [comment]
Sorry for the confusion! This is indeed how Bridgy works, at least for posts with titles, publishing to places with length limits like Twitter and Mastodon. If a post doesn't have a title, Bridgy will publish the full contents, truncated (with ellipsis) if necessary. [More background here.](https://brid.gy/about#microformats)

**Comment by mark4409** [comment]
Thanks for the reply - I've just tested again without a title and this works as I want. Does the same apply also to publishing to Facebook via the browser addon?

**Comment by snarfed** [comment]
Great! The browser extension doesn't support publish to Facebook or Instagram, sadly, just backfeed.

**Comment by snarfed** [comment]
Closing. Feel free to reopen!
