### ISSUE TITLE
Thx for a great service ! 😁🙏🏻 - but - Twitter "likes" ? 

### ISSUE THREAD

**Issue by jalsco** [snarfed/bridgy#1088]
Brig.dy is seriously amazing !  thank you  ! So quick and seemles - all auto setup - works great straight out of the box 😊

I've built my first blog (Pelican) for my "client" 👍, as I'm still learning , no money involved (yet).  Anyway, the blog looks good.. the webmention-feed looks good  ( thx to bridgy and webmention.io) . The client is happy, I have  learned a mountain of stuff. & setting up bridgy and webmention was the easiest part ! 

I noticed the site is receiving Twitter-shares and random commentpara.de  messages.  BUT - even I go in myself onto one of their test tweets and hit - LIKE ❤ - no "like" comes onto the webmention feed.  

Is this a common problem? Did I miss a step?  Are Twitter "likes❤" not supported by Brid.gy ?  

Any advice and/or suggestions welcome

**Comment by snarfed** [comment]
Thanks for the kind words, and sorry for the trouble! Likes are definitely supported. Happy to look into this. What's their Bridgy user page? Does it show any of the likes?

**Comment by jalsco** [comment]
thanks!  Nothing showing on webmention.io page.  Am searching for the Brid.gy page but am not seeing it there.... Could be just that my coffee is not yet working this morning. #checking_further

**Comment by snarfed** [comment]
What's the web site or Twitter username?

**Comment by jalsco** [comment]
may I pm you that please - as the client has not launched publicly
BTW - thanks for your responsiveness

**Comment by snarfed** [comment]
Sure! Go for it.

**Comment by jalsco** [comment]
sent via email

**Comment by snarfed** [comment]
Thanks! Looks like the Twitter account you signed up hasn't actually posted any tweets. Only likes on the signed up account's tweets are backfed to the web site.

**Comment by snarfed** [comment]
More background: https://brid.gy/about#backfeed

**Comment by jalsco** [comment]
Wait - only likes *ON* the Brid.gy signed up twitter account -  show up in the feed ? 

So - somebody (random public)  shares to twitter and other people "like" their share... those  "likes" are not supposed to show up.  

So if that;s true - I some more work to do to setup bridgy publishing and backfeed. Thanks for explaining !

**Comment by snarfed** [comment]
Correct!

**Comment by jalsco** [comment]
So for "likes" to be significant - still need to build a twitter following and actively engage in that silo....  Just am thinking out loud.  😁
