### ISSUE TITLE
"No webmention targets" error when there are some.

### ISSUE THREAD

**Issue by tunetheweb** [snarfed/bridgy#1092]
Trying to figure out why some of the webmentions are not being recognised.

For example [this tweet](https://twitter.com/stefanjudis/status/1466700685580423171) was spotted by Bidgy:

![image](https://user-images.githubusercontent.com/10931297/144590590-464dddb5-12f8-4db9-9af4-9159266bf484.png)

However it says "No webmention targets found" but [the linked page](https://almanac.httparchive.org/en/2021/javascript#how-much-javascript-do-we-load) has the webmention URL:

```html
<link rel="webmention" href="https://webmention.io/almanac.httparchive.org/webmention" />
<link rel="pingback" href="https://webmention.io/almanac.httparchive.org/xmlrpc" />
```

And the Twitter profile has that domain on it:

![image](https://user-images.githubusercontent.com/10931297/144590912-61984ff1-67e9-4e20-8314-3858354818bb.png)

Some webmentions for this account are making it through, but a large amount are not - similar to above example.

A couple of things I noticed which might be affecting us here:
- The Twitter profile URL was entered without the scheme (`almanac.httparchive.org`) and I'm wondering if that causes a problem if the link is an https link? But other links using HTTPS are working.
- The link has a hash component. Does that cause any problems? Can't seem to find any webmentions with hash URLs so maybe that's it?

Any other ideas how of to debug this?

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Not entirely sure what's going on here yet, but the author of that tweet is also a Bridgy user, so I suspect some bad interaction between the two sides. I'll keep you posted.

**Comment by tunetheweb** [comment]
Oh interesting! Maybe that's it. Let me know if you need anything else from me. As I say, seeing this for quite a lot of Tweets so not just that one.

**Comment by snarfed** [comment]
Thanks! You can see on `https://brid.gy/twitter/[username]` if someone's a Bridgy user, eg https://brid.gy/twitter/stefanjudis here. If you see any from people who aren't Bridgy users, definitely let me know, that would be useful info!

**Comment by tunetheweb** [comment]
I don’t think it is that. Here’s another tweet that has no webmention targets but the user is not a Bridgy user: https://twitter.com/alonkochba/status/1466092485957070858?s=21

**Comment by snarfed** [comment]
That original tweet actually was backfed. Second from the bottom here (for now): https://brid.gy/twitter/HTTPArchive?responses_before=2021-12-04T17:48:23.280775#responses . The "No webmention targets" responses are likes and retweets of that tweet, which aren't backfed because the original tweet wasn't from your account.

It's definitely confusing that they show up on your Bridgy page, though. I'll fix that!

**Comment by tunetheweb** [comment]
Oh that's interesting. The original tweet was not originally picked up (the tweet is from 1st December and was picked up on 4th December). I used "Resend for post" for that Tweet to ensure it was the same "no webmention targets" error message before. responded here (then read the wrong one!). So looks like the recrawl kicked that one into life. So a different problem than the one we're discussing here. Any ideas why it missed it first time round? Or is that a best efforts basis and not unexpected to miss Tweets unless we're directly mentioned?

**Comment by snarfed** [comment]
Sadly yes, Twitter's search API itself (v1 at least) is best effort only. It's generally pretty good, but we do see it miss results occasionally, and this may be one of those cases. More details: https://brid.gy/about#Twitter+responses

 v2 may be better, but they still haven't opened it for (re-)approval yet. Fingers crossed that happens soon.

**Comment by snarfed** [comment]
Tentatively closing as due to Twitter's search API. Feel free to reopen!
