### ISSUE TITLE
Backfeeding of Mastodon faves / likes / boosts

### ISSUE THREAD

**Issue by waweic** [snarfed/bridgy#1096]
Hi, i'm currently trying out brid.gy to POSSE content on my new Blog over to Mastodon and backfeed replies.
This works really well, but I have a small problem. Brid.gy is not just forwarding replies, but also faves/likes and boosts. This might be a very nice feature for some, but I would like to deactivate it, as there is no obvious way for the people reading my notes / toots to know that their (private) likes are (publicly) displayed on my Blog.
Is there a way to do so that I am missing??

**Comment by snarfed** [comment]
Hey, glad it's working well! And sorry, no, there's currently no way to only enable certain types of webmentions, and not others, but you can always just not display likes or boosts on your site.

**Comment by waweic** [comment]
Hi, thanks for your prompt answer, i might have to look a bit further, then

**Comment by snarfed** [comment]
Good luck! Tentatively closing, feel free to reopen.
