### ISSUE TITLE
Piwigo support

### ISSUE THREAD

**Issue by xplosionmind** [snarfed/bridgy#1105]
Flickr is supported in Bridgy, but [Piwigo](https://piwigo.org) no… it would be great if it was!

**Comment by snarfed** [comment]
Hmm, interesting! I'm not very familiar with Piwigo. It looks like it's a self-hosted web server for photo galleries, not a social network. How would you expect Bridgy to support it?

**Comment by xplosionmind** [comment]
> How would you expect Bridgy to support it?

I do not really know, but it is known to be the most common ethical, self-hosted, and open-source alternative to Flickr, that is supported.

**Comment by snarfed** [comment]
Right, it sounds great! Bridgy uses the webmention standard (https://webmention.net/) to connect to web servers. Maybe you want a webmention plug-in for Piwigo?

**Comment by xplosionmind** [comment]
> Maybe you want a webmention plug-in for Piwigo?

It would be wonderful

**Comment by snarfed** [comment]
Sounds good. Good luck, let us know if you find one or make one!
