### ISSUE TITLE
Cannot  add webmentions to Medium

### ISSUE THREAD

**Issue by Potherca** [snarfed/bridgy#1109]
When I try to connect Medium, I get the "Sorry, that user was not found." page.

The URL in the browser is:

```
https://brid.gy/medium/choose_blog?state=%257B%2522feature%2522%253A%2522webmention%2522%252C%2522operation%2522%253A%2522add%2522%257D&code=e78bf5b3f6b3
```

When I try in a private/incognito window, after login in to Medium, I get this:

![image](https://user-images.githubusercontent.com/195757/151385171-b9a2cbb3-a5bd-4adf-81bd-87be423161c9.png)

The URL in the browser at that point is:

```
https://medium.com/m/oauth/authorize?client_id=26a50e2df83e&scope=basicProfile%2CbasicProfile%2ClistPublications&redirect_uri=https%3A%2F%2Fbrid.gy%2Fmedium%2Fchoose_blog&state=%7B%22feature%22%3A%22webmention%22%2C%22operation%22%3A%22add%22%7D&response_type=code&source=login----------------------------------------
```

Not sure what is going on... API change on the Medium side? Something weird with encoding? No idea... 😳 

Anyway, any help with this would be  much appreciated. I'd love to start using WebMentions!

**Comment by snarfed** [comment]
Ruh roh! Sorry for the trouble, will look.

**Comment by snarfed** [comment]
Fixed! Thanks for reporting!

**Comment by Potherca** [comment]
Just tested, works fine. Thanks!
