### ISSUE TITLE
Manual share of a tweet (adding it to a thread) didn't send webmention

### ISSUE THREAD

**Issue by thiagomgd** [snarfed/bridgy#1124]
I have this tweet (https://twitter.com/FalconSensei/status/1493678663723720705) that got the correct webmentions for shares and likes.
But then it was added to a thread (https://twitter.com/fubits/status/1494256000613900293), and that didn't send a webmention. 
My reply that tweet however (https://twitter.com/FalconSensei/status/1494358075280556033), sent a webmention. 

share: 
![image](https://user-images.githubusercontent.com/12170252/154741420-b0d4481d-6111-4aff-b32d-5919ba984577.png)

my response:
![image](https://user-images.githubusercontent.com/12170252/154740434-b1aaf617-42b7-46c0-9c1e-c0d6acc87947.png)

I've tried resending the webmention with https://brid.gy/repost/twitter/falconsensei/1493678663723720705/1494256000613900293, but that didn't work

**Comment by snarfed** [comment]
Hmm. Thanks for reporting, and sorry for the trouble!

Not sure what's going on here. [This poll originally found the quote tweet](https://brid.gy/log?start_time=1645176427&key=agdicmlkLWd5chkLEgdUd2l0dGVyIgxGYWxjb25TZW5zZWkM), 2022-02-18 09:27:07 UTC. OPD log snippet looks like it found the original post https://geekosaur.com/post/eleventy-notion-notes-section/ ok:

```
D 2022-02-18 09:27:12.242310+00:00 discovering original posts for: https://twitter.com/fubits/status/1494256000613900293
...
I 2022-02-18 09:27:12.582976+00:00 Original post discovery found original posts set(), mentions {'https://twitter.com/FalconSensei/status/1493678663723720705', 'https://twitter.com/FalconSensei'}
I 2022-02-18 09:27:12.583246+00:00 Demoting original post links because user tag:twitter.com,2013:FalconSensei doesn't match author id tag:twitter.com,2013:fubits username fubits
D 2022-02-18 09:27:12.583396+00:00 running original post discovery on attachment: tag:twitter.com,2013:1493678663723720705
D 2022-02-18 09:27:12.583514+00:00 discovering original posts for: https://twitter.com/FalconSensei/status/1493678663723720705
...
I 2022-02-18 09:27:13.092744+00:00 Original post discovery found original posts {'https://geekosaur.com/post/eleventy-notion-notes-section/'}, mentions {'https://twitter.com/NotionHQ', 'https://twitter.com/eleven_ty'}
I 2022-02-18 09:27:13.093939+00:00 starting posse post discovery with syndicated https://twitter.com/FalconSensei/status/1493678663723720705
D 2022-02-18 09:27:13.135503+00:00 original post discovery found originals for attachment, {'https://geekosaur.com/post/eleventy-notion-notes-section/'}
I 2022-02-18 09:27:13.136848+00:00 starting posse post discovery with syndicated https://twitter.com/fubits/status/1494256000613900293
I 2022-02-18 09:27:13.172144+00:00 skipping refetch h-feed. last-syndication-url None, last-refetch 2022-02-15 23:03:58.964505
```

...but it's not in the `Response` entity [`tag:twitter.com,2013:1494256000613900293`](https://console.cloud.google.com/datastore/entities;kind=Response;ns=__$DEFAULT$__/edit;key=0%2F%257C8%2FResponse%257C45%2Fname%253Atag%253Atwitter.com%252C2013%253A1494256000613900293?project=brid-gy) in the datastore.

That response looks fine otherwise though. Trimmed down `response_json` is:

```json
{
  "verb": "post",
  "object": {
    "id": "tag:twitter.com,2013:1494256000613900293",
    "objectType": "note",
    "url": "https://twitter.com/fubits/status/1494256000613900293",
    "attachments": [{
      "id": "tag:twitter.com,2013:1493678663723720705",
      "url": "https://twitter.com/FalconSensei/status/1493678663723720705",
      "tags": [
        "...",
        {
          "objectType": "article",
          "url": "https://geekosaur.com/post/eleventy-notion-notes-section/",
          "displayName": "geekosaur.com/post/eleventy-…",
          "startIndex": 84,
          "length": 29
        }
      ],
      "content": "How to write notes on @NotionHQ and publish on your blog with @eleven_ty  #eleventy geekosaur.com/post/eleventy-…"
    }],
    "content": "Uh, @FalconSensei has a really nice getBlock() approach and local asset caching (among many other gems) here: ",
    "..."
  }
}
```

Also responses to the quote tweet are getting propagated fine, both comments and likes, as mentioned in the original report above.

Hrmph.

**Comment by thiagomgd** [comment]
> Thanks for reporting, and sorry for the trouble!

No problem, thanks for looking into that. And no worries, I think this is the first time something was attached to a thread instead of just being QRT'd.

**Comment by snarfed** [comment]
Oh, by attached to a thread, you mean quote tweeted in a reply instead of an original tweet? Good point! I'll look at that.

**Comment by thiagomgd** [comment]
Yeah, if you look at https://twitter.com/fubits/status/1494256000613900293, seems like they copied my tweet url, and then wrote a reply to their own thread including the link to my tweet.

**Comment by snarfed** [comment]
Thanks again for filing this, and for the followup! It helped track down a subtle bug. Should be fixed now!
