### ISSUE TITLE
Reddit backfeed appears reversed

### ISSUE THREAD

**Issue by reiterate-app** [snarfed/bridgy#1135]
Thanks for fixing the reddit backed issue. However there appears to be a new issue.

I now see a list of reddit comments that bridgy has found, but they are in reverse order. That is, on the first page I see the oldest posts and comments. If I click the "Older->" button it actually takes me to newer comments, and if I keep clicking it I eventually get to the last page, which has the most recent comments.

**Comment by snarfed** [comment]
Sorry for the confusion! Responses on https://brid.gy/reddit/rattroupe aren't perfectly ordered by timestamp, but by when Bridgy found them. Looks like it found pretty much all of those comments at the same time. Going forward, new comments will show up at the top as Bridgy finds them.
