### ISSUE TITLE
[Twitter Publish] Alt text appears to be trimmed

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#1175]
I've just noticed that i.e. on [this tweet](https://twitter.com/JamieTanna/status/1511989846008639488) the alt text is trimmed to:

> Black Cat's face framed in a window of a grey hidey hole in his...

Whereas [the post](https://www.jvt.me/mf2/2022/04/rzbbo/) has:

> Black Cat's face framed in a window of a grey hidey hole in his tower, looking a little bit crabby

I wonder if there's something in the API to tweak to not trim the alt text?

**Comment by jamietanna** [comment]
See also https://brid.gy/log?start_time=1649402638&key=agdicmlkLWd5ckwLEg1QdWJsaXNoZWRQYWdlIiVodHRwczovL3d3dy5qdnQubWUvbWYyLzIwMjIvMDQvdXd5eTkvDAsSB1B1Ymxpc2gYgIDo0uT8gwkM for a recent tweet creation

**Comment by jamietanna** [comment]
Yep, looks like something Granary is doing https://github.com/snarfed/granary/blob/db58da109e80103464226b1ad8a40e6e8d6cf9cc/granary/twitter.py#L933-L935

**Comment by jamietanna** [comment]
I've found the cause will be raising a Granary PR shortly

**Comment by snarfed** [comment]
🎉
