### ISSUE TITLE
Twitter signup 404s in India

### ISSUE THREAD

**Issue by RitikPatni** [snarfed/bridgy#1192]
Clicking on the twitter link to authenticate bridgy ends up at a 404 page as shown in the screenshot

![image](https://user-images.githubusercontent.com/16117262/167305078-1f49b628-dce5-492e-b909-0a7cb5edb6fb.png)

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! I see a few Twitter login attempts from the same IP between 16:13 and 16:17 UTC today that didn't make it all the way through, I'm guessing those were you.

Oddly though, I can't reproduce this. Tried with multiple accounts and browsers. [Neither could a couple other people on #indieweb who tried too.](https://chat.indieweb.org/2022-05-08#t1652028023828100) Could you post the URL in your browser when you get this 404 error? (And redact any tokens or codes in it?)

**Comment by RitikPatni** [comment]
@snarfed Sure 
https://api.twitter.com/oauth/authorize?oauth_token=UP837AAAAAAASyT_AAABgKSSyCo

**Comment by RitikPatni** [comment]
@snarfed  Sure
https://api.twitter.com/oauth/authorize?oauth_token=OAUTH_TOKEN

**Comment by snarfed** [comment]
Thanks! Oh, and which browser, version, and OS are you on? And are you running any extensions that might affect this, etc?

**Comment by RitikPatni** [comment]
@snarfed 
I've tried on Firefox 101 and Chrome 101 on macOS

**Comment by snarfed** [comment]
Really odd. That is the right URL. Maybe there's something unusual about your Twitter account? Can't think of what that would be, though, especially if we haven't seen this before now.

**Comment by RitikPatni** [comment]
@snarfed 

Can this be something related. This is what I see when I try to login from webmention.io website indieauth.com
![image](https://user-images.githubusercontent.com/16117262/167307622-52812eb1-eaa2-438c-ba0a-7876f20c6017.png)

**Comment by RitikPatni** [comment]
The twitter link is not working for me from any browser, not sure why because on other browsers it's not even connected to any of my accounts yet(I haven't yet logged in to twitter on Safari or Chrome). If this was something account specific, then this should have worked fine there

**Comment by snarfed** [comment]
Thanks! That's a useful data point. But still, even in an incognito window, that same URL (with different token) works for me. So odd.
<img width="672" alt="image" src="https://user-images.githubusercontent.com/778068/167308477-96c3e8dc-cbde-4cee-98e7-e66124a12905.png">

And good eye on webmention.io, but that's different, due to Twitter dropping rel-me links many years.

**Comment by ritikpatni1** [comment]
After trying in many browsers and devices that were available with me, I finally tried in TOR Browser and there it is working as you shared. I'll check with other people in my region to figure out if it has something to do with region.

**Comment by RitikPatni** [comment]
@snarfed I asked a friend to verify it who is in no way connected to my network except one common thing country. And he is also getting the same thing.

So is it possible that this is related to region?

**Comment by snarfed** [comment]
Yes! Great hunch, it probably is region specific. I'll not familiar with region settings for Twitter API apps, but I'll look.

**Comment by snarfed** [comment]
Out of curiosity, if you change your account's country manually, does that help? https://help.twitter.com/en/managing-your-account/how-to-change-country-settings

**Comment by snarfed** [comment]
I don't see any region settings i can control for my app in https://developer.twitter.com/en/apps, and I haven't found anything online about regions in the API in a few quick searches.

**Comment by RitikPatni** [comment]
> Out of curiosity, if you change your account's country manually, does that help? https://help.twitter.com/en/managing-your-account/how-to-change-country-settings

Don't think it can be that, as it is happening even when I'm not logged in

**Comment by RitikPatni** [comment]
I don't think this is an issue at your end, I've read the docs and tried on [Feedly](https://feedly.com/) and there also it's the same thing.

**Comment by snarfed** [comment]
Agreed, other API developers are reporting the same thing, evidently started within the last few days: https://twittercommunity.com/t/error-when-authorize-twitter-nothing-to-see-here/170967

**Comment by snarfed** [comment]
Twitter says they fixed this. Let me know if you're still seeing it!
https://api.twitterstat.us/incidents/c1qxf8zk63tg
https://twittercommunity.com/t/error-when-authorize-twitter-nothing-to-see-here/170967/25?u=schnarfed

**Comment by RitikPatni** [comment]
Working for me now 👍
