### ISSUE TITLE
Is there a way to see the outgoing webmention requests brid.gy sends for syndicated posts?

### ISSUE THREAD

**Issue by davidcelis** [snarfed/bridgy#1195]
I'm still new to brid.gy so sorry if I'm just missing something, but I'm trying to figure out an issue with my very first syndicated cross-post on my micro.blog site: https://davidcel.is/2022/05/08/going-out-to.html

Brid.gy correctly polled and sent the replies I'd received and I can see them as comments there (yay!) but their timestamps are being shown as when the webmention was received rather than when the replies were actually posted on twitter. bridgy's help docs say that they send a `dt-published` property for webmentions but I was hoping to see the logs for these webmention requests before I open an issue with micro.blog so that I can get them as much info as possible.

I clicked through to the log for the most recent webmention (https://brid.gy/log?start_time=1652107865&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTUyMzY0NzA4Njk3MzMyNTMxMww) but it just has a link to GCP that I (very reasonably) don't have permission to view 😅 Are there visible logs anywhere else on brid.gy? I don't manage the micropub endpoint for my own blog so I unfortunately can't see the requests there. If the outgoing requests from brid.gy were visible on brid.gy, that would be super helpful for debugging!

**Comment by snarfed** [comment]
Glad you found the logs! They have the link to  the source mf2 + HTML page that Bridgy generates, which is where you want to look. Eg [in this log](https://brid.gy/log?start_time=1652066284&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTUyMzQ3MTA1MTEyMzg3OTkzNgw), this line:

```
D 2022-05-09 03:18:03.946160+00:00 webmention send: https://brid.gy/comment/twitter/davidcelis/1523434725448159233/1523471051123879936 -> https://davidcel.is/2022/05/08/going-out-to.html
```

shows the webmention source URL as https://brid.gy/comment/twitter/davidcelis/1523434725448159233/1523471051123879936 . If you look at its mf2 in eg https://pin13.net/mf2/?url=https://brid.gy/comment/twitter/davidcelis/1523434725448159233/1523471051123879936 , it shows its `dt-published` as `2022-05-09T01:12:57+00:00`, which [matches the tweet](https://twitter.com/davidcelis/status/1523508444287750145).

**Comment by snarfed** [comment]
A couple caveats though. First, [Bridgy only includes `dt-published` if the silo itself exposes it](https://brid.gy/about#order). Twitter, for example, exposes it for tweets, but not likes. Second, Bridgy's log fetching is flaky right now, I'll work on that.

**Comment by davidcelis** [comment]
Perfect, thank you! I opened up a [topic](https://help.micro.blog/t/micro-blog-isnt-respecting-the-dt-published-property-of-webmentions-from-brid-gy-and-other-oddities/1002) in Micro.blog's help forum and hopefully they can get this issue fixed and use `dt-published` instead of the time of the webmention request!
