### ISSUE TITLE
Connecting a new twitter account for a new website disconnects a previous connection to twitter

### ISSUE THREAD

**Issue by MegaKeegMan** [snarfed/bridgy#1204]
We think that connecting [Brid.gy](http://brid.gy/) to a new Twitter account for a different website disconnected a previous connection to Twitter. Is that a possibility? Tangentially related to #1194 and maybe directly related to #38 feature request.

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! Which accounts were these, and when? Happy to look into it.

**Comment by MegaKeegMan** [comment]
I responded in an email but writing here as well:
"Wow thanks for the immediate response. We are working with the twitter accounts for agaric.coop and portside.org (@agaric and @PortsideOrg)" - me

I think our connection for Portside dropped on the 12th or 13th

**Comment by snarfed** [comment]
Ah, different Twitter accounts. @PortsideOrg disconnecting should be unrelated to @agaric. If you log into Bridgy with @PortsideOrg again, or just click the yellow pause button on https://brid.gy/twitter/PortsideOrg, that should reconnect it.

**Comment by MegaKeegMan** [comment]
This does not seem to have worked. I did click the button and "authorize app" from the Twitter api, but after failing to post again, and returning to this page, the yellow pause button has returned and tells me that the app has been disconnected from Twitter. Perhaps this is actually a problem with Twitter.

**Comment by MegaKeegMan** [comment]
Okay I did a little more investigation. FYI we are using https://www.drupal.org/project/indieweb
Each time a failure has occurred, it has followed a some time of successful syndications.

Whenever the first failure occurs, we see this message in our error logs:
```
Error sending webmention for https://portside.org/2022-05-12/olga-dies-dreaming to https://brid.gy/publish/twitter: Client error: `POST https://brid.gy/publish/webmention` resulted in a `400 Bad Request` response: { "error": "Error: {\"request\":\"\\/1.1\\/statuses\\/update.json\",\"error\":\"Read-only application cannot POST.\"} (truncated...) 
```
subsequent failed posts, however, contain a different error message:
```
Error sending webmention for https://portside.org/2022-05-13/ideas-postpone-end-world to https://brid.gy/publish/twitter: Client error: `POST https://brid.gy/publish/webmention` resulted in a `400 Bad Request` response: { "error": "Publish is not enabled for your account. <a href=\"https://brid.gy/\">Try signing up!</a>" } 
```

So it seems that somehow after the "Read-only application cannot POST." error, somehow twitter gets disconnected...

**Comment by MegaKeegMan** [comment]
Will try that in the future if we experience a break again. For now, things seem to be working again.

**Comment by MegaKeegMan** [comment]
:shrug:

**Comment by snarfed** [comment]
Sounds good, glad it's working again!
