### ISSUE TITLE
bridgy responses always with "No webmention targets" (used to work a while ago)

### ISSUE THREAD

**Issue by BorisTheBug** [snarfed/bridgy#1260]
First of all: thank you for your plugins, they are really great and helpful!

A few months ago I installed webmentions on my blog (fastlaners.de). It worked for a while and I received all my webmentions from twitter including webmention targets. I am not sure what happened, but in the last weeks this did not work for me anymore. I still receve the responses in brid.gy, but it always states that there are "no webmention targets".
Can you assist me in this? I have no idea what I am doing wrong or not seeing here.

Twitter account: https://twitter.com/Fastlaners1
Blog: https://fastlaners.de/
Old blog post where I correctly received a few web mentions: https://fastlaners.de/3-gruende-warum-du-mit-bitcoin-nicht-reich-wirst/

Any help is highly appreciated :-)

Thank you and have a nice day.

![image](https://user-images.githubusercontent.com/62843263/179391655-d2eb7cb9-c7e8-4a28-ad2f-85d1a1a3dbb8.png)

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! I don't actually see your account any more, did you disable it? https://brid.gy/twitter/Fastlaners1

**Comment by BorisTheBug** [comment]
It works with a small "f"
[https://brid.gy/twitter/fastlaners1](url)

**Comment by snarfed** [comment]
Ah, thanks! And thank you for reporting, this was indeed a bug, due to the changes we rolled out for #884. Easy fix, your webmentions are working again!
