### ISSUE TITLE
(#12) singular published story API is deprecated for versions v2.4 and higher

### ISSUE THREAD

**Issue by ob1vanq** [snarfed/bridgy#1280]
I send 

**https://graph.facebook.com/v14.0/17814849610/media?image_url=https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg
&is_carousel_item=true
&access_token=<token>**

But it not working

**Comment by snarfed** [comment]
Sorry, I don't understand. Can you add more information? What's your Bridgy user page URL or Facebook username? What are you trying to do.

**Comment by ob1vanq** [comment]
I'm trying to use an API to post to my instagram account. It seems that this error indicates that I do not have rights to use the API. 

I registered in Graph API Explorer to get permission and changed my account type to "business account", but when using this method:

POST _/{ig-user-id}/media_  
to load an image into the carousel,  I still get the error, this time this one:

> (#100) Tried accessing nonexisting field (instagram_business_account) on node type (Application)

**Comment by snarfed** [comment]
Sounds like you're in the wrong GitHub project, Bridgy doesn't offer posting to Instagram. Are you looking https://developers.facebook.com/community?category=1682619081946621 ?
