### ISSUE TITLE
Missing Likes and Repost from Twitter

### ISSUE THREAD

**Issue by tunetheweb** [snarfed/bridgy#1329]
We used to get the following WebMention types from Twitter:

- `in-reply-to`
- `like-of`
- `mention-of`
- `repost-of`

But now only receiving `in-reply-to` and `mention-of`.

For example, this Tweet that our account posted had numerous reposts and likes: https://twitter.com/HTTPArchive/status/1580545120272715776?s=20&t=4jU2v1cs_KIBoA1TxIZkwA

But only see `in-reply-to` and `mention-of` in the webmentions API:
https://webmention.io/api/mentions.jf2?perPage=500&target=https://almanac.httparchive.org/en/2022/jamstack&sort-dir=up&include

Got loads of examples of this and can't find a single one with a like recently. Last "like" we got through was perhaps way back in January at 2022-01-13T22:31:07Z.

Has something changed either at Twitter, or Bridgy, or webmention.io? Did a search at this and the [Webmention Repo](https://github.com/aaronpk/webmention.io), but can't see anything.

Or if this is not supported for Twitter any more then let us know.

Happy to help debug more if I can.

**Comment by snarfed** [comment]
Thank you for the report, and sorry for the trouble! This was a bug affecting accounts with capital letters. We updated much of our username handling to be more case insensitive a while back, but didn't quite catch everything. Background in #884.

I've fixed this bug and verified that likes and reposts are getting sent for your account again. If you want to backfill more of them, feel free to paste other tweet URLs into the "Resend for post" on https://brid.gy/twitter/HTTPArchive.

**Comment by tunetheweb** [comment]
Thanks for your speedy response!

I do see some coming in now, but for others I don't see them working even after resending.

For example:
- https://twitter.com/ldevernay/status/1574658405599363073?s=20&t=JTAd5tOXKnh6tRDSx24XhA (note not sent by our account, but our account was mentioned in it)
- https://twitter.com/HTTPArchive/status/1577006610316419073?s=20&t=YEJksRscCl32jFFTPeanSA (sent by our account)

Any further ideas?

**Comment by snarfed** [comment]
Yes! 

> * https://twitter.com/ldevernay/status/1574658405599363073?s=20&t=JTAd5tOXKnh6tRDSx24XhA (note not sent by our account, but our account was mentioned in it)

Ah, sure. When someone else tweets a link to you, Bridgy sends that tweet as a mention, but it doesn't send likes or reposts on it. This is consistent with current IndieWeb semantics. ([Salmentions](https://indieweb.org/Salmention) are worth looking into if you're more interested here, and #458, but those are still pretty nascent.)

> * https://twitter.com/HTTPArchive/status/1577006610316419073?s=20&t=YEJksRscCl32jFFTPeanSA (sent by our account)

I'm seeing that Bridgy sent the three likes and one retweet for this tweet: https://brid.gy/twitter/HTTPArchive?responses_before=2022-10-20T06:23:21.518785+00:00#responses . Logs:

- https://brid.gy/log?start_time=1666246992&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTU3NzAwNzEzOTE2NzgyMTgyNQw&module=background
- https://brid.gy/log?start_time=1666246991&key=agdicmlkLWd5ckwLEghSZXNwb25zZSI-dGFnOnR3aXR0ZXIuY29tLDIwMTM6MTU3NzAwNjYxMDMxNjQxOTA3M19mYXZvcml0ZWRfYnlfMTQxNzIzNDgM&module=background
- https://brid.gy/log?start_time=1666246991&key=agdicmlkLWd5ck0LEghSZXNwb25zZSI_dGFnOnR3aXR0ZXIuY29tLDIwMTM6MTU3NzAwNjYxMDMxNjQxOTA3M19mYXZvcml0ZWRfYnlfOTMxMjI1NDk1DA&module=background
- https://brid.gy/log?start_time=1666246990&key=agdicmlkLWd5clcLEghSZXNwb25zZSJJdGFnOnR3aXR0ZXIuY29tLDIwMTM6MTU3NzAwNjYxMDMxNjQxOTA3M19mYXZvcml0ZWRfYnlfMTM1MTg4NDI3ODgxNzIzOTA0MQw&module=background

**Comment by snarfed** [comment]
Ah yes, it probably is due to the fragment. Nice catch! I see the wms in wm.io when I include it: https://webmention.io/api/mentions.jf2?perPage=500&target=https://almanac.httparchive.org/en/2022/css%23class-names&sort-dir=up

I've forgotten exactly what Bridgy does with fragments, and what it should do. I'll look.

(There might also be a wm.io feature request in here to strip fragment, and/or to include all known fragments when fetching mentions for a given URL. Not sure. cc @aaronpk)

**Comment by tunetheweb** [comment]
Ah I tried that too but didn’t url encode the hash so didn’t see them!

**Comment by snarfed** [comment]
Turns out Bridgy doesn't currently do anything special for backfeeding to URLs with fragments. It includes the fragment in the target URL when it sends the webmention, as we saw here.

The webmention spec says target URLs with fragments are allowed, and implies that it's on receivers - in this case, somewhere between webmention.io and your site - to merge them into the same underlying post if they want. From https://webmention.net/draft/#request-verification :

> Note that a target URL may contain a fragment identifier, and if the receiver limits which URLs can receive Webmentions, the fragment SHOULD be ignored when checking if the URL is supported.

...and aha, yes, looks like this is already an open wm.io feature request, https://github.com/aaronpk/webmention.io/issues/106.

**Comment by tunetheweb** [comment]
> in this case, somewhere between webmention.io and your site

I presume there's no easy way of reliably iterating through all fragments webmention.io (since there could in theory be any number of them, and they might change over time) has so this really does need to be done in webmentions?

**Comment by snarfed** [comment]
Right!

It's tough. I can see the argument for collapsing fragments in Bridgy...but there are also arguments for keeping them, and non-Bridgy senders could still send you wms with fragments. So I think the spec is right in implying that this is ultimately on receivers, in this case webnention.io. cc @aaronpk
