### ISSUE TITLE
Multiple WebMentions from a single Twitter mention

### ISSUE THREAD

**Issue by edent** [snarfed/bridgy#1338]
I keep getting WebMentions from https://brid.gy/comment/twitter/edent/1586030387117314048/1586030387117314048

![Screenshot 2022-11-04 at 07-16-32 Comments (1) ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/199915049-3b03c3ba-a42b-4b9d-afe1-5bdfbc5e8bd5.png)

I delete the mention and, a day later, I receive another. This doesn't happen with any other WebMention from Brid.gy.

Any idea what's causing it?

**Comment by snarfed** [comment]
Hah. Bridgy resends webmentions when source posts (eg tweets) change, [in line with the spec and standard behavior](https://webmention.net/draft/#sending-webmentions-for-updated-posts). In this case, it's seeing that the [in-reply-to author](https://twitter.com/kevinbaker)'s display name here keeps changing back and forth between `⌜ktb⌟` and `⌜ktb⌟ is offline until 11/07`. Not sure if that itself is actually happening or a bug on my end. Regardless, Bridgy obviously shouldn't be including that in its diff logic. Funny one though!

**Comment by snarfed** [comment]
Oh btw @GWG this also seems like the wrong behavior from the WordPress Webmention plugin. If an existing wm is in trash or spam, and it gets received again, like here, it should just update (if necessary) in place, not create an entirely new WP comment, right?

**Comment by edent** [comment]
Ha! How weird. TBF, I do excel at finding odd edge cases :-)

Interestingly, this touches on another issue. I get warnings from a WordPress plugin that I have broken links. Mostly caused by people deleting Tweets which have become comments.  3.1.5 of that document suggests that I should be receiving deletion notices. But, I suspect that's probably too hard to do without checking thousands of mentions?

Anyway - thanks for the service, it has been a great source of joy to see what people are saying about my work.

**Comment by snarfed** [comment]
> Interestingly, this touches on another issue. I get warnings from a WordPress plugin that I have broken links. Mostly caused by people deleting Tweets which have become comments. 3.1.5 of that document suggests that I should be receiving deletion notices. But, I suspect that's probably too hard to do without checking thousands of mentions?

Right! Millions, almost 2.4M right now. https://github.com/snarfed/bridgy/issues/907, https://brid.gy/admin/stats, https://snarfed.org/2022-06-05_bridgy-stats-update-7

> Anyway - thanks for the service, it has been a great source of joy to see what people are saying about my work.

Aww, thanks for the kind words! Much appreciated.
