### ISSUE TITLE
Error with sign up for GoToSocial

### ISSUE THREAD

**Issue by jk-na** [snarfed/bridgy#1340]
Hello,

I tried to sign up using my GtS instance (https://gts.kelbie.scot) using the mastodon sign-up process, as GtS is implementing the mastodon API (though still in alpha), and I received the following 400 error:

```Bad Request: scopes must be less than 64 bytes```

GoToSocial intends to implement additional functionality on top of the mastodon API with relation to scopes, so is it possible that this limit could be extended?

cc @tsmethurst - tobi - all-round awesome lead dev of GtS

**Comment by snarfed** [comment]
Wow, with a broken error page no less. Thank you for reporting! Looking now.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/778068/200096327-06b05ff3-c93d-433e-89b0-9ac8d6b6b4f3.png">

**Comment by snarfed** [comment]
Ah, that HTML is actually from https://gts.kelbie.scot/, and we're expecting JSON.

More importantly, @tsmethurst looks like that `Bad Request: scopes must be less than 64 bytes` message is coming from https://gts.kelbie.scot/ too. Scope string we're sending is:

`read+read:accounts+read:blocks+read:bookmarks+read:favourites+read:filters+read:follows+read:lists+read:mutes+read:notifications+read:search+read:statuses+write+write:accounts+write:blocks+write:bookmarks+write:favourites+write:filters+write:follows+write:lists+write:media+write:mutes+write:notifications+write:reports+write:statuses+follow+push`

Raw example request:

```
POST https://gts.kelbie.scot/api/v1/apps
Content-Type: application/x-www-form-urlencoded
client_name=Bridgy&redirect_uris=http%3A%2F%2Flocalhost%3A8080%2Fmastodon%2Fdelete%2Ffinish%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fpublish%2Fmastodon%2Ffinish%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fmastodon%2Fcallback%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fdelete%2Ffinish%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fmicropub-token%2Fmastodon%2Ffinish&website=http%3A%2F%2Flocalhost%3A8080%2F&scopes=read+read%3Aaccounts+read%3Ablocks+read%3Abookmarks+read%3Afavourites+read%3Afilters+read%3Afollows+read%3Alists+read%3Amutes+read%3Anotifications+read%3Asearch+read%3Astatuses+write+write%3Aaccounts+write%3Ablocks+write%3Abookmarks+write%3Afavourites+write%3Afilters+write%3Afollows+write%3Alists+write%3Amedia+write%3Amutes+write%3Anotifications+write%3Areports+write%3Astatuses+follow+push
```

**Comment by jk-na** [comment]
I see, I wasn't sure on the source of the error but with the url being the brid.gy one I raised this ticket.  I'll raise another at the GtS end and link to here. Thank you @snarfed
