### ISSUE TITLE
More context to what "failed" means / how to fix it?

### ISSUE THREAD

**Issue by EllyLoel** [snarfed/bridgy#1341]
Hi there, I've tried to setup Webmentions on my website using webmention.io and brid.gy but I seem to be having some issues with getting tweets backfed.
As you can see in this image, it says failed:
![](https://user-images.githubusercontent.com/63755046/200167984-0b5b50d5-2ab3-4049-9399-b7011891631e.png)
Is there anyway we could get some more context or explanation as to why it has failed? I'm trying to fix things but I can't for the life of me figure out what's wrong.

Any help is much appreciated 🙏🏻

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Looks like your web site originally had `https://webmention.io/https://ellyloel.com/webmention` as your webmention endpoint, which wasn't right. Looks like you've fixed it since then. I clicked the 🔁 button to retry the webmention, and it worked.

**Comment by EllyLoel** [comment]
Ah! I tried that too but I must have needed to wait a bit before doing it, thank you for the help and sorry for the trouble 😅
