### ISSUE TITLE
Star GitHub repos on favorite as well as like

### ISSUE THREAD

**Issue by mjgardner** [snarfed/bridgy#1345]
I am using @dshanske's Post Kinds WordPress plugin, and I noticed that Bridgy only starred a GitHub repo that used the plugin's "Like" rather than "Favorite." This was confusing at first because the plugin uses a star icon to indicate "Favorite."

**Comment by snarfed** [comment]
Sure! Sounds like this change would need to happen in that WordPress plugin though, not in Bridgy, right? cc @dshanske

**Comment by mjgardner** [comment]
I’m not so sure. The plug-​in uses a dif­fer­ent prop­er­ty for each (like-​of vs. favorite-​of) and [there’s some argu­ment that they mean dif­fer­ent things to users and are treat­ed dif­fer­ent­ly on dif­fer­ent sys­tems](https://indieweb.org/favorite#Differences_From_Like), though I don’t think any sys­tem cur­rent­ly uses both. So a POSSE gate­way like Bridgy should con­sol­i­date both to a sin­gle prop­er­ty for sys­tems that do that, but pre­serve the abil­i­ty to keep them sep­a­rate should a dif­fer­ent (or new­er ver­sion) receiv­er dis­tin­guish between the two.

In any case I think the plug-​in should pre­serve the exist­ing prop­er­ties authors have already added to posts rather than lose infor­ma­tion by con­sol­i­dat­ing their mean­ing at the source.

### _Related_

(Originally published at: https://phoenixtrap.com/2022/11/11/not_sure_bridgy_github_star/)

**Comment by snarfed** [comment]
Ah, sure! Understood, will do.

Are you posting `u-favorite-of` posts then? Looks like https://phoenixtrap.com/2022/11/11/bridgy-github/ is a `u-like-of`, I'm guessing you changed it to make Bridgy understand it. If/when you have a `u-favorite-of` post, could you add it and yourself to https://indieweb.org/favorite#IndieWeb_Examples ? Favorite posts are still pretty rare on the IndieWeb, and `u-favorite-of` isn't yet official mf2, [unlike `u-like-of`](https://microformats.org/wiki/h-entry#Core_Properties). [I don't even see an issue for it yet.](https://github.com/microformats/microformats2-parsing/issues?q=is%3Aissue+favorite) cc @dshanske if Post Kinds is publishing `u-favorite-of`.

**Comment by snarfed** [comment]
Interesting data point, [ActivityStreams 1.0 includes favorite as distinct from like](https://activitystrea.ms/specs/json/schema/activity-schema.html#verbs), but [AS 2.0 (which ActivityPub uses) doesn't](https://www.w3.org/TR/activitystreams-vocabulary/#activity-types).

**Comment by snarfed** [comment]
Done!
