### ISSUE TITLE
Some Likes do not have names or avatar from Mastodon to WordPress?

### ISSUE THREAD

**Issue by quicoto** [snarfed/bridgy#1355]
Wondering if this is something from my side.

I've got some (just 2) "Likes" that have proper name and avatar but all the rest look like "mentions" not like "Likes".

I haven't changed anything. Using the same WordPress plugin [Webmention](https://wordpress.org/plugins/webmention/). Even more interesting the same users have liked both posts and only in 1 it shows as "Like".

Are the some scenarios where Bridgy us not able to fetch this information, thus not sending it with the webmention?

![WordPress Admin](https://cldup.com/Lbl0QEcPMF.jpg)

Example post with just mentions (even though there are likes): https://ricard.dev/how-to-add-web-mentions-to-your-wordpress-site/

Example post with both "mention" and "likes" showing correctly with name and avatar: https://ricard.dev/improving-mastodons-disk-usage/

**Comment by snarfed** [comment]
Hmm! Sorry for the trouble! I'm honestly not sure what happened here. Looking at one example, the like from https://ricard.social/@m0bi13@mastodon.social (user id 109314048220964009 on ricard.social) on https://ricard.social/@ricard/109425962934953029, Bridgy sent it successfully at 2022-11-29 08:06:30 UTC and got an HTTP 200 from your webmention endpoint ([log](https://brid.gy/log?start_time=1669709193&key=agdicmlkLWd5clcLEghSZXNwb25zZSJJdGFnOnJpY2FyZC5zb2NpYWwsMjAxMzoxMDk0MjU5NjI5MzQ5NTMwMjlfZmF2b3JpdGVkX2J5XzEwOTMxNDA0ODIyMDk2NDAwOQw&module=background)). I clicked the retry button on it just now on https://brid.gy/mastodon/%40ricard%40ricard.social, and it again successfully sent the webmention ([log](https://brid.gy/log?start_time=1669733248&key=agdicmlkLWd5clcLEghSZXNwb25zZSJJdGFnOnJpY2FyZC5zb2NpYWwsMjAxMzoxMDk0MjU5NjI5MzQ5NTMwMjlfZmF2b3JpdGVkX2J5XzEwOTMxNDA0ODIyMDk2NDAwOQw&module=background)).

@dshanske (author of the WordPress Webmention plugins), any ideas?

**Comment by quicoto** [comment]
Thank you for the quick reply @snarfed 

Who decided the name of the "comment author", is that the webmention payload ping from Bridgy? 

Or is it the Webmention WordPress Plugin?

Because I only see `Bridgy Response`  as authors for all pings

**Comment by snarfed** [comment]
I think @dshanske/@pfefferle's Semantic Linkbacks plugins extract it from the source (Bridgy) page's microformats2. I suspect it didn't get that far in these cases though.

**Comment by quicoto** [comment]
Right, I don't have that one installed! I didn't think it was mandatory for it to retrieve the "Like" author name and avatar. As the output from it was breaking my comments layout.

I'll try it, Thank you

**Comment by quicoto** [comment]
Solved.

So the Semantic Linkbacks is mandatory for the faces to show up correctly when receiving a ping.

Thank you.

**Comment by snarfed** [comment]
Ugh. Sorry for the trouble! @dshanske and @pfefferle have been trying to merge those two plugins for something like 7+ years 😭
