### ISSUE TITLE
Having to manually poll to receive webmention

### ISSUE THREAD

**Issue by spcbfr** [snarfed/bridgy#1371]
Hey, I have a blog and I wanted to be able to receive replies from elsewhere, mainly social media (not too interested in receiving replies from other blogs) I have setup webmention.io, and connected brid.gy but there are a few problems/questions:

1. say someone `x` (not me) makes a top-level tweet mentioning one of my posts, does that get sent as a webmentions or do replies to my personal posts only count?
2. right now when going to any of my accounts brid.gy accounts (I have 3: reddit, mastodon and twitter) it always says `next poll a minute from now` no matter what
3. here is the biggest problem: If I want to receive any webmentions, I have to first go to brid.gy, go to the account, manually do a poll, and then go through every response that has the word `sent` and click the button `retry` for the webmention to get sent

resources:

- [my website](https://www.yusuf.fyi)
- [one of my brid.gy accounts](https://brid.gy/mastodon/@spacebuffer@fosstodon.org)
-  [the webmentions that get sent to me](https://webmention.io/api/mentions.html?token=MbyTl_LpfHkwpoTcMKX9Hw)

**Comment by snarfed** [comment]
Thanks for trying Bridgy, and sorry for the trouble!

> say someone x (not me) makes a top-level tweet mentioning one of my posts, does that get sent as a webmentions or do replies to my personal posts only count?

Bridgy definitely sends other people's tweets that link to your site! More: https://brid.gy/about#which

> right now when going to any of my accounts brid.gy accounts (I have 3: reddit, mastodon and twitter) it always says next poll a minute from now no matter what

Absolutely right, this bit of the UX has degraded. #615 tracks this bug, I can look into prioritizing fixing it.

> here is the biggest problem: If I want to receive any webmentions, I have to first go to brid.gy, go to the account, manually do a poll, and then go through every response that has the word sent and click the button retry for the webmention to get sent

Hmm! Bridgy isn't real time, it polls periodically, roughly every 30m or so for active accounts. More: https://brid.gy/about#missing . Maybe it just hadn't polled yet in those cases?

**Comment by spcbfr** [comment]
Hey thanks for replying so fast, and also for making such a great project!

to test if everything was working properly, I made this post on mastodon https://fosstodon.org/@spacebuffer/109562100003582702 that contained a link to one of my posts and replied to it, then waited for over an hour and a half but nothing showed up. then when I clicked on `poll now` it finally picked it up.

**Comment by spcbfr** [comment]
I've noticed that it seems to be counting the time until the next poll properly, until it reaches 30 minutes, then it keeps saying `next poll a minute from now` until I manually press poll now or crawl now, see the figure below for what I mean

![image](https://user-images.githubusercontent.com/77839865/209333606-1024a5a9-bd67-4071-a808-5244fa1f63f7.png)

**Comment by snarfed** [comment]
> to test if everything was working properly, I made this post on mastodon https://fosstodon.org/@spacebuffer/109562100003582702 that contained a link to one of my posts

Ah, sorry, Bridgy only sends _tweets_ that link to your site, not Mastodon posts, since Mastodon has no global search. https://brid.gy/about#which

> I've noticed that it seems to be counting the time until the next poll properly, until it reaches 30 minutes, then it keeps saying `next poll a minute from now` until I manually press poll now or crawl now, see the figure below for what I mean

Yup! That's right, details in #615. I'll see if I can improve this eventually.

**Comment by spcbfr** [comment]
Alrighty everything is clear now, thanks! I'll reopen if I face any other problems

**Comment by snarfed** [comment]
I do need to improve the docs here though, at minimum. They currently say we send links on Mastodon too, and we do, but we only search your account's instance, which will only find a small fraction of all links across the fediverse. I wonder if I should just turn that off altogether to avoid confusion.

**Comment by snarfed** [comment]
Wow, I just learned that Mastodon search doesn't even fully search the local instance. It only searches hashtags, users, and your own posts. Evidently by design, to prevent harassment.  https://docs.joinmastodon.org/user/network/#search
 News to me...and also means link search doesn't even work on the local instance. OK then! Guess I'm removing it.

**Comment by snarfed** [comment]
Done, 8329016a73f88068fbb151293f08b75660b4148e
