### ISSUE TITLE
Edit Post Preview before sending

### ISSUE THREAD

**Issue by bennypowers** [snarfed/bridgy#1406]
Awesome app thanks for publishing

I'd like to edit post previews before sending them off, so i could for example add hashtags, or alter the post text some other way.

apologies if this was already opened, I could not find this issue by searching the terms `edit`, `post`, `preview`

**Comment by snarfed** [comment]
Thanks for the kind words, and for the idea! This would definitely be convenient, but it would require a post editor UI, which is not something I plan to build or maintain in Bridgy. More background: https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb, #478, #527, etc.

There are a couple alternatives. First, [Bridgy Publish now has Micropub support](https://brid.gy/about#micropub), so you can use a Micropub client (ie a real editor 😁) to POSSE custom tweets to twitter. [There's also the `p-bridgy-twitter-content` (etc) custom microformats](https://brid.gy/about#silo-content) you can use in your HTML.

**Comment by bennypowers** [comment]
Sounds legit
