### ISSUE TITLE
Hello @snarfed! I was checking my comments and something seems a little off. All...

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy#1408]
Hello @snarfed! I was checking my comments and something seems a little off. All of the comments are referencing a Brid.gy link today.I don’t remember this being like this before. The screenshot has 3 likes. The first comment was me liking the Mastodon post using my mastodon.social account, the second comment is a like from the same person that liked in the 3rd comment and the result is different (no picture or name). My guess on when this changed would be between 2/1/2023 5 am EST back to 1/31. I believe that I would have noticed it yesterday. But to be safe I might say1/29 or 1/30.

![Mastodon Screenshot](https://i0.wp.com/photos.smugmug.com/Photo-journal/n-MLkhDz/2023/2023-02/02-01-2023-Bridgy-Name/i-kNzfkcx/0/61227e76/XL/IMG_0416-XL.png?ssl=1)

(Originally published at: https://tmichellemoore.com/?p=152457)

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! It looks like your Semantic Linkbacks plugin got disabled or uninstalled. That's the first place I'd check. If it's installed and enabled, ask @dshanske @pfefferle if this is related to the upcoming plugin  merge.

**Comment by pfefferle** [comment]
hey @tmichellemoore this would only be the case if you have installed the 5.0.0 version of Webmentions. Otherwise it should simply work.

**Comment by tmichellemoore** [comment]
Hi @pfefferle! I have 4.0.8. Should I upgrade? Will it stay like what's in the screenshot?

**Comment by pfefferle** [comment]
@tmichellemoore please do not deinstall it before Webmention 5.0.0 is released. Btw. The Webmention update will do everything for you. Even deactivating and deinstalling the semantic linkbacks plugin.

**Comment by tmichellemoore** [comment]
Ok, thank you @pfefferle!

**Comment by pfefferle** [comment]
@tmichellemoore there are still some small issues, but I think we will be able to release 5.0.0 this week!

**Comment by dshanske** [comment]
We should have a release party

**Comment by tmichellemoore** [comment]
Awesome news! @pfefferle
