### ISSUE TITLE
Wrong url when using publish

### ISSUE THREAD

**Issue by thiagomgd** [snarfed/bridgy#1409]
In a few occasions, using the publish feature - either on site, or via webmention - seems to get the wrong url.

In the example below, I'm trying to publish https://geekosaur.com/post/geekosaur-news-26/. On the preview, it shows https://geekosaur.com/tags/geekosaurnews/, which is the category/tag link.

![image](https://user-images.githubusercontent.com/12170252/216179517-a82502c0-accf-401b-99fa-d5529665ce7e.png)

Looking at my page source, the only link to `/tags/geekosaurnews/` is on the link to the tag. Canonical, og:url and twitter:url are all correct with the actual post url

**Comment by snarfed** [comment]
Oof, sorry for the trouble! Looks like microformats2 parsing is incorrectly interpreting your https://geekosaur.com/tags/geekosaurnews/ tag link as the `u-url` for this page. Background: https://github.com/microformats/microformats2-parsing/issues/36 , https://microformats.org/wiki/microformats2-implied-properties#root_class_with_one_child_hyperlink .

[from chat](https://chat.indieweb.org/microformats/2023-02-01#t1675292686380500), @tantek says one workaround would be to add `<data class="u-url" value="..."></data>` to your HTML, inside the `h-entry`.

**Comment by thiagomgd** [comment]
thanks for the workaround!!!
