### ISSUE TITLE
Publish Full URL

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy#1422]
Hello @snarfed, Is there a way to publish the original post's full URL instead of the one with the numbers on Mastodon? 
Mastodon Post: https://mastodon.social/@tmichellemoore/109916559265513912.
The URL Brid.gy posted on Mastodon: tmichellemoore.com/?p=152663
The actual URL is: https://tmichellemoore.com/blog/almost-ready-to-continue-my-100-days-of-indie-web-project/
Please forgive me if I have asked this before. :-)

**Comment by snarfed** [comment]
Hi Michelle! Sounds like your site is including a rel=shortlink element in your posts' HTML with that URL, which Bridgy obeys: https://brid.gy/about#short-link . Not sure how to disable that in WordPress, @dshanske might know?

**Comment by snarfed** [comment]
Tentatively closing, feel free to reopen.
