### ISSUE TITLE
Timeout when setting up link to Mastodon account

### ISSUE THREAD

**Issue by stevenjmesser** [snarfed/bridgy#1429]
Hello,

Been trying to link brid.gy to my Mastodon account and got the following error:
`Upstream server request failed: HTTPSConnectionPool(host='indieweb.social', port=443): Read timed out. (read timeout=15)`

Not sure if it’s an issue with my instance or not as I was able to authorise the Bridgy connection from the indieweb.social instance, but Bridgy gave the timeout when accepting the call back.

**Comment by snarfed** [comment]
Hi! Yup, I see timeouts to indieweb.social from ~10:50p PT yesterday to ~3:50a PT this morning. @timchambers was there downtime? Looks like it's fine now though, I was able to log in with my indieweb.social account. Try again?

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen!

**Comment by stevenjmesser** [comment]
Yep, now working. Thanks for your help!
