### ISSUE TITLE
Mastodon backfeed produces duplicate replies

### ISSUE THREAD

**Issue by JoelOtter** [snarfed/bridgy#1431]
Hi! Thanks so much for this great tool, I've been using it for about a week now and I love it.

I wrote [this post](https://www.joelotter.com/posts/2023/03/good-shit-pizza/) yesterday, and all the publishing and backfeeding for Twitter and Mastodon worked correctly!

Today I [replied to the post](https://www.joelotter.com/notes/2023/03/07-pizza/) from my own website, which shows up as a webmention without going through Bridgy. I then published the post, and Bridgy correctly posted the tweet and toot as replies of the original. So far, so good!

The issue is that on Mastodon Bridgy then backfed the reply toot to the original post, resulting in a duplicate (which I've since manually deleted). On Twitter, on the other hand, it correctly recognised that this reply was itself syndicated from my website, and didn't send a webmention for it.

Is this a config error on my side, an intentional behavioural difference, or a bug? I did notice that on Twitter the website had been crawled but on Mastodon it had not.

My bridgy pages: 
https://brid.gy/mastodon/@joel@otter.garden
https://brid.gy/twitter/joelotter

Again, thanks so much for your work on this!

**Comment by snarfed** [comment]
Probably yes; Bridgy doesn't de-dupe across silos. Here's some of our thinking on that so far, and how some people are doing it right now: https://indieweb.org/deduplication

**Comment by JoelOtter** [comment]
Ah, of course there's a wiki entry! Thanks for this. I'll close this issue now - perhaps a line in the docs to just state that Bridgy makes no attempt to deduplicate would help prevent others making my same mistake :)

**Comment by snarfed** [comment]
> perhaps a line in the docs to just state that Bridgy makes no attempt to deduplicate would help prevent others making my same mistake :)

Yes! Great idea, I've added that at https://brid.gy/about#duplicates
