### ISSUE TITLE
Calckey Beta compatibility 

### ISSUE THREAD

**Issue by Lunarequest** [snarfed/bridgy#1443]
Calckey Beta has a mastodon compatible auth api which allows you to link it to various 3rd party services. In Bridgy when you attempt to link it you get redirected to a url that returns a 404. This is a example of the url that is returned

https://brid.gy/mastodon/delete/finishhttps://brid.gy/mastodon/callbackhttps://brid.gy/micropub-token/mastodon/finishhttps://brid.gy/publish/mastodon/finishhttps://brid.gy/delete/finish?code=%22A_code_I_think_shouldnt_share&state=$(getUrlParams().state)

The `$(getUrlParams().state)` is actually part of the url. I am currently not sure if this is an issue with calckey or with birdgy-fed since the url is extremely mangled. This is reproducible consistently

**Comment by snarfed** [comment]
Looks like Calckey may not support multiple OAuth redirect URIs when creating a new OAuth app like Mastodon does? https://docs.joinmastodon.org/methods/apps/#form-data-parameters . We've seen this problem with other fediverse apps: https://github.com/snarfed/bridgy/issues/1385#issuecomment-1378224069 . Maybe file an issue with them?

**Comment by Lunarequest** [comment]
Will do

**Comment by Lunarequest** [comment]
The calckey folks were wondering how you send multiple uris in the form and what do you expect to happen after the oauth part? how do you expect calckey to return?

**Comment by snarfed** [comment]
Hi! I don't see an issue on https://codeberg.org/calckey/calckey/issues, I'm guessing this was in chat o or somewhere else?

I'm passing multiple redirect URLs when I _create_ the API app initially, not in the user-facing OAuth flow. I do that because I have multiple user-facing OAuth flows in different places. I only pass a single URL in `redirect_uri` in those, but Calckey evidently uses the one it stored when I created the app instead, which is handled because it doesn't support multiple.

**Comment by Lunarequest** [comment]
Calckey folks asked in chat "Are the ones(urls) used in user oauth flow different ones than the ones supplied at app creation"

**Comment by Lunarequest** [comment]
what should be done with each url, I'm trying to wrap my head around this and work on it in my free time but I don't understand what should be done with the multiple uris?

**Comment by snarfed** [comment]
When you create an API app with `/api/v1/apps`, you pass _all the possible redirect URLs your app might use_ in the `redirect_uris` param. Then during a single OAuth flow, you specify in the `redirect_uri` param _which one of those redirect URLs_ CalcKey should redirect the user to, in that one single flow, after they auth and approve.

It looks like CalcKey currently always redirects every OAuth flow for the app back to the (mangled) `redirect_uris` value from the initial app creation. It should instead use the `redirect_uri` param from the OAuth flow itself, check that it's in the `redirect_uris` provided at app creation, and then redirect the user to it.

**Comment by snarfed** [comment]
Btw @Lunarequest I'm happy to jump into chat and talk to them directly if you want. I searched history on #calckey:matrix.fedibird.com in Matrix, but didn't see any of this, so I'm guessing you've been talking to them somewhere else.

**Comment by Lunarequest** [comment]
this has been fixed in iceshrimp dev so I'm considering this has been fixed now

**Comment by snarfed** [comment]
Hmm! Sounds like good news. Do you know of a live iceshrimp dev instance that we can test against?
