### ISSUE TITLE
Handle new Reddit API rate limits and pricing

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1492]
[Reddit is cracking down on their API usage and starting to enforce rate limits and charge developers.](https://www.theverge.com/2023/6/8/23754780/reddit-api-updates-changes-news-announcements) Whee. Specifically, they're dropping the rate limit from 100qpm per app per user to 100qpm per app, total. Oof.

From https://www.reddit.com/r/modnews/comments/141oqn8/api_updates_questions/ / https://support.reddithelp.com/hc/en-us/articles/16160319875092-Reddit-Data-API-Wiki :

> As of July 1, 2023, we will enforce two different rate limits for those eligible for free access usage of our Data API. The limits are:
>
> * If you are using OAuth for authentication: 100 queries per minute (QPM) per OAuth client id
> * If you are not using OAuth for authentication: 10 QPM
>
> QPM limits will be an average over a time window (currently 10 minutes) to support bursting requests.
>
> _Important note: Historically, our rate limit response headers indicated counts by client id/user id combination. These headers will update to reflect this new policy based on client id only on July 1, 2023._

Emphasis mine. Fortunately Bridgy only does 10-20qpm total right now, so hopefully we shouldn't notice this.

**Comment by spcbfr** [comment]
If reddit is gone too we will no longer have most of the big social media apps :( I hate all of these API price changes that happened this year.

**Comment by snarfed** [comment]
Nothing more to do here, we're comfortably under the quotas and will be for the foreseeable future. Phew.
