### ISSUE TITLE
Implement Token Introspection Method for Publish Tokens

### ISSUE THREAD

**Issue by dshanske** [snarfed/bridgy#1501]
https://indieauth.spec.indieweb.org/#access-token-verification-request

Problem is how to, if my WordPress plugin accepts tokens, to verify they work.

If not verification, even the old school using it to fetch a page that returns something.

**Comment by snarfed** [comment]
Agreed! Bridgy doesn't implement IndieAuth itself at all, just Micropub, but I'll see what I can do.

**Comment by dshanske** [comment]
Yes, so it doesn't have to be to spec. It's  just a starting point.  You could use something like the old IndieAuth method.

https://www.w3.org/TR/indieauth/#access-token-verification

No auth.

**Comment by snarfed** [comment]
I've done this by moving Bridgy's minimal Micropub query support behind auth, specifically `?q=config`. That now fails unless you include a valid token for a valid, publish-enabled Bridgy account. ([I think that's how the spec says it's supposed to work anyway](https://micropub.spec.indieweb.org/#authentication-and-authorization) 😁)
