### ISSUE TITLE
Can bridgy also post my mastodon content to my Wordpress blog ?

### ISSUE THREAD

**Issue by delusho** [snarfed/bridgy#1509]
(No issue but feature request) 

It seems there is a feature to post from Wordpress to mastodon. But can bridgy also work the other way round? I would like to create a blog with my mastodon posts including all the media.

**Comment by snarfed** [comment]
Sounds like you're looking for automated [PESOS](https://indieweb.org/PESOS)! Bridgy doesn't currently do this, and I'm unlikely to add it, but [I've definitely thought about it before, it's a great idea](https://snarfed.org/2015-01-22_pesos-for-bridgy-publish). Lots of others in the community have built various PESOS tools too. Feel free to check out that wiki page or [ask in chat](https://indieweb.org/discuss)!

**Comment by delusho** [comment]
Thank you for your reply! I will join the discord. I am looking for this as I like the streamlined way of posting to mastodon. And I would like to keep that. Will ask in the chat if someone has done it.
