### ISSUE TITLE
Syndication with mastodon: content is truncated

### ISSUE THREAD

**Issue by jpcaruana** [snarfed/bridgy#1533]
With X (previously twitter), content had to be truncated to conform with their (ever changing) tweet char limit. On mastodon (depending on the instance I think), we can post more text. It seems to me that Bridgy truncates mastodon syndication in the same fashion as it did with X, see https://indieweb.social/@jpcaruana/110831617954383431 for instance, but I might be wrong here.

Is there a limitation somewhere or could bridgy post more content when syndicating to a mastodon instance?

(Originally published at: https://jp.caruana.fr/notes/2023/08/04/syndication-with-mastodon/)

**Comment by snarfed** [comment]
Hi! Yes, Mastodon has a 500 character limit, https://docs.joinmastodon.org/user/posting/#text , so Bridgy truncates to that.

**Comment by jpcaruana** [comment]
The default character limit is 500 characters.
Hi, thank you for your answer. The char limit is a default one, some instances seem to have a higher limit. I assume this would be difficult to accomodate with, instance by instance.
As an example, https://indieweb.social/@Zumbador@mefi.social/110831709271663521 is 675 char long.

(Originally published at: https://jp.caruana.fr/notes/2023/08/04/the-default-character-limit-is/)

**Comment by jpcaruana** [comment]
I would gradly help! I took a look at granary, it seems like the truncate_text_length attribute is set in the constructor: would it be wise to call an API endpoint on the constructor of an object? It looks like an antipattern to me, preventing people from doing isolated unit test and / or using this object in different contexes.
What would you suggest for implemeting this?

(Originally published at: https://jp.caruana.fr/notes/2023/08/04/i-would-gradly-help-i-took-a/)

**Comment by snarfed** [comment]
Awesome! And funny, we actually already do this:

https://github.com/snarfed/bridgy/blob/db16a9d9c7f68eec6742f4000bf3fd455d2885d6/models.py#L252-L254

...but evidently Mastodon's v1 instance info API object has changed since then: https://docs.joinmastodon.org/methods/instance/#v1 . So maybe all we need to do is update it to look for the new field as well as the old one?

Also, unit test here:

https://github.com/snarfed/bridgy/blob/db16a9d9c7f68eec6742f4000bf3fd455d2885d6/tests/test_mastodon.py#L57-L61

**Comment by jpcaruana** [comment]
Nice! I was looking in the wrong place. I might be able to cook some PR, but I suspect some instances still rely on the v1 API.

(Originally published at: https://jp.caruana.fr/notes/2023/08/04/nice-i-was-looking-in-the-wrong/)

**Comment by snarfed** [comment]
Oh, this is a v1 API response object that we've already fetched. All you'd need to do is look at the new field.

**Comment by jpcaruana** [comment]
Oh I see, on the instance I use, https://indieweb.social/api/v2/instance/ and https://indieweb.social/api/v1/instance/ speak in v2 API...

**Comment by snarfed** [comment]
Hey @jpcaruana have you had a chance to try this? Did it work?

**Comment by jpcaruana** [comment]
Not sure. This post https://jp.caruana.fr/notes/2023/08/05/how-to-synchronize-a-tree/ is 501 chars long and https://indieweb.social/@jpcaruana/110836774445084366 does not contain the last sentence.

When was the production deploy for this update? Maybe I just posted this before? It posted it on Aug 5th, 13:29 CEST (4:29 PDT if I didn’t mess up with time zones).

I haven’t posted anything longer than 500 chars since… I’ll give it another try.

**Comment by snarfed** [comment]
Hmm. This was deployed around 8/4 11:25am PT, well before your post.

**Comment by snarfed** [comment]
Oh, indieweb.social has the default 500 character limit: https://indieweb.social/api/v2/instance . You'll want to test on a different instance that has it set higher.

**Comment by jpcaruana** [comment]
oh, I feel stupid mow! :) I am glad I could help people with a higher char limit instance.

**Comment by jpcaruana** [comment]
I understand where I was misleaded: I can see https://indieweb.social/@helge@mymath.rocks/110869631107921516 in my feed, but it does come from another instance...

**Comment by jpcaruana** [comment]
I found https://techhub.social/ with a 1000 char limit and I created an account on it for testing purposes. As I added this syndication to my website and to bridgy, I found myself unable to post from bridgy with this error message:

> Try publishing that page from [@jpcaruana@indieweb.social (Mastodon)](https://brid.gy/mastodon/@jpcaruana@indieweb.social) instead.

Any idea how I could give it a try?

ps: in the mean time I reverted back my public pages with indeweb.social profile link

**Comment by jpcaruana** [comment]
(I could imagine a use case where you have several Mastodon accounts and want to syndicate to one or antother depending on the content you post: could it work?)

**Comment by snarfed** [comment]
Definitely a real use case! Sorry Bridgy doesn't yet handle multiple accounts per domain. #629 tracks that feature request. (It wouldn't be easy. 😐)

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen if necessary!

**Comment by JoelOtter** [comment]
Hello! Sorry to zombie this, but I'm not sure it's working correctly, or if I'm doing something wrong. My [Mastodon instance](https://otter.garden) supports 5000 characters, but [this post](https://www.joelotter.com/notes/2024/03/26-atproto/) seems to have gotten [truncated](https://otter.garden/@joel/112161695372141818) down to 500 as normal.

Does brid.gy fetch the character limit on each publish or does it just do it once at signup? If so that might have something to do with it; I changed that character limit just a couple months ago and have been using brid.gy rather longer!

**Comment by snarfed** [comment]
Hmm! Good hunch, we do store and reuse that per-server limit, and i don't think we ever expire and refresh it yet. We should!

**Comment by JoelOtter** [comment]
Hmm, it doesn't seem to! At least, the preview still shortens it - does that work differently?

**Comment by snarfed** [comment]
Argh no, you're right. Following up in #1698.
