### ISSUE TITLE
Bluesky: convert button logo to logotype

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1577]
The current logo on the home page Bluesky button is great!...but it's a bit out of place as just a logo and not a full logotype with the "Bluesky" word. Might be nice to add that to it.

cc @JoelOtter

**Comment by JoelOtter** [comment]
Yeah I couldn't find anything at the time! This logo isn't even from Bluesky really, it's from the ATProto website. You know some folks on the Bluesky team right, worth asking them if they have anything official?

**Comment by snarfed** [comment]
Not yet, but sounds like it's coming soon! https://github.com/bluesky-social/atproto/discussions/1754#discussioncomment-7383467

**Comment by snarfed** [comment]
done! https://blueskyweb.xyz/blog/12-21-2023-butterfly
