### ISSUE TITLE
Bluesky: skip "What's your web site?" page on signup if their handle is their web site

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1578]
Feels a bit awkward to ask, "Hey Bluesky user snarfed.org, what's your web site?" 😆

Concretely, we'd probably fetch the home page and look for an h-card? Or something similar. cc @JoelOtter

**Comment by JoelOtter** [comment]
Hmm we can't discount the possibility that users might want to add multiple websites, right?

**Comment by snarfed** [comment]
Right now, maybe we can? We don't try very hard yet to support multiple sites per user. We skip that UI flow entirely in other silos that have a dedicated "web site" profile field, at least when the user has filled it in, and user pages don't currently have a way for you to add more sites after initial signup.

**Comment by snarfed** [comment]
OK. snarfed/granary@ee7b8f5 implemented this. There's still the occasional case where someone's web site is a different domain than their handle, or they want to attach multiple web sites, but those apply to pretty much all silos, and I think #623 tracks them. So, tentatively closing.
