### ISSUE TITLE
Bluesky: sending original posts as replies?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1586]
I got this just now as a reply, but it's the original POSSEd post. Odd. https://snarfed.org/2023-04-10_49894#comment-2868402

**Comment by snarfed** [comment]
Another: https://snarfed.org/2023-04-13_49914#comment-2868418

**Comment by JoelOtter** [comment]
Weird, I've not seen this - mine show up as the original in Bridgy: 
<img width="903" alt="image" src="https://github.com/snarfed/bridgy/assets/2765356/370053dd-7c23-47bc-83c9-961bd36a7b81">

Have you a link to the Bluesky post? I wonder if this is an overlapping thing with Bridgy Fed or something?

**Comment by snarfed** [comment]
The original post on my site does have a synd link to Bluesky. It's staging.bsky.app, not bsky.app, but after #1584 that should now work!

**Comment by JoelOtter** [comment]
Ah sorry I meant could you link here to the post on Bluesky so I can have a look

**Comment by snarfed** [comment]
Ah, sure! https://staging.bsky.app/profile/snarfed.org/post/3jt2hqcbvod2a

**Comment by snarfed** [comment]
My first step when debugging something like this is to find the log of the propagate task that sent the webmention, usually from the user page, and look at the AS1 object it used, and then find Bridgy's webmention source URL and fetch it and check that it looks right.

**Comment by snarfed** [comment]
This hasn't happened to me recently, I think it may have been fixed along with everything else we've been doing recently.
