### ISSUE TITLE
Bluesky: receiving comments, but not likes or reposts

### ISSUE THREAD

**Issue by laril** [snarfed/bridgy#1592]
I don't know if this is a bug or some other issue, but after configuring Bluesky to brid.gy, I'm succesfully receiving all the comments as webmentions, but the likes or reposts to the same bs-posts are not received. Brid.gy sees them, but says "No webmention target" on them. 

On the logs there is this: 
I 2023-11-01 09:44:53.671214+00:00 Demoting original post links because user tag:[bsky.app](http://bsky.app/),2013:did:plc:mzvszw2oinlhjryugr5kluyp did:plc:mzvszw2oinlhjryugr5kluyp doesn't match author did:plc:mzvszw2oinlhjryugr5kluyp [larilohikoski.fi](http://larilohikoski.fi/)

I have no idea what that means, but it may or may not have something to do with this (as all author id's mentioned on that are the same).

**Comment by snarfed** [comment]
Hmm! Odd indeed, especially since other people are receiving likes and reposts ok. cc @JoelOtter

**Comment by JoelOtter** [comment]
Weird. I've seen that demotion line before but not sure it's related to this.

@laril if possible could you post a link here to a Bluesky post and corresponding post on your website that it's not working for?

**Comment by laril** [comment]
Here's one: 
https://larilohikoski.fi/shorts/2023-10-31-10-01-18/ 

..and

https://bsky.app/profile/larilohikoski.fi/post/3kd4c65jfu22r

**Comment by snarfed** [comment]
A couple data points:
* Afaik most (all?) of us who have received likes and reposts so far only have synd links from our sites to Bluesky; we don't also include backlinks in our Bluesky posts to the original posts on our sites. @laril, on the other hand, does have backlinks.
* @laril's synd links use DID, not handle, eg https://bsky.app/profile/did:plc:mzvszw2oinlhjryugr5kluyp/post/3kd4c65jfu22r in the example post above.

Not sure whether either of those matter here yet.

**Comment by laril** [comment]
I don't think backlinks can be the reason, as here's another example of a post without backlinks, which doesn't work either: https://larilohikoski.fi/shorts/2023-10-29-09-13-36/ , https://bsky.app/profile/larilohikoski.fi/post/3kcuxpymf7j2a . Also, this one is linking to Bluesky with my handle in it.

Just a guess, but could this have something to do with me using my domain name as my Bluesky handle?

**Comment by snarfed** [comment]
Makes sense!...except that replies are coming back ok. If synd links are the issue, I still don't quite get why replies would work but not likes/reposts.

**Comment by JoelOtter** [comment]
Oh good point. Errrr. I’ll do some testing.

**Comment by laril** [comment]
To make things even more strange, now I had all of a sudden received one like for this https://larilohikoski.fi/shorts/2023-11-01-13-47-23/ (bs-link below the text), but still not to any others.

**Comment by laril** [comment]
> Here's one: https://larilohikoski.fi/shorts/2023-10-31-10-01-18/
> 
> ..and
> 
> https://bsky.app/profile/larilohikoski.fi/post/3kd4c65jfu22r

Now I was able to receive also likes and reposts for this post after using the Bluesky url above for "Resend for post" instead of my blog url. I had previously changed the syndication url on the post to one using my handle, without the DID, but it apparently wasn't enough. Is Bridgy caching these, or what might be the reason? 

I noticed another thing, I'm not sure if this is a problem with Bridgy or some other part of the process. I'm using https://github.com/PlaidWeb/webmention.js/ to show the webmentions on my blog, and I noticed that it shows only the first reaction that has come from Bluesky even when there are many more of them. The problem was in its "dedupe"-function, which uses "url" attribute to recognize duplicate reactions. However, all the reactions coming from Bluesky to a certain post share the same url, and thus are seen as duplicates. On likes and retoots coming from Mastodon this attribute refers to the like or retoot itself, not to my post that has been liked. I was able to make the script to show all the Bluesky-reactions by changing it to use wm-source attribute instead of url to recognize them.

**Comment by snarfed** [comment]
> The problem was in its "dedupe"-function, which uses "url" attribute to recognize duplicate reactions. However, all the reactions coming from Bluesky to a certain post share the same url, and thus are seen as duplicates.

Great catch, thank you for mentioning this! I've filed #1600 for it.

**Comment by JoelOtter** [comment]
I'm now seeing some likes not get picked up for one of my posts that likes were previously going through to! How weird.

**Comment by snarfed** [comment]
OK! I think both this and #1600 should be fixed. "Resend for post" may still be broken sometimes for Bluesky; that's tracked in #1604. Thanks again for reporting @laril! Tentatively closing.

**Comment by jacklorusso** [comment]
I'm now seeing likes and reposts being picked up, which is progress! This issue was affecting me too.

They're unfortunately all saying "No webmention targets found" though. I assume it's #1604 as I've been trying to resend for the posts where it wasn't working previously to capture those mentions. There **_should_** be webmention targets — mentions and replies work. Even like webmentions do work — thanks for the like on  https://jacklorusso.com/posts/i-archived-my-twitter/ @snarfed :) I assume you were testing!

Bridgy account if you want to look https://brid.gy/bluesky/did:plc:7dzg2vnr65pvlqgb2ziqgm4d 

Thanks to all you are doing here @snarfed @JoelOtter — it's really cool.

**Comment by snarfed** [comment]
Ugh, sorry, thanks for the nudge! I think that's actually https://github.com/snarfed/bridgy/issues/1611#issuecomment-1813267452, will follow up there.
