### ISSUE TITLE
Github: URLs don't work

### ISSUE THREAD

**Issue by mschoenlaub** [snarfed/bridgy#1601]
When testing Webmention POSSE with Github, I figured that sending WebMentions directly via `webmentions.io` works now for my page.

However, when bridgy tries to serve the source (generated from the GH issue), it crashes. 

When I look at the [source here](https://brid.gy/log?module=background&start_time=1699199568&key=agdicmlkLWd5ckQLEghSZXNwb25zZSI2dGFnOmdpdGh1Yi5jb20sMjAxMzptc2Nob2VubGF1YjpibG9nLnNjaG9lbmxhdWIuaW5mbzoxDA) i get a HTTP 500 from Bridgy. 

One thing that come to my mind from the top of my head:

- The repo name contains dots. Maybe it's an encoding issue

I'm just quickly typing this together before waking up my kid, so if you need more info ping me and I'll do a nicer writeup, thanks :)

**Comment by snarfed** [comment]
Oof, sorry for the trouble, thank you for reporting! Definitely a Bridgy bug, will fix.
