### ISSUE TITLE
Re-check Mastodon OAuth clients before using

### ISSUE THREAD

**Issue by justincox** [snarfed/bridgy#1602]
I'm unable to set up a connection to Mastodon 4.2.1 and receive the following error message:

> Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

Is there a bug in Bridgy or did Mastodon change something that prevents the connection?

**Comment by snarfed** [comment]
Hmm! I'm not sure. holonet.social, right? Bridgy's Mastodon auth is working fine with other instances right now; I wonder if it's something specific to that instance.

**Comment by snarfed** [comment]
Hmm! I'm not sure. holonet.social, right? Bridgy's Mastodon auth is working fine with other instances right now; I wonder if it's something specific to that instance.

I could debug a bit more if I had an account, but holonet.social says it's closed to new accounts right now, so I'm a bit stuck.

**Comment by snarfed** [comment]
Did you maybe move the instance to a new host since Sept 15? Or recreate it, or do anything else that might have wiped the registered OAuth apps?

In any case, it's easy to wipe this OAuth app from Bridgy's records and have it create a new one. I am still curious what happened though.

**Comment by snarfed** [comment]
Thank you for looking @hugogameiro! Definitely an odd mystery.

For now, I've archived this OAuth app on Bridgy's end and had it generate a new one, client id `nObmt8su2u3MgC94w5R-58R7UEqO6fqjczD_dEVIAT0`. @justincox feel free to try again!

**Comment by hugogameiro** [comment]
I have add another report from a different instance with a similar problem but when authenticating with Buffer. Still had no response from Buffer regarding that. 
It does start to feel that either Mastodon is automatically cleaning/deleting some `oauth_applications` from the database, or Mastodon is failing to save them or there is something else going on that I still couldn't find a pattern/answer for.

**Comment by rg-wood** [comment]
Still doesn't seem to be working for me.

<img width="602" alt="Screenshot 2023-11-06 at 17 09 23" src="https://github.com/snarfed/bridgy/assets/37806009/c6c6f832-4e8f-441a-8254-a7af4d3866d2">

**Comment by snarfed** [comment]
@rg-wood yeah that fix was only for holonet.social, not your instance toot.io. I wonder if we're seeing the same problem there though. Bridgy created the OAuth app below on toot.io at 2023-04-22 10:29:09 UTC with client id `IynWaVvErkoTYf2lDByy5sSH1_m4Bx1Uipr_a3tuLi8`. Could you check with your instance's admin to see if that app is missing on their end?

```json
{
  "id": "16890",
  "name": "Bridgy",
  "website": "https://brid.gy/",
  "redirect_uri": "https://brid.gy/micropub-token/mastodon/finish\nhttps://brid.gy/publish/mastodon/finish\nhttps://brid.gy/mastodon/delete/finish\nhttps://brid.gy/delete/finish\nhttps://brid.gy/mastodon/callback",
  "client_id": "IynWaVvErkoTYf2lDByy5sSH1_m4Bx1Uipr_a3tuLi8",
  "client_secret": "...",
  "vapid_key": "..."
}
```

**Comment by wiegelmann** [comment]
I have access to the toot.io instance database and there no app registered from Bridgy at 2023-04-22.
If you need further debugging help, just let me know.

**Comment by hugogameiro** [comment]
I just opened a ticket on GitHub with all the information I could gather: https://github.com/mastodon/mastodon/issues/27740
Feel free to add any more information there.

**Comment by snarfed** [comment]
Conclusion in https://github.com/mastodon/mastodon/issues/27740 is to periodically call `/api/v1/apps/verify_credentials` to confirm that an app is still valid. Not ideal, but ok.

**Comment by snarfed** [comment]
Deployed in snarfed/oauth-dropins@c127c287ad6841616e4f598185a03fb2f48a34df

**Comment by snarfed** [comment]
Reopening due to #1644. The original fix here in https://github.com/snarfed/oauth-dropins/commit/c127c287ad6841616e4f598185a03fb2f48a34df worked for OAuth clients (apps) that we never generated an access token for, but not for clients that we generated a token for, but then that user revoked the token from inside Mastodon, and then Mastodon garbage collected that client.

The fix for that is probably to delete an account's `MastodonAuth` entity when we get a 401 for it and we raise `DisableSource`. This will fix it for accounts with backfeed enabled, since we poll those regularly, but it won't fix it for accounts with only publish enabled that don't publish via Bridgy very often. 😐

**Comment by snarfed** [comment]
From https://github.com/mastodon/mastodon/issues/27740#issuecomment-1891241015:

> I ran into another edge case with this garbage collection recently. We have a small fraction of users who make API calls infrequently. We hit a case recently where we had just one user on a given instance, they revoked our app's access inside Mastodon, which then garbage collected the OAuth client, and then a new user on that same instance tried to sign up. We hadn't yet made another API call with original user's token, so we hadn't yet gotten a 401 and learned the client had been garbage collected.
> 
> When there's just one outstanding token for a given client, it's easy to call `verify_credentials` first and check it. If there are n outstanding tokens, though, calling `verify_credentials` on all of them would be unfortunate, at best.

**Comment by snarfed** [comment]
OK, I think this is fixed going forward now, a different way.
