### ISSUE TITLE
Bluesky: include embeds in original post discovery

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1611]
Looks like OPD is currently missing original post links that show up in an embed but not in post text. We should look in embeds too! Example: https://bsky.app/profile/snarfed.org/post/3kearseq3532n

```json
{
  "uri": "at://did:plc:fdme4gb7mu7zrie7peay7tst/app.bsky.feed.post/3kearseq3532n",
  "cid": "bafyreigast6fvdbuyxe3hdgeyou6pn2pxjcfgggxxvb3scdf5z564yjm44",
  "value": {
    "$type": "app.bsky.feed.post",
    "text": "Hot on the heels of last week's Bridgy Fed progress, more to report this week: first pass at Bluesky support is feature complete! All basic interactions - user discovery, following, posts, replies, likes, reposts - are working, both directions. 🎉",
    "embed": {
      "$type": "app.bsky.embed.external",
      "external": {
        "uri": "https://snarfed.org/2023-11-15_bridgy-fed-status-update-9",
        "thumb": {
          "$type": "blob",
          "ref": {
            "$link": "bafkreicxbomf3uvbq5xogp3wozcureg5poh44zhzhwhjdy5vhcp5rvuk4u"
          },
          "mimeType": "image/jpeg",
          "size": 665507
        },
        "title": "Bridgy Fed status update",
        "description": "Another brief Bridgy Fed progress report: first pass at Bluesky support is feature complete! All basic interactions – user discovery, following, posts, replies, likes, reposts – are wor…"
      }
    },
    "langs": ["en"],
    "createdAt": "2023-11-15T19:30:47.318Z"
  }
}
```

**Comment by snarfed** [comment]
Surprisingly easy fix ^ ...but oddly it only worked for replies, not likes or reposts. Hrm.

**Comment by snarfed** [comment]
I'm guessing the problem here is that likes and replies don't have the full original post object, and we're not fetching it like we need to before we do OPD. Hrm.

**Comment by snarfed** [comment]
Actually I think this [from this poll log](https://brid.gy/log?module=background&start_time=1700254419&key=agdicmlkLWd5ci0LEgdCbHVlc2t5IiBkaWQ6cGxjOjJqd3lzM2toazN2ZXpvNHM3ZG9kdnJubww) is the smoking gun:

`I 2023-11-17 20:53:37.859508+00:00 Demoting original post links because user tag:bsky.app,2013:did:plc:2jwys3khk3vezo4s7dodvrno did:plc:2jwys3khk3vezo4s7dodvrno doesn't match author did:plc:2jwys3khk3vezo4s7dodvrno marcuslindblom.com`

**Comment by snarfed** [comment]
Yup, looks like that did it. @marcuslindblom this fix didn't backfill your missing like from before, but hopefully they should work going forward. Thanks again for the reports, all!

**Comment by marcuslindblom** [comment]
Awesome 👏

**Comment by jacklorusso** [comment]
This worked for me, thank you so much! Likes and replies showing up perfectly on my site now, cheers
