### ISSUE TITLE
Meetup

### ISSUE THREAD

**Issue by calebhearth** [snarfed/bridgy#1636]
I was just browsing the FAQ and poking around. I noticed that Meetup's GQL api now seems to support RSVPing. https://www.meetup.com/api/schema/#rsvp despite that the Help page says that [it doesn't](https://brid.gy/about#rip-meetup) but maybe I'm misunderstanding the docs.

**Comment by snarfed** [comment]
Hmm. We did a pretty deep dive on this last year in https://github.com/snarfed/bridgy/issues/1065 and concluded - among other things - that new apps on their API requires a $30/mo plan, (https://github.com/snarfed/bridgy/issues/1065#issuecomment-907256594), that the docs are wrong (https://github.com/snarfed/bridgy/issues/1065#issuecomment-1000932882), and that you can't RSVP (https://github.com/snarfed/bridgy/issues/1065#issuecomment-1019213376).

Feel free to try again and see if anything has changed!

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen!
