### ISSUE TITLE
OAuth authentication with Mastodon after revoking access last year

### ISSUE THREAD

**Issue by simoncox** [snarfed/bridgy#1644]
I tried to build out webmentions on my site last year but couldn't get it to work and I may have revoked the Bridgy access on mastodon which is why I think I am not able to authenticate.

When I go to my bridgy URL:  https://brid.gy/mastodon/@simoncox@seocommunity.social
and click the reconnect to Mastodon i get the "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method." error.

Anything you can do?

**Comment by snarfed** [comment]
Ugh, sorry for the trouble @simoncox! Looks like this is #1602 / https://github.com/mastodon/mastodon/issues/27740 still  not fully fixed. I've deleted Bridgy's OAuth client for seocommunity.social, feel free to try again. And I'll reopen #1602 to figure out a better fix.

**Comment by snarfed** [comment]
OK, I think this is fixed going forward now. Thanks for reporting!

**Comment by rezhajulio** [comment]
Hi @snarfed, the same issue is also happened to my account today `@kimiamania@pegelinux.top`

```
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
```

**Comment by snarfed** [comment]
Sorry @rezhajulio! I've reset your account's stored auth, feel free to try logging into Bridgy again.
