### ISSUE TITLE
Mastodon publishing broken?

### ISSUE THREAD

**Issue by JoelOtter** [snarfed/bridgy#1651]
I'm trying to (re)enable publishing on Mastodon (https://brid.gy/mastodon/@joel@otter.garden) using the web UI, put on clicking the button I get this error:

<img width="253" alt="image" src="https://github.com/snarfed/bridgy/assets/2765356/9f9f8fa3-0ec8-49b4-ba96-03d070c989a1">

Is this a known thing/recent thing, or am I doing something wrong? I've tried the usual log out/back in etc!

**Comment by snarfed** [comment]
Ruh roh! Definitely looks broken, I'll look.

**Comment by snarfed** [comment]
Fixed, thanks for the report!
