### ISSUE TITLE
Bluesky publish: support @-mentions, hashtags, links

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1661]
Most or all of the work here is https://github.com/snarfed/granary/issues/675, filing this just to track on the Bridgy side. cc @JoelOtter

**Comment by singpolyma** [comment]
Just came here to report the @-mention thing, so glad it's known :)

**Comment by snarfed** [comment]
Yes!

@singpolyma out of curiosity, what does your Bluesky @-mention HTML look like?

**Comment by snarfed** [comment]
Thanks! Looks like it's:

```html
@<span class=\"vcard\"><a class=\"fn url\" href=\"http://ipg.gay\">ipg.gay</a></span>
```

A couple interesting things here. First, it links to their handle's web site directly, not their bsky.app profile URL, and second, the `@` character is outside the link. Both of those make it a bit trickier to reliably/safely interpret the intent here as an @-mention and not a normal link. (As a comparison, [Bridgy Fed's @-mention detection requires the @ character inside the link](https://fed.brid.gy/docs#web-mention).)

**Comment by snarfed** [comment]
Apart from @-mentions specifically, I'll also echo here what I mentioned in https://github.com/snarfed/granary/issues/675 in general : this is going to be difficult to implement. We have to "disassemble" span-based HTML markup into Bluesky index-based facets. For arbitrary content HTML, we have to parse it, extract just the tags we care about (currently links and microformats2 hashtag `u-categories`), discard other tags (including overlapping ones like the `span` here), extract the plain text, calculate the start and end indices of the tags we care about into the plain text, convert those indices to bytes in the HTML document's character encoding, and populate all of that into Bluesky facets. Phew.

@kevinmarks sent [the old XOXO parser as an example that does this](https://github.com/microformats/xoxo/blob/master/xoxo.py), which is great! Still though. This feels like a nontrivial project.

**Comment by singpolyma** [comment]
Happy to make changes if needed, but to me it's a mention because it 
mentions someone (via vcard) the @ sign isn't part of the microformats and 
so not part of the semantics.

As for the link pointing directly at their handle, it shouldn't be too hard 
to discover bluesky id from handle right? That's what bluesky is doing 
internally.

**Comment by snarfed** [comment]
h-card/vcard is reasonable! We'd probably need a fallback, since most user-level sites/CMSes don't let people attach arbitrary classes to links, but the fallback can be expecting `@` inside the link like BF does.

**Comment by kevinmarks** [comment]
There's a public bluesky api to map handle to id that does not need auth

**Comment by snarfed** [comment]
Yup! Linking to their domain is manageable for Bridgy classic (here) because we know which specific silo you're POSSEing to. It's trickier in Bridgy Fed - which shares much of the underlying logic - because there we federate the same post to multiple networks. In that case, we wouldn't know which of those networks to try to convert this @-mention to, if any.

**Comment by singpolyma** [comment]
>Yup! Linking to their domain is manageable for Bridgy classic (here) 
>because we know which specific silo you're POSSEing to. It's trickier in 
>Bridgy Fed - which shares much of the underlying logic - because there we 
>federate the same post to multiple networks. In that case, we wouldn't know 
>which of those networks to try to convert this @-mention to, if any.

Right, in that case you would have to check which fed protocols the handle 
supports

**Comment by snarfed** [comment]
I more want to know the author's _intent_. May be worth discussing in #microformats.

One approach would be to try to convert to a native @-mention in each network separately. We don't necessarily know if that's what the author themselves want though? Ugh.

**Comment by JoelOtter** [comment]
> One approach would be to try to convert to a native @-mention in each network separately. We don't necessarily know if that's what the author themselves want though? Ugh.

This is something I was meaning to bring up separately. I think it is separate to this ticket though.

**Comment by snarfed** [comment]
Got hashtags working! https://bsky.app/profile/snarfed.bsky.social/post/3kp3bfhk25d2c

**Comment by snarfed** [comment]
Links are working now too, shipped those a while back.

**Comment by snarfed** [comment]
...and @-mentions too, use a `u-category` link to the user's bsky.app profile URL, `at://` URI to their repo or profile record, or DID.

Feel free to try, let me know if you hit any issues!

**Comment by singpolyma** [comment]
Just updated my markup finally to try the mentions https://singpolyma.net/actionstream/reply-https-bsky-app-profile-8/ but it seems like it just comes though as a link? Which isn't too bad, but I think it's different from other mentions maybe: https://bsky.app/profile/singpolyma.net/post/3lau7jr6xk52c

**Comment by snarfed** [comment]
@singpolyma you linked to http://allastud.bsky.social/ , which Bridgy doesn't (yet) understand. Try linking to https://bsky.app/profile/allastud.bsky.social ?

**Comment by singpolyma** [comment]
Oh,  I guess I misread the context here and thought links to the profile domain were supported.
