### ISSUE TITLE
Bluesky truncation

### ISSUE THREAD

**Issue by miklb** [snarfed/bridgy#1666]
Posted a note today that didn't syndicate to Bluesky  

[brid.gy log](https://brid.gy/log?module=default&start_time=1707754539&key=agdicmlkLWd5clQLEg1QdWJsaXNoZWRQYWdlIi1odHRwczovL21pY2hhZWxiaXNob3AubWUvbm90ZS8xNzA3NzU0NDc2Lmh0bWwMCxIHUHVibGlzaBiAgPjZs42MCQw)

`Invalid [app.bsky.feed.post](http://app.bsky.feed.post/) record: Record/text must not be longer than 300 graphemes"}`

I'm currently using `<data class="p-bridgy-omit-link" value="maybe" />` as I was debugging sending webmentions and wanted to eliminate the URL param as the culprit.

_Originally posted by @miklb in https://github.com/snarfed/bridgy/issues/1580#issuecomment-1939180282_

**Comment by snarfed** [comment]
Thanks for filing! Here's the text bridgy tried to post:

`Reading a blog post from a designer I really admire and went to take a look at their markup. Holy divitis Batman! Straight up tailwind soup. No `<main>`. No `<article>` just `<divs>` and `<p>` all the way down. It’s really hard to want to care about this stuff when people… https://michaelbishop.me/note/1707754476f.html`

Looks like we're treating URLs as fixed length in Bluesky, when they're actually not.

**Comment by miklb** [comment]
that's not convenient.

**Comment by snarfed** [comment]
cc @JoelOtter, this and #1665 should be pretty straightforward if you're interested in jumping back in here at all!

**Comment by JoelOtter** [comment]
Happy to take this - is this dependent on the linkification work or do we already turn these particular links into facets?

**Comment by snarfed** [comment]
I think they're independent. My guess is that we default to assuming that text URLs only cost a fixed 23 chars, probably in a constant in `Source`, and we need to override that.

**Comment by snarfed** [comment]
I looked at this a bit, and my hunch ^ wasn't right.

I'm not sure exactly what happened originally here, but I've made some changes to this code, and I suspect it may be fixed. I posted https://bsky.app/profile/snarfed.bsky.social/post/3klxj6ulons2o which was truncated and used "omit link: maybe", and it worked ok. @miklb want to try again?

**Comment by miklb** [comment]
@snarfed success. thank you.
