### ISSUE TITLE
Bluesky: unable to authenticate with domain handle

### ISSUE THREAD

**Issue by TedTschopp** [snarfed/bridgy#1667]
Sorry for the spartan bug report. I am on mobile. 

I use @ted@tedt.org as my handle at BlueSky. I am unable to authenticate from this page. 

I was able to get this working by using my DID, which is a TXT record off my tedt.org that BlueSky uses to validate I own the domain name.  Brid.gy then gets my name right and works ok.  

I suspect you don't have a case in the code to do the DNS lookup.

https://brid.gy/bluesky/start

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! Looks like you're @tedt.org on Bluesky. I'll look into it.

**Comment by TedTschopp** [comment]
No troubles.  I might have been "Holding it wrong"

But once I got the DID, as I saw it was looking that up in the Error Messages, everything worked.  I also didn't quite know what format you wanted the handle in.  Was it @tedt.org or ted@tedt.org or @ted@tedt.org or or or or... 

Perhaps this defect is a UI/UX 'error'

**Comment by snarfed** [comment]
Bluesky handles are just domains, not email addresses or fediverse-style webfinger addresses, so your Bluesky handle is tedt.org, or stylized, @tedt.org.

Bridgy has a couple bugs to fix here. First, it needs to validate handles better, including stripping any leading `@`. Second, it needs to convert input handles to lower case before using them in Bluesky API calls.

We'll fix both of those. Thanks again for reporting!

**Comment by TechLifeWeb** [comment]
Yep, looks like I'm in this boat too. Seeing your comment and changing TechLifeWeb.bsky.social to lower case enabled me to authenticate.

**Comment by snarfed** [comment]
Fixed! Thanks again for reporting!
