### ISSUE TITLE
Backfeeding comments and reactions returns error

### ISSUE THREAD

**Issue by voss** [snarfed/bridgy#1668]
I noticed today that backfeeding comments and reactions to my posts crossposted to Mastodon hasn't been working since September, it seems.

I use Known (1.5) on my [website](https://blog.voss.co/) and using brid.gy for backfeeding which has been working flawless. It appears that around September something changed somewhere, and my Mastodon page on brid.gy shows Error exclamation marks on responses:

![image](https://github.com/snarfed/bridgy/assets/10601/46c15af3-736c-4b6d-9f25-0403c34d97b0)

When I click through on [the error link](https://brid.gy/log?module=background&start_time=1708000733&key=agdicmlkLWd5cloLEghSZXNwb25zZSJMdGFnOnNvY2lhbC5kYXRhLmNvb3AsMjAxMzoxMTE4Nzk1MjUxMDA4Mzk0OTJfZmF2b3JpdGVkX2J5XzEwODI2MjMyMDEzNjA2ODgyNww), I get the message that no log is found:

![image](https://github.com/snarfed/bridgy/assets/10601/b8498808-0f93-4456-9112-6c5a9cd659d9)

I notice it says the last webmention was sent 4 months ago, which seems incorrect, as I've sent webmentions just a few days ago (at least I should've). I didn't change anything in Known, but I am running on a shared server, so potentially something changed with the underlying server settings, but I'm unsure how to check for my webmentions working.

Any good pointers?

**Comment by voss** [comment]
I used webmention.rocks to check if webmentions are sent correctly from my site, and they show up correctly there. From that it seems like webmentions work on the site. Not sure what to check next.

**Comment by snarfed** [comment]
Hi @voss, sorry for the trouble! Looks like your site's webmention endpoint is failing on these webmentions and returning HTTP 500 with this message:

```
Something went wrong.

base64_encode(): Argument #1 ($string) must be of type string, array given
```

**Comment by voss** [comment]
Hi @snarfed,

That's super helpful, thank you!

**Comment by snarfed** [comment]
Welcome! Closing here in favor of https://github.com/idno/known/issues/3199

**Comment by voss** [comment]
Hi @snarfed, I have a stupid question. Do you have a URL where the error message you quoted in https://github.com/snarfed/bridgy/issues/1668#issuecomment-1947387905 shows up in a readable way, or did you find it in your logs? I'm trying to raise the issue with my hosting provider, so see if it's an issue that came about due to upgrading software on the shared hosting, and providing them with an example will probably be helpful.

Thank you!
