### ISSUE TITLE
Bluesky replies are maybe a bit funny?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#1696]
I'm not yet sure if this is bridgy related, but it seems when I post replies they look like this: https://bsky.app/profile/singpolyma.net/post/3koasngjcry2f -- which seems to sort of think it is a reply, but I can't see the parent and it doesn't show up on the parent's thread. Though the parent does show it has "one reply" which I expect is mine and in my own feed it shows on the parent. But no link to the parent like I see on other bsky replies. Feels like there might be some subtle different in the metadata.

**Comment by snarfed** [comment]
Hmm! You're right, that does look broken, and the in-reply-to post itself looks fine on bsky.app. Not sure what's going on here.

**Comment by snarfed** [comment]
^ that commit _might_ fix this. I've deployed it, I'll test manually soon, @singpolyma feel free to try yourself in the meantime!

**Comment by snarfed** [comment]
Tested a reply to a reply manually just now, https://bsky.app/profile/snarfed.bsky.social/post/3korkdv3w332b , it looks right and shows the upstream thread. Tentatively closing. Thanks again for reporting!
