### ISSUE TITLE
How to reset facebook connection

### ISSUE THREAD

**Issue by lumenpink** [snarfed/bridgy#1704]
Hi!

I registered on brid.gy not so long time ago with my site https://lumen.pink and my Facebook account which used to be fb.me/lumen.pink.
But someday I removed the dot from the Facebook name. I changed it everywhere in my site (I hope, at least), disconnect bridge and connect again.
For some reason, the brid.gy extension doesn't recognize the new name and keeps using the name with the dot.
Is there a way to reset it? Or what am I doing wrong?

Many thanks

**Comment by snarfed** [comment]
Hi! The Facebook profile username and link in the browser extension settings are just cosmetic. You're definitely right, ideally the extension should detect username changes like this and update, but it should still backfeed your account fine right now regardless.

**Comment by lumenpink** [comment]
So I think I'm doing really wrong here.
My posts are public. But bridgy still can't see it.
Do you have any clues?

![image](https://github.com/snarfed/bridgy/assets/614844/0c886acf-9574-4ed5-8c6e-db250f515dc5)

**Comment by snarfed** [comment]
Hmm! Sorry for the trouble, I'm not sure, I'll take a look.

**Comment by lumenpink** [comment]
I am sorry. I think I messed up something.
Thanks for your time and patience.

I changed my Facebook profile to English, and apparently it starts to grab the posts.
But now it can't find the counterpart. I tried to  put exactly the same post link tha bridgy found, but without success until now.

**Comment by snarfed** [comment]
Needed a tweak on the server side, I've done that, looks like it's sending webmentions now. Thanks for checking, glad it's working now!

**Comment by lumenpink** [comment]
It's running smoothly now.
Many many thanks!

**Comment by lumenpink** [comment]
The problem is solved!
