### ISSUE TITLE
Bluesky: parse user URLs out of profile bio

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy#1720]
I just tried setting up the bsky integration on brid.gy, and the webmention to `https://brid.gy/publish/bluesky` generates this error:

> Could not find <b>Bluesky</b> account for <b>beesbuzz.biz</b>. Check that your Bluesky profile has beesbuzz.biz in its <em>web site</em> or <em>link</em> field, then try signing up again.

Any idea what’s going on? My bluesky profile ~~is~~ was `fluffy.beesbuzz.biz` and I don’t see any specific way of adding a “web site” or “link” to my profile, but I have a link in my bio.

I'd rather not set my ATProto identity to just `beesbuzz.biz` but that seems to be what's expected by brid.gy (but this isn't actually documented in the integration).

**Comment by fluffy-critter** [comment]
For now I've just changed my bsky profile to `beesbuzz.biz` but I'd rather be able to decouple the origin URL from my profile URL if possible.

**Comment by snarfed** [comment]
Yes! You're right, looks like Bluesky isn't pulling URLs from profile bios right now. Sorry about that, thanks for reporting! Will fix.

**Comment by snarfed** [comment]
This should hopefully be fixed. @fluffy-critter try re-authing with Bluesky into Bridgy and see if it picks up your profile links!

**Comment by fluffy-critter** [comment]
Okay, I've changed my bsky handle back to `fluffy.beesbuzz.biz` although it'll probably be some time before I can test this as I don't have anything to post right now.

**Comment by snarfed** [comment]
No worries! Feel free to reopen if it doesn't work.

**Comment by fluffy-critter** [comment]
Actually I'm not clear on what's going to happen now, because brid.gy shows both beesbuzz.biz and fluffy.beesbuzz.biz as being connected.

Also at the current moment https://fluffy.beesbuzz.biz/ is not resolving thanks to some vagaries of how wildcard DNS records work (although I added a CNAME which should start working within a few hours).

**Comment by fluffy-critter** [comment]
The thing is I'd be wanting to publish posts from beesbuzz.biz but to show up as being fluffy.beesbuzz.biz on bluesky. This is all using automated plumbing from my site commit hooks and I don't want to have to complicate things so that some of my mentions come from a different domain.

**Comment by snarfed** [comment]
> I'd be wanting to publish posts from beesbuzz.biz but to show up as being fluffy.beesbuzz.biz on bluesky

If by "show up as being fluffy.beesbuzz.biz" you mean "post on the [Bluesky account with the handle fluffy.beesbuzz.biz](https://bsky.app/profile/fluffy.beesbuzz.biz)," then yes, that should work now.

**Comment by fluffy-critter** [comment]
Yes, what I mean is:

1. I post a post on https://beesbuzz.biz/blog/ to
2. I send a webmention from the blog entry (on the beesbuzz.biz domain) to https://brid.gy/publish/bsky
3. A link to the post ends up on https://bsky.app/profile/fluffy.beesbuzz.biz

The post itself never appears on fluffy.beesbuzz.biz (which just redirects to beesbuzz.biz).
