### ISSUE TITLE
disqus alternative proposal: Cactus

### ISSUE THREAD

**Issue by fishy** [snarfed/bridgy#1721]
Based on https://brid.gy/about#disqus, I'm suggesting adding [Cactus](https://cactus.chat/) as an alternative to disqus.

Cactus is open source, self-host-able, and based on open source [matrix protocol](https://matrix.org/).

**Comment by snarfed** [comment]
Thanks! Does Tumblr let you install Cactus on Tumblr blogs? That's the specific integration that matters here, not general purpose Disqus anywhere else.

**Comment by fishy** [comment]
> Thanks! Does Tumblr let you install Cactus on Tumblr blogs? That's the specific integration that matters here, not general purpose Disqus anywhere else.

I don't even have a Tumblr account, but my guess would be no as there's very limited support for Cactus in the wild. official integrations are listed on their website [here](https://cactus.chat/docs/integrations/integrations/), I added Cactus support to my (fork) blog system [myself](https://b.yuxuan.org/my-fork-of-polarbearblog).

**Comment by snarfed** [comment]
Got it, thanks. The specific idea here would be if/when Tumblr themselves support anything other than Disqus for commenting on Tumblr blogs. I'll update our docs to clarify that.
