### ISSUE TITLE
Bluesky: Missing newlines in posts

### ISSUE THREAD

**Issue by jphastings** [snarfed/bridgy#1727]
Newlines seem to be ignored when viewing Bluesky posts in Mastodon. 

I use [EchoFeed](https://echofeed.app) to syndicate notes from my blog to Bluesky (and elsewhere); when I look at the Bluesky post from my Mastodon instance or client (as bridged by Brid.gy) then white space is removed. See example below:

[Post on my Mastodon instance](https://hachyderm.io/@byjp.me@bsky.brid.gy/112430343009928803), [Post on Bluesky](https://bsky.app/profile/byjp.me/post/3ksd4xxfks62v)

<img width="1019" alt="Screenshot 2024-05-14 at 11 07 45" src="https://github.com/snarfed/bridgy/assets/42999/60c819e6-c662-4005-9074-ca1eafc8f0e1">

**Comment by snarfed** [comment]
True, sorry for the trouble! This is https://github.com/snarfed/bridgy-fed/issues/990 ; moving to the Bridgy Fed repo and merging into that issue.

**Comment by jphastings** [comment]
No trouble! Thanks & apologies for not spotting the dupe ☺️
