### ISSUE TITLE
Unable to disconnect Nostr to Bsky bridge using Nostr bot

### ISSUE THREAD

**Issue by dmnyc** [snarfed/bridgy#1747]
I tested the Nostr bot to crosspost to bsky, but there doesn't seem to be a way to turn it off.

Emails to feedback@brid.gy have not received a response.

Please add a simple bot command to turn off crossposts. 

A way to delete the Bsky feed would also be appreciated.

**Comment by snarfed** [comment]
Hi! Apologies, looks like your emails ended up in my spam filter. [You can disable your account by blocking the @bsky.brid.gy@bsky.brid.gy fediverse account.](https://fed.brid.gy/docs#opt-out) I don't know all of the ins and outs of the Nostr bridge(s), so I don't know whether or how you'd do that in Nostr, but if you can't, let me know and I can disable your account manually.

**Comment by dmnyc** [comment]
Hi Ryan, no problem. Blocking isn’t a feature on Nostr. Can the account
that reads from
npub1aeh2zw4elewy5682lxc6xnlqzjnxksq303gwu2npfaxd49vmde6qcq4nwx be disabled
and the corresponding Bsky account terminated?

**Comment by snarfed** [comment]
Yes! Done.

**Comment by dmnyc** [comment]
Confirmed - thank you! This was a fun experiment but I’m no longer a Bsky
user and don’t plan to be again.
