### ISSUE TITLE
Would it be possible to delete my bridged bluesky account so i can stop cross posting. Im from nostr

### ISSUE THREAD

**Issue by issanode** [snarfed/bridgy#1752]
My npub is npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve

thank you for your help in deleting my bridged account.

**Comment by snarfed** [comment]
Hi! Hmm, looks like Bluesky themselves may have taken down your bridged account? https://bsky.app/profile/npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve.momostr.pink.ap.brid.gy

**Comment by snarfed** [comment]
Never mind, looks like that was an outage or glitch on their end. I see it now.

@issanode do you have a way to show that you own this account? I see node@nostrplebs.com in your [Nostr profile](https://coracle.social/people/nprofile1qqsp3yzapfwkyw4cr2vt4xx9s27474lj2pkxhqyfqh79n826pv3fkzqpz3mhxw309akx7cmpd35x7um58gurqvph9uq3wamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet59uq3wamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmny9uasjz7c), could you [email me](https://snarfed.org/about) from that address? Or link to your GitHub account in your Nostr profile?

**Comment by snarfed** [comment]
[Alternatively if you can block @bsky.brid.gy@bsky.brid.gy via the bridge, that will disable your account automatically.](https://fed.brid.gy/docs#opt-out)

**Comment by issanode** [comment]
Node@nostrplebs.com is a receive only address. The NIP-05 provider (nostrplebs) offers this service. 

I just go to my github account and share a link to it on my nostr profile?

**Comment by snarfed** [comment]
> I just go to my github account and share a link to it on my nostr profile?

Yes! Either a post or in your profile bio. Or I'm open to any other way you can demonstrate that you own the account.

**Comment by issanode** [comment]
I just added a link to my github profile in the website section of my profile. 
thank you!

**Comment by snarfed** [comment]
Done!

**Comment by issanode** [comment]
Thank you for your help!
