### ISSUE TITLE
Response of "No webmention support"

### ISSUE THREAD

**Issue by adactio** [snarfed/bridgy#176]
Bridgy is pretty amazing: indistinguishable from magic, actually. :-)

I just noticed though: it's starting to show "No webmention support" for my endpoints e.g.:

https://www.brid.gy/log?start_time=1401819090&key=aglzfmJyaWQtZ3lyTAsSCFJlc3BvbnNlIj50YWc6dHdpdHRlci5jb20sMjAxMzo0NzM3ODA4ODY2NDgxNTIwNjRfZmF2b3JpdGVkX2J5XzI4MTU1OTY0Ngw

Any idea what's going on? Is it something I did at my end?

**Comment by snarfed** [comment]
we haven't seen this recur; tentatively closing.
