### ISSUE TITLE
Prompt non-Bridgy users to opt-in upon interaction with bridged content

### ISSUE THREAD

**Issue by kolgza** [snarfed/bridgy#1816]
A non-Bridgy user who likes or comments on a bridged post is unlikely to know that it is a bridged post, and will not know that the original poster will not see the interaction.

If a user interacts with a bridged post, the Bridgy account should DM them requesting them to opt in.

**Comment by snarfed** [comment]
Great idea! We already do this, we added it a bit ago in https://github.com/snarfed/bridgy-fed/issues/1205. It doesn't happen every time, we often filter out these replies earlier in the pipeline, and right now we prioritize that efficiency and scaling somewhat above these kind of UX nice-to-haves. Still, definitely agreed!
