### ISSUE TITLE
Switch to opt out for BlueSky users?

### ISSUE THREAD

**Issue by moyitpro** [snarfed/bridgy#1818]
There has been some discussion on the Fediverse wondering if there is going to be a change from the Bluesky side from being opt-in to opt-out. There has been a lot of discussion since the people on Bluesky follow the bridged account and never bother enabling bridging on their accounts, thus none of the replies and interactions make it to the Fediverse side.

I know this discussion is brought up several times:
https://snarfed.org/2024-10-17_ame-snarfed-org-theres-been-this-breta-moe

I have a few questions:
* What are the technical issues as to why the Bluesky side is currently Opt-in? Is it because of scaling?
* When is the timeline for the Bluesky side to switch from Opt-in to opt-out, while the Fediverse side remains opt-in?

**Comment by snarfed** [comment]
Hi James! Thanks for asking. It's a policy question, not a technical one. There's no technical obstacle to switching Bluesky to opt out. Scaling can be a challenge for any service, and keeping everything opt in does slow adoption, but that's not a primary factor here.

The norms and protocol on Bluesky are meaningfully different than on the fediverse, so opt out does indeed seem more feasible. In general, there are vocal minorities on both sides, and a silent majority somewhere in the middle, but the loud opt out side on Bluesky probably does outnumber the loud opt in side.

However, it's still a policy question, and not necessarily an easy one. I'm not really the best person to navigate these kinds of policy questions; I'd probably want to work with group(s) like [IFTAS](https://about.iftas.org/) or [SWF](https://socialweb.foundation/) or similar to do it in a more meaningfully structured way.

Also, given the backlash from the fediverse a while back, Bridgy Fed probably isn't the best project to take the lead on policy issues like this. I'd love to see other projects take the lead on providing opt out services on Bluesky!

Given all that, this is not something I'm actively thinking about right now. Maybe someday.

**Comment by moyitpro** [comment]
Completely understandable, but here is a suggestion to make opt in easier, as it seems too hard for Bluesky users.

Instead of having Bluesky user follow a certain account to enable it, if a user that haven't followed any bridged account, and decides to follow a bridge account, consider that an opt in. Put a disclaimer on the profile description:

[bridged from <profile link> on the fediverse, Following this account opts you into bridging. Learn more at fed.brid.gy]

There are probably other ideas to make this easier, but opt-in on the Bluesky side is a bit too hard, probably not as difficult for people on the Fediverse since they tend to be more tech savvy to figure it out.

**Comment by snarfed** [comment]
Hmm, interesting! Once someone knows that the bridge exists, though, opting in by following the @ap.brid.gy user seems pretty easy, right? If by "too hard," you mean "too unknown," I definitely agree! Most people don't know that the bridge exists, true.

People follow in lots of ways and places other than profiles, and they don't always read profile bios anyway, so I can't depend on that guaranteeing that they understand that their account will be bridged if they follow. Understanding what the bridge does is tricky enough on its own; I'm not sure I want to add more complexity than I have to.

**Comment by snarfed** [comment]
Merging into https://github.com/snarfed/bridgy-fed/issues/1471
