### ISSUE TITLE
Sync incomplete 

### ISSUE THREAD

**Issue by myfta** [snarfed/bridgy#1845]
How often does the bridge sync from Mastodon to BlueSky? I boosted 4 toots yesterday but only 2 have appeared on BlueSky.

**Comment by snarfed** [comment]
Are the authors of the missing ones bridged? Bridgy Fed only bridges reposts of bridged original posts.

**Comment by myfta** [comment]
That's the reason. Unfortunately one of the original posters even has a
separate un-bridged account on BSkyB.
