### ISSUE TITLE
Bluesky Webmention "Failed"

### ISSUE THREAD

**Issue by sspaeti** [snarfed/bridgy#1850]
Not sure if the error is on my side or anything else with the change of AT Proto. But it has certainly worked before. Just leaving it here in case others have the same issue. I hope it will resolve itself over time.

This is where I get an error - `Failed`. Any way I can check the error? Or any hint of what I'm doing wrong?
![image](https://github.com/user-attachments/assets/6024147f-485f-479e-a313-5c2ddef3ec53)

This is the note https://www.ssp.sh/brain/open-source-data-engineering-projects/ does not work?'
It works mostly on the note below (not always shown?).

### Worked before and works on this note

Worked:
https://bsky.app/profile/ssp.sh/post/3l7ympz5nea2y
![image](https://github.com/user-attachments/assets/f9a49959-be08-4291-9185-7a2c315c2241)

That note still seems to work, sometimes:
https://www.ssp.sh/brain/listmonk/

**Comment by snarfed** [comment]
Hi! You can click the "X hours ago" links to see what happened.

In this case, it looks like the webmention endpoint on https://www.ssp.sh/blog/data-engineering-project-in-twenty-minutes/ is https://webmention.io/ssp.sh/webmention , without a www in your domain, but you need the www. webmention.io treats www and no-www differently.

Bridgy caches webmention endpoints per domain for 2 hours. If you update your endpoint on that page, and then wait two hours, and then click the 🔁 retry buttons for these responses on your user page, it should work.

**Comment by snarfed** [comment]
> Can I have two linked webmention to one page?

Sadly no, webmention only supports a single endpoint per page: https://webmention.net/draft/#sender-discovers-receiver-webmention-endpoint

**Comment by sspaeti** [comment]
Too bad, but that's also what I figured when trying. Again, thank you so much for the help and this great tool. Much appreciated. Closing now.
