### ISSUE TITLE
Bluesky backfeed failing

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#1860]
Unclear what the error means here: https://brid.gy/log?module=background&start_time=1732977427&key=agdicmlkLWd5cmYLEghSZXNwb25zZSJYdGFnOmJza3kuYXBwLDIwMTM6YXQ6Ly9kaWQ6cGxjOmdqbnF6Zml5a3kzejdpZWIzdjY3cm91ei9hcHAuYnNreS5mZWVkLnBvc3QvM2xjNGl2N2Z2NWsydgw

**Comment by snarfed** [comment]
Hi! Are you asking about a different problem here than #1859? Could you elaborate?
