### ISSUE TITLE
Emoji get turned into question marks

### ISSUE THREAD

**Issue by EllyLoel** [snarfed/bridgy#1861]
See the webmentions section on [ellyloel.com/guestbook](https://www.ellyloel.com/guestbook/), there is a mix of webmentions from both Mastodon and Bluesky, most emojis are being turned into `????`, but some aren't.

**Comment by snarfed** [comment]
Hey Elly, sorry for the trouble! I don't know what's going on here, but I suspect it's on your side. Looking at an example Bridgy webmention source page that you show ???? for, https://brid.gy/comment/mastodon/@elly@front-end.social/110143472326627842/112122295587022974 , Bridgy serves it with `Content-Type: text/html; charset=utf-8` and `<meta charset="utf-8">` , and it seems to have the 😊 character ok in it. Maybe check that your site fully supports UTF-8 and Unicode, if you're using MySQL you have the utf8mb4 charset and utf8mb4_*_ci collation on (https://wordpress.org/plugins/database-collation-fix/ ), etc?

**Comment by EllyLoel** [comment]
Oh gosh, I thought it was bridgy, sorry! I know it's not on my end as I've checked and also seen the same issue on other peoples blogs (css-irl.info/ive-been-doing-blockquotes-wrong/) but upon further inspection it seems like it might be a [webmention.io](https://webmention.io/) issue, as I can see the question marks in here: https://webmention.io/api/mentions.jf2?per-page=1000&target=https://www.ellyloel.com/guestbook/
