### ISSUE TITLE
Bluesky comments are not displayed with icon on my website

### ISSUE THREAD

**Issue by wbrakowski** [snarfed/bridgy#1862]
Hi there. I am using bridgy to show bluesky comments on my website. Unfortunately, the icons of the users who wrote the comments are not displayed and it looks weird on my website. Am I missing any setting. Is this even the right place to report this? Thank you for your help.
![grafik](https://github.com/user-attachments/assets/0c0f56cf-29ac-4ad7-b3c7-d6fb6f72a7a6)

**Comment by snarfed** [comment]
Looks like this is WordPress with an old version of the Webmention plugin. Try updating that plugin, and remove the Syndication Links plugin if you have it installed?

**Comment by wbrakowski** [comment]
Thank you for your fast response. I have the newest version of webmention installed, at least I cannot find a newer one. And I uninstalled the syndication link plugin. It still looks the same. Any other idea? Thank you.

![grafik](https://github.com/user-attachments/assets/361d5c8f-0dca-4159-960a-794fcb1bc520)

**Comment by snarfed** [comment]
This isn't causing your problem, but one awkward thing you'll probably want to fix is that right now your HTML is advertising both the plugin's webmention endpoint and webmention.io's. It's also sending the plugin's in an HTTP header, so senders will use that, but you'll probably want to remove webmention.io's since it's needlessly confusing.

```html
<link rel="webmention" href="https://navinsights.net/wp-json/webmention/1.0/endpoint" />
<link rel="http://webmention.org/" href="https://navinsights.net/wp-json/webmention/1.0/endpoint" />
...
<link rel="webmention" href="https://webmention.io/navinsights.net/webmention" />
<link rel="pingback" href="https://webmention.io/navinsights.net/xmlrpc" />
```

**Comment by wbrakowski** [comment]
@snarfed Thank you for your help, it looks like it is fixed now for new webmentions, some old ones are still being displayed weird, but not that big of a deal. I removed the lines that you mentioned. Thank you and have a nice day. :-)
