### ISSUE TITLE
fake comment/like permalinks by adding fragment (e.g. #USERID)

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#215]
we already do this for FB event attendee RSVPs, might as well do it for G+ comments too.

cc @kartikprabhu

status:

* N/A: Facebook comments
* [x] Facebook likes
* [x] Facebook RSVPs
* [x] Twitter favorites
* N/A: Twitter replies
* [x] Google+ comments
* [x] Google+ +1s
* [x] Google+ shares
* [x] Instagram comments
* [x] Instagram likes
* [x] Flickr comments
* [x] Flickr likes

**Comment by snarfed** [comment]
reopening since we should do this for more responses, e.g. FB likes. [inspired by IRC.](http://indiewebcamp.com/irc/2016-01-04#t1451936298403) cc @tantek @dissolve @aaronpk

**Comment by dissolve** [comment]
agreed that omitting u-url is not a good solution. +1 to urls being unique via fragment
