### ISSUE TITLE
backfeed comments and faves from Flickr

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#225]
we have several people POSSEing to Flickr, e.g. https://www.flickr.com/photos/adactio/14604446101, https://www.flickr.com/photos/benwerd/14671472684/

as noted by @tantek in IRC, http://indiewebcamp.com/irc/2014-07-17/line/1405646007

**Comment by herbsmn** [comment]
Hey @kylewm, I would definitely this brid.gy Flickr backfeed with my Flickr Known plugin if you got it working. https://github.com/idno/Flickr

**Comment by skddc** [comment]
This would be great! Just started POSSEing to Flickr from Known as well, and dearly missing the favs and comments now. :)

**Comment by kylewm** [comment]
Thanks for the feedback @herbsmn and @skddc, I'm working on this a little bit at a time in https://github.com/kylewm/granary/commits/flickr-support

**Comment by herbsmn** [comment]
thanks for the update @kylewm! I really appreciate it!

**Comment by snarfed** [comment]
launched! @kylewm want to close this issue?

**Comment by kylewm** [comment]
haha yes thanks!

**Comment by skddc** [comment]
![bluesbrothers](https://cloud.githubusercontent.com/assets/842/9956746/0a968b00-5df3-11e5-8413-fcf916e91f63.gif)

Thanks!!
