### ISSUE TITLE
KeyError in tasks.PropagateResponse.source_url()

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#237]
while propagating [this Response](https://appengine.google.com/datastore/edit?app_id=s~brid-gy&version_id=2.372689861983840287&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo0OTIyOTM5NTM4NzA2NTU0ODgM):

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.377468959475730450/tasks.py", line 394, in send_webmentions
    self.do_send_webmentions()
  File "/base/data/home/apps/s~brid-gy/3.377468959475730450/tasks.py", line 416, in do_send_webmentions
    source_url = self.source_url(target)
  File "/base/data/home/apps/s~brid-gy/3.377468959475730450/tasks.py", line 600, in source_url
    activity = self.activities[urls_to_activity[target_url]]
KeyError: u'http://runkeeper.com/user/adamprocter/activity/399523496?activityList=false&tripIdBase36=6lv6aw&channel=web.activity.shorturl'
```

**Comment by snarfed** [comment]
for the record, we still see this occasionally. the propagate task usually eventually succeeds after a few retries. whee.

**Comment by snarfed** [comment]
still happening.

**Comment by snarfed** [comment]
saw a new symptom of this today: https://console.cloud.google.com/errors/8833924187179738464

```
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/7.395968697636195513/tasks.py", line 469, in send_webmentions
  self.do_send_webmentions()
File "/base/data/home/apps/s~brid-gy/7.395968697636195513/tasks.py", line 496, in do_send_webmentions
  source_url = self.source_url(target)
File "/base/data/home/apps/s~brid-gy/7.395968697636195513/tasks.py", line 691, in source_url
  activity = self.activities[0]
IndexError: list index out of range
```

**Comment by snarfed** [comment]
searched logs for `github.com/snarfed/bridgy/issues/237` on 2017/07/24, didn't find it in the last week at least. may be gone?

**Comment by snarfed** [comment]
error reporting hasn't seen it in the last 30d either:

https://console.cloud.google.com/errors?time=P30D&filter=KeyError&order=LAST_SEEN_DESC&resolution=OPEN&resolution=ACKNOWLEDGED&project=brid-gy

tentatively closing.

**Comment by snarfed** [comment]
It's back, saw an instance today 😂 😭

**Comment by gijswijs** [comment]
I've got two new instances of this issue. You can see one here: https://brid.gy/log?start_time=1648555482&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTUwNTA1MzMyNTQwMTc2Mzg0Nww

Isn't https://github.com/snarfed/bridgy/commit/bb45cb351c48ca9147cc595ffda3178ec54c19ed released yet or didn't that fully resolve the issue?

You want me having a go at it? I can't promise anything, tho.

**Comment by snarfed** [comment]
The bug that wouldn't die. 😁 😢 

Thanks for the reports. bb45cb3 is definitely released, but it was aimed more a different (related) bug, #1124, not at this one directly.

I'm not actively working on this bug right now, but I'm happy to fix these two instances of yours manually, or you're also welcome to use them to debug on your own if you want!

**Comment by snarfed** [comment]
One more example:
- https://twitter.com/kevinmarks/status/1518999221692682242
- tag:twitter.com,2013:1518999221692682242
- agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTUxODk5OTIyMTY5MjY4MjI0Mgw
- https://brid.gy/log?start_time=1651095909&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTUxODk5OTIyMTY5MjY4MjI0Mgw

Notably, this one has four target URLs:
- https://xoxo.zone/@kevinmarks
- https://www.kevinmarks.com/distributed-verify.html
- https://www.kevinmarks.com/
- http://epeus.blogspot.com/2012/12/the-antifragility-of-web.html


```
I 2022-04-27 21:45:08.976727+00:00 Created by this poll: https://brid.gy/log?start_time=1650996502&key=agdicmlkLWd5cg4LEgdUd2l0dGVyIgF0DA
I 2022-04-27 21:45:08.977989+00:00 Starting Response comment tag:twitter.com,2013:1518999221692682242 https://twitter.com/kevinmarks/status/1518999221692682242
...
I 2022-04-27 21:45:09.885008+00:00 Returning 304: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url http://epeus.blogspot.com/2012/12/the-antifragility-of-web.html not in urls_to_activity: None
activities: [] {}
I 2022-04-27 21:45:09.885424+00:00 
Traceback (most recent call last):
  File "/workspace/tasks.py", line 772, in source_url
    activity = self.activities[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/tasks.py", line 579, in do_send_webmentions
    source_url = self.source_url(target)
  File "/workspace/tasks.py", line 778, in source_url
    error(f"""Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
...
oauth_dropins.webutil.flask_util.NotModified: 304 Not Modified: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url http://epeus.blogspot.com/2012/12/the-antifragility-of-web.html not in urls_to_activity: None
activities: []
W 2022-04-27 21:45:09.894081+00:00 Error 304, response body: '<p>Hit https://github.com/snarfed/bridgy/issues/237 KeyError!<br>target url http://epeus.blogspot.com/2012/12/the-antifragility-of-web.html not in urls_to_activity: None<br>activities: []</p>'
W 2022-04-27 21:45:09.894737+00:00 Error sending to endpoint: None
I 2022-04-27 21:45:09.895088+00:00 Returning 304: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url https://www.kevinmarks.com/ not in urls_to_activity: None
activities: [] {}
I 2022-04-27 21:45:09.895281+00:00 
Traceback (most recent call last):
  File "/workspace/tasks.py", line 772, in source_url
    activity = self.activities[0]
IndexError: list index out of range
...
oauth_dropins.webutil.flask_util.NotModified: 304 Not Modified: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url https://www.kevinmarks.com/ not in urls_to_activity: None
activities: []
...
```

**Comment by snarfed** [comment]
Another example:
- https://twitter.com/btconf/status/1517140237159256070
- https://brid.gy/log?start_time=1650765136&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTUxNzE0MDIzNzE1OTI1NjA3MAw
- https://console.cloud.google.com/datastore/entities;kind=Response;ns=__$DEFAULT$__/edit;key=0%252F%257C8%252FResponse%257C45%252Fname%253Atag%253Atwitter.com%252C2013%253A1517140237159256070?project=brid-gy

Only one target URL: https://beyondtellerrand.com/events/dusseldorf-2022/schedule/monday

```
I 2022-04-24 01:52:16.070367+00:00 Created by this poll: https://brid.gy/log?start_time=1650551488&key=agdicmlkLWd5chcLEgdUd2l0dGVyIgptYXJjdGhpZWxlDA
I 2022-04-24 01:52:16.070896+00:00 Starting Response comment tag:twitter.com,2013:1517140237159256070 https://twitter.com/btconf/status/1517140237159256070
I 2022-04-24 01:52:16.072150+00:00 Returning 304: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url https://beyondtellerrand.com/events/dusseldorf-2022/schedule/monday not in urls_to_activity: None
activities: [] {}
I 2022-04-24 01:52:16.072404+00:00
Traceback (most recent call last):
  File "/workspace/tasks.py", line 772, in source_url
    activity = self.activities[0]
IndexError: list index out of range
...
target url https://beyondtellerrand.com/events/dusseldorf-2022/schedule/monday not in urls_to_activity: None
activities: []
```

**Comment by snarfed** [comment]
Key lead so far: both `Response.activities_json` and `.urls_to_activity` are empty in these cases.

**Comment by snarfed** [comment]
Trying out a very brute force fix here. Not hugely confident in it, I give it 50/50 that it fixes the bug and doesn't introduce other problems. Will see!

**Comment by snarfed** [comment]
Fwiw, this fixed the two examples above from earlier today. I had to delete their existing `Response` entities, than ran discover on the tweets, and Bridgy created new `Response` entities with `activities_json` populated, and propagate worked. I just also expect the fix to have other unintended side effects. 🤷🤷🤷

**Comment by snarfed** [comment]
Confirmed, this change made us add and propagate arbitrary responses (likes, reposts, etc) on other people's tweets. Eg https://brid.gy/twitter/BillSeitz is now full of likes and retweets of https://twitter.com/meekaale/status/1517839838816477184, which seems totally unrelated. I can't even find how that tweet is connected to @BillSeitz. 🤦

Reverting and reopening.

**Comment by snarfed** [comment]
Still useful learning though. I guess the fix is to keep extending the logic for populating `Response.activities`, in this case if the response links to the user's site.

**Comment by snarfed** [comment]
Thanks for the details, and sorry for the trouble! Still hoping to fix the actual bug here eventually, but for now, I've fixed this one manually.

**Comment by gRegorLove** [comment]
Another one: https://brid.gy/log?start_time=1656352924&key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTU0MTIwNTY1ODQ1MTU3NDc4NAw&module=background

```
D 2022-06-27 18:02:04.257321+00:00 Params: [('response_key', '[agdicmlk...](https://console.cloud.google.com/datastore/entities;kind=Response;ns=__$DEFAULT$__/edit;key=0%252F%257C8%252FResponse%257C45%252Fname%253Atag%253Atwitter.com%252C2013%253A1541205658451574784?project=brid-gy)')]
I 2022-06-27 18:02:04.365763+00:00 Source: OpenMentions (Twitter) openmentions, https://brid.gy/twitter/openmentions
I 2022-06-27 18:02:04.543324+00:00 Created by this poll: https://brid.gy/log?start_time=1656287751&key=agdicmlkLWd5chkLEgdUd2l0dGVyIgxvcGVubWVudGlvbnMM&module=
I 2022-06-27 18:02:04.543975+00:00 Starting Response comment tag:[twitter.com](http://twitter.com/),2013:1541205658451574784 https://twitter.com/sxybio/status/1541205658451574784
I 2022-06-27 18:02:04.546026+00:00 Returning 304: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url https://openmentions.com/topics/conversation-starters/ not in urls_to_activity: None
activities: [] {}
I 2022-06-27 18:02:04.546390+00:00 
Traceback (most recent call last):
  File "/workspace/[tasks.py](http://tasks.py/)", line 779, in source_url
    activity = [self.activities](http://self.activities/)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/[tasks.py](http://tasks.py/)", line 585, in do_send_webmentions
    source_url = self.source_url(target)
  File "/workspace/[tasks.py](http://tasks.py/)", line 785, in source_url
    error(f"""Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/flask_util.py](http://google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/flask_util.py)", line 221, in error
    abort(int(status), msg, **kwargs)
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/werkzeug/exceptions.py](http://google.python.pip/pip/lib/python3.9/site-packages/werkzeug/exceptions.py)", line 879, in abort
    _aborter(status, *args, **kwargs)
  File "/layers/[google.python.pip/pip/lib/python3.9/site-packages/werkzeug/exceptions.py](http://google.python.pip/pip/lib/python3.9/site-packages/werkzeug/exceptions.py)", line 862, in __call__
    raise [self.mapping](http://self.mapping/)[code](*args, **kwargs)
oauth_dropins.webutil.flask_util.NotModified: 304 Not Modified: Hit https://github.com/snarfed/bridgy/issues/237 KeyError!
target url https://openmentions.com/topics/conversation-starters/ not in urls_to_activity: None
activities: []
W 2022-06-27 18:02:04.546860+00:00 Error 304, response body: '<p>Hit https://github.com/snarfed/bridgy/issues/237 KeyError!<br>target url https://openmentions.com/topics/conversation-starters/ not in urls_to_activity: None<br>activities: []</p>'
W 2022-06-27 18:02:04.547088+00:00 Error sending to endpoint: None
I 2022-06-27 18:02:04.547259+00:00 Some targets failed
```

**Comment by snarfed** [comment]
Thanks! cc @lordmatt. Root cause here for both of the recent failed wms on https://brid.gy/twitter/openmentions is a bit different. The original tweet https://twitter.com/lordmatt/status/1541205044757929986 mentions (links to) https://openmentions.com/topics/conversation-starters/, and it sent correctly. However, it's not a syndicated copy, either explicitly or implicitly, and both of these are replies to it, so they shouldn't have been picked up or sent as wms at all. I'll file a new issue.

**Comment by snarfed** [comment]
Added an `assert` in https://github.com/snarfed/bridgy/commit/7438d4d2d095b88793940d41a65873f1d7b0a9c3 at poll time, when these Respones with empty `activities` are created, and it started firing immediately. Collected nine examples, all reply tweets, that break down into a few categories. Useful!

- Reply by someone else that links to user's site
  - https://brid.gy/twitter/Flo_H : https://twitter.com/supergraf/status/1545141739513692160, [log](https://brid.gy/log?start_time=1657300955&key=agdicmlkLWd5chwLEgdUd2l0dGVyIg9CZXRyaWVic2ZhbWlsaWUM&module=background)
  - https://brid.gy/twitter/FCCIDio : https://twitter.com/andrew771211/status/1545323873851285504, [log](https://brid.gy/log?start_time=1657298787&key=agdicmlkLWd5chQLEgdUd2l0dGVyIgdGQ0NJRGlvDA&module=background)
  - https://brid.gy/twitter/EdgarInsider : https://twitter.com/picadix829/status/1545435065580228608, [log](https://brid.gy/log?start_time=1657300211&key=agdicmlkLWd5chkLEgdUd2l0dGVyIgxFZGdhckluc2lkZXIM&module=background)
- Reply _by user_ that links to user's site
  - https://brid.gy/twitter/Betriebsfamilie : https://twitter.com/Betriebsfamilie/status/1545404764711751680, [log](https://brid.gy/log?start_time=1657300770&key=agdicmlkLWd5chwLEgdUd2l0dGVyIg9CZXRyaWVic2ZhbWlsaWUM&module=background)
  - https://brid.gy/twitter/EddieHinkle : https://twitter.com/EddieHinkle/status/1545226690930130944, [log](https://brid.gy/log?start_time=1657300772&key=agdicmlkLWd5chgLEgdUd2l0dGVyIgtFZGRpZUhpbmtsZQw&module=background)
  - https://brid.gy/twitter/JamieTanna : https://twitter.com/JamieTanna/status/1545387849125609473, [log](https://brid.gy/log?start_time=1657300195&key=agdicmlkLWd5chcLEgdUd2l0dGVyIgpKYW1pZVRhbm5hDA&module=background)
- Unrelated reply, same one for all three users below!, haven't found a connection to any of them yet. https://twitter.com/librarianbe/status/1545419836079185922
  - https://brid.gy/twitter/_vincentritter, [log](https://brid.gy/log?start_time=1657294859&key=agdicmlkLWd5chsLEgdUd2l0dGVyIg5fdmluY2VudHJpdHRlcgw&module=background)
  - https://brid.gy/twitter/ShortFormErnie, [log](https://brid.gy/log?start_time=1657300120&key=agdicmlkLWd5chsLEgdUd2l0dGVyIg5TaG9ydEZvcm1Fcm5pZQw&module=background)
  - https://brid.gy/twitter/RolandLegrand, [log](https://brid.gy/log?start_time=1657299000&key=agdicmlkLWd5choLEgdUd2l0dGVyIg1Sb2xhbmRMZWdyYW5kDA&module=background)

**Comment by snarfed** [comment]
The three different users above with the same tweet triggering this raise an interesting point: we don't separate `Response`s by user. That tweet is stored in the same single `Response` that's shared by all three users' poll and propagate tasks.

I don't know if that's a problem. If OPD looks up stored syndication links for just the user it's operating on, we could miss the other users' synd links. We should also look to see if any `Response` handling isn't transactional and needs to be. Otherwise, maybe this is ok?

**Comment by snarfed** [comment]
^ e9ae80d is a partial fix here. In `PropagateTask.source_url()`, if we find that `Response.activities_json` is empty, we use `Response.response_json` instead. This still has problems though: in the examples above, we don't crash, but instead we now miss the targets entirely. I still haven't come up with a test that reproduces that. 😐

**Comment by snarfed** [comment]
^ This fix is looking promising, testing worked. Tentatively closing!

First opened this bug 8y ago, what a run. End of an era. 🤞🤞🤞
