### ISSUE TITLE
signup API for @idno

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#240]
@benwerd recently mentioned that @idno would like an API for signup, ie a way that Known users can click a button inside Known to start bridgy signup, go directly to the silo oauth prompt, and then redirect back to Known, ideally without seeing a bridgy page at all - or if they do, make it an obvious part of the known UX flow.

i like it! totally doable. here's a straw man: we add a query parameter to the bridgy signup URL to specify where to redirect the user after it's done. if provided, and (probably) if it matches a whitelist, we'd redirect there at the end instead of to the bridgy user page.

open questions:
* i think i want the redirect whitelist, but that doesn't really work for self-hosted known instances. we could initially do this for only known-as-a-service, and see how it goes.
* the silo oauth prompts will show bridgy's name and logo, not known's. this could be a problem for novice users, and could cause dropoff. one solution is to use separate api keys with known's name and logo, but i'd rather not do that if we can help it.
* user education. this will blur the line between known and bridgy, and contribute to people thinking that this is a known feature instead of a separate service. that's fine with me, but it will cause problems when they need support. for example, i (maybe?) still want users to know about their brid.gy user page, which shows info on their recent responses. (in the long run, known might prefer to do its own backfeed, which totally makes sense, but is a lot of work to tackle.)

@benwerd, thoughts?

**Comment by benwerd** [comment]
We just pushed this into core. However, the links don't seem to be working right now?

Still, awesome.

**Comment by kylewm** [comment]
whoa awesome, which links aren't working?

**Comment by benwerd** [comment]
eg:

https://brid.gy/twitter/start?feature=listen&callback=http%3A%2F%2Fwerd.io%2Faccount%2Fbridgy%2F

**Comment by benwerd** [comment]
I'm actually testing with my localhost domain idno.dev, so I was also using:

https://brid.gy/twitter/start?feature=listen&callback=http%3A%2F%2Fidno.dev%2Faccount%2Fbridgy%2F

**Comment by kylewm** [comment]
You actually have to use https://www.brid.gy ... it's some App Engine limitation.

**Comment by benwerd** [comment]
Aha. We have the same requirement on our hosted service (to do with CNAME rules and dynamic IPs).

Made those changes and it appears to work like a charm!

**Comment by kylewm** [comment]
Phew, glad it was that easy. Congrats on the feature, looking forward to seeing it in action!!

**Comment by benwerd** [comment]
Thanks for building such a simple interface!

**Comment by snarfed** [comment]
yay, excited to see this go out. nice work guys!
