### ISSUE TITLE
support HTML meta http-equiv=refresh redirects

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#253]
right now, when we resolve URLs and follow redirects in `util.follow_redirects()`, we support HTTP 301/2 and the HTTP `Refresh` header, but not HTML `<meta http-equiv=refresh ...>`.

this is currently biting @pierreozoux (https://www.brid.gy/twitter/pierreozoux). for example, http://www.pierre-o.fr/s/9.htm doesn't advertize a webmention endpoint, but includes an HTML meta refresh redirect to http://www.pierre-o.fr/blog/2014/08/02/permashortlinks/ , which does.

**Comment by slyduda** [comment]
[This is what I was thinking so far.](https://github.com/slyduda/webutil/blob/main/util.py#L1997) I haven't implemented any tests quite yet. 

I think the place you directed me first was correct because that is the first point that grabs contents.

**Comment by slyduda** [comment]
I see what you are referring to now [here](https://github.com/snarfed/bridgy/blob/main/util.py#L293). I will add the same `parse_http_equiv` function that I added in the webutils package. As for performance, this will require that all attempt to get the webmention target must now be parsed with BeautifulSoup. Not sure how much overhead that will add, but I will make those changes.

**Comment by snarfed** [comment]
Thank you for the details! And for noticing the overhead. Webmention endpoints are indeed cached, but per domain, and Bridgy regularly runs webmention discovery on 10-20k domains. That's currently ~2qps steady state, so I'm reluctant to switch all of that to GETs and start downloading all of those pages:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/778068/196588318-a837e2b6-37ed-46ea-87ee-a532f81f14c7.png">

How about adding it to `discover` in https://github.com/snarfed/webutil/blob/main/webmention.py instead? That already downloads the full response body.

**Comment by snarfed** [comment]
I've also asked on #indieweb-dev if anyone else has experience or thoughts: https://chat.indieweb.org/dev/2022-10-19#t1666148871932600

**Comment by slyduda** [comment]
> How about adding it to `discover` in https://github.com/snarfed/webutil/blob/main/webmention.py instead? That already downloads the full response body.
Sure! I can do that, it will still require doubling get requests though since an additional search through the content will have to be made.

If this is not feasible due to performance though, I completely understand and am willing to scrap my idea.

**Comment by snarfed** [comment]
Hmm! `discover` already makes a GET request, and parses the HTML contents if there's no webmention endpoint in the headers, so it shouldn't need any additional HTTP requests or expensive parsing, right?

**Comment by slyduda** [comment]
Right, but upon getting that http-equiv from the document head in the parsed request another request must be made to get the webmention endpoint in new url.

For example:
discover(url='https://slyduda.com/p/29835') -> 'https://slyduda.com/post/0238975ur290834572038945' (http-equiv)
discover(url='https://slyduda.com/post/0238975ur290834572038945') -> 'https://webmention.io/slyduda.com/webmention' (webmention meta tag)

And now I am realizing that you're saying that it wouldn't necessarily impact performance because we either find the webmention url and if we don't we find a http-equiv! Got it!!! :)

**Comment by slyduda** [comment]
Confirmed working for me after refreshing past response!

**Comment by snarfed** [comment]
Woo, awesome, glad to hear it! Thank you again!

**Comment by slyduda** [comment]
Noticed that webmentions are not being sent to the correct target. This is okay-ish for my use case, but definitely ideal. I would like to add a third return value to the discover function in the webutil package that gets populated with the last client-side redirect if any. In Bridgy discover we can replace `target`'s value with the `corrected_target` value if it is returned by the discover function. This is a little less elegant than I had hoped for, but would be the easiest way to fix this last little issue.

Apologies for not catching this earlier. I got really happy when I saw "Sent!" and I forgot to check the webmention results.

**Comment by snarfed** [comment]
Good follow-up! This can definitely be an awkward surprise, but it's actually intended webmention behavior. As part of receiving a webmention, the receiver [fetches the source page and checks that it contains a link to the target](https://webmention.net/draft/#webmention-verification). If we change the target, the receiver (webmention.io here) will look for a link that doesn't exist in the source page, so verification will fail. It's up to the receiver to handle shortlinks and other redirecting targets.

[The spec discusses this briefly](https://webmention.net/draft/#request-verification):

> The receiver SHOULD check that target is a valid resource for which it can accept Webmentions. This check SHOULD happen synchronously to reject invalid Webmentions before more in-depth verification begins. What a "valid resource" means is up to the receiver. For example, some receivers may accept Webmentions for multiple domains, others may accept Webmentions for only the same domain the endpoint is on.

For webmention.io, I expect it would return these wms with the shortlink targets, and you'd have to merge them on your end. Some background in https://github.com/aaronpk/webmention.io/issues/92.

**Comment by snarfed** [comment]
(Oh btw, with your client side redirect change, the `requests.Response` that `discover` returns will now contain the final redirected URL, so users can get it if they do need it.)

**Comment by slyduda** [comment]
> For webmention.io, I expect it would return these wms with the shortlink targets, and you'd have to merge them on your end. Some background in https://github.com/aaronpk/webmention.io/issues/92.

Thank you for the background. This makes sense. From what I'm gathering, in order for what I have described to work the whole spec would have to account for client side redirects which doesnt seem feasible. Though, it works enough now and I can definitely easily provide two values in the webmention url fetch from `webmention.io`!

Thank you so much for the help and guidance! I really appreciate it.

**Comment by snarfed** [comment]
You're welcome! Glad this is still working out ok. Feel free to jump into chat or https://github.com/w3c/webmention/issues to discuss more, eg https://github.com/w3c/webmention/issues/103 or others in https://github.com/w3c/webmention/issues?q=is%3Aissue+redirect !
