### ISSUE TITLE
publish facebook events (not currently supported in FB API)

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#274]
@tantek [suggested adding event support to Facebook publish](http://indiewebcamp.com/irc/2014-08-30#t1409418027797). great idea!

...argh, except the FB API doesn't allow creating events. boo!

https://developers.facebook.com/docs/graph-api/reference/v2.1/user/events#publish
https://developers.facebook.com/docs/graph-api/reference/v2.1/event#publish

leaving this open as a placeholder to capture more info in case (hope) this changes.

**Comment by pierreozoux** [comment]
This is sad :/ :-1: for facebook... (no middle finger emoji :/ )

**Comment by snarfed** [comment]
were you perhaps looking for :hankey: ? :P

**Comment by pierreozoux** [comment]
Luckaly we still have ascii art :) https://github.com/idno/Facebook/issues/22

**Comment by edrex** [comment]
just found this :(
hi @pierreozoux  :D

**Comment by snarfed** [comment]
bridgy publish for facebook will disappear soon (#817), so I'm closing open issues for it. sad. feel free to holler if you disagree.
