### ISSUE TITLE
backfeed FB wall posts from other people (not currently in API)

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#316]
...at least, if/when we know the mf2 to do it. example: https://www.facebook.com/snarfed.org/posts/10101706354683423 .

cc @colintedford @tantek, inspired by http://indiewebcamp.com/irc/2014-12-09#t1418147855260 :

```
colintedford: When you post to someone else's timeline on Facebook, does it also appear on your own in some way?
...
colintedford: Anyway, tantek suggested handling "other-person-posts-to-your-timeline" as a "guest post", which is sensible
tantek: colintedford: just based on previous existing behavior :)
colintedford but I was considering treating it like a comment / mention to my homepage
```

**Comment by tantek** [comment]
Some research and thoughts on what "wall" posts mean and/or how they could work: https://indieweb.org/wall

**Comment by snarfed** [comment]
i _think_ we may be able to get these out of the facebook API. sounds like they should already come back in the API calls we already make, as posts with `status_type=wall_post`, and content in the `story` field. https://developers.facebook.com/docs/graph-api/reference/v2.10/post#fields

next step here is to find a recent example of an FB wall post. i suspect this feature is now demoted enough that examples in the wild may be rare.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/316" class="u-in-reply-to"></a>Are birthday wishes likely the most common examples of this type of post? 
eg: https://www.facebook.com/ChrisAldrich/posts/10101384341809765 (sadly the audience for this may not be public, and worse, doesn't seem to be changeable.)

**Comment by snarfed** [comment]
@chrisaldrich thanks! those are definitely wall posts.

sadly i don't get yours from either `/[user]/feed` or `/[user]/posts`, and i don't see any other likely edge endpoints: https://developers.facebook.com/docs/graph-api/reference/user/#edges

https://developers.facebook.com/docs/graph-api/reference/v2.10/post/ implies that i may need to read it from the _author's_ user object, with their access token - https://developers.facebook.com/docs/graph-api/reference/v2.10/post/#readperms - which i don't have.

ah well.

**Comment by tantek** [comment]
Since I so rarely post myself on FB, I think you should be able to find some "public" (not friends-only) wall posts from others on my profile if you scroll just a little: https://facebook.com/tantek.celik - not logged in myself right now (away for a bit) or else I'd provide a direct link.

Also we should be sure to distinguish "wall posts" from PersonA > PersonB, from just posts (e.g. photos) that you're "tagged in" showing up on your profile / timeline.

**Comment by tantek** [comment]
@snarfed re: "don't get yours from either /[user]/feed or /[user]/posts" - is there an endpoint for a user's "timeline" somewhere? That could have more than just their "feed" (stuff they see) or their "posts" (stuff they post).

Another possible route to finding these is - is there an endpoint for all of a user's notifications from which you could retrieve the "posted on your wall" and "tagged you in a post" items?

**Comment by snarfed** [comment]
> is there an endpoint for a user's "timeline" somewhere?

yup, /[user]/feed, but it only includes wall posts if you have the user_posts permission for their *author* - https://developers.facebook.com/docs/graph-api/reference/user/feed#permissions - which we'll only have if they're also bridgy user. (sorry, should have mentioned that bit of research.)

i could implement it anyway, for the rare bridgy user case, but i wouldn't prioritize that. I've spent too much of my life chasing down FB's endlessly complicated data and permission models. :P

> is there an endpoint for all of a user's notifications

sadly no. details in #616.

**Comment by snarfed** [comment]
[Facebook support is dead](https://brid.gy/about#rip-facebook) (#817, #826), so I'm closing this as obsolete. feel free to reopen if you have any concerns!
