### ISSUE TITLE
publish: support location (not in Facebook API)

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#317]
looks like we'd just need to convert p-location and/or u-checkin to the place param in the/user/feed POST.

https://developers.facebook.com/docs/graph-api/reference/v2.2/user/feed

(thanks for not mentioning that I hand waved past a hard part or two there. nice of you. :P)

status:
- [x] _Twitter_: done!
- [x] _Flickr_: done!
- [ ] _Facebook_: difficult, [requires UI or FB place URL in post (inconsistent)](https://github.com/snarfed/bridgy/issues/317#issuecomment-169516187).
- _Instagram_: API doesn't allow publishing.
- _Google+_: API doesn't allow publishing.

**Comment by tantek** [comment]
I think this would be useful as an aspect of *any* post type, not just "check-ins". E.g. notes have locations, photos have locations etc. similar to making #459 apply to more than just photos.

Encountered need: http://indiewebcamp.com/irc/2015-09-01/line/1441139465398

**Comment by snarfed** [comment]
twitter now supports this too: https://dev.twitter.com/rest/reference/post/statuses/update

**Comment by petermolnar** [comment]
for Flickr, I suggest looking for a h-geo tag, as Flickr accepts latitude/longitude.

This is a snippet from a PHP code that does this for Flickr:
```
$params = array (
		'format' => 'php_serial',
		'method'=>'flickr.photos.geo.setLocation',
		'photo_id'=>$phiID,
		'lat'=>$latitude,
		'lon'=>$longitude,
);

$oauth->makeReq('https://api.flickr.com/services/rest/',$params);
```

**Comment by kylewm** [comment]
@petermolnar I pushed some changes that should make this work for Flickr. Could you test it when you have a chance? Thanks!

**Comment by snarfed** [comment]
the catch with facebook that i [hand waved past initially](https://github.com/snarfed/bridgy/issues/317#issue-51906728) is that we have to use a location from their database. specifically, we'd [search for candidates](https://developers.facebook.com/docs/graph-api/using-graph-api#search), choose one somehow, and includes its id in the [`place` param with our publish call](https://developers.facebook.com/docs/graph-api/reference/v2.2/user/feed#publish).

the "choose one" part is the hard part. it implies UI, or at least multiple round trips and more interface functionality in bridgy publish, [which we're trying to avoid](https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb).

we could do it if they include a link to the facebook place page in their post, though. something like `a.p-location.u-url`? afaik that mf2 doesn't actually make sense, but something similar?

**Comment by kylewm** [comment]
`.u-location` or `.p-location.h-card > .u-url` would work

A tiny bit of exploration, some place URLs are like

https://www.facebook.com/The-Creamery-276261304155/ or
https://www.facebook.com/Kathys-Kreative-Kakes-139715692377/

The place ID is predictably the # after the slug.

Some are like https://www.facebook.com/bstreetandvine (this seems rare, I wonder if they were grandfathered in)

Where you can request graph.facebook.com/v2.5/bstreetandvine and get
```
{
  "name": "B Street and Vine",
  "id": "141366356825"
}
```

**Comment by kylewm** [comment]
Also, for reference I tried to implement place/location for Facebook in silo.pub

I used `https://graph.facebook.com/v2.5/search?type=place&center=lat,lng&distance=500&q=place_name` which is actually pretty decent PROVIDED you have a place_name if you don't, it'll check you in to the nearest venue of any kind (in my case it was a massage place)

**Comment by snarfed** [comment]
bridgy publish for facebook will disappear soon (#817), so I'm closing open issues for it. sad. feel free to holler if you disagree.
