### ISSUE TITLE
publish: FB like POSTs sometimes 404

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#331]
[example log.](https://www.brid.gy/log?start_time=1420189075&key=aglzfmJyaWQtZ3lyRAsSDVB1Ymxpc2hlZFBhZ2UiHWh0dHA6Ly90YW50ZWsuY29tLzIwMTUvMDAyL2YyDAsSB1B1Ymxpc2gYgICAgICAgAoM)

we're POSTing to e.g. `https://graph.facebook.com/NovemberProjectSF_568825249920639/likes`, but maybe it should be either `https://graph.facebook.com/568825249920639/likes` or `https://graph.facebook.com/NovemberProjectSF/568825249920639/likes`? not sure which yet, or if either will work.

...but sometimes that URL format works. maybe the difference is user id vs username? post object id vs photo? [here's an example that worked](https://www.brid.gy/log?start_time=1419615889&key=aglzfmJyaWQtZ3lyhAELEg1QdWJsaXNoZWRQYWdlIl1odHRwczovL3NuYXJmZWQub3JnLzIwMTQtMTItMjZfam9zaHVhLXJlZHN0b25lLWRvdWJsZS1zdXJmLXNlc3Npb24tdG9kYXktNmFtLWF0LXBsYXlhLWhlcm1vc2EMCxIHUHVibGlzaBiAgICAgICACgw) by POSTing to `https://graph.facebook.com/753470156_10155052328930157/likes`

thanks to @tantek for the report!

**Comment by tantek** [comment]
This is very odd as all I did was copy the URL of the hyperlinked date/time from several phosts/photos on FB - confusing that somehow they are treated differently by FB.

**Comment by snarfed** [comment]
ah, no, sorry if i was unclear. bridgy breaks down the `u-like-of` URL you give it, then reconstructs variants when it needs them. the maybe bad URL is a `graph.facebook.com` API URL.

**Comment by tantek** [comment]
Just manually iterated through all the likes on http://tantek.com/2015/002/f and of the 10 there, only http://tantek.com/2015/002/f2 and http://tantek.com/2015/002/f3 caused the 404 bug (and consistently so). All the other http://tantek.com/2015/002/f posts (f1-f10) seemed to work fine.

**Comment by snarfed** [comment]
thanks for the info!

**Comment by snarfed** [comment]
looks like this is because the FB API doesn't like usernames anywhere except in bare object lookups. specifically, ids like `NovemberProjectSF_568825249920639` definitely don't work. it should be the NovemberProjectSF page id instead.

sounds like this is actually the same problem as #349.

**Comment by snarfed** [comment]
confirmed, at least for reading, but should apply to writing too. [/276430682493432_568825249920639/likes](https://developers.facebook.com/tools/explorer?method=GET&path=276430682493432_568825249920639%2Flikes&version=v2.2&) works,  [/NovemberProjectSF_568825249920639/likes](https://developers.facebook.com/tools/explorer?method=GET&path=NovemberProjectSF_568825249920639%2Flikes&version=v2.2&) doesn't.

**Comment by snarfed** [comment]
this is mostly fixed by the changes in #349 and nearby. the part that's not fixed is #350, which is a whole other can of worms. :/
