### ISSUE TITLE
add GitHub support

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#333]
...specifically, publish for POSSEing issues and issue comments and backfeed for issue comments. (anything else?)

of all the "add silo X" feature requests we have, this is the one i'd use, and use a lot. i don't expect to implement it anytime soon, but i'd love to use it!

(#326 - Instagram publish support for likes - is maybe the one other i'd use, but we already support IG backfeed, so it only half counts. :P)

**Comment by snarfed** [comment]
(for posterity, i currently back up my github issues with https://github.com/snarfed/misc/blob/master/export_github_issues.py )

**Comment by aaronpk** [comment]
Plain text posts could be POSSEd to github as a Gist!

**Comment by aaronpk** [comment]
I've done some experimental POSSE to GitHub, and have found the following patterns useful:

If no `in-reply-to` property, then create a gist.

If `in-reply-to` matches:
* `/https:\/\/github\.com\/.+\/.+(?:\/issues)/`: open a new issue. Use the "name" of the h-entry as the issue name. If no name present, try to construct one from the first sentence of the entry content.
* `/https:\/\/github\.com\/.+\/.+\/issues(?:\/\d+)/`: reply to an issue thread

**Comment by tantek** [comment]
Suggested title edit: Bridgy Publish to Github: note->gist, reply-> issues/ or issues/n

**Comment by snarfed** [comment]
if anyone's interested in tackling this, i've written up [comprehensive instructions on how to add a new silo to bridgy.](https://github.com/snarfed/bridgy#adding-a-new-silo) feel free to jump in!

**Comment by snarfed** [comment]
starting to think about this again...

**Comment by snarfed** [comment]
@tantek wants (plans?) this for himself this year: http://tantek.com/2018/015/t1/made-destination-figured-out-newwwyear

**Comment by snarfed** [comment]
some of what we need is [in the v4 API](https://developer.github.com/v4/):
* [addComment](https://developer.github.com/v4/mutation/addcomment/)
* [addReaction](https://developer.github.com/v4/mutation/addreaction/), [removeReaction](https://developer.github.com/v4/mutation/removereaction/)
* [addStar](https://developer.github.com/v4/mutation/addstar/), [removeStar](https://developer.github.com/v4/mutation/removestar/)
* fetch [issues](https://developer.github.com/v4/object/repository/#issues), [comments](https://developer.github.com/v4/object/issue/#comments), [labels](https://developer.github.com/v4/object/issue/#labels), [reactions](https://developer.github.com/v4/object/issue/#reactions)

some is currently [only in v3](https://developer.github.com/v3/):
* [create issue](https://developer.github.com/v3/issues/#create-an-issue) ([on the roadmap for v4](https://platform.github.community/t/how-do-i-create-an-issue/3979/2))
* [edit issue](https://developer.github.com/v3/issues/#edit-an-issue)

some i didn't see anywhere:
* close/reopen an issue ([on the roadmap for v4](https://platform.github.community/t/add-closeissue-mutation/3250))

**Comment by snarfed** [comment]
particularly interesting: the v3 API has [webhooks for many events we care about for backfeed!](https://developer.github.com/webhooks/) e.g. new issue comments. not for reactions though.

**Comment by snarfed** [comment]
big open question for backfeed: is a bridgy github account a repo? or a user? ie would it poll just a single repo for backfeed, or all of the user's repos? not sure either is obviously the right answer.

**Comment by EdwardHinkle** [comment]
For my use case, a bridgy github account would be a user. I would want responses on ALL my repos to backfeed

**Comment by snarfed** [comment]
@EdwardHinkle you'd probably want responses from outside your own repos too, right? eg if you file an issue on someone else's repo, and they reply.

**Comment by EdwardHinkle** [comment]
I hadn’t thought that through, but yes, that’s how I would want it to operate. Especially having been posting in the Microsub repo issues today, I can see having wanted to backfeed those

**Comment by snarfed** [comment]
one interesting question is whether there's a reasonable and scalable way to fetch all of a user's recent issues or comments, across all repos. maybe [`User.issues`](https://developer.github.com/v4/object/user/#issuecomments) and/or [`.issueComments`](https://developer.github.com/v4/object/user/#issuecomments)?

**Comment by snarfed** [comment]
yay, those seem to work. e.g. this gets the last 10 issues a user created, across all repos:

```graphql
query { 
  viewer { 
    issues(last:10) {      
      edges {
        node {
          id url
        }
      }
    }
  }
}
```

`issueComments` and `pullRequests` get the last 10 comments and PRs, respectively.

issues on the users' repos aren't quite as straightforward. this query does it, but only for 100 repos. to look at more, we'd need to make multiple API calls.

```graphql
{
  viewer {
    repositories(last: 100) {
      edges {
        node {
          issues(last: 10) {
            edges {
              node {
                id
                url
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by snarfed** [comment]
thinking about the [v4 API's 5000 points/hr rate limit](https://developer.github.com/v4/guides/resource-limitations/#rate-limit) now. i'm not sure, but afaict it seems to be per app, per user, which is problematic for scaling.

if i estimate a poll will cost ~22 points (more on that later), and i poll hourly, that sets a scaling celing of ~227 github accounts. beyond that, i have to start dropping poll frequency. :( maybe they expect to talk to individual apps once they get big and raise their limits individually? who knows.

**Comment by snarfed** [comment]
testing foo bar

**Comment by EdwardHinkle** [comment]
Let’s see if a reply to this thread works!

**Comment by miklb** [comment]
in #dev star/liking a repo was suggested to be added a Feature request. Would a separate issue be helpful? I would assume it would be similar to how [silo.pub](https://silo.pub/developers#vocab-github) considers a like of repo URL. Or am I conflating two different things?

**Comment by snarfed** [comment]
@miklb that's it! no new issue needed, it's on the list.

**Comment by snarfed** [comment]
(circling back, i shipped starring support this past weekend.)

**Comment by tantek** [comment]
The “Authorize Bridgy” prompt page has a big green button that says to “Authorize snarfed” which seems a bit incongrous.


It would be better for branding/trust reasons if this prompt for Bridgy could use the github.com/bridgy organization, and thus show a button named “Authorize bridgy” instead.

(Originally published at: http://tantek.com/2018/050/t1/authorize-bridgy-prompt)

**Comment by snarfed** [comment]
^ fixed the auth prompt, thanks again @tantek for acquiring the @bridgy org! example prompt below. the real one has the real logo and omits "local."

![github_bridgy_org_auth](https://user-images.githubusercontent.com/778068/36569186-a4f00d52-17e1-11e8-8989-841c09db906e.png)

**Comment by snarfed** [comment]
ok, first pass is pretty complete. publish to github supports issues, comments, reactions, and repo stars. backfeed supports comments and reactions. docs:
* https://brid.gy/about#which
* https://brid.gy/about#publish-types

there are still bugs to fix, and backfeed is best effort (and may be for the foreseeable future), but i think i'm comfortable closing this now. if anyone disagrees, feel free to holler.
