### ISSUE TITLE
facebook publish: POSSE like should return FB POSSE like permalink

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#334]
When you use Bridgy to POSSE a like post to Facebook, Bridgy should return to you the new permalink of the FB POSSE like.

Background: http://indiewebcamp.com/irc/2015-01-03#t1420318033946

I asked: "I don't think Bridgy Publish returns the FB permalink of the POSSE like of a FB object, does it?"
and @kylewm thinks "it should if it doesn't"

And: http://indiewebcamp.com/irc/2015-01-03#t1420332232527

**Comment by snarfed** [comment]
thanks for filing! I'd definitely like to do this.

first, we have to figure out how to get or generate that like permalink. [FB doesn't return it in the API call that creates the like.](https://developers.facebook.com/docs/graph-api/reference/v2.2/object/likes#publish) I'll keep looking, but let me know if you have any ideas!

**Comment by tantek** [comment]
Perhaps immediately make a call to check the user's "/allactivity" and grab the permalink from the like post there? Possible race condition with other FB clients between the two calls, but unlikely.

**Comment by tantek** [comment]
In case it helps - all the "NovemberProject's photo" like posts here http://tantek.com/2015/002/f now have a manually added syndication link to the FB POSSE copy of the like, for all them that didn't 404 (https://github.com/snarfed/bridgy/issues/331) error out when trying to Bridgy Publish the POSSE like to FB.

**Comment by snarfed** [comment]
ongoing research:
* [/USER_ID/likes](https://developers.facebook.com/tools/explorer?method=GET&path=me%2Flikes&version=v2.2) returns a user's likes, but only of pages, not posts, and i don't see anything related to the permalinks
* http://stackoverflow.com/questions/9984051/facebook-api-retrieve-all-activity implies that /USER/allactivity isn't available via the API. >2.5y old, but still

**Comment by snarfed** [comment]
...tentative conclusion so far is that we don't know how to get the like permalinks. :/ deprioritizing for now, sadly.

**Comment by snarfed** [comment]
...and closing altogether now that publish for facebook likes and comments is dead (#350). :(
