### ISSUE TITLE
publish doesn't handle unicode post content well

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#335]
@heindys originally reported this in idno/idno#670. Unicode chars (eg accents) get mangled in publish. example: http://lire.heindys.com/2015/dmonstration-pour-idno has this text:

> Démo  pour les développeur .Je suis navrée de ce problème , j'ai vraiment des soucis !

plug it into preview on https://www.brid.gy/facebook/1317802598 , and you get this:

> Â  DÃ©moÂ  pour les dÃ©veloppeur .Je suis navrÃ©e de ce problÃ¨me , Â j'ai vraiment des soucis !

**Comment by heindys** [comment]
@snarfed Thank you, I will follow

**Comment by snarfed** [comment]
hrm. this may be specific to known. i tried the same unicode text with a page on my site, https://snarfed.org/accents , and it previewed and published to facebook fine, accents included.

**Comment by snarfed** [comment]
@heindys's page http://lire.heindys.com/2015/dmonstration-pour-idno is also UTF-8, just like mine, so it's not a character encoding difference.

**Comment by snarfed** [comment]
when i copy that page to my server, https://snarfed.org/dmonstration-pour-idno.html , and preview it from there, the accents _still_ come through correctly.

**Comment by snarfed** [comment]
here are the HTTP headers. the only meaningful difference i see is that mine sends `Content-Type: text/html; charset=UTF-8`, while known sends just `Content-Type: text/html`. that theoretically shouldn't matter, though, since the doc itself includes `<meta charset="utf-8">`. hrmph.

http://lire.heindys.com/2015/dmonstration-pour-idno
```
Date: Tue, 06 Jan 2015 00:34:05 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Link: <http://lire.heindys.com/micropub/endpoint>; rel="micropub", <http://lire.heindys.com/webmention/>; rel="http://webmention.org/", <http://lire.heindys.com/webmention/>; rel="webmention", <http://withknown.superfeedr.com/> rel="hub", <http://lire.heindys.com/content/all/?_t=rss> rel="self"
X-Powered-By: http://withknown.com
Access-Control-Allow-Origin: *
Set-Cookie: known=[redacted]; expires=Thu, 05-Feb-2015 00:34:05 GMT; Max-Age=2592000; path=/; HttpOnly
Last-Modified: Sun, 04 Jan 2015 17:01:09 GMT
Vary: Accept-Encoding,User-Agent
Transfer-Encoding: chunked
Content-Type: text/html
Set-Cookie: SERVERID=http1-apache-01d; path=/; HttpOnly
```

https://snarfed.org/dmonstration-pour-idno.html
```
Date: Tue, 06 Jan 2015 00:34:18 GMT
Server: Apache/2.2.29
Accept-Ranges: bytes
Content-Length: 20387
Vary: Accept-Encoding
Strict-Transport-Security: max-age=16070400
Cache-Control: max-age=2592000, public, must-revalidate
Content-Type: text/html; charset=UTF-8
```

**Comment by snarfed** [comment]
ok, found a difference. mf2py parses the content differently when it's served from my server vs heindys's. maybe mf2py is honoring the Content-Type header but not the `<meta charset>` tag? @kylewm, @kartikprabhu, any ideas?

here's the parsed content from https://snarfed.org/dmonstration-pour-idno.html ([details in this log](https://www.brid.gy/log?start_time=1420504280&key=aglzfmJyaWQtZ3lyVgsSDVB1Ymxpc2hlZFBhZ2UiL2h0dHBzOi8vc25hcmZlZC5vcmcvZG1vbnN0cmF0aW9uLXBvdXItaWRuby5odG1sDAsSB1B1Ymxpc2gYgICAgICAgAoM)):
```
'content': [
  {'html': u'\n<div>\n<h2 class="p-name"><a href="http://lire.heindys.com/2015/dmonstration-pour-idno">D\xe9monstration pour idno</a>\n</h2>\n<p class="reading">\n<span class="vague">1 min read </span>\n</p>\n<p>\xa0 D\xe9mo\xa0 pour les d\xe9veloppeur .Je suis navr\xe9e de ce probl\xe8me , <br/></p><p>\xa0j\'ai vraiment des soucis !<br/></p><p><br/></p></div> ',
   'value': u"\n\nD\xe9monstration pour idno\n\n\n1 min read \n\n\xa0 D\xe9mo\xa0 pour les d\xe9veloppeur .Je suis navr\xe9e de ce probl\xe8me , \xa0j'ai vraiment des soucis ! "}],
```

vs from http://lire.heindys.com/2015/dmonstration-pour-idno ([details in this log](https://www.brid.gy/log?start_time=1420504280&key=aglzfmJyaWQtZ3lyVgsSDVB1Ymxpc2hlZFBhZ2UiL2h0dHBzOi8vc25hcmZlZC5vcmcvZG1vbnN0cmF0aW9uLXBvdXItaWRuby5odG1sDAsSB1B1Ymxpc2gYgICAgICAgAoM)):
```
'content': [
  {'html': u'\n<div>\n<h2 class="p-name"><a href="http://lire.heindys.com/2015/dmonstration-pour-idno">D\xe9monstration pour idno</a>\n</h2>\n<p class="reading">\n<span class="vague">1 min read </span>\n</p>\n<p>\xc2\xa0 D\xc3\xa9mo\xc2\xa0 pour les d\xc3\xa9veloppeur .Je suis navr\xc3\xa9e de ce probl\xc3\xa8me , <br/></p><p>\xc2\xa0j\'ai vraiment des soucis !<br/></p><p><br/></p></div> ',
   'value': u"\n\nD\xe9monstration pour idno\n\n\n1 min read \n\n\xc2\xa0 D\xc3\xa9mo\xc2\xa0 pour les d\xc3\xa9veloppeur .Je suis navr\xc3\xa9e de ce probl\xc3\xa8me , \xc2\xa0j'ai vraiment des soucis ! "}],
```

**Comment by snarfed** [comment]
...looking at the code, `requests.get` [gives us what _should_ be a unicode string](64), which we [pass directly to BeautifulSoup](https://github.com/snarfed/bridgy/blob/master/webmention.py#L72), then we [pass that BeautifulSoup object to mf2py's `parser.Parser`](https://github.com/snarfed/bridgy/blob/master/webmention.py#L92), which [seems to operate on it directly](https://github.com/kartikprabhu/mf2py/blob/master/mf2py/parser.py#L69), ie it doesn't call `str()` on it or anything.

soooo...i don't yet see what's going wrong.

**Comment by kylewm** [comment]
We've dealt with this before with exactly that issue with the headers. At least I bet it's the same. I will dig up @kartikprabhu's clever hack when I get home

**Comment by kartikprabhu** [comment]
you have to pass the "correct" data from requests to bs4 so that the encoding is guessed right. Here is the hack line in mf2py.

https://github.com/kartikprabhu/mf2py/blob/master/mf2py/parser.py#L61

**Comment by kylewm** [comment]
the explanation is kind of subtle:
 
* `requests.Response.text` tries to decode the `content` (bytes) based on what it thinks the encoding is.
* but it bases that guess about the encoding on the headers alone, without looking at the body (for efficiency?), and that defaults to iso8859-1. so basically when no charset is specified in the Content-Type header, `text` is always wrong.

so Kartik's hack says, if the headers specify an encoding, then go ahead and use the already decoded `.text`; If not then use the raw `.content` and let BeautifulSoup do the work of looking for a `meta charset`

**Comment by snarfed** [comment]
thanks for the explanation, guys!
