### ISSUE TITLE
facebook: switch to v2.2 api

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#339]
we currently use the graph API via unversioned URLs, so we default to the v1 api, which will sunset in april. we should start using v2.2.

background:
* https://developers.facebook.com/docs/apps/upgrading/
* https://developers.facebook.com/docs/apps/changelog
* https://developers.facebook.com/docs/apps/faq

**Comment by snarfed** [comment]
snarfed/oauth-dropins@a442b7d74ccf6f57f60906b1392e026d62b28159

**Comment by kylewm** [comment]
exciting! :+1:

**Comment by snarfed** [comment]
i checked a couple tokens on  from users who signed up after this change, and confirmed they got all the oauth scopes we need:
* listen: `public_profile, read_stream, user_website, user_events, user_photos, user_status`
* publish: `rsvp_event, publish_actions, user_likes`

...and that they expire in 2 months, so we also still get `offline_access`.
