### ISSUE TITLE
Publish preview: "include link" checkbox does not work without Javascript

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#344]
the non-AJAX version of publish preview is not respecting the bridgy_omit_link checkbox.

I think this is because `<input id="include-link-checked" name="bridgy_omit_link" value="false" checked="" type="checkbox">` is doing a sort of weird "return false if checked" thing.

Reported by NoScript devotee @tantek

**Comment by snarfed** [comment]
aww man, and i fixed that just a bit ago in f263a9655039d393b7b8b344cb1edac13ea21d47. i wonder what (re)broke.

**Comment by kylewm** [comment]
it looks like the logic that checked for bridgy-omit-link was generalized to its own function and dropped the `if self.PREVIEW or...` bit. 

```
  def param_or_prop(self, name, props):
    assert name
    if name in self.request.params:
      return self.request.get(name).lower() in ('', 'true')
    else:
      return name.replace('_', '-') in props
```

**Comment by snarfed** [comment]
nice find! ugh, and i even remember removing that part. "why is this here? it doesn't seem necessary," i thought to myself. "check the tests...yup, they pass without it. baleeted."

benefit of good test coverage? confidence. subtle drawback? overconfidence. :/

**Comment by snarfed** [comment]
now that i've already fixed this, i'm tempted to ditch the ajax altogether for previews and just do a full page load. the long pole for latency will usually be fetching the source page, and bridgy user pages aren't too heavy anyway, so i doubt we're saving more than 10-100ms at most by avoiding the full page layout and render. maybe the ajax UX is a little nicer, but only a little.

meh.
