### ISSUE TITLE
publish: facebook: support liking comments

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#347]
[as requested (implicitly) by @tantek.](http://indiewebcamp.com/irc/2015-01-16#t1421481354919) here's an example comment permalink:

https://www.facebook.com/NovemberProjectSF/photos/a.576939782442519.1073741994.276430682493432/576939812442516/?type=1&comment_id=576956685774162&offset=0&total_comments=14

which should result in a POST to [`/576939812442516_576956685774162/likes`](https://developers.facebook.com/tools/explorer?method=GET&path=576939812442516_576956685774162%2Flikes&version=v2.2&)

also an example non-photo comment permalink:
https://www.facebook.com/snarfed.org/posts/10101337878587383?comment_id=10101338438275763&offset=0&total_comments=1&pnref=story

**Comment by tantek** [comment]
E.g. this like post: http://tantek.com/2015/016/f9

**Comment by snarfed** [comment]
still need to do preview.

**Comment by snarfed** [comment]
931722d3336f90a4463c07661eaad235b48743aa, 3b68168c25f4af6b97df0643ba77fd5c39dfb530
