### ISSUE TITLE
facebook publish: support liking pages

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#349]
as requested by @tantek in #41. the problem is that the page has a username, and FB requires ids in API URLs, not usernames. the fix is to look up the object by username first, then use its id.

**Comment by tantek** [comment]
Another real world example: http://tantek.com/2015/021/f2 :)

**Comment by snarfed** [comment]
thanks for looking! yup, that's it. if only it worked for users in v2.x! poor #350.

i'm actually already mostly done implementing this. stay tuned!

**Comment by snarfed** [comment]
goddammit. from https://developers.facebook.com/docs/graph-api/reference/v2.2/user/likes#publish :

> You can't publish using this edge, as it is not possible to like a Facebook Page via any API. You should use the Like Button if you want people to be able to like a page in your app.

f'ing facebook api. i need a drink.

**Comment by tantek** [comment]
Thanks for trying. Documented: http://indiewebcamp.com/POSSE_to_Facebook#API_disallows_liking_pages

**Comment by kylewm** [comment]
Reopening this one briefly. Tantek got an error message "Sorry, the Facebook API doesn't support liking pages." when trying to like a photo.

* photo: https://www.facebook.com/photo.php?fbid=10204561339047703&amp;set=a.10204145890661753.1073741846.1060530082
* bridgy log: https://www.brid.gy/log?start_time=1422843635&key=aglzfmJyaWQtZ3lyRAsSDVB1Ymxpc2hlZFBhZ2UiHWh0dHA6Ly90YW50ZWsuY29tLzIwMTUvMDMyL2YxDAsSB1B1Ymxpc2gYgICAgICAgAoM

**Comment by snarfed** [comment]
sigh. should we just give up and declare facebook publish bankruptcy? :p

I honestly wonder if scraping and imitating a browser would be easier or more reliable, short-lived auth cookies notwithstanding. (kidding... kinda...)

**Comment by kylewm** [comment]
I do honestly think we should give up publishing likes and comments to Facebook...

**Comment by snarfed** [comment]
:(

(that's my disbelieving, then sad, then resigned face.)

ok. so. for completeness, what do we have to do first to exhaust all possibilities? post an SO question, include all of our research so far, and attach a big fat bounty? find a personal connection at facebook and ply them for information? anything else?

**Comment by snarfed** [comment]
moving discussion to #350

**Comment by snarfed** [comment]
tentatively blaming #350. holler if you disagree.
