### ISSUE TITLE
403 errors on wordpress, specifically jeanmrussell.com due to User-Agent blocking

### ISSUE THREAD

**Issue by kevinmarks** [snarfed/bridgy#358]
see https://www.brid.gy/log?start_time=1422522696&key=aglzfmJyaWQtZ3lyGAsSB1R3aXR0ZXIiC051cnR1cmVHaXJsDA

and previous discussions - @snarfed could repro with:

http://indiewebcamp.com/irc/2015-01-28/line/1422502560154
```
import requests; requests.get('http://www.jeanmrussell.com/testing-brid-gy/')
```
if I change the useragent, I get a 200, so this is a naive scraper preventer:

```
>>> import requests; r=requests.get('http://www.jeanmrussell.com/testing-brid-gy/')
<Response [403]>
>>> r.request.headers
{'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.4.0 CPython/2.7.6 Darwin/13.4.0'}

>>> r2=requests.get('http://www.jeanmrussell.com/testing-brid-gy/', headers={'User-Agent':'brid.gy'})
<Response [200]>
>>> r2.request.headers
{'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'brid.gy'}
```
so bridgy should set its own useragent so that it can be specifically blocked or accepted

**Comment by snarfed** [comment]
thanks for filing! sounds like a reasonable request.

...having said that, though, i'd really like to know which part of jean's wordpress or hosting setup is blocking based on user agent, since the vast vast majority of WP sites don't have this problem. i'm not sure yet which side is better to tackle it on.

also, app engine somewhat allows modifying user agent, but it also tacks on an app engine watermark: https://cloud.google.com/appengine/docs/python/urlfetch/#Python_Request_headers . we'd also want to test to make sure that watermark isn't also included in whatever blacklist is triggering here.

**Comment by dshanske** [comment]
What about the usage of Bridgy in the User-Agent for use by log analyzers?

**Comment by snarfed** [comment]
@dshanske i'm not sure i see the concrete use case (yet), but you can identify webmentions specifically by target URLs at brid-gy.appspot.com (or brid.gy), and you can identify all HTTP requests by `appid: brid-gy` in the user agent. details: https://cloud.google.com/appengine/docs/python/urlfetch/#headers_identifying_request_source

**Comment by snarfed** [comment]
just for completeness, here's the user agent we're advertizing right now:

`python-requests/2.1.0 CPython/2.7.5 Linux/ AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)`

**Comment by kevinmarks** [comment]
If I fetch with that string, I get a 403. If I modify 'python-requests' at all I get a 200, so it is that string being blocked. Not sure where - I tried looking through Jean's hosting config on weds night but wasn't able to find the settings. 
googling reveals http://perishablepress.com/2013-user-agent-blacklist/ as a common catch-all, and it does include the string 'request'

**Comment by snarfed** [comment]
thanks for the research @kevinmarks! man, that blacklist is pretty aggressive. also includes "pyth", among many others.

ok, setting a custom user agent is reasonable. I'll do that.
