### ISSUE TITLE
link regex matches trailing parens, breaks twitter char counting

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#359]
... which results in 403s when people try to publish tweets that trigger it. cc @kylewm

**Comment by kylewm** [comment]
Here was the post @dissolve tried to publish https://ben.thatmustbe.me/note/2015/1/31/1/

and the truncated text Bridgy came up with
```
Hey #indieweb, the coming storm of webmention Spam may not be far away. Those of us that have input fields to send… (https://ben.thatmustbe.me/note/2015/1/31/1/)
```
which twitter counts as 141 characters because the final ) is matched by Bridgy but not Twitter

**Comment by kylewm** [comment]
I was wrong. It wasn't the link regex causing the problem (although that *was* overmatching). It's an off by one in the ellipsizing code -- it didn't account for the ellipsis when determining where to truncate.

**Comment by kylewm** [comment]
Here's the change to autolinking https://github.com/kylewm/webutil/commit/33796ae91248423bee1a107f3276e3ed035fe603

And here's the one that accounts for the ellipsis https://github.com/snarfed/activitystreams-unofficial/commit/1ff2828434eb1eb3f1fbfcb68f950127e9b8a3b5

**Comment by snarfed** [comment]
thanks for the research and fix (and tests!) the a-u change looks good, feel free to deploy it if you want, but no pressure.

and thanks for the auto linking changes too! you're right, I had done that subdomains one. I am often lazy about updating submodule pointers when there's nothing else to commit, but I usually do try to at least push each repo's master, so I'm surprised that one didn't make it. meh.

greetings from Carmel btw: p

**Comment by snarfed** [comment]
@kylewm, is this one fixed now?

**Comment by kylewm** [comment]
Yes, but I didn't deploy it yet

**Comment by snarfed** [comment]
oh, heh, then i deployed it yesterday. :P

confirmed by previewing https://ben.thatmustbe.me/note/2015/1/31/1/ on https://www.brid.gy/twitter/dissolve333 . it now omits the final "send."
