### ISSUE TITLE
Facebook 403 response when liking a public post

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#360]
Seen by @tantek

* original http://tantek.com/2015/031/f2
* target post: https://www.facebook.com/bmd101/posts/10101484301205283
* error log: https://www.brid.gy/log?start_time=1422770585&key=aglzfmJyaWQtZ3lyRAsSDVB1Ymxpc2hlZFBhZ2UiHWh0dHA6Ly90YW50ZWsuY29tLzIwMTUvMDMxL2YyDAsSB1B1Ymxpc2gYgICAgIDkkQoM

Hmm...everything seems to be OK. Maybe a transient FB API hiccup? Keeping an eye out for more of these.

**Comment by snarfed** [comment]
ugh, probably #351's fault. sorry @tantek. I can look when I get back on tues.

**Comment by kylewm** [comment]
Might it be related to

http://indiewebcamp.com/irc/2015-01-31#t1422736428358

**Comment by kylewm** [comment]
I think it's actually #350 (facebook API v2.0 ID problems). 10101484301205283 is one of those mysterious post IDs that the Graph API does not recognize without a user ID in front of it (and we have no way to look up the user ID). :cry:

**Comment by kylewm** [comment]
I found bmd101's app-scoped ID by getting their user ID from an unauthenticated call to https://graph.facebook.com/bmd101 and then an authenticated call to https://graph.facebook.com/208458 -- so their app-scoped ID is 10101338078880993.

but I cannot fetch 10101338078880993_10101484301205283, nor its likes, nor can I POST to its likes endpoint.

![screenshot from 2015-02-01 08 27 00](https://cloud.githubusercontent.com/assets/950127/5992774/24a6e1cc-a9ec-11e4-8ba0-e97737aa1e3d.png)

I'm more and more of the belief that posting FB likes and comments is just not reliably allowed any more.

**Comment by snarfed** [comment]
yeah...at least, when you're trying to work backward from a URL in a browser, instead of finding the post/object via the api in the first place - their expected user case, I'd guess - so you get id(s) that you know should work.

**Comment by tantek** [comment]
Another example if it helps: http://tantek.com/2015/035/f1 liking of https://www.facebook.com/andigalpern/posts/678121182314631

**Comment by snarfed** [comment]
merging into #350
