### ISSUE TITLE
duplicate facebook wms 

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#363]
@gRegorLove and @benwerd have both reported seeing duplicate webmentions from facebook in the last couple days. @benwerd said one was usually fine, and one was only marked up with u-mention, not u-like-of (or whatever).

**Comment by snarfed** [comment]
based on no data, i blame the 2.x api.

**Comment by gRegorLove** [comment]
Sample duplicates:
https://brid-gy.appspot.com/like/facebook/27301982/10100921482184384/541445614
https://brid-gy.appspot.com/like/facebook/27301982/10100921482184384/10155219179320615

https://brid-gy.appspot.com/like/facebook/27301982/10100921482184384/56200139
https://brid-gy.appspot.com/like/facebook/27301982/10100921482184384/884913424803

Looks like different author URLs, with different IDs in them.

**Comment by kylewm** [comment]
I got some too, last night around 9:35pm

https://brid-gy.appspot.com/like/facebook/12802152/10101026484044669/10100843809875169
https://brid-gy.appspot.com/like/facebook/12802152/10101036914731489/10104122507808150
https://brid-gy.appspot.com/like/facebook/12802152/10101026484044669/10100847100974779
https://brid-gy.appspot.com/like/facebook/12802152/10101026484044669/816511395045146
+ more

They're all on two posts from September that had already received a bunch of duplicate likes when the initial 2.x switch happened, so I think you're probably right that it's something they did.

**Comment by snarfed** [comment]
likely related to #374 and/or #305. closing for now.
