### ISSUE TITLE
poll not backing off on 400s

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#364]
right now, facebook is always 400ing @kylewm on poll. not sure why...but one bad side effect is that we're not backing off to once an hour. not sure why.

https://www.brid.gy/facebook/12802152

**Comment by kylewm** [comment]
I'm sure I broke something tinkering with permissions. Disabled and re-enabled and it seems to be working again (I know that is not actually the bug that you are noting)

By the way, I assume you have seen this warning when asking for `read_stream`?

![bridgy-read-stream-warning](https://cloud.githubusercontent.com/assets/950127/6217955/3b5829a6-b5ce-11e4-8e69-1f4e88860e2f.png)

**Comment by snarfed** [comment]
thanks! i figured it was something like that. and yeah, that's the warning when you ask for an unapproved scope and it only gives it to you because you're an app owner. whee!

**Comment by snarfed** [comment]
huh, it's not just polls. failed propagate tasks also retry too much, every few minutes. e.g. this one of jeena's:

```
 0.1.0.2 - - [16/Feb/2015:22:04:57 -0800] "POST /_ah/queue/propagate HTTP/1.1" 306 1140 "http://brid-gy.appspot.com/_ah/queue/poll" "AppEngine-Google; (+http://code.google.com/appengine)"

Params: UnicodeMultiDict([(u'response_key', u'aglzfmJy...')])
Source: Jeena Pa (Facebook) 728407677, http://brid-gy.appspot.com/facebook/728407677
Created by this poll: http://brid-gy.appspot.com/log?start_time=1423774115&key=aglzfmJyaWQtZ3lyGwsSDEZhY2Vib29rUGFnZSIJNzI4NDA3Njc3DA
Starting Response comment tag:facebook.com,2013:10153585358202678_10153585651827678 https://www.facebook.com/10153585358202678?comment_id=10153585651827678
Webmention from https://brid-gy.appspot.com/comment/facebook/728407677/10153585358202678/10153585358202678_10153585651827678 to https://jeena.net/photos/97
Sending...
Starting new HTTPS connection (1): jeena.net
"GET /photos/97 HTTP/1.1" 200 None
Starting new HTTPS connection (1): jeena.net
"POST /webmentions HTTP/1.1" 500 None
Error sending to endpoint: {'body': ...
Propagate task failed
```

**Comment by snarfed** [comment]
i wonder if some of this is because `/cron/replace_poll_tasks` is overzealous and looks at the last _successful_ poll, not the last poll _attempt_. that's one thing to fix.

**Comment by snarfed** [comment]
there were actually a bunch of different propagate tasks for that one bad jeena response, not just one. probably due to idno/Known#755. so, one mystery down.

**Comment by snarfed** [comment]
i _think_ the polls were due to the overagressive `/cron/replace_poll_tasks`. tentatively closing.
