### ISSUE TITLE
redirect brid-gy.appspot.com to brid.gy

### ISSUE THREAD

**Issue by bcomnes** [snarfed/bridgy#367]
```json
{
"code": 400,
"error_type": "OAuthException",
"error_message": "Redirect URI does not match registered             redirect URI"
}
```

Tried logging in with my instagram and hit this

**Comment by snarfed** [comment]
hoo boy, that's bad. thanks for reporting. I wonder if I changed the Instagram app we use and forgot to tell @kylewm? I'll look.

**Comment by snarfed** [comment]
i deployed myself and instagram seems to work again. @bcomnes, mind confirming? if so, i'll send @kylewm the new app id and secret.

**Comment by bcomnes** [comment]
Still getting the same exception.

**Comment by snarfed** [comment]
aha i think i know what's going on. @bcomnes any chance you're using https://brid-gy.appspot.com/ and not https://www.brid.gy/ ?

if so, i should make that redirect to brid.gy on the front page, user pages, /about, etc.

**Comment by bcomnes** [comment]
Oh wow, yes!  The appspot url was the first thing to pop up in my url bar history.  This makes sense.
