### ISSUE TITLE
Issue connecting to Facebook Page

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#373]
For some reason, I'm having issues connecting to a FB page.  I've tried putting the relevant website address in both the list of websites on my personal page as well as the page's website field.  Despit this I'm still getting the "First things first: what's your web site? Edit your Facebook profile, enter it in the Website field, then click here:" message
https://www.brid.gy/facebook/874430162577077 

I've tried disconnecting/reconnecting brid.gy as an app in my FB account, but that doesn't seem to help.  Is there something else simple that I'm missing?

**Comment by snarfed** [comment]
hey chris! sorry for the trouble, and thanks for the report. definitely a bug. i'll fix it soon.

just so you know though, the page actually is working ok. the only thing it's missing by not finding the web site is that it won't find u-syndication links. posts with links in them should work fine though, e.g. if you like or comment on https://www.facebook.com/henryjameskorn/posts/876959478990812 , bridgy should send that back ok.

regardless, i'll fix the bug!

**Comment by snarfed** [comment]
fixed by snarfed/oauth-dropins#b6cbae2debd8b42bab3e1b255d8c8732b2ba60b9 . @chrisaldrich, feel free to try again!
