### ISSUE TITLE
only resend updated comments, not likes or reposts or RSVPs

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#374]
... since none of our silo likes, reposts, or RSVPs currently include user-generated content.

(actually, check FB shares first, we might include user text in those.)

this would have prevented the storm of resends noticed by @aaronpk and caused by #371, which dropped the auto generated content for those response types.

updates were originally added in #9.

**Comment by snarfed** [comment]
i'm actually not sure if we really want to do this. the only use case right now seems to be protecting against unusual, one-off changes we make to our own logic, like we did with #371. i'm not convinced this is the right way to handle those.

**Comment by snarfed** [comment]
#371 is still causing fallout. the propagate task queue grew from ~3500 to ~7500 in the last 30m, so we're still generating and sending about 100 dupe wms per minute. i'm going to temporarily turn updates off for likes and reposts, but i'm still not sure i want to make it permanent.

**Comment by kylewm** [comment]
you mean you're not sure you want to make #371 permanent?

**Comment by snarfed** [comment]
oh no, i mean i'm not sure i'd want to permanently narrow #9 to just comments (ie what i proposed in this issue).

**Comment by kylewm** [comment]
According to the protocol, it's technically doing the right thing by resending those mentions (i.e. since the content has changed) isn't it?

Maybe there should just be some reasonable time horizon on how far back it'll look for updates (like e.g. a month?)

**Comment by aaronpk** [comment]
Or maybe bridgy is fine, and everyone's webmention endpoints need to be better about detecting duplicate webmentions and properly handling notifications. This is really only a problem for me because I get push notifications about each webmention, regardless of whether it's already seen or is an update.

**Comment by snarfed** [comment]
right, all true. i just try hard to be nice to existing implementations, even when they don't exactly follow a spec, e.g. in this case where many people still don't de-dupe well, or even at all, and even when they do, there are sometimes bad side effects, e.g. known might still send email notifs for every single wm, even if it's a dupe. (idno/Known#755, #363.)

re the time horizon, agreed, that's a good idea. it's currently limited to the last X (usually 50) per silo, but goes back arbitrarily far in time, which it probaly shouldn't.
