### ISSUE TITLE
investigate superfeedr notification spike

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#378]
our superfeedr subscriptions haven't grown very fast, but our notifications spiked >10x in feb. @kylewm and i wonder if one or a few feeds are responsible. i didn't see deep per-feed analytics in superfeedr, but we should be able to investigate pretty easily in the datastore with [`remote_api_shell`](https://developers.google.com/appengine/articles/remote_api#running).

from https://superfeedr.com/stats/user/snarfed?frame=year , notifications:

![bridgy_superfeedr_notifs](https://cloud.githubusercontent.com/assets/778068/6807133/e92437f8-d209-11e4-82ba-29755baa9d51.png)

vs subscriptions:

![bridgy_superfeedr_feeds](https://cloud.githubusercontent.com/assets/778068/6807141/ef71d80e-d209-11e4-95a0-77a0d3d31b91.png)

**Comment by snarfed** [comment]
huh. i looked at the obvious question - were there way more blog posts in feb? - and no, there weren't. herre are the numbers:

* [nov 2014](https://appengine.google.com/datastore/explorer?app_id=s~brid-gy&kind=BlogPost&viewby=gql&query=SELECT+*+FROM+BlogPost+++%0Awhere+created+%3E%3D+DATE%282014%2C+12%2C+1%29+++%0Aand+created+%3C+DATE%282015%2C+1%2C+1%29&limit=200&offset=1800): 1856
* [dec 2014](https://appengine.google.com/datastore/explorer?app_id=s~brid-gy&kind=BlogPost&viewby=gql&query=SELECT+*+FROM+BlogPost+++%0Awhere+created+%3E%3D+DATE%282014%2C+12%2C+1%29+++%0Aand+created+%3C+DATE%282015%2C+1%2C+1%29&limit=200&offset=1200): 1239
* [jan 2015](https://appengine.google.com/datastore/explorer?app_id=s~brid-gy&kind=BlogPost&viewby=gql&query=SELECT+*+FROM+BlogPost+++%0Awhere+created+%3E%3D+DATE%282015%2C+1%2C+1%29+++%0Aand+created+%3C+DATE%282015%2C+2%2C+1%29&limit=200&offset=800): 943
* [feb 2015](https://appengine.google.com/datastore/explorer?app_id=s~brid-gy&kind=BlogPost&viewby=gql&query=SELECT+*+FROM+BlogPost+++%0Awhere+created+%3E%3D+DATE%282015%2C+2%2C+1%29+++%0Aand+created+%3C+DATE%282015%2C+3%2C+1%29&limit=200&offset=1200): 1254
* [mar 2015](https://appengine.google.com/datastore/explorer?app_id=s~brid-gy&kind=BlogPost&viewby=gql&query=SELECT+*+FROM+BlogPost+++%0Awhere+created+%3E%3D+DATE%282015%2C+3%2C+1%29+++%0Aand+created+%3C+DATE%282015%2C+4%2C+1%29&limit=200&offset=1600): 1601

(i used the [admin console datastore viewer](https://appengine.google.com/datastore/explorer?app_id=s~brid-gy). i started with queries like this in [remote_api_shell](https://cloud.google.com/appengine/articles/remote_api#running) instead, but they took forever. not sure why, given the small result size.
```py
len(list(BlogPost.query()
.filter(BlogPost.created >= datetime.datetime(2014, 12, 1))
                         .filter(BlogPost.created < datetime.datetime(2015, 1, 1))
                         .iter(keys_only=True, batch_size=1000)))
```)

**Comment by snarfed** [comment]
[looking at our daily rate](https://superfeedr.com/stats/user/snarfed?frame=month), we've held steady at the new elevated rate of ~425 notifications/day over the last month, compared to ~75/day before. (we dropped to ~250/day over the last few days, but unclear whether that will hold, and it's still elevated.)

![canvas](https://cloud.githubusercontent.com/assets/778068/6924648/cfdf54fa-d78e-11e4-914c-58f5516aae19.png)

**Comment by snarfed** [comment]
aha. [looking at the logs](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=path:%2Fwordpress%2Fnotify%2Fnikolnieto.me), something like 90% of the superfeedr notifications are for nikolnieto.me: https://www.brid.gy/wordpress/nikolnieto.me . they're coming consistently every 8m. they look like this:

```
Source: Nikol (WordPress.com) nikolnieto.me
Raw feed: {"status":{"code":200,"http":"Parser Error not well-formed (invalid token)","nextFetch":1427819537,"bozoRank":0.5,"period":900,"lastFetch":1427818637,"lastParse":1238466305,"lastMaintenanceAt":1427768860,"feed":"http://nikolnieto.me/feed/"},"title":"","updated":null,"id":""}
```

every 8m works out to 180/day, which accounts for all of the notification volume we're seeing right now above our old average of 75/day. i still don't know what put us up to ~425/day before though.

**Comment by snarfed** [comment]
i've disabled the [nikolnieto.me account](https://appengine.google.com/datastore/edit?app_id=s~brid-gy&version_id=3.383236630846410047&key=aglzfmJyaWQtZ3lyHAsSCVdvcmRQcmVzcyINbmlrb2xuaWV0by5tZQw) and [removed the superfeedr subscription](https://superfeedr.com/users/snarfed/subscriptions).

**Comment by snarfed** [comment]
[logs for 3/25 show that](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=text:%2Fnotify%2F&lastVisibleOffset=551295be00ff03621dd7f45e5a0001737e627269642d677900013300010125&lastVisibleTimestampNanos=1427281342239000000) atg.soy (https://www.brid.gy/wordpress/atg.soy) was the other runaway feed prior to 3/26ish. i'm leaving that account alone for now, since they're fixed, but worth noting for the record. they were also notifying every 8m:

```
Source: Zingplex (WordPress.com) atg.soy
Raw feed: {"status":{"code":200,"http":"Parser Error duplicate attribute","nextFetch":1427279863,"bozoRank":0.5,"period":900,"lastFetch":1427278963,"lastParse":1422469133,"lastMaintenanceAt":1427251926,"feed":"http://atg.soy/feed/"},"standardLinks":{"alternate":[{"rel":"alternate","href":"/feed.xml"}],"shortcut icon":[{"rel":"shortcut icon","href":"/packages/telescope-theme-weld/img/favicon.ico"}],"apple-touch-icon":[{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-57x57.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-60x60.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-72x72.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-76x76.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-114x114.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-120x120.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-144x144.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-152x152.png"},{"rel":"apple-touch-icon","href":"/packages/telescope-theme-weld/img/apple-touch-icon-180x180.png"}],"manifest":[{"rel":"manifest","href":"/packages/telescope-theme-weld/img/manifest.json"}]},"title":"","updated":null,"id":""}
```

**Comment by kylewm** [comment]
Oh no, does Superfeedr not throttle spurious notifications like that?

**Comment by kylewm** [comment]
Also interesting that nikolnieto.me is a tumblr site and it was registered as Wordpress.com... maybe they switched it and that caused problems somehow?

**Comment by snarfed** [comment]
interesting, true! they must have switched it. superfeedr doesn't have an explicit server type though, or at least we don't give it one. the switch may have caused the problem, but if so that's out of our control.

**Comment by snarfed** [comment]
we're back down to our normal level of <100/day, so i'm tentatively closing. i should add monitoring and alerting for this, but i'm lazy. :P

last 24h:
![canvas](https://cloud.githubusercontent.com/assets/778068/6947041/52ce03b4-d859-11e4-8dcf-87b66573d44f.png)

last 7d:
![canvas](https://cloud.githubusercontent.com/assets/778068/6947046/635e392e-d859-11e4-97bc-9c01ea0338a8.png)

**Comment by snarfed** [comment]
reopening. our daily notification rate jumped from <100 to >1k a few days ago.

![canvas](https://cloud.githubusercontent.com/assets/778068/7576347/7d4cdb58-f7f1-11e4-9456-529b40deabc6.png)

jasonwoj.com is one clear outlier, with 151notifis over the last 24h. it just redirects to https://svbtle.com now, so i'll disable it. i don't see other outliers though. tumblr blogs seem to be notifying often now, many of them every hour or so even if they haven't changed at all. i'll see if that was also true before.

**Comment by snarfed** [comment]
(interesting, superfeedr's status field for jasonwoj.com was _Parser Error syntax error_, and it said it was fetching every 30m or so.)

**Comment by snarfed** [comment]
[i asked @superfeedr](https://twitter.com/schnarfed/status/597894960134815744); we'll see what they say.

**Comment by snarfed** [comment]
@superfeedr says this is a systemic issue on their end with many tumblr sites. they're looking into it.

**Comment by snarfed** [comment]
no news yet. i may start unsubscribing inactive tumblr blogs manually.

**Comment by snarfed** [comment]
no news for a month; this is probably the new normal. i've unsubscribed a bunch of stale tumblr accounts that weren't actually using us, ie weren't sending or receiving webmentions. we're down to ~100 notifs/day, which is ~1/3 of the superfeedr free quota. good enough for now.
