### ISSUE TITLE
Support request : How can I use it on multiuser sites?

### ISSUE THREAD

**Issue by rhisss** [snarfed/bridgy#379]
For example, I am using Drupal 5 where there are many users each of whom has a profile page, a blog etc - when they post a b;log post and also posts its link to facebook, and then someone comments in facebook how can they get the comment in their individual blog post ?

https://indieauth.com/setup enables to set up things on the entire drupal site but not on individual user or individual user blog ? Isn't it so? 

Many users are using similar set-up for Drupal 5 and 6 - so some guide for them would be appreciated or still better a drupal 5 and 6 compatible plugin. Drupal 7 has some rdf or microformat support but 7 is not yet that widely used and upgradation to 7 not possible for all sites.

**Comment by snarfed** [comment]
hmm. have you tried bridgy on a multi-user site? if the site accepts webmentions, and attaches them to the target post appropriately, it should Just Work. (indieauth is unrelated to bridgy, so it doesn't matter that indieauth may or may not support multi-user sites.)

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen if you run into a problem!
