### ISSUE TITLE
Enhancement : How to cluster outside comments or likes

### ISSUE THREAD

**Issue by rhisss** [snarfed/bridgy#380]
How to group together several Likes or Facebook ( or similar) comments into :
abc, def, xyz  and 5 more commented on this
rather than
abc commented on facebook
def commented on facebook
xyz commented on facebook
.....
This can make the blog comment section unnecessarily long with no actual reading matter, and can "pollute" with too many likes (when there are likes) appearing serially one after another - this can push down actual comments made on the site itself pushed down or appear few and far between.

Thanks

**Comment by snarfed** [comment]
good point! agreed, it's definitely nicer to cluster those together than show them individually.

unfortunately, bridgy doesn't really have any control over how your site renders likes, comments, etc. you'll need to do this in your site itself.

here are a couple examples of sites that do this well, in one way or another:

http://stream.withknown.com/
https://aaronparecki.com/notes/2015/03/28/1/berlin#likes
https://kylewm.com/2015/03/view-to-a-bay

here are some good resources:
https://indiewebcamp.com/like#notification_first_design
https://indiewebcamp.com/comments-presentation

**Comment by rhisss** [comment]
Can there be any request made for such plugin to the devs in Wordpress, Elgg, Easysocial etc?
I have no idea how or rather whom to request - so what can be the start point for dummies?
Can brid.gy involve some devs and create such plugins so that things work out-of-the-box?
Thanks.

**Comment by kylewm** [comment]
@rhisss this is where the "scratch your own itch" philosophy really comes in handy -- You don't have to fix this problem for everyone in the world, just for yourself! (and ideally by fixing it for yourself, it will be helpful to others of course). So focus on the software you use to run your own site, can you file a request for this behavior? If it's Wordpress, I *think* there is already a solution or two.

**Comment by rhisss** [comment]
Yes Wordpress (at least non-multisite) works. Problem is with others like Drupal 5, 6, Joomla etc
Not everyone can "scratch your own itch" unfortunately ( I wish I could) and a lot of time has to be spent on building the actual site content and user-base. That way, things that work almost universally and out-of-the-box (and is even backward compatible) becomes really popular and widely adopted. Otherwise things become like 'abandoned' like openid. Webmentions, despite its comparative easiness, need to be more easy or maybe something 'new' and more easy. But thanks a lot that brid.gy is here.
