### ISSUE TITLE
brid.gy site pages leaking non-public information

### ISSUE THREAD

**Issue by beck24** [snarfed/bridgy#383]
The responses list includes responses to posts that are restricted access and includes the post title and names of people and how they responded to a restricted access post.

eg. My account
https://www.brid.gy/facebook/948590525171368

Shows this post: https://www.facebook.com/948590525171368/posts/950057688357985

**Comment by snarfed** [comment]
oh man, that's really bad. sorry about that, and thanks for the report. we're really careful not to send webmentions for non-public comments, posts, etc, but i guess we never caught the posts on the user page. fixing now!

**Comment by snarfed** [comment]
huh. we actually do check that they're public before showing them. (i could have sworn we did.) https://github.com/snarfed/bridgy/tree/master/app.py#L231

...except that check clearly isn't working for these responses. i wonder why not.

**Comment by beck24** [comment]
ok, yeah something is slipping past the check
I imagine this could happen if the post was originally posted as public and later modified after bridgy did its thing, but I'm 100% sure I haven't modified the access on the post, it was posted as friends only

**Comment by beck24** [comment]
I've added some test posts also set to friends only access, and they're not showing up on the bridgy page.  The post that showed up was a picture added from my phone (via the site, not the app), and I've done a test post with the same conditions, and it's not showing here either - both test posts have replies.

It seems to be limited to just the one post I linked above.

**Comment by snarfed** [comment]
interesting. thanks for the tests!

**Comment by snarfed** [comment]
so, the FB API doesn't actually think that post is private. here it is in the graph api explorer: https://developers.facebook.com/tools/explorer?method=GET&path=950057688357985&version=v2.3& (it'll only show up with an access token for @beck24.)

if it's non-public, it will have a [`privacy` field](https://developers.facebook.com/docs/graph-api/reference/v2.2/post#fields) with details on who can see it...but it doesn't have that field at all.

**Comment by beck24** [comment]
ok, that is strange... here's how it looks on my wall.  It's clearly set to friends only which is my default.

![screen shot 2015-04-06 at 11 08 30 am](https://cloud.githubusercontent.com/assets/738363/7009200/575484ce-dc4d-11e4-8247-25edcbe5b7e4.png)

I guess this is a facebook API fail then :)

**Comment by beck24** [comment]
I've created a ticket with FB - https://developers.facebook.com/bugs/983622558349347/
This post isn't sensitive at all so I don't really care about this instance, but in general the API should be returning consistently correct privacy!

**Comment by snarfed** [comment]
thanks!

**Comment by beck24** [comment]
oh, hey, it happened again

https://www.facebook.com/948590525171368/posts/950536744976746

This was the test post that replicated the conditions.  A photo uploaded from my phone through the mobile version of the site (not the app).
It took hours to actually pick up though, and I manually polled it a few times after posting...

**Comment by snarfed** [comment]
conclusion from `the FB bug report`: we get `privacy` if we request the two-part id, e.g. `948590525171368_950536744976746`, but not if we request just `950536744976746`. i suspect this changed during the upgrade to FB API v2.x (#350).

cc @kylewm because ids in the FB API have been gradually driving both of us to :beer: :beer: :beer: :beers: :sob: :gun:

**Comment by snarfed** [comment]
the fix here is to always fetch FB posts with the two-part id (and comments with the three-part id) whenever possible. bleh.

**Comment by snarfed** [comment]
...actually i'm not sure if we can fix this easily ourselves. the problem is that photo objects returned by `/user/photos` don't have the `privacy` field either:
https://developers.facebook.com/docs/graph-api/reference/v2.3/photo#fields
https://developers.facebook.com/docs/graph-api/reference/v2.3/user/photos

**Comment by snarfed** [comment]
[FB responded and said](https://developers.facebook.com/bugs/983622558349347/?comment_id=1654708664748756) to get a photo's privacy, we need to fetch its corresponding post object. ugh. :(

>  ...you should assume a photo object privacy is potentially self or friends unless, a) It is associated with a non-timeline album, and privacy can be inferred from the album or, b) It is associated with a /feed post and privacy can be inferred from the post.
> ...
> Our engineers have confirmed this is intentional design, and we have no plans to change it; each photo in the timeline album should have a corresponding post in feed, from which privacy settings can be inferred.

bleh.

**Comment by beck24** [comment]
Yeah that is very annoying and seems poorly designed from this side of things...

**Comment by snarfed** [comment]
i dove into this a bit, and i don't quite follow how it's happening with the current code. when we [merge post objects and photo objects](https://github.com/snarfed/granary/blob/31248e3c566108e01bdea9bf0867d0262bbf3dc2/granary/facebook.py#L335), we only use the photo object's id, comments, and likes. everything else comes from the post object, including `privacy`.

i confirmed by running `get_activities(...)` with matt's access token and looking at the post in #562. post id 1070245399672546 (photo `object_id` 1070245016339251) shows up once, correctly, using the photo object id and marked private:

```py
import dev_appserver; dev_appserver.fix_sys_path()
from granary import facebook
print json.dumps(a, indent=2)
from granary.source import SELF
f = facebook.Facebook('CAAD...')
print json.dumps(f.get_activities(fetch_likes=True, fetch_replies=True, fetch_shares=True, fetch_mentions=True, group_id=SELF), indent=2))
...
{
  "verb": "post",
  "url": "https://www.facebook.com/948590525171368/posts/1070245016339251",
  "object": {
    "id": "tag:facebook.com:1070245016339251",
    "fb_object_id": "1070245016339251",
    "fb_id": "1070245016339251",
    "to": [{
        "alias": "@private",
        "objectType": "group"
      }],
    "objectType": "image"
    ...
  },
},
...
```

i'd say it's maybe a race condition, ie facebook gave us the post object but not the photo object, but i doubt it, especially not consistently like with this one, which kept getting comments backfed.

my next hunch is that the comment ids have the post id embedded in them, not the photo id, and maybe we're refetching or otherwise looking at the post based on that instead of the photo object id? seems like a stretch

**Comment by snarfed** [comment]
another thought: i could just copy the AS `to` field from each post into its comments.

not sure that would work, since we should be _skipping_ those comments when we see that their post is non public, but who knows.

**Comment by snarfed** [comment]
ok. my current theory is that this was actually fixed a while back, by [what's now `granary.Facebook._merge_photos()`](https://github.com/snarfed/granary/blob/31248e3c566108e01bdea9bf0867d0262bbf3dc2/granary/facebook.py#L335).

@beck24, thanks again for all your help with debugging these issues. do you have any idea when bridgy last sent you comments from a non-public facebook post? (to the correct matching post, not a mismatched post like in #562). if it was months ago, this may be fixed.

**Comment by beck24** [comment]
No prob.
I just took a look, and went back a day or so before the merged images thing - there still may be something wonky going on:

https://brid.gy/facebook/948590525171368?responses_before=2015-11-27T06:20:11.890190#responses
![screen shot 2015-11-27 at 10 27 42 pm](https://cloud.githubusercontent.com/assets/738363/11450492/543e578e-9556-11e5-8486-d8ddd04a5db2.png)
These two comments are on a non public status that is not a syndicated image, bridgy seems to have linked them with this profile picture update: https://www.facebook.com/948590525171368/posts/919078041455950

![screen shot 2015-11-27 at 10 31 10 pm](https://cloud.githubusercontent.com/assets/738363/11450495/a20d186a-9556-11e5-8c12-efa57c2ccc7d.png)
https://www.facebook.com/matt.beckett.39/posts/1067061366657616

**Comment by snarfed** [comment]
right, that sounds like another instance of #562. it's a standard facebook feature, not a fluke; we just don't know how often they do it or how we can reliably detect and handle it via the API.

i was curious if you'd seen _this_ bug happen recently, ie bridgy finds and shows non-public comments on your user page but doesn't send them anywhere. (sorry, i misspoke originally.)

...but i can look and see for myself. no worries.

**Comment by beck24** [comment]
ok, I didn't see any that were non-public AND attributed to the non-public post, just ones that are non-public but attributed to a public post which would fall under the #562 description.  Let's close this one out.
