### ISSUE TITLE
twitter publish: error 32 "Could not authenticate you."

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#389]
seen this a few times over the last few days (week) or so, i think just for @gRegorLove and @barryf. (sorry guys!)

example [from this log](https://www.brid.gy/log?start_time=1429801303&key=aglzfmJyaWQtZ3lyXQsSDVB1Ymxpc2hlZFBhZ2UiNmh0dHBzOi8vYmFycnlmcm9zdC5jb20vMjAxNS8wNC9pLXNlZW0tdG8taGF2ZS1sb3N0LWFsbAwLEgdQdWJsaXNoGICAgICAgIAKDA):
```py
D Fetching https://api.twitter.com/1.1/statuses/update.json?status=I+seem+to+have+lost+all+my+saved+searches+in+%40tweetbot+and+the+Twitter+web+app.+I+only+had+a+few+and+can+recreate+but+%C2%AF%5C_%28%E3%83%84%29_%2F%C2%AF
W Error 401, response body: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
W Error 401, response body: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
W Error: {"errors":[{"code":32,"message":"Could not authenticate you."}]} HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/3.383799630097582262/publish.py", line 195, in _run
    result = self.attempt_single_item(item)
  File "/base/data/home/apps/s~brid-gy/3.383799630097582262/publish.py", line 313, in attempt_single_item
    result = self.source.as_source.create(obj, include_link=not omit_link)
  File "/base/data/home/apps/s~brid-gy/3.383799630097582262/activitystreams/twitter.py", line 405, in create
    return self._create(obj, preview=False, include_link=include_link)
...
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized
```

**Comment by snarfed** [comment]
on the plus side, i'm doing a happy dance in my seat right now to have a silo bug that's _not facebook_. (i live a small, sad life. :P)

**Comment by barryf** [comment]
Hey @snarfed. No need to apologise! -- is there anything I can help with in terms of debugging? I've tried re-authenticating but that still results in the `401`.

**Comment by snarfed** [comment]
@barryf thanks for the offer! i don't know where to start looking yet, and [my day job has been pretty busy recently](https://snarfed.org/2015-04-21_introducing-color-genomics), so it may be a few days before i get to it. definitely feel free to jump in if you want!

**Comment by snarfed** [comment]
progress: i can reproduce it on https://www.brid.gy/twitter/snarfed_org by trying to publish http://xenon.stanford.edu/~rbarrett/iso.html, but not with the same page and account in dev_appserver. so maybe there's something up with bridgy's twitter app.

**Comment by snarfed** [comment]
...except we use the same twitter app (key and secret) for localhost and for brid.gy. so i'm kind of stumped. :(

**Comment by snarfed** [comment]
i've poked at this some more, but no luck. [web searches](https://www.google.com/search?q=++twitter+api+code+32+%22Could+not+authenticate+you.%22&ie=utf-8&oe=utf-8) say re-authing as the individual user sometimes fixes it, but not always (including here). they also say it can happen when you change your app-level permissions, or auth as a user with a different `x_auth_access_type`, like we did in #258...but both of those were a while back, and it's been working since then.

i'm at a wall. anyone have any ideas?

**Comment by barryf** [comment]
Re-authing seems to be the only recommendation I've seen and, as you say, that doesn't help here.

**Comment by snarfed** [comment]
next lead i'm going to try: check tweepy's changelog and update if i see anything promising. (or maybe even if i don't.)

**Comment by barryf** [comment]
Thanks Ryan. If it doesn't look like there's going to be a simple fix I'll happily write my own Twitter syndication code (I'd started down that track anyway but found your implementation was better) and I guess others could also do so. As you say, you've got quite a lot on your plate with your day job (congrats!).

**Comment by snarfed** [comment]
i upgraded tweepy, but no luck. i'm out of ideas. :/

**Comment by snarfed** [comment]
another data point: i tried locally with the _same access token_ as an account in prod, and it worked. so they've blacklisted app engine, or something else about the prod environment that i can't find is unhappy.

**Comment by snarfed** [comment]
[posted this on github's developer forum](https://twittercommunity.com/t/post-to-statuses-update-json-started-hitting-error-32-could-not-authenticate-you-with-no-code-changes/36495):

>hi all! my app has been happily posting tweets via `/1.1/statuses/update` for a year or so. a week ago it started returning HTTP 401 `{"errors":[{"code":32,"message":"Could not authenticate you."}]}` for all of my users. i hadn't changed any of my relevant code or app settings recently.
>
>here's the particularly odd part: when i try it in my local environment with the same code, twitter app key/secret, and even _the exact same user access token key/secret_, it works fine. it only fails in production.
>
>i'm on google app engine using tweepy. (tried versions 2.2 and 3.3, the latest. both fail.) could app engine's external facing IPs have been blacklisted or graylisted somehow?
>
>[more details in this github issue.](https://github.com/snarfed/bridgy/issues/389) any ideas? thanks in advance!

**Comment by snarfed** [comment]
the plot thickens: [a number of people chimed in on that forum post](https://twittercommunity.com/t/post-to-statuses-update-json-started-hitting-error-32-could-not-authenticate-you-with-no-code-changes/36495) with the same problem.

i've also [posted on the GAE forum](https://groups.google.com/forum/#!topic/google-appengine/6ILDt39anbs/discussion).

**Comment by kylewm** [comment]
major respect to the three of you debugging a black box. that's awesome to watch.

**Comment by snarfed** [comment]
aww thanks! especially to dave loomer in that [GAE forum thread](https://groups.google.com/d/topic/google-appengine/6ILDt39anbs/discussion), he's diving _really_ deep.

**Comment by snarfed** [comment]
to summarize the current state of affairs, we think app engine 1.9.20 introduced new URL-escaping behavior into the urlfetch API that sometimes breaks OAuth 1.1 signatures in Twitter API calls. we see this on 1.9.20 instances but not 1.9.19. (i'm guessing it would also happen with other OAuth 1.1 services, e.g. Tumblr.)

[a google devrel person pointed us](https://groups.google.com/d/msg/google-appengine/6ILDt39anbs/g8mEEV4mNnMJ) to [this app engine issue](https://code.google.com/p/googleappengine/issues/detail?id=11917), which sounds like the same thing. feel free to star it!

**Comment by snarfed** [comment]
app engine fixed their bug; bridgy publish can tweet again! yay. glad i can close this.

**Comment by barryf** [comment]
Wow. True needle-in-a-haystack debugging. Thanks very much for persevering with this. I'm happily Bridgy publishing again.
