### ISSUE TITLE
Lanyrd publish event support

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#390]
Lanyrd has a pretty good API, and is a good place to POSSE events like IndieWebCamps and Homebrew Website Club meetups. Would be nice to be able to automatically create a Lanyrd POSSE copy event for an Indie Event (since their API allows it, in contrast to FB).

**Comment by snarfed** [comment]
if anyone's interested in tackling this, i've written up [comprehensive instructions on how to add a new silo to bridgy.](https://github.com/snarfed/bridgy#adding-a-new-silo) feel free to jump in!

**Comment by chrisaldrich** [comment]
Lanyard doesn't exist as an active service anymore after shuttering in 2018.

**Comment by snarfed** [comment]
aww, sad. thanks for the update.

i guess it also says something for this issue tracker's longevity, for better or worse. 😎
