### ISSUE TITLE
Lanyrd backfeed

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#391]
Lanyrd has a pretty good API, and is a good place to POSSE events like IndieWebCamps and Homebrew Website Club meetups. Would be nice to be able to automatically have RSVPs on Lanyrd backfeed to the original Indie Event.

**Comment by snarfed** [comment]
noted! #390 too. i don't use lanyrd, but i hear great things!

**Comment by snarfed** [comment]
if anyone's interested in tackling this, i've written up [comprehensive instructions on how to add a new silo to bridgy.](https://github.com/snarfed/bridgy#adding-a-new-silo) feel free to jump in!

**Comment by tommorris** [comment]
As Lanyrd now seems pretty definitively dead, this seems highly unlikely to happen. 😞

**Comment by snarfed** [comment]
agreed, thanks. closing. 😢
