### ISSUE TITLE
brid.gy does not find website in profile anymore

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#393]
maybe it’s a facebook api change, but bridgy seems not find my website in my profile anymore. it worked fine all the time, but right now it doesn’t. i have 4 sites in my facebook profile (which was fine), but bridgy also failed to grab the info when i just listed my main site.
![bildschirmfoto 2015-05-02 um 10 42 35](https://cloud.githubusercontent.com/assets/4541494/7440489/03dbc9c2-f0b8-11e4-9bc6-02f450d149ed.png)

**Comment by kylewm** [comment]
It looks like bridgy has an invalid access token for you... Have you tried re-authing?
 
![felix-debug-access-token](https://cloud.githubusercontent.com/assets/950127/7441645/eba09fe8-f0a5-11e4-8bd4-6d70f318d535.png)

**Comment by diplix** [comment]
yeah. tried it several times. logged out, and in. deleted the bridgy-app in facebook, re-authorisation seems to be different, too. i do not get asked by bridgy if i want to use my account or my pages. bridgy only offers me my personal account. which would be fine, if it worked.

**Comment by kylewm** [comment]
Hmm, it seems to have worked that time. The token is valid now, but still not getting your website. We may need to double-check the scopes that Bridgy asks for...

**Comment by diplix** [comment]
i checked my profile with the facebook api console and if i ask with a broad enough scope, i get the right answer.
![bildschirmfoto 2015-05-02 um 17 52 33](https://cloud.githubusercontent.com/assets/4541494/7441693/0d01a4f4-f0f4-11e4-99b1-84ab5cd83f8a.png)
![bildschirmfoto 2015-05-02 um 17 52 18](https://cloud.githubusercontent.com/assets/4541494/7441694/0d4c9f9a-f0f4-11e4-856e-80bb45b00db8.png)

**Comment by kylewm** [comment]
hmm, interesting, Bridgy doesn't have any of the scopes that it asks for for you. It's supposed to request 

user_likes, user_website, user_events, user_photos, user_videos, user_status, user_posts, read_stream, rsvp_event, manage_pages, publish_pages, publish_actions, public_profile

but has only public_profile

**Comment by diplix** [comment]
https://developers.facebook.com/docs/facebook-login/permissions/v2.3#checking
> If someone has declined a permission for your app, the login dialog won't let your app re-request the permission unless you pass auth_type=rerequest along with your request.

(may be i once denied (accidentaly) the permissions once and now facebook won’t let bridgy re-request them?)

**Comment by kylewm** [comment]
I tried removing Bridgy from my apps and reauthing, thinking maybe I would lose `user_website`, but when I re-authorized it, it still had the permission. Though it's possible I'm getting special treatment as a "developer". I will check what scopes we have under the new Facebook Login stuff, but otherwise I'm stumped

**Comment by kylewm** [comment]
I don't think it's anything you did, very probably it's to do with the Facebook Login changes that just shipped yesterday. I think @snarfed will need to submit the app for review of a few more login permissions.

![permission-scopes](https://cloud.githubusercontent.com/assets/950127/7441790/5d777c3a-f0ac-11e4-9066-eb829b6e7a0c.png)

**Comment by diplix** [comment]
ok. thanks a lot.

**Comment by snarfed** [comment]
ugh, sorry guys. i hate silos. bridgy would be so much easier if i could drop silo support altogether. :P

given the timing, i suspect this is due to the [FB v2.0 API apocalypse](https://developers.facebook.com/blog/post/2015/04/28/april-30-migration/), even though bridgy has been using the v2.2 API explicitly for a while now. not sure of more details quite yet. constant FB API fires like this over the last quarter have been gradually sapping my energy and will to fight them. :/

**Comment by snarfed** [comment]
btw @kylewm (or anyone else who wants to help!), here are my notes from the fb reviews i've gone through before:
* https://snarfed.org/bridgy_facebook_permissions_review
* https://snarfed.org/facebook_permissions_review_activitystreams_facebook-atom

**Comment by kylewm** [comment]
I tested logging in with only `user_website`. It did not prompt me to select a User or Page, but otherwise everything seemed to work. So I filed an application for user_website, which should be easy to get (feel like I read somewhere that they had some sort of ast review process for Facebook Login scopes). Hopefully it will be processed soon.

**Comment by snarfed** [comment]
awesome, thanks @kylewm! much appreciated.

but the reason you're not getting prompted for use vs page is probably that we don't actually have the pages permission yet. i applied a couple times but never got it. that's #41.

**Comment by snarfed** [comment]
also, when we upgraded bridgy to the v2.2 API, i explicitly checked in #339 that we still got the `user_website` permission. have i mentioned recently that i hate the FB API? :/

**Comment by kylewm** [comment]
It sounds like we need `user_posts` too based on #394, should I cancel that first submission and add it?

**Comment by snarfed** [comment]
@kylewm good catch, sure!

**Comment by snarfed** [comment]
woot, [FB granted the new permissions](https://developers.facebook.com/apps/256884317673197/review-status/)!

**Comment by nekr0z** [comment]
Great! Any hope things start working any time soon?

**Comment by snarfed** [comment]
@diplix hopefully yes! if you re-sign up with facebook, your account might actually start working again now. we plan to automatically notify other users to do that soon.

**Comment by armingrewe** [comment]
It's already working again, at least for me. I was able to "re-link" my profile successfully and bridgy is picking up likes and comments again.

**Comment by drikkes** [comment]
I deleted the app in FB, then reconnected, but still get this error message: 
Error: {"error":{"message":"(#200) The user hasn't authorized the application to perform this action","type":"OAuthException","code":200}} HTTP Error 403: Forbidden
At least, it previews the content right. Before it says "Couldn't fetch...".
Bridgy still shows me only the personal profile, no FB pages. 
What am I doing wrong?

**Comment by kylewm** [comment]
Hi @drikkes! Thanks for reporting. It sounds like you are trying to publish to FB, which is a separate issue. Have you already tried disabling and re-enabling the Publish stuff specifically (the right hand column of https://www.brid.gy/facebook/10206219375153745)?

If that doesn't work, would you mind opening a new issue describing your problem?

**Comment by snarfed** [comment]
agreed. FB says we have `publish_actions`, so publish should still work. https://developers.facebook.com/apps/256884317673197/review-status/

@drikkes please do let us know if re-enabling publish doesn't work for you!

tentatively closing.

**Comment by drikkes** [comment]
Yes, working again. Dis- and re-enabling obviously did the job. Thanks!

**Comment by nekr0z** [comment]
I remove Bridgy from my Facebook apps, then re-register it again, and yet it stillI says it wants my website in profile. Does not work.

**Comment by kylewm** [comment]
@nekr0z could you check that the website in your Facebook profile starts with http:// or https://? If it is just a bare domain, I think Bridgy will miss it (which we should probably fix).

**Comment by nekr0z** [comment]
@kylewm yes, it does start with http://

**Comment by kylewm** [comment]
and it looks like Bridgy found it now? https://www.brid.gy/facebook/10152710552987085

**Comment by nekr0z** [comment]
@kylewm which actually seemed to be the problem: the site is https only. I changed it to https in profile, now it works.
