### ISSUE TITLE
FB started 400ing /me/posts API requests for some users

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#394]
started about 24h ago, around the same time as #393. maybe same root cause: timing implies that the [FB v2.0 API apocalypse](https://developers.facebook.com/blog/post/2015/04/28/april-30-migration/) may be to blame, and/or that we don't have the right permissions for those users.

[example log](https://www.brid.gy/log?start_time=1430588071&key=aglzfmJyaWQtZ3lyIQsSDEZhY2Vib29rUGFnZSIPOTU1NTQ3NzUxMTIzNDI1DA):

```py
Fetching https://graph.facebook.com/v2.2/me/posts?offset=0&limit=50&access_token=...... kwargs {'headers': {'If-None-Match': u'"71aab0b83a454f8018c8c6e3dd07f13419985fee"'}}
Error 400, response body: Bad Request
HTTP Error 400: Bad Request
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/3.383971133541294147/tasks.py", line 109, in post
source_updates.update(self.poll(source))
File "/base/data/home/apps/s~brid-gy/3.383971133541294147/tasks.py", line 161, in poll
cache=cache)
File "/base/data/home/apps/s~brid-gy/3.383971133541294147/facebook.py", line 104, in get_activities_response
resp = self.as_source.get_activities_response(group_id=SELF, **kwargs)
File "/base/data/home/apps/s~brid-gy/3.383971133541294147/activitystreams/facebook.py", line 227, in get_activities_response
resp = self.urlopen(url, headers=headers, parse_response=False)
File "/base/data/home/apps/s~brid-gy/3.383971133541294147/activitystreams/facebook.py", line 1204, in urlopen
timeout=appengine_config.HTTP_TIMEOUT)
...
HTTPError: HTTP Error 400: Bad Request
```

**Comment by snarfed** [comment]
follow #393 for @kylewm's and@diplix's great work so far. also thanks to @armingrewe for [first reporting this](https://twitter.com/islayblog/status/594109657377017856)!

**Comment by armingrewe** [comment]
For some reason didn't spot this earlier, but it looks like there's a lot more impacted by the FB API change:
I'm also using the Jetpack Share plugin on my photoblog. That used to show how many times an entry was liked on FB. Those numbers have now completely disappeared for all entries. For Twitter and Pinterest the numbers still show (G+ never showed), but FB is gone.
No idea if this helps you guys, but I thought you might find it interesting.

**Comment by snarfed** [comment]
thanks for the info! definitely interesting. apocalypse indeed. :/

**Comment by snarfed** [comment]
this is getting acute. :(

![chart](https://cloud.githubusercontent.com/assets/778068/7446296/a44cf950-f188-11e4-99f8-ac26e06d5e37.png)

**Comment by snarfed** [comment]
woot, [FB granted the new permissions](https://developers.facebook.com/apps/256884317673197/review-status/)!

**Comment by armingrewe** [comment]
That seems to have fixed it. I just "re-linked" my FB account and it's starting to find the links. Quite a lot coming through now, I'll be busy approving this evening.
Kind of related, Jetpack have released a new version today as well, that's fixed the like count.

**Comment by snarfed** [comment]
currently disabling ("pausing") FB accounts hit by this. we try to send them an FB notification, like usual, but that API call is getting 403ed with `{"error":{"message":"(#200) Cannot send notifications to a user who has not installed the app","type":"OAuthException","code":200}}`. sigh.

**Comment by snarfed** [comment]
reverted that change. all affected accounts should be disabled and notified (or at least attempted).
