### ISSUE TITLE
Status query endpoint for Known

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#395]
I'd like to help Known improve their Bridgy Connect UX ([parallel issues here](https://github.com/idno/Known/issues/843)). The first step was easy: add query params for `{"result": "success", "user": user-id}` to the callback.

I need a little guidance on the second step: how can they check in the future if the user is still connected in Bridgy. Thinking a couple of options:

1. Add microformats classes to the user pages. The user page could reasonably be an `h-card` but basically all of the properties would be `p-bridgy-something`. Stuff like, p-bridgy-last-polled, p-bridgy-listen-status, p-bridgy-publish-status, p-bridgy-warning-message...

2. Support `?format=json` on the user page endpoint, and return a json message. This seems easiest, but I really don't want to accidentally create a crappy piecemeal Bridgy REST API.

**Comment by snarfed** [comment]
huh. interesting!

i honestly don't know which i prefer, and i don't feel too strongly. i also think they're both about the same difficulty/effort. feel free to propose something!

**Comment by snarfed** [comment]
oh btw you can use github's native comment linking across projects with eg idno/Known#843.

**Comment by kylewm** [comment]
I'm leaning microformats now. less because I have drunk the mf2 koolaid, and more because I think it will be a less invasive change to the code.

**Comment by snarfed** [comment]
sgtm! btw there's a prefix for nonstandard mf2 extension classes. I've forgotten it but i know @aaronpk uses it.

**Comment by kylewm** [comment]
thanks! and hehe, you can use `-x-` if you want to research/document your experimental use, or `-appSpecificPrefix-` if you don't. Aaron uses `p-p3k-` on e.g. http://aaronparecki.com/metrics

**Comment by kylewm** [comment]
Closing now, thanks for your help!
