### ISSUE TITLE
Error sending 'Likes' to post with "10.10 Yosemite" in Title

### ISSUE THREAD

**Issue by andrejstefanovski** [snarfed/bridgy#398]
_**User:**_ 
https://www.brid.gy/facebook/7724450#

_**Error:**_
>0.1.0.2 - - [08/May/2015:04:16:42 -0700] "POST /_ah/queue/propagate HTTP/1.1" 306 133 "https://www.brid.gy/retry" "AppEngine-Google; (+http://code.google.com/appengine)"
>
>2015-05-08 11:16:42.836400 D Params: UnicodeMultiDict([(u'response_key', u'aglzfmJy...')])
>2015-05-08 11:16:42.904520 I Source: andrej stefanovski (Facebook) 7724450, http://brid-gy.appspot.com/facebook/7724450
>2015-05-08 11:16:42.904840 I Created by this poll: http://brid-gy.appspot.com/log?start_time=1430394305&key=aglzfmJyaWQtZ3lyGQsSDEZhY2Vib29rUGFnZSIHNzcyNDQ1MAw
>2015-05-08 11:16:42.905100 I Starting Response like tag:facebook.com,2013:10102306756099158_liked_by_10204689596535026 https://www.facebook.com/7724450/posts/10102306756099158
>2015-05-08 11:16:42.908269 I Webmention from https://brid-gy.appspot.com/like/facebook/7724450/10102306756099158/10204689596535026 to http://10.10/Yosemite
>2015-05-08 11:16:42.909880 I Sending...
>2015-05-08 11:16:42.923320 I Starting new HTTP connection (1): 10.10
>2015-05-08 11:16:42.926510 W 
>Traceback (most recent call last):
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/tasks.py", line 478, in do_send_webmentions
>    if not mention.send(timeout=999, headers=util.USER_AGENT_HEADER):
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/webmention-tools/webmentiontools/send.py", line 24, in send
>    self._discoverEndpoint()
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/webmention-tools/webmentiontools/send.py", line 30, in _discoverEndpoint
>    r = requests.get(self.target_url, verify=False, **self.requests_kwargs)
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/activitystreams/oauth_dropins/requests_module/requests/api.py", line 55, in >get
>    return request('get', url, **kwargs)
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/activitystreams/oauth_dropins/requests_module/requests/api.py", line 44, in >request
>    return session.request(method=method, url=url, **kwargs)
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/activitystreams/oauth_dropins/requests_module/requests/sessions.py", line >383, in request
>    resp = self.send(prep, **send_kwargs)
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/activitystreams/oauth_dropins/requests_module/requests/sessions.py", line >486, in send
>    r = adapter.send(request, **kwargs)
>  File "/base/data/home/apps/s~brid-gy/3.384143210970976928/activitystreams/oauth_dropins/requests_module/requests/adapters.py", line >372, in send
>    raise ConnectionError(e)
>ConnectionError: HTTPConnectionPool(host='10.10', port=80): Max retries exceeded with url: /Yosemite (Caused by <class 'google.appengine.api.remote_socket._remote_socket_error.error'>: An >error occured while connecting to the server: Unable to connect to server at URL: http://10.10/Yosemite)
>2015-05-08 11:16:42.932230 W Error sending to endpoint: {'code': 'EXCEPTION'}
>2015-05-08 11:16:42.932500 W Propagate task failed

_**Image:**_ 
![screen shot 2015-05-08 at 7 42 24 am](https://cloud.githubusercontent.com/assets/6420626/7535724/2c1e1474-f556-11e4-8ae7-3c1b33654399.png)

**Comment by kylewm** [comment]
Thank you for the report, @andrejstefanovski! That's an interesting edge case.
 
It looks like the [permashortcitation](https://indiewebcamp.com/permashortcitation) false positive causes Bridgy to assume the 10.10/Yosemite is the original, and any other links are just mentions (and I don't believe Known shows received webmentions that aren't explicitly replies, likes, etc.).

```
<a class="u-mention" href="https://social.andrejstefanovski.com/10101859667632951/creating-a-mac-os-x-usb-installer-1010-yosemite"></a>
<a class="u-mention" href="https://social.andrejstefanovski.com/2015/creating-a-mac-os-x-usb-installer-1010-yosemite"></a>
  </div>
<a class="u-like u-like-of" href="https://www.facebook.com/7724450/posts/10102306756099158"></a>
<a class="u-like u-like-of" href="http://10.10/Yosemite"></a>
```

**Comment by snarfed** [comment]
yup. thanks for filling, andrej! we thought this was hilarious (or at least i did) when we first saw it: http://indiewebcamp.com/irc/2015-04-30#t1430411897829

two possible solutions are hard-coding the list of all TLDs into our regex, which is unlikely, or not allowing numbers in TLDs, or at least as the first character, which could be reasonable.

this bug is pretty rare, so i don't know that we'd prioritize it, but I'd happily merge a PR for the second approach above.

**Comment by andrejstefanovski** [comment]
@snarfed I thought it was pretty funny myself. It's such an odd ball bug I agree it doesn't merit too much time; certainly not maintaining a list. Mostly I just wanted to share and give you a heads up.

Thanks for the service and everyone's contributions - they are very much appreciated.

**Comment by snarfed** [comment]
#416 is an expanded version of this, so i'm going to merge it in there.

**Comment by snarfed** [comment]
funny, we hit another one of these: `Photos.app`. https://www.brid.gy/twitter/myfreeweb#responses
