### ISSUE TITLE
use authenticate endpoint when disabling a Twitter account

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#400]
When you click the Disable button on a Twitter account, it would be nice to go to /authenticate instead of /authorize. It is currently confusing to see "Authorize Bridgy to use your account" when you click disable.

By my reading of the code, we just need to pass an empty `access_type` [here](https://github.com/snarfed/bridgy/blob/master/twitter.py#L107) when the operation is delete instead of add.

**Comment by snarfed** [comment]
interesting. it's been a while, but iirc one reason i switched to `/authorize` is that it doesn't re-prompt you if you've already approved. looks like that was #245. did that not stick? (#258 modified that some, but i don't think it switched endpoints.)

**Comment by snarfed** [comment]
i started following the bread crumb trail and ended up getting a 500 from github on https://github.com/snarfed/oauth-dropins/commit/7ff17feabb86ed88133332b8544f9aaf9c2995cf . whee.

if you want to tackle this, go for it! my personal priorities (in order) are:
1. maintain the `x_auth_access_type` read only vs read/write permission distinction for listen vs publish.
1. avoid prompting if they've already approved us.
1. have the twitter prompt use the appropriate word.

...but i'm open to discussion!

**Comment by kylewm** [comment]
GitHub is giving me a 500 on most everything now.. hopefully a transient bug

02f688d41aa898dbcf3f09b1af0891b1fff5af71 has the answer. It adds x_auth_type_type when disabling, so you can disable publish without disabling altogether, and Twitter won't let us do that without using /authorize. Thanks for looking at it, I'll close this now with CANTFIX
