### ISSUE TITLE
FB authorization not asking for user_posts for some users 

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#401]
@nekr0z [reports](https://github.com/snarfed/bridgy/issues/375#issuecomment-100262719) (thank you!) that Facebook is only asking him for user_website and public_profile, not user_posts and the rest. So we don't see any posts in his feed and don't backfeed any comments.

**Comment by nekr0z** [comment]
@kylewm The funny thing is: here's the redirecting URL: https://www.facebook.com/v2.2/dialog/oauth?scope=,user_website,user_status,user_photos,user_events,read_stream,manage_pages&client_id=256884317673197&r
![screenshot_2015-05-08-17-50-08](https://cloud.githubusercontent.com/assets/1515080/7539917/0fdeac4e-f5b3-11e4-89c0-d734f791fbec.jpg)
edirect_uri=https%3A%2F%2Fwww.brid.gy%2Ffacebook%2Foauth_handler%3Fstate%3D%257B%2522feature%2522%253A%2522listen%2522%252C%2522operation%2522%253A%2522add%2522%257D&response_type=code

It looks like it does ask for the permissions eventually. However, Facebook does not care, see the screenshot.

**Comment by snarfed** [comment]
one possibility: this kind of partial prompt can happen when you've approved some permissions but not others. in that case, the prompt only shows the new permissions.

**Comment by nekr0z** [comment]
@snarfed Apps page in Facebook lists no Brid.gy, so it's hardly a case of some permissions already approved.

**Comment by snarfed** [comment]
@nekr0z FB's permission prompt logic is actually pretty complicated. for example, they often split up the permissions we ask for and show multiple prompts, one after another. i think this is to highlight certain permissions and try to make users pay more attention to them, but i'm not sure.

another example is that i suspect they remember _which_ permissions you've approved for an app even after you revoke it. when you re-auth that app, they may not prompt for those permissions specifically, just for the app as a whole and any new permissions. (i'm not 100% sure about this, but it matches v2.x API behavior i've seen so far.)

i can't guarantee either of these is happening for you, but i do suspect them. regardless, the key test is to approve all of the prompts and see if bridgy then finds your posts. if it still doesn't, we definitely have a bug.

**Comment by nekr0z** [comment]
@snarfed The trouble is, right now I have granted it what it wanted (i.e. public profile and website), and it simply doesn't ask me for anything more. And no, Bridgy doesn't see anything.

**Comment by kylewm** [comment]
@nekr0z thank you for sharing the screenshot above, that helped me realize that we are not actually asking for the `user_posts` scope. (Argh this new Facebook API stuff is complicated).

I'm not in a place where I deploy a fix right now, but I think as a temporary workaround you can literally just edit the scopes parameter in that url to add user_posts:

https://www.facebook.com/v2.2/dialog/oauth?scope=user_posts,user_website,user_status,user_photos,user_events,read_stream,manage_pages&client_id=256884317673197&redirect_uri=https%3A%2F%2Fwww.brid.gy%2Ffacebook%2Foauth_handler%3Fstate%3D%257B%2522feature%2522%253A%2522listen%2522%252C%2522operation%2522%253A%2522add%2522%257D&response_type=code

**Comment by snarfed** [comment]
i can actually add `user_posts` right now. i'll update here when it's deployed.

**Comment by snarfed** [comment]
deployed. feel free to try again!

**Comment by drikkes** [comment]
Clicking the FB link above adding the permission worked for me. Bridgy just polled the likes for the last two posts.



Hendrik SpreeOberländer Wall 28

50678 Köln

http://drikkes.com/

+4915154775884

**Comment by nekr0z** [comment]
@snarfed @kylewm It did ask for a new permission this time and seems to be getting the posts now. Looks fixed for me. Thank you, guys, you're awesome!

**Comment by kylewm** [comment]
@nekr0z Known is returning an HTTP 400 error when the webmention is sent... The "The target page https://www.evgenykuznetsov.org/2015/untitled-1 does not exist." error is coming from your Known site. I would guess it's confused by https vs. http

2015-05-08 18:12:56.443320 D "POST /webmention/ HTTP/1.1" 400 None
2015-05-08 18:12:56.445010 I Giving up this target. {'code': 'RECEIVER_ERROR', 'request': u'POST http://www.evgenykuznetsov.org/webmention/ (with source=https://brid-gy.appspot.com/like/facebook/10152710552987085/10152713307512085/907789262576879, target=https://www.evgenykuznetsov.org/2015/untitled-1)', u'error_text': u'The target page https://www.evgenykuznetsov.org/2015/untitled-1 does not exist.', 'http_status': 400, u'error': u'target_not_found'}

**Comment by nekr0z** [comment]
@kylewm ah, I see. That page actually does exist, but Known seems to have got confused when moving to another domain, and it tries to use *.withknown.com certificate for that link.

Anyway, thanks a lot again.
