### ISSUE TITLE
pulling facebook comments faulty?

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#403]
don’t know if it's a bug, but since the latest facebook api-apocalypse i don’t get my facebook likes and comments anymore, despite the new scopes brid.gy is requesting. so i did a little manual [webmentioning](https://www.brid.gy/post/facebook/548616784/10152984131726785) and found this:

https://www.brid.gy/comment/facebook/548616784/10152984131726785/10152984395521785

this should produce (according to the pattern /comment/SITE/USER_ID/POST_ID/COMMENT_ID) the mf2-comment-page: 
* my USER_ID is [548616784](https://www.facebook.com/548616784)
* the POST_ID is [10152984131726785](https://www.facebook.com/548616784/posts/10152984131726785) and 
* the COMMENT_ID is [10152984395521785](https://www.facebook.com/diplix/posts/10152984131726785?comment_id=10152984383606785)

still [this](https://www.brid.gy/comment/facebook/548616784/10152984131726785/10152984395521785) produces this error:
> Facebook error:
{"error":{"message":"Unsupported get request. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100}}

the post is public and so are the comments, so it should not be an access rights problem. may-be the API query needs to be altered? can you reproduce it with other new facebook comments?

**Comment by kylewm** [comment]
Thank you for the detailed report. First could you try re-authorizing Bridgy with Facebook? (you don't have to revoke the old permission just click the login button on https://brid.gy again). We were not requesting all the permissions that were needed, discussed in #401.

**Comment by diplix** [comment]
great. polling seems to work again. thanks!

**Comment by diplix** [comment]
sorry for reopening this, or rather prematurely closing it. polling works all right, bridgy also sends webmentions for facebook comments. they don’t work though, because the comments can not be checked:
https://www.brid.gy/comment/facebook/548616784/10152984131726785/10152984395521785
https://www.brid.gy/comment/facebook/548616784/10152989132581785/10152989158951785

for voth these comments webmentions were sent, but when die webmention client tries to check the link it gets a facebook error instead of parsable mf2:

> Facebook error:
{"error":{"message":"Unsupported get request. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100}}

**Comment by kylewm** [comment]
> sorry for reopening this

Not at all, thank you for following up.

OK I haven't seen this before ... we can see Felix's original post which has comments nested in it

![diplix-posts-comments](https://cloud.githubusercontent.com/assets/950127/7567657/29f481e2-f7b3-11e4-9c82-b061898593f2.png)

but clicking the ID of a comment is a dead-end

![diplix-comment-by-id](https://cloud.githubusercontent.com/assets/950127/7567661/2ca9a106-f7b3-11e4-9f94-c2957db10cbf.png)

**Comment by diplix** [comment]
strange. with some comments clicking the ID produces an error, but some work. this one i can see: 10152989132581785_10152989136406785 
![bildschirmfoto 2015-05-11 um 18 09 49](https://cloud.githubusercontent.com/assets/4541494/7569443/139a72ac-f809-11e4-9412-9e144d1f2eb7.png)

this one (my own) i can’t see: 10152989246176785_10152989284501785
![bildschirmfoto 2015-05-11 um 18 10 43](https://cloud.githubusercontent.com/assets/4541494/7569446/1931ed6c-f809-11e4-9a7d-beecd778ed52.png)

**Comment by kylewm** [comment]
if you can't even see some of your *own* comments, that makes me think it's a bug and not a permissions issue. if it doesn't sort itself out in a few days, we can try filing a bug on their developer site (those usually get attention right away)

**Comment by snarfed** [comment]
sigh, yeah. we've consistently seen problems when we fetch FB objects with and without prefixes like `USERID_`, `USERID_POSTID_`, `POSTID_`, etc. some 400 like this, some return different fields, etc. background in #388 #350 #229 #337 #189 #305...[i'm glazing over...]

it's not that we've seen the behavior change over time (i think), just that it's hard to tell which prefix(es) we need for which object types. [when we've asked on the developer site](https://developers.facebook.com/bugs/786903278061433/), FB people generally say to only use ids that the API returns us, and not try to construct them ourselves, which isn't very useful for bridgy specifically.

so, it's very possible this isn't a permissions issue or an FB bug, but instead that we're still using the wrong id format in some cases. :(

**Comment by kylewm** [comment]
@snarfed except in this case, in the graph explorer, we are very carefully following the advice to "only use ids that the API returns us", literally just clicking on the linked id, and it still returns the error (i.e. Bridgy is not involved at all in reproducing this)

**Comment by snarfed** [comment]
@kylewm oh agreed, their advice definitely doesn't always work either :/

**Comment by diplix** [comment]
i have a new post where i can view all comments in ie API explorer:
548616784_10152991837921785 (myID_postID)

the API explorer shows the comment all right:
10152991837921785_10152991855376785 (postID_commentID)

but bridgy doesn’t; 
https://www.brid.gy/comment/facebook/548616784/10152991837921785/10152991855376785

it seems to me it’s not a permission issue, but a query issue?

**Comment by kylewm** [comment]
With the access token that bridgy has for you, (which has scopes `user_website, user_posts, rsvp_event, publish_actions, public_profile`), I cannot access that comment via the API explorer... I can see the post just fine, which even contains the comment and its text, but clicking the comment id itself it gives that error.

**Comment by snarfed** [comment]
@kylewm huh, interesting point that fetching the post works and contains the comment object. is it missing anything we care about? if not, could we fall back to fetching the post and extracting comments from there when we can't fetch comments directly?

(btw i think i've given up trying to actually understand FB API ids and permissions. :P it all seems pretty arbitrary right now. on the plus side, it does look deterministic, at least within API major versions, so if we treat it like a black box and run experiments, maybe we can keep our head above water. ¯\_(ツ)_/¯ )

**Comment by diplix** [comment]
@kylewm hmm. i’m wondering if my account is the only one experiencing this. what ever, i like @snarfed’s idea.

**Comment by kylewm** [comment]
No you're not the only one. I just spot checked GWG's account, and it has similarly unreachable comments, e.g.

/v2.3/828010357287507_828045163950693

**Comment by kylewm** [comment]
This thread on FB's bug tracker is discussing the same problem: https://developers.facebook.com/bugs/449024225257676/ (It kind of seems like the reviewer is just choosing permissions scopes randomly telling the person to try)

I asked on SO what is the difference between "user_posts" (which we have) and "user_status" (which we don't). http://stackoverflow.com/questions/30241192/what-is-the-difference-between-fbs-user-posts-and-user-status-permissions

**Comment by kylewm** [comment]
I posted this comment on the FB support thread. Will he be caught by my unrefutable logic??

```
Hi Chi,

I am experiencing the same issue. I can fetch a post by its ID, but when I try to fetch one of its comments by comment ID, I get the error above.

POST_ID: 100002356503167_828010357287507
COMMENT_ID: 828010357287507_828052707283272

(The post and comment are by the same author)

The documentation for comments says "To read a comment, you generally need the same permissions as required for viewing the object that the comment was added to". We have permission to read the parent object, and in fact the parent object contains the full text of the comment in its "comments" field.

The fact that I can see the full comment details inside the post object when fetching the post ID means that EITHER: 

1) I have permission to see the comment, and it's a Facebook bug that I get an error when fetching by comment ID. 
2) I do not have permission to see the comment, and it's a Facebook bug that I am shown it in the post object.

I do not see how there can be a third option :)

Thanks,
Kyle
```

**Comment by snarfed** [comment]
UNREFUTABLE LOGIC!!! nice find!...and gives me an idea. @kylewm can you pls start an FB_API_HULK twitter acct? kthxbye!

/me waits with bated breath

**Comment by kylewm** [comment]
hahaha

FB DEVELOPER SUPPORT ENGINEER SCRIPT SAY "ALL ELSE FAIL, TELL THEM NEED READ_STREAM. THEN DIE LAUGHING."

**Comment by snarfed** [comment]
ahahahaha :):):) :(:(:(

**Comment by snarfed** [comment]
hey @diplix, we just got approved for some new permissions we needed (#407). mind re-authing facebook on bridgy and see if you get comments ok?

**Comment by diplix** [comment]
great. quite a lot of new comments and likes are pouring in now. those new permissions seem to have done it!

**Comment by diplix** [comment]
i have to differentiate a bit: most post comments are being pulled again. i just checked one posting, where the facebook API is still throwing that Unsupported get request error. all comments are shown, but the detail page still won’t generate:
https://www.brid.gy/post/facebook/548616784/10153006554581785
https://www.brid.gy/comment/facebook/548616784/10153006554581785/10153007765606785

:(

**Comment by kylewm** [comment]
had me worried there @diplix!!
