### ISSUE TITLE
set up an IRC bot

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#405]
TODO for me, set up an IRC bot for logging and async messaging in #bridgy (on freenode) 

It would be great if it also notified for GitHub activity like the bot in #pocoo does.

**Comment by snarfed** [comment]
huh. interesting! _definitely_only if you want to; I'm also ok if we leave it ephemeral and use #indiewebcamp for logging and tells.

if you do, one easy way could be to add it to the indiewebcamp slack account as a new channel.

**Comment by kylewm** [comment]
that's an idea, if you'd rather do Slack than IRC I'm totally open to that.
