### ISSUE TITLE
Facebook API live integration test

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#406]
FB API's changes and unexpected behavior have kept us behind the eight ball over the last 6 mos or so. that's no fun. i'd love to get us out in front and keep us there instead.

let's add an integration test against the live, production FB API, using a [test user](https://developers.facebook.com/docs/apps/test-users) populated with canned test data. the test would do the oauth dance, poll, find new responses, propagate them, fetch their mf2 handlers, and check that we get everything we expect. it would run as part of `alltests.py` with a flag that either enables or disables it, depending on which we make the default.

our existing unit test suite is great, but for our API client code, it's only as good as our understanding of those APIs. in FB's case, that understanding is clearly lacking. this would close that gap.

**Comment by snarfed** [comment]
cc @benwerd (if only to commiserate0 since he's feeling the FB API pain now too

**Comment by snarfed** [comment]
(no need to cc @kylewm since he both feels the FB pain and follows this issue tracker more closely than me these days :P)

**Comment by benwerd** [comment]
Suggesting Facebook augments taggable_friends with punchable_api_designers

**Comment by kylewm** [comment]
ohhh @benwerd you might want to get in on this @FB_API_HULK twitter account! https://github.com/snarfed/bridgy/issues/403#issuecomment-102084378

**Comment by snarfed** [comment]
it's alive, it's aliiiiive!!!

this is currently up and running. you'll need an access token for the canned user (100009447618341) to run it; ping me and i can send that to you if you want it.

the exciting part is that it runs all the way through signup, poll, and propagate, then hits a 400 on the first mf2 handler fetch, which means it reproduces #403. if we fix that, we might fix this too. fingers crossed!

...either that or maybe i just need a new access token with the newly approved #407 permissions. heh. ¯\_(ツ)_/¯

**Comment by kylewm** [comment]
Nicely done! Also your shrug emoji is missing an arm!

**Comment by snarfed** [comment]
heh, it's being rendered as markdown. :P

more good news: i re-authed the canned user, it got the new permissions, and now the test passes. woo! i'm adding it to the deploy command in the README, then i'll close this issue.

**Comment by kylewm** [comment]
> ping me and i can send that to you if you want it.

yes please!

**Comment by snarfed** [comment]
done! feel free to add to it or mess with it if you want.
