### ISSUE TITLE
Facebook: Apply for user_status, user_events, and user_photos

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#407]
Any others?

We apparently need all of these individual permissions in addition to user_posts. I'm not sure why.

According to

https://developers.facebook.com/bugs/449024225257676/?comment_id=424263017699018

user_status will fix #403

**Comment by kylewm** [comment]
Note that I applied half-heartedly for user_events and user_photos and was denied because they could not reproduce the steps I outlined. So when we do this, the steps need to be thorough.

**Comment by snarfed** [comment]
thanks for filing this! and for applying for the new permissions recently while i've been avoiding FB issues. :see_no_evil: :hear_no_evil: :speak_no_evil:

for posterity, here are [our currently approved and rejected permissions](https://developers.facebook.com/apps/256884317673197/review-status/), and the [info i've sent them in my previous applications](https://snarfed.org/bridgy_facebook_permissions_review), notably for `publish_actions` and `rsvp_event` (approved) and `manage_pages` (rejected).

the last one is meaningful. we've fully implemented support for FB pages, #41, but it doesn't work for new users since we're still not approved for `manage_pages`. we should probably try for that one again along with the rest.

**Comment by kylewm** [comment]
How about `publish_pages`? i.e. should Bridgy Publish allow users to publish *as* a Page?

**Comment by snarfed** [comment]
huh. sure! except... i see it on https://developers.facebook.com/docs/facebook-login/permissions/v2.3 , but not on https://developers.facebook.com/docs/facebook-login/permissions/v2.2 . is it 2.3 only? would we need to upgrade first?

**Comment by kylewm** [comment]
Ungggggh

![](https://pbs.twimg.com/media/CE_Hh1PWYAEtrPM.jpg:large)

**Comment by snarfed** [comment]
![af_poster_featurecreep_800__76182 1405401397 1280 1280](https://cloud.githubusercontent.com/assets/778068/7666890/0c208ac0-fbab-11e4-830b-8e4972eaeee9.jpg)

**Comment by kylewm** [comment]
OK submitted with these descriptions...fingers crossed that we get at least some progress this time.

# Notes for user_events

## Description:

Bridgy connects events posted on Facebook with the same event
posted on a user's personal site or blog. When the Facebook event
receives RSVPs, Bridgy notifies the personal site of the RSVP
too. See an example here
https://kylewm.com/2015/05/homebrew-website-club-2015-may-20

## Steps:

1. Test with a user with at least one friend.

2. Create a PUBLIC event (it must be public--Bridgy ignores all
private data), and invite at least one other user.

3. Visit https://www.brid.gy and click the Facebook button under "Get Started"

4. Accept the "user_events" permission.

5. You will be taken to the Bridgy user page for your FB account.

6. After a few minutes, refresh the page, and you should see a
list of "user_events" responses being checked (it should include
the primary user's invitation to themself and the invitation to
the 2nd user)


# Notes for user_photos

## Description:

When you post a photo to your website and share it via Facebook,
Bridgy will find likes and comments on the shared photo and send them
back to the original post.

## Steps:

1. Post a PUBLIC photo to your Facebook timeline. (Bridgy ignores all
friends-only or private posts)

2. Like or comment on the photo.

3. Visit https://www.brid.gy and click the Facebook button under "Get Started"

4. Accept the "user_photos" permission.

5. You will be taken to the Bridgy user page for your FB account.

6. After a few minutes, refresh the page, and you should see a list of
"user_photos" responses being processed and sent to their original
post. If the photo description links to a webpage, Bridgy will try to
send a webmention to that page notifying it of the new likes or
comments.

# Notes for user_status

## Description:

When you post a status update to your blog and share it via Facebook,
Bridgy will find likes and comments on the Facebook status and send them
back to the original blog post.

## Steps:

1. Post a PUBLIC status to your Facebook timeline. (Bridgy ignores all
Friends-only or private posts)

2. Like or comment on the status.

3. Visit https://www.brid.gy and click the Facebook button under "Get Started"

4. Accept the "user_status" permission.

5. You will be taken to the Bridgy user page for your FB account.

6. After a few minutes, refresh the page, and you should see a list of
"user_status" responses being processed and sent to their original
post. If the status body links to a webpage, Bridgy will try to
send a webmention to that page notifying it of the new likes or
comments.

# Notes for manage_pages

## Description

We've added support for Facebook pages for all of Bridgy's features:
notifying web pages of comments, likes, etc, to their associated
Facebook page.

## Steps

1. Login to Facebook as a user who owns at least one public Page.

2. Ensure that the page has at least one PUBLIC post with likes or
comments on it (or create a new post and "like" it)

3. Open https://www.brid.gy/ in a browser.

4. Click the Facebook button and authorize Facebook with the
`manage_posts` permission.

5. Bridgy will show a page for you to choose either the user or a
page. Choose a page.

6. You'll be taken to the Bridgy profile corresponding to that
Facebook page.

7. Refresh the page after a few minutes (it may take up to 10). You'll
see recent comments and likes of the page's wall posts. If any of them
link to web pages, Bridgy will try to send webmentions to those web
pages to notify them.

**Comment by snarfed** [comment]
woo, these look great! thank you! good call on not trying to walk them through setting up a web site that accepts webmentions; just check the user page and see that poll finds the post, event, etc. fingers crossed!

**Comment by kylewm** [comment]
Phew, all four were approved.

Fun fact: I found out because of  a [Loqi flood of notifications](http://indiewebcamp.com/irc/2015-05-20#t1432140337418) of RSVPs to NYC's HWC.

**Comment by snarfed** [comment]
woo congrats @kylewm!!! much props.
