### ISSUE TITLE
disabling Bridgy account associated with a Facebook page

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#409]
When I try to disable a Bridgy account for a Facebook Page, I get the error "Please log into Facebook as Hardly Starving to disable it here."

Bridgy account page: https://www.brid.gy/facebook/108663232553079#
Facebook page: https://www.facebook.com/pages/Hardly-Starving/108663232553079
Screenshot of the error message

![facebook-bridgy-page-disable](https://cloud.githubusercontent.com/assets/950127/7759327/51453cb8-ffc5-11e4-85f7-1549d075fa5f.png)

Amusingly, even if I AM signed in to Facebook as the Page, it makes me switch to my personal account before it tries and fails:

![youre-using-facebook-as-hardly-starving](https://cloud.githubusercontent.com/assets/950127/7759354/8ed12c22-ffc5-11e4-9615-b61f222d7098.png)

We should probably allow the owner of a page to disable its Bridgy acc't

**Comment by snarfed** [comment]
oh wow, great find! (also i have no idea what's up here. :P)

**Comment by snarfed** [comment]
...except the usual facebook :facepunch: :gun:

**Comment by kylewm** [comment]
fixed in 7fcaa48

**Comment by snarfed** [comment]
yay, thanks! lgtm. only one "now" bug left, #378, and it's largely out of our hands. i may need to find a new hobby. :P
