### ISSUE TITLE
support facebook pages as accounts

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#41]
requested by rim_light: https://twitter.com/rim_light/status/425595328520544256

**Comment by snarfed** [comment]
requested by @alohastone: https://twitter.com/alohastone/status/555375247990718464

maybe we should finally prioritize this. :P

**Comment by alohastone** [comment]
Thank you for replying and adding my request.

The thing is, when it comes to blogpostings, I generally only share them on my FB page, not my personal profile. Which is why It'd be cool to poll the comments & likes from there. Keep up the great work! :+1:

**Comment by tantek** [comment]
+1 to request, real world example: http://tantek.com/2015/020/f1 thanks for your consideration! -t

**Comment by snarfed** [comment]
@tantek oh interesting. this issue is actually about creating bridgy accounts for an FB pages, ie backfeeding to them and publishing as them, not about liking pages. i'll file another issue for liking.

**Comment by snarfed** [comment]
the [`manage_pages`](https://developers.facebook.com/docs/facebook-login/permissions/v2.2#reference-manage_pages) permission might work. we might need to show a page to choose which FB page to sign up (or your own user account), though.

**Comment by snarfed** [comment]
also, with that permission, we might be able to use `/{pageId}?fields=access_token` to get a long lived token that may last longer than 2 months (maybe forever).

**Comment by snarfed** [comment]
we'd call [`/user/accounts`](https://developers.facebook.com/docs/graph-api/reference/v2.2/user/accounts) to get the list of pages that the current user administers.

**Comment by snarfed** [comment]
@TechLifeWeb @alohastone i've pushed this live. feel free to try it out!

**Comment by snarfed** [comment]
... actually, scratch that, I need to get facebook's approval for the pages permission first. I'll ping you again once that's done.

**Comment by snarfed** [comment]
ok, i've submitted to facebook for review. fingers crossed. :cop:

**Comment by alohastone** [comment]
I just signed up my facebook page with brid.gy, and can confirm that it's working. As for the publishing feature, I haven't tried that out yet. But the likes and comments are coming in, and I now need to figure out a way to separate the likes and favourites from the comments. Have them displayed as a facepile or something, so they don't mess up the comments section too much.

Thank you so much for your awesome support and pushing this live this quickly. Kudos to you, Ryan ;)

**Comment by snarfed** [comment]
yay, glad to hear it's working. thanks for the kind words.

also...huh. odd. facebook actually hasn't approve us for the `manage_pages` permission yet, which should be necessary, so I have no idea how this worked for you. the plot thickens!

**Comment by snarfed** [comment]
aha, right, @alohastone originally signed up for bridgy before we migrated to the v2.2 api (#339), so he was grandfathered in for `manage_pages`. mystery solved.

**Comment by MatthieuScarset** [comment]
Hi. I have the same issue and I'd like to know if it is possible to link my account to a Facebook Page ?
I'm using Known CMS and I'd love to use brid.gy but I need to connect to a FB Page, not to my profile.

I've already tried to use a private browser with nothing related to Facebook, unfortunately with no luck.

Any of my pages are listed in Brid.gy connection screen.

**Comment by kylewm** [comment]
Hi @MatthieuScarset, all the Bridgy code is implemented to support Facebook Pages; we are in the process of applying for the `manage_pages` permission scope that we lost in the recent facebook API changes. When and if that is approved, it should start working again. You may want to keep an eye on #407 :)

**Comment by kylewm** [comment]
@MatthieuScarset mind giving it another shot?

**Comment by MatthieuScarset** [comment]
Hi @kylewm and thank you for your answer. 
It is not working yet... I have no pages listed in the connection screen.
I'm watching the #407 and hope that Bridy will support Facebook pages again soon.

**Comment by snarfed** [comment]
thanks @MatthieuScarset, that's great news! glad to hear it. i see your page: https://www.brid.gy/facebook/355488674490022 . tentatively closing.
