### ISSUE TITLE
facebook publish: support posting links

### ISSUE THREAD

**Issue by jeena** [snarfed/bridgy#411]
The Facebook API allows to post links. If there is a link in the content then the first link could be used for that. Facebook shows a small preview of the link inline which is nice.

**Comment by snarfed** [comment]
interesting idea! lots of posts have links that may not be intended as the "featured" link, so we might only want to do this based on some markup, eg `u-featured`, but otherwise sounds good! i think we'd gladly merge a PR for this.

**Comment by kylewm** [comment]
I like this idea although I think we'd need to brainstorm with microformats people what a good propetly name would be. `u-featured` has been "claimed" specifically for images https://indiewebcamp.com/link-preview#u-featured

**Comment by diplix** [comment]
i have a feeling that bridgy misses the responses to posts with links. so this mystery should be solved first: #415

**Comment by snarfed** [comment]
duped by #474.
