### ISSUE TITLE
Lanyrd publish RSVP support

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#412]
Lanyrd has a pretty good API, and many (most?) major events/conferences are on it, so it would be a natural place to Indie RSVP to.

Would be nice to be able to automatically create a Lanyrd POSSE copy RSVP from an Indie RSVP post that was in-reply-to a Lanyrd event.

Specifically:
RSVP yes = Lanyrd attending
RSVP no = Lanyrd stop attending
RSVP interested = Lanyrd tracking

See also related: issue #390, issue #391.

**Comment by tantek** [comment]
Here is a real world example of an indie RSVP:
http://tantek.com/2015/149/t1/yxyy003-thoughtful-independent-creatives-yxyy
to a Lanyrd event:
http://lanyrd.com/2015/yxyy/

**Comment by snarfed** [comment]
if anyone's interested in tackling this, i've written up [comprehensive instructions on how to add a new silo to bridgy.](https://github.com/snarfed/bridgy#adding-a-new-silo) feel free to jump in!

**Comment by snarfed** [comment]
[lanyrd seems to be dead.](https://en.wikipedia.org/wiki/Lanyrd#cite_ref-14) closing. 😢
