### ISSUE TITLE
backfeeding not working properly (may-be mf2/Parser related)

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#413]
this is probably a site specific bug (for wirres.net). 
wirres.net serves iso-8859-1 which seems (for example) to cause problems with the mf2-parser at quill.p3k.io. when quill tries to fetch my rel=me info, it throws this error:

    Message: mb_convert_encoding(): Illegal character encoding specified
    File: /web/sites/quill.p3k.io/vendor/mf2/mf2/mf2/Parser.php

since i provide a u-syndication backlink to instagram with all my posted instagrams (i.e.: http://wirres.net/article/articleview/7716/1/53/ — no laughing!) i suspect bridgy to stumble when parsing my h-feed for syndication links, just as quill does. 

anyhow: i always need to post a backlink to my blog to my , to help bridgy find the post on my site. could it be possible to find out more in the logs?

**Comment by snarfed** [comment]
hey felix, thanks for the report, and sorry for the trouble! i don't know what's wrong yet, but here are a few notes.

looks like we are fetching your home page, finding post permalinks, and parsing them for u-syndication links ok. here's the last log of that: https://www.brid.gy/log?start_time=1433074325&key=aglzfmJyaWQtZ3lyFQsSCUluc3RhZ3JhbSIGZGlwbGl4DA

that log says the last time we found an Instagram u-syndication link for you was 4/21, ie 5w ago.

we are currently finding your Facebook u-syndication links ok though. here's the last log of that: https://www.brid.gy/log?start_time=1433078640&key=aglzfmJyaWQtZ3lyGwsSDEZhY2Vib29rUGFnZSIJNTQ4NjE2Nzg0DA

**Comment by snarfed** [comment]
looks like mf2py, the mf2 parser bridgy uses, sees your u-syndication links fine:
https://kylewm.com/services/mf2?url=http%3A%2F%2Fwirres.net%2Farticle%2Farticleview%2F7716%2F1%2F53
https://kylewm.com/services/mf2?url=http%3A%2F%2Fwirres.net%2Farticle%2Farticleview%2F7719%2F1%2F6%2F

**Comment by snarfed** [comment]
looking at the parsed output for your home page: https://kylewm.com/services/mf2?url=http%3A%2F%2Fwirres.net%2F

it doesn't have a permalink (u-url) for the example post you mentioned (search for "chilli"), but it does see syndication links to both twitter and instagram.

**Comment by diplix** [comment]
oh. my bad. did catch my mistake, because post with a titel do have a u-url permalink. now also posts without a title have a permalink. i assume everythink will be fine now and close the issue.
sorry for making you bugtracking for my mistakes and thanks a lot …

**Comment by snarfed** [comment]
@kylewm can confirm, but @diplix i think that's the problem. on your homepage, some of your posts (like this one) don't have the u-url mf2 property, so we don't know their permalink, so we don't know where to send webmentions for them.

**Comment by snarfed** [comment]
oops, you got there before i did. no worries. thanks for using bridgy!

**Comment by diplix** [comment]
it’s working now. thanks a lot again.
