### ISSUE TITLE
not sending FB responses for some posts

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#415]
this post: http://gregorlove.com/2015/05/1196/

we're sending twitter responses to it fine, just not FB. [here's the FB post](https://www.facebook.com/gregorlove/posts/10101679559980404); it has the post link in both the text and attached as a link. the post is type `link`.

[searching the logs for the FB post id](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=text:10101679559980404) (10101679559980404) doesn't turn up anything.
[searching for the original post URL](https://console.developers.google.com/project/brid-gy/logs?service=appengine.googleapis.com&key1=default&key2=3&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=America%2FLos_Angeles&filters=text:gregorlove.com%2F2015%2F05%2F1196%2F) has lots of noise, but no obvious cause.

(cc @gRegorLove)

**Comment by snarfed** [comment]
looking in the FB explorer with his current access token, [`/me/posts`](https://developers.facebook.com/tools/explorer?method=GET&path=me%2Fposts&) finds that post fine. the token was issued at 1433178977 (18 minutes ago) and has scopes user_website, user_events, user_photos, user_friends, user_status, user_posts, rsvp_event, publish_actions, public_profile.

**Comment by gRegorLove** [comment]
Another one. https://www.facebook.com/gregorlove/posts/10101699400764314 

Why doesn't Bridgy loooove me? ;)

**Comment by snarfed** [comment]
ugh, sorry. i think it's actually happened to me recently too. :/

i poked around a bit, but haven't seen anything obvious in any of the cases yet. my best guess right now is Facebook API being charming, as usual.

**Comment by snarfed** [comment]
collecting examples here... mine is https://snarfed.org/2015-06-04_what-doesnt-kill-my-baby . has both u-syndication and a backlink in the fb post, but no luck.

**Comment by diplix** [comment]
same with me. it mostly (only?) happens with facebook link posts (posts that show a thumbnail and description of the link). deactivating the preview (before manually posting) seems to help  bridgy to allocate the responses. fresh example from my stream:
https://www.facebook.com/548616784/posts/10153082207936785

bridgy finds the responses,
https://brid-gy.appspot.com/post/facebook/548616784/548616784_10153082207936785

but not the link to wirres.net. (http://wirres.net/7875) syndication backlink and my h-entry markup seem to be fine. 

the facebook api response seems to be fine:
https://developers.facebook.com/tools/explorer?method=GET&path=548616784_10153082207936785

**Comment by snarfed** [comment]
great sleuthing @diplix! i agree, seems like the attached links are the most likely cause. Facebook is probably handling them differently somehow.

**Comment by gRegorLove** [comment]
I'll try leaving the link in the text body next time and see what happens.

**Comment by gRegorLove** [comment]
Confirmed:

- It does work if you choose to remove the link preview when you initially post the status. https://www.facebook.com/gregorlove/posts/10101708133598644 is backfeeding now.

- It appears FB no longer lets the link appear in both the status body and in the attached link preview. I tried editing an existing status multiple times to put the link in the status body, but it always removed it when I saved. Same when creating a new status. Removing the link preview when initially posting (above example) keeps the link in the status body and backfeed works.

**Comment by diplix** [comment]
parsing attached links for backfeeding should actually be easier than parsing the message body for links? (i’d make a pull request, if i knew anything of programing)

**Comment by snarfed** [comment]
thanks for the sleuthing, guys!

bridgy has definitely handled backlinks in both attachments and post text for a long time. my own site's example for this bug also had a `u-syndication` link, so it should have worked without either.

i expect something changed with the FB API, either the data itself or permissions or our handling of it, that breaks support for posts with link attachments. ...which is also why i've been procrastinating working on this. :/

**Comment by snarfed** [comment]
gotcha! looks like link posts now have `status_type : shared_story`. not sure when that happened. maybe a 2.x API thing. from [this code comment](https://github.com/snarfed/granary/blob/ec906b800a8facaac60c7b0f73b681101955b8bb/granary/facebook.py#L230):

> we "filter out `shared_story` because they tend to be very tangential - friends' likes, related posts, etc.

looks like that was added in 9b65d08a9593ee604426419efdfbfeed461b4021.

**Comment by snarfed** [comment]
sigh. i wish that change had more context!

here's what i'm thinking: only filter out `shared_story`s when the author isn't the current user. and/or `type` isn't `link`. meh, i dunno yet.

**Comment by snarfed** [comment]
i want to just check for author == current user and make an exception then, but we often don't know the current user's id (or username or whatever), just their access token, so we'd need to make another API call to get that, which i'm not quite ready to incur.

i'm now leaning toward filtering out `shared_story` only when we're fetching activities from multiple people, ie `user_id` and `activity_id` are unset and `group_id` is not `SELF`.

**Comment by snarfed** [comment]
done! @gRegorLove @diplix, looks like your missing responses are trickling in. the dates for likes will incorrectly default to today since facebook doesn't expose the real dates; sorry about that.

**Comment by diplix** [comment]
great. good work!

**Comment by armingrewe** [comment]
Fantastic, just approved 120+ missing FB likes/comments for my blog! I had pretty much given up on Facebook, but you guys have managed to bring them back in again. Thank you!

**Comment by snarfed** [comment]
@armingrewe you're welcome!
