### ISSUE TITLE
webmention endpoint cache does not seem to timeout

### ISSUE THREAD

**Issue by leitmedium** [snarfed/bridgy#417]
Hey,

two days ago I setup webmention in my blog and an account in the official brid.gy instance. As webmentioning did not work before setting up the account, brid.gy cached the state and refuses to send updates. 

According to https://github.com/snarfed/bridgy/blob/ef748e7bda9a4d272f28d5f707efa9adfeb1d9c9/tasks.py#L37

the cache should invalidate after 24h. As webmentioning via curl and webmention-tools work, I assume the cache is not purged after 24hours?

As an example this event should have worked:

https://www.brid.gy/log?start_time=1434099799&key=aglzfmJyaWQtZ3lyTAsSCFJlc3BvbnNlIj50YWc6dHdpdHRlci5jb20sMjAxMzo2MDkyODI0Mzk2NTE5NzkyNjRfZmF2b3JpdGVkX2J5XzI1Njc1NDIxMgw

Best.

**Comment by snarfed** [comment]
thanks for the report, and sorry for the trouble! i think i might see the bug. more in a while.

**Comment by snarfed** [comment]
in the meantime, i've cleared your site from the cache, so it should work for you now.
