### ISSUE TITLE
PPD: crawl all rel=feed links, not just the first

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#423]
this has a been a known, low priority limitation for a while. @kartikprabhu [hit it recently](http://indiewebcamp.com/irc/2015-07-14#t1436887460416).

@kylewm, do you remember if there was a reason we did this, other than just load?

**Comment by kylewm** [comment]
no particular reason, not even load really, I think I just didn't anticipate multiple feeds. I can work on adding support for this.

**Comment by snarfed** [comment]
woo thank you!
