### ISSUE TITLE
Facebook backfeed for likes on a photo using wrong FB URL

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#424]
@dissolve reported via IRC that his post is not receiving backfeed likes https://ben.thatmustbe.me/photo/2015/7/17/1/

Bridgy sees the likes and tries to send them https://www.brid.gy/facebook/14305603

![screenshot from 2015-07-17 07 24 07](https://cloud.githubusercontent.com/assets/950127/8749208/e8b0ff0e-2c54-11e5-850c-19a6e756ce74.png)

but it seems to be using the wrong Facebook post ID ... https://www.facebook.com/14305603/posts/10101541550801774 ... which is the "Ben Roberts added 2 new photos to the album: Brid.gy Photos." activitystreams-style activity post, and not the photo itself.

as a result the source URLs bridgy sends to Ben 404 https://brid-gy.appspot.com/like/facebook/14305603/10101541550801774/727349030638052

**Comment by snarfed** [comment]
aughhh no not fb photo URLs again :sob: :gun: :gun: :gun:

**Comment by snarfed** [comment]
(but thank you for filing so comprehensively @kylewm!)

**Comment by snarfed** [comment]
related to #388 and #346. FB ids are no end of fun/headache.

**Comment by snarfed** [comment]
the tentative fix is to fetch *both* forms of the id and merge the results.

**Comment by snarfed** [comment]
seems to work. https://brid-gy.appspot.com/like/facebook/14305603/10101541550801774/727349030638052 now 200s.

**Comment by diplix** [comment]
great job!
