### ISSUE TITLE
Deployment virtualenv-related outage post-mortem

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#427]
We had about a 20 minute outage today when I deployed with a bad virtualenv. I think I better understand how GAE vendoring works now, so this won't happen in the future.

All local tests passed, but when deployed, every request got a "could not import module webmentiontools" error. (webmention tools was installed in editable mode)

I guess that GAE's vendoring code doesn't see packages installed in editable mode (i.e. to local/src instead of local/lib/python2.7/site-packages). The README suggests symlinking the project to local/lib but I kinda feel like this makes it easy to get in a situation where you don't know exactly what version of the library is being referenced (pypi vs. github vs. local). if e.g. you

 pip install granary

then

 pip install -e git+https://github.com/snarfed/granary#egg=granary

I believe you will have the pypi version in lib and the git version in src, so locally the git version takes precedence, but once deployed only the pypi version is visible. What I ended up doing was installing all three libraries (oauth-dropins, granary, and webmention-tools) from github without the "-e" switch, and that worked.

There's also a small issue that if oauth_dropins.webutil tests run before oauth_dropins tests, webutil can't import mox

**Comment by snarfed** [comment]
thanks for the comprehensive writeup! yeah, i think that's right, pip lets you install the same package all three ways, which can lead to this problem.

my goal is for us to be able to install granary in source mode, and the same for oauth-dropins inside granary, so we can have one local repo for each that's reused across them all. `pip install -e [path]` plus symlinks worked for me, but i'm open to a more robust way!

re the webutil tests, huh, interesting. are you using nose, and it runs them in a different order than python's unittest?

also, when i run the webutil tests from Its repo alone, with `PYTHONPATH=/usr/local/google_appengine`, they find mox ok, but `test_handlers` fails with `ImportError: No module named oauth_dropins.test`, which it shouldn't. i'll fix that.

**Comment by snarfed** [comment]
(more ongoing discussion in de2a7a2a022e7e7a3a6d3c9c9a429ad84265538e...)

**Comment by kylewm** [comment]
nope, not using nose, just -m unittest discover

```
(local)kmahan@lemur:~/projects/bridgy$ cd ../oauth-dropins && source local/bin/activate && python -m unittest discover && \
>   cd ../granary && source local/bin/activate && python -m unittest discover && \
>   cd ../bridgy && source local/bin/activate && python -m unittest discover && \
>   ./facebook_test_live.py && git push && ~/google_appengine/appcfg.py update .
EE............
======================================================================
ERROR: oauth_dropins.webutil.testutil (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: oauth_dropins.webutil.testutil
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/kmahan/projects/oauth-dropins/oauth_dropins/webutil/testutil.py", line 9, in <module>
    import mox
ImportError: No module named mox


======================================================================
ERROR: oauth_dropins.webutil.test.test_util (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: oauth_dropins.webutil.test.test_util
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/kmahan/projects/oauth-dropins/oauth_dropins/webutil/test/test_util.py", line 17, in <module>
    import webapp2
ImportError: No module named webapp2


----------------------------------------------------------------------
Ran 14 tests in 0.027s

FAILED (errors=2)
```

**Comment by kylewm** [comment]
I think this is a good order-of-operations for getting the right versions of everything in the right places for development and deployment.

```
kmahan@lemur:~/projects/bridgy$ virtualenv local
(local)kmahan@lemur:~/projects/bridgy$ source local/bin/activate
(local)kmahan@lemur:~/projects/bridgy$ pip install -e ../webmention-tools/
(local)kmahan@lemur:~/projects/bridgy$ pip install -e ../oauth-dropins/
(local)kmahan@lemur:~/projects/bridgy$ pip install -e ../granary/
(local)kmahan@lemur:~/projects/bridgy$ pip install -r requirements.txt 
(local)kmahan@lemur:~/projects/bridgy$ cd local/lib/python2.7/site-packages/
(local)kmahan@lemur:~/projects/bridgy/local/lib/python2.7/site-packages$ ln -s ~/projects/webmention-tools/webmentiontools
(local)kmahan@lemur:~/projects/bridgy/local/lib/python2.7/site-packages$ ln -s ~/projects/oauth-dropins/oauth_dropins
(local)kmahan@lemur:~/projects/bridgy/local/lib/python2.7/site-packages$ ln -s ~/projects/granary/granary
```

**Comment by snarfed** [comment]
agreed, lgtm! I'd like something more robust that doesn't depend on order of operations, but if we can't get there with pip's current features and behavior, I'd be fine with updating the README with this.

incidentally, I'm sure we're not the only open source app engine app that uses virtualenv and multiple repos. i wonder what others do. i bet e.g. khan academy has figured this out.

**Comment by kylewm** [comment]
We need to do something about webmentiontools too. Right now it's not visible to GAE because we're installing it in source mode. 
```
-e git+git@github.com:snarfed/webmention-tools.git#egg=webmentiontools
```

I'm currently symlinking it the same way as the other two, which seems fine.

**Comment by snarfed** [comment]
true, thanks for the nudge! done.

btw, i fixed the webutil test failure, but not the other order-of-import one, and i don't see it anymore, at least when i run `discover`with no args. if you still see it, mind taking a look?

**Comment by kylewm** [comment]
:+1:
