### ISSUE TITLE
favourites and +1's are "mentioned on" ?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#428]
I thought it used to say "favourited", but now when someone favourites a tweet it just says "mentioned on twitter.com" and links to my own tweet, which is confusing

**Comment by kylewm** [comment]
Bridgy sends the 'like' with u-like-of pointing to its best guess as to the original post urls:

https://brid-gy.appspot.com/like/twitter/singpolyma/621653023346032640/45489796

which is parsed to 

http://pin13.net/mf2/?url=https%3A%2F%2Fbrid-gy.appspot.com%2Flike%2Ftwitter%2Fsingpolyma%2F621653023346032640%2F45489796

It's up to your webmention receiver to interpret that as a reply/like/etc. and usually falls back to just "a mention" if none of the above is recognized.

**Comment by singpolyma** [comment]
Hmm, I thought it used to include more helpful text, but maybe not.

**Comment by kylewm** [comment]
What software are you using to receive/interpret the webmentions? It looks like maybe wordpress?

**Comment by singpolyma** [comment]
Yeah, with the webmention plugin.

**Comment by snarfed** [comment]
do you have http://wordpress.org/plugins/semantic-linkbacks too? a recent version? that's the one that understands reply types.

**Comment by armingrewe** [comment]
I use those and they work perfectly fine (except for that I have to approve every single one of them, haven't found a way yet to "auto-approve" known likers/retweeters etc)

**Comment by snarfed** [comment]
@armingrewe here's the PHP snippet i use to auto-approve bridgy responses. @pfefferle @acegiak might be worth adding to one of the plugins?

```php
function unspam_webmentions($approved, $commentdata) {
  return $commentdata['comment_type'] == 'webmention' ? 1 : $approved;
}
add_filter('pre_comment_approved', 'unspam_webmentions', '99', 2);
```

**Comment by singpolyma** [comment]
@snarfed I have added that plugin, we'll see how it goes :)

**Comment by snarfed** [comment]
fingers crossed! closing...

**Comment by dshanske** [comment]
@singpolyma You appear to be running WordPress 3.6.1. Semantic Linkbacks uses features implemented in later versions. Could be part of the issue.  Also a security risk.

**Comment by dshanske** [comment]
@snarfed That auto-approves all webmentions. I have an alternate solution that whitelists domains.

**Comment by singpolyma** [comment]
Working well with the plugin installed :)  I'm not running an unpatched 3.6.1, but rather the version for debian stable

**Comment by dshanske** [comment]
Semantic Linkbacks works using a bit of code that was not working prior to 4.2. There was a bug and the author used a low-level fix that was subsequently removed when the bug was fixed.
