### ISSUE TITLE
backfeed facebook notes (not currently available in FB API)

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#429]
just a quick note, not an issue: it took me a while to find this out, but you can post ”notes“ on facebook, that allow basic formating, post-images and even html-links. example:
https://www.facebook.com/notes/felix-schwenzel/nachhaltigkeit/10153150034826785

post discovery doesn’t honor notes however, even if there is a plain text link to the blogpost in it or if you put a syndication-backlink on your blogpost.

what works however is this url structure:
https://www.facebook.com/548616784/posts/10153150034826785

if you set a syndication link to this url, bridgy’s backfeed discovery gets the note — or rather the post that anounces the note. the note above got one comment and one like, which are attached to both, the post and the note — and bridgy sends a mention accordingly:
http://wirres.net/article/articleview/8177/1/6/#trackback

**Comment by snarfed** [comment]
thanks for the thorough investigation! sadly, it looks like [facebook dropped notes from the API altogether in API v2.0.](https://developers.facebook.com/docs/apps/changelog#v2_0_graph_api) (search for _/me/notes_). they always kind of treated notes as a second class citizen anyway, as you mentioned: they're hard to find, and they never got much prominence in the news feed.

`/me/posts` returns a story when you create a note:

```json
{
  "story": "Felix Schwenzel wrote a new note: Nachhaltigkeit?",
  "created_time": "2015-07-20T07:02:31+0000",
  "id": "548616784_10153150034826785"
}
```

...but you can't get te actual contents of the note. `/548616784_10153150034826785` returns that same JSON object, `/548616784/posts/10153150034826785` returns a generic error, and most notably, `/10153150034826785` says:
```json
"error": {
  "message": "(#12) notes API is deprecated for versions v2.0 and higher",
  "type": "OAuthException",
  "code": 12
}
```

i'll add this to the bridgy docs, and i'll leave this issue open for tracking in case FB ever adds notes back to the API

**Comment by snarfed** [comment]
looks like we already are backfeeding comments and likes on notes ok, as felix mentioned originally. details at the bottom of #480.

so, the remaining part here is to handle FB `/notes/...` syndication urls. should be straightforward.
