### ISSUE TITLE
drop u-like from mf2, use only u-like-of

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#430]
Trying to publish https://kylewm.com/2015/07/demoing-aaron-demoing-swat0 to Twitter

I get the error "Could not find a tweet to favorite. Check that your post has a like-of link to a Twitter URL or to an original post that publishes a rel-syndication link to Twitter."

I suspect this means it sees the likes at that the bottom and interprets them to mean the post itself is a **like**

A bit tricky because Bridgy tends to support u-like as a synonym of u-like-of for backward compatibility, but I think we need to drop it now that people are using u-like to mark up received likes (like in a facepile). 

Actually it's probably time to drop it from Bridgy's mf2 output too, since salmentions might interpret them as "like of a like"

**Comment by snarfed** [comment]
all of that logic sgtm. go for it!

**Comment by snarfed** [comment]
this fixes publish, but doesn't remove `u-like` from mf2 output. i worry that some users out there have old mf2 parsers that may not know `u-like-of` yet. i don't have a good feeling for how to weigh breaking that backward compatibility vs possibly breaking salmentions. feedback is welcome!

**Comment by kylewm** [comment]
I'm with you. Let's wait until it actually breaks something ;)

**Comment by tantek** [comment]
Now that it's breaking salmentions per #640 let's do this.
