### ISSUE TITLE
facebook: /me/posts consistently 400s for some users

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#431]
for a while now, we've seen a tiny trickle of FB users start permanently seeing 400s from the `/me/posts` API call, which obviously breaks poll. no details in the error response. :/

this has been happening a bit more recently. example log:

```
Params: UnicodeMultiDict([(u'last_polled', u'2015-07-20-17-09-02'), (u'source_key', u'aglzfmJyaWQtZ3lyGwsSDEZhY2Vib29rUGFnZSIJNTE0MTcwODc5DA')])
Source: ... (Facebook) 514170879, http://brid-gy.appspot.com/facebook/514170879
Last poll: http://brid-gy.appspot.com/log?start_time=1437476290&key=aglzfmJyaWQtZ3lyGwsSDEZhY2Vib29rUGFnZSIJNTE0MTcwODc5DA
Using ETag "96b6ad2b4d329b2c662768e16f716dfa0b7fa997", last activity id 10152893592180880
Fetching https://graph.facebook.com/v2.2/me/posts?offset=0&limit=50&access_token=CAAD..., kwargs {'headers': {'If-None-Match': u'"96b6ad2b4d329b2c662768e16f716dfa0b7fa997"'}}
Error 400, response body: Bad Request
HTTP Error 400: Bad Request
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/tasks.py", line 109, in post
    source_updates.update(self.poll(source))
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/tasks.py", line 161, in poll
    cache=cache)
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/facebook.py", line 104, in get_activities_response
    resp = self.gr_source.get_activities_response(group_id=SELF, **kwargs)
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/local/lib/python2.7/site-packages/granary/facebook.py", line 214, in get_activities_response
    resp = self.urlopen(url, headers=headers, parse_response=False)
  File "/base/data/home/apps/s~brid-gy/3.385840981807235338/local/lib/python2.7/site-packages/granary/facebook.py", line 1213, in urlopen
    timeout=appengine_config.HTTP_TIMEOUT)
...
HTTPError: HTTP Error 400: Bad Request
```

here's an incomplete list of user ids who have hit it recently:

* [10153013291712807](https://www.brid.gy/facebook/10153013291712807)
* [10153551234732738](https://www.brid.gy/facebook/10153551234732738)
* [10205489002117460](https://www.brid.gy/facebook/10205489002117460)
* [10205983537418744](https://www.brid.gy/facebook/10205983537418744)
* [13731464](https://www.brid.gy/facebook/13731464)
* [13731464](https://www.brid.gy/facebook/13731464)
* [1659137334316731](https://www.brid.gy/facebook/1659137334316731)
* [550539683](https://www.brid.gy/facebook/550539683)
* [596817951](https://www.brid.gy/facebook/596817951)
* [765235586](https://www.brid.gy/facebook/765235586)
* [897547826964187](https://www.brid.gy/facebook/897547826964187)
* [514170879](https://www.brid.gy/facebook/514170879)

[1659137334316731](https://www.brid.gy/facebook/1659137334316731) is notable, he's been slamming the "poll now" button for days now, hoping it will fix this. :/

**Comment by snarfed** [comment]
(mumble mumble facebook mumble :sob: :gun: :gun: :gun:)

**Comment by tzpazifist** [comment]
The slammer writing. ;)
I've tried that re-authenticating from different workstations, cache clearings, new installations - nothings worked so far.
The error is 

{
   "error": {
      "message": "An active access token must be used to query information about the current user.",
      "type": "OAuthException",
      "code": 2500
   }
}

Although I reconnected to FB from the different varieties of setups, nothing worked so far. So what's that 'active access token' all about? Isn't it active as long as I'm (newly) logged in to FB?

**Comment by tzpazifist** [comment]
The only thing I've found is that some init stuff is working asynchronously, which is why other 3rd party apps have similar probs. (https://stackoverflow.com/questions/15812050/facebook-javascript-sdk-an-active-access-token-must-be-used-to-query-information/21977100#21977100)
I'm no developer, so some capable minds are appreciated. ;)

**Comment by snarfed** [comment]
thanks for the info @tzpazifist! and sorry for the name calling, the slamming was actuallya a misconfiguration on it did, not you at all.

honestly i don't know what's going on here yet, especially since it's only affected a few users so far. :/

**Comment by tzpazifist** [comment]
It's not the name calling but the error message that annoyed me. ;)
As your error stack didn't reflect the nested message I got, I thought I might as least add the info I was crawling through.
Anyway, I can't estimate the numbers as I'm not into the user counts for brid.gy... so: I'm here for whoever wants me to test anything.

**Comment by snarfed** [comment]
@tzpazifist have you tried revoking (ie removing) bridgy in your Facebook account settings, under "apps"? I'm curious if that might help.

**Comment by tzpazifist** [comment]
Tried.
Nope.

**Comment by snarfed** [comment]
thanks for trying.

more data: here's the error message. i checked with a few of the other affected users, and they get the same message.

```
{"error":{"message":"(#100) Tried accessing nonexisting field (name) on node type (OpenGraphObject)","type":"OAuthException","code":100}}
```

 i didn't look for it before because bridgy tries pretty hard to always log the full response body for requests that error, but evidently it doesn't catch this one. i'll fix that.

**Comment by snarfed** [comment]
looks like this may be a bug on facebook's end. they're tracking it in https://developers.facebook.com/bugs/1605000643111156/

**Comment by tzpazifist** [comment]
Although the bug isn't yet marked as solved at FB there's some data trickling through - still failing at some posts containing a concrete URL in post text though.
Info: I didn't do, try or change anything on my side.

**Comment by snarfed** [comment]
thanks @tzpazifist! we stopped seeing the error around 4pm PST yesterday. looks like FB may have fixed their bug. fingers crossed!

**Comment by snarfed** [comment]
woo, FB agreed. closing...
