### ISSUE TITLE
FB event API endpoints disappearing in july 2017

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#433]
[the FB v2.4 API is deprecating `/[event]/invited`](https://developers.facebook.com/docs/apps/changelog#v2_4_deprecations), [which we use to get event invitees and RSVPs](https://github.com/snarfed/bridgy/blob/a96de232cd186a56c68d43edc9d35c74055adbc8/facebook.py#L136), and removing it on 2017-07-08. we'll need to either figure out an alternative before then or sunset backfeed of invites and rsvps. :(

scary, but not exactly urgent. :P good self-contained project for someone interested in digging into the API!

**Comment by aaronpk** [comment]
It makes me happy that there is an issue created for this even though the target date is 2 years from now.

**Comment by snarfed** [comment]
i'm thinking i'll look into this when FB announces API v2.6, since that will hopefully also have reactions (#626).

**Comment by snarfed** [comment]
woo, good news! looks like these edges weren't removed after all, just renamed. they're now `attending`, `maybe`, `interested`, `declined`, and `noreply`. easy fix, hopefully.

https://developers.facebook.com/docs/graph-api/reference/event
