### ISSUE TITLE
make unit tests ignore .pth files

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#443]
this would check that the local client's virtualenv symlinks are in a good state (for app engine) before deploying. props to @kylewm for the idea!

**Comment by kylewm** [comment]
Interesting, according to https://github.com/pypa/pip/issues/435#issuecomment-3566380 the .egg-link files are just markers. It's actually the `local/lib/python2.7/site-packages/easy-install.pth` that modifies the python path, and that's the thing we need to ignore.

**Comment by snarfed** [comment]
pretty sure this is obsolete now after the python 3 migration. closing.
