### ISSUE TITLE
Use correct URI for a Google+ Plus comment or reply

### ISSUE THREAD

**Issue by csarven** [snarfed/bridgy#444]
It appears to be that bridgy is using the URI of the original post for the Google+ comments/replies URIs e.g:

https://brid-gy.appspot.com/comment/googleplus/114223893421375686319/z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k/z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k.1374504298928262

is referring to https://plus.google.com/114223893421375686319/posts/WRUEiHYYkM1 and probably should be https://plus.google.com/114223893421375686319/posts/WRUEiHYYkM1#z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k%231374504298928262 (note that gives us a double # since the id in source contains `#`, so, using %23 for the second)

Note that the URI with the fragment precisely refers to the comment/reply.

Bridgy already has that fragment value since it is part of its URI (after the slash) i.e., https://brid-gy.appspot.com/comment/googleplus/114223893421375686319/z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k/z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k.1374504298928262

**Comment by kylewm** [comment]
That permalink doesn't actually work for me, should it be (s/\./#/) https://plus.google.com/114223893421375686319/posts/WRUEiHYYkM1#z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k#1374504298928262

**Comment by kylewm** [comment]
The comment ID seems to actually be (s/\./#/) right? z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k#1374504298928262

**Comment by csarven** [comment]
You are right. Copy/paste error. Updated the issue to reflect that. As awkward it may seem, note the double #. Arguably, the second # probably should be encoded to: %23. I'm open to interpretation and usage on that.

**Comment by snarfed** [comment]
G+ comments have real permalinks now?! awesome! they didn't, notoriously, for a long time, so we faked them as you saw, in #215. we can definitely update them to the real permalinks now.

**Comment by csarven** [comment]
Entries contain `@id`s, in which they can be used for the entry's URI. However, the entry itself doesn't come with a URI/permalink, i.e., there is no `<a>` in the entry. That's fine.

**Comment by snarfed** [comment]
@csarven done! bad news though, i forgot one detail about this that i discovered a while back in snarfed/granary@b6bfed03978c25ffda0324835088398f64b95f29: G+'s JS catches and strips fragments with redirects. e.g. if you open https://plus.google.com/114223893421375686319/posts/WRUEiHYYkM1#z12ifhzqjt2bfpwxj04ci3zxzrnsg1bjqok0k%231374504298928262 in a new tab/window, it will redirect you to the same URL without the fragment.

silly. sad. bridgy is now at least rendering the right comment u-url, even if it won't change anyone's UX. ah well. thanks for the report!

**Comment by csarven** [comment]
Hey, awesome! Thanks for getting this going. Check this out:

http://csarven.ca/linked-statistical-data-analysis#i-20130722144458

(I re-verified)

That (and all others) now point at the actual comment/reply.

(I have to run now, but I'll take a look at the 'likes' later.. maybe it is a similar. I might have to link to the Google+ article instead of the bridgy URL [for the like]. I realize that there is no URL for the like. Same as Twitter's...)

**Comment by csarven** [comment]
re: the redirect, yes, I've noticed that too. I've also noted that if you enter the full URL again into the address bar, it doesn't get stripped.

**Comment by snarfed** [comment]
yup. i think that's general browser behavior, not G+ specific: when you add/change a fragment for the page you're currently on, browser(s) just scroll to that element and don't reload the page, fire `window.onload()`, etc.
