### ISSUE TITLE
facebook no longer gives us usernames, which breaks OPD

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#447]
...at least for syndication links with usernames, e.g. https://www.facebook.com/snarfed.org/posts/10100929680893833 , which may be the majority. similar/related to #375 and #350.

here's an example user object that FB currently gives us with the v2.2 API:

```json
{
   "name" : "Ryan Barrett",
   "gender" : "male",
   "id" : "212038",
   "website" : "https://snarfed.org/",
   "first_name" : "Ryan",
   "last_name" : "Barrett",
   "locale" : "en_US",
   "verified" : true,
   "updated_time" : "2015-06-06T07:29:11+0000",
   "timezone" : -7,
   "link" : "http://www.facebook.com/212038"
}
```

my username is `snarfed.org`, which isn't mentioned there. (the `link` field doesn't count. :P)

options:
* do a `HEAD` request on the `link` field and follow redirects until we get to `facebook.com/USERNAME`, which is the final location.
* see if we can look up the username somehow. maybe FB just wants us to request it specifically with `?fields`?

note that those options only work for global user ids, not app scoped user ids. new users who authed with us after we ported to the v2.0 API are just SOL.

**Comment by snarfed** [comment]
second option doesn't work: https://developers.facebook.com/tools/explorer?method=GET&path=me%3Ffields%3Did%2Cname%2Cusername&version=v2.4 gives the error `(#12) username field is deprecated for versions v2.0 and higher`. `HEAD` request it is!

**Comment by snarfed** [comment]
i should also document in /about that syndication urls with usernames won't work for new users. :/

**Comment by snarfed** [comment]
huh. here's a weird hacky idea that might work for app-scoped user ids: when PPD finds an FB syndication URL with a username, and we don't already know the account's username, make a leap of faith and store it as the account's username so we can use it during OPD in the future.

imperfect for all sorts of reasons, but maybe crazy enough that it just might work. what do you think @kylewm?

**Comment by kylewm** [comment]
I'm a bit confused. Doesn't this only apply to PPD and the bit of OPD logic that "upgrades" a u-mention-of to a u-in-reply-to when there is a u-syndication link? Or does it really break OPD in the general case in some way I'm not thinking of?

What if Bridgy canonicalized Facebook permalinks by removing the username altogether??

The syndication link for 

  https://www.facebook.com/snarfed.org/posts/10100929680893833 

would be stored as 

  https://www.facebook.com/_/posts/10100929680893833

**Comment by snarfed** [comment]
ran this to retry a few of my recent responses:
```
for r in resps:
  if r.failed:
    print `r.key`
    r.status = 'new'
    r.put()
    util.add_propagate_task(r)
```

**Comment by snarfed** [comment]
TODOs for #448 before merging:
* [ ] switch `SyndicatedPost` hook to _pre_ put, not post, so that any inferred username applies to the `SyndicatedPost` that triggers it
* [ ] consider dropping the new `inferred_username` field and just use `username` directly, since we're not getting it directly from FB at all any more, for any users (new or old)

**Comment by snarfed** [comment]
looking at what it would take to backfill this for existing syndication urls. in remote_api_shell:
```
s~brid-gy> SyndicatedPost.query(SyndicatedPost.syndication >= 'https://www.facebook.com/a', SyndicatedPost.syndication <= 'https://www.facebook.com/zzzzzzzzzzzz').count()
220L
s~brid-gy> SyndicatedPost.query(SyndicatedPost.syndication >= 'https://www.facebook.com/A', SyndicatedPost.syndication <= 'https://www.facebook.com/ZZZZZZZZZZZZ').count()
26

s~brid-gy> sps = list(SyndicatedPost.query(SyndicatedPost.syndication >= 'https://www.facebook.com/a', SyndicatedPost.syndication <= 'https://www.facebook.com/zzzzzzzzzzzz')) + SyndicatedPost.query(SyndicatedPost.syndication >= 'https://www.facebook.com/A', SyndicatedPost.syndication <= 'https://www.facebook.com/ZZZZZZZZZZZZ')
s~brid-gy> keys = filter(None, {sp.key.parent() for sp in sps})
s~brid-gy> len(keys)
34

s~brid-gy> usernames = {urlparse.urlparse(sp.syndication).path.split('/')[1] for sp in sps}
s~brid-gy> print usernames
set([u'dominik.schwind', u'ken.kennedy', u'story.php', u'AdamsHillNeighborhood', u'nicolas.cluzeau', u'photo.php', u'login.php', u'MarcCooperPhotos', u'LFL8424', u'gregorlove', u'jgarber623', u'events', u'officialwarrenellis', u'beatsantiquefans', u'kyle.mahan', u'ChrisAldrich', u'dissolve333', u'permalink.php', u'floyboy', u'snarfed.org', u'mysmiffstream', u'notes', u'diplix', u'aaronpk', u'petermolnar.eu', u'wirres', u'dshanske'])
```

**Comment by snarfed** [comment]
#448 seems to be working well, so i merged it. @kylewm the wildcard approach would add a bit more complexity, so i'm not prioritizing it personally, but i'm still totally open to it! feel free to try it if you're ever interested.

**Comment by kylewm** [comment]
:+1: Facebook's in such a state of flux right now, I'm not excited to spend any more time than absolutely necessary working around their weirdness
