### ISSUE TITLE
search all silo posts for links to users' sites and send mentions

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#456]
spun out of #51. from https://github.com/snarfed/bridgy/issues/51#issuecomment-135816838:

> an idea for expanding this: search silos for *any* posts, from anyone, that link to the user's domain(s), and send wms for them too. these are effectively mentions.

silo support for this is mixed:
*  Twitter: [`/search/tweets.json?q=`](https://dev.twitter.com/rest/reference/get/search/tweets)
*  G+: [`/activities?query=`](https://developers.google.com/+/web/api/rest/latest/activities/search)
*  FB: no. search was removed in API v2.0. [you can search over other things, including events](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.0#search), but mentions in event descriptions are a small minority case.
*  IG: no. can't find any full text search support in their [API reference docs.](https://instagram.com/developer/endpoints/)
*  Flickr: ...?

**Comment by snarfed** [comment]
cc @kylewm in case you're interested in adding flickr search support... (see above)

**Comment by snarfed** [comment]
the remaining part here is to send mention posts themselves, not just their responses. this needs a new `post` response type connected to the post mf2 handler.

**Comment by snarfed** [comment]
finally soft launched this, and it worked well, but evidently has a memory leak, so i had to roll it back.

> Exceeded soft private memory limit of 256 MB with 328 MB after servicing 2 requests total.

ugh.

there's FUD [here](https://github.com/getlantern/laeproxy/issues/19) [and](https://github.com/getlantern/lantern/issues/243) [there](https://code.google.com/p/googleappengine/issues/detail?id=11452) about the sockets API maybe causing memory leaks due to badly handled range requests, but i can't tell how real it is or if it could be causing this. i suspect i've just been wasteful with memory, e.g. lots of string concatenations [and `copy.deepcopy`s](https://github.com/snarfed/bridgy/commit/fee8d507e5d76142263eebc0d7af1af8f1087657), and it's finally time to pay the piper. whee, can't wait to heap profile. :sob:

**Comment by snarfed** [comment]
the little orange bump of 500s here is our instances flapping (OOMing, restarting, and OOMing again):

![chart](https://cloud.githubusercontent.com/assets/778068/9982455/4754ed2a-5f92-11e5-98e3-61d4fa565794.png)

here's a snippet of individual requests at peak flap. the red !!! ones are OOMs. not pretty!

<img width="569" alt="screen shot 2015-09-20 at 12 24 48 pm" src="https://cloud.githubusercontent.com/assets/778068/9982462/9994c484-5f92-11e5-8401-0bd8cd1673da.png">

**Comment by snarfed** [comment]
silver lining: it's working ok, at least! e.g. the top response here: https://www.brid.gy/twitter/kylewmahan#responses is this tweet: https://twitter.com/anarcho/status/643921641664200704 which propagated as a mention to https://kylewm.com/2015/09/repost-of-glenn-greenwald-the-new-revolving-door

**Comment by kylewm** [comment]
wow, that mention is hidden behind a redirect too, pretty cool!

**Comment by snarfed** [comment]
for the record: who's the dunce who sprinkled `copy.deepcopy`s throughout poll, basically bridgy's inner loop, and then acted all surprised when it blew our memory budget? _this guy!!!_ :P

**Comment by snarfed** [comment]
ok, i think it might stick this time. monitoring graphs below. i turned it on for just @kylewm at the 1hr (ago) point, for 6 more accounts at 45m, and for everyone at 30m. ran out of memory once, largely due to polling @kevinmarks a few times in rapid succession (he's prolific), but that's it. and we hit that cap occasionally anyway, so i'm not too worried.

<img width="764" alt="screen shot 2015-09-23 at 12 18 49 pm" src="https://cloud.githubusercontent.com/assets/778068/10055882/6b7c39da-61ed-11e5-827f-3d351542e7be.png">
<img width="773" alt="screen shot 2015-09-23 at 12 18 15 pm" src="https://cloud.githubusercontent.com/assets/778068/10055884/70a4dffc-61ed-11e5-923f-9054e3be6e86.png">

**Comment by diplix** [comment]
i love it. it actually collects all tweets containing links to my articles. looks great, too.
<img width="572" alt="bildschirmfoto 2015-09-23 um 21 34 50" src="https://cloud.githubusercontent.com/assets/4541494/10056315/dfeb73ba-623a-11e5-8dc3-103f200f7b8e.png">
thanks a lot for this, it’s a great new feature!

**Comment by snarfed** [comment]
thanks for the kind words!

**Comment by snarfed** [comment]
this has noticeably increased our poll latency:
<img width="764" alt="screen shot 2015-09-24 at 10 43 13 am" src="https://cloud.githubusercontent.com/assets/778068/10081287/065e0e68-62a9-11e5-8cfc-3bc8b5a92838.png">

the poll task queue is now ~90m behind. not a big deal, but definitely not ideal. hrmph. time to profile i guess.

**Comment by snarfed** [comment]
some of this might be just because our slow poll frequency is once a day, so we're still working through the first set of search results for many users. that should be done by around noon PST. i'll revisit if latency is still consistently bad after that.

**Comment by snarfed** [comment]
scratch that, we'll be caught up by ~1:30pm PST today, since we're ~90m behind. math!

**Comment by snarfed** [comment]
poll latency is looking better now. averaging 5-10s, higher than ~4s before, but still reasonable.

<img width="757" alt="screen shot 2015-09-25 at 11 42 22 am" src="https://cloud.githubusercontent.com/assets/778068/10109200/80013250-637a-11e5-80bd-5b50aab65b67.png">

**Comment by snarfed** [comment]
the poll queue is still behind by 45m :/, but i'm hoping some of that was due to #490. i pushed out a change there (1ebfe1cf0d3c6675d9f8291434dc50e3fba2c39a) a few hours ago that adds a bunch of shortlink generator domains to the blacklist and checks the blacklist before searching for a domain, so i'm hoping that will help some too.

**Comment by snarfed** [comment]
tentatively closing. this has been running in prod and stable for a few days. I'm sure there are more bugs left to fix, but we can open new issues for them.

**Comment by singpolyma** [comment]
Does brid.gy also turn @ mentions to my twitter username to webmentions to my domain? That would be similar to this and very nice

**Comment by snarfed** [comment]
@singpolyma not right now, but that's an interesting feature request. just to confirm, you're proposing they'd be sent to your front page, e.g. `target=https://singpolyma.net/`?

**Comment by singpolyma** [comment]
@snarfed yes. or whatever URL is on my twitter profile

**Comment by snarfed** [comment]
i currently craft search queries by stripping scheme (ie http://), putting quotes around the remaining domain and path, and ORing all of those together, e.g. `"snarfed.org" OR "instagram.com/snarfed"`. sadly, this has been returning both false positive and false negatives in both G+ and Twitter. :/

i added the scheme back to G+ searches in 485af7323352ef9840c962c090dd7598fe9f8d53, and it looks like that cut out the false positives but didn't add any false negatives.

still working on Twitter. here's some research so far. for the URL https://hypothes.is/, here are some options and their results (linked to searches):
* [`hypothes.is`](https://twitter.com/search?f=tweets&q=hypothes.is) returns similar
  usernames and word variations, e.g. _@hypothes_is_ and _hypothesis is_
* [`"hypothes.is"`](https://twitter.com/search?f=tweets&q=%22hypothes.is%22) (our current approach) is better, but still returns _@hypothes\_is_
* [`https://hypothes.is`](https://twitter.com/search?f=tweets&q=https%3A%2F%2Fhypothes.is) and [`https://hypothes.is/`](https://twitter.com/search?f=tweets&q=https%3A%2F%2Fhypothes.is%2F) (trailing slash) only return links to the home page. same with [`"https://hypothes.is"`](https://twitter.com/search?f=tweets&q=%22https%3A%2F%2Fhypothes.is%22) and [`"https://hypothes.is/"`](https://twitter.com/search?f=tweets&q=%22https%3A%2F%2Fhypothes.is%2F%22)

hrmph.

**Comment by snarfed** [comment]
i'm now thinking about still using the `"hypothes.is"` style search for twitter and filtering out the false positives manually.

**Comment by snarfed** [comment]
[discussion in IRC.](http://indiewebcamp.com/irc/2015-12-06#t1449420402367)

**Comment by singpolyma** [comment]
Filtering false positives seems like an essential thing to do. Trying to get as much as possible is probably the best, then filter after

**Comment by snarfed** [comment]
i wish! sadly many users' domains are common words, or have common words in them, so their false positive rate can be 1K:1 or even 1M:1 for domains with words like _blog_ or _web_. :/ and bridgy is approaching 1k twitter users, so I'd like to try to cut down that workload (and cost) a bit.

**Comment by singpolyma** [comment]
filter out common words and only search for the unique part maybe?

**Comment by snarfed** [comment]
oh boy, and now i'm in the business of maintaining a stop word list and search query rewriter. :P you're definitely right, it's doable, i'm just not sure i want to take that plunge...

**Comment by singpolyma** [comment]
Sorry. Was a thought

**Comment by snarfed** [comment]
np! definitely appreciated. :two_men_holding_hands:
