### ISSUE TITLE
take protocol into account when caching webmention endpoint

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#457]
Noticed [in IRC](http://indiewebcamp.com/irc/2015-09-01#t1441147419827) that, for a site that serves both http and https, Bridgy might cache the http webmention endpoint, and use it when sending webmentions to an https target.

Granted the webmention receiver should handle this case, but it would also be nice if Bridgy sent https webmentions to an https target (and http to http).

I would probably prefer to cache the two endpoints separately (e.g. `W cleverdevil.io` and `W https://cleverdevil.io`) than to do something cleverer.

cc @cleverdevil

**Comment by snarfed** [comment]
yeah, fair point. this is actually pretty easy to do, and no migration necessary. we just switch to reading/writing the new keys, and the old ones eventually disappear from the cache.

it is slightly arbitrary to include scheme in the cache key, but not path, etc...but i get that scheme is *kind of* a special case. i am pretty fond of the curent domain-wide caching, though, so i'd probably resist narrowing the cache key any further, at least for now.
