### ISSUE TITLE
figure out how to interoperate with salmentions

### ISSUE THREAD

**Issue by voxpelli** [snarfed/bridgy#458]
I'm looking at adding Salmentions-support to my WebMention endpoint so I started to look at the data I would use and I immediately ran into a Brid.gy comment that had been marked up according to http://indiewebcamp.com/comments-presentation and with the `u-url` set to the silo-URL of the post.

This isn't a problem in Brid.gy itself, but it becomes a problem if I want to look up the original data of all of the comments of a post as I would then fetch each silo-URL rather than each Brid.gy-URL and therefore wouldn't find any Microformats-data at all.

I'm not sure how to best solve this – but would be good to figure out a best practice.

One solution would be for comments to actually have the Brid.gy-URL as the `u-url` and to have Brid.gy redirect to the silo-URL when an end-user visits the site (through the use of JS or user-agent sniffing?). It's not pretty, but it would achieve the two end goals: That a user that clicks the URL arrives at the silo-URL and that a Microformat-parser can find the original Brid.gy data.

Another advantage of said solution is that it can be deployed by Brid.gy.

**Comment by snarfed** [comment]
huh, interesting. thanks for filing this! i have to admit, i do still like having `u-url` point directly to the silo post, but i also like salmentions, and i want to help.

bridgy already kind of does its own version of salmentions - it sends wms for all comments all the way upstream, including threaded twitter reply chains - so i'm curious about the use case. do you have a concrete example where you'd want this that bridgy doesn't already handle? the one case i can think of is an indieweb-only post, with a reply that's POSSEd to a silo, and then a silo-only reply to that reply. i suspect that's pretty rare though...

**Comment by snarfed** [comment]
would an alternative solution be for bridgy to render silo responses with two `u-url`s, first the silo post's and then the bridgy url, and then 1) update http://indiewebcamp.com/comments-presentation to say both should be included in the rendered comment, and 2) encourage salmention implementations to fetch and parse all available `u-url`s?

**Comment by snarfed** [comment]
cc @kylewm and @acegiak since i think they know the most about salmentions.

**Comment by voxpelli** [comment]
The problem with fetching many `u-url`:s is: How to pick which to use for presentation? Should one pick just one? If so – which one is "better" or more correct? Or should one try to merge them?

Also cc @aaronpk

**Comment by snarfed** [comment]
@voxpelli! true! i definitely don't want to come up with that algorithm. my simpler proposal is just to pick the first one (or any one) that has mf2. it doesn't fully generalize, but it solves this problem.

**Comment by kylewm** [comment]
I've had situations where I want to keep the bridgy proxy-representative URL around for testing/debugging, but I agree that I wouldn't want to show that to the user.

We could propose a new u- property, like `u-representative-url` and follow that instead of `u-url` if it's available? (I could imagine doing the same thing for following recursive reply-chains like @dissolve does)

@voxpelli Alternatively, your salmentions implementation could fall back on using the content of the "p-comment h-cite" if you are unable to fetch the url or unable to find an h-entry there. (my implementation *only* uses the "p-comment h-cite"). Any brid-gy.appspot.com link is going to be a leaf node anyway, since they don't expose replies-to-a-reply

**Comment by snarfed** [comment]
@voxpelli i'm still curious to see a concrete example where we want salmentions and bridgy's built in kinda-salmentions for silo replies weren't enough...? it'd help this discussion to have one to look at.

**Comment by voxpelli** [comment]
@kylewm The microformats data in my data model is all identified using URL:s and I would prefer to only save microformats data for a URL of the data is actually found at that URL – to avoid getting spoofed content in the system.

@snarfed Perhaps there isn't one for Salmentions specifically – but it is somewhat problematic that someone can't verify the metadata of a Brid.gy comment currently – it may be that there will never be a need for that in the Salmentions flow – but in other flows there may be, such as in indie-readers.

I stumbled upon it as I'm using example microformats from existing pages to ensure that I can parse the data correctly and since it's very common to have Brid.gy comments amongst ones webmentions it became problematic for me.

Also: I know that I will be sending Salmention pings for received Brid.gy WebMentions once I get so far – and then, depending on the receivers implementation, it may or may not be a problem. (Sounds like there will be a conflict between Salmention markup and Brid.gy ping that the receiver will have to try and resolve)

**Comment by snarfed** [comment]
reviewing this now. lots of good discussion here, but it doesn't look like there's actually a concrete problem right now...? @voxpelli were you just thinking there might be a problem in the future (or now), and we just don't know exactly what it is yet?

if so, I'm inclined to close until if/when that problem actually happens. let me know...

**Comment by voxpelli** [comment]
@snarfed I do still think this is a problem that needs to be solved somehow, but that we probably need more real world deployments to figure out how to solve it.

I myself has been so caught up in freelance work the last six months that I haven't had the chance to do any additional work on my Salmentions so I unfortunately can't yet offer any more insight into this.

**Comment by kylewm** [comment]
> it doesn't look like there's actually a concrete problem right now...?

I think there is a concrete problem -- 

1. Alice posts on her site 
2. Bob replies to Alice on his site
  1.  Bob sends webmention to Alice
  2. Alice fetches Bob's post, parses the reply and adds it to her list of replies
3. Carl replies to Bob on Twitter
    1. Bridgy constructs a mf2 proxy of Carl's tweet at `https://brid-gy.appspot.com/twitter/12345` and webmentions Bob
    2. Bob fetches the mf2 proxy of the tweet, parses the reply and adds it to his list of replies.
    3. per-salmentions, Bob sends a webmention to Alice
    4. Alice fetches Bob's post to check for updates and new comments
    5. Alice sees a new comment from Carl at `https://twitter.com/12345`
    6. Alice tries to fetch `https://twitter.com/12345` to parse the original for mf2 (bc she does not want to have to rely on Bob's interpretation, either to prevent spoofing or degraded quality from parsing a copy-of-a-copy)
    7. Of course twitter.com post does not have mf2 and fails to parse.

**Comment by snarfed** [comment]
@kylewm ooh good point!

that seems like a bigger problem than just bridgy. mf2 currently has `u-url` for canonical copy, but it doesn't have the inverse, ie _this version is subsidiary and non-authoritative *but* you should still prefer it in some cases, eg if you want mf2._ do we need a new mf2 class for that? am i even describing it right?

cc @tantek @aaronpk @kevinmarks

**Comment by snarfed** [comment]
it's not `u-syndication`, since it's not a syndicated copy. maybe `u-proxy`? i dunno. feels like i'm thinking about this fundamentally wrong somehow. ¯\\\_(ツ)\_/¯

**Comment by snarfed** [comment]
@kylewm was way ahead of me earlier in https://github.com/snarfed/bridgy/issues/458#issuecomment-137188329 when he proposed `u-representative-url`. sorry kyle!

**Comment by kylewm** [comment]
[per discussion on IRC](http://indiewebcamp.com/irc/2016-04-06/line/1459974297796) if Alice POSSEd to Twitter and Bob POSSEd to Twitter, then Bridgy would backfeed Carl's reply all the way back to Alice without having to rely on Salmentions.

So I'm on board that this may not really be something we need to solve, and I'm +1 closing it for now.

**Comment by snarfed** [comment]
[*lots* of discussion in IRC today.](http://indiewebcamp.com/irc/2016-04-06#t1459973643455)
* could we use `u-uid` for this? unclear, but probably not.
* we don't need this for twitter replies-to-replies, since bridgy already backfeeds those natively, #217. (or to rephrase, that's not a very useful concrete use case.)
  * (also, this preserves the full nesting/threading structure. few recipients actually use or recreate that, though, if any.)
* consumers could read and use the wm source's own mf2 of its responses. they don't necessarily need to fetch those responses' `u-url`s and parse them. people want to, though, to get the best fidelity and precision.
* @dissolve currently handles salmentions + bridgy backfeed by using https://github.com/indieweb/php-mf2-shim to get mf2 from silo urls.
* @kylewm is currently looking for a good real world example of this problem in the wild.

**Comment by kylewm** [comment]
> @dissolve currently handles salmentions + bridgy backfeed by using https://github.com/indieweb/php-mf2-shim to get mf2 from silo urls.

I'm pretty sure this was talking about crawling recursive reply contexts, not really related to salmentions nor Bridgy.

> @kylewm is currently looking for a good real world example of this problem in the wild.

I failed, and doubt an example currently exists (though I could construct one easily).

**Comment by snarfed** [comment]
sgtm! happy to leave this open pending a real world example until if/when we find one.

**Comment by snarfed** [comment]
hey @voxpelli et al, it's been  a year. did we ever find a concrete problem or feature here that bridgy needs to fix or implement?

**Comment by voxpelli** [comment]
@snarfed There's still a lack of Salmention deployments and I haven't had time during the last year to finish my own Salmention implementation and deploy that, so we're not any wiser now than we were a year ago but I still think this issue is valid and would love to keep it open until Salmention starts to get some traction and we can see some real world examples of Bridgy interactions with it

**Comment by snarfed** [comment]
it's been another year! and salmention adoption is still...maybe weak at best. i'm lightly inclined to close this, since i'm still not sure there's a concrete bridgy bug or missing feature here, other than we just want to test it more. 😁

**Comment by voxpelli** [comment]
I want to keep it open – still feels promising, but eg. I myself haven’t really had the ability to work on it for the last 1-2 years but when I do Salmention should be fairly close to be working 😝

**Comment by snarfed** [comment]
agreed, i definitely think salmentions are promising too! both in general and with bridgy specifically. I'm just not convinced about keeping an issue with no concrete ask open. (not to mention it's been a number of years and still none of us care enough to actually test it. :P)

how about we close this, and if/when one of us tests, we open new issue(s) for any problems we find?

**Comment by snarfed** [comment]
sure! done. this is the first time we've wanted this kind of label in >4y though, so if we don't use it on more issues, i may eventually delete it. :P we'll always be able to find this issue by searching for _salmentions_!
