### ISSUE TITLE
flickr comments with dt-updated instead of dt-published date stamp

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#460]
is there a specific reason, that for example bridgy posts twitter comments with a ```dt-published``` datestamp, but the new flickr thing (thanks, great new feature!) uses ```dt-updated```?

examples:
https://brid-gy.appspot.com/comment/twitter/diplix/640184121407307776/640186341289017344
https://brid-gy.appspot.com/comment/flickr/92049783@N06/20987343809/92004461-20987343809-72157657817355789

the problem seems to be at least with webmetion.io getting "published":null mention data:
http://webmention.io/api/mentions?target=http%3A%2F%2Fwirres.net%2Farticle%2Farticleview%2F8467%2F1%2F6%2F

**Comment by kylewm** [comment]
Just a mistake on my part, fixed now. Thanks @diplix!
