### ISSUE TITLE
Return syndication URL in Location header

### ISSUE THREAD

**Issue by aaronpk** [snarfed/bridgy#462]
When Bridgy Publish creates a POSSE copy on Twitter, Facebook, etc, it currently returns the Tweet/Facebook URL of the post in a JSON body. In addition, it should return a `Location` header with that URL, and the `HTTP 201 Created` response code. More info: http://indiewebcamp.com/syndication-brainstorming

**Comment by snarfed** [comment]
:+1:

**Comment by snarfed** [comment]
deployed!
