### ISSUE TITLE
bridgy publish twitter: bridgy returns error 500, publishes nevertheless

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#467]
if i send a http post request (via curl) to ```https://www.brid.gy/publish/webmention``` (data ```source=http://wirres.net/8479&target=http://brid.gy/publish/twitter&bridgy_omit_link=```), bridgy responds with this:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=UTF-8
Vary: Accept-Encoding
Date: Mon, 07 Sep 2015 20:05:17 GMT
Server: Google Frontend
Cache-Control: private
Alt-Svc: quic=":443"; p="1"; ma=604800
Accept-Ranges: none
Transfer-Encoding: chunked
<html>
<head>
<title>500 Internal Server Error</title>
</head>
<body>
<h1>500 Internal Server Error</h1>
The server has either erred or is incapable of performing the requested operation.<br/><br/>
</body>
</html>
```

if i try this with bridgy publish to facebook, the response is fine, as always. 

this is the bridgy log (which i don’t understand): https://www.brid.gy/log?start_time=1441656317&key=aglzfmJyaWQtZ3lyVgsSDVB1Ymxpc2hlZFBhZ2UiL2h0dHA6Ly93aXJyZXMubmV0L2FydGljbGUvYXJ0aWNsZXZpZXcvODQ3OS8xLzYvDAsSB1B1Ymxpc2gYgICAgICAgAoM

at the end of the log there seems to be a hint, to what causes the problem (which, again, i don’t understand):

```
2015-09-07 20:05:17.653600 E header values must be str, got 'unicode' (u'https://twitter.com/diplix/status/640979169422233601') for 'Location'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1522, in __call__
    return response(environ, start_response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webob-1.1.1/webob/response.py", line 939, in __call__
    start_response(self.status, headerlist)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 200, in _StartResponse
    (_GetTypeName(value), value, name))
InvalidResponseError: header values must be str, got 'unicode' (u'https://twitter.com/diplix/status/640979169422233601') for 'Location'
```

one more question remains: my bug or bridgy’s bug?

**Comment by snarfed** [comment]
sorry for the trouble @diplix, and thanks for the report! looks like this was introduced in #462. @myfreeweb mind taking a look?

**Comment by diplix** [comment]
no problem. glad to help and glad to find out it’s not again one of my mistakes.

**Comment by myfreeweb** [comment]
Ugh, Python 2.x unicode handling, also inconsistency between tests and real App Engine? :(

I don't want to bother with pull requests for a one line fix again... Can you just put an `.encode('utf-8')` on it?

```python
self.response.headers['Location'] = self.entity.published['url'].encode('utf-8')
```

**Comment by snarfed** [comment]
sure, no problem. actually it looks like we just missed it due to test coverage, not charset handling surprises or prod/test app engine skew. bridgy's fake test silo returns a `string` url, but twitter returns a `unicode`. :P
