### ISSUE TITLE
Bridgy Publish to Facebook of notes appears to overescape ampersands

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#471]
Bridgy Publish to Facebook appears to overescape ampersands (which must be HTML-escaped in the original markup in order to be valid HTML)
E.g. original:
* http://tantek.com/2015/256/t1/purge-stuff-not-building-positive-future

Bridgy Publish to FB copy:
* https://www.facebook.com/tantek.celik/posts/10101883746673363
(note the "amp;" in the visible text of the FB post)

**Comment by snarfed** [comment]
thanks for the report! [log here](https://www.brid.gy/log?start_time=1442197850&key=aglzfmJyaWQtZ3lybQsSDVB1Ymxpc2hlZFBhZ2UiRmh0dHA6Ly90YW50ZWsuY29tLzIwMTUvMjU2L3QxL3B1cmdlLXN0dWZmLW5vdC1idWlsZGluZy1wb3NpdGl2ZS1mdXR1cmUMCxIHUHVibGlzaBiAgICAgOSRCgw). @kylewm started to debug and noticed that `html2text.html2text()` oddly leaves HTML entities as is. he suggests running `html2text.unescape() `afterward.

**Comment by snarfed** [comment]
thanks @kylewm, worked like a charm!

**Comment by tantek** [comment]
Thanks @kylewm @snarfed! I've edited the FB copy to just have an & now, but you can still see the original &amp; if you click the "Edited" link on the post.
