### ISSUE TITLE
Google+ Error

### ISSUE THREAD

**Issue by drikkes** [snarfed/bridgy#472]
When I click the g+Button under the "Get started:" on https://www.brid.gy/, then I get this:
"500 Internal Server Error
The server has either erred or is incapable of performing the requested operation."
Am I the only one?

**Comment by snarfed** [comment]
hey, thanks for the report, and sorry for the trouble! looks like that 500 was transient; google just timed out on one of the API calls. mind trying again?

**Comment by drikkes** [comment]
The error (message) is gone, but it looks like bridgy doesn't poll new responses. Or can't find the new ones.

**Comment by snarfed** [comment]
huh, ok. apologies again. i'll investigate soon.

**Comment by snarfed** [comment]
@drikkes looking at your G+ posts https://plus.google.com/+HendrikSpree/posts , it looks like the last two responses are on https://plus.google.com/+HendrikSpree/posts/KCScr2wVH5E on 2015-09-17, and then on https://plus.google.com/+HendrikSpree/posts/QQtQFbBvhS9 on 2015-06-24, and bridgy saw both of those (https://www.brid.gy/googleplus/117081496722450941731). are there others i missed? maybe on non-public posts?

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!

**Comment by drikkes** [comment]
Apologies for not answering this long. Somehow my crosspostings to G+ switched from "public" to "private". I don't remember having ever touched any of these settings. I suspect the crappy Wordpress App for iPhone to somehow messed things up. Could that be possible? 
Now everything bridgy-related on G+ is working fine for me again. Sorry for bothering you with stuff like this.

**Comment by snarfed** [comment]
hey, not at all, bug reports are always valuable. I'm not sure what would have changed your G+ setting, but I'm glad it's working again!à
