### ISSUE TITLE
quiet down oauth1 logging

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#475]
our twitter and flickr poll logs are painfully chatty and hard to read right now, mostly due to the overly verbose oauth1 logging for every API request. it'd be nice to turn that down to a single line per HTTP request, like with the oauth2 silos. the URL and query params are useful, but i bet we can do without all of the oauth1 details (signature etc).

**Comment by snarfed** [comment]
afaik the hard part about this is that the logging comes from other libraries, e.g. `requests-oauthlib`, not from us. should still be doable with per-logger configs in the `logging` module though.

**Comment by kylewm** [comment]
played with this a little, I think this gets it
```
# quiet down oauth1 log messages
logging.getLogger('oauthlib').setLevel(logging.INFO)
logging.getLogger('requests_oauthlib').setLevel(logging.INFO)
```

but should it go in `bridgy.appengine_config`, `granary.appengine_config`, or somewhere else?

**Comment by snarfed** [comment]
awesome, thanks! hmm, not sure where it would go. even `oauth_dropins.appengine_config` is a candidate, since it mediates many of those API calls.

i don't have a strong opinion. thoughts?

**Comment by kylewm** [comment]
on reflection, I think probably in Bridgy proper. tweaking the logs seems like it should be up to the application not its libraries

**Comment by snarfed** [comment]
sgtm!

**Comment by snarfed** [comment]
thanks again!
