### ISSUE TITLE
Facebook posts through apps not picked up?

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#479]
Not a big issue (and doesn't necessarily need a fix), more of a question where I'd like to understand what's happening:
I've got two self-hosted WordPress blogs. For one of them I share the posts manually on FB, Twitter & G+ (mainly because I individualise the posts for each platform). For the other one I use the WordPress/Jetpack Publicise functionality (because that's good enough).
Both blogs are picked up in my FB/bridgy profile (https://www.brid.gy/facebook/776938267, they are islay.org.uk and blog.ministryofpropaganda.co.uk).
For the first blog bridgy picks up likes and comments just fine. For the second it seems bridgy doesn't seem to pick up the reactions.
I'm guessing it's because FB somehow posts these differently, i.e. for the second blog it posts these as "Armin Grewe published an article on WordPress", although it links directly to the blog post.
As I said, doesn't necessarily need a fix as far as I'm concerned (unless you deem it needs to be fixed), but I'm curious about why these aren't picked up.

**Comment by snarfed** [comment]
thanks for filing! huh, you're absolutely right. we use the `/me/feed` API endpoint to get your posts, and your blog.ministryofpropaganda.co.uk posts don't show up at all.

here's a hunch: try logging into Facebook on https://www.brid.gy/ again? we've added a few different permissions recently, maybe since you last authorized your account.

**Comment by armingrewe** [comment]
Have re-authorised, not sure yet if it helped. Will keep watching.

**Comment by snarfed** [comment]
cc @pfefferle, looks like this is happening to him too, also with posts from WordPress. https://brid.gy/facebook/660908551

**Comment by pfefferle** [comment]
habe you tried it with the v2.5 namespace in the api url? o have tried it in the developer sandbox https://developers.facebook.com/tools/explorer and it seems to work.

**Comment by kylewm** [comment]
This is almost certainly a [user_actions.news](https://developers.facebook.com/docs/facebook-login/permissions#reference-user_actions_music) permission that Bridgy's missing. Those "published an article on Wordpress" posts are from Facebook's ([soft deprecated?](http://www.theverge.com/2014/5/27/5754862/facebook-gives-up-on-automatically-sharing-everything-you-do-online-open-graph)) Actions and Objects API. Here's one I published when I was experimenting with mention tagging a while back

![](http://indiewebcamp.com/images/c/c8/fb-post-news-publishes.png)

**Comment by snarfed** [comment]
ooh, that sounds promising. thanks @kylewm! damn, the [graph api explorer](https://developers.facebook.com/tools/explorer) doesn't support the user_actions.news permission. i wonder if there's any other easy way to confirm. looks like you're right, though. i may just go ahead and request it now.

**Comment by snarfed** [comment]
i'm actually now thinking about requesting user_actions.books, user_actions.fitness, user_actions.music, user_actions.news, and user_actions.video.

**Comment by snarfed** [comment]
ugh, actually, the reviews for these permissions are a bit involved. they all claim the require screencasts. :/ i've done one of these screencasts before - https://brid.gy/about#like - and it's doable, but takes a bit of work.

**Comment by kylewm** [comment]
Experimenting a little. I added a news.publishes action via the API

![screenshot from 2015-12-22 09-32-55](https://cloud.githubusercontent.com/assets/950127/11961722/2e62bd60-a88f-11e5-9d13-afea531434a8.png)


Even with the `user_actions.news` permission this post doesn't show up in `/me/feed` or `/me/posts` :sob:  As far as I can tell it only shows up in `/me/news.publishes`

![screenshot from 2015-12-22 09-35-09](https://cloud.githubusercontent.com/assets/950127/11961766/8c6680d6-a88f-11e5-84d3-8d44777bdd84.png)

**Comment by snarfed** [comment]
ooh interesting! we already hit plenty of API endpoints, we could definitely add `/me/news.publishes` too if it works. what's one more. can you tell if it definitely needs `user_actions.news`? i assume so; just curious.

**Comment by snarfed** [comment]
hey btw, where'd you find `/me/news.publishes`? i don't see it on https://developers.facebook.com/docs/graph-api/reference/v2.2/user or https://developers.facebook.com/docs/graph-api/reference/v2.5/user.

**Comment by snarfed** [comment]
also, if we were to actually do this, i'd be fine with just `news` for now. i doubt many (or any!) bridgy users are posseing with `books`, `fitness`, `music`, or `video` open graph actions.

**Comment by kylewm** [comment]
It's from the Open Graph Stories API

https://developers.facebook.com/docs/reference/opengraph/action-type/news.publishes/

news.publishes is one of the common actions, but there are tons, including custom application-specific actions. Facebook hasn't removed this API but its use is definitely not encouraged. E.g. when I posted a story via the API it didn't show up in my feed, just in my "Recent Activity"

**Comment by snarfed** [comment]
huh, interesting. i wonder if they prioritize some other apps for news feed, etc. eg @pfefferle's https://www.facebook.com/660908551 shows posts from WordPress that i think are `news` from as recent as 12/7.

**Comment by armingrewe** [comment]
In my experience both versions (the manual ones from islay.org.uk as well as the WordPress/Jetpack (I think it might be a Jetpack function) from blog.ministryofpropaganda.co.uk) show up in the FB feed pretty much instantly. No different from that point of view.
The only difference is that the latter (which are not picked up by bridgy) show as "Armin Grewe published an article on WordPress." while the former show as a simple link share even though I actually use the share functionality/buttons from the blog.

**Comment by pfefferle** [comment]
I run some tests with the "Graph API Explorer" (v2.5) and I got all WordPress posts only with the `user_posts` and `user_actions.news` credentials.

**Comment by snarfed** [comment]
i made a screencast, https://youtu.be/v6mBcRs8CGI , and applied for `user_actions.news`, https://developers.facebook.com/apps/256884317673197/review-status/items-in-review/ . fingers crossed!

**Comment by snarfed** [comment]
woo, Facebook approved us!

@armingrewe, if you log into Bridgy with Facebook again, it should hopefully start picking up the ministryofpropaganda.co.uk posts now.

**Comment by snarfed** [comment]
hrm, it's not working for my account. let me debug a bit first.

**Comment by snarfed** [comment]
i see the bug. i can fix it later today.

**Comment by armingrewe** [comment]
Only just got home from a day out watching Starlings (yes, really). If I'm not sleeping (am quite tired) by the time it's ready I'll try today, otherwise tomorrow.

**Comment by snarfed** [comment]
ok @armingrewe, should be fixed now. feel free to try whenever!

**Comment by pfefferle** [comment]
works like a charm! thanks!

**Comment by armingrewe** [comment]
Logged in again just before I went to bed, woke up this morning to lots of activity coming through. Think it has picked up everything going back several weeks. I'd call this resolved, happy to close unless there's anything you still need to do.

**Comment by snarfed** [comment]
yay, glad to hear it!
