### ISSUE TITLE
FB publish: detect missing permission and re-request it

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#481]
@diplix hit this just now. sorry felix!

error below. we can probably match on the code and/or _Requires extended permission_.

``` json
{
   "error" : {
      "message" : "(#200) Requires extended permission: publish_actions",
      "type" : "OAuthException",
      "code" : 200
   }
}
```

[log](https://www.brid.gy/log?start_time=1442945156&key=aglzfmJyaWQtZ3lyVgsSDVB1Ymxpc2hlZFBhZ2UiL2h0dHA6Ly93aXJyZXMubmV0L2FydGljbGUvYXJ0aWNsZXZpZXcvODU4Ni8xLzYvDAsSB1B1Ymxpc2gYgICAgIDDlQoM):

```
Params: [(u'state', u'{"source_url":"http://wirres.net/8586",...
...
Fetching https://graph.facebook.com/v2.2/me/photos?access_token=...... kwargs {'data': 'url=http%3A%2F%2Fwirres.net%2Fezimagecatalogue%2Fcatalogue%2Fvariations%2F6098-500x2000.jpg%3Ffull%3D%2Fezimagecatalogue%2Fcatalogue%2FphpG8f8m4.jpg&message=schlossplatz.%0A%0A%28Originally+published+at%3A+http%3A%2F%2Fwirres.net%2F8586%29'}
Error 403, response body: {"error":{"message":"(#200) Requires extended permission: publish_actions","type":"OAuthException","code":200}}
Converting code 403 to 401
...
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/6.387336388592316301/publish.py", line 209, in _run
result = self.attempt_single_item(item)
File "/base/data/home/apps/s~brid-gy/6.387336388592316301/publish.py", line 332, in attempt_single_item
result = self.source.gr_source.create(obj, include_link=not omit_link)
File "/base/data/home/apps/s~brid-gy/6.387336388592316301/local/lib/python2.7/site-packages/granary/facebook.py", line 377, in create
return self._create(obj, preview=False, include_link=include_link)
File "/base/data/home/apps/s~brid-gy/6.387336388592316301/local/lib/python2.7/site-packages/granary/facebook.py", line 533, in _create
resp = self.urlopen(API_PHOTOS, data=urllib.urlencode(msg_data))
File "/base/data/home/apps/s~brid-gy/6.387336388592316301/local/lib/python2.7/site-packages/granary/facebook.py", line 1267, in urlopen
timeout=appengine_config.HTTP_TIMEOUT)
...
HTTPError: HTTP Error 403: Forbidden
```

**Comment by snarfed** [comment]
@diplix if you re-auth FB on bridgy and grant it permission to post as you, hopefully that will fix this.

**Comment by snarfed** [comment]
actually never mind, i see that you already tried that. looks like that's a separate bug: #482.

**Comment by diplix** [comment]
i could delete the bridgy permission alltogether from facebook and reauthenticate. if that helped. but probably better wait for #482?

**Comment by snarfed** [comment]
sure! that should work. or more easily, just disable and then re-enable publish. the bug fix is at least a few days away, and it won't do anything different or better than those options.

**Comment by diplix** [comment]
it worked :)

**Comment by snarfed** [comment]
now that #482 is done, i actually think this is lower priority, since relatively few people should hit it and re-authing will now fix it consistently. deprioritizing.

**Comment by snarfed** [comment]
bridgy publish for facebook will disappear soon (#817), so I'm closing open issues for it. sad. feel free to holler if you disagree.
