### ISSUE TITLE
Got mentions for my POSSE'd copies

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#485]
22 minutes ago on https://www.brid.gy/twitter/singpolyma for example see the mention on https://singpolyma.net/actionstream/they-took-our-myths-httpwww/

**Comment by snarfed** [comment]
hey, sorry for the trouble, and thanks for the report! this is due to today's launch of #456 + #51. i'll look into it soon.

**Comment by kartikprabhu** [comment]
bridgy is sending mentions to original post from POSSE copies. 
example: https://kartikprabhu.com/notes/philip-brooks-jr

**Comment by snarfed** [comment]
this is hopefully fixed. @kartikprabhu let me know if it happens again!
