### ISSUE TITLE
backfeed Facebook location tags (not currently in API)

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#489]
Just as your friends can tag other people in your POSSE copies of photos (e.g. on Facebook, Flickr), on Facebook in particular, your friends can set (what Facebook oddly calls "tag" for a singular field) the location of your photos as well!

Thus just as Bridgy should backfeed person-tags (Issue #488 ), Bridgy should also backfeed such location "tagging" on silo copies of your posts (especially photos) back to the original.

Related on the publish side: issue #317

**Comment by snarfed** [comment]
:+1:

**Comment by snarfed** [comment]
i don't see these exposed in the API. https://developers.facebook.com/docs/graph-api/reference/v2.10/post/ has `with_tags`, but that's just people. no relevant edges. https://developers.facebook.com/docs/graph-api/reference/place-tag/ may be it, but the docs are worthless, and i don't see how to get to it from anywhere else.

**Comment by snarfed** [comment]
[Facebook support is dead](https://brid.gy/about#rip-facebook) (#817, #826), so I'm closing this as obsolete. feel free to reopen if you have any concerns!
