### ISSUE TITLE
interpret website URLs from profiles more intelligently

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#490]
right now we're pretty dumb about it. it didn't matter too much before, but it does now that we search for links to users' web sites and backfeed them (#456).

off the top of my head:
* [x] follow redirects and only store final URLs in `Source.domains`/`domain_urls`
* [x] mentions search: don't search for domains in the webmention blacklist
* [x] add url shortener domains to blacklist
* profile URLs with paths:
  * [x] mentions search: include the path in the search query? (check that this works first)
  * [x] show the path on the user page (we don't right now :/ )
  * [ ] publish: check that publish source URL matches path

**Comment by snarfed** [comment]
this was motivated by https://www.brid.gy/twitter/DodgerWA , who has http://tiny.cc/DodgerWA in the website field of his twitter profile. tiny.cc is a url shortener, and his link redirects to http://tiny.cc/DodgerWA. however, we didn't check for a redirect, and instead blithely extracted tiny.cc as his domain and proceeded to search for mentions of it, which turned up all sorts of shortlinks, including porn and spam. whee!

**Comment by kylewm** [comment]
perhaps require a (rel=me) backlink on the homepage? is that too strict?

**Comment by snarfed** [comment]
huh. which problem would that solve?

**Comment by kylewm** [comment]
I'm thinking the problem of someone listing their website as microsoft.com, and then Bridgy searching for every mention of microsoft.com

**Comment by snarfed** [comment]
aha. yeah that would definitely work, but i don't know that we actually have that problem yet. following redirects and using the webmention blacklist would both have helped here.

i also worry a bit about checking rel-me because it's one more adoption hurdle, and i still kinda like our promiscuous-by-default stance.

related to #86 too i guess.

**Comment by kylewm** [comment]
good points :+1:

**Comment by snarfed** [comment]
current status: learning about domain blacklists, e.g. http://uribl.com/ . probably overkill and too heavyweight for our purposes, but still interesting.

**Comment by snarfed** [comment]
here's a `remote_api_shell` snippet that dumps all domains currently in the system. maybe someday when i have a lot of free time, i'll audit it for more blacklist candidates.
```py
import models
import flickr
import googleplus
import instagram
import twitter
import facebook

domains = set()
i = 0
for cls in models.sources.values():
  for src in cls.query(cls.domains > ''):
    if src.domains:
      print src.domains
      domains.update(src.domains)
    i += 1
    if i % 100 == 0:
      print i
```
