### ISSUE TITLE
not backfeeding comments

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#492]
sorry for the trouble, @hank!

user page: https://www.brid.gy/googleplus/107426216497388193170. example post: https://plus.google.com/+ErikGregg/posts/dmdVTVCCTLA , https://www.jointsecurityarea.org/2015/testing-out-bridgy

oddly we are backfeeding +1s ok.

**Comment by hank** [comment]
Awesome thanks!  I'm looking forward to seeing comments show up soon.  Let me know if there's anything I can do to test / help.  I noticed a lot of the code appears to be in python.  I'm a pretty decent python dev, so I'd be happy to help code / debug too.

**Comment by snarfed** [comment]
thanks for the offer! I'm probably best suited for this bug specifically, or one of the other regular contributors, but there are lots of other open issues (small feature requests, etc) that we'd love help with! feel free to drive in if you want, and ping me if you get stuck.

looks like this one is due to the recent launch of #456 + #51. it's affecting me too, so probably all G+ account, and maybe other silos too.

**Comment by snarfed** [comment]
yup, this indeed affects all silos. caused by cd6c58870165c8ab352676f95967178d402dd93b. fixing now.

**Comment by hank** [comment]
Fantastic!

**Comment by snarfed** [comment]
thanks again for the report! i think it should also send your existing comments, but it needs a new comment on the post to trigger it.

**Comment by hank** [comment]
It pulled in the new comment, but not the old ones.  That's OK though.
