### ISSUE TITLE
Twitter - "no webmention targets"?

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#494]
For some reason retweets of my own tweets don't seem to work correctly anymore. Bridgy seems to identify them (shows them as "original") and I believe correctly doesn't send them. However, if that tweet is then retweeted it seems to have a problem sending them, showing as "no webmention targets"? Other mentions (FB, G+) of that post work just fine.
The retweet of a "third party" tweet is recognised and sent fine.
![image](https://cloud.githubusercontent.com/assets/9156586/10124112/87f4aa52-6544-11e5-9902-be44dd88a3f6.png)

**Comment by snarfed** [comment]
damn. thanks for the report! probably another bug introduced by #51 + #456. I'll look soon.

**Comment by snarfed** [comment]
ok, so, current theory is that mention search found these RTs first, before fetching the user's activities did, so we ended up storing them as mentions, with `Response.type` == `post`.

i'm surprised that search returns RTs along with the original tweet...? yup, confirmed, it does. guess i need to filter RTs out of search results.
