### ISSUE TITLE
Link inside webmention body is different from URL of `target=` param

### ISSUE THREAD

**Issue by fiatjaf** [snarfed/bridgy#497]
Take a look at this: https://www.brid.gy/log?start_time=1443734078&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo2NDk2OTIzNzQzODIyODg4OTYM

the `target` URL of the webmention HTTP request (`http://entulho.fiatjaf.alhur.es/notas/pastorq-ganha-de-dawkins-em-seu-proprio-documentario-https-www-youtube-com-watch-t-1539-v-8naos1m-ts/`) is different from the URL that is linked at the body of the webmention (`http://entulho.fiatjaf.alhur.es/c/560d94c5b840794b598068cc`).

Now, I don't know if this is a bug, but I think it is.

Considering my site structure, specifically: the second link (the link in the body of the webmention) is the "permalink" version of the first. The permalink version is marked as `u-url` and `u-uid` in my `rel=feed`, and it redirects to the other version, which has a slug with lots of words and so on and is mutable.

**Comment by kylewm** [comment]
I don't think this is a bug. Bridgy intentionally follows redirects before sending a webmention, among other things to make sure we aren't sending webmentions to blacklisted domains that are hidden behind a redirect.

**Comment by fiatjaf** [comment]
Yes, I don't think that following redirects is a bug, the problem is only that the URLs are different. It could use the URL after redirection in the body of the webmention also, not only in the POST params. Is this a bad idea?

My problem is that is complicated for my webmention endpoint to handle this. It can easily know if the `target=` URL is correct when receiving a webmention request, but it _can't_ easily know that it must check the body of a webmention for an alternate version of the URL in `target=`.

**Comment by fiatjaf** [comment]
Imagine that there are various URLs (say, `/a?n=23` and `/n/twenty/three`), all redirecting to one, `/n/23`, and you refer to `/a?n=23&other=xyz` in your post. Then your webmention sender follows the redirects and get the final URL, `/n/23`, then send the webmention to it, but in the body of your post it leaves `/a?n=23`. Is that reasonable? Now that I wrote I think it is reasonable from the sender viewpoint, but I still don't know how the receiver should treat this: should he follow redirects on all the URLs in the webmention body to see if they match his "final" URL, `/n/23`?

Now this is not a bug report anymore.

**Comment by kylewm** [comment]
> Now this is not a bug report anymore.

:grinning: 

Let's ask in IRC; I don't honestly know, and I could argue either way.

**Comment by kylewm** [comment]
For my own reference, we're not following redirects in this one very specific case of posse-post-discovery where `u-syndication` is available right there in the `h-feed`, so we don't go to the trouble of fetching the permalink itself.

https://github.com/snarfed/bridgy/blob/master/original_post_discovery.py#L397

**Comment by aaronpk** [comment]
Whatever URL bridgy includes in the HTML is the value that should be sent as the target. If you're going to follow redirects, then just make sure you're using the URL after redirects for both. Does that help?

**Comment by fiatjaf** [comment]
So it is a bug.

**Comment by kylewm** [comment]
Thanks @aaronpk that does help. Haha, yes it is a bug!

**Comment by kylewm** [comment]
Confirmed working in https://brid-gy.appspot.com/comment/twitter/fiatjaf/649738083391266816/649999077661261825

I don't think older posts that Bridgy has already discovered syndication relationships for will be updated, but new posts going forward should have the fully expanded url in the post body. Thanks for the report @fiatjaf!

**Comment by snarfed** [comment]
@kylewm++ thanks for the fix!

**Comment by fiatjaf** [comment]
Thank you very much!
