### ISSUE TITLE
backfeed quote tweets

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#504]
[requested by @kartikprabhu on irc](http://indiewebcamp.com/irc/2015-10-08#t1444338186501). quote tweets can be identified by the `quoted_status_id` field. more docs:
* https://support.twitter.com/articles/20169873
* https://dev.twitter.com/overview/api/tweets
* http://indiewebcamp.com/quotation#Silo_Examples

looks like we can find them by searching for the id of the quoted tweet. for bridgy, we can search for the user's last N tweets by `OR`ing the ids together, e.g. https://twitter.com/search?q=564316935001628672%20OR%20652182041757380608

TODO: are there corresponding features in any other silos? cc @tantek @kevinmarks @aaronpk for their silo knowledge.

**Comment by kevinmarks** [comment]
+1 to this, especially as I am trying out emoji likes as tweets. e.g. https://twitter.com/kevinmarks/status/662041840938422274 of https://twitter.com/benwerd/status/662002025270349825 that is the POSSE copy of http://werd.io/2015/creating-a-usable-text-editor-in-a-web-browser-is

**Comment by tantek** [comment]
+1 to this as someone who's tweets get quoted once in a (rare?) while, like:
https://twitter.com/kfury/status/661738224969121792
And of course @KevinMarks doing his reacjweet thing: 
https://twitter.com/kevinmarks/status/661802300407545856

**Comment by kylewm** [comment]
![reacjweet](https://github-cloud.s3.amazonaws.com/assets%2F950127%2F10956796%2F675a3478-8313-11e5-9f51-5266183980a3.jpg)

**Comment by kevinmarks** [comment]
it's happening, kyle, just watch http://emojitracker.com

**Comment by snarfed** [comment]
what are quote tweets? reposts with content? replies with a cite? how should we translate a quote tweet to mf2?

**Comment by kylewm** [comment]
i don't think the mf2 vocab is a settled issue yet, but i'm fine with whatever markup you go with.

for the record, in my mind it's definitely a repost + content, just like Tumblr reblogs and Facebook shares (which can have commentary but are primarily about highlighting the original). I believe @tantek argues that repost cannot have additional content, but retweets are basically the *only* implementation I can think of that doesn't allow you to add commentary.

**Comment by snarfed** [comment]
yup, agreed that the real world examples mostly do allow commentary.

one additional consideration is that many webmention handlers currently facepile reposts, probably even if they have content, so their display would hide it. we could maybe encourage people to not facepile reposts with content.

**Comment by aaronpk** [comment]
When I repost something, my intent is to share the original content as a post with equal weight as one I wrote myself. 

Twitter shows a facepile and count of pure reposts, and quoted tweets are not part of that count.

I am of the opinion that a quoted tweet, or repost with content, is not the same as a pure repost. It is more along the lines of just sharing a link and adding a comment, where the rendering of the post also includes the original content.

**Comment by snarfed** [comment]
thanks for the input! do you think the same of facebook and google+ shares with messages? (which they encourage you to include.)

**Comment by snarfed** [comment]
I'm currently leaning toward backfeeding quote tweets as replies, not reposts, because many webmention handlers render reposts in facepiles, so the comments in them would be hidden.

i don't feel strongly, and I'd happily switch if enough facepile implementations start fully rendering reposts that have content.

feedback is welcome!

**Comment by kevinmarks** [comment]
That makes sense to me; the facepile code could look for the pure emoji
ones if necessary

**Comment by aaronpk** [comment]
They're not replies, so could you just add a link to them without in-reply-to?

**Comment by kylewm** [comment]
> a link to them without in-reply-to

+1 this

**Comment by snarfed** [comment]
> They're not replies, so could you just add a link to them without in-reply-to?

sure! that could work too.

honestly though, to be fair, we don't know what they are. twitter definitely doesn't say explicitly. so we kinda get to choose for ourselves.

i know some webmention handlers suppress mentions similarly and just render then as "X mentioned this." fewer than facepile responses, maybe, but still some, and that's not ideal either.

i dunno.

**Comment by kevinmarks** [comment]
They can be replies, they are like top posted ones in email

**Comment by aaronpk** [comment]
Twitter calls them "quoted tweets" but doesn't show a counter of how many times a tweet has been quoted.

I would say don't add any special property until we have a better idea of what that property might be. If you don't add anything except a plain link to the tweet (and more accurate would be to also include the full text of the quoted tweet), then webmention receivers will treat it just like any other URL linked to their post. 

You could add `h-cite` markup around the text of the quoted tweet which would be an accurate representation of what's happening.

For example, this tweet https://twitter.com/joshmarinacci/status/666413402789535744
Here's how I imagine it showing up after parsing the microformats: https://gist.github.com/aaronpk/5cb3306d6ba0605b5425

**Comment by snarfed** [comment]
agreed, i ended up coming around to the same conclusion last night. thanks for writing it up, @aaronpk! the tweet and markup example are definitely helpful. plus, i'd like to encourage pure mention handlers to look at content length and show the whole content if it's under a certain size, and this is definitely good ammo for that.

**Comment by kevinmarks** [comment]
I like that answer with the embedded h-cite - I should make my fragmention
auto-linker do that too
http://www.unmung.com/?rawtext=Thus+we+could+turn+a+link+like+this%3A+https%3A%2F%2Fkartikprabhu.com%2Farticle%2Fmarginalia%23In%2520the%2520case%2520of%2520digital%2520content%2C%2520the%2520artifact%2C%2520once%2520created%2520and%2520published%2C%2520is%2520not%2520static.+into+an+inline+embed&maxurllength=0&embed=on

**Comment by kylewm** [comment]
Thinking about what to do with replies to quote tweets. I think we've concluded that quote tweets are basically equivalent to "mentions" (i.e. the same as someone tweeting a link to a post on your site). And so replies to a quote are not considered replies to the original, and will not be backfed.

**Comment by snarfed** [comment]
:+1:

**Comment by kevinmarks** [comment]
Well, they are replies too, except that twitter shows them as top posts. It
doesn't thread them though, so they can be discussion terminating.

**Comment by kylewm** [comment]
one remaining issue: the mentioned link is added to the outer h-entry, but it should really be the u-url of the contained h-cite.

```html
<article class="h-entry">
  this is a quote tweet https://twitter.com/kylewm/1234
  <a class="u-mention-of" href="https://kylewm.com/2015/12/the-thing-being-quoted"></a>
  <article class="h-cite">
    this is the thing being quoted
    <a class="u-url" href="https://twitter.com/kylewm/1234"></a>
  </article>
</article>
```

**Comment by kylewm** [comment]
Deployed... It doesn't seem to have broken anything, but it also doesn't seem to have worked. It's not finding new tweets, e.g. searching for

https://twitter.com/dissolve333/status/677170470152593408

should find 

https://twitter.com/kylewmahan/status/677171403544616960

Here's the query. Confirmed via the API console that Twitter does return that quote tweet. Not sure yet why Bridgy isn't backfeeding it. and now i have to go do Christmas family stuff :(

679698503644352512+OR+677937737186459648+OR+677809810084110336+OR+677172635407634432+OR+677170470152593408+OR+668510418902487040+OR+664964044860686336+OR+664561829201375232+OR+663777396206776322+OR+663008355120758784+OR+662665847509504000+OR+659391428343300096+OR+654295558962720768+OR+652490299374092288+OR+651858246257389568+OR+644705523988889601+OR+644242456846856192+OR+644242104869195780+OR+644241717701378048+OR+644241008432037888

**Comment by snarfed** [comment]
i think that's because bridgy includes `since_id` in its search, so it will only find quote tweets created since the deploy. totally ok with me, fwiw.

**Comment by kylewm** [comment]
Oh good point!

**Comment by kylewm** [comment]
Yay! New quote tweet from me to Ben went through:

```
2015-12-25 15:39:29.495670 I Webmention from https://brid-gy.appspot.com/post/twitter/dissolve333/680412194941476864 to https://ben.thatmustbe.me/note/2015/12/18/1/
```

**Comment by snarfed** [comment]
woo yay congrats! a Christmas miracle! thanks @kylewm! 🏅🎉🎄

**Comment by tantek** [comment]
Re-reading this thread per Bridgy Publish feature request issue 720, note that we have a separate explicit post type for quotation posts, with explicit markup:

https://indieweb.org/quotation#How_to_markup

Not sure if/when/how many people are publishing or consuming, but wanted to at least provide an update here in case we want to consider updating what Bridgy backfeed uses as markup to represent backfed quote tweets.

**Comment by snarfed** [comment]
done! thanks for the nudge.

example updated markup (simplified) from https://brid.gy/post/twitter/dissolve333/680412194941476864 :
```html
<article class="h-entry">
  <a class="u-url" href="https://twitter.com/kylewmahan/status/680412194941476864">...</a>
  ...
  <article class="u-quotation-of h-cite">
    <a class="u-url" href="https://twitter.com/dissolve333/status/677937737186459648">...</a>
    <div class="e-content p-name">
    New reacji UI, backfed reacji from twitter now working, and all likes are now converted to reacji hearts!… (<a href="http://btmb.me/s/Da">btmb.me/s/Da</a>)
    </div>
  ...
  </article>
</article>
```
