### ISSUE TITLE
OPD: handle composite url properties?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#511]
not sure if we actually want to do anything about this or not. @kylewm hopefully you can help triage? low priority.

this example isn't ideal, since it's not an OP of a silo post that we'd backfeed for, but i can imagine a similar case that we would. @rhiaro's ["indie" follow here](http://rhiaro.co.uk/2015/10/1444083305). [poll log](https://www.brid.gy/log?start_time=1445016937&key=aglzfmJyaWQtZ3lyEwsSB1R3aXR0ZXIiBnJoaWFybww) line:

```
unexpected non-string "url" property: {
  'type': ['h-card'],
  'properties': {
    'url': ['https://twitter.com/nicolagreco'],
    'follow-of': ['https://twitter.com/nicolagreco'],
    'name': [u'https://twitter.com/nicolagreco']
  },
  'value': u'https://twitter.com/nicolagreco'
}
```

**Comment by kylewm** [comment]
I haven't seen `<span class="h-card p-url">` before, I'd guuuuuess it was unintentional, and it was meant to be `u-follow-of h-card`?

Still the idea with composite properties is we should be able to use any dict's "value" if we don't want all the complex properties...We could generalize that bit of code to pull out the value instead of warning about unexpected non-string properties.

**Comment by kylewm** [comment]
Huh, there's actually test in Granary's microformats2 tests for compound URLs. Is this something you've encountered before? `"u-url h-*"` doesn't make much sense to me.

```python
  def test_nested_compound_url_object(self):
    mf2 = {'type': ['h-as-share'],
           'properties': {
             'repost-of': [{
               'type': ['h-outer'],
               'properties': {
                 'url': [{
                   'type': ['h-inner'],
                   'properties': {'url': ['http://nested']},
                 }],
               },
             }],
           }}
    obj = microformats2.json_to_object(mf2)
    self.assertEquals('http://nested', obj['object']['url'])
```

**Comment by snarfed** [comment]
we definitely have encountered it before, hence `microformats2.get_string_urls`, but probably during publishing, not OPD...?

maybe check git log?

**Comment by kylewm** [comment]
Ok, we discussed it here https://github.com/snarfed/bridgy/issues/419 and I remember the conversation, I just didn't know the outcome was that we'd support `u-url h-*`, but that's OK with me.

**Comment by snarfed** [comment]
hey @kylewm, remind me, is this falling out of your recent granary work? or should we still do it? or is it obsolete? ...

**Comment by kylewm** [comment]
we should still do it.

really anywhere we expect simple property values, we would ideally accept a dict instead and just pull out the "value". (that said, I don't think anyone has taken mf2 handling code to this extreme yet)

**Comment by snarfed** [comment]
we're hitting this again, this time in propagates for @notenoughneon, https://brid.gy/twitter/notenoughneon. we should probably fix it. :P

```
Propagate task failed
Traceback (most recent call last):
  File "/base/data/home/apps/s~brid-gy/7.392520642131857416/tasks.py", line 475, in send_webmentions
    self.do_send_webmentions()
  File "/base/data/home/apps/s~brid-gy/7.392520642131857416/tasks.py", line 502, in do_send_webmentions
    source_url = self.source_url(target)
  File "/base/data/home/apps/s~brid-gy/7.392520642131857416/tasks.py", line 697, in source_url
    activity = self.activities[0]
IndexError: list index out of range
```

**Comment by snarfed** [comment]
wait, that's something different. never mind!

**Comment by snarfed** [comment]
fwiw, looks like @rhiaro has dropped mf2 from her site, eg on https://rhiaro.co.uk/2015/10/1444083305 and other posts on https://rhiaro.co.uk/

**Comment by snarfed** [comment]
Haven't seen this from anyone else. Tentatively closing.
