### ISSUE TITLE
Facebook response handler 404s and 400s

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#512]
we regularly see small clusters of 404s from facebook like handlers and 400s from comment handlers.

like example: http://brid.gy/facebook/5410052, [bridgy like](https://brid-gy.appspot.com/like/facebook/5410052/10100835608944825/1690795869), [propagate log](https://www.brid.gy/log?start_time=1445073523&key=aglzfmJyaWQtZ3lySQsSCFJlc3BvbnNlIjt0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxMDA4MzU2MDg5NDQ4MjVfbGlrZWRfYnlfMTY5MDc5NTg2OQw), handler log:

```
Fetching facebook:5410052 like ('10100835608944825', '1690795869')
Fetching https://graph.facebook.com/v2.2/5410052_10100835608944825?access_token=CAAD..., kwargs {}
Fetching https://graph.facebook.com/v2.2/10100835608944825?access_token=CAAD..., kwargs {}
```

comment example: https://www.brid.gy/facebook/1490933893, [bridgy comment](https://www.brid.gy/comment/facebook/1490933893/10206946362206137/10206946362206137_10206947523075158), handler log:

```
Fetching facebook:1490933893 comment ('10206946362206137', '10206946362206137_10206947523075158')
Fetching https://graph.facebook.com/v2.2/10206946362206137_10206947523075158?fields=id,message,from,created_time,message_tags,parent&access_token=CAAD..., kwargs {}
Fetching https://graph.facebook.com/v2.2/10206947523075158?fields=id,message,from,created_time,message_tags,parent&access_token=CAAD..., kwargs {}
Error 400, response body: {"error":{"message":"Unsupported get request. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"fbtrace_id":"C0TakC6Ixfd"}}
```

**Comment by snarfed** [comment]
interesting. for at least the last week (and probably more), almost all the comment 400s are for https://www.brid.gy/facebook/1490933893 , and don't seem to be part of the propagate flow. User-Agent `Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)` implies a browser is fetching them, but not sure.

here's the only one i found for a different account: https://www.brid.gy/comment/facebook/548616784/10152991837921785/10152991855376785 :
```
Fetching facebook:548616784 comment ('10152991837921785', '10152991855376785')
Fetching https://graph.facebook.com/v2.2/10152991855376785?fields=id,message,from,created_time,message_tags,parent&access_token=CAAD..., kwargs {}
Error 400, response body: {"error":{"message":"Unsupported get request. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"fbtrace_id":"Eel7b\/9lAsu"}}
```

**Comment by snarfed** [comment]
most of the recent like 404s are also from those two accounts. i had to go back almost a week to find examples from other people...but that probably just reflects posting frequency.

i suspect missing permissions.

https://www.brid.gy/facebook/403320719840728 , https://www.brid.gy/like/facebook/403320719840728/473881392784660/703523556425343 :
```
Fetching facebook:403320719840728 like ('473881392784660', '703523556425343')
Fetching https://graph.facebook.com/v2.2/403320719840728_473881392784660?access_token=CAAD..., kwargs {}
Fetching https://graph.facebook.com/v2.2/473881392784660?access_token=CAAD..., kwargs {}
```

https://www.brid.gy/facebook/1490933893 , https://www.brid.gy/like/facebook/1490933893/10208329876993142/10153565482810288
```
Fetching facebook:1490933893 like ('10208329876993142', '10153565482810288')
Fetching https://graph.facebook.com/v2.2/1490933893_10208329876993142?access_token=CAAD..., kwargs {}
Fetching https://graph.facebook.com/v2.2/10208329876993142?access_token=CAAD..., kwargs {}
```

**Comment by snarfed** [comment]
the like failures may be spurious, or something. example: https://www.brid.gy/like/facebook/5410052/10100835608944825/673915669

```
Fetching facebook:5410052 like ('10100835608944825', '673915669')
Fetching https://graph.facebook.com/v2.2/5410052_10100835608944825?access_token=CAAD..., kwargs {}
Fetching https://graph.facebook.com/v2.2/10100835608944825?access_token=CAAD..., kwargs {}
```

of the 53 likes on that post, https://www.facebook.com/ChrisAldrich/posts/10100835608944825, 51 were successfully backfed to http://boffosocko.com/2015/08/04/little-free-library-8424-adams-hill-branch-grand-opening/ . no clue why it doesn't fetch now. maybe it's too old?

**Comment by snarfed** [comment]
may be fixed, or improved, by the upgrade to api v2.6...?

**Comment by gRegorLove** [comment]
I got a bunch more of these about 19 hours ago.

Samples:
https://brid-gy.appspot.com/like/facebook/27301982/10102325182627444/761900500 (followed by quite a few that were found / processed)
https://brid-gy.appspot.com/like/facebook/27301982/10102322101811424/159101032
https://brid-gy.appspot.com/like/facebook/27301982/10102261890305764/161503044
https://brid-gy.appspot.com/like/facebook/27301982/10102237121352944/630101607
https://brid-gy.appspot.com/react/facebook/27301982/10102322101811424/585812018/10102322101811424_love_by_585812018

Majority were likes, but a few reactions in the mix. Can provide more URLs if needed.

**Comment by snarfed** [comment]
thanks for the report!

honestly, this has been happening for a long time, and i've exhausted most of the debugging paths and workarounds i've come up with. i've been just tolerating it for a while now, especially since most webmention receivers are still synchronous, so they return 4xx when this happens, which makes bridgy retry, so these usually eventually succeed. definitely sad for async wm receivers though.

**Comment by snarfed** [comment]
[Facebook support is dead](https://brid.gy/about#rip-facebook) (#817, #826), so I'm closing this as obsolete. feel free to reopen if you have any concerns!
