### ISSUE TITLE
set up continuous integration

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#519]

**Comment by kylewm** [comment]
Just out of curiosity/ignorance why Circle rather than Travis?

**Comment by snarfed** [comment]
heh, good question. no reason other than i have more experience with it. i have no preference; if you want to try travis, go for it!

**Comment by kylewm** [comment]
I have no clue if Travis can do GAE and a vague impression that I looked into it and it looked difficult so I gave up; so definitely go for what you've used before!

**Comment by snarfed** [comment]
evidently jenkins is another option:
http://googleappengine.blogspot.com/2012/10/jenkins-meet-google-app-engine.html
https://appengine.cloudbees.com/

**Comment by snarfed** [comment]
...scratch that, at least cloudbees. it's $60/mo. :/ https://www.cloudbees.com/pricing/platform

**Comment by kylewm** [comment]
now Jenkins I have some expertise with

**Comment by bear** [comment]
TravisCI has a GAE helper lib that hasn't been made official, but it can be done.
Same with CircleCI, tho it is an official one.

**Comment by snarfed** [comment]
woo, up and running for oauth-dropins!

* https://circleci.com/gh/snarfed/oauth-dropins
* https://github.com/snarfed/oauth-dropins/blob/master/circle.yml
* https://github.com/snarfed/oauth-dropins#readme

**Comment by snarfed** [comment]
woo, up and running for granary, done in snarfed/granary@b29083f0125ae0b74440bb9fb210f21af0c83c42.

* https://circleci.com/gh/snarfed/granary
* https://github.com/snarfed/granary/blob/master/circle.yml
* https://github.com/snarfed/granary#readme

**Comment by bear** [comment]
+1 !!
