### ISSUE TITLE
registering via callback: allow publish, listen in one step

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#522]
If passing the /start route publish,listen it would be nice if both got setup in one step.

**Comment by snarfed** [comment]
hmm! sounds like you're just proposing handling a query param for that, not a full UX? are you thinking this is for the registering with callback flow? are you thinking about implementing that in a new CMS? (just curious!)

for normal users signing up on brid.gy itself, i think i like the current two step process. when you're re-registering, i definitely agree that we should keep publish enabled for you if it already is. #482 and #518 should hopefully do that, even if the UX isn't quite ideal.

let me know if i'm misinterpreting...

**Comment by singpolyma** [comment]
Yes, for registering with callback flow. I'm hoping to write a brid.gy plugin for GNU Social.

**Comment by snarfed** [comment]
oh wow, awesome, that'd be great, thank you! cc'ing @kylewm, he wrote the callback registering support, so hoepfully he can triage and help with any other details.

**Comment by kylewm** [comment]
Good idea. Currently you can pass feature= listen *or* publish but not both; it would be nice to allow a multivalued feature query arg. I'll work on this soon

**Comment by kylewm** [comment]
Hmm, registering for publish is actually a totally different code path (and a different url `/publish/twitter/start` instead of `/twitter/start`). Being able to register both in one fell swoop looks like a much bigger refactoring, of tricky code that I am not very familiar with, than I am willing to bite off right now...

**Comment by snarfed** [comment]
heh, sorry, that's probably misleading. `/publish/twitter/start` is actually for the interactive preview/publish feature, not signup. we do use `/twitter/start` for both listen and publish signup.

**Comment by kylewm** [comment]
Oh! Phew that makes much more sense, thanks!

**Comment by kylewm** [comment]
As of 47fbc87f0c2ba519e06716189bf4d52b47a950f0 you should be able to register with the feature "listen,publish" and get both.
