### ISSUE TITLE
backfeed silo mentions from other people

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#523]
e.g. if someone else tweets 'hey @username foo bar!', we'd send it as a webmention to your web site's front page. same with user mentions/tags on FB, G+, and IG.

similar to #488. inspired by https://github.com/snarfed/bridgy/issues/456#issuecomment-150386830. (thanks @singpolyma!)

**Comment by snarfed** [comment]
current silo support:

* **Twitter: yes**, via search. we [already do this to walk reply chains](https://github.com/snarfed/granary/blob/master/granary/twitter.py#L353).
* **Google+: maybe?** [`activities/search`](https://developers.google.com/+/web/api/rest/latest/activities/search) might work.
* Flickr: TODO
* Facebook: no. Not via notifications: They can only be read [for pages](https://developers.facebook.com/docs/graph-api/reference/page/notifications), [not for users](https://developers.facebook.com/docs/graph-api/reference/user/notifications). A number of other endpoints look promising, but don't pan out. [Google doesn't find much either.](https://www.google.com/search?q=facebook+api+user+mentions) and FB removed search from the API in v2.0 (see #456).
* Instagram: no. [search](https://instagram.com/developer/endpoints/media/#get_media_search) is just for location, not text query.

**Comment by snarfed** [comment]
one wrinkle here if that twitter @-replies usually mention the tweet's author, but they probably shouldn't get backfed to the front page as mentions.

however, if someone mentions you in a reply to someone else, that maybe should get backfed.

here's a straw man: if a mention isn't a reply, backfeed it. if it is, but it's not a reply to you, and if the tweet it's replying to doesn't mention you, backfeed it.

(other silos don't start comments with mentions by default, so they don't have this problem.)

**Comment by singpolyma** [comment]
I'm ok with not doing the backfeed a second time for posts that are a direct reply to you. But I'd also be ok with doing it, since it still mentions you. Either way.

**Comment by snarfed** [comment]
sounds good!

i'm also inclined to suppress mention backfeed when we find an original post link to one of your sites, [e.g. tweets like these](https://adactio.com/journal/9775#comment24279), so that we don't double backfeed those either.

**Comment by snarfed** [comment]
turning this on now. hold onto your britches...

**Comment by snarfed** [comment]
first confirmed kill!
https://brid.gy/twitter/leitmedium#responses
https://twitter.com/nordhessenmami/status/668539086567809025

(their site doesn't accept front page webmentions, but that's fine.)

**Comment by snarfed** [comment]
example of one that did go through: 

https://twitter.com/lucavgobbi/status/668762681000796160
http://www.kevinmarks.com/

(i love how @kevinmarks's use of webmention.herokuapp.com on his front page is kind of a light stress test. :P)

**Comment by dissolve** [comment]
getting these now but they don't actually refer to my URL,  for example
it sent me a webmention of https://brid-gy.appspot.com/post/facebook/14305603/837135243002270 pointing to https://ben.thatmustbe.me/
but my homepage URL is missing from the generated page
