### ISSUE TITLE
registration "API" does not pass permission scopes

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#526]
Discovered a major bug in the registration hook when used with Facebook -- the permission scopes are only defined in the templates facebook_user.html and facebook_signup.html, which means that the mini-registration-API doesn't pass scopes to OAuth (unless they are explicitly listed in the registration form on the third party site, which they aren't for Known). Not sure how I missed this for so long. :/

Instagram, Facebook, and Google+ all get "scope" via the html.

I need to either: 
1. update the documentation to tell callers to include scope in their call to Bridgy, 
2. or remove the scopes from the html forms and add them programmatically in custom StartHandlers for each service based on the selected features.

I'm not terribly excited about either option but I think I'd prefer the second. What do you think?

**Comment by kylewm** [comment]
Sigh, also the documentation tells users to post to `/service/start` with `feature=publish` to enable publishing -- that's wrong -- it needs to be changed to `/publish/service/start`

**Comment by snarfed** [comment]
good find, at least! and sad oauth flows are harder to comprehensively unit test than other code.

I've been wading through this past of the codebase recently too, for #482 and #518. i actually think option 2 might not be so bad, and i think i need to do qpart of it for #482 anyway. I'll take a look and get back to you,

**Comment by kylewm** [comment]
And confirmed that permission scopes are being passed via the Known integration, phew
