### ISSUE TITLE
Can't fetch pages from my site?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#529]
https://brid.gy/log?start_time=1445869672&key=aglzfmJyaWQtZ3lylgELEg1QdWJsaXNoZWRQYWdlIm9odHRwczovL3Npbmdwb2x5bWEubmV0L2FjdGlvbnN0cmVhbS9ydC1odHRwc3R3aXR0ZXItY29tbW9kc3VwZXJzdGFyc3RhdHVzZXM2NTg2NDEwMTE0NjQzODg2MDgtbW9kc3VwZXJzdGFyLW1heS8MCxIHUHVibGlzaBiAgICAgOSRCgw

tried manually and got same error. that page loads fine for me

**Comment by singpolyma** [comment]
My server logs show me returning 200s for these requests.

**Comment by singpolyma** [comment]
Maybe related to https://github.com/snarfed/bridgy/commit/19e66acf9c648163d1879b94583f3448eaf1733d -- wordpress doesn't return a content-length header, but the code doesn't seem to require one and my pages aren't big.  not sure...

**Comment by kylewm** [comment]
You're correct, it is a problem with the Content-Length check. I'm on it.

**Comment by snarfed** [comment]
thanks for the quick fix @kylewm, and sorry for the breakage @singpolyma!

**Comment by snarfed** [comment]
that log also shows that we're not populating the `Content-Length` response error message correctly. i'll fix that.

```
Starting new HTTPS connection (1): singpolyma.net
"GET /actionstream/rt-httpstwitter-commodsuperstarstatuses658641011464388608-modsuperstar-may/ HTTP/1.1" 200 None
Could not fetch source URL https://singpolyma.net/actionstream/rt-httpstwitter-commodsuperstarstatuses658641011464388608-modsuperstar-may/
Traceback (most recent call last):
File "/base/data/home/apps/s~brid-gy/7.388086954427067927/webmention.py", line 65, in fetch_mf2
  fetched.raise_for_status()
File "/base/data/home/apps/s~brid-gy/7.388086954427067927/local/lib/python2.7/site-packages/requests/models.py", line 765, in raise_for_status
  raise HTTPError(http_error_msg, response=self)
HTTPError: 599 Server Error: OK
```

**Comment by kylewm** [comment]
599: This is fine

![this-is-fine](https://cloud.githubusercontent.com/assets/950127/10736304/72cc0512-7bc9-11e5-9c18-b96ce217519c.png)
