### ISSUE TITLE
Duplicate webmention for domain with different capitalization

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy#531]
This is minor and quite an edge case, seemingly due to my odd, stylized capitalization. :) [This backfeed](https://brid-gy.appspot.com/like/twitter/gRegorLove/659185668900294660/718713474) contains my target URL twice, once with the domain lowercase and once with my stylized capitalization, so I received two webmentions. 

I don't think this has happened with [other likes](https://brid-gy.appspot.com/like/twitter/gRegorLove/659079707942481920/121468302). I'm guessing it's because I included the backlink (lowercase) in the first one, and Bridgy is using my domain (capitalized) from Twitter to complete the permalink from my feed.

**Comment by snarfed** [comment]
interesting! thanks for the report. you're right, path and query params are case sensitive, but domain names aren't, and we're probably not handling that right.

i take it you also don't de-dupe? :P http://gregorlove.com/2015/10/ive-added-event-posts-to/ totally up to you, of course. we'll still fix this!

this was also a fun 5-minute nerd snipe: modern unicode domain names are case insensitive just like old school ascii domain names.

* http://unicode.org/faq/idn.html#6
* https://tools.ietf.org/html/rfc4343#section-5

**Comment by gRegorLove** [comment]
I de-dupe, but not properly apparently. :) My primary key for a webmention is md5(source, target). I think I'll fix it by using the target path instead of full URL.
