### ISSUE TITLE
Flickr malformed JSON response

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#537]
We get intermittent bad responses to some requests to the Flickr API. It looks like every once in a while, it will return XML for a JSON request. There doesn't seem to be any particular pattern to when it occurs

E.g.,

```
Fetching https://api.flickr.com/services/rest?photo_id=21957885785&nojsoncallback=1&method=flickr.photos.comments.getList&format=json

malformed flickr response: <?xml version="1.0" encoding="utf-8" ?>
<rsp stat="ok">
<set_ids id="72157660747719192" />
<created_now />
</rsp>
```

```
Fetching https://api.flickr.com/services/rest?photo_id=21957849815&nojsoncallback=1&method=flickr.photos.comments.getList&format=json

malformed flickr response: <?xml version="1.0" encoding="utf-8" ?>
<rsp stat="fail">
	<err code="3" msg="Set not found" />
</rsp>
```

**Comment by snarfed** [comment]
as @aaronpk says, _silos gonna silo_

**Comment by kylewm** [comment]
I think downgrading to a warning is really all that can be done here. Fixed in https://github.com/snarfed/oauth-dropins/commit/a817d21061848c90b1022ec93116567abed8942e

**Comment by snarfed** [comment]
'+1: thanks for the forensics!
