### ISSUE TITLE
refetch h-feed button and visible timestamps

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#538]
the 2 hour OPD (refetch h-feed) cycle is a bit arbitrary and opaque. the retry buttons currently reset and retry almost every part of handling a response *except* OPD. it'd be nice for users debugging their syndication links or bridgy bugs :) :( if we had an explicit "refetch" button...or maybe even better, do it as part of the retry button. maybe with a buffer on the order of 1m-2m.

related: #524, #183, #536, etc.

**Comment by kylewm** [comment]
Similarly: At a quick glance it looked to me like 'retry' resends the webmention based on the stored Response. It would be awesome if it fetched the response again from the silo first, in case the user has updated it with backlinks.

**Comment by snarfed** [comment]
agreed! briefly discussed in https://github.com/snarfed/bridgy/issues/524#issuecomment-151382270 . i decided against it because i think it'd introduce a fair amount of complexity. i'd happily look at a PR that adds it, but i can't guarantee i'd like it. :P

**Comment by snarfed** [comment]
we should probably also show per site timestamps on user pages for last fetch, last syndication URL found for that specific silo, and maybe also last webmention sen successfully sent.

**Comment by snarfed** [comment]
ugh, UI. i have no idea how we should lay out all that new info for each profile URL.

**Comment by snarfed** [comment]
another idea: add `polling` to `Source.status` and show it on the user page.

**Comment by snarfed** [comment]
hey @kylewm, I'm debating the UX for what should trigger refetching h-feed: poll now button or retry response button (implemented now). got an opinion?

**Comment by kylewm** [comment]
can it be both? :smiling_imp: I think 'retry' makes a little more sense, since it's a signal from the user that "hey something didn't work, please try harder".

**Comment by snarfed** [comment]
sgtm!

**Comment by tantek** [comment]
Just as the "Polled ... Next poll in ..." line has a [ Poll now ] button, 

the "Web site crawled ... ago." line should have a [ Crawl now ] button.

**Comment by snarfed** [comment]
yeah, that's reasonable. reopening.
