### ISSUE TITLE
extract_links cuts off trailing hyphen

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#541]
Original post discovery for https://www.facebook.com/photo.php?fbid=1091808337510617 cut off too early, eliding the trailing hyphen

```
>>> import util
>>> util.extract_links("""Tambourcorps Polos  =)
...
... Haben wir jetzt auch endlich alle wieder Polos. War auch Zeit!!
...
... Original: http://broxxer.de/2015/tambourcorps-polos-""")
['http://broxxer.de/2015/tambourcorps-polos']
```

Bridgy found the hyphen version via posse-post discovery, and the non-hyphen version via regular link extraction, here's the user page https://brid.gy/facebook/1014855791872539

This is pretty edge-casey. Don't know if it's worth fixing.

**Comment by snarfed** [comment]
wow, nice find. and yeah, definitely edge casey. i don't know if it's worth fixing either. definitely worth capturing at least, thanks!

**Comment by snarfed** [comment]
hmm. i think this might be the same bug as #399. @kylewm does that look right?

**Comment by kylewm** [comment]
Definitely looks like a duplicate!

**Comment by snarfed** [comment]
thanks!
