### ISSUE TITLE
Tag silo profile URLs in Webmentions

### ISSUE THREAD

**Issue by paulcmal** [snarfed/bridgy#543]
Related to [Idno/Known #1097](https://github.com/idno/Known/issues/1097): Webmention avatars are (re-)stored every time

Bridgy's webmentions seem to return as author URL (h-card > p-name) whatever is provided by the user on their silo's profile.

The URL to the user's profile on the silo is also provided, but is not tagged as such ([for example](https://brid-gy.appspot.com/repost/twitter/cmal_PP/663394802965340160/663394856782471168)).

I would suggest to systematically add a tag (such as *silo-url*) to the u-url corresponding to the profile on the silo (whether it's the p-name or not).

**Comment by kylewm** [comment]
Just to clear up a little misunderstanding -- `p-name` is unrelated. It happens to live on the same tag as `u-url` in the example above but it's not tagging the url as something special. It's just a parsing directive saying that the person's name is the text content of the &lt;a> tag. i.e., in the parsed output, `name=["Jeunes Pirates"]`, and `url=["http://www.jeunespirates.fr", "https://twitter.com/jeunespirates"]`

In general, I think this is solvable without special-casing Bridgy or adding Bridgy-specific markup. Indieweb-to-indieweb webmentions have the same issue with avatars that might change content while being served from a fixed URL... Our solution should support that use case too.

**Comment by snarfed** [comment]
@paulcmal thanks again for filing! looks like most of the action on this is in idno/Known#1097, and i think kyle addressed your concerns for bridgy specifically...? let me know if not, otherwise i'll close this issue.
