### ISSUE TITLE
publish should propagate photo person-tags to Twitter as an inline shorthand

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#547]
This is a follow-on from Issue #459 for a specific use-case.

When POSSEing a photo post to Twitter, Bridgy Publish should detect person-tags in the original, and then put them as the very last thing in the tweet text (before the original post link), preceded by a line-break.

This makes sense from a design / adjacency perspective, since Twitter photo posts put the photo _after_ the tweet text, and thus in reading the tweet, one will see:
- first the tweet text (as much as will fit) 
- then ellipsis "…" if necessary for what doesn't fit from the tweet text
- then the person-tags downlevel support as described below
- then "(originalPostLink)" - assuming no opt-out of it per usual

Proposed person-tags downlevel tweet text support examples:

E.g. person-tagging two people with @-names and one with only their own domain (not on Twitter)

```
👤 @exampleperson p2.example.net @exampleorg
```

And if that one person lacks a domain or @-name, then just their given name:

```
👤 @exampleperson Person2givenname @exampleorg
```

Note that the person-tag tweet text fallback should be preceded by a line break so that the "👤" starts the line, which will make it look much more like a line of metadata about the photo rather than part of the preceding content text.

Details of the derivation of this proposed person-tag tweet-text fallback here:
- https://indiewebcamp.com/person-tag#tweet_text (scroll-up as needed)

To be clear this feature is _only_ requested for _photo_ posts to Twitter, since only Twitter's photo posts have their own person-tags (plain text tweets lack person-tags, thus no need to clutter them with something unfamiliar to Twitter users).

**Comment by kylewm** [comment]
This seems like a good fallback given the API limitations :+1:

**Comment by snarfed** [comment]
huh. from a product/UX perspective, i have to admit i'm not convinced. it seems like this could be an unwelcome surprise to users:

* we'd only do it for tweets with pictures. we'd continue to ignore person tags when publishing non-photo tweets and to other silos.
* twitter has actual person tags, but the person tags don't end up as first class twitter person tags.
* person tags could quickly eat into the valuable 140 char real estate and shorten the text too drastically.

the last is (reasonable) speculation, but the inconsistencies in the first two are real. if we were to do this, i wonder if we should do it for all tweets and silos, for consistency. worth thinking about more.

**Comment by kylewm** [comment]
> twitter has actual first class person tags, so users would expect we'd use them (not knowing that we can't). instead, we'd do something different and unusual.

Agree, but also if a lot of people started using 👤, it's a signal to Twitter "hey we'd use this feature if you supported it" (like @KevinMarks's emoji reactions, which seemed ... particularly effective)

It'd also be important not to duplicate the person's tag if they are @-mentioned in the body of the post.

> person tags could quickly eat into the valuable 140 char real estate and shorten the text too drastically.

I convinced myself that this wasn't a big deal because the text that accompanies a photo is usually short and/or less important compared to the photo itself. I definitely wouldn't be OK with losing a bunch of characters from note posts

**Comment by kevinmarks** [comment]
I person tag speakers in noterlive.com html generation. I don't in the tweets I make, just @ mention them

**Comment by snarfed** [comment]
looking at this another way: bridgy is big enough now that it may not the right place to experiment with unusual new designs, patterns, and techniques. it may be more appropriate for individual sites to try out this kind of thing, see how it works, iterate, and then we add it to bridgy once it's stabilized and there's a bit more of a consensus.

**Comment by kylewm** [comment]
That I agree with. Bridgy Publish should be a lagging indicator -- adopt conventions based on what people are doing with their own sites, not set new conventions.

**Comment by tantek** [comment]
Agreed in general with a lot of this analysis, especially with personal site experimentation first. Planning on it. :)

Some updates:
* For more than 3 person-tags:
<blockquote>👤 @exampleperson @exampleorg …</blockquote>
* Put original post link at the end as usual in Bridgy (easier, more consistent, makes more sense in the abbreviated person-tag text case).

Continuing to iterate on design thinking here:  https://indiewebcamp.com/person-tag#tweet_text

**Comment by tantek** [comment]
In continuing to iterate on the brainstorming of how to POSSE person-tags to Twitter, especially from in-content UI vs a separate explicit UI, I am discovering even more complexity in "doing it well".

Thus while I'd like to leave this as an open issue for Bridgy (my intuition is still that there exists a simple/elegant/predictable solution that Bridgy could adopt), for now the burden of simplicity / implementability falls on some sort of indieweb site version.

**Comment by snarfed** [comment]
very related to #527. somewhat related to #765, #761, etc.

**Comment by snarfed** [comment]
it's been 3y, and we haven't really started doing this at all in the indieweb community. tentatively closing. feel free to reopen if/when we do!
