### ISSUE TITLE
Automatic publish via webmention expects www. URL

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#549]
At least I think that's the problem.

@rhiaro discovered/was bitten by a bug where embedding `<a href="https://brid.gy/publish/twitter"></a>` in the body of her post would return "Couldn't find link to https://www.brid.gy/publish/twitter"

This bit of code in WebmentionHandler

```python
    if util.domain_from_link(self.request.host_url) == 'brid.gy':
      # also accept www
      bases.add(self.request.host_url.replace('brid.gy', 'www.brid.gy'))
```

attempts to augment the host_url with the www-version, bu if the host_url *is* the www-version, then we're in trouble.

And based on the line in the access log, I think that's exactly what's happening 

```[18/Nov/2015:20:08:44 -0800] "POST /publish/webmention HTTP/1.1" 400 159 - - "www.brid.gy" ms=8599 cpu_ms=1207 cpm_usd=0.000098 app_engine_release=1.9.29 instance=00c61b117c03113d8f5308746a4a3bb3cccc5732```

**Comment by snarfed** [comment]
ugh, absolutely right. thanks for the forensics! and yeah that code is too clever (and therefore too brittle) by half. blame me and fa2f603ec29fda8b3c552b10f4875c98fcec2326. easy to fix at least!
