### ISSUE TITLE
Format permalink differently when only posting a title

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#553]
When POSSE to Twitter, bri.gy uses just the title if there is one.  This is great behaviour for my long-form posts.  brid.gy currently formats the link at the end of the tweet the same way, though, as a parenthetical.  Since my followers are pretty used to that link not being a continuation unless there's an ellipse, it can be confusing.  I propose that if using a title (maybe "if use a title that is different/shorter than the content" or "if I have a title and also content" since if I have both assumedly I intend both to be consumed by humans) the tweet have a slightly different format:

    <title>: <permalink>

**Comment by kylewm** [comment]
Totally agree with this... &lt;self-serving-suggestion>I vote I add it to [brevity](https://github.com/kylewm/brevity/) and then have Bridgy use brevity&lt;/self-serving-suggestion>

Also when publishing a note longer than 140 characters, I'd like to keep the ellipsis but lose the parentheses. e.g., 


```
Wow, fascinating article. Always impressed when someone has the strength to break away from a cult… I really… https://kylewm.com/2015/11/wow-fa...
```
instead of 

```
Wow, fascinating article. Always impressed when someone has the strength to break away from a cult… I really… (https://kylewm.com/2015/11/wow-fa...)
```

**Comment by snarfed** [comment]
this all sgtm. I'm a bit wary of punctuation changes like this since they can devolve into bikeshedding and/or making it user configurable. these specific changes don't seem like those, though, and do seem like the right idea.
