### ISSUE TITLE
Include title (if present) when POSSE to Facebook

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#554]
Currently, brid.gy ignores any title when POSSE to Facebook.  My titles are often a useful part of the post.  They could be included simply as the first line of the post (followed by a blank line).

**Comment by snarfed** [comment]
:+1:

**Comment by singpolyma** [comment]
https://github.com/singpolyma/granary/tree/title-to-facebook solves this, but is dependant on the resolution of https://github.com/snarfed/granary/issues/60

**Comment by snarfed** [comment]
hey @singpolyma, any interest in pushing through a PR from your title-to-facebook branch for this now that snarfed/granary#60 is done?
