### ISSUE TITLE
Allow publishing reposts to silos the original is not from

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#555]
For example, I often want to POSSE my "retweets" to Facebook, even though the original is not on Facebook.  Right now I get a "Facebook publishing doesn't support shares" error, but since for a repost the entire original content is in my post anyway, it would be nice if the whole content just went through as if it weren't a repost (currently I do this manually).

**Comment by snarfed** [comment]
definitely! i think this is basically #362, except for reposts. same root cause. shall we merge them?

**Comment by singpolyma** [comment]
Sure. Makes sense
