### ISSUE TITLE
Receiving Bridgy mentions of friends-only comments left on Facebook

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy#559]
These all appear to be homepage mentions, too, which is new. They're just general FB comments friends have left on my wall.

https://brid-gy.appspot.com/post/facebook/27301982/10100833139693444
https://brid-gy.appspot.com/post/facebook/27301982/10101343900699294
https://brid-gy.appspot.com/post/facebook/27301982/10101423973512734
https://brid-gy.appspot.com/post/facebook/27301982/10101423501403844
https://brid-gy.appspot.com/post/facebook/27301982/10101215007457384
https://brid-gy.appspot.com/post/facebook/27301982/10101204455523544

**Comment by snarfed** [comment]
side effect of #523

**Comment by snarfed** [comment]
[@dissolve sees a related issue](https://github.com/snarfed/bridgy/issues/523#issuecomment-159057189):

> getting these now but they don't actually refer to my URL, for example
> it sent me a webmention of https://brid-gy.appspot.com/post/facebook/14305603/837135243002270 pointing to https://ben.thatmustbe.me/
> but my homepage URL is missing from the generated pagegetting these now but they don't actually refer to my URL, for example
> it sent me a webmention of https://brid-gy.appspot.com/post/facebook/14305603/837135243002270 pointing to https://ben.thatmustbe.me/
> but my homepage URL is missing from the generated page

**Comment by gRegorLove** [comment]
I got a couple that don't include gregorlove.com as well:

https://brid-gy.appspot.com/post/facebook/27301982/10101215013949374
https://brid-gy.appspot.com/post/facebook/27301982/10101215007457384

**Comment by snarfed** [comment]
facebook actually doesn't tell us that these posts are friends-only. :( [e.g. the creed one has blanks for all of the `privacy` fields](https://developers.facebook.com/tools/explorer?method=GET&path=27301982_10100833139693444&version=v2.2) (you'll need an access token): 

```json
  "privacy": {
    "allow": "",
    "deny": "",
    "description": "",
    "friends": "",
    "value": ""
  },
```

same result if we fetch it with `?fields=privacy`.

[the docs don't say what the default is in this case.](https://developers.facebook.com/docs/graph-api/reference/v2.2/post#fields) :/

this may mean that it inherit's from the user's default? not sure. looking.

**Comment by snarfed** [comment]
[evidently this is expected.](http://stackoverflow.com/a/25621114/186123)

> Not sure this is your case, but if the user is posting to a page, event, group or another users's feed, the privacy field is expected to be empty.

i haven't found any more details, or anywhere to get the user's default privacy setting for wall posts, either googling or in FB's docs. :/

**Comment by snarfed** [comment]
i may have to default to being conservative and never backfeed any wall posts. for my own notes, FB wall post objects have `"status_type": "wall_post"`.

**Comment by kylewm** [comment]
I think this comes from each user's settings, and can't be changed per-post

![who-can-see](https://cloud.githubusercontent.com/assets/950127/11402123/0d29d830-934b-11e5-8b4c-1c0ff4c46597.png)

**Comment by snarfed** [comment]
@kylewm right, thanks! sadly i haven't found a way to get that from the API. eg i don't see anything on https://developers.facebook.com/docs/graph-api/reference/v2.2/user or nearby. :/

**Comment by kylewm** [comment]
Yeah, I didn't see anything either. Requesting with the security_settings field didn't give back anything useful.

**Comment by snarfed** [comment]
done. thanks again for the report @gRegorLove, @dissolve. please let us know if you see any more of these!
