### ISSUE TITLE
publish: let users provide exact silo post text in param/mf2 class

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#560]
[originally proposed here](https://github.com/snarfed/bridgy/issues/527#issuecomment-158547898):

 > what if we support custom new webmention query params and/or mf2 classes that clients can use to give us the exact text they want to publish for a specific silo? that would relieve the pressure for complex transformations like this. sophisticated users/CMSes could use their own rich UI to craft this, then send it to us and we'd post it verbatim. unsophisticated users could keep using our existing translation. it would also let CMSes keep reusing our silo API implementations instead of doing it themselves, which i'm definitely for.

**Comment by kylewm** [comment]
:clap: very innnnnteresting

**Comment by snarfed** [comment]
"Beware of bugs in the above code; I have only proved it correct, not tried it."

**Comment by kylewm** [comment]
if you have a post that embeds the brid.gy/publish/twitter link but hasn't been published yet (say on a site that embeds the link on every page for convenience) ... is there anything to prevent someone from sending a webmention with the `&bridgy-twitter-content= ` parameter set to whatever they want?

**Comment by snarfed** [comment]
ooh, great catch! there absolutely is not; that's a huge hole.

the simple fix is just to drop the query param entirely, which I'm ok with, unless you can think of a safe way to keep it...?
