### ISSUE TITLE
publish: option to include a link only when content > 140 chars

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#561]
Many who POSSE notes to twitter include a link to the original *only* when the note is more than 140 characters (me, aaronpk, Known by default, according to https://indiewebcamp.com/posse-post-discovery), but Bridgy does not support this style -- `bridgy_omit_link` is all or nothing.

My ideal would be to just change the interpretation of `bridgy_omit_link=true` to "omit the link iff the post is <= 140 characters". But I can also understand that sometimes including a link even when you said to omit it might be surprising for some.  What about as a compromise adding support for a third option `bridgy_omit_link=conditional`?

(Ryan discussed this with me on IRC, but I wanted to have an issue for tracking/possible elaboration)

**Comment by snarfed** [comment]
thanks for filing!

yeah, i do think disobeying `bridgy_omit_link` could be an unpleasant surprised, and i'm not excited about adding another option, but i'm not sure what else to do. this may fall under "keep bridgy publish dumb," but i don't know. thoughts?

**Comment by kylewm** [comment]
Oh sorry, I closed it right before you commented. I was being all "someone is wrong on the internet" last night, but in the clear light of day I don't want to bikeshed this issue :)

**Comment by snarfed** [comment]
lol fair. i actually came back to it to say this one specifically seems like a common enough desire that it might be worth the option, or maybe a new `maybe` value for the existing option? i think that'd be just a few lines? I'd be happy to see that go in if you want to do it!

**Comment by kylewm** [comment]
> or maybe a new maybe value for the existing option?

speaking of bikesheds, I like "conditional" a little better than "maybe" (maybe makes it sound like it'd include the link randomly)

**Comment by snarfed** [comment]
`bridgy_omit_link=totally-up-to-you-of-course-im-fine-either-way` :P

**Comment by singpolyma** [comment]
Seems like this could be done by just using omit link, or not, at the publisher according to whatever criteria you want (length, etc)

**Comment by kylewm** [comment]
@singpolyma sure if you're willing to count the tweet's characters and determine whether it will be truncated or not. but there are a lot of edge cases in the way twitter recognizes urls and how many characters they count for (see https://github.com/kylewm/brevity-testcases/blob/92438a3399f9327db48ef15e5e8df78e6e60221b/tests.json if you're curious)

**Comment by snarfed** [comment]
reopening! i probably wouldn't implement this myself any time soon, since it's not an itch for me personally and also because https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb , but i'd be opening to merging a PR.

**Comment by kylewm** [comment]
Assuming it's still OK for me to merge the brevity change on granary, I think adding "maybe" would be a 1-2 line change + documentation ... which I would be thrilled to do.

**Comment by snarfed** [comment]
sure, sgtm! looking at snarfed/granary#59, i think I'd vote to keep the tests, but otherwise it lgtm.

**Comment by kylewm** [comment]
I'm planning to make the `omit_link` object a string equal to one of "true", "false", "maybe".

Currently we interpret `?bridgy_omit_link` or `?bridgy_omit_link=true` or the presence of a `u-bridgy-omit-link` property (regardless of value) to all mean true.

I'm planning to only support "maybe" via the query param `?bridgy_omit_link=maybe`. For now there won't be any way to set "maybe" in the HTML (we could do something like this, but it seems ugly to me:

```html
<data class="p-bridgy-omit-link" value="maybe">
</data>
```
)

**Comment by snarfed** [comment]
ok! I'm actually fine with handling the mf2 too. rsvps are data elements that accept more than `yes` and `no` values, so there's precedent, right?

another alternative is a new boolean param... but i think i like this better.
