### ISSUE TITLE
cron job to update flickr profile pictures?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#566]
looks like we might need one? e.g. https://brid.gy/flickr/97484212@N00 . cc @kylewm.

the existing ones for instagram and twitter (unused) are in [`cron.py`](https://github.com/snarfed/bridgy/blob/master/cron.py).

**Comment by kylewm** [comment]
Oh thanks for the heads up. I think I missed a bit of documentation for finding buddyicons https://www.flickr.com/services/api/misc.buddyicons.html

> If the icon server *is greater than zero*, the url takes the following format:
>
> http://farm{icon-farm}.staticflickr.com/{icon-server}/buddyicons/{nsid}.jpg
>
> else the following url should be used:
>
> https://www.flickr.com/images/buddyicon.gif

Apparently icon-server=0 means the user doesn't have an icon.

**Comment by snarfed** [comment]
aha, got it. if those urls are definitely evergreen, then agreed, switching to that should be enough, no need for a cron job.

**Comment by kylewm** [comment]
ok actually it looks like they can change too, so we do need a cron job.

ref https://www.flickr.com/groups/51035612836@N01/discuss/72157631745985010/

**Comment by kylewm** [comment]
fixed in 

bde94b6c11aeab6cd575717f4a2ee4226bff649a
and
https://github.com/snarfed/granary/commit/845afbbd521f7ba43b3339bcc1ce3afddd205047
