### ISSUE TITLE
tweet mentions my username and a url, only generates webmention to my website-root

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#570]
i understand, that bridgy handles mentions as a webmention to my website root (@diplix → webmention to wirres.net). but in this case, there’s also an article-url mentioned, which doesn’t get a mention sent to, but IMHO should:

* https://twitter.com/dasnuf/status/675309443601588224
* https://brid-gy.appspot.com/post/twitter/diplix/675309443601588224
* [log](https://brid.gy/log?start_time=1449841891&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo2NzUzMDk0NDM2MDE1ODgyMjQM)

(i did send a manual webmention to my page, which of course worked, because the [bridgy proxy page](https://brid-gy.appspot.com/post/twitter/diplix/675309443601588224) is just fine.)

<img width="1148" alt="bildschirmfoto 2015-12-11 um 15 05 14" src="https://cloud.githubusercontent.com/assets/4541494/11745511/fb706ca0-a018-11e5-944e-d97dca463239.png">

**Comment by snarfed** [comment]
huh, you're absolutely right. thanks for reporting this!

**Comment by snarfed** [comment]
found by this poll: https://brid.gy/log?start_time=1449841378&key=aglzfmJyaWQtZ3lyEwsSB1R3aXR0ZXIiBmRpcGxpeAw

**Comment by snarfed** [comment]
current theory: we found this post via both @-mention search and link search, we do original post discovery differently for each, the @-mention won, and its OPD ignored the link. not sure why yet.

**Comment by snarfed** [comment]
thanks again for reporting this @diplix! subtle bug. i'm glad it's fixed now.

**Comment by diplix** [comment]
tnx!
