### ISSUE TITLE
 Bridgy Publish to Facebook: detect u-video and post video

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#573]
Similar to Bridgy Publish to Facebook u-photo support, Bridgy Publish to Facebook should (before photos) try to detect u-video and if found, post a video to Facebook.

Test post where I'll be trying this (has u-video markup)

http://tantek.com/2015/346/t3/world-of-laughter-tears-hopes-fears

(actually tried to trick Bridgy Publish with u-photo and that was rejected by the silo API calls)

**Comment by snarfed** [comment]
:+1: yes!

**Comment by snarfed** [comment]
one big open question is whether we can post a video by giving the API its URL, like we currently do for photos, or whether we need to upload the file ourselves. [the docs say](https://developers.facebook.com/docs/graph-api/reference/user/videos/#Creating) POSTing to `/user/video` accepts a `file_url` param, but they also say the `source` param, which takes the video data as form-encoded, is required. ¯\\\_(ツ)\_/¯

it we have to upload the video, that makes this tricky. [details.](https://github.com/snarfed/bridgy/issues/574#issuecomment-164595296)

**Comment by snarfed** [comment]
never mind. [streaming upload is evidently very straightforward.](https://github.com/snarfed/bridgy/issues/574#issuecomment-164599872)
