### ISSUE TITLE
Facebook comments linked to wrong post

### ISSUE THREAD

**Issue by beck24** [snarfed/bridgy#575]
![screen shot 2015-12-17 at 8 43 11 am](https://cloud.githubusercontent.com/assets/738363/11875586/44b83b88-a49a-11e5-829f-a87a9b5a7147.png)

Comments from this post (FB: https://www.facebook.com/photo.php?fbid=1080330665330686 original: http://known.mattbeckett.me/2015/day-17-devilish-demands)

Are showing up on this post: http://known.mattbeckett.me/2015/new-plugin-elgg-copy

I don't think it's the same issue as before (where the photos are grouped) as the elgg_copy plugin post isn't an image post and is from 23 days ago.

**Comment by beck24** [comment]
![screen shot 2015-12-17 at 8 50 57 am](https://cloud.githubusercontent.com/assets/738363/11875862/a0345694-a49b-11e5-87cf-221a24894ecf.png)

These last few pictures did get grouped into one of those statuses, but it doesn't include the plugin post
https://www.facebook.com/matt.beckett.39/timeline/story?ut=43&wstart=0&wend=1451635199&hash=-4645984981838288132&pagefilter=3

(doesn't appear to be available while logged out despite all photos being public, shoot me a friend request if it helps)

![screen shot 2015-12-17 at 8 58 20 am](https://cloud.githubusercontent.com/assets/738363/11876057/87aef574-a49c-11e5-9669-cffafdabdcf2.png)
![screen shot 2015-12-17 at 8 58 53 am](https://cloud.githubusercontent.com/assets/738363/11876056/87ae9732-a49c-11e5-90b9-c1fc9b0254e9.png)

Actually it looks like some (but not all comments) from each of the grouped pictures ended up on the plugin post.

**Comment by snarfed** [comment]
ugh, thanks for letting me know. and sorry this keeps happening. :/

looking at https://brid.gy/facebook/948590525171368 , it looks like we started sending them to the right post ~5h ago. we cache the mapping between facebook post objects and photo objects, so i suspect we had an old mapping cached. still badly wrong, given that the elgg post isn't a photo at all, so that part is still confusing. definitely worth investigating more!

**Comment by snarfed** [comment]
hey @beck24, have you seen this happen on any more posts recently?

**Comment by beck24** [comment]
Last occurrence I see is from a week ago: http://known.mattbeckett.me/2015/day-21-update-2#comments

Those comments belong to this post: http://known.mattbeckett.me/2015/day-21-scene-se7en

Since then it seems comments haven't been coming through, or are inconsistent...

http://known.mattbeckett.me/2015/day-22-baited-baddies#comments

![screen shot 2015-12-28 at 10 40 36 am](https://cloud.githubusercontent.com/assets/738363/12023564/8b59cda0-ad4f-11e5-9056-3321633b99b8.png)

http://known.mattbeckett.me/2015/day-22-update---mystery-solved#comments

![screen shot 2015-12-28 at 10 40 15 am](https://cloud.githubusercontent.com/assets/738363/12023563/8b560c9c-ad4f-11e5-9c43-7690148d47c4.png)

**Comment by beck24** [comment]
@snarfed sorry to bring you some bad news...

The comments here: http://known.mattbeckett.me/2016/john-scott-on-his-road-to-the-all-star-game#comments

Belong here: http://known.mattbeckett.me/2016/a-new-level-of-stupid#comments

**Comment by snarfed** [comment]
damn. sorry! bad news indeed. thanks for letting us know.

**Comment by beck24** [comment]
ok, this is getting confusing.

http://known.mattbeckett.me/2016/i-have-named-my-website-many-fine-books-so-now#comments

Has comments from this post:
![screen shot 2016-02-06 at 1 46 40 am](https://cloud.githubusercontent.com/assets/738363/12866010/857cc7f0-cc73-11e5-8438-bd64735dcecd.png)

They have nothing in common, were posted over 24 hrs apart, only the one post is syndicated.  The one about my kids is also set to privacy:friends so those comments shouldn't have been pushed anywhere.

**Comment by snarfed** [comment]
I'm so sorry this is still happening to you, Matt, and especially with non-public posts and comments! that's definitely not OK, and obviously not what we want.

i haven't made much more progress on finding the root cause yet, nor have i found anyone else who's seeing the same bug. I'll definitely keep looking, though. wish me luck.

**Comment by beck24** [comment]
Yeah I don't know.  I guess it's good in a way that I'm the only one, but I'm not sure why I'm the only one.  I don't think I'm doing anything out of the ordinary with it, it's pretty much a stock known installation with a couple of custom display/analytics plugins, but nothing that even touches syndication.
I do hope you can find something though, good luck :)

**Comment by snarfed** [comment]
links:
* [source](https://console.developers.google.com/datastore/entities/edit?project=brid-gy&kind=FacebookPage&queryType=gql&key=0%2F|12%2FFacebookPage|20%2Fname:948590525171368&gql=) and [auth](https://console.developers.google.com/datastore/entities/edit?project=brid-gy&kind=FacebookAuth&queryType=gql&key=0%2F|12%2FFacebookAuth|20%2Fname:948590525171368&gql=) datastore entities
* [recent `Response` datastore entities](https://console.developers.google.com/datastore/entities/query?kind=Response&project=brid-gy&ns=&queryType=kind&filter=6%2Fsource|KEY|EQ|38%2FKey%28%27FacebookPage%27,%20%27948590525171368%27%29&sortCol=updated&sortDir=DESCENDING)
* [FB public post](https://www.facebook.com/948625878501166/posts/1109803145716771)
* [FB public post in FB API explorer](https://developers.facebook.com/tools/explorer/?method=GET&path=948590525171368_1109129219117497&version=v2.2)
* [FB comment on private post](https://www.facebook.com/948590525171368/posts/1109129219117497?comment_id=1109286935768392)
* [private post in FB API explorer](https://developers.facebook.com/tools/explorer/?method=GET&path=948590525171368_1109129219117497&version=v2.2)
* [bridgy handler for FB private comment (400s)](https://brid.gy/comment/facebook/948590525171368/1109129219117497/1109286935768392)

[private comment `Response.response_json`](https://console.developers.google.com/datastore/entities/edit?key=0%2F|8%2FResponse|60%2Fname:tag:facebook.com,2013:1109129219117497_1109286935768392&project=brid-gy&ns=&kind=Response&filter=6%2Fsource|KEY|EQ|38%2FKey%28%27FacebookPage%27,%20%27948590525171368%27%29&sortCol=updated&sortDir=DESCENDING&queryType=kind):
```json
{
  "objectType": "comment",
  "id": "tag:facebook.com,2013:1109129219117497_1109286935768392",
  "published": "2016-02-05T06:34:11+00:00",
  "content": "...",
  "fb_id": "1109129219117497_1109286935768392",
  "url": "https:\/\/www.facebook.com\/1109129219117497?comment_id=1109286935768392",
  "author": {
    "objectType": "person",
    "id": "tag:facebook.com,2013:1028054227212961",
    "image": {
      "url": "https:\/\/graph.facebook.com\/v2.2\/1028054227212961\/picture?type=large"
    },
    "url": "https:\/\/www.facebook.com\/1028054227212961",
    "displayName": "...",
    "numeric_id": "1028054227212961"
  },
  "inReplyTo": [
    {
      "id": "tag:facebook.com,2013:1109129219117497",
      "url": "https:\/\/www.facebook.com\/1109129219117497"
    }
  ]
}
```

[...and `Response.activities_json`](https://console.developers.google.com/datastore/entities/edit?key=0%2F|8%2FResponse|60%2Fname:tag:facebook.com,2013:1109129219117497_1109286935768392&project=brid-gy&ns=&kind=Response&filter=6%2Fsource|KEY|EQ|38%2FKey%28%27FacebookPage%27,%20%27948590525171368%27%29&sortCol=updated&sortDir=DESCENDING&queryType=kind):
```json
[{
  "id": "tag:facebook.com,2013:1109803145716771",
  "fb_id": "948590525171368_1109803145716771",
  "object": {
    "content": "I have named my website 'many fine books'. So now I can be referenced as 'Matt Beckett - developer, scuba diver, and author of many fine books'.\n\n(known.mattbeckett.me\/s\/3Vl2R)"
  },
  "url": "https:\/\/www.facebook.com\/948590525171368\/posts\/1109803145716771"
}]
```

**Comment by snarfed** [comment]
notable: both the public and private FB posts are simple status updates. neither has photo(s) or a link. so this probably isn't our post <=> photo object mapping after all.

**Comment by snarfed** [comment]
we currently check that posts and respones are public in poll and propagate, but not in the mf2 handlers. checking there too would be a good safeguard to add. it wouldn't fix the root cause bug, but it would  at least prevent backfeeding non-public responses.

...the catch is that FB doesn't actually include the `privacy` field in many individual response objects, eg comments. you have to fetch the parent post/object and use its value instead. we already do this for photos/albums, https://github.com/snarfed/bridgy/issues/559#issuecomment-159642227, so it might still be worthwhile.

**Comment by snarfed** [comment]
btw, for the record, i do expect this bug is hitting other people too. i just haven't heard from or found any of them yet.

**Comment by snarfed** [comment]
interesting. the `Response` key name `tag:facebook.com,2013:1109129219117497_1109286935768392` uses the private post's id, but `Response.activities_json` is the public post.

**Comment by snarfed** [comment]
phew, i think i found it. we make multiple FB API calls to get all of the different kinds of posts and responses, and then do some bookkeeping to match responses with their posts. as our FB API code grew and evolved organically, that bookkeeping didn't entirely keep up, so in some cases it was attaching responses to the wrong posts.

thanks again for your patience and persistenc, @beck24! this was an ugly bug, so i'm glad it's (hopefully!) fixed. i'll keep this issue open for a while until we're confident it's gone.

**Comment by beck24** [comment]
Awesome, thanks for digging deep on it.
I'll keep you posted if anything else comes up, but I'm looking forward to things just ending up in the right places :)
