### ISSUE TITLE
crash in instagram poll

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#577]
...for https://brid.gy/instagram/kylewm2. not sure why yet. i suspect it got disabled and we didn't handle that well.

```
14:46:25.327 Source: kylewm2 (Instagram) kylewm2, http://brid-gy.appspot.com/instagram/kylewm2
14:46:25.327 Last poll: http://brid-gy.appspot.com/log?start_time=1450302270&key=aglzfmJyaWQtZ3lyFgsSCUluc3RhZ3JhbSIHa3lsZXdtMgw
14:46:25.417 suspended generator transaction(context.py:1019) raised AttributeError('NoneType' object has no attribute 'updates')
14:46:25.418 'NoneType' object has no attribute 'updates'
Traceback (most recent call last):
...
  File "/base/data/home/apps/s~brid-gy/7.389352778280538223/tasks.py", line 83, in post
    source = models.Source.put_updates(source)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/utils.py", line 194, in inner_wrapper
    return wrapped_decorator(func, args, kwds, **options)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 3830, in transactional
    func, args, kwds, **options).get_result()
...
  File "/base/data/home/apps/s~brid-gy/7.389352778280538223/models.py", line 215, in put_updates
    source.updates = updates  # because FacebookPage._pre_put_hook uses it
AttributeError: 'NoneType' object has no attribute 'updates'
```

**Comment by snarfed** [comment]
wow, i do not understand this. `source. key.get()` at [`models.py:214`](https://github.com/snarfed/bridgy/blob/master/models.py#L214) is evidently returning `None`, but we got `source`from that same key earlier, at [`tasks.py:61`](https://github.com/snarfed/bridgy/blob/master/tasks.py#L61). and this same crash has happened at least twice, ie not just once after the entity was deleted. (I'm guessing it wasn't.)

@kylewm, any idea what's up with this source? :P

**Comment by snarfed** [comment]
ah, you did delete it. :P https://appengine.google.com/adminlogs?&app_id=s~brid-gy

**Comment by kylewm** [comment]
Dang sorry that's my fault again. I deleted the Instagram account and the Twitter account for kyle_wm via the appengine console (because I don't have those usernames anymore and couldn't disable them the right way). I don't understand how the page https://brid.gy/instagram/kylewm2 still works :confused:  It's not in the user list anymore https://brid.gy/users?start_name=Kyle

**Comment by snarfed** [comment]
lol, np! ndb's memcache key format is `NDB9:[string key]`. in this case it's https://console.developers.google.com/appengine/memcache?entry=NDB9:aglzfmJyaWQtZ3lyFgsSCUluc3RhZ3JhbSIHa3lsZXdtMgw&project=brid-gy . deleted, looks ok! and it looks like the twitter account is already gone from memcache. https://brid.gy/twitter/kyle_wm
