### ISSUE TITLE
optimize app engine frontend instance count

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#578]
we average ~2 app engine frontend instances right now, and they cost money (at least above the first), so i've been experimenting with different tuning knobs to see if i can get that average down a bit. this isn't high priority, and i'm also not sure i can have much impact without making drastic changes, so this is mostly just for tracking.

directly related:
* #90 figure out why requests aren't running concurrently (enough)
* #110 optimize poll task

loosely related:
* #8 find an alternative to the resident backend for twitter streaming
* #53 get backend memory usage below cap
* #145 cache in instance memory as well as memcache
* #300 try dedicated memcache

here are a few things i've tried recently, and the results. tl;dr: none of them had a meaningful effect on instance count.
* 12/17 12:20pm: 30m fast poll frequency, poll concurrency 2
* 12/18  7:21am: 15m fast poll frequency, concurrency 1
* 12/18 10:40am: 15m fast poll frequency, poll concurrency 10

<img width="1178" alt="screen shot 2015-12-18 at 3 13 24 pm" src="https://cloud.githubusercontent.com/assets/778068/11909317/fa6b7b7a-a599-11e5-9eef-2404eb48afba.png">

<img width="1176" alt="screen shot 2015-12-18 at 3 13 41 pm" src="https://cloud.githubusercontent.com/assets/778068/11909328/2287576e-a59a-11e5-9571-fbfa35557e84.png">

**Comment by snarfed** [comment]
the really annoying part is that we don't actually need more than one instance, but app engine's scheduler doesn't handle us well, and it *thinks* we do, so it usually keeps two or three around. from https://console.developers.google.com/appengine/instances?project=brid-gy&moduleId=default&versionId=7&duration=P1D :

<img width="784" alt="screen shot 2016-02-02 at 2 48 04 pm" src="https://cloud.githubusercontent.com/assets/778068/12767327/5e7ae5e6-c9bd-11e5-833c-4e65c7679102.png">

this is the norm. one instance serves almost all of the requests; the remaining instance(s) serve almost none.

details on how app engine's request scheduler/auto scaler works:
* https://cloud.google.com/appengine/docs/python/scaling#scaling_dynamic_instances
* https://cloud.google.com/appengine/docs/python/console/managing-resources#change_auto_scaling_performance_settings

@kylewm and i talked a bit on IRC just now on profiling. our request volume is mostly poll and propagate ([~87% and ~9% each, respectively](https://console.developers.google.com/appengine?project=brid-gy&moduleId=default&versionId=7&duration=P1D)), both of which i expect spend most of their time blocked on network I/O. good idea to check, though. [app stats](https://cloud.google.com/appengine/docs/python/tools/appstats) is great for that; we can [turn it on here](https://github.com/snarfed/bridgy/blob/master/appengine_config.py#L37).

the poll task queue is currently configured to run up to 2 at a time, propagate up to 1 at a time, and we have [`threadsafe: yes` in our app.yaml](https://github.com/snarfed/bridgy/blob/master/app.yaml#L4) to allow instances to serve multiple requests concurrently. last time i checked [with bridgy's instance info recording](https://github.com/snarfed/bridgy/blob/master/appengine_config.py#L42), this was indeed happening.

**Comment by snarfed** [comment]
for reference, [here's bridgy's lifetime cost history](https://snarfed.org/2015-12-07_bridgy-stats-update#comment-2596759):

![costs](https://cloud.githubusercontent.com/assets/778068/12768105/4da515e8-c9c2-11e5-9636-963af7def758.png)

**Comment by snarfed** [comment]
tried another experiment: removed `max_concurrent_requests: 4` from the poll queue and let it run as many as once as it wanted. part of the motivation was to let backlogs clear faster and avoid telling users "next poll in 1m" for long periods of time, but also a (weak) hypothesis was that running more polls simultaneously would better utilize instances.

<img width="1167" alt="screen shot 2016-02-11 at 9 50 33 am" src="https://cloud.githubusercontent.com/assets/778068/12984914/ef9e2fea-d0a4-11e5-9cf7-d30df1004779.png">

in practice, it didn't clearly help or hurt. i flipped the switch feb 10 ~11am. the main difference i see is that our active instance count was more jagged and variable because we weren't throttling polls (and thus load).

i also don't know why feb 9 evening averaged so low, but afaik it wasn't due to anything we did.

**Comment by snarfed** [comment]
oh, right, requests were unusually slow feb 9 evening, i suspect due to one of the silo APIs having issues and being slow itself. not sure why that would drop our average instance count, but it is the one clear correlation.

<img width="1183" alt="screen shot 2016-02-11 at 9 55 17 am" src="https://cloud.githubusercontent.com/assets/778068/12985120/c7f5ecfc-d0a5-11e5-8fe1-f8edf0d2fde4.png">

**Comment by snarfed** [comment]
i started experimenting with this again yesterday. coincidentally, poll latency also spiked a bit *before* i started experimenting, and has stayed pretty high.

<img width="1159" alt="latency" src="https://cloud.githubusercontent.com/assets/778068/13184912/6a9a7ce0-d6f3-11e5-899b-c1dabb1880d1.png">

the only change i made that could have caused that was deploying #620 and snarfed/granary@74aed5c7025d75e93dd59b959537023f50cae6be, both of which really seem unrelated. maybe i accidentally deployed a different version of some libraries in my virtualenv? (although [deploy.sh](https://github.com/snarfed/bridgy/blob/master/scripts/deploy.sh) should have caught that?) maybe some bad new interaction in app engine 1.9.33? i don't know. :(

**Comment by snarfed** [comment]
anecdotally, it seems like the cause might be slower HTTP fetches during OPD. i looked at a few poll logs and saw a number of >10s requests when fetching different people's web pages. :(

**Comment by snarfed** [comment]
here are the experiment results, even if they're tainted by the high latency.

![all](https://cloud.githubusercontent.com/assets/778068/13194979/8c4427a4-d759-11e5-813e-5eacf2044527.png)

the magic single-instance period starting at 10am was the first time woth `min_idle_instances=0, max_idle_instances=1`, but the poll queue was caught up when that started, which i suspect mattered. otherwise, unclear.

**Comment by snarfed** [comment]
latency is slowly maybe getting back to normal.

<img width="1160" alt="screen shot 2016-02-20 at 10 19 28 pm" src="https://cloud.githubusercontent.com/assets/778068/13201313/1709debc-d820-11e5-9546-c6ffea54da13.png">

**Comment by snarfed** [comment]
well that's a pleasant surprise.

![instances](https://cloud.githubusercontent.com/assets/778068/13203741/f50f0adc-d872-11e5-8478-b34a56784a18.png)

**Comment by snarfed** [comment]
definitely promising. looks like we may be able to hold sustain ~1.5 instances on average. we'll see.

<img width="1145" alt="screen shot 2016-02-23 at 9 23 32 am" src="https://cloud.githubusercontent.com/assets/778068/13260150/27e2b060-da0f-11e5-92c0-7fde902c77c4.png">

**Comment by snarfed** [comment]
seeing substantial poll latency spikes again. anecdotally, it looks like many of the long requests are doing OPD refetch. filed #624 to optimize.

**Comment by kylewm** [comment]
huh, there's weird big gaps between RPCs. Not sure if that's the process being asleep, or if it's actually doing something processor intensive in that time.

![pollling-profile](https://cloud.githubusercontent.com/assets/950127/13346565/02e2de2a-dc1c-11e5-887c-d9262732205c.png)

here's another one

![another-profile](https://cloud.githubusercontent.com/assets/950127/13346624/633bd5e2-dc1c-11e5-8348-48931e142ca4.png)

**Comment by snarfed** [comment]
whoa, those are big gaps indeed.15-25s?! i mean, I'm sure some of our compute is inefficient, but not *that* inefficient.

i guess we could try to repro it in dev_appserver, refetching a local web server, and comment out parts of the code in the gap and binary search down until we isolate it. maybe tedious, but could work.

**Comment by snarfed** [comment]
maybe it's context switching to other requests in other threads? hard to believe though. i'd think it should be doing that *during* the API calls, and i'd also hope no self respecting scheduler would starve a thread for 20s at a time.

maybe worth searching/asking on SO or https://groups.google.com/forum/m/#!forum/google-appengine ?

**Comment by kylewm** [comment]
I found one where the spacing is much more regular
![screenshot from 2016-02-26 07-55-32](https://cloud.githubusercontent.com/assets/950127/13358323/9b81820c-dc63-11e5-8ff8-16203015ed3a.png)

After adding some more debug output, I'm finding that mf2 parsing regularly takes longer than the fetch itself


```
D 2016-02-26 16:24:34.896 fetching post permalink https://cmal.info/2016/online-legal-publishers-squabble-over-the-right-to-copyright-the
D 2016-02-26 16:24:35.248 done fetching. now parsing post for mf2 https://cmal.info/2016/online-legal-publishers-squabble-over-the-right-to-copyright-the
D 2016-02-26 16:24:36.749 done parsing https://cmal.info/2016/online-legal-publishers-squabble-over-the-right-to-copyright-the
```

That's 350ms for fetching, 1500ms for parsing!

**Comment by snarfed** [comment]
hoooooly crap, really?!? that's...not OK.

also profiling++ obviously. thanks for doing this!

i wonder if switching HTML parsers would help? i guess it's time to cpu profile mf2py.

**Comment by kylewm** [comment]
Just doing some basic dumb testing now locally. Lxml doesn't seem significantly faster :(

On February 26, 2016 8:56:26 AM PST, Ryan Barrett <notifications@github.com> wrote:
>hoooooly crap, really?!? that's...not OK.
>
>also profiling++ obviously. thanks for doing this!
>
>i wonder if switching HTML parsers would help? i guess it's time to cpu
>profile mf2py.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/snarfed/bridgy/issues/578#issuecomment-189369978

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kylewm** [comment]
Huh, actually html5lib uses lxml if lxml is installed. And it's a hell of a lot faster with it installed (but still slow)

**Comment by kylewm** [comment]
I'm at a loss for speeding up mf2. And making the fetches asynchronous is moot when so much more time is spent processing the result. 

Your suggestion to encourage people to post syndication links in their h-feed, and then limit our fetches when we know they do, seems like the only way forward.

I'd honestly be open to deprecating the deep fetch behavior altogether, _requiring_ syndication links in the h-feed.

**Comment by snarfed** [comment]
whoa, they added a "Billed instances estimate" (green) to the instances graph, and it's noticeably below the total instance count (blue), which is what i thought they were charging for. nice!

<img width="1195" alt="screen shot 2016-03-01 at 9 46 09 pm" src="https://cloud.githubusercontent.com/assets/778068/13451788/2ee7abc0-dff7-11e5-9ec3-39a24a26e832.png">

**Comment by snarfed** [comment]
...hmm. oddly the billed instances estimate is sometimes *higher* than the total instance count. confusing. 🤔
<img width="1177" alt="screen shot 2016-03-02 at 9 59 44 am" src="https://cloud.githubusercontent.com/assets/778068/13469935/536ed1a0-e05e-11e5-835a-b5518cc75455.png">

**Comment by snarfed** [comment]
we get Twitter favorites by fetching and scraping html for each tweet, in serial. i thought parallelizing these with async utlfetch could be a big win, but i looked at ~10 Twitter polls anecdotally, and most didn't fetch any favorites HTML pages, and the rest only fetched one. looks like our caching logic is working. yay. measure first then optimize, and all that!

**Comment by snarfed** [comment]
we've been back on `min_idle_instances: 0, max_idle_instances: 1` for a few days now, and it definitely does cut down instance count, but anecdotally it also hurts interactive latency pretty badly. :/ (cc @tantek @aaronpk.)

as an experiment,  i dropped `max_idle_instances: 1` and kept `min_idle_instances: 0` to see if that helps latency while still keeping some of the instance count improvement. we'll see.

**Comment by snarfed** [comment]
ok so https://cloud.google.com/trace/docs/analysis-reports is pretty great. aggregated latency reports for any subset of URL, HTTP method, etc.

here are some comparing default auto scaling to `min_indle_instances: 0`. default is better latency, as suspected, but it doesn't look like a huge difference. maybe i'm reading the graphs wrong? not sure.

`/` (home page):
<img width="1006" alt="homepage" src="https://cloud.githubusercontent.com/assets/778068/13760176/001aee4a-e9ef-11e5-84fa-4fb29d5124df.png">

`/twitter/*` (user pages):
<img width="1011" alt="twitter_user" src="https://cloud.githubusercontent.com/assets/778068/13760191/16faae70-e9ef-11e5-9a73-716102895177.png">

`/like/*` (mf2 handlers):
<img width="1015" alt="like" src="https://cloud.githubusercontent.com/assets/778068/13760201/2709b05e-e9ef-11e5-8b08-924d10f84c57.png">

poll and propagate are also interesting but less meaningful. we only really care about fine grained latency for interactive pages and mf2 handlers.

poll:
<img width="1003" alt="poll" src="https://cloud.githubusercontent.com/assets/778068/13760223/42e5100c-e9ef-11e5-9d77-e69b63c3e1f9.png">

propagate:
<img width="989" alt="propagate" src="https://cloud.githubusercontent.com/assets/778068/13760231/490c4536-e9ef-11e5-9ca0-7d1a43da027c.png">

**Comment by snarfed** [comment]
interesting data point: anecdotally, when i've glanced at the poll queue over the last week or so, it's often idle or only running one poll. i think it used to consistently be running 4-8 at any given time. so, that implies #624 is largely done.

_...however,_ with the default auto-scaling options, we still hang out at two instances most of the time. so, either app engine's auto scaling just still doesn't handle our workload well (very possible), or there's a lot of load we're missing.

here's some back of the envelope math: we avg .3qps right now, ie ~26k requests per day. over the last 24h, we've had ~16k polls, ~2k propagates, and a handful of front page, retry, publish, propagate-blogpost, etc...but nowhere near the remaining 8k. i'm going to look at logs now to see what those were. they might be bots, in which case i can add user pages to robots.txt...

**Comment by snarfed** [comment]
look at the last week, the remaining 8k qpd average out to approximately:
* 1200 WordPress (every fetch is repeated 3x :( )
* 624: http://airbornesurfer.com crawling a bunch of his twitter and FB mf2 handlers. :/
* 525: [Domain Re-Animator Bot](http://domainreanimator.com) (will blacklist)
* 500 static
* 400 Known (conveniently exactly 1/3 of WordPress :P)
* 304 [X-ray](http://xray.p3k.io/)
* 82 Bridgy (what the?)
* 60 Googlebot (of which 2/3 are the home page)
* 53 Yahoo
* 40 bingbot

searching for all bots (ie `\*[Bb]ot\*`) shows ~930 qpd, which is totally reasonable (if very inexact).

**Comment by kylewm** [comment]
hmm, I know airbornesurfer IRL, sort of doubt he knows that's happening (he should just be on the vanilla wordpress plugin)

**Comment by kylewm** [comment]
> 1200 WordPress (every fetch is repeated 3x :( )

micro-caching might help?

**Comment by snarfed** [comment]
yeah i guess that'd be #15. (that issue number tho! :P)

also i pinged airbornesurfer: https://twitter.com/schnarfed/status/709519485795840001

**Comment by snarfed** [comment]
more importantly, 1200 qpd is <1qpm, and those requests average 1-2s, so i don't think that's really our problem. same with all the other requests in that breakdown.

i think app engine's auto scaling just really doesn't like our workload. _if_ we can convince ourselves that `min_idle_instances: 0` doesn't really hurt latency too much - which i'm not at all sure of - i vote to leave that on and call it a day.

**Comment by snarfed** [comment]
go home billed instance estimate ur drunk
<img width="496" alt="billed" src="https://cloud.githubusercontent.com/assets/778068/13931393/59cdfa6a-ef60-11e5-8bec-c19b967ef24c.png">

**Comment by snarfed** [comment]
so after tons of work and soul searching and waffling, i think all the optimization here was nice and appreciated, but really the one thing that did the trick all by itself was `max_idle_instances: 1`. whee. :P

<img width="1144" alt="screen shot 2016-03-29 at 3 31 37 pm" src="https://cloud.githubusercontent.com/assets/778068/14126039/659ef6aa-f5c3-11e5-97da-bb2ee28ab83f.png">

tentatively closing for now.

**Comment by snarfed** [comment]
incidentally, wow, billed instance estimate really does just get totally drunk sometimes. no clue why. funny.

<img width="871" alt="screen shot 2016-03-30 at 9 44 56 am" src="https://cloud.githubusercontent.com/assets/778068/14150079/2b045942-f65c-11e5-9ea4-ecdb7ad5c08d.png">

**Comment by snarfed** [comment]
weird new instance scaling pattern recently. i haven't found that it corresponds to anything yet (request volume, cron jobs, backups, etc).

<img width="1170" alt="screen shot 2016-05-08 at 9 06 34 am" src="https://cloud.githubusercontent.com/assets/778068/15098859/3324af8c-14fc-11e6-9df7-e1f8b4884d8d.png">

for reference, we got billed for 38 instance hrs on 5/6, 39 on 5/5, and 40 on 5/4, ie much closer to the blue line than the yellow _Billed instance estimate_. boo.

**Comment by snarfed** [comment]
the weird pattern continues. silly. at least the instance hours they're billing us ends up pretty close to the estimate (yellow) instead of the total (blue).

<img width="1152" alt="screen shot 2016-05-31 at 9 56 57 am" src="https://cloud.githubusercontent.com/assets/778068/15683244/311c3936-2716-11e6-967d-40430598c208.png">

**Comment by snarfed** [comment]
weird pattern is gone, more or less.

<img width="1155" alt="screen shot 2017-01-08 at 4 16 42 pm" src="https://cloud.githubusercontent.com/assets/778068/21754874/e3da4dd2-d5bd-11e6-88c8-fc62bf1d9179.png">

**Comment by snarfed** [comment]
the granary/o-d python 3 migration bumped up our instance count for some reason, not sure why except that maybe python-future adds meaningfully more overhead?

this moves task queue and cron processing into a separate 'background' service. this decouples quick, light user-facing requests (front page, user pages, etc) from heavier background tasks (poll, propagate, etc), which makes more sense app engine's scheduler. it now runs the frontend 'default' service on ~1.5 instances avg, and lets me control the 'background' service's instances more directly with manual or basic scaling.

(i'd include instance count graphs, but they're buggy right now and the console isn't showing them. :/ )

background:
https://cloud.google.com/appengine/docs/standard/python/an-overview-of-app-engine
https://cloud.google.com/appengine/docs/standard/python/modules/converting
https://cloud.google.com/appengine/docs/standard/python/config/appref#basic_scaling
https://cloud.google.com/appengine/docs/standard/python/config/appref#manual_scaling

**Comment by snarfed** [comment]
now that facebook is dead (#826 #817), i tried an experiment to see if a single frontend instance could serve both interactive requests and poll/propagate tasks. i disabled the dedicated `background` service and moved task queues back to targeting the frontend (`default`) service.

turns out...no. even if a single frontend instance may theoretically be enough to handle the load, app engine's scheduler still just doesn't like serving two very differently shaped workloads from the same service. it served on 3-4 instances on average, and billed us for 2-3.

i flipped the switch 8/16 1pm PST. background service requests:

<img width="1125" alt="screen shot 2018-08-18 at 4 05 04 pm" src="https://user-images.githubusercontent.com/778068/44303859-9a5e5100-a300-11e8-9561-feb375912460.png">

frontend service:

<img width="1144" alt="screen shot 2018-08-18 at 3 58 06 pm" src="https://user-images.githubusercontent.com/778068/44303862-a6e2a980-a300-11e8-9beb-bdc93df6f3a1.png">

frontend instances:

<img width="1136" alt="screen shot 2018-08-18 at 4 04 40 pm" src="https://user-images.githubusercontent.com/778068/44303865-b19d3e80-a300-11e8-9071-eaa03c5b4aae.png">

cost:

<img width="746" alt="screen shot 2018-08-18 at 3 55 26 pm" src="https://user-images.githubusercontent.com/778068/44303866-b4982f00-a300-11e8-817f-1241b6894b35.png">

ah well. it was worth a shot. turning on the dedicated background service now.

**Comment by snarfed** [comment]
zooming out...costs of running bridgy, granary, indie map, etc over the last two and a half years:

![project_costs](https://user-images.githubusercontent.com/778068/59940659-2608a880-9410-11e9-8e01-0afc1d7e555e.png)
