### ISSUE TITLE
Get mentions to older posts

### ISSUE THREAD

**Issue by marcthiele** [snarfed/bridgy#579]
Hey there,

It would be fantastic to get bridgy to look even for older posts, if you start using it. Automatically would be fantastic, but I can see the overhead here with big blogs or websites. Therefore a manual way to let bridgy trigger a certain url and time would be fantastic.

Cheers,

/marc

**Comment by snarfed** [comment]
thanks for filing!

the example here was https://brid.gy/twitter/btconf , which signed up on 12/14, and hoped to backfeed everything on https://twitter.com/btconf/status/664389870492717056 (posted on 11/11) to http://beyondtellerrand.com/blog/wrap-up-ber2015 .

some IRC discussion with @kevinmarks and aaronpk:
> KevinMarks: if you tweet a link to it, does bridgy decide to look again?
> snarfed: KevinMarks: the new tweet, yes, but not the old tweet with the responses he wants
> KevinMarks: ah, right
> aaronpk: snarfed: do you think it'd be simple enough to make a field you could put in a link to an old post and bridgy would go check it?
> snarfed: aaronpk: honestly, no. :/ it's not really designed for that mode
>   i mean, it's obviously doable, but nontrivial
> aaronpk: it wouldn't require extra backend infrastructure would it?
> snarfed: i'm not sure
> aaronpk: I don't really know how the queueing system works but I would imagine it might be as simple as putting a new job onto the queue the same way it does when it finds a new post
> snarfed: aaronpk: yeah, i understand the idea. the problem is that most of the work happens *before* then, in creating the job to enqueue
> aaronpk: ah
> snarfed: mostly since that job is per response, not per post, since posts regularly get new responses
>   if you want to look, it'd basically be generalizing the poll method here to handle a single silo post as well as the current "grab everything" mode: https://github.com/snarfed/bridgy/blob/master/tasks.py#L108

**Comment by tantek** [comment]
One possible UI for this would be a form like: "Original permalink: _______________ (Recrawl)" where the user/author could enter a permalink to an original post on their site, and have Bridgy recrawl *that* for u-syndication URLs, and then check its DB for all webmentions it attempted for those u-syndication URLs that failed (e.g. "No webmention targets") and resend them all.

**Comment by amandarush** [comment]
While I can definitely understand how non-trivial a feature like this would be, it would definitely be useful. When resending webmentions while using a screen reader, every time you resend, the focus changes because the page refreshes to reflect the new activity, so there's no way to pick up where you left off.

**Comment by snarfed** [comment]
done! feel free to try it on your user page. thanks for the suggestions all!
