### ISSUE TITLE
Tweet went out without link back to my site

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#580]
https://brid.gy/log?start_time=1450898212&key=aglzfmJyaWQtZ3lyZAsSDVB1Ymxpc2hlZFBhZ2UiPWh0dHA6Ly93ZWJlci50ZWFtY2hhZC5vcmcvMjAxNS8xMi9jaHJpc3RtYXMtZ3JlZXRpbmdzLXRoYW5rcy8MCxIHUHVibGlzaBiAgICAgK6ZCgw

Tweet being deleted now, but it had just the title and no permalink...

**Comment by kylewm** [comment]
It looks like the webmention that triggered publishing was sent with the parameter `bridgy_omit_link` https://brid.gy/about#omit-link

If bridgy_omit_link is either "true" or "", it is interpreted as true

**Comment by singpolyma** [comment]
interesting.  I cut-n-paste from the UI, which always includes it as "" IME

**Comment by kylewm** [comment]
oh that's bad, nice catch!

**Comment by snarfed** [comment]
thanks for the catch @singpolyma!
