### ISSUE TITLE
publish multi-photo posts

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#583]
indieweb details in https://indiewebcamp.com/multi-photo. just a normal post with multiple `u-photo`s.

twitter looks straightforward, we just need to [upload the photos in separate API calls](https://dev.twitter.com/rest/public/uploading-media) and then port to [`/statuses/update`](https://dev.twitter.com/rest/reference/post/statuses/update). (we currently use [`/statuses/update_with_media`](https://dev.twitter.com/rest/reference/post/statuses/update_with_media), which is deprecated and evidently only supports one photo anyway: [`/help/configuration`](https://dev.twitter.com/rest/reference/get/help/configuration) returns `"max_media_per_upload": 1`.)

facebook is less obvious. https://developers.facebook.com/docs/graph-api/reference/v2.2/user/photos#Creating says:
 > There is no way to publish more then one photo in the same graph API call.

...and SO agrees:
* http://stackoverflow.com/questions/21355785/facebook-graph-api-posting-multiple-photos
* http://stackoverflow.com/questions/15891692/facebook-graph-api-post-multiple-photos-to-album-and-feed

the one workaround people mention is using [Custom Stories aka Open Graph Stories](https://developers.facebook.com/docs/sharing/opengraph), which support a [multi-valued `image` param](https://developers.facebook.com/docs/sharing/opengraph/using-actions#photos)...but custom stories [seem to be dying](http://marketingland.com/quick-death-facebook-kills-open-graph-collections-developers-72973) and [deprioritized in news feed ranking](http://www.theverge.com/2014/5/27/5754862/facebook-gives-up-on-automatically-sharing-everything-you-do-online-open-graph) (related: https://github.com/snarfed/bridgy/issues/479#issuecomment-166383558), so i'm reluctant to use them.

the other approach that would probably work is to create a new album for each post...but that seems...undesirable. :P

**Comment by snarfed** [comment]
cc @kartikprabhu @tantek

**Comment by kartikprabhu** [comment]
@snarfed I don't POSSE to FB so I have no opinion on that. Twitter would be nice yes!

**Comment by tantek** [comment]
Instagram FYI now supports multi-photo posts. While they still lack an API for posting, I wanted to drop this comment in here for search result purposes, in case there's ever an IG posting API.
