### ISSUE TITLE
posse-post-discovery doesn't find nested h-feed

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#584]
I don't think posse-post-discovery is finding @tantek's h-entrys. I suspect this is because he nests his h-feed inside a top-level h-card.

**Comment by snarfed** [comment]
true! i see `No h-feed found, fallback to top-level h-entrys.` in his [poll log](https://brid.gy/log?start_time=1451542682&key=aglzfmJyaWQtZ3lyDgsSB1R3aXR0ZXIiAXQM).
