### ISSUE TITLE
bridgy can't publish my replies anymore?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#585]
https://brid.gy/log?start_time=1451578438&key=aglzfmJyaWQtZ3lyjQELEg1QdWJsaXNoZWRQYWdlImZodHRwczovL3Npbmdwb2x5bWEubmV0L2FjdGlvbnN0cmVhbS9yZXBseS1odHRwc3R3aXR0ZXItY29tYmFsbGV5bmVzdGF0dXM2ODIzNzk1OTg2NjM5NTg1MjgtYmFsbGV5bmUtYS8MCxIHUHVibGlzaBiAgICAgOSRCgw

**Comment by snarfed** [comment]
huh. sorry about that! maybe related to changes for #583 i deployed yesterday?

**Comment by singpolyma** [comment]
seems to be complaining because the post contains an hcard...

**Comment by kylewm** [comment]
I think the relevant line from the log is:

```
2015-12-31 16:13:58.099280 I Object type(s) set(['h-entry', 'in-reply-to']) not supported; error=Cannot publish type=comment, verb=None to Twitter; trying next.
```

**Comment by snarfed** [comment]
fixed and deployed. thanks for diagnosing @kylewm!
