### ISSUE TITLE
fix auth for facebook page publish

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#588]
interactive publish for facebook pages doesn't work right now. bridgy wants you to log in as the page, but facebook wants you to log in as yourself. whee.

thanks to @belp-audio for reporting!

**Comment by Belp-audio** [comment]
You're most welcome... Looking forward when this gets fixed. But take your time, it's all awesome already anyways. Thanks for all the wonderful work, really appreciate it.

**Comment by snarfed** [comment]
background on our FB page support in #41.

**Comment by snarfed** [comment]
...ooh, we actually have `publish_pages`! i didn't realize. that's nice. https://developers.facebook.com/apps/256884317673197/review-status/#js_2
