### ISSUE TITLE
Receiving invalid mentions

### ISSUE THREAD

**Issue by voxpelli** [snarfed/bridgy#589]
Just took a look in the logs of my endpoint and discovered a couple if pings from Bridgy that couldn't be validated:

https://brid-gy.appspot.com/comment/twitter/sil/683634417869402112/683637152077508608 didn't link to http://www.kryogenix.org/ as claimed
https://brid-gy.appspot.com/comment/twitter/krisshaffer/682293054905139200/682293897247199233 didn't link to http://kris.shaffermusic.com/ as claimed
https://brid-gy.appspot.com/comment/twitter/kevinmarks/683180563528826880/683182377514975232 didn't link to http://www.kevinmarks.com/ as claimed

There's a couple of more examples for each of those three authors where tweets from themselves are claimed to contain a link to their own web pages, but  when I look them up they don't.

I've been looking at the logs for the last 7 days and I can see this activity throughout that period.

**Comment by snarfed** [comment]
thanks for the report! looks like these are user mentions (#523). i thought i'd fixed this bug in snarfed/granary@927dc1ac9b8acb830063f7581a15090b2d0c0ce4, but maybe not. i'll look.
