### ISSUE TITLE
Wrong content for Facebook share?

### ISSUE THREAD

**Issue by marcthiele** [snarfed/bridgy#591]
Hey there,

I have a mention, which is a share on Facebook with a text included. Somehow the content says "name" for the text instead of "text". Is this correct? 

Example is: 

{"author":{"name":"beyond tellerrand","photo":"https:\/\/graph.facebook.com\/v2.2\/181579715213817\/picture?type=large","url":"https:\/\/www.facebook.com\/181579715213817"},"published":"2016-01-05T12:59:40+00:00","name":"Help getting a better image of how people plan their journey to and for events. With a bit of luck you can also win a book for taking part. Thanks!","text":"shared this.","url":"https:\/\/www.facebook.com\/181579715213817\/posts\/1019399561431824","type":"mention"}

Let me know if you need more input.

/marc

**Comment by snarfed** [comment]
interesting! i'll take a look.

your Kirby webmention plugin fetches HTML from bridgy, so i'm curious how it converts it to that JSON. it looks like there was more processing than just parsing mf2. @bastianallgeier could you describe that?

**Comment by snarfed** [comment]
[bridgy log](https://brid.gy/log?start_time=1451999491&key=aglzfmJyaWQtZ3lyNAsSCFJlc3BvbnNlIiZ0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxOTM5OTU2MTQzMTgyNAw):

```
0.1.0.2 - - [05/Jan/2016:05:11:31 -0800] "POST /_ah/queue/propagate HTTP/1.1" 200 84 "http://brid.gy/_ah/queue/poll" "AppEngine-Google; (+http://code.google.com/appengine)"

Params: NestedMultiDict([('response_key', u'aglzfmJy...')])
Source: Marc Thiele (Facebook) 10152730008413916, http://brid-gy.appspot.com/facebook/10152730008413916
Created by this poll: http://brid-gy.appspot.com/log?start_time=1451999428&key=aglzfmJyaWQtZ3lyIwsSDEZhY2Vib29rUGFnZSIRMTAxNTI3MzAwMDg0MTM5MTYM
Starting Response repost tag:facebook.com,2013:1019399561431824 https://www.facebook.com/181579715213817/posts/1019399561431824
Webmention from https://brid-gy.appspot.com/repost/facebook/10152730008413916/10154447849633916/1019399561431824 to http://marcthiele.com/notes/planning-event-trips
Sending...
Starting new HTTP connection (1): marcthiele.com
"GET /notes/planning-event-trips HTTP/1.1" 200 None
Starting new HTTP connection (1): marcthiele.com
"POST /webmention HTTP/1.1" 200 None
Sent! {'body': u'{"status":"success","code":200,"message":"Yay","data":202}', 'request': u'POST http://marcthiele.com/webmention (with source=https://brid-gy.appspot.com/repost/facebook/10152730008413916/10154447849633916/1019399561431824, target=http://marcthiele.com/notes/planning-event-trips)', 'http_status': 200}
Setting last_webmention_sent
```

**Comment by snarfed** [comment]
here are the relevant parts of bridgy's mf2 HTML for that share:

https://brid-gy.appspot.com/repost/facebook/10152730008413916/10154447849633916/1019399561431824

```
<article class="h-entry h-as-share">
  <span class="p-uid">tag:facebook.com,2013:1019399561431824</span>
...
  <a class="p-name u-url" href="https://www.facebook.com/181579715213817/posts/1019399561431824">Help getting a better image of how people plan their journey to and for events. With a bit of luck you can also win a book for taking part. Thanks!</a>
  <div class="e-content">

  <a href="https://www.facebook.com/marcthiele/posts/10154447849633916">shared this.</a>
  </div>

<a class="u-repost u-repost-of" href="https://www.facebook.com/marcthiele/posts/10154447849633916"></a>
<a class="u-repost u-repost-of" href="http://marcthiele.com/notes/planning-event-trips"></a>
<a class="u-repost u-repost-of" href="https://t.co/fYgxhfPHvS"></a>
...
</article>
```

**Comment by snarfed** [comment]
...so yes, you're absolutely right, we could include the text of the share in the content as opposed to "shared this" when there is text

cc @kylewm since he knows more about mf2 than me. think that would be ok?

**Comment by snarfed** [comment]
(btw @bastianallgeier feel free to ignore my earlier question!)

**Comment by kylewm** [comment]
Absolutely, I think it makes sense to switch p-name and e-content here.

The p-name could also be something more descriptive like "shared this and added a comment" or "shared this and said: ..."

**Comment by snarfed** [comment]
researching this is a bit confusing so far. i haven't yet found anywhere we're doing anything wrong that would result in the HTML above.
* `handlers` seems to correctly map `/repost/facebook/10152730008413916/10154447849633916/1019399561431824` to granary's `Facebook.get_share('10154447849633916', '10154447849633916', '1019399561431824')`
* that `get_share` call correctly fetches `/1019399561431824` from the FB API, which returns this share object
* `facebook` correctly converts FB API `message` to AS `content`
* `microformats2.object_to_json/html` correctly propagate AS `content` in a `share` object into mf2 `e-content`

**Comment by snarfed** [comment]
aha, found it, it's [this code in bridgy's repost handler](https://github.com/snarfed/bridgy/blob/52d43acc3f7e09b4c83d336db9e2de1e11b70215/handlers.py#L287):

```py
# webmention receivers don't want to see their own post in their
# comments, so remove content before rendering.
for key in 'content', 'attachments':
  if key in repost:
    del repost[key]
```

introduced in ebdca44828d192474acf6dda29fc704b2b0c3f82. so, to keep the spirit of that change, i guess we need to detect when the content is from the repost and not the original post, and not remove it then.

**Comment by snarfed** [comment]
...easier said than done. @kylewm, any chance you remember the background to ebdca44828d192474acf6dda29fc704b2b0c3f82?

as data points, it looks like we currently omit AS `content` entirely for FB shares with no message, and here's example current AS `content` field that we generate for a retweet:

```
  "content": "RT <a href=\"https://twitter.com/julien51\">@julien51</a>: It takes years to make the most important decision of your life.", 
```

**Comment by kylewm** [comment]
It's that thing where marking up reposts is tricky -- do we err on the side of making consumption easier for readers (where the "content" of the "share" object should at least be "shared a post by @\julien51" or maybe even include the content of the shared post "RT @\julien51 ..."), or do we make it easier for webmention receivers (who just want to see "shared this." or maybe "shared this and said: ..."?)

Likes have a similar but less dramatic problem; is the name "liked a post by so-and-so" or "liked this"?

The RepostHandler is one place where it makes sense to do the latter because it's only ever being seen by webmention receivers. And deleting content was probably the expedient way to do that at the time. I don't *think* the changes I made for quote tweets would affect it.

Maybe we want `microformats2.render_content` to have a parameter for who the intended recipient is? And then RepostHandler would tell it to render the content for a webmention receiver... Not ideal.

**Comment by snarfed** [comment]
great point about how rendering is consumer specific, i hadn't thought about it that way before.

i agree that an intended consumer arg is maybe a bit clunky. what if we framed it instead as whether to synthesize content or not? if true, we do what we do now; false, we only include content explicitly authored by the activity's actor. in practice i think this would only be messages in FB/G+ shares and maybe FB RSVPs, and maybe similar things in Flickr that I'm not familiar with.

**Comment by kylewm** [comment]
Hmm, what do we actually want the property values to be for the above example? name = "shared this." and content = "Help getting a better image of how people plan... etc"?

I think it could also make sense for name = content = "shared this and said, "Help getting a better image of how people plan... etc"" or something along those lines

**Comment by snarfed** [comment]
for this example, if `synthetic_content=False` (or whatever we call it), i think we'd actually leave both `content` and `name` as exactly what the author entered: `""Help getting a better image..."`.

If `synthetic_content=True` - which i think is what you're asking? - then your second suggestion sounds good to me: `'shared this and said, "Help getting a better image...'` or anything along those lines.

**Comment by kylewm** [comment]
I hate to say it but shouldn't we handle quote tweets and facebook shares with commentary the same? Quote tweets were simply a mention with the original in an h-cite (that'd be similar to just always doing  the `synthetic_content=False` suggestion).

**Comment by snarfed** [comment]
sure! i still don't think everyone agrees on whether quote tweets are reposts or replies or something else yet, but sure, once we've settled on what we want here, we could definitely include them.

**Comment by kylewm** [comment]
It might be interesting to discuss in channel again at some point. I have a feeling people have a firmer idea of the semantics of an FB Share than a Quote Tweet.

**Comment by snarfed** [comment]
sure! we could also maybe not block on quote tweets in the meantime. if we're OK with this proposal for FB shares and other unambiguous reposts, we could move ahead with it.

**Comment by kylewm** [comment]
Hmm, sorry I don't think I was being very clear. I'm not trying to block at all, more I was saying "we've already litigated the markup for quote tweets, so let's just use that same thing for FB reposts-with-comment". In which case the markup is unambiguously

```html
<article class="h-entry">
<div class="p-name e-content">
Help getting a better image...
</div>
<a class="u-mention-of" href="https://www.facebook.com/marcthiele/posts/10154447849633916"></a>
<a class="u-mention-of" href="http://marcthiele.com/notes/planning-event-trips"></a>
<a class="u-mention-of" href="https://t.co/fYgxhfPHvS"></a>
</article>
```

And there's no need to complicate things with a `syntethic_content` switch

**Comment by snarfed** [comment]
oh! i see. I'm not convinced though. FB shares seen to be reposts much more clearly. I'm not sure I'd want to denote then to mentions.

**Comment by kylewm** [comment]
that's exactly how I felt about quote tweets! except you're right that the case for FB shares being reposts is stronger (e.g., bc they are included in the count of "shares"). so you won't get any argument from me. I really don't feel strongly either way though. sorry for dragging this out, I'm done now :speak_no_evil:

**Comment by snarfed** [comment]
we've discussed this a bit on IRC, but just for the record, one side effect of this is that webmention receivers that don't special case likes and reposts now show blank webmentions for them since they don't have built in content any more. :( e.g. http://marcthiele.com/notes/atomic-design-book

<img width="817" alt="screen shot 2016-01-19 at 11 49 10 am" src="https://cloud.githubusercontent.com/assets/778068/12430114/b2d1fa24-bea2-11e5-97c0-f80831f55cd0.png">

**Comment by marcthiele** [comment]
True. Already recognised this. Just did not find the time to work on this. Going to sort Facebook likes and Twitter favourites under one category (you can use the given link structure to do this) and mentions with "content" (text) under mentions.
