### ISSUE TITLE
consider not retrying webmentions that 4xx

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#593]
motivated by high volume accounts like http://brid.gy/twitter/btconf that get @-mentioned often, but don't support home page webmentions, so they return 400.

i *think* this would be mostly ok. any other opinions?

(we'd need to be careful to only give up on webmention handler 4xxes, not silo API 4xxes like e.g. #512 _Facebook response handler 404s and 400s_. that still definitely happens, and i think at least some of the FB 4xxes are transient. not sure though.)

**Comment by kylewm** [comment]
It certainly makes sense to me... If they say 400, to me that means "I got it, checked it, and determined it was invalid", and we should not retry.

Downside as usual is that it makes it slightly more difficult when someone is coding a webmention receiver for the first time. But I'm guessing the manual retry button will still be there, which handles that nicely

I went looking for documentation and found only Bridgy! According to https://indiewebcamp.com/Webmention-brainstorming#retrying Bridgy historically didn't retry 4xx responses. Do you remember why you changed it?

**Comment by snarfed** [comment]
heh, thanks for the nudge. i remembered that too, and figured i'd dropped it at some point...but no, it's still there: https://github.com/snarfed/bridgy/blob/5b0747b91280b467a115fb9663e82eaaf147aa1b/tasks.py#L520

funny, turns out we still retry sometimes due to a bug in webmention-tools that i've already had to work around once just days ago, in 5b0747b91280b467a115fb9663e82eaaf147aa1b. it returns a dict with response type (e.g. `RECEIVER_ERROR`) in the `code` key, but if the response body is JSON, it merrily updates that dict with it, including overwriting the `code` key. whee!

honestly we don't get that much value from webmention-tools; i probably should have dropped it a while back. :P
