### ISSUE TITLE
migrate off of webmention-tools

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#594]
it's served us well, and it was indispensable during early development, but workarounds for bugs like in  5b0747b91280b467a115fb9663e82eaaf147aa1b and ea91b1274046cde1c52466f24c9302627998d858 are probably signs that it's time to move away from it.

**Comment by kylewm** [comment]
It looks like you are only using the `send` module; I'd be happy to pull out a reusable subset of https://github.com/kylewm/redwind/blob/master/redwind/plugins/wm_sender.py and slap some tests and documentation on it...

**Comment by snarfed** [comment]
thanks for the offer! bear's ronkyuu (#43) is maybe another option. i'm probably not prioritizing this right now, just tracking.

**Comment by kylewm** [comment]
:+1: for ronkyuu; I'd forgotten it! Definitely would prefer to focus our attention there, and I'll probably migrate my sender at the same time.

**Comment by bear** [comment]
if you leave me issues I will fix/change ronkyuu to work -- i've been looking for a "not bear's" use case to make ronkyuu better

**Comment by snarfed** [comment]
thanks @bear!
