### ISSUE TITLE
rerunning OPD for each new response

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#597]
looking at [this poll log for @t](https://brid.gy/log?start_time=1452730190&key=aglzfmJyaWQtZ3lyDgsSB1R3aXR0ZXIiAXQM), we're running a full OPD for each new response, including fetching his site and processing all h-entries. we should only need to do it once. :P cc @kylewm

**Comment by kylewm** [comment]
The good news is that it only fetches the feed for each new response, and doesn't actually dive into each permalink. There's [even a test](https://github.com/snarfed/bridgy/blob/master/test/test_original_post_discovery.py#L137) that makes sure we fetch the feed anew for each response. Wish I could remember why I did that!

I need to decide whether to change the logic to be smarter, or to just add a temporary cache (dict) so that it can pull the feed content from memory if it's already been fetched this round...

**Comment by kylewm** [comment]
Hmm, the *really* simple alternative is just to set `fetch_hfeed` to false on all but the first call to `discover`... Relationships are stored in the DB for all permalinks, so there's no need to run fetch_hfeed more than once per cycle.

We have to know kind of a lot about the implementation of `original_post_discovery` to know that that's an OK decision to make, but I like it better than the alternatives (either a radical restructuring of OPD, or passing an opaque cache dict around)

**Comment by kylewm** [comment]
It looks like the naive solution I proposed above isn't quite working. @aaronpk asked why [this tweet](https://twitter.com/aaronpk/status/724379791734919168) wasn't being connected to his site.

The first time `discover` is run, it's run for [this tweet](https://twitter.com/kevinmarks/status/721724227439697921) that links to a page on Aaron's site... I think it must already have a `SyndicatedPost` for this page, so it skips fetching the h-feed. 

Then the optimization prevents it from fetching the h-feed on subsequent iterations.

```
16:45:45.994
Original post discovery found original posts set([u'https://aaronparecki.com/sleep']), mentions set([])
16:45:45.995
Demoting original post links because user tag:twitter.com,2013:aaronpk doesn't match author tag:twitter.com,2013:kevinmarks
16:45:46.032
starting posse post discovery with syndicated https://twitter.com/kevinmarks/status/721724227439697921
16:45:46.051
Original post discovery found original posts set([]), mentions set([u'https://indiewebcamp.com/2016/Nuremberg'])
16:45:46.051
Demoting original post links because user tag:twitter.com,2013:aaronpk doesn't match author tag:twitter.com,2013:openSUSE
16:45:46.057
starting posse post discovery with syndicated https://twitter.com/openSUSE/status/719914707566649344
16:45:46.127
Original post discovery found original posts set([]), mentions set([])
16:45:46.127
starting posse post discovery with syndicated https://twitter.com/aaronpk/status/724379791734919168
16:45:46.139
posse post discovery found no relationship for https://twitter.com/aaronpk/status/724379791734919168
16:45:46.306
skipping refetch h-feed. last-syndication-url 2016-04-24 04:10:24.620410, last-refetch 2016-04-24 23:10:40.857280
16:45:46.313
Updating aaronpk (Twitter) /twitter/aaronpk : {'last_polled': datetime.datetime(2016, 4, 24, 23, 45, 42, 610400), 'poll_status': 'ok', 'last_activity_id': u'724379791734919168', 'recent_private_posts': 0, 'last_public_post': datetime.datetime(2016, 4, 24, 23, 29, 35)}
16:45:46.380
Added poll task 90221531404143534281 with args {'countdown': 1767.9868069463994}
```

**Comment by snarfed** [comment]
doh! :( thanks for catching.
