### ISSUE TITLE
rename last_hfeed_fetch to last_hfeed_refetch

### ISSUE THREAD

**Issue by kylewm** [snarfed/bridgy#600]
Because `last_hfeed_fetch` refers only to the `original_post_discovery.refetch` operation, we'll rename it `last_hfeed_refetch`

**Comment by kylewm** [comment]
Here's the remote_api_console script I'll use to transfer values from last_hfeed_fetch to last_hfeed_refetch if refetch is not initialized:

```python
from google.appengine.ext import ndb
import blogger
import facebook
import flickr
import googleplus
import instagram
import tumblr
import twitter
import util
import wordpress_rest


@ndb.transactional
def update(key):
  src = key.get()
  if src.last_hfeed_refetch == util.EPOCH:
      src.last_hfeed_refetch = src.last_hfeed_fetch

  src.put()
  print (src.key.flat(), src.last_hfeed_refetch)

facebook.FacebookPage.query().map(update, keys_only=True)
flickr.Flickr.query().map(update, keys_only=True)
twitter.Twitter.query().map(update, keys_only=True)
instagram.Instagram.query().map(update, keys_only=True)
googleplus.GooglePlusPage.query().map(update, keys_only=True)
blogger.Blogger.query().map(update, keys_only=True)
tumblr.Tumblr.query().map(update, keys_only=True)
wordpress_rest.WordPress.query().map(update, keys_only=True)

```

**Comment by snarfed** [comment]
(related to https://github.com/snarfed/bridgy/issues/206#issuecomment-47789048.)

hmm. any reason not to just always copy `last_hfeed_fetch`? it'd be nice to preserve it for all sources, e.g. disabled sources that aren't polling any more.

**Comment by snarfed** [comment]
also, minor nit, you can skip running it for tumblr, blogger, and wordpress if you want. :P

**Comment by kylewm** [comment]
> hmm. any reason not to just always copy last_hfeed_fetch? it'd be nice to preserve it for all sources, e.g. disabled sources that aren't polling any more.

Just because I didn't want to overwrite `last_hfeed_refetch` if it happened to do a refetch between the time that I deployed the application and the time that I ran the migration script

**Comment by snarfed** [comment]
ohhhh i misread the migration script. nm, lgtm, thanks!

**Comment by kylewm** [comment]
here's what I actually ended up doing. It is not a lot faster, but it doesn't get hung up the way the original script was

```python
from google.appengine.ext import ndb
import facebook
import flickr
import googleplus
import instagram
import twitter
import util


@ndb.transactional_tasklet
def update(key):
  src = yield key.get_async()
  if src.last_hfeed_refetch == util.EPOCH:
    src.last_hfeed_refetch = src.last_hfeed_fetch
  yield src.put_async()
  print (src.key.flat(), src.last_hfeed_refetch)

for cls in (
        facebook.FacebookPage,
        flickr.Flickr,
        twitter.Twitter,
        instagram.Instagram,
        googleplus.GooglePlusPage,
):
  cls.query().map(update, keys_only=True)
```

**Comment by snarfed** [comment]
slick. i spot checked a few entities and they look good. thanks!

**Comment by kylewm** [comment]
Thank you for checking!
