### ISSUE TITLE
Bridgy Publish to Flickr: detect hashtags and set Flickr tags

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#604]
Bridgy Publish supports publishing photos (including user tags) to Flickr, what's missing is normal / plain Flickr tags.

There are two ways an indieweb post can tag a post that Bridgy Publish should consider picking up:
1. \# hashtags. Hashtags in the (p-)name, (p-)summary, (p-)content property values could (should) be parsed out as intended as tagging the photo/video.
2. (p-)category markup. Since Bridgy Publish is already parsing for (u-)category properties, and this parsing should be generic to any kind of (*-)category property, if/when a 'category' property is not a URL (thus not person-tag), then it should be treated as a plain text tag.

**Comment by snarfed** [comment]
thanks for filing!

publish actually already propagates p-category mf2 tags to Flickr tags. @kylewm added that pretty recently. this is a good nudge to add it to the docs.

as for hashtags in plain text, I'm not sure. i get that #hashtag syntax is pretty universal now, and i get that it's necessary in silos that don't allow explicit tags, but publish users generally own their markup and get to author explicit mf2 tags with p-category.

given that, I'm a bit reluctant to promote text only #hashtags to explicit silo tags... but i dunno. thoughts?

**Comment by kylewm** [comment]
I notice that Known autolinks hashtags so `"category": ["#indieweb"]`. If we stripped the octothrope for silos that don't use it, that might be a happy medium? Then sites like tantek's that want interpret them as tags could make it explicit by wrapping them with a `<span class="p-category">`

**Comment by snarfed** [comment]
(daaamn it's a sunday morning and @kylewm got me all https://www.google.com/search?q=define%3Aoctothrope )

**Comment by snarfed** [comment]
stripping octothpus sgtm!

**Comment by tantek** [comment]
@snarfed I'm sympathetic to not overdoing the smarts re: "reluctant to promote text only #hashtags to explicit silo tags".

This might be another example of not over-interpreting text (e.g. whitespace) into markup.

Even if you do end up rejecting this suggestion (to autopromote plain text hashtags to categories/tags), I wanted to capture it (and subsequent analysis) because I expect it will come up again.

**Comment by tantek** [comment]
Narrowed the scope since p-category tags are already supported apparently. Just need to update the docs re: p-category

**Comment by singpolyma** [comment]
This publish brid.gy did https://www.flickr.com/photos/singpolyma/24001981743/ seems to have the hashtag autolinked (maybe flickr did that from the plain text?) but then the tag itself is not on the post?  A bit confusing UX on the flickr side, not sure if my tag ended up on the post or not.  My tag is marked up using rel=tag in the hentry, so it seems like brid.gy should be able to pick it up?

**Comment by snarfed** [comment]
[discussing in IRC now.](http://indiewebcamp.com/irc/2016-01-26#t1453827624132)

**Comment by kylewm** [comment]
@singpolyma http://sngpl.ma/t4fS0 is returning 404, can you point me to the original that was POSSEd? My guess is mf2py isn't doing backcompat for rel=tag

**Comment by singpolyma** [comment]
@kylewm oh, right, my short domain is still down (grumble,grumble morocco) -- full URL https://singpolyma.net/actionstream/boring-cabinets/

**Comment by kylewm** [comment]
great! so I think if you just add class="p-category" on that tag, it'll work just fine.

**Comment by kylewm** [comment]
Should be backward-compatible with rel=tag now, so you don't need to change your markup.

**Comment by snarfed** [comment]
tentatively closing due to discussion above: p-category tags are supported and documented.
