### ISSUE TITLE
facebook: can't distinguish some photos as public vs private

### ISSUE THREAD

**Issue by tinokremer** [snarfed/bridgy#611]
I added a photo post on my site (Known, self hosted) this morning which syndicated to Facebook, Twitter and Flickr (and manually to Google+). I noticed there are no comments appearing from Facebook so I decided to dive into it.

The post: https://tinokremer.nl/2016/hiep-hiep-hoera
The FB syndicated post: https://facebook.com/504157529757046

Both are fully public and the photo post does have the "Original" link in there which works correctly.

I'm wondering what is causing it to not appear. I can think of these reasons:

1) The post has not been discovered for some reason, I notice my photo appears in my wife's timeline as "Tino Kremer has posted 2 photos), could that be the reason?

2) There are 2 fails on the FB Bridgy page:

![image](https://cloud.githubusercontent.com/assets/546983/12535658/50c9d658-c28a-11e5-8397-c7d10eeb371e.png)

That failure is probably another bug which could be Known and not Bridgy. The link is https://tinokremer.nl/10102571892817971/conversatie-tussen-mijn-zoon-en-dochter-4zoon-ik-vind-het which does not appear to be working. Perhaps it did work before as I did receive quite a few comments on that post as well, original here: https://tinokremer.nl/2016/conversatie-tussen-mijn-zoon-en-dochter-4zoon-ik-vind-het

3) Something else?

I don't think I can see access what Bridgy sees on my FB profile, but I'm wondering what is causing it and if I can do something to fix it.

**Comment by kylewm** [comment]
> https://tinokremer.nl/10102571892817971/conversatie-tussen-mijn-zoon-en-dochter-4zoon-ik-vind-het 

Ah darn, this is actually an unintended consequence of my changes to Known's permalink routing. It is now expecting a 4 digit year, whereas it used to accept any number. So when facebook changes 2016 to 10102571892817971, it doesn't work anymore.

Blech I didn't realize Facebook was rewriting links *in the body* of the post now. That suuucks.

**Comment by kylewm** [comment]
> Blech I didn't realize Facebook was rewriting links in the body of the post now. That suuucks.

Update: ok fortunately it isn't that. The post that's failing has a "See Original" link, rather than a link in the body, and that is what Facebook is rewriting. (Which is well known)

**Comment by tinokremer** [comment]
Is that the case? In this post it looks like it's just text "Original: link": "Original: https://tinokremer.nl/2016/hiep-hiep-hoera". I'm talking about the not discovered post https://facebook.com/504157529757046

**Comment by kylewm** [comment]
You're right, the photo post seems like it should have been discovered. I wouldn't guess that has anything to do with the webmentions to `https://tinokremer.nl/10102571892817971/conversatie-tussen-mijn-zoon-en-dochter-4zoon-ik-vind-het` that are failing... Webmentions in the queue are more or less independent.

**Comment by snarfed** [comment]
oh boy, fun!

for more background, the facebook bug that rewrites years in URLs to longer ids is #368.

@kylewm is right about the rest; we can look into it. looks like your bridgy user page is https://brid.gy/facebook/403320719840728 .

**Comment by snarfed** [comment]
looks like [this line in the log](https://brid.gy/log?start_time=1453651464&key=aglzfmJyaWQtZ3lyIQsSDEZhY2Vib29rUGFnZSIPNDAzMzIwNzE5ODQwNzI4DA) is the problem:

```
2016-01-24 16:04:28.001640 I Skipping non-public activity tag:facebook.com,2013:504157529757046
```

evidently we don't think https://facebook.com/504157529757046 is public, even though it is. not sure why; i'll investigate.

**Comment by snarfed** [comment]
whee. so figuring out an FB post or photo's privacy setting is surprisingly hard, and can take multiple conditional API calls. background in https://github.com/snarfed/bridgy/issues/559#issuecomment-159642227 .

in this case, it looks like we followed the bread crumb trail correctly, from photo (object) id 504157529757046 back to consolidated "uploaded 2 photos" post id 403320719840728_504157529757046, which has privacy `CUSTOM` with no extra details:
```
"privacy": {
  "value": "CUSTOM",
  "description": "",
  "friends": "",
  "allow": "",
  "deny": ""
},
```

[privacy field docs here](https://developers.facebook.com/docs/graph-api/reference/v2.2/post#fields)...but they don't say anything about what `CUSTOM` with no details means. currently we're conservative and only interpret `EVERYONE` as public.

@tinokremer, does that photo or [the album](https://www.facebook.com/media/set/?set=a.496713230501476.1073741846.100004884100993&type=3) have anything more than just "Public" selected in privacy settings? maybe under "More Options"?

(ah facebook. never change!)

**Comment by tinokremer** [comment]
You're correct @snarfed. The 'album' (which is virtual, I haven't created a single album on Facebook myself) has it's setting to "Custom", meaning every photo will have its own privacy setting:

![image](https://cloud.githubusercontent.com/assets/546983/12538150/70dede32-c2d2-11e5-9985-da69c78a680e.png)

This is quite normal. I have several automatically created albums (I never create one myself) and all have that setting. I don't think I can change it either. This is what the 'album' page on Facebook says:

![image](https://cloud.githubusercontent.com/assets/546983/12538162/f91d2c7c-c2d2-11e5-89c6-5746e415ab26.png)

I'm actually annoyed Facebook does create albums and decides to show several completely unrelated photos as a group. That's what we have to deal with, it's a common issue with Silo's, they tend to do things a certain way and you, as a user, have no way to alter that.

I'm not an expert on the Facebook API (in fact, I know it exists, but haven't actually looked at it closely). It seems like "Custom" means the privacy setting of the individual photo's should be used instead.

I learned something as well, I should not post pictures when something like this is popping up within the next 24 hours. This is a 'card' letting my friends and family know it's both my kids birthday today. One of the most interesting ones to save comments from.

**Comment by snarfed** [comment]
thanks for the details @tinokremer! sadly the photo object has no `privacy` field, and the post connected to it (by `object_id`) has the blank `CUSTOM` privacy field i posted above, se we fall back to the album's.

we've seen this before, e.g. https://github.com/snarfed/bridgy/issues/559#issuecomment-159642227. we originally defaulted to interpreting these cases as public, and we ended up backfeeding non-public responses.

that's definitely not acceptable, so we had to stop that. sadly it's looking like the tradeoff may be that we lose some public posts like this one, since there's no way to distinguish that they're public. i'd love to find a way though!

**Comment by snarfed** [comment]
and you're definitely righ that facebook consolidating photo posts is annoying! we've had to do a lot of work to handle that so far, for both backfeed (#562) and publish (#571).

**Comment by tinokremer** [comment]
Can we get Bridgy to process the comments manually in this particular case? Or should I just leave it like it is for now or write something to import it manually myself? :)

**Comment by snarfed** [comment]
@tinokremer sure! you can send webmentions for each comment and like manually, using https://brid.gy/about#source-urls to generate the bridgy source URLs.

that is a lot of tedious work though. #579 is probably what you're looking for, triggering backfeed for an entire post, but that's not supported yet, especially not for private posts. that check is very strict right now.

sorry. feel free to subscribe to #579 so you'll know if we do eventually do it!

**Comment by tinokremer** [comment]
Done and massive thanks for the support @kylewm and @snarfed !

**Comment by kylewm** [comment]
FWIW, I believe "Custom" can also mean some complicated union of "These groups and not these groups". For a long time I had my default setting to share with "Friends minus people from high school I don't really like".

**Comment by tinokremer** [comment]
You could be very right @kylewm. I think more people use it like that. Unfortunately we have to deal with the woes of using those Silo's. There is a reason we're posting on our own sites after all :)

**Comment by tinokremer** [comment]
Just a heads-up for people that may encounter the same issue. I removed a few posts from FB yesterday, including the second 'photo' that was causing this virtual album and a while later all comments and likes were imported. Bridgy probably was now able to retreive everything as the virtual album was removed and it's a single photo again.

Do we want to keep this issue open @snarfed?

**Comment by snarfed** [comment]
glad to hear it!

let's keep this issue open, since the problem still exists in general. that way, if it happens to someone else, and they come here, they'll be able to find this issue.

**Comment by snarfed** [comment]
[Facebook support is dead](https://brid.gy/about#rip-facebook) (#817, #826), so I'm closing this as obsolete. feel free to reopen if you have any concerns!
