### ISSUE TITLE
Bridgy Publish to Flickr: ignore fallback content inside video tags

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#612]
Minor nit, not sure of the best way to fix this:
This POSSE copy: https://www.flickr.com/photos/tantek/24235088549/
starts with the text "a video", which is from *inside* the &lt;video&gt; tag with u-video.

According to HTML5, if a user agent (browser, crawler - Bridgy's HTML parsing code in this case) supports the video tag, then it must ignore the content inside, since that's only for browsers / UAs that don't support the video tag.

Alternatively you could pushback and say Bridgy requires no text content inside video tags, which is a bit limiting for publishers, but may actually be the 90%+ case (no idea, just guessing).

**Comment by snarfed** [comment]
good point! thanks for filing.

**Comment by tantek** [comment]
Looks like the "Preview" view when manually submitting a URL to POSSE on https://brid.gy/flickr/39039882@N00# still starts with "a video".

**Comment by snarfed** [comment]
fixed. thanks for reporting!
