### ISSUE TITLE
Thinks my photo post to instagram is a person?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#613]
https://brid.gy/log?start_time=1453827433&key=aglzfmJyaWQtZ3lyWwsSDVB1Ymxpc2hlZFBhZ2UiNGh0dHBzOi8vc2luZ3BvbHltYS5uZXQvYWN0aW9uc3RyZWFtL2JvcmluZy1jYWJpbmV0cy8MCxIHUHVibGlzaBiAgICAgMOVCgw

**Comment by snarfed** [comment]
heh, funny. yeah, i guess that log entry is misleading. your webmention HTTP 400 response should have included [the more useful message intended for users](https://github.com/snarfed/granary/blob/master/granary/instagram.py#L329):

> Cannot publish this post on Instagram. Instagram does not support posting photos or videos from 3rd party applications.

let me know if that wasn't in the response body!

**Comment by singpolyma** [comment]
I just got (in the response):

>   "error": "Cannot publish this post on Instagram."

**Comment by snarfed** [comment]
thanks! i see why. fixing now.
