### ISSUE TITLE
Facebook user mentions should backfeed to homepage (not supported by API)

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#616]
When someone mentions me in a status, I should get a webmention to my homepage, just like with Twitter @reply

**Comment by snarfed** [comment]
I'd love this too! sadly the API doesn't support it: https://github.com/snarfed/bridgy/issues/523#issuecomment-155523875

happy to leave this open for tracking in case they ever do add support, if you want...? seems unlikely since they're moving in the wrong direction, eg removing search in API v2, but who knows.

**Comment by singpolyma** [comment]
Oh, hmm.  The app on my phone notifies me of mentions, so I assumed it was possible.  I guess undocumented API?  Hmm..

**Comment by singpolyma** [comment]
https://github.com/gsurrel/FacebookNotifications seems to be getting notifications somehow. Maybe they've found some of the undocumented stuff?

**Comment by kylewm** [comment]
I think it's basically just scraping https://m.facebook.com/notifications.php if you look at the code around here https://github.com/gsurrel/FacebookNotifications/blob/master/app/src/main/java/org/surrel/facebooknotifications/UpdateService.java#L95

**Comment by snarfed** [comment]
the current user mentions feature (for other silos) doesn't use notifications, it uses search. details in #523.

using notifications instead is definitely an interesting idea!... but yeah, what @kylewm said. the API doesn't support reading them at all: https://developers.facebook.com/docs/graph-api/reference/user/notifications#Reading

**Comment by martymcguire** [comment]
Hey folks. Sorry to resurrect this thread, but I might have some details worth adding.

I noticed a mention on Facebook that bridgy found and attempted to send a webmention to my main url but didn't show up in my results on webmention.io. So I hit retry to send it again. I started digging down from my bridgy dashboard page for my Facebook account, where this appears:

![screen shot 2017-03-28 at 11 02 39 am](https://cloud.githubusercontent.com/assets/14772/24412332/2d6eb84a-13a6-11e7-849a-3c2105d7f8d2.png)

The link does in fact go to the post where I am tagged, and my homepage URL is correct, so in theory this mention should be working.

Clicking through to the bridgy log for sending the mention, it queues for processing and webmention.io returns a status tracking link:

```

0.1.0.2 - - [28/Mar/2017:07:57:11 -0700] "POST /_ah/queue/propagate HTTP/1.1" 200 84 "https://brid.gy/retry" "AppEngine-Google; (+http://code.google.com/appengine)"

2017-03-28 14:57:09.719740 D Params: NestedMultiDict([('response_key', u'aglzfmJy...')])
2017-03-28 14:57:09.810490 I Source: Marty McGuire (Facebook) 10205860140564648, http://brid-gy.appspot.com/facebook/10205860140564648
2017-03-28 14:57:09.810990 I Created by this poll: http://brid-gy.appspot.com/log?start_time=1490624488&key=aglzfmJyaWQtZ3lyIwsSDEZhY2Vib29rUGFnZSIRMTAyMDU4NjAxNDA1NjQ2NDgM
2017-03-28 14:57:09.812950 I Starting Response post tag:facebook.com,2013:10212425859384600 https://www.facebook.com/10210293049505686/posts/10212425859384600
2017-03-28 14:57:09.908710 I Webmention from https://brid-gy.appspot.com/post/facebook/10205860140564648/10212425859384600 to https://martymcgui.re/
2017-03-28 14:57:09.915550 I Sending...
2017-03-28 14:57:10.410000 I Sent! {'body': u'{"status":"queued","summary":"Webmention was queued for processing","location":"https://webmention.io/martymcgui.re/webmention/78GZdpkg4FiBt2KDK6XZ","source":"https://brid-gy.appspot.com/post/facebook/10205860140564648/10212425859384600","target":"https://martymcgui.re/"}', 'request': u'POST https://webmention.io/martymcgui.re/webmention (with source=https://brid-gy.appspot.com/post/facebook/10205860140564648/10212425859384600, target=https://martymcgui.re/)', 'http_status': 201}
2017-03-28 14:57:10.718800 I Setting last_webmention_sent
```

The [webmention.io status link](https://webmention.io/martymcgui.re/webmention/78GZdpkg4FiBt2KDK6XZ) shows debugging info that suggests the bridgy proxy page doesn't contain a link to my home url after all:

```
{
  "status": "no_link_found",
  "source": "https://brid-gy.appspot.com/post/facebook/10205860140564648/10212425859384600",
  "target": "https://martymcgui.re/",
  "summary": "The source document does not have a link to the target URL"
}
```

And clicking through to the [bridgy proxy post for this mention](https://brid-gy.appspot.com/post/facebook/10205860140564648/10212425859384600) shows an FB API error:

```
Facebook error:
{"error":{"message":"Unsupported get request. Object with ID '10205860140564648_10212425859384600' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"fbtrace_id":"C1PzwSAriRb"}}
```

I understand that FB API issues might prevent bridgy from looking up some needed details about this post to create the proxy page. However, I am confused that bridgy seems to know enough about this post and where it belongs to have it show up in my dashboard. Would it be possible to construct a more minimal proxy page for mentions like this?

Thanks and my apologies once again. 😓

**Comment by snarfed** [comment]
huh, very interesting. thanks for noticing and adding these details!

you're right, bridgy correctly converted the user mention to a home page webmention, but it only *found* the post because it's in your profile's feed (née "on your wall"). i think this issue is about finding mentions elsewhere too.

the real problem is that this post isn't public, but the FB API doesn't tell us that. [this happens surprisingly often](https://brid.gy/about#enough+information), sadly. :( we default to assuming posts are private due to this - details in #611 - but evidently that's not happening here. i'll file a new issue for that.

**Comment by snarfed** [comment]
oh, and my sincere apologies for exposing and attempting to backfeed a non-public post!

**Comment by martymcguire** [comment]
thanks for the response and sorry for polluting this issue!

i didn't even think about this post being "private", but that makes a lot of sense. it appears that i have a similar bug in my mental code. :}

**Comment by snarfed** [comment]
[Facebook support is dead](https://brid.gy/about#rip-facebook) (#817, #826), so I'm closing this as obsolete. feel free to reopen if you have any concerns!
