### ISSUE TITLE
whitelist of accounts to backfeed private posts

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#620]
[requested here](http://indiewebcamp.com/irc/2016-02-16#t1455655871762) by @tantek. specifically twitter.com/t, instagram.com/tantek, facebook.com/tantek.celik, plus.google.com/109182513536739786206.

not yet flickr.com/39039882@N00. maybe at some point.

**Comment by snarfed** [comment]
i'm reconsidering this now, inspired by #628. if an account or post is private, that extends beyond just the account/post itself into comments, likes, etc. people often expect that, so they might be surprised if bridgy backfeeds their (private) comments on private posts/accounts to a public web page.

...sorry to say it, @tantek, but this might mean you lose some of your silo backfeed, at least from bridgy.

**Comment by tantek** [comment]
I'm hoping Bridgy will still backfeed public @-replies at a minimum, and I have added a disclosure to my FB profile https://www.facebook.com/tantek.celik "Posts here come from my site tantek.com Comments/likes may be copied to original posts & made public!" to set expectations.

**Comment by tantek** [comment]
I realize such disclosures are unlikely to be automatically detectable, but at least we can encourage them as a best practice, and perhaps even have Bridgy (documentation?) recommend that backfeed users add a disclosure like those in https://indiewebcamp.com/disclosure#Backfeed_Examples to their silo profiles.
