### ISSUE TITLE
brid.gy parses h-breadcrumb instead of h-entry

### ISSUE THREAD

**Issue by dogada** [snarfed/bridgy#621]
Got strange issue with brid.gy after I added  h-breadcrumb microformat to my blog [dogada.org](https://dogada.org). 

Page with a post now has both h-breadcrumb and h-entry (for example please see https://dogada.org/dvd/blog/implemented-breadcrumbs) but when I try to publish it via brid.gy, it offers me to use text from h-breadcrumb and not from h-entry.

How to force brid.gy to ignore first microformat h-breadcrumb and use text from h-entry (as it actually did before I added h-breadcrumb)?

**Comment by snarfed** [comment]
hah, funny. sorry for the trouble! should at least be an easy fix.

right now i think publish mostly ignores type. @kylewm can you think of anything that might go wrong if we prioritized or even required h-entry?

**Comment by kylewm** [comment]
That definitely makes sense. Maybe look for h-entry or h-event ... we don't publish any events, but it's nice to give the silo-specific error message in that case.

**Comment by snarfed** [comment]
fixed. @dogada feel free to try again!

**Comment by dogada** [comment]
Works now. Thanks, Ryan.
