### ISSUE TITLE
in-reply-to link to indie website prevents publishing to Twitter

### ISSUE THREAD

**Issue by dogada** [snarfed/bridgy#622]
If a post have an in-reply-to link I can publish it only if in-reply-to links point to Twitter or a post with Twitter rel-syndication. When I want to post a reply to an IndieWeb site or even WordPress blog (for example  
https://dogada.org/dvd/blog/there-is-no-silver-bullet-id?breadcrumbs=off) I see following error:

```
Could not find a tweet to reply to. Check that your post has an in-reply-to link a Twitter URL or to an original post that publishes a rel-syndication link to Twitter.
``` 

I suppose brid.gy should just publish normal tweet instead of reply in this case.

**Comment by kylewm** [comment]
Thanks for filing! I believe this is the same issue as #362, and definitely something a couple of people have asked for. Let's track over there.
