### ISSUE TITLE
optimize OPD refetch

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#624]
we've started seeing waves of poll latency spikes in the last week or two. anecdotally, it looks like much of the time is spent in OPD refetch. even without the latency spikes, OPD may be one of the main contributors to load. background in https://github.com/snarfed/bridgy/issues/578#issuecomment-186350518.

here are some optimization ideas:

1. [x] ignore syndication links to silos that aren't the one currently being polled. right now we HEAD them to resolve redirects.
1. [x] more aggressive: ignore all syndication links *except* the current silo. this is a bit scary since we'd stop supporting shortlinks for syndication links and alternate domains like flic.kr. not sure how widespread either of those are.
1. [x] similar to poll frequency, ratchet down refetch frequency when we haven't seen a new syndication link for a given user in N days, weeks, etc.
1. [x] remember if we've seen a syndication link in a feed before. if we have, don't bother ever fetching permalinks, at least for a while.
1. [x] we `HEAD` a lot of silo post URLs that we know are ok as is and won't redirect. we should skip those. related: [`Facebook.canonicalize_syndication_url`](https://github.com/snarfed/bridgy/blob/f8a0202175ca8a69f923d441978482fad1436405/facebook.py#L152).
1. [ ] beyond silo URLs, we also `HEAD` and follow a lot of URLs that we then immediately `GET`. this is largely due to (over)using `util.get_webmention_target` to check that the final URL isn't in the blacklist and is `text/html`, but we can easily do that by `GET`ing from the beginning (and check headers before reading data, etc).
1. [ ] fetch feeds and permalinks [in parallel](https://cloud.google.com/appengine/docs/python/urlfetch/asynchronousrequests) instead of serial.
1. [ ] merge refetch for the same domain across multiple sources.
  1. [ ] easy first step: let sources detect and store syndication links for other silos.
  1. [ ] more ambitious: decouple refetch from poll and key it on domain so we don't duplicate refetches per domain.

**Comment by snarfed** [comment]
the minimal first steps i may take here are \#2 and \#3.

**Comment by kylewm** [comment]
It does a whole lot of HTTP requests, especially for pages with a lot of h-entries. Might it be worth using a thread pool parallelize some of those fetches? All the processing of the actual results could still be synchronous.

Although if the initial h-feed is taking > 10s, then that might not help much.

**Comment by snarfed** [comment]
ah good point! i'd meant to include that in the initial list. async http fetches would be a big win. thanks!

**Comment by kylewm** [comment]
> more ambitious: decouple refetch from poll and key it on domain so we don't duplicate refetches per domain.

man, this would be fantastic, but I agree it is likely to be a big job. I wish I had done it that way from the beginning.

I'm willing to take it on if the minimal steps you suggested make a noticeable difference on overall load (or I guess, even if they don't, if there's still reason to believe refetch is the issue)

**Comment by snarfed** [comment]
thanks for the offer! if we guess bridgy users average ~2 accounts each - totally a guess - then yeah, naively it'd cut OPD's load in half.

i say let's try the others first, and if they're not enough we can consider it.

if you're interested, feel free to look at the async http idea! doc link in the issue description.

**Comment by kylewm** [comment]
I guess I had been naively hoping that a small enough portion of users publish syndication links that OPD would be dwarfed by something else :D

**Comment by snarfed** [comment]
i think that's still probably true, although it's still a decent number. there are a lot of known accounts! :P

the catch is that OPD still does most of its work even if there aren't any syndication URLs. fetch the h-feeds, fetch permalinks, HEAD many urls to follow redirects, etc.

**Comment by snarfed** [comment]
ah, but you're right that we only refetch if we've seen at last one synd url before. I'm definitely going to slow that down if it's been a while, which may help.

**Comment by snarfed** [comment]
another idea: we currently always fetch the permalink if there's no syndication link to our silo in the feed entry. if we've seen syndication links in other feed entries on this site before, we know they do publish them in the feed, so fetching the permalink probably won't find any new ones. we could skip it in that case.

this could change across server/config migrations or upgrades, so we might want an expiration, or maybe (better) we just clear it when they manually click the Crawl Now button.

**Comment by snarfed** [comment]
we're also too promiscuous about HEADing any url we come across in order to follow redirects, both in OPD and elsewhere. we could probably rein that in a bit and still be ok.

**Comment by kylewm** [comment]
The async stuff seems like a dead end because mf2 parsing (surprisingly) dominates I/O time.

Encouraging people to post syndication links in their h-feed, and then limiting our fetches when we know they do, seems like the only way forward.

I'd honestly be open to deprecating the deep fetch behavior altogether, _requiring_ syndication links in the h-feed.

**Comment by kylewm** [comment]
I also haven't been able to tell if *refetch* in particular is significantly worse than regular posse-post-discovery. It seems like I saw plenty of high-latency tasks that were not doing the full refetch.

**Comment by snarfed** [comment]
thanks again for investigating all this @kylewm!

so you didn't find any big wins for parsing? are we really resigned to a fate of parse times in seconds, at least on the entry level app engine instance's CPU? I'll be on irc later this afternoon, we can maybe talk "in person" then.

otherwise, that all makes sense. let's keep tracking the OPD optimizations here for now. I'll keep the checkboxes in the description updated and prioritized.

sounds like the next biggest wins may be 1) skipping permalink fetches when appropriate and 2) decoupling refetch from poll and keying on url...?

**Comment by snarfed** [comment]
i collected some interesting numbers overnight, ~10h total. it looks like our average BeautifulSoup parsing time is ~132ms per page, and our average mf2py parsing time (*after* BeautifulSoup) is ~1.03s per page. seems surprising to me, i would have guessed BS was most of it.@kartikprabhu @tommorris @kylewm @kevinmarks, any thoughts?

methodology: #627. i timed every BS and mf2py parse, making sure i always passed mf2py BS doc objects and not strings. i collected the total time for each, the total number of mf2py parses, and the total HTML length (in characters) parsed by BS. for BS, i then divided by 67kb, [HTTP Archive's average web page HTML size for 2/2016.](http://httparchive.org/interesting.php)

(i should have just counted every BS parse like i did with mf2py, but i didn't think i'd be comparing them directly like this. oh well. i can do that next time!)

raw data:
```
{'timed beautifulsoup size': 356913979,
 'timed mf2py size': 10882,
 'timed beautifulsoup': 703200,
 'timed mf2py': 11178723
}
```

**Comment by kylewm** [comment]
Interesting, it seems like the vast majority of time in the parser is spent in `backcompat.apply_rules`

**Comment by kevinmarks** [comment]
Average is not a good guide to these kinds of complexity - better to
collect a lot of individual pages and histogram them - average will hide
the O(n^2) cases

**Comment by kevinmarks** [comment]
Apply rules does seem to be turning a dictionary lookup into a nested for loop

**Comment by snarfed** [comment]
@kevinmarks true! if that is what's happening, though, I'd be disappointed that mf2py has such bad degenerate cases. even disregarding statistical methods entirely, bridgy spent ~16x more CPU time over these 10h in mf2py than in BeautifulSoup (which includes the HTML parsing!). :/

**Comment by snarfed** [comment]
tommorris/mf2py#61 looks promising!

**Comment by kylewm** [comment]
parsing should be comfortably faster than fetching with that change. (although mf2py still takes longer than beautifulsoup, which is perplexing). Fetching my homepage and all permalinks:

```
total time in request 6.80604124069
total time in soup    0.982750654221
total time in parse   1.53459310532
```

**Comment by kevinmarks** [comment]
Is there a way to make the rule application not be a loop too? As that is 2
loops derp already?

**Comment by tommorris** [comment]
This work looks absolutely amazing. I'll have a proper look at the mf2py PR tomorrow but the performance improvements look great.

**Comment by kylewm** [comment]
> Is there a way to make the rule application not be a loop too? As that is 2 loops derp already?

Yeah I could make the classname conversion a dict lookup instead of iterating over the rules. Since there aren't many rules for any given root, I don't think it would make much difference though.

**Comment by snarfed** [comment]
more numbers, from ~5.5h of explicitly configuring BeautifulSoup and mf2py to use lxml (#627): mean BS parse 186ms (up 40%), mf2py 1.65s (up 60%). total mf2py CPU time was 17.5x total BS time.

i honestly don't know if those increases were caused by lxml or something else.

i'm going to try out tommorris/mf2py#61 next.

```
{'timed beautifulsoup size': 150055124,
 'timed mf2py size': 4397,
 'timed beautifulsoup': 415654,
 'timed mf2py': 7262877
}
```

**Comment by snarfed** [comment]
hah. from my shell just now:

```sh
hell:~/src/bridgy{lxml}> ./scripts/deploy.sh
...
ERROR: Package version mismatch! Expected:
mf2py==1.0.2
hell:~/src/bridgy{lxml}>
```

the system works! :P

**Comment by snarfed** [comment]
woo! huge success. based on the last 4h, tommorris/mf2py#61 brough mean mf2py parse time down to 300ms. 3-5x speedup! thanks @kylewm!

```
{'timed beautifulsoup size': 166806076,
 'timed mf2py size': 5064,
 'timed beautifulsoup': 489964,
 'timed mf2py': 1517804}
```

**Comment by snarfed** [comment]
noticed that we do a lot of `HEAD`ing silo post URLs that we know are fine as is and won't redirect. we should add some heuristics to skip that, like eg [`Facebook.canonicalize_syndication_url`](https://github.com/snarfed/bridgy/blob/f8a0202175ca8a69f923d441978482fad1436405/facebook.py#L152). adding to the list.

**Comment by kylewm** [comment]
based on the last 4ish hours:

```
timed mf2py: 3584033
timed mf2py size: 1788
```

2s per call :( No guess why there are so many fewer fetches than in the earlier samples.

```
timed beautifulsoup: 209228
timed beautifulsoup size: 67282250
```

So that means it's back up to 17x BS, suspiciously close to what it was before the backcompat changes. 

Rolling back mf2py to 1.0.3 and deploying again.

**Comment by kylewm** [comment]
BTW, remote_api_shell was not working for me. I tried creating service credentials and setting the environment variable they tel you to set, but then it would return "Unauthorized: Too may attempts". Now I have downloaded the Cloud SDK and run `gcloud init`. It did the OAuth2 login thing, and now I can use the shell again.

**Comment by kylewm** [comment]
Well, reverted back to the release version of mf2py, and it's back down to average 232ms, about 3x beautifulsoup.

```
{'timed mf2py size': 1316,
 'timed beautifulsoup size': 47622874,
 'timed mf2py': 306377,
 'timed beautifulsoup': 103728}
```

I'm guessing that when I pip installed mf2py from git, I didn't do it in a way that would deploy to GAE. I'll give it another shot tomorrow.

Testing my changes locally on a bunch of different sites, mf2py.parse is routinely less CPU time than BS4, so that's what I'm hoping to see.

**Comment by kylewm** [comment]
started again with the find_all optimization, I think installed correctly this time, at 11:40

**Comment by kylewm** [comment]
OK over the last ~11 hours, mf2py has averaged 150ms, which is 2x BS parse time. So that seems to be a marked improvement

```
{'timed mf2py size': 3900,
 'timed beautifulsoup size': 153546887,
 'timed mf2py': 590271,
 'timed beautifulsoup': 232768}
```
(Still concerned that the size is 3900 over 11h, when you had another example that was 5000 over 4h... not sure what could cause such a large discrepancy)

**Comment by snarfed** [comment]
hey, that's a big improvement! great news. congrats!

i can think of a couple reasons the volume was lower. 1) i dropped refetch from 2h to 4h, i think since the first round, and 2) the instrumenting was off for a bit today since i deployed over you. (probably mostly 1.)

**Comment by snarfed** [comment]
interesting data point: anecdotally, when i've glanced at the poll queue over the last week or so, it's often idle or only running one poll. i think it used to consistently be running 4-8 at any given time. so, that implies our work here has paid off, and we can close this soon, maybe when #634 is in. yay!

**Comment by snarfed** [comment]
so after tons of work and soul searching and waffling, i think all the optimization here was nice and appreciated, but really the one thing that did the trick all by itself (and didn't drive our latency through the roof) was `max_idle_instances: 1`. whee. :P

<img width="1144" alt="screen shot 2016-03-29 at 3 31 37 pm" src="https://cloud.githubusercontent.com/assets/778068/14126039/659ef6aa-f5c3-11e5-97da-bb2ee28ab83f.png">

tentatively closing for now.
