### ISSUE TITLE
Fails to send webmentions to Known pages with encoded unicode in URL

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy#625]
After recent change in the way Known treats non-ASCII characters when building URLs Bridgy fails to send webmentions to perfectly valid URLs.

Example:
https://brid.gy/log?start_time=1456307139&key=aglzfmJyaWQtZ3lyTgsSCFJlc3BvbnNlIkB0YWc6ZmFjZWJvb2suY29tLDIwMTM6MTAxNTMyNDk2ODQ2ODIwODVfbGlrZWRfYnlfODk1NDYxNDU3MTg4MTAzDA

**Comment by kylewm** [comment]
Oh funny coincidence, I was looking at the same issue. This is internal to Known because just sending a webmention to myself for https://kylewm.com/2016/02/testing-pr%C3%AAt-%C3%A0-porter I get a HTTP 400 error

**Comment by snarfed** [comment]
thanks for triaging, @kylewm! mind referencing the known issue for this if/when there is one?

**Comment by snarfed** [comment]
@nekr0z looks like this should be fixed once https://github.com/idno/Known/issues/1301 is included in the next Known release. thanks again for reporting!
