### ISSUE TITLE
Facebooks new "Reactions" not being pulled?

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#626]
Facebook implemented their new "Reactions" feature today, which has replaced the old "Like" button. I'm not 100% sure, but I think bridgy doesn't seem to pull those now? I'm fairly sure I've had a few "reactions" including a "Love" which haven't pulled through.

Any ideas?

**Comment by snarfed** [comment]
interesting! [doesn't look like they're in the API yet.](http://stackoverflow.com/questions/35606109/getting-facebook-reactions-with-graph-api-2-5) i'll keep an eye on the [changelog](https://developers.facebook.com/docs/apps/changelog).

fwiw, i don't actually see them in my FB account yet. :P

**Comment by snarfed** [comment]
oh, btw, i'm not sure exactly how we'd backfeed these. i guess [reacji](https://indiewebcamp.com/reacji)? but we'd special case the thumbs up one and keep interpreting that as a like? or maybe they'd all be likes, and we'd include the emoji as content? except doesn't seem appropriate for the negative ones, e.g. :cry: and :angry:. who knows.

**Comment by aaronpk** [comment]
There has been some experiments with posting and receiving reacji documented here: https://indiewebcamp.com/reacji#How_to_markup

Should be simple enough to send an `in-reply-to` URL with the content being the reaction. It has the added benefit of receivers treating them as regular comments if they don't roll them up like Ben does here: https://ben.thatmustbe.me/note/2015/12/8/2/

**Comment by armingrewe** [comment]
Yes, I was wondering that as well. There are 6 options now, including the original "like". The new ones are Love, Angry, Sad, Haha and Wow. Just saying "xyz reacted to this" seems wrong as well.

I can see them since I got home about three hours ago (it's 21:00hrs here now), but I hear not everyone can see them yet.

**Comment by armingrewe** [comment]
Quick update after this morning's post: it looks like if from the six options the "like" is used it still comes through on bridgy. If they pick one of the five new options they are not coming through. I'll keep watching and update of I spot anything different.

**Comment by barnabywalters** [comment]
+1 it’d be great to get the other reactions implemented as reacji, if they ever show up in the API

**Comment by snarfed** [comment]
woo! they did indeed add a reactions API in v2.6, announced today at F8.

https://developers.facebook.com/blog/post/2016/04/12/introducing-graph-api-v26/
https://developers.facebook.com/docs/graph-api/reference/post/reactions

the downside is that we have to upgrade all of our facebook usage to API v2.6...i assume? i wonder if we could just use v2.6 for reactions. i *think* we can't because access tokens are API version specific, but not sure. worth investigating.

if we do need to upgrade, that will require #496 and #433 at least, probably more.

**Comment by snarfed** [comment]
ooh this looks like it will help find everything we need to upgrade: https://developers.facebook.com/tools/api_versioning

**Comment by snarfed** [comment]
huh. i was actually able to make a v2.6 API request, [`/212038_10102223481816413?fields=reactions`](https://developers.facebook.com/tools/explorer/?method=GET&path=212038_10102223481816413%3Ffields%3Dreactions&version=v2.6), with a v2.2 access token after all. so i guess access tokens aren't versioned after all, or at least aren't strictly versioned, so we can mix and match different API version requests with the same token. lets us upgrade versions gradually, which is nice.

https://developers.facebook.com/docs/apps/versions#calling_older_versions
