### ISSUE TITLE
show warning if last n posts (say 10ish) are private

### ISSUE THREAD

**Issue by srcr** [snarfed/bridgy#632]
I notices that Brid.gy isn't sending anything back to my server

[My post](https://srcr.nl/2016/gisteren-toru%C5%84-bezocht-het-beeld-is-van-copernicus-die-uit) has no comments and likes on my site
![4untitled](https://cloud.githubusercontent.com/assets/1507320/13671939/fb6e572a-e6d2-11e5-9797-e8941da4675d.png)

but on facebook I have 4 comments and 12 likes
![2](https://cloud.githubusercontent.com/assets/1507320/13671877/bee979ba-e6d2-11e5-9fd8-3ac177f1a7b5.png)

Also Bridgy self states it hasn't send anything back the last 3 months
![1](https://cloud.githubusercontent.com/assets/1507320/13671896/d5d6b67e-e6d2-11e5-9ac1-6a08f07a5f60.png)

Can you check from you end to see what the problem is?

**Comment by snarfed** [comment]
hi peter, sorry for the trouble! it looks like none of your facebook posts are public. bridgy deliberately only backfeeds public posts. http://brid.gy/about#missing

other people have asked about this recently too, so i'm going to keep this issue open and have bridgy show a warning when it notices this is happening. thanks for the nudge!

**Comment by snarfed** [comment]
might obviate #628. related to #304.

**Comment by srcr** [comment]
Hi @snarfed,

Thanks for the explanation, makes a lot of sense also when i read the logs

```
2016-03-10 13:45:10.846110 I requests.head https://facebook.com/10205968656197024 {}
2016-03-10 13:45:10.940370 I Starting new HTTPS connection (1): facebook.com
2016-03-10 13:45:11.228120 D "HEAD /10205968656197024 HTTP/1.1" 301 None
2016-03-10 13:45:11.538650 I Starting new HTTPS connection (1): www.facebook.com
2016-03-10 13:45:11.741349 D "HEAD /10205968656197024?_rdr HTTP/1.1" 404 None
2016-03-10 13:45:12.232150 W Couldn't resolve URL https://facebook.com/10205968656197024 : 404 Client Error: Not Found
```

I made my post public and also made it that the site posts as public to prevent future issues.
Comments and likes are already pouring in.

Thanks for the hel
