### ISSUE TITLE
Support multiple response types in the same post

### ISSUE THREAD

**Issue by barnabywalters** [snarfed/bridgy#635]
…if that’s not possible or awkward, document which will take priority if multiple are provided. For example, this post https://waterpigs.co.uk/notes/4gG89z/ is both a photo and an  event RSVP, but when POSSEing to facebook using Publish it was treated just as a photo. From this I can assume that presence of a u-photo takes priority over presence of u-in-reply to p-rsvp — where do other response types fit into this?

**Comment by snarfed** [comment]
good point! at minimum, we should think through the order of precedence (and document it) more deliberately. rsvp should probably come before photo, for example. :P

do you know if there's any prior art or best practice documented anywhere for this yet? I'll go look on the wiki in a bit.

**Comment by snarfed** [comment]
we're probably more likely to just document the order of precedence than to try to get multi posting right. beyond problems like atomicity, we don't necessarily know the user's intent. i can imagine someone else with the same post might be a bit surprised if bridgy posted the rsvp and also the photo, separately. (maybe no more surprised than us choosing one, though. not sure.)

@barnabywalters if you're interested in a more powerful and configurable posse tool, definitely check it @kylewm's https://silo.pub/ ! more background: https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb , https://kylewm.com/2015/11/silo-pub-as-a-generic-micropub-to-silo-adapter

**Comment by barnabywalters** [comment]
Sounds good to me, at the moment at least I’m very happy to continue using a “dumb” tool, provided I can understand exactly how it’s dumbness works :) So documenting the order of precedence would be great.

**Comment by snarfed** [comment]
i dug into this a bit more, and we actually interpreted this specific post as a note with photo instead of an RSVP because it has `class="h-as-note"`, which overrides post type discovery (http://indiewebcamp.com/post-type-discovery).

`h-as-*` classes are evidently deprecated, so the fix is probably just to remove support for them and fully follow post type discovery. easy to document too. :P
