### ISSUE TITLE
drop legacy (2+ years deprecated?) u-like u-repost

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#640]
Bridgy should drop use of legacy (>2 yrs deprecated) u-like u-repost class names, e.g.

s/class="u-like u-like-of"/class="u-like-of"

s/class="u-repost u-repost-of"/class="u-repost-of"

**Comment by tantek** [comment]
related: https://github.com/acegiak/Semantic-Linkbacks/issues/28

**Comment by snarfed** [comment]
:+1: yes! first attempt was #430.
