### ISSUE TITLE
OPD: truncate Instagram syndication URLs at 11 chars before comparing

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#641]
Instagram permalinks are different lengths depending on if the photo was posted while the account was public or private!

E.g. this photo was posted when the account was private:
https://www.instagram.com/p/BDCv87dA9R_ibz5dUgymJjtGo2XiKl7o42gCQc0/
However, it's public permalink is actually just the first 11 characters of the ID, i.e.:
https://www.instagram.com/p/BDCv87dA9R_

If Bridgy were to always truncate IG permalink URLs at 11 characters, it would be able to compare previously private photos with public syndication and vice versa.

Useful for when someone had private photos for a while, then switched to public, and used shorter permalinks - this would allow them to get Bridgy backfeed on their newly public photos.

**Comment by snarfed** [comment]
ack! definitely an unusual use case (switching back and forth btw private and public), but it does seem like this would handle it well.

**Comment by snarfed** [comment]
Closing as obsolete; Bridgy's Instagram support is dead.
