### ISSUE TITLE
My server being blocked?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#642]
When I try `curl -i https://brid-gy.appspot.com/like/twitter/singpolyma/712687111254597633/1588576836` from my new server, I get:

```
HTTP/1.1 403 Forbidden
Date: Mon, 04 Apr 2016 14:20:48 GMT
Content-Type: text/html
Server: Google Frontend
Content-Length: 434
Alternate-Protocol: 443:quic
Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"

<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>403 Sorry...</title>
<style>body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style>
</head><body>
<div style="margin-left: 4em;">
<h1>We're sorry...</h1>
<p>... but your computer or network may be sending automated queries.
To protect our users, we can't process your request right now.
</p>
</body></html>
```

**Comment by singpolyma** [comment]
If I use `curl -4` if fixes things, so I'm only blocking from accessing over IPv6?  My IPv6 block is `2607:5300:60:9e74::/64`

**Comment by snarfed** [comment]
wow, true! sorry about that. details: https://github.com/snarfed/bridgy/issues/578#issuecomment-196553529 , https://github.com/snarfed/bridgy/blob/master/dos.yaml#L5

you're evidently on the same ISP as Domain Re-Animator Bot, which i blocked because it behaves very badly. i'll figure out a narrower IP block.

**Comment by singpolyma** [comment]
Whew!  Glad it's not a generic google blocking me thing :P 

That whole /64 should be under my control, so as long as you're narrower than that, I should be fine

**Comment by snarfed** [comment]
cool. i've narrowed those two blocks to /64s too.  feel free to try again!

**Comment by singpolyma** [comment]
Working now, thanks!
