### ISSUE TITLE
Backfeed photos in comments on facebook

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#646]
https://singpolyma.net/actionstream/orange-office/#comment-255293 the comment on facebook contains a photo, which could at least be linked to in the content, perhaps?

**Comment by snarfed** [comment]
yes!

...except it doesn't look like they're in the API. :/

comment: https://developers.facebook.com/tools/explorer/?method=GET&path=10153737107208051_10153737214418051&version=v2.2
```json
{
  "created_time": "2016-04-08T13:57:22+0000",
  "from": {
    "name": "Paul Weber",
    "id": "10153596654619408"
  },
  "message": "Orange you glad it's yours ;-) enjoy",
  "can_remove": true,
  "like_count": 2,
  "user_likes": false,
  "id": "10153737107208051_10153737214418051"
}
```

post: https://developers.facebook.com/tools/explorer/?method=GET&path=515373050_10153737107208051&version=v2.2
```json
{
  "id": "515373050_10153737107208051",
  "comments": {
    "data": [
      "...",
      {
        "created_time": "2016-04-08T13:57:22+0000",
        "from": {
          "name": "Paul Weber",
          "id": "10153596654619408"
        },
        "message": "Orange you glad it's yours ;-) enjoy",
        "can_remove": true,
        "like_count": 2,
        "user_likes": false,
        "id": "10153737107208051_10153737214418051"
      }
    ]
  },
  "..."
}
```

**Comment by snarfed** [comment]
aha, i have to add `?fields=attachment`:

```json
{
  "attachment": {
    "media": {
      "image": {
        "height": 405,
        "src": "https://scontent.xx.fbcdn.net/hphotos-xat1/v/t1.0-9/s720x720/12932713_10154842838994408_8485929365544529955_n.jpg?oh=d27b9a87ea83b77f00ef1f30a78d914d&oe=5775B834",
        "width": 720
      }
    },
    "target": {
      "id": "10154842838994408",
      "url": "https://www.facebook.com/photo.php?fbid=10154842838994408&set=p.10154842838994408&type=3"
    },
    "type": "photo",
    "url": "https://www.facebook.com/photo.php?fbid=10154842838994408&set=p.10154842838994408&type=3"
  },
  "id": "10153737107208051_10153737214418051"
}
```

**Comment by snarfed** [comment]
fighting facebook's API data model recently (#575, #633, etc) has burnt me out on it pretty thoroughly, so i'm not likely to tackle this myself in the near future, just fyi. i'm all for it though! should hopefully be pretty straightforward, probably all in [`granary/facebook.py`](https://github.com/snarfed/granary/blob/hub/granary/facebook.py). we already to it for tweets, and that works ok.

**Comment by tantek** [comment]
@snarfed same issue for Twitter @-replies with photos? Or new issue?

**Comment by snarfed** [comment]
@tantek bridgy backfeed already supports photos in twitter @-replies! i don't have an example handy, but i know they exist.

you can see how it renders them in eg https://brid.gy/post/twitter/acegiak/718400075131527172

**Comment by snarfed** [comment]
ok i lied. i knew this would be small and unrelated to the other data model ugliness, so i went ahead. :P

@singpolyma bridgy's mf2 for this seems ok - https://brid-gy.appspot.com/comment/facebook/515373050/10153737107208051/10153737107208051_10153737214418051 - but when i retried sending that wm, your site didn't like it: https://singpolyma.net/actionstream/orange-office/#comment-255293 . i'll leave this issue open for now.

**Comment by singpolyma** [comment]
Looks related to https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/39 -- I'll check it out.

Thanks so much for your help on this!
