### ISSUE TITLE
improve error mesage when Publish is not enabled

### ISSUE THREAD

**Issue by mblaney** [snarfed/bridgy#648]
When someone who hasn't registered tries to use bridgy publish from a domain with multiple users, an error message is returned containing all the accounts on the domain that have registered. It should probably just direct them towards https://brid.gy

**Comment by snarfed** [comment]
agreed! feel free to send a PR if you want!

**Comment by mblaney** [comment]
done https://github.com/snarfed/bridgy/pull/649
