### ISSUE TITLE
Wrong post links for Webmentions after re-enabling Facebook sync

### ISSUE THREAD

**Issue by skddc** [snarfed/bridgy#650]
I just noticed that Bridgy had stoppd syncing my FB posts to Known a while ago. It offered the auth link on the respective bridgy page, so I re-enabled it with that. But now it's using wrong URLs to my posts, which I can't find anywhere in my markup.

Here's an example:

Facebook post: https://www.facebook.com/10153093120378440/posts/10153717682573440
Original post with correct syndication markup: https://updates.kip.pe/2016/finally-booked-flights-out-of-colombia-next-up-in-varying
URL brid.gy is trying to send Webmentions to: https://updates.kip.pe/10102571892817971/finally-booked-flights-out-of-colombia-next-up-in-varying

So instead of `/2016/some-slug` it is replacing the year with some ID, which a) I can't find anywhere on my site and b) looks a lot like a Facebook ID of some sort.

**Comment by kylewm** [comment]
Take a look at https://github.com/snarfed/bridgy/issues/368 and https://github.com/idno/Facebook/issues/31 ... these should at least explain the issue. If you update your Facebook plugin, it should stop using the problematic "See Original" link.

It is not a complete fix; for now you'd have to include a link from your Facebook post back to your site by turning "Include permalinks" on in your Known settings for Bridgy to find the relationship between your facebook post and the original.

**Comment by skddc** [comment]
Ok, thanks!

It seems like Bridgy is using metadata from FB (i.e. "original link") instead of the syndication markup on my site then, correct? If that's the case, then wouldn't it make sense to change that to using the markup on the original site?

**Comment by kylewm** [comment]
[posse-post-discovery](https://indiewebcamp.com/posse-post-discovery) is tricky because Facebook gives Known a URL with an app-scoped user ID when you publishing. So for example, the post  

https://updates.kip.pe/2016/finally-booked-flights-out-of-colombia-next-up-in-varying 

has a u-syndication property that points to 

https://facebook.com/10153093117548440/posts/10153717682573440 

but that user ID (10153093117548440) is only meaningful in the context of Known's app keys. When Bridgy accesses your account to look for replies, it gets a different user ID (10153093120378440). At the moment Bridgy does not know how to match those up, though we have talked about a possible heuristic to fix this in the future.

(PS I'm surprised those two user IDs are actually pretty similar, same first 9 and last 4 characters, what does it mean??)

**Comment by skddc** [comment]
Wow, weird. Thanks for the explanation!

> When Bridgy accesses your account to look for replies, it gets a different user ID (10153093120378440). At the moment Bridgy does not know how to match those up, though we have talked about a possible heuristic to fix this in the future.

What exactly is Bridgy receiving? The same URL, but with a different user ID? Like: https://facebook.com/10153093120378440/posts/10153717682573440 maybe?

It looks like the post ID is the important one. It seem also possible to access the post via username in the URL e.g., like so: https://www.facebook.com/sebastiankippe/posts/10153717682573440

So perhaps it would be easier/better if Known generated the post URL using the username and post ID itself, instead of Bridgy implementing a heuristic for mapping user IDs.

**Comment by kylewm** [comment]
> So perhaps it would be easier/better if Known generated the (syndication) post URL using the username and post ID itself, instead of Bridgy implementing a heuristic for mapping user IDs?

Yes, I've tested that in the past and it works.

The problem is, (believe it or not) Known's FB plugin doesn't have any way to find out your username via the API. We'd have to make it a configuration option or something.

**Comment by skddc** [comment]
> The problem is, (believe it or not) Known's FB plugin doesn't have any way to find out your username via the API. We'd have to make it a configuration option or something.

Ouch. :/

**Comment by snarfed** [comment]
we've removed the See Original OPD support, which will prevent this problem. thanks for the nudge @skddc!

**Comment by kylewm** [comment]
I clicked "Crawl Now" on https://brid.gy/facebook/10153093120378440# and the combination of the two fixes seems to have done the trick!

**Comment by skddc** [comment]
Yay! Thanks!
