### ISSUE TITLE
Trunates too soon for Twitter Publish

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#654]
see https://mobile.twitter.com/singpolyma/status/723250309594636288 -- 125 characters? Couldn't fit the one hashtag?

**Comment by kylewm** [comment]
The composed tweet is 144 characters:
```
Today: food to room, hurry to wrong train, pretty palace&gardens, too much walking, american sandwich bread #honeymoon (http://sngpl.ma/t4gs0)
```

**Comment by singpolyma** [comment]
142, but I guess the URL counts longer. And too long anyway, I suck at counting. I guess my compose limit is like 115 or something now? Sorry for the noise.

**Comment by snarfed** [comment]
np! yeah, sadly all URLs cost 23 chars due to t.co wrapping.
https://dev.twitter.com/overview/t.co#Node--147
https://github.com/snarfed/granary/blob/2fd8ef017588b955e78606242ce582849cfd57ac/granary/twitter.py#L70-81

**Comment by snarfed** [comment]
btw, if you want more tweet real estate, you can always omit the backlink! :P https://brid.gy/about#omit-link

**Comment by kylewm** [comment]
obligatory plug for https://github.com/snarfed/bridgy/issues/561 :)
