### ISSUE TITLE
brid.gy does not find website in facebook profile anymore

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#658]
didn’t manage to reopen #393 so i duplicate it here: facebook does not find my sites anamore, for my personal profile, as well as pages that i admin.

https://www.facebook.com/diplix/about
https://www.facebook.com/wirres/about

changing my website to https does not work either.

**Comment by snarfed** [comment]
thanks for reporting, @diplix! looks like this is due to our in-progress migration to facebook API v2.6. should hopefully be an easy fix.

**Comment by snarfed** [comment]
thanks again for the report!
