### ISSUE TITLE
Photos in Facebook no longer seem to be processed

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy#661]
If two or more photos are published to Facebook in a short period of time, Facebook unites them into one publication. Brid.gy doesn't seem to have a way of processing such a publication, and ignores the photos altogether, even though all of them have proper links to original.

**Comment by snarfed** [comment]
@nekr0z that's true! this is an unfortunate facebook feature that we don't have much control over. when it consolidates photos like this, it also generally stops saying whether those photos are public or private, and we only backfeed when we know for sure that a photo (or post, etc) is public. background: https://brid.gy/about#new%20photos

i think you can work around it by posting photos to a specific album. i think any album will work, including _Timeline Photos_, which should make them show up in your timeline.

**Comment by nekr0z** [comment]
@snarfed I don't believe posting to an album would solve this: Known posts to "Known Photos" album by default, and Facebook is happily bundlig those. However, you're probably right in that facebook should better fix this "feature", not brid.gy.

**Comment by snarfed** [comment]
@nekr0z good data point! the "Timeline Photos" album may be special. bridgy publish uses that for publishing photos to defeat the bundling, which definitely works. https://github.com/snarfed/granary/blob/bb7ae6ec0ef392ec944f0c27ac94a4b3b6bd5c5e/granary/facebook.py#L724-727

**Comment by snarfed** [comment]
tentatively closing. hope the known people are open to doing this! (cc @kylewm.) feel free to reopen if necessary...
