### ISSUE TITLE
facebook poll /me/events fails with a 500 error

### ISSUE THREAD

**Issue by diplix** [snarfed/bridgy#664]
https://brid.gy/facebook/548616784#
log: https://brid.gy/log?start_time=1461910659&key=aglzfmJyaWQtZ3lyGwsSDEZhY2Vib29rUGFnZSIJNTQ4NjE2Nzg0DA

error response: 

`Error 500, response body: {"error":{"code":1,"message":"Please reduce the amount of data you're asking for, then retry your request"}}
`

i just reauthenticated, so there should be no problem because of invalid tokens or missing access rights.

**Comment by diplix** [comment]
update: seems, the problem solved itself. now there are no more errors.

**Comment by snarfed** [comment]
thanks for filing! this is actually hitting other people too, still. reopening to track that.

**Comment by snarfed** [comment]
current failing users: https://brid.gy/admin/sources

failing API call: `me/events?fields=rsvp_status,id,attending,comments,declined,description,end_time,interested,maybe,noreply,name,owner,picture,place,start_time,timezone,updated_time`

errors seen (all 500s):
* `{"error":{"code":1,"message":"An unknown error occurred"}}`
* `{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"..."}}`
* `{"error":{"code":1,"message":"Please reduce the amount of data you're asking for, then retry your request"}}`

that last one [is supposedly unrelated](http://stackoverflow.com/questions/29351125/facebook-graphapi-reduce-amount-of-data-with-limit) to [FB's rate limiting](https://developers.facebook.com/docs/marketing-api/api-rate-limiting), but not 100% sure.

possibly related FB bug reports:
* https://developers.facebook.com/bugs/682222548584673
* https://developers.facebook.com/bugs/958397824256856/

[this SO question](http://stackoverflow.com/questions/28370428/facebook-v2-2-me-groups-return-error-code-3) says using a `limit=` smaller than the default fixed it.

**Comment by snarfed** [comment]
this is hitting ~15% of all active facebook users right now.

**Comment by snarfed** [comment]
fixed! closing.
