### ISSUE TITLE
Instagram is blocking our scraping

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#665]
... by returning empty 429s to our profile page HTTP requests. seems like it started under 36h ago. may have happened before too though. eg https://brid.gy/log?start_time=1461974780&key=aglzfmJyaWQtZ3lyFgsSCUluc3RhZ3JhbSIHc25hcmZlZAw

instagram-atom isn't having this problem, and it's using the same IPs, so maybe changing user agent might fix it.

**Comment by snarfed** [comment]
changed our user agent to a normal browser string, which seemed to fix this....but i doubt it'll stay fixed for long. app engine [still appends our app id to the user agent](https://cloud.google.com/appengine/docs/python/outbound-requests#request_headers), so instagram will still be able to identify us. we'll see.

**Comment by snarfed** [comment]
didn't work :(

**Comment by snarfed** [comment]
the 429 body:

<img width="640" alt="screen shot 2016-04-30 at 9 21 43 am" src="https://cloud.githubusercontent.com/assets/778068/14937212/0b88adc2-0eb5-11e6-9fbf-baa380a5c05f.png">

**Comment by snarfed** [comment]
i also dropped instagram max poll freq down to 2h. with that and the new user agent, we're back in business. >75% of active instagram accounts have polled successfully in the last few hrs. eg https://brid.gy/instagram/aaronpk

not sure which of the two changes did the trick. we'll see.

**Comment by snarfed** [comment]
we're still mostly blocked after all. :/ a few fetches went through ok, but they were the exception.

i'm going to disable instagram entirely for a day or two to see if that resets anything on their end.

**Comment by snarfed** [comment]
i wonder if this is all of app engine's (slash google's) IP block, not just bridgy. eg granary-demo sees the same problem: https://granary-demo.appspot.com/?site=instagram

**Comment by snarfed** [comment]
evidence for that: scraping instagram with bridgy's user agent works fine on my local machine.

**Comment by snarfed** [comment]
tried switching to sockets instead of urlfetch in the hopes that it used a different IP block, but no luck. one request made it through out of five, but the other four were 429ed. :/

**Comment by snarfed** [comment]
pinged the app engine mailing list: https://groups.google.com/d/msg/google-appengine/rpendSIxJMo/_u4G6uXiBQAJ

**Comment by snarfed** [comment]
i set up a reverse proxy to get around the IP block.

**Comment by snarfed** [comment]
this has been working ok for a couple days now, yay. we'll see how long it lasts. :P closing.

**Comment by gerbz** [comment]
I noticed you're scraping the profile page - you should checkout /username/media/.  No auth needed.
https://www.instagram.com/snarfed/media/

Discovering [this](http://stackoverflow.com/a/33783840) blew my mind.

Are you using a single IP?  How often are you polling?  Been working for 21+ days since your fix?

**Comment by snarfed** [comment]
@gerbz sadly that only works if you're logged in. http://stackoverflow.com/questions/17373886/33783840#comment61481772_33783840

the proxy was a single IP, yes, but instagram actually stopped blocking app engine recently, so i switched back to fetching directly instead.

we're polling ~1k users between once a day and once an hr, depending on how active they are. each poll may also fetch up to N individual media pages too though. in practice it looks like we average <1qpm right now, slightly bursty.

**Comment by gerbz** [comment]
@snarfed that comment is incorrect - try for yourself.  I've even hit it unauthed using Tor.  Works fine.  Haven't polled it excessively but should work.

Thanks for the info.

**Comment by snarfed** [comment]
good point! you're right. thanks!

**Comment by snarfed** [comment]
@shafikhaan yup! https://brid.gy/ , https://granary.io , and https://instagram-atom.appspot.com are still happily scraping Instagram.

**Comment by shafikhaan** [comment]
@snarfed Which one will you pick from the above ?

**Comment by snarfed** [comment]
@shafikhaan sorry? i don't follow the question.

they all share this scraping code, if that helps:

https://github.com/snarfed/granary/blob/master/granary/instagram.py#L758-L975

**Comment by snarfed** [comment]
we've been scraping with a logged in session cookie for a while now. not ideal, maybe not sustainable, but it's been working. tentatively closing.

**Comment by staabm** [comment]
The website still reports bridgy is blocked? Is this message still up2date?

**Comment by snarfed** [comment]
@staabm which web site? where?

**Comment by staabm** [comment]
![image](https://user-images.githubusercontent.com/120441/78498609-af912900-774b-11ea-8030-3cd1a1cb753a.png)

**Comment by staabm** [comment]
I a getting this erro when trying to add instagram to my brigy account

**Comment by snarfed** [comment]
ah, got it, thanks. I'll look soon!

**Comment by snarfed** [comment]
@staabm thanks again for the report. i think i've fixed this. mind trying again?

**Comment by staabm** [comment]
Thx for the fast fix. The error is gone..

Seems to work now ✌️
