### ISSUE TITLE
Identify placeholder vs real profile pictures

### ISSUE THREAD

**Issue by dshanske** [snarfed/bridgy#667]
When there isn't an image set on Facebook, Twitter, etc....there is a stock image. Wondering if there is a way that Bridgy can either detect this and mark it up, or alternatively, decide this means there is no image and not pass it.

**Comment by snarfed** [comment]
interesting! i don't know if there's an existing mf2 property that means "this image is a placeholder," but agreed, we could definitely invent one, or just omit the image entirely.

most of the work would be finding the silo API fields or image URL regexes that tell us this. the changes would be entirely in granary. this isn't an itch for me personally, so feel free to dive in!

**Comment by pabru** [comment]
Perhaps they could be downloaded and SHA256-hashed, then the hash matched against a list of hashes for known placeholder images? That could work.

**Comment by snarfed** [comment]
@dshanske do you want this? did you have a concrete user-visible feature planned for distinguishing placeholder vs non-placeholder profile photos? and a concrete mf2 property? if not, i may close for lack of interest. haven't heard any other requests for it yet, or any user-visible feature in webmention receivers that would use it.

**Comment by snarfed** [comment]
tentatively closing this due to lack of use case and prior art. feel free to reopen!
