### ISSUE TITLE
WordPress Blocking Bridgy

### ISSUE THREAD

**Issue by mrkrndvs** [snarfed/bridgy#669]
I have been trying to install Bridgy on my self-hosted WordPress blog. After install the suite of plugins, I go to sign in to Bridgy and keep getting the following message:

![screenshot 2016-05-12 at 11 55 20](https://cloud.githubusercontent.com/assets/13294754/15234566/523d5da8-18f6-11e6-8ba9-3a291928e638.png)

Can anyone help?

**Comment by kylewm** [comment]
Hmm, perhaps are you clicking "Wordpress.com" on the Bridgy homepage? If so, sorry that that's misleading -- you actually want to enable services from the first row (Facebook, Twitter, etc.). 

The Wordpress.com service in Bridgy is actually only for people using wordpress.com who can't install the indieweb plugins themselves.

**Comment by mrkrndvs** [comment]
Thank you for that. I was.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/669" class="u-in-reply-to"></a>@mrkrndvs In case you haven't seen it, you should be aware of http://indiewebcamp.com/wordpress. Let us know if we can be of help: http://indiewebcamp.com/WordPress_Outreach_Club

**Comment by mrkrndvs** [comment]
@chrisaldrich can you please elaborate on the Indieweb issues or direct me to more information? Can you use Brid.gy without running the Indieweb plugin?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/669#issuecomment-219349522" class="u-in-reply-to"></a>You could start with http://indiewebcamp.com/Getting_Started_on_WordPress which will walk you through most of the process. You should start with the Webmention Plugin and Semantic Linkbacks to send/receive webmention support and to help comments look better respectively. Brid.gy connects your blog to responses from sites such as Facebook, Twitter, et al. 

Keep in mind that some of the other plugins you'll run across may have small bugs or quirks as they're being actively developed. Most of the plugins in the WordPress.org repository are usually more stable than some you'll run across on GitHub, but those also are dated in terms of development work, so you'll have a better idea how current they are.  You can usually find one or more of us via IRC, or in social media if you need help.
