### ISSUE TITLE
twitter publish: handle spaces in photo URLs

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#670]
spaces in `u-photo` URLs break twitter publish for some reason. not sure why yet. thanks for finding @rrix!

[example log](https://brid.gy/log?start_time=1463385985&key=aglzfmJyaWQtZ3lyXwsSDVB1Ymxpc2hlZFBhZ2UiOGh0dHA6Ly9ub3Rlcy53aGF0dGhlZnVjay5jb21wdXRlci8xNDYzMzgyMzAwLjAtbm90ZS5odG1sDAsSB1B1Ymxpc2gYgICAgIDyiAoM):

```
"properties": {
  "photo": [
    "http://notes.whatthefuck.computer/d44cb6b0-ba1b-48bc-8d19-836de68e934b-IMG_20160515_211534.jpg",
    "http://notes.whatthefuck.computer/d44cb6b0-ba1b-48bc-8d19-836de68e934b-IMG_20160515_233108 (1).jpg",
    "http://notes.whatthefuck.computer/d44cb6b0-ba1b-48bc-8d19-836de68e934b-IMG_20160515_233712 (1).jpg"
  ],
  "..."
}
```

**Comment by snarfed** [comment]
root cause is that we pass these URLs to `urllib2.urlopen` as is, which fetches them as is, and @rrix's server doesn't handle the space and returns 404. if i manually encode the space to a `%20`, the server happily returns the image.

encoding ourselves is nontrivial - preserving the rest of the URL (other than just path? anything else), avoiding double encoding, etc. i'm inclined to either do nothing or port to requests, which does the encoding itself. we'll see.

cc @tantek @kevinmarks. whee!

**Comment by kylewm** [comment]
It sounds like @rrix's site should be doing the encoding so that the mf2
properties have %20 instead of a space
 
On Mon, May 16, 2016, at 11:57 AM, Ryan Barrett wrote:
> root cause is that we pass these URLs to urllib2.urlopen as is, which
> fetches them as is, and @rrix[1]'s server doesn't handle the space and
> returns 404. if i manually encode the space to a %20, the server
> happily returns the image.
> encoding ourselves is nontrivial - preserving the rest of the URL
> (other than just path? anything else), avoiding double encoding, etc.
> i'm inclined to either do nothing or port to requests, which does the
> encoding itself. we'll see.
> cc @tantek[2] @kevinmarks[3]. whee!
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub[4]
>
 

Links:

  1. https://github.com/rrix
  2. https://github.com/tantek
  3. https://github.com/kevinmarks
  4. https://github.com/snarfed/bridgy/issues/670#issuecomment-219513750

**Comment by snarfed** [comment]
...or alternatively @rrix's server could handle and serve the URL paths with spaces. bridgy would work either way, as long as the server can serve the URLs it's emitting.

given that, I'm going to tentatively close. feel free to reopen if you disagree!
