### ISSUE TITLE
Not receiving webmentions via Instagram on WP.org

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#671]
I notice I'm not receiving likes/comments from Instagram via Bridgy (and apparently never have.)

I'm using OwnYourGram to PESOS Instagram photos into a WordPress (.org) site, which are then marked has having been syndicated using the Syndication Links WP plugin. The Instagram post naturally doesn't have a link to my web site's post, but my sites's post does have rel-syndication and u-syndication like so: `<a title="Instagram" class="u-syndication" href="https://www.instagram.com/p/BFcP4knxC6m/" rel="syndication"></a>`

Is there some other smaller fine point I'm missing from the Brid.gy about page and support? Has anyone else seen this with WP (.org)?

Cross reference:
https://brid.gy/instagram/chrisaldrich#
https://www.instagram.com/chrisaldrich/ 
with post https://www.instagram.com/p/BFcP4knxC6m/ "syndicated" from http://boffosocko.com/2016/05/15/55672649/

**Comment by snarfed** [comment]
sorry for the trouble, chris!

https://brid.gy/instagram/chrisaldrich#responses shows that bridgy sees your IG likes and comments, but doesn't know where to send them. clicking on the "X minutes ago" link after "Web site crawled..." [goes to this log](https://brid.gy/log?start_time=1463438730&key=aglzfmJyaWQtZ3lyGwsSCUluc3RhZ3JhbSIMY2hyaXNhbGRyaWNoDA), which shows that bridgy isn't finding an `h-feed` or any `h-entry`s on your front page. if you add those, or just add a [rel-feed](http://indiewebcamp.com/rel-feed) pointing to a page with an `h-feed` or `h-entry`s, bridgy should find your syndication links!

**Comment by snarfed** [comment]
btw, gory details of parsing the mf2 in http://boffosocko.com/ : http://pin13.net/mf2/?url=http://boffosocko.com/

**Comment by snarfed** [comment]
oh, and docs for this: https://brid.gy/about#link

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/671#issuecomment-219580229" class="u-in-reply-to"></a>Thanks @snarfed, I'll see if I can't manage to get it sorted. Looks like I'm going to have to hack my theme a good bit to support this and other fun. I'll see if I can't post the details to IndieWebCamp and other relevant locations for others shortly as well. Thanks as always for having done the lion's share of the heavy lifting.

**Comment by snarfed** [comment]
you're welcome! good luck!
