### ISSUE TITLE
About/FAQ missing reference to webmention-endpoint?

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#673]
In the FAQ https://brid.gy/about#endpoint there's a line about "Why do I have to add that line of HTML to my blog?"

Am I now missing it or did the actual line of HTML that's being referred to disappear from the page in an update? 

I'm presuming it's referring to:
`<link href="http://yourwebsite.host/webmention-endpoint" rel="webmention" />` or on WordPress
`<a rel="webmention" href="https://www.brid.gy/webmention/wordpress"></a>`

I think the brid.gy interface prompts the user to include such a line when signing up for service, but it may also make sense to mention it on this page in this section somewhere for completeness? It could certainly be referenced here for those reading the "about" page prior to actually attempting to set things up.

**Comment by snarfed** [comment]
interesting idea! i don't think i've ever had the actual HTML in the docs. that's deliberate, since it's a bit different for each service, especially the instructions and where to add it. it is in the UI during the signup flow, you're right, which is better since then i know which service they're on, and other config details. i'd rather not confuse people by putting all those details in the docs too, since people will inevitably follow the wrong instructions.

i think i still prefer it that way, but i'm open to arguments otherwise...

**Comment by kylewm** [comment]
Echoing what snarfed said, the markup is actually really different per service ... e.g., Tumblr lets you edit the template and add &lt;link> tags in the header, but Wordpress.com only lets you add &lt;a>'s in a widget in the body.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/673#issuecomment-220480776" class="u-in-reply-to"></a>I'm always a fan of instructions being built intuitively into the UI flow, to guide new users along, especially if they have a solid idea of what they're getting into in the first place. In this particular instance, the reference to the HTML was a tad too nebulous and may confuse many -- especially those who begin reading rather than jumping right in.

Shortly the indieweb will be so big that totally tyro users with no facility with code will be on the doorstep and will need better explanations/instructions. Perhaps I'll take some time in the coming months to put together simple walk thrus for the handful of major platforms? If you think it's worthwhile, can you let me know, based on the current userbase (or even recent growth in the past 6months-year), how you'd rank them in order of priority so we can help the biggest groups first? Or perhaps it's worth starting at the lowest hurdle for the least technical users (Tumblr/Blogger?) and building toward the more technical (WordPress.com)? (I'd presume most above this level are okay with most of what exists now).

I'm presuming that Brid.gy was originally meant as a "code" bridge to connect activity on silos, but I can also see it as taking on a secondary meaning in providing the initial value and impetus to bridge users into to the bigger IndieWeb movement.

**Comment by snarfed** [comment]
heh, you made me https://www.google.com/search?q=define%3Atyro ! :P

point taken. we can definitely consider expanding that part of the docs. and walkthroughs for major platforms would be great! we try to do that somewhat with http://indiewebify.me/ , https://indiewebcamp.com/Getting_Started , https://indiewebcamp.com/web_hosting , etc., but they can definitely be improved. maybe start there to see what we have so far?

and you're right, bridgy is intended to bridge the indieweb and silos, both social networks and web/blog hosts. i'm all for improving it, but making it a catch-all tutorial/intro to the indieweb as a whole is a bit out of scope. http://indiewebify.me/ , the wiki, and/or new walkthroughs like you describe are probably more appropriate places...?

**Comment by kylewm** [comment]
@tantek has used it in the "Bridge to bring in new users" sense before, too!
