### ISSUE TITLE
support bridgy-omit-link and -ignore-formatting as webmention target query params

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#675]
right now, [we support `bridgy-omit-link` and `bridgy-ignore-formatting`](https://brid.gy/about#omit-link) as query params in the webmention request itself, e.g. `/publish/webmention?source=...&target=...&bridgy-omit-link=true`, and as mf2 elements. we should support them as query params on the webmention _target_ too, e.g. `target=https://brid.gy/publish/twitter?bridgy-omit-link=true` (modulo url encoding).

[inspired by](http://indiewebcamp.com/irc/2016-06-30#t1467317871902) @miklb and @gregorlove.

**Comment by kylewm** [comment]
I think no. That way lie madness 😱

**Comment by snarfed** [comment]
yeah? why? i believe you, just curious. :P

**Comment by kylewm** [comment]
Now that I thought about it a little more, I think it's a really good idea :+1:. This way you can stick

```
<a href="https://brid.gy/publish/twitter?bridgy-omit-link=true"></a>
```

in your code and it'll work the way people already expect. I vaguely remember this happening before too.

(original objection was: allowing parameters to nest in various/arbitrary ways sounded confusing)

**Comment by miklb** [comment]
In my case once I understood, I was able to adapt my workflow to get the desired result (omit the link) but a +1 as I could see it benefitting static site users who have less control than I do over the build/deploy process.
