### ISSUE TITLE
Notification of webmention failures

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#677]
I'd like to be notified (by XMPP or SMTP) when bridgy webmentions to my domain fail for any reason. Site upgrades, etc, sometimes break things and it can take time for me to notice, during which I miss messages.

**Comment by snarfed** [comment]
hoo boy. interesting! we only have email/XMPP addrs for a fraction of accounts, either from mf2 on their home page or their FB profile (if it's there), and this would definitely take some work, but we could consider it.

**Comment by snarfed** [comment]
one low tech way to do this would be a cron job that polls [bridgy's api](https://brid.gy/about#api) for each of your user pages and looks for `p-bridgy-status="failed"` (or `error`). e.g.:

```sh
curl 'https://mf2.kylewm.com/?url=https://brid.gy/twitter/singpolyma' | grep -E 'error|failed'
...
```

**Comment by snarfed** [comment]
tentatively closing, given the API. feel free to reopen!
