### ISSUE TITLE
Facebook photo albums

### ISSUE THREAD

**Issue by OliverJAsh** [snarfed/bridgy#678]
Would you consider supporting Facebook photo albums? My use case is I upload my photo albums to my blog (samefourchords.com), and I want to be able to push and pull this to silos.

Thanks for the awesome software.

Olly

**Comment by snarfed** [comment]
definitely sounds doable! not an itch for me personally, but I'd happily accept PRs.

first thing to check is whether we've nailed down mf2 for photo albums yet. see if there's anything on https://indieweb.org or http://microformats.org/wiki/microformats2 , or ask in #indieweb on freenode?

**Comment by tantek** [comment]
Hoping to see brainstorming for album microformats markup start appearing on https://indieweb.org/album based on existing IndieWeb publishing practices

**Comment by snarfed** [comment]
bridgy publish for facebook will disappear soon (#817), so I'm closing open issues for it. sad. feel free to holler if you disagree.
