### ISSUE TITLE
brid.gy publish to flickr: "Could not find content in h-entry or any other element!"

### ISSUE THREAD

**Issue by iamwebrocker** [snarfed/bridgy#679]
Hi,
something seems to have changed in the recent two months (last time I possed a picture to flickr)?

Today I'm getting the error "Could not find content in h-entry or any other element!" and in the brid.gy log I see

```
2016-07-10 15:36:44.219390 D publishing object type note to Flickr
2016-07-10 15:36:44.307470 I Object type(s) set([u'h-entry']) not supported; error=Cannot publish type=note to Flickr.; trying next.
2016-07-10 15:36:44.313160 W Could not find content in <a href="http://microformats.org/wiki/h-entry">h-entry</a> or any other element!
None
```
Here is the source code of [the image-post ](https://www.webrocker.de/2016/07/10/skyline-am-main/) in my (WordPress)Blog; to me everything regarding the mf2 seems to be ok (?):

```
<div id="post-25235" class="h-entry post-25235 post type-post status-publish format-image has-post-thumbnail hentry category-geknipst tag-frankfurt tag-grass tag-skyline tag-skyscaper post_format-post-format-image" >
	<h2 class="post-title p-name">Skyline am Main</h2>
	<div class="post-content e-content">
		<p><a class="thickbox" href="https://www.webrocker.de/blog/wp-content/uploads/2016/07/maincafe_IMG_2633.jpg"><img class="alignnone wp-image-25236 size-medium" src="https://www.webrocker.de/blog/wp-content/uploads/2016/07/maincafe_IMG_2633-800x600.jpg" alt="Skyline am Main" width="800" height="600" srcset="https://www.webrocker.de/blog/wp-content/uploads/2016/07/maincafe_IMG_2633-800x600.jpg 800w, https://www.webrocker.de/blog/wp-content/uploads/2016/07/maincafe_IMG_2633-300x225.jpg 300w, https://www.webrocker.de/blog/wp-content/uploads/2016/07/maincafe_IMG_2633-1200x900.jpg 1200w" sizes="(max-width: 800px) 100vw, 800px" /></a><a href="https://brid.gy/publish/flickr"></a></p>
	</div>
(... post footer )
</div>
```

**Comment by snarfed** [comment]
thanks for the detail! looks like your `img` is missing `class="u-photo"`. details: https://brid.gy/about#picture

**Comment by iamwebrocker** [comment]
oh d'oh. I swear I looked over the source again and again, but this escaped me. Sorry for the bother an thanks for the fast reply! <3

**Comment by ScootRay** [comment]
I seem to be having this issue with Wordpress --> Flickr. I'm getting this error:

```
I 2021-02-08 07:52:44.805459 Object type(s) {'h-entry'} not supported; error=Cannot publish type=article to Flickr.; trying next.
I 2021-02-08 07:52:44.805753 Could not find content in <a href="http://microformats.org/wiki/h-entry">h-entry</a>; or any other element!

```
..even though I can confirm the image has the "u-photo" item in the img class:

`<img class="u-photo alignnone wp-image-4541 size-full" src="https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro.jpg" alt="" width="1598" height="1065" srcset="https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro.jpg 1598w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-300x200.jpg 300w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1024x682.jpg 1024w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1536x1024.jpg 1536w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-768x512.jpg 768w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1000x666.jpg 1000w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-500x334.jpg 500w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1400x933.jpg 1400w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-1320x880.jpg 1320w, https://flyingcdn-1007c4.b-cdn.net/wp-content/uploads/2021/01/El_Morro-300x200@2x.jpg 600w" sizes="(max-width: 1598px) 100vw, 1598px" loading="eager" style="opacity: 1;">`

Is there anything else I can do to fix this?

Many thanks for providing a wonderful service!
Ray
