### ISSUE TITLE
add ability to clear old syndication links

### ISSUE THREAD

**Issue by OliverJAsh** [snarfed/bridgy#680]
I am setting up my site to use brid.gy, mostly through a process of trial and error. Brid.gy is storing lots of old incorrect relationships from previous crawls of my websites. Is there a way to clear out all data/relationships Brid.gy has for my website?

**Comment by snarfed** [comment]
interesting! by relationships, you mean `u-syndication` links from posts on your web site to POSSE copies on social network silos?

if so, the old ones shouldn't hurt. once bridgy crawls your new site (you can trigger this by clicking the Crawl Now button on your user page), it will add any new `u-syndication` links, which should be all you need.

if you mean something else, mind adding some details and example links?

**Comment by OliverJAsh** [comment]
Take a look at this: https://brid-gy.appspot.com/like/facebook/1051748518251476/1051774048248923/306748659660390?format=json.

The `like-of` field is showing lots of old relationships which I added during my testing. They no longer exist on my website, by bridgy continues to show them. I want to clear these relationships, as if to start again.

I guess it doesn't hurt to keep the old relationships, but would be nice if there was a way to clear them. :-)

**Comment by snarfed** [comment]
got it. thanks!

agreed, it shouldn't hurt that the old relationships stick around. there shouldn't be any user-facing change in behavior with and without them, other than that the mf2 pages like that link have extra data in them, so i probably wouldn't add a user-visible operation to clear them (sorry), but i'm happy to leave this open to track the idea!

**Comment by snarfed** [comment]
tentatively closing since old stored syndication links shouldn't have any user-visible impact. feel free to reopen if you disagree!
