### ISSUE TITLE
listen: support hash/fragment permalinks to entries inside feeds

### ISSUE THREAD

**Issue by OliverJAsh** [snarfed/bridgy#681]
I have a `h-entry` with a relative hash fragment as its `u-url`. It seems like bridgy got confused about this and added other entries to the relationship. Do you know whether bridgy could support hash fragment URLs?

**Comment by snarfed** [comment]
hmm! do you mean for backfeed, ie sending back replies/likes? in general, specific example link(s) and specific details help with bug reports like this one. mind adding them here?

**Comment by OliverJAsh** [comment]
Take a look at this: https://brid-gy.appspot.com/like/facebook/1051748518251476/1051774048248923/306748659660390?format=json.

The `h-entry`s in my feed contained `u-url`s like so:
```
<div class="h-feed">
  <article class="h-entry">
    <a href="#foo1" class="u-url"></a>
    <!-- syndications go here -->
  </article>
  <article class="h-entry">
    <a href="#foo2" class="u-url"></a>
    <!-- syndications go here -->
  </article>
  <article class="h-entry">
    <a href="#foo3" class="u-url"></a>
    <!-- syndications go here -->
  </article>
</div>
```

However it appears that bridgy did not pick these up correctly. Take a look at [this entity](https://brid-gy.appspot.com/like/facebook/1051748518251476/1051774048248923/306748659660390?format=json):

```
"like-of": [
"https://www.facebook.com/1051748518251476/posts/1051774048248923",
"https://samefourchords.com/2016/07/09/pottery-class-lewes",
"https://samefourchords.com/timeline#IMG_9020.jpg",
"https://samefourchords.com/timeline#IMG_9092.jpg",
"https://samefourchords.com/timeline#IMG_9014.jpg",
"https://samefourchords.com/timeline#IMG_9085.jpg",
"https://samefourchords.com/timeline#IMG_9093.jpg",
"https://samefourchords.com/timeline#IMG_9082.jpg",
"https://samefourchords.com/pottery-class-lewes/IMG_9092.jpg",
"https://samefourchords.com/timeline#IMG_9011.jpg",
"https://samefourchords.com/timeline#IMG_9077.jpg",
"https://samefourchords.com/timeline#IMG_9037.jpg",
…
```

It has many different hash fragment URLs, when it should only have one. Sorry, this is quite difficult to explain!

**Comment by OliverJAsh** [comment]
Tested again, this is definitely happening! https://brid-gy.appspot.com/like/facebook/1051748518251476/1051774048248923/306748659660390?format=json

**Comment by snarfed** [comment]
thanks for the details!

the short answer is, bridgy doesn't officially support backfeeding to (or publishing) hash-based permalinks to items inside a feed. it doesn't explicitly block them, but i definitely haven't designed or tested for them, so i'm not surprised that you're seeing weird behavior.

so far, the vast majority of indieweb precedent uses permalinks to full-fledged individual pages for posts, so i'm not sure that we'd try to support this. i'm open to talking more though!

i also haven't fully grokked your setup yet. eg i don't see your example markup above (or even `h-feed` `u-url`) on https://samefourchords.com/ , https://samefourchords.com/timeline, or https://samefourchords.com/2016/07/09/pottery-class-lewes . parsing those pages with eg https://mf2.kylewm.com/ doesn't show any mf2.

**Comment by snarfed** [comment]
the similar feature request for publish is #445.

**Comment by snarfed** [comment]
This setup still isn't supported or planned any time soon. Adding the `speculative` label and tentatively closing. Feel free to reopen!
