### ISSUE TITLE
Webmentions failing sporadically

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#682]
Sometime in the last week I find I'm sporadically missing webmentions from both Twitter and Facebook. It doesn't happen all the time, but I feel like I'm missing about a quarter or so of what should be coming back.

I've tried resending them through the brid.gy UI and it seems they then make it about 50% of the time.

The responses I'm seeing on those that fail are similar to the text below

> 2016-07-11 09:48:49.613280 I Giving up this target. {'body_json': {u'error': u'Could not find WordPress.com account for boffosocko.com. Is it registered with Bridgy?'}, 'code': '...', 'request': u'POST https://www.brid.gy/webmention/wordpress (with source=https://brid-gy.appspot.com/react/facebook/5410052/10101051440366925/10152707877027963/10101051440366925_wow_by_10152707877027963, target=http://boffosocko.com/2016/07/10/lunch-at-wordcamp-orange-county/)', 'http_status': 400}

This appears to me to be that Brid.gy thinks I have a WordPress.**COM** account rather than a self-hosted .**ORG** version. I'm unsure what could be causing this and don't seem to find any type of commonality for why some fail while others go through.

**Comment by snarfed** [comment]
sigh, yeah, i saw those too. sorry for the trouble, and thanks for filing! we'll investigate.

**Comment by snarfed** [comment]
aha. you've gone indieweb, um, a little too aggressively. :P

your site is advertising both your webmention plugin's endpoint and bridgy's. e.g on http://boffosocko.com/2016/07/10/lunch-at-wordcamp-orange-county/ i see:
```html
<a rel="webmention" href="https://www.brid.gy/webmention/wordpress"></a>
...
<link rel="http://webmention.org/" href="http://boffosocko.com/?webmention=endpoint" />
<link rel="webmention" href="http://boffosocko.com/?webmention=endpoint" />
```

if you remove the first one that points to bridgy, that should fix this.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/682" class="u-in-reply-to"></a>Thanks @snarfed, brilliant find as I wouldn't have thought of it.  I took out the first one which I'd had hiding in a widget and moved into my header for clarity a few months back.

I vaguely recall putting the others in many months ago, but honestly I can't remember for the life of me where they came from (probably IWC) or which portion of my WordPress is actually generating them now. I also don't seem to recall where I was hiding my code that injects my rel="icon" photos (primarily for shortcut buttons on iOS and Android), though I'm guessing they're in the same place. Any suggestions on where a clever guy who's too sleep deprived to find them right now may have hidden them? None of the IndieWeb plugin sub-plugins would be generating them quietly could they?!

The quirky part is that all three lines have been in there a while and (to my knowledge) haven't been causing problems until about a week ago.

The 6 or so outstanding webmentions went right through without any issue, so I'll mark this as closed for now unless problems continue.

**Comment by chrisaldrich** [comment]
Cross reference: https://chat.indieweb.org/2016-07-13#bottom
# 21:59 [chrisaldrich] GWG: there isn't a chance that one of the IndieWeb plugins for WordPress throws in <link rel="webmention" href="http://sitename.com/?webmention=endpoint" /> into headers to automatically identify a webmention endpoint is there?
# 21:59 GWG [chrisaldrich]: Yes, the webmention plugin does it automatically.
# 21:59 GWG Why? Did you embed it manually?
# 22:01 [chrisaldrich] A ha! I was losing my mind trying to find where it was coming from as I thought I'd put it in manually. I'm guessing it also throws in <link rel="http://webmention.org/" href="http://boffosocko.com/?webmention=endpoint" /> too?
# 22:02 snarfed joined the channel
# 22:02 [chrisaldrich] I'd had put in <a rel="webmention" href="https://www.brid.gy/webmention/wordpress"></a> manually ages ago and it was apparently causing issues with Brid.gy sending webmentions properly since the endpoint was specified multiple times.
# 22:03 [chrisaldrich] snarfed: You might consider updating the brid.gy FAQ for WordPress.ORG use, or if you prefer I can do it
# 22:04 GWG [chrisaldrich]: I think pfefferle figured most people wouldn't do it themselves.
# 22:07 [chrisaldrich] Smart thinking for moving forward, but be aware in the near term that it may cause people with the bridgy snippet above to have webmentions failing sproradically until it's fixed.

**Comment by snarfed** [comment]
funny, i only added that endpoint link to the docs (https://brid.gy/about#endpoint) maybe a few weeks ago. before then, the only place it showed up was in the wordpress.com signup flow. odd indeed that you had it!
