### ISSUE TITLE
missing twitter backfeed for @gRegorLove

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#686]
@gregorlove ([user page](https://brid.gy/twitter/gRegorLove)) found a case where bridgy was missing backfeed from twitter for a post with a syndication link: https://gRegorLove.com/2016/07/my-bedhead-was-trying-to/ . [poll log that discovered it.](https://brid.gy/log?start_time=1468865985&key=aglzfmJyaWQtZ3lyFwsSB1R3aXR0ZXIiCmdSZWdvckxvdmUM) evidently the bug was that the twitter.com synd url had a trailing slash:

```html
<a rel="syndication" class="u-syndication u-bridgy-omit-link"
   href="https://twitter.com/gRegorLove/status/755099818611978240/">
```

after he removed that, backfeed worked.

i don't understand why it broke, though. we supposedly remove trailing slashes from twitter synd urls: https://github.com/snarfed/bridgy/blob/master/twitter.py#L35 , https://github.com/snarfed/webutil/blob/master/util.py#L1174

it's also odd that we sometimes normalize his domain's case to gregorlove.com in our stored `SyndicatedPost`s, e.g. http://gRegorLove.com/2016/07/my-bedhead-was-trying-to/ => https://twitter.com/gRegorLove/status/755099818611978240 ([datastore entity](https://console.cloud.google.com/datastore/entities/edit?key=0%2F%7C9%2FInstagram%7C15%2Fname:gregorlove%7C14%2FSyndicatedPost%7C19%2Fid:5749328048029696&project=brid-gy&ns=&kind=SyndicatedPost&filter=8%2Foriginal%7CSTR%7CEQ%7C55%2Fhttp:%2F%2Fgregorlove.com%2F2016%2F07%2Fmy-bedhead-was-trying-to%2F)), but other times we don't, e.g. http://gregorlove.com/2016/07/my-bedhead-was-trying-to/ => https://www.instagram.com/p/BIAxWb3A2al/
([datastore entity](https://console.cloud.google.com/datastore/entities/edit?key=0%2F%7C7%2FTwitter%7C15%2Fname:gRegorLove%7C14%2FSyndicatedPost%7C19%2Fid:5680752083599360&project=brid-gy&ns=&kind=SyndicatedPost&afilter=11%2Fsyndication%7CSTR%7CEQ%7C57%2Fhttps:%2F%2Ftwitter.com%2FgRegorLove%2Fstatus%2F755099818611978240%2F)). i guess it doesn't really matter, since we heavily normalize the silo urls themselves, and they're the ones that count.

**Comment by snarfed** [comment]
huh, interesting. we have lower case domain for all of his facebook and instagram synd url mappings ([datastore query](https://console.cloud.google.com/datastore/entities/query?project=brid-gy&ns=&kind=SyndicatedPost&filter=8%2Foriginal%7CSTR%7CGT%7C26%2Fhttp:%2F%2Fgregorlove.com%2F2016)), and for twitter before 2015-07-02, but after that we started storing capitalized domains for just the twitter ones ([datastore query](https://console.cloud.google.com/datastore/entities/query?project=brid-gy&ns=&kind=SyndicatedPost&filter=8%2Foriginal|STR|GT|22%2Fhttp:%2F%2FgRegorLove.com%2F)).

probably triggered by a change on his site; looks like 2015-07-02 is when he launched URL slugs. last id-based URL we have is http://gregorlove.com/2015/07/1206/ . funny.

**Comment by gRegorLove** [comment]
If it makes a difference, I typically manually cross-post to Facebook and Instagram, but I use Bridgy Publish for Twitter. I think my URL on my Twitter profile has been mixed-caps for quite a while before 2015-07, so that's interesting.

**Comment by gRegorLove** [comment]
Also, the post in question set the Twitter syndication link from the Bridgy response, then I accidentally re-saved an older version of the post that overwrote it with the Bridgy Publish link. So I went to Twitter, copied the link and re-saved the post. Somehow in that process I added the trailing slash. That all happened within a few minutes of publishing.

**Comment by snarfed** [comment]
thanks for the info!

found the trailing slash bug. forgot that `re.match()` doesn't require whole string match; it matches any substring starting at the beginning. easy fix at least.
