### ISSUE TITLE
like mf2 handlers missing original post urls for flickr user julie ann noying

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#687]
we're not including original post `u-like-of` links in julie ann noying's flickr mf2 like responses pages, which means her like webmentions are getting rejected. https://brid.gy/flickr/50254144@N07

example:

* https://www.flickr.com/photos/sickonsunday/28177854532/  (Grecia Contreras)
* https://brid-gy.appspot.com/like/flickr/50254144@N07/28177854532/43953629@N08

we are including them in comments, but as `u-mention`, not `u-in-reply-to`, which is also wrong. example

* https://www.flickr.com/photos/sickonsunday/28116257630/#comment72157671161116976
* https://brid-gy.appspot.com/comment/flickr/50254144@N07/28116257630/50232814-28116257630-72157671161116976

**Comment by snarfed** [comment]
fwiw, we've successfully sent flickr likes for other accounts as recently as 3-4w ago:
https://brid.gy/flickr/36003160@N08
https://brid.gy/flickr/72685908@N00

**Comment by snarfed** [comment]
log for https://brid-gy.appspot.com/like/flickr/50254144@N07/28177854532/43953629@N08 :

```
Fetching flickr:50254144@N07 like ('28177854532', '43953629@N08')
urlopen GET https://api.flickr.com/services/rest?photo_id=28177854532&nojsoncallback=1&method=flickr.photos.getInfo&format=json {}
urlopen GET https://api.flickr.com/services/rest?photo_id=28177854532&nojsoncallback=1&method=flickr.photos.getFavorites&format=json {}
requests.head https://julieannenoying.com/2011/02/21/dear-winter {'headers': {'User-Agent': '...'}}
Resolved https://julieannenoying.com/2011/02/21/dear-winter to https://julieannenoying.com/2011/02/21/dear-winter/
Original post discovery found original posts set([u'https://julieannenoying.com/2011/02/21/dear-winter/', u'https://julieannenoying.com/2011/02/21/dear-winter']), mentions set([])
Demoting original post links because user tag:flickr.com,2013:sickonsunday doesn't match author tag:flickr.com,2013:Julie Anne Noying
starting posse post discovery with syndicated https://www.flickr.com/photos/50254144@N07/28177854532/
```

**Comment by snarfed** [comment]
hey @kylewm, i'm seeing this in the Flickr API response for `?photo_id=28177854532&method=flickr.photos.getInfo`:

```json
{
  "owner": {
    "iconfarm": 8,
    "nsid": "50254144@N07",
    "username": "Julie Anne Noying",
    "path_alias": "sickonsunday",
    "realname": "",
    "iconserver": "7315",
    "location": ""
  },
  "..."
```

seems weird that it has `"username": "Julie Anne Noying"`, right? wouldn't we expect `"sickonsunday"` instead? any idea if this is expected somehow, or a flickr API bug?

(apologies in advance, i haven't actually started reading through the flickr API docs yet. :P)

**Comment by kylewm** [comment]
Im not at my computer right now, but i think that's normal. Their API is
wildly inconsistent... But nsid and path_alias tend to be the two ids
 
 
On Thu, Jul 21, 2016, at 06:26 PM, Ryan Barrett wrote:
> hey @kylewm[1], i'm seeing this in the Flickr API response for
> ?photo_id=28177854532&method=flickr.photos.getInfo:
> {  "owner": {  "iconfarm": 8,  "nsid": "50254144@N07",  "username":
> "Julie Anne Noying",  "path_alias": "sickonsunday",  "realname": "",
> "iconserver": "7315",  "location": "" },  "..."
> seems weird that it has "username": "Julie Anne Noying", right?
> wouldn't we expect "sickonsunday" instead? any idea if this is
> expected somehow, or a flickr API bug?
> (apologies in advance, i haven't actually started reading through the
> flickr API docs yet. :P)
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>

Links:

  1. https://github.com/kylewm
  2. https://github.com/snarfed/bridgy/issues/687#issuecomment-234431135

**Comment by snarfed** [comment]
hrm ok. granary flickr generates most tag ids from `username`, but one or two from `nsid` and maybe others. i guess we should switch this one to `pathalias`? hmm, will see.

**Comment by snarfed** [comment]
corresponding API response snippets from the successful likes:

https://brid-gy.appspot.com/like/flickr/36003160@N08/27879125662/28736492@N02

```json
  "owner": {
    "nsid": "36003160@N08",
    "iconfarm": 4,
    "username": "petermolnareu",
    "path_alias": "petermolnareu",
    "iconserver": "3955",
    "realname": "P\u00e9ter Moln\u00e1r",
    "location": ""
  },
```

https://brid-gy.appspot.com/like/flickr/72685908@N00/26519202081/143137783@N06

```json
  "owner": {
    "nsid": "72685908@N00",
    "iconfarm": 8,
    "username": "jgarber",
    "path_alias": "jgarber",
    "iconserver": "7315",
    "realname": "Jason Garber",
    "location": "Arlington, VA, USA"
  },
```

**Comment by snarfed** [comment]
here it is for the example photo in granary's `test_flickr.py`, id 5227922370:

```json
  "owner": {
    "location": "San Diego, CA, USA", 
    "username": "kylewm", 
    "path_alias": "kindofblue115", 
    "realname": "Kyle Mahan", 
    "nsid": "39216764@N00", 
    "iconfarm": 5, 
    "iconserver": "4068"
  }, 
```

this one makes it difficult. `username`, `path_alias`, and `realname` are all different, and so far we've been generating AS ids from `username`. the easy fix for this bug would be to switch to `path_alias`, but that would change AS actor ids for owners like this one, which isn't good.

**Comment by snarfed** [comment]
ideas:
* use `path_alias` only if `realname` is empty
* use `path_alias` only if there are space(s) in `username` (won't catch all cases)
* skip this author check for flickr. (introduced in 57a91e2a994186aac1b90099dcf648c8e48896fd, for #456)

**Comment by snarfed** [comment]
@kylewm thanks for the sanity check. i went with a dumb heuristic in snarfed/granary@35afdc7. let me know if you have any better ideas!
