### ISSUE TITLE
Odd webmention with link to bridgy

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#694]
I've seen something like this a few times on WordPress (maybe once every thirty webmentions or so), and always presumed it was an issue with my WordPress configuration and processing, but today I saw this with regard to a post on WordPress with a mention of a Known site:

I posted this on WordPress: http://boffosocko.com/2016/08/22/a-new-reading-post-type-for-bookmarking-and-reading-workflow/
which mentioned this post on Known: https://www.rmendes.net/2016/08/22/blockchain-democracy-government-of-the-people-by-the-people-for

The mention appeared on rmendes.net, but had an odd link to brid.gy.appspot.com. See picture below:

![bridgy mention](https://cloud.githubusercontent.com/assets/5882943/17876833/8c1809e2-6892-11e6-9a29-c38c3dccf9b8.PNG)

The brid.gy link was to https://brid-gy.appspot.com/like/facebook/5410052/10101081212777775/10153986333712786
which doesn't relate at all to either the primary post or to the  post that was mentioned. It does however link to another unrelated post on my WordPress site for with a POSSE post to Facebook.

Incidentally, the webmention/comment that appeared on Known didn't include my avatar as it usually would have, but I'm not sure if that's related to the proximal problem, though it may help in troubleshooting. 

If it helps, my webmention should have been sent by the standard WordPress plugin rather than via bridgy publish or other other available methods. I'm also aware that Rick isn't averse to monkeying under the hood of Known, but I suspect that because the mention related to another of my personal posts that POSSEd to Facebook, the fault likely doesn't stem from that.

Any idea what's going on here? I'm at a loss.

**Comment by chrisaldrich** [comment]
Adddendum:
I've also just noticed the same bridgy link: https://brid-gy.appspot.com/like/facebook/5410052/10101081212777775/10153986333712786

appear in a webmention from the same originating WP post as above to another WP post on my site that was also referenced (so at least it's being consistent whether the post mentioned was on WP or Known): http://boffosocko.com/2011/05/10/the-adventures-of-sherlock-holmes/#comment-31766

This one , too, choked on providing the correct avatar/site details.

**Comment by snarfed** [comment]
huh. odd indeed. i don't know what's going on here either.

looking at https://mf2.kylewm.com/?url=http://boffosocko.com/2016/08/22/a-new-reading-post-type-for-bookmarking-and-reading-workflow/ , neither brid.gy nor brid.gy.appspot.com show up anywhere. and you're right, those webmentions were WP -> Known and WP -> WP, respectively. bridgy wasn't involved.

i have no idea why the brid.gy.appspot.com URL is showing up, but we might have more luck debugging the WP webmention plugin. maybe file an issue in that repo?

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
