### ISSUE TITLE
twitter publish failed, inexplicably over 140 char limit

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#696]
@miklb's (https://brid.gy/twitter/miklb) publish attempt of https://miklb.com/social/2016/09/05/3180/ yesterday failed with an "over 140 chars" error. the text is 136 chars long:

```
Turn on debug menu in Mac App Store `defaults write com.apple.appstore ShowDebugMenu -bool true`
```

[log](https://brid.gy/log?start_time=1473036984&key=aglzfmJyaWQtZ3lyUAsSDVB1Ymxpc2hlZFBhZ2UiKWh0dHBzOi8vbWlrbGIuY29tL3NvY2lhbC8yMDE2LzA5LzA1LzMxODAvDAsSB1B1Ymxpc2gYgICAgICAgAoM) below. maybe twitter didn't URL-decode the text? even then, it's exactly 140 chars, not over.

(also why is the `/statuses/update.json` API call a GET?!?)

```
2016-09-05 00:56:24.462680 D Converted to ActivityStreams object: {
"url": "https://miklb.com/social/2016/09/05/3180/",
"content": " <p>Leaving this here for future reference. Turn on debug menu in Mac App Store `defaults write com.apple.appstore ShowDebugMenu -bool true`</p> ",
"author": {
"url": "https://miklb.com/social/2016/09/05/3180/",
"image": [
{
"url": "https://cdn.miklb.com/images/profile_4_16_sm.png"
}
],
"displayName": "Michael Bishop",
"objectType": "person"
},
"objectType": "note",
"tags": [
{
"displayName": "notes",
"objectType": "hashtag"
},
{
"displayName": "macOS",
"objectType": "hashtag"
}
]
}
2016-09-05 00:56:24.548049 I urlopen GET https://api.twitter.com/1.1/statuses/update.json?status=Leaving+this+here+for+future+reference.+Turn+on+debug+menu+in+Mac+App+Store+%60defaults+write+com.apple.appstore+ShowDebugMenu+-bool+true%60 {}
2016-09-05 00:56:24.693300 W Error 403, response body: {"errors":[{"code":..."message":"Status is over 140 characters."}]}
2016-09-05 00:56:24.693800 W Error: {"errors":[{"code":..."message":"Status is over 140 characters."}]} HTTP Error 403: Forbidden
```

**Comment by miklb** [comment]
Interesting. I didn't even realize it had failed.

**Comment by snarfed** [comment]
i was able to post the same text fine through [twitter's api console](https://apigee.com/embed/console/twitter): https://twitter.com/snarfed_org/status/772813047320707072 . i also tried a pre-URL-encoded version, and it happily decoded it.

one maybe related quirk is that it linkifies `com.apple`, so that costs 24 chars instead of just 9. that's #416. (cc @kylewm)

**Comment by kylewm** [comment]
Hehe, I think you're just missing the first sentence:

```
Leaving this here for future reference. Turn on debug menu in Mac App Store `defaults write com.apple.appstore ShowDebugMenu -bool true`
```

150 characters after it linkifies com.apple (which I agree is weird).

**Comment by snarfed** [comment]
hah. thanks for the sanity check @kylewm!

`apple` is in brevity's TLD list, so maybe it didn't catch this because it doesn't linkify substrings? @kylewm, is brevity for shortening tweets specifically? or just notes in general? not sure whether we expect it to match twitter exactly, including quirks like this, or not.

**Comment by kylewm** [comment]
Ah, good question. The library's scope is to match twitter's behavior more or less exactly... so we don't have to add special cases for quirks like this anywhere else. Which means it's a bug in brevity.

The way to solve it is probably going to be adding the TLD list to the regex itself instead of checking it after matching is done. That way the matcher will stop at `.apple` instead of matching anything `[a-z0-9\.]`. I'll have a look!

**Comment by snarfed** [comment]
thanks @kylewm! deployed and confirmed.
