### ISSUE TITLE
Twitter like backfed with username "None"

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#697]
https://singpolyma.net/actionstream/pepper-carrot-christmas-card/comment-page-1/#comment-256812

None seems like a python thing, it is neither his twitter handle nor name.

**Comment by snarfed** [comment]
interesting! looking.

**Comment by snarfed** [comment]
response is https://brid.gy/like/twitter/singpolyma/773634008118796292/23238890

**Comment by snarfed** [comment]
fix is working locally but not on prod. not sure why.

**Comment by snarfed** [comment]
too many cache layers. :P fixed. thanks again for reporting!

**Comment by snarfed** [comment]
too many cache layers. :P fixed. thanks again for reporting!
