### ISSUE TITLE
icon font gives 404

### ISSUE THREAD

**Issue by jonnybarnes** [snarfed/bridgy#700]
`https://brid.gy/fonts/glyphicons-halflings-regular.woff2` is the URI returning 404

**Comment by snarfed** [comment]
thanks for the heads up! fortunately the woff 1 file is loading fine, so nothing's broken, but still worth fixing.

**Comment by snarfed** [comment]
caused by snarfed/oauth-dropins@b4a504e0179f72c15b691b110e5f6dfe67de0660

**Comment by snarfed** [comment]
fixed by snarfed/oauth-dropins@fec508e56d726ecbc94fcd14028f8bd32611c916
