### ISSUE TITLE
Regression: tweet should use explicit title when present

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#702]
https://brid.gy/log?start_time=1475605224&key=aglzfmJyaWQtZ3lyXwsSDVB1Ymxpc2hlZFBhZ2UiOGh0dHBzOi8vc2luZ3BvbHltYS5uZXQvMjAxNi8xMC9ob2xpZGF5LWdyZWV0aW5nLWZyZWVkb20vDAsSB1B1Ymxpc2gYgICAgICAgAoM

Tweet was posted using start of body instead of title.  This used to be the case, but got changed at some point.  Looks like it's gone back.

**Comment by snarfed** [comment]
thanks for filing! will fix.

**Comment by snarfed** [comment]
confirmed the fix by previewing https://singpolyma.net/2016/10/holiday-greeting-freedom/ on http://brid.gy/twitter/singpolyma .

**Comment by snarfed** [comment]
(from snarfed/granary@675eb17225585f522d8014a81a07d2f79c89064c )
