### ISSUE TITLE
How should location info for notes be parsed?

### ISSUE THREAD

**Issue by jonnybarnes** [snarfed/bridgy#706]
As per discussion in #indieweb and #microformats.

My markup is currently:
```
<div class="h-entry">
  <div class="note">
    <div class="e-content p-name">
      <p>What a goal! <a rel="tag" class="p-category" href="/notes/tagged/mufclive">#mufclive</a></p>
    </div>
    <div class="note-metadata">
      <a class="u-url" href="/notes/CB"><time class="dt-published" datetime="2016-10-20T19:54:18+0000">20 hours ago</time></a> via <a class="client" href="https://jonnybarnes.uk/notes/new">jonnybarnes.uk/notes/new</a> in <span class="p-location"><span class="p-name">Salford, UK</span> <span class="coordinates">(<span class="p-latitude">53.49827040530361</span>, <span class="p-longitude">-2.379474594222717</span>)</span></span>
    </div>
  </div>
</div>
```

So more specifically I have `h-entry > p-location > {p-name,p-latitude,p-longitude}`

Will bridgy syndicate this to Twitter? The preview option suggests not.

**Comment by tantek** [comment]
Currently p-location is the only "stable" location related property in h-entry, so that's a good place to start, treating it as a location string (similar to how h-event p-location works).

There has also been some use of u-location with a geo: URI (e.g. @aaronpk's OwnYourGram apparently posts IG photo locations this way to micropub servers), that might be good to check for "geo:" before treating it as a "plain string".

Requiring p-location to have some structure (like an embedded h-card, as above, or an h-adr or h-geo) is another possible approach.

**Comment by jonnybarnes** [comment]
I think a more pertinent question is how should location info that doesn’t suit an `h-card` be marked up.

**Comment by snarfed** [comment]
> I think a more pertinent question is how should location info that doesn’t suit an h-card be marked up.

http://indieweb.org/location#How_to_determine_the_location_of_a_microformat describes a lookup algorithm that's very permissive and supports many different options - `h-card`, `h-adr`, `h-geo`, and even top-level properties like the markup you initially posted.

making bridgy support that algorithm is a reasonable feature request. right now we can only POSSE location to twitter and flickr, and they only support lat/long, so it's not too much work. i'll plan to do that.

**Comment by jonnybarnes** [comment]
I’m currently playing around with my markup at the moment, thinking of using data tags for the actual latitude and longitude values, they look messy when displayed visually and don’t really mean anything for a person.

This is currently the markup on my local machine:
```
<span class="h-adr">
  <span class="p-locality">Salford</span>, <span class="p-country-name">UK</span>
  <data class="p-latitude" value="53.499"/>
  <data class="p-longitude" value="-2.379"/>
</span>
```

**Comment by snarfed** [comment]
sgtm!

oh btw @jonnybarnes i saw you forked granary. cool! if you're thinking of working on this, we might actually consider doing it in https://github.com/kylewm/mf2util , [probably here in `_interpret_common_properties`](https://github.com/kylewm/mf2util/blob/master/mf2util.py#L561), and then reuse it in both twitter and flickr `_create()`. cc @kylewm.

**Comment by jonnybarnes** [comment]
yeah, [I’m a PHP guy...](http://i1.kym-cdn.com/photos/images/original/000/234/765/b7e.jpg)

**Comment by jonnybarnes** [comment]
I’m not sure if granary code has been updated, or my changed markup is better, but the publish preview option on brid,gy is now picking up the latitude/longitude values from my notes :)

**Comment by snarfed** [comment]
it's your changed markup. :P `latitude` and `longitude` are now inside a `location` property, so bridgy sees them. from https://mf2.kylewm.com/?url=https://jonnybarnes.uk/notes/CB :

```json
{
 "type": [
  "h-entry"
 ], 
 "properties": {
  "location": [
   {
    "type": [
     "h-adr"
    ], 
    "properties": {
     "latitude": [
      "53.49827040530361"
     ], 
     "longitude": [
      "-2.379474594222717"
     ], 
     "name": [
      "Salford, UK"
     ]
    }, 
    "value": "Salford, UK"
   }
  ], 
  "..."
```

having said that, i'm actually about to push a change that will make bridgy support top-level `lat`/`long` too. teamwork! :P

**Comment by snarfed** [comment]
this isn't actually pushed live quiet yet. reopening until that happens.
