### ISSUE TITLE
Bridgy stopped finding my webmention endpoint

### ISSUE THREAD

**Issue by rhiaro** [snarfed/bridgy#711]
For over a month I haven't had any twitter interactions sent as webmentions by bridgy. On my user page, it says "No webmention targets" for everything it finds, even though each of them is a reply to one of my tweets which contains a link back to the source on my site. Each of my posts advertises the webmention endpoint with the HTTP Header.

Update: when I try reauthorizing twitter with bridgy, it says "No valid web sites found in your Twitter profile." So I guess that's why... But my URL is very much in my profile, so I have no idea why this would happen. What does bridgy class as 'valid' exactly?

**Comment by snarfed** [comment]
thanks for reporting!

this turned out to be [content negotiation](https://en.wikipedia.org/wiki/Content_negotiation). https://rhiaro.co.uk/ serves multiple content types based on what the user agent sends in the `Accept` header, defaulting to `application/ld+json`. Bridgy requires `text/html`, but doesn't send `Accept`, so it rejects rhiaro.co.uk pages entirely.

fix is to start sending `Accept`.

**Comment by rhiaro** [comment]
Thanks! Maybe I'm just being impatient, but it found one response to one tweet and sent a webmention for that, but none of the others... https://brid.gy/twitter/rhiaro?responses_before=2016-12-21T02:29:57.586080#responses

**Comment by snarfed** [comment]
yeah, i saw that, sorry. the new one happened after i pushed the content negotiation fix.

i hate to say it, but retrying the old ones isn't easy right now. bridgy can retry lots of cases, but not if it didn't find a webmention endpoint on a site, at least not after the first 24h of automatic retries. #579 may make this easier eventually.

you can send them yourself in the meantime! it takes work, but it's doable: https://brid.gy/about#source-urls

**Comment by rhiaro** [comment]
Ohhh I didn't know it didn't retry in that case. No worries, I'll catch them up myself. Thanks!
