### ISSUE TITLE
Medium publish support, in particular likes (not supported by API)

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#712]
If I post a "like" of a Medium article, it would be great if I could POSSE that "like" to Medium using Bridgy Publish (similar to POSSEing likes of tweets to Twitter via Bridgy Publish).

Here is a bit of indirect evidence that there may be some additional interest in such a feature: 

https://twitter.com/csleh/status/813468565370208256

**Comment by snarfed** [comment]
thanks for filing! i'd love this too. sadly the medium API [only supports creating posts](https://github.com/Medium/medium-api-docs/#33-posts) right now, not recommends or likes. [docs](https://github.com/Medium/medium-api-docs/), [google](https://www.google.com/search?q=medium+api+like).

keeping open for tracking.

**Comment by snarfed** [comment]
related:
* Medium/medium-api-docs#24 (query likes)
* Medium/medium-api-docs#52 (CRUD for posts)
* Medium/medium-api-docs#72 (CRUD for recommends)
* Medium/medium-api-docs#72 (CRUD for responses)

**Comment by snarfed** [comment]
aha, figured out what was nagging at me about this. i was trying to figure out what likes on medium are, and they're the same as "recommending," not a separate thing. ok. https://help.medium.com/hc/en-us/articles/215252328-Recommends

**Comment by chrisaldrich** [comment]
nota bene: This probably just got wonkier with the replacement of recommendations with "claps". 
http://indieweb.org/clap

**Comment by snarfed** [comment]
i'm doing a sweep and closing issues that depend on silo API support like this if it doesn't currently exist. apologies for the bad news, or if this is a surprise. feel free to reopen if/when the silo adds this support!
