### ISSUE TITLE
Bridgy not returning webmentions from Instagram to WordPress

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#718]
This is an odd one, but I've noticed recently that I'm not getting webmentions from Bridgy on Instagram posts on my WordPress install. I do seem to be getting them back from Twitter and Facebook however, so I'm not sure if it's something else quirky on my side or something that changed within Bridgy.

Note that I am posting my Instagram photos to both a WordPress and a Known install separately, so comments/likes are (or were) being sent successfully to both for the past year or so. The Known side is still receiving webmentions, but not WP for some reason.

Could it possibly be related to changes from https://github.com/snarfed/bridgy/issues/713? It looks like those changes coincided with the last time I'd gotten webmentions to my WP install for an Instagram syndicated post.

I've looked at it a couple times over the last few days to see if I've accidentally changed something, but if it's something simple, I'm just not seeing it for some reason.

**Comment by snarfed** [comment]
hey chris, sorry for the trouble!

looks like your mf2 on the front page of http://boffosocko.com/ isn't conducive to crawling. maybe something changed recently?

on https://brid.gy/instagram/chrisaldrich, clicking on the _Web site crawled X hours, Y minutes ago_ link shows that bridgy's crawl fetches http://boffosocko.com/ , doesn't find an `h-feed`, and doesn't find any top-level `h-entry`s:

```
attempting to refetch h-feed for chrisaldrich (Instagram)
requests.head http://www.boffosocko.com {'headers': {'User-Agent': '...'}}
Resolved http://www.boffosocko.com to http://boffosocko.com/
fetching author url http://boffosocko.com/
requests.get http://boffosocko.com/ {'headers': {'User-Agent': '...'}}
No h-feed found, fallback to top-level h-entrys.
requests.head http://stream.boffosocko.com/profile/chrisaldrich {'headers': {'User-Agent': '...'}}
...
```

parsing http://boffosocko.com/ for mf2, using e.g. https://mf2.kylewm.com/?url=http://boffosocko.com/ , gives:

```json
{
 "items": [
  {
   "type": ["h-as-note"],
   "properties": {
    "name": ["..."]
   },
   "children": [
    {
     "type": ["h-entry"],
     "properties": {
      "name": ["Featured Posts"],
      "content": [{"html": "...", "value": ""}],
      "syndication": ["https://chrisaldrich.wordpress.com/?p=55670253"]
     }
    },
    {
     "type": ["h-card"],
     "properties": {
      "name": ["Chris\n  Aldrich"],
      "..."
     }
    }
   ]
  }
 ],
 "..."
}
```

an easy fix might be to add something like `<link rel="feed" src="/blog/">` to your front page. more: https://brid.gy/about#link

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/718" class="u-in-reply-to"></a>Thanks snarfed.  The issue has continued for the last few days after I implemented your suggestion (apparently I'd accidentally deleted a few lines of code when I made some changes in my feeds back in December), and it was driving me bonkers still.  

Ultimately I dug back through some records and tried using
`<link rel="feed" type="text/html" title="BoffoSocko Blog feed" href="http://boffosocko.com/blog/" />`
which I had some months ago. Things now seem to be back on track.  Apparently (??) it was using `href `and not `src `which may have been the more recent issue if you need to make the suggestion in the future.

I still think it's kind of odd that the issue was only with Instagram and didn't seem to affect Twitter or Facebook.

Thanks again for helping to save my sanity!
