### ISSUE TITLE
Feature request: Bridgy Publish quotation to quote tweet

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#720]
This is the flip side of Issue #504 

If I post a quotation post where the thing being quoted is either a tweet itself, or has a syndicated POSSE tweet equivalent, then it would be nice if Bridgy Publish of my quotation post to Twitter would create a "Quote Tweet" (https://support.twitter.com/articles/20169873#Quote%20Tweet) for me.

Some more thoughts here: https://indieweb.org/quotation#Quote_entirety_with_commentary

Not sure how to best POSSE a quotation post when it's only quoting *part* of a tweet, since a POSSE "quote tweet" would make it look like you were quoting the entire tweet.

**Comment by snarfed** [comment]
sure! you can actually posse a quote tweet right now by including the quoted tweet URL at the end of the content, but supporting `u-quotation-of` when it points to a tweet URL is definitely worthwhile and straightforward.

**Comment by snarfed** [comment]
done!

**Comment by snarfed** [comment]
docs: https://brid.gy/about#quote-tweet
