### ISSUE TITLE
FAQ entry for >10 Instagram likes

### ISSUE THREAD

**Issue by chrisjonesio** [snarfed/bridgy#722]
Just a request for an update to the FAQ. Instagram only returns usernames for the first 10 likes of a post. Beyond that it's just a generic number. So if people are wondering why they're only getting 10 likes backfed to their site, I think that's why.

**Comment by snarfed** [comment]
based on spot checking a few different posts, it looks like it's always the first 10, or at least the 10 never change.

**Comment by chrisjonesio** [comment]
I'm inclined to agree with you. From my testing and poking around it seems like the first ten likes come through the API as separate users, thus getting pulled by bridgy, then once it rolls over to 11, no more of that. I'm not sure what the API response looks like but I'd guess it turns from an array of like objects each with user info into a single object with total likes and no user info.

There are some articles here and there discussing how IG only shows a number of likes, never names, even under 10. That doesn't appear to be the case now, or for a while now, as all my <10 liked photos (I am SO popular) have usernames listed, not a total number of likes.

I can see why so many devs flipped their desks and walked away from working with IG.

**Comment by snarfed** [comment]
most devs walked away from IG because they dramatically closed their API to most use cases, including bridgy. so we're not using the API at all now, we're scraping. :/ see #603.

regardless, thanks for reporting!
