### ISSUE TITLE
Quote tweet should not include h-cite content

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy#723]
I switched up the markup a bit when attempting to publish a quote tweet: https://gregorlove.com/2017/01/i-joined-the-aclu-today/ The publish preview correctly indicated "will quote this tweet" (with link), but then the tweet preview text showed:

> I joined the ACLU today and encourage you to donate. Send [@]sacca your receipt; he is matching up to $75K.
>
>\> We filed suit against…

When I published, the tweet text appeared exactly like that with no quoted tweet attached.

Bridgy Publish should probably drop the `h-cite` element that has `u-quotation-of`. There may be another issue of the quoted tweet not being attached.

**Comment by snarfed** [comment]
thanks for reporting!

**Comment by snarfed** [comment]
the second bug, dropping the quoted tweet URL, is because we append it to the content before we truncate.

that should be straightforward to fix. dropping the `h-cite`...not so much. :/
