### ISSUE TITLE
Twitter: “No webmention targets” for tweet with target

### ISSUE THREAD

**Issue by matthiasott** [snarfed/bridgy#727]
Hi @snarfed, 
this tweet has a backlink to my site in it, but Bridgy doesn't catch the link: https://twitter.com/beep/status/831136280465522689
<img width="1101" alt="bridgy response" src="https://cloud.githubusercontent.com/assets/991611/22902683/2cff0c84-f236-11e6-9d71-65fd71962530.png">

Is this the relevant part of the [poll log](https://brid.gy/log?start_time=1486994491&key=aglzfmJyaWQtZ3lyEgsSB1R3aXR0ZXIiBW1fb3R0DA)?

````
Original post discovery found original posts set([u'https://matthiasott.com/articles/patterns-beyond-context']), mentions set([])
Demoting original post links because user tag:twitter.com,2013:m_ott doesn't match author tag:twitter.com,2013:beep
starting posse post discovery with syndicated https://twitter.com/beep/status/831136280465522689
requests.head https://matthiasott.com/ {'headers': {'User-Agent': '...'}}
fetching author url https://matthiasott.com/
requests.get https://matthiasott.com/ {'headers': {'User-Agent': '...'}}
No h-feed found, fallback to top-level h-entrys.
posse post discovery found no relationship for https://twitter.com/beep/status/831136280465522689
````

It works like charm for other tweets linking to the same URL, though: 
https://twitter.com/m_ott/status/831047069251039232
https://twitter.com/c_huggins/status/831148577544138754
https://twitter.com/chopeh/status/831141013582405632

Thanks for any help, Ryan  – and also huge thanks for Bridgy!

**Comment by snarfed** [comment]
thanks for reporting!

not sure what's up here. the usual first stop for debugging these is https://brid.gy/about#missing , but bridgy clearly found this tweet, and backfeed similar tweets with links to the same post, so you're comfortably beyond the things to check in that docs link. i'll look soon.

**Comment by matthiasott** [comment]
Thanks Ryan! If there is anything I can do to help, just let me know.

**Comment by snarfed** [comment]
looks like this finally made it through to your site! https://matthiasott.com/articles/patterns-beyond-context#webmention-source

tentatively closing. feel free to reopen.
