### ISSUE TITLE
Bridgy Publish feature request: POSSE video to Internet Archive

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#730]
The Internet Archive encourages uploading of videos:
https://archive.org/details/movies&tab=about
as long as you set a Creative Commons license on them.

It would be cool if we could use Bridgy Publish to automatically POSSE video posts to the Internet Archive:

https://archive.org/upload/

**Comment by tantek** [comment]
Of course this requires being able to markup a video post with a easily identifiable / parseable Creative Commons license which is doable for a post permalink with rel=license (and a whitelist of CC URLs?), and see also the u-license proposal https://indieweb.org/license#Brainstorming

**Comment by snarfed** [comment]
interesting! @tantek do you know that this is doable programmatically? i see their web UI uploader, and the FAQ points to a github repo with code, but it's not immediately obvious how that code works.

http://indieweb.org/Internet_Archive#Trigger_an_Archive says you can POSSE a _page_ with a single POST request. if that also works for video/audio accessible over HTTP, then bridgy publish support maybe seems like overkill...?

**Comment by snarfed** [comment]
also, step by step instructions for adding a new silo here​: https://github.com/snarfed/bridgy/#adding-a-new-silo

**Comment by tantek** [comment]
re: if that also works for video/audio accessible over HTTP

Good point. Yes, looks like we have some testing to do with existing methods before seeing if there is any benefit to other methods.

**Comment by snarfed** [comment]
cleaning up issues...tentatively closing since internet archive seems to have both a web UI and programmatic HTTP POST API that are just as easy as bridgy's web UI and webmention API.

feel free to reopen if that turns out to be wrong, or anything changes!
