### ISSUE TITLE
Use correct permalink settings when posting without Hum URL shortener

### ISSUE THREAD

**Issue by treitnauer** [snarfed/bridgy#731]
I prefer posting content using the full URL instead of a shortened link using Hum. After disabling Hum, brid.gy seems to take the WordPress post ID instead of the correct permalink settings:

![](http://iwmn.me/Ivdw/2mZwhBUj.png)

Not sure if the issue is due to a setting I'm missing but I couldn't find anything.

**Comment by dshanske** [comment]
This is related to an issue @snarfed and I discussed. It is a WordPress issue.

**Comment by snarfed** [comment]
thanks @dshanske! mind linking to the plugin issue?

**Comment by dshanske** [comment]
I can, but it is a WordPress, not a plugin issue per se.

**Comment by dshanske** [comment]
It is my intention to solve it in my plugin though
