### ISSUE TITLE
Don't send Webmentions for root URLs

### ISSUE THREAD

**Issue by pfefferle** [snarfed/bridgy#732]
only if they are really linked in a tweet.

I realized that bird.gy alway sends a Wgebmention to the root URL and to the permalink.

![bildschirmfoto 2017-03-17 um 08 29 21](https://cloud.githubusercontent.com/assets/2373/24033172/e026428c-0aeb-11e7-8b0e-d38b6df6cd55.png)

If I enable Webmentions for my root URL, I will receive every ping twice.

**Comment by snarfed** [comment]
this is actually expected. bridgy does send root URL wms, but only when you're @-mentioned and it's not a reply. we interpret an @-mention as similar to linking to your root URL in a native indieweb post.

let me know if you disagree!

**Comment by pfefferle** [comment]
Hmmm, let me think about that!

**Comment by snarfed** [comment]
@pfefferle any thoughts? :P

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!

**Comment by pfefferle** [comment]
this might resolve this "issue" https://github.com/pfefferle/wordpress-webmention/commit/6721547258c96619aae7346a4820145199dd3ef6
