### ISSUE TITLE
Twitter favorites backfed with `None` usernames

### ISSUE THREAD

**Issue by barryf** [snarfed/bridgy#734]
Four recent favorites to [one of my tweets](https://twitter.com/barryf/status/844905864288964608) were each backfed to [my post](https://barryfrost.com/2017/03/wxg) with a URL linking to `https://twitter.com/None` rather than with their correct Twitter account URLs: 

- https://brid-gy.appspot.com/like/twitter/barryf/844905864288964608/15178085
- https://brid-gy.appspot.com/like/twitter/barryf/844905864288964608/57797169
- https://brid-gy.appspot.com/like/twitter/barryf/844905864288964608/3665012673
- https://brid-gy.appspot.com/like/twitter/barryf/844905864288964608/2202870271

It's a bit odd. It's worth noting the two retweets to my post were fine.

Not a big deal but wondered if it's something I need to change my end. Thanks again for the wonderful Bridgy, Ryan 👍

**Comment by snarfed** [comment]
thanks for reporting! fixed.

twitter's API doesn't expose a tweet's favorites (!), so we scrape them from HTML, and they changed it slightly. fortunately easy to fix this time.

updating the _existing_ responses will take more work, though, and i'm out of time for the night. apologies. feel free to update them on your end though!

**Comment by barryf** [comment]
Thanks, @snarfed. No problem, I'll update the existing ones.
