### ISSUE TITLE
Facebook comment ordering

### ISSUE THREAD

**Issue by jaduncan** [snarfed/bridgy#737]
Right now Brid.gy often creates a situation where the FB comment backfeed doesn't correctly order the comments on Known, breaking the flow of the conversation.

Example:

Comment A: blah
Comment C: ha, comment B was funny.
Comment B: response to comment A.

I'm unsure if this is an issue caused by the order that brid.gy detects the comments, or if they are detected in order but sent off so quickly that Known picks them up incorrectly as all having the same time stamp and then orders them incorrectly.

If it's the former, is there an FB API issue that prevents ordering these correctly? If the latter, would it be worth attaching a delay between sent messages? That would ensure that an effective race condition didn't exist, and wouldn't increase overall load on the server.

**Comment by snarfed** [comment]
thanks for filling, and sorry for the trouble!

bridgy doesn't guarantee that it sends comments in order, and that wouldn't be easy to do architecturally, but it does provide the `dt-published` mf2 property in each comment, which known should use for ordering: https://github.com/idno/Known/issues/1104 . are you maybe on a known version older than 11/2015? or maybe that feature regressed recently?

**Comment by jaduncan** [comment]
No problem - the work you've done on bridgy is awesome, so decent bug hunting is the least of my duty here. I'm on 0.9.2. Comment as added in idno/Known#1104:

I'm currently getting incorrectly ordered comments on FB and Twitter comments sent from bridgy. I'm running 0.9.2 as provided by Reclaim Hosting (stock, I would think) and the order is broken in that, while comments from different bridgy pushes are ordered correctly, if bridgy is picking up multiple comments in one check (let's say that 10 have been added since bridgy last scanned FB) then the order within those 10 comments is random.

**Comment by jaduncan** [comment]
Looks like you're doing the correct thing though, so feel free to close this.
