### ISSUE TITLE
POSSE events to Upcoming.org (no API yet)

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#740]
Now that upcoming.org is live and I *think* has an API (or fairly straightforward form submission "API" at https://upcoming.org/event/add) it should be possible to have Bridgy Publish support POSSEing Indie events and RSVPs to Upcoming!

And similarly, Bridgy backfeed RSVPs back from Upcoming (ok to split into separate issue)
E.g. https://upcoming.org/event/homebrew-website-club-san-francisco-246bjt5v5f backfeed to: http://werd.io/2017/homebrew-website-club-april-5-2017 (perhaps extra challenging since POSSE copy was added manually not by the creator of the original post!)

If we get this working, this would be the first event destination where it is possible to fully automatically POSSE to it!

**Comment by tantek** [comment]
Example of an event on Upcoming I'd like to RSVP to: https://upcoming.org/event/homebrew-website-club-san-francisco-246bjt5v5f

**Comment by snarfed** [comment]
cool!

i see _REST API and JSON views_ in the _What's coming up?_ section in the right sidebar on the https://upcoming.org/ home page, which implies it's not there yet. bridgy publish generally only uses APIs, not form submit scraping, so we'd probably wait for the API. fingers crossed that arrives soon!

**Comment by snarfed** [comment]
(related: eventbrite (#275) and lanyrd (#412) both also have full fledged event publishing APIs.)

**Comment by aaronpk** [comment]
Alternately, upcoming.org could support importing events by parsing the event Microformats at the existing URL. Related issue: https://github.com/upcoming/upcoming-www/issues/49

**Comment by snarfed** [comment]
doesn't seem like upcoming is actively developed any more. [roadmap on the home page right side bar](https://upcoming.org/#news) seems pretty much unchanged, including API. [github commits](https://github.com/upcoming/upcoming-www/commits/master) ([and twitter](https://twitter.com/upcomingorg)) show the last meaningful development and activity was spring 2017. only a handful of minor changes and tweaks since then.

**Comment by snarfed** [comment]
Same, more or less, 2.5y later. A few scattered commits on GitHub, but no API or other meaningful progress on the roadmap.

**Comment by snarfed** [comment]
Same, over 6 mos later. Seems like Upcoming is abandoned. Closing.
