### ISSUE TITLE
Bridgy Publish to Twitter should consider u-featured fallback for u-photo for article use-case

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#741]
including an image in a tweet serves multiple purposes (is overloaded), both as a "photo" or as a "preview" of what an article is about.

Thus it may make sense for Bridgy Publish to first look for a u-photo to POSSE to Twitter (as a photo tweet), and lacking any u-photo, fallback to looking for a u-featured image to attach to the tweet as part communicating a friendlier "preview" of an article post to Twitter.

This has recently been suggested as a motivating use-case in the #indieweb IRC channel, specifically, to POSSE a blog post to Twitter as an article with the featured image from the article (which ideally would not force the original article to have to put u-photo on the feature article because that's not what it is).

**Comment by snarfed** [comment]
sure!

next (slightly embarrassing) step for me to implement this is to figure out how to map `u-featured` into ActivityStreams, granary's lingua franca. haven't found anything obvious yet, at least in AS1...

**Comment by snarfed** [comment]
done! for all silos, not just twitter. :P cc @miklb.

(i ended up just adding `u-featured` onto the AS1 `image` field that `u-photo` already goes into.)

**Comment by tantek** [comment]
re: "how to map u-featured into ActivityStreams" I don't think there's an AS equivalent. So downformatting it to "image" is probably the best we can do for AS for now.
