### ISSUE TITLE
bridgy publish to twitter doubles @-names in some replies

### ISSUE THREAD

**Issue by martymcguire** [snarfed/bridgy#742]
This post: https://martymcgui.re/2017/04/11/162245/

is in-reply-to this tweet: https://twitter.com/DnDSVU/status/851588489741303809

The text of the post includes an @-mention of "@DnDSVU":

> Had a blast running Everyone is John on @DnDSVU last night! Looking forward to next week when @thatonegm runs another one-shot.

When I POSSE the post via bridgy publish, I get this tweet, which is in a "canoe": https://twitter.com/schmarty/status/851894835086839817

Loqi's preview (which can be found here: https://chat.indieweb.org/dev/2017-04-11#t1491942552890000) looks like:

> @schmarty @DnDSVU Had a blast running Everyone is John on @DnDSVU last night! Looking forward to next week when @thatonegm runs another one-shot. (twtr.io/1QXxhpQ6UqH)

While the post on my site is in-reply-to this tweet, since my note doesn't start with the @-name of the original tweet's author, I wouldn't expect it to end up in a canoe. In other words - I would consider this post to be an [IndieWeb reply](https://indieweb.org/reply), but not a *Twitter* reply. In my wild dreams I would hope for it to be a [quote tweet](https://indieweb.org/quote_tweet).

**Comment by snarfed** [comment]
hey, thanks for filing! i think the problem may actually be that loqi doesn't yet support [twitter's new extended tweet feature](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets), which rolled out for @-replies recently. cc @aaronpk. (also see https://brid.gy/about#extended-tweets and snarfed/granary#89.)

the `@schmarty @DnDSVU` prefix in loqi's preview is actually outside the extended tweet's `display_text_range`, which means it shouldn't be rendered as part of the text, like loqi is doing. bridgy's preview and the final POSSEd tweet on twitter both handle this:

<img width="654" alt="screen shot 2017-04-11 at 2 44 09 pm" src="https://cloud.githubusercontent.com/assets/778068/24932228/67578bfc-1ec5-11e7-8490-cd887fd636ba.png">

**Comment by snarfed** [comment]
oh, and re:

> I would consider this post to be an IndieWeb reply, but not a Twitter reply. In my wild dreams I would hope for it to be a quote tweet.

interesting! good feedback, thanks for mentioning it.

right now, this mapping is deliberate; we map indieweb post types to silo post types literally. if you want to POSSE a quote tweet, you can definitely do that with `u-quotation-of`! https://brid.gy/about#quote-tweet . if you'd like more control over bridgy's own mapping, no promises, but i'm happy to hear ideas.

**Comment by martymcguire** [comment]
Thanks for the deep dive!

I have been swayed by the [is it really a quotation discussion on the IndieWeb wiki](https://indieweb.org/quotation#reply). I think of these as indieweb [reply](https://indieweb.org/reply) posts because I want to show the original tweet in context on my site, but my note is aimed at the general public and not just at the author of the tweet I'm replying to. While Twitter makes a distinction here between replies and quotations, I am not sure I want to build one into my site when a reply "looks" right on my site and in readers like woodwind.

So I'll POSSE these by hand and not worry too much about it. :}

Thanks again!
