### ISSUE TITLE
publish: support Facebook Pages

### ISSUE THREAD

**Issue by martymcguire** [snarfed/bridgy#744]
I've got a podcast at https://wehavetoask.com/ that I post to via micropub with [Screech](https://github.com/martymcguire/screech). The podcast has a Facebook Page that I'd like to be able to syndicate my posts to automatically.

Annoyingly this is a [separate Facebook API](https://developers.facebook.com/docs/pages/publishing), but I think is still in scope for bridgy publish, since bridgy supports backfeeding activity from pages?

**Comment by snarfed** [comment]
huh. out of curiosity, have you tried publishing with a page? i vaguely remember that it should work. not sure though; I'll test too.

**Comment by snarfed** [comment]
(btw fortunately it's not actually a separate API; they just separated the docs for it for some reason.)

**Comment by martymcguire** [comment]
ooooops, you are correct and it *does* work. super my bad!

i forgot that i had test this once before and it almost did what i wanted, but i wanted a link at the end of a note to show up as the FB link preview and it did not. that would be a separate issue.

**Comment by snarfed** [comment]
thanks! and i think the link feature is #474.
