### ISSUE TITLE
Bridgy Instagram stopped working?

### ISSUE THREAD

**Issue by sebsel** [snarfed/bridgy#745]
Backfeeding Instagram likes stopped working, and while investigating the weird error my site gave, I came across this:

https://brid-gy.appspot.com/like/instagram/sebsel/1494239816405360768_8154000/5061890 
> HTTP Error 404: 404 Not Found The resource could not be found. instagram:sebsel like ('1494239816405360768_8154000', '5061890')

This was not only the case for the failed webmentions, but also for webmentions that are already sent.

Also found this other (random) user who has the same problem:
https://brid-gy.appspot.com/like/instagram/absolonkent/1494335751838788370_602632/3886222319

So I think it's on Bridgy's / Instagram's side.

It all started somewhere between 2017-04-17 21:40:28 and 2017-04-16 14:31:08 (+0000)

**Comment by sebsel** [comment]
XRay also does not work for Instagram anymore (https://xray.p3k.io/parse?url=https%3A%2F%2Fwww.instagram.com%2Fp%2FBS_wnbiF-oE%2F), so I think they changed the JSON.

**Comment by snarfed** [comment]
ugh. the downside of scraping: constant updates. thanks for filling! I'll look.

i should also set up a cron job to test this regularly so i notice earlier...

**Comment by snarfed** [comment]
fixed!
