### ISSUE TITLE
Instagram publish by scraping new mobile browser upload UI (unlikely)

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#746]
Per https://www.theverge.com/2017/5/8/15562892/instagram-mobile-browser-photo-upload since it is now possible to upload to Instagram with a mobile web browser, this may mean it is also possible for Bridgy to do so, acting as your mobile browser. In addition likely also possible for POSSEing comments, likes, etc. to Instagram.

**Comment by snarfed** [comment]
interesting, thanks for filing the issue!

i hate to say it, but this is unlikely. scraping instagram to read photos and feeds already breaks pretty regularly, and scraping/automating form submission is usually even more brittle than scraping HTML. i've avoided doing it for publish, and i honestly wouldn't plan to start now.

if anyone else wants to take a stab it it and maintain a service, i'd happily lend a hand!

**Comment by snarfed** [comment]
i'm doing a sweep and closing issues that i don't plan to do myself _or_ accept a PR for. apologies for the bad news, or if this is a surprise. feel free to reopen if you feel strongly.
