### ISSUE TITLE
New Facebook reacji: Thankful

### ISSUE THREAD

**Issue by sebsel** [snarfed/bridgy#748]
I got one of the new Facebook reacji, wondered what Brid.gy does with it, but it seems it just ignores it.

It's called 'Thankful' and has a flower.

![schermafbeelding 2017-05-14 om 09 51 58](https://cloud.githubusercontent.com/assets/16517999/26032118/2dc8f774-388b-11e7-94af-5cb293e7b1c7.jpg)

Possible emoji:
🌼 < 'flower' (I think this is the best)
💐 < 'Bouquet' (this does give the 'thankful' message better)

There are a lot of other flowers, of which 🌸 renders pink and is the closest to Facebooks icon.

**Comment by Zegnat** [comment]
It’s called ‘grateful’ on my end.

![grateful](https://cloud.githubusercontent.com/assets/490579/26032213/179e4b72-388e-11e7-9b0a-b260900bde7c.png)

**Comment by sebsel** [comment]
That seems to be UK vs US English: US is 'Thankful', UK is 'Grateful', (NL 'Dankbaar').

**Comment by snarfed** [comment]
interesting, thanks for filing!

do you all know any more about this new reaction? I'm curious if it's permanent or just temporary.

**Comment by armingrewe** [comment]
Might be a test or only available in specific regions. I don't see this (yet), I only have the original 6.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/748" class="u-in-reply-to"></a>I've read that it was something they tested out last year in select markets around Mother's Day. It's possible that it was brought back today again for Mother's Day on a limited basis.

https://www.theverge.com/2017/5/13/15635974/mothers-day-thankful-facebook-camera-flower-reaction-instagram

https://www.facebook.com/help/community/question/?id=10207656192377271

**Comment by snarfed** [comment]
done! thanks again for filing. here's an example backfed to @sebsel's site: https://seblog.nl/2017/05/14/1/eurovisie-in-een-hostel

background: https://developers.facebook.com/docs/graph-api/reference/post/reactions

**Comment by sebsel** [comment]
🌼 :)

**Comment by sebsel** [comment]
@chrisaldrich was right! It was temporary. It's not possible to send them anymore, although they are still visible in the list.

![schermafbeelding 2017-05-18 om 08 40 05](https://cloud.githubusercontent.com/assets/16517999/26189631/de4f800a-3ba5-11e7-88da-da3393879112.jpg)

Still glad that that one made it to my site. Thanks @snarfed!
