### ISSUE TITLE
http redirect handling from webmention endpoint

### ISSUE THREAD

**Issue by aaronpk** [snarfed/bridgy#753]
We discovered the Webmention spec is vague on HTTP redirect handling of the webmention endpoint itself, but there still appears to be a problem with Bridgy.

Currently if bridgy gets a 3xx response when sending the webmention, it will follow the redirect and fetch the new URL with a GET request. This means the webmention isn't actually sent to the new location, yet bridgy treats this as a success because it sees the 200 response from the GET request of the new URL.

The quick fix here is to avoid following redirects in the POST request, and treating a 3xx response as the webmention failed to be sent. That would at least make these problems visible.

The longer-term fix (which might require some more thought) is to follow the HTTP redirect and send the webmention again to the new location. However there are some subtleties in how 301/302/307/308 should be interpreted.

**Comment by tantek** [comment]
Even quicker fix - at least indicate an *error* in the Bridgy log for a specific webmention sending attempt when this happens, because currently it appears that the webmention is successfully sent, e.g. "Sending... Sent!" in the logs.

**Comment by aaronpk** [comment]
That's what I was trying to say. I'm guessing that because bridgy is seeing the 200 and thinks the webmention is successful is because the HTTP library is automatically following the request. Therefore, step 1 is stop following the request, step 2 is treat the 3xx response as an error.

**Comment by snarfed** [comment]
understood! thanks for filing, and for all the info. easy enough to stop following redirects when sending wms, I'll do that for now.

**Comment by bobbysebolao** [comment]
Hi, I'm new to Bridgy, so please forgive me if this question has been asked already.

Having read the above thread, I can see that Bridgy no longer follows redirects . But, I think there are cases where following redirects would be useful. For example, when a website changes its URL subfolder structure, but wants to keep all the webmentions from Bridgy scraping its old Twitter links. In that case, the website owner would want Bridgy to follow the redirect and post webmentions to the new location.

Do people agree that this is a good reason why Bridgy should follow redirects?

I love Bridgy, by the way!

**Comment by snarfed** [comment]
@bobbysebolao bridgy definitely still handles those redirects! that's webmention discovery. this bug is about _sending_ webmentions, ie the HTTP POST to your endpoint.
