### ISSUE TITLE
Picture-only Facebook replies

### ISSUE THREAD

**Issue by lostfocus** [snarfed/bridgy#755]
When a FB reply is only a picture, the resulting brid.gy page ([Example](https://brid-gy.appspot.com/comment/facebook/765235586/10158892052250587/10158892052250587_10158894458325587)) ends up being pretty weird, as there is no `e-content p-name` class on the empty div. I'm not sure what the best way to handle these things is, though.

**Comment by snarfed** [comment]
huh. sorry for the trouble, and thanks for filing! will look. related: #646

**Comment by snarfed** [comment]
#646 already added support for normal images in comments, but this turned out to be a new comment attachment type, `animated_image_autoplay`. easy to add.
