### ISSUE TITLE
Support for alt text on images posted to Twitter (blocked on mf2py)

### ISSUE THREAD

**Issue by miklb** [snarfed/bridgy#756]
It seems that it is doable with the Twitter REST API to [pass alt text for images](https://blog.twitter.com/developer/en_us/a/2016/alt-text-support-for-twitter-cards-and-the-rest-api.html) 

Not 100% sure how to do so with Bridgy, unless bridgy can parse the `alt` attribute from the image with a `u-photo` or `u-featured` class. Then it would be pretty straight forward I would guess.

**Comment by gRegorLove** [comment]
API docs: https://dev.twitter.com/rest/reference/post/media/metadata/create

**Comment by snarfed** [comment]
this is currently blocked on mf2py supporting img alt text explicitly, tommorris/mf2py#83, based on microformats/microformats2-parsing#2.

(also, for my own notes, i'm tentatively planning to serialize HTML `alt` into AS1 `displayName`. alternative was `summary`.)

**Comment by snarfed** [comment]
this is deployed! still needs more testing and bug fixes - eg i need to ellipsize at 420 chars, and i think it doesn't work with multiple photos right now - but feel free to try it!

**Comment by snarfed** [comment]
fixed both of those issues.

**Comment by snarfed** [comment]
recent example of a twitter publish with alt text:
* http://jgregorymcverry.com/6851-2/
* https://twitter.com/jgmac1106/status/1041295971911696385
* alt text: _screen shot of aperture and my website_

**Comment by jamietanna** [comment]
@snarfed I'm not sure if this may have broken again, but looking at [this tweet](https://twitter.com/JamieTanna/status/1215968528676851713) in Granary, I don't see the alt tag returned, unless I'm doing something wrong?

**Comment by snarfed** [comment]
ah, i only implemented this for publishing, not consuming. i take you're interested in the consuming side in granary? [looks doable!](https://blog.twitter.com/developer/en_us/a/2016/alt-text-support-for-twitter-cards-and-the-rest-api.html) interested in tackling it? 😁

**Comment by jamietanna** [comment]
Sorry yep, I'm only looking for the consuming side as I've seen that Bridgy does publish the alt tags to Twitter.

I wasn't looking where I was and thought this issue was on Granary - sorry! I'll raise an issue for it, not sure if I'll get round to it soon, but it'll at least be there for someone else to

**Comment by Ryuno-Ki** [comment]
@jamietanna Perhaps helpful to crosslink it here when you open the ticket.

**Comment by jamietanna** [comment]
@Ryuno-Ki https://github.com/snarfed/granary/issues/183 is the issue, of which snarfed has already implemented a fix 🙌🏼
