### ISSUE TITLE
Twitter: default avatar URL is 404

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy#770]
Example: https://brid-gy.appspot.com/like/twitter/gRegorLove/910235986143191040/125120721 has https://pbs.twimg.com/profile_images/1277699150/default_profile_2_normal.png

**Comment by snarfed** [comment]
looks like this might be a twitter bug. the profile image on https://twitter.com/scotclose is 404 too. 😆

**Comment by snarfed** [comment]
profile image still broken on https://twitter.com/scotclose, but shows up ok in https://mobile.twitter.com/scotclose and the android app.

hey @gRegorLove are you seeing this with any other accounts? if not, i'm tempted to close this as a twitter bug with just this specific user.

**Comment by gRegorLove** [comment]
I haven't noticed it with anyone else, though haven't looked closely. This prompted me to fix a bug in my code with image caching, so even if it's happening with others it's not affecting me. Closing this sounds good to me.
