### ISSUE TITLE
Twitter’s 280 chars

### ISSUE THREAD

**Issue by sebsel** [snarfed/bridgy#773]
Couldn’t find this one on here.
Now that Twitter seems to support 280-chars, can Bridgy post them? 

I wrote a 173-char note today to see what happened, but bridgy cropped and added a link (I have it on omit_link=maybe indeed).

I heard that there was a way to fool a third party app into showing the 280 UI, which would mean that currently it’s only a UI restriction. In that case, Bridgy could use them already. Don’t know the fine details yet.

**Comment by snarfed** [comment]
thanks for filing!

last we checked, the API still doesn't support 280 chars, https://chat.indieweb.org/dev/2017-09-27#t1506565409291000 , nor does it have a way to determine whether a given user has access to them, even in the UI. so, we probably need to wait until they're rolled out to everyone.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/snarfed/bridgy/issues/773" class="u-in-reply-to"></a>There had been an interesting work around to fool Twitter, but they closed that loophole pretty quickly. Links found through here: http://boffosocko.com/2017/10/18/heres-a-hack-so-you-can-tweet-with-280-characters-right-now-the-verge/

**Comment by EdwardHinkle** [comment]
Just updating this with the fact that Twitter is officially supporting 280 characters.

There’s an [announcement here](https://twittercommunity.com/t/updating-the-character-limit-and-the-twitter-text-library/96425) supposedly it doesnt’t require any updates if the library is using the most up to date endpoints.

**Comment by snarfed** [comment]
thanks for the nudge @EdwardHinkle! updated in snarfed/granary@26b29a466addbf9998008c72bce2afdc3aafa05f and deployed. bridgy can now tweet 280 chars.

**Comment by EdwardHinkle** [comment]
Yay!! Success 💯 💯 💯  Thanks!
