### ISSUE TITLE
Drupal integration?

### ISSUE THREAD

**Issue by brylie** [snarfed/bridgy#774]
I have briefly searched, but found no clear picture for Drupal integration. What are some steps/considerations related to setting up a Drupal site for Bridgy? Is there (planned to be) a Drupal module, similar to the Indyweb WordPress module?

**Comment by snarfed** [comment]
hey, sure! the minimum you need is webmention support. looks like this plugin does that? https://www.drupal.org/project/vinculum

i don't use drupal myself, but feel free to post back here with details!

**Comment by snarfed** [comment]
friendly ping. i'll probably close this eventually if there's no specific ask for bridgy itself (just fyi).

**Comment by brylie** [comment]
Ok, thanks. I am still considering a bit how we can use Bridgy with our online magazine site. Seems really promising.

**Comment by snarfed** [comment]
sounds good! let me know if i can help!

**Comment by chrisaldrich** [comment]
As it happens, the newest version of the Linkback plugin for Drupal was apparently pushed a few hours ago: https://twitter.com/HongPong/status/937576654746128385

@brylie I suspect that with the correct rel-me set up,  you should potentially be able to integrate and use Brid.gy out of the box. https://twitter.com/HongPong could probably provide you with info if you have questions. I haven't done it in a while, but I suspect that much of the set up would be very similar to (WordPress)[https://indieweb.org/WordPress_with_Bridgy] though the plugin architectures are obviously different.
