### ISSUE TITLE
403 error on POSSE post discovery

### ISSUE THREAD

**Issue by jackysee** [snarfed/bridgy#775]
Log: https://brid.gy/log?start_time=1511801984&key=aglzfmJyaWQtZ3lyFQsSB1R3aXR0ZXIiCGphY2t5c2VlDA

I try to setup the POSSE post discovery on my site.
The site's front page is not the full list of posts, so I added a 
```
<link rel="feed" type="text/html" href="https://jacky.seezone.net/archives/">
```
It renders list of links, which I follow this structure
```
<ul class="h-feed">
  <li class="h-entry">
    <a class="u-url" href="(permalink)">(title)</a>
  </li>
  .....(other li.h-entry )
</ul>
```
Where at the permalink's page, it would have `u-syndication` links for discovery.

But from the log, seems that brid.gy cannot access the full list page ( https://jacky.seezone.net/archives/ ), with a 403 error. I'm puzzled as I can open it with browser, without any credentials.

Anything I missed here?

**Comment by snarfed** [comment]
heh, funny. that page is actually returning HTTP 403 to your browser too. it's just also rendering a normal-looking page, so you can't tell. here's what i get from curl:

```
$ curl -v https://jacky.seezone.net/archives/
...
> GET /archives/ HTTP/2
> Host: jacky.seezone.net
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 403
< date: Mon, 27 Nov 2017 17:51:15 GMT
...
<!doctype html>
<html lang="en-US" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://ogp.me/ns/fb#">
<head>
...
```

**Comment by jackysee** [comment]
I changed the page url and it's now working.
I think it's server configuration problem.
