### ISSUE TITLE
OK, you're not signed up. Hope you reconsider!

### ISSUE THREAD

**Issue by khurtwilliams** [snarfed/bridgy#783]
I get the same error message whenever I try to enable publishing (WordPress to Facebook).

> OK, you're not signed up. Hope you reconsider!

And it appears that Bridgy is publishing to my Facebook page instead of my timeline.

e.g. 

https://islandinthenet.com/little-creature/ attempted syndication to https://www.facebook.com/469804493057745/posts/1631998853504964

**Comment by snarfed** [comment]
thanks for reporting! looks like a real bug. i'll take a look soon.

**Comment by khurtwilliams** [comment]
Thank you for the fix. I appreciate  what you do.
