### ISSUE TITLE
Search by Letter on User Page

### ISSUE THREAD

**Issue by dshanske** [snarfed/bridgy#784]
On the user page, would you be able to add quick links to jump to letters of the alphabet or numbers? It would really make finding a page easier.

**Comment by snarfed** [comment]
sure! good idea. that UI is pretty weak overall, but this would definitely help.

in the meantime, you can actually do this yourself by changing the URL. e.g. https://brid.gy/users?start_name=B jumps to B.

also, if you know a user's web site, you can use it to go to their user page directly by using it in place of their silo id/username. e.g. https://brid.gy/facebook/snarfed.org redirects to my facebook user page https://brid.gy/facebook/212038.

i'll add all of this to the docs.
