### ISSUE TITLE
publish should support POSSEing person-tag reply to Facebook

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#786]
This is a feature request for POSSEing person-tag reply posts.

I.e. if I post a person-tag reply on my own site, like documented here:

https://indieweb.org/tag-reply#person_tag_reply

where one (or more) of the reply-to URLs is to a Facebook permalink post (likely others's photos, but could be my own that I'm adding person-tags to after I published it), Bridgy Publish (of my person-tag reply) should propagate that person-tag reply to that FB permalink.

This is distinctly different (but may be related to)
* #459 (probably most similar to this, which is about propagating person-tags on *your own* photo post that you're POSSEing)
* #488 
* #540

**Comment by snarfed** [comment]
thanks for filing! FB API docs are pretty terse on this, but it looks like you should be able to do this by POSTing to `/[photo_id]/tags`: https://developers.facebook.com/docs/graph-api/reference/photo/tags/#Creating

**Comment by snarfed** [comment]
bridgy publish for facebook will disappear soon (#817), so I'm closing open issues for it. sad. feel free to holler if you disagree.
