### ISSUE TITLE
Bridgy Publish to GitHub: support images and hyperlinks

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#794]
It’s awesome that Bridgy Publish now has basic support for POSSEing to GitHub (https://github.com/snarfed/bridgy/issues/333) and I’ve had pretty good luck with it http://tantek.com/t4t11 and http://tantek.com/t4t31.

However I noticed that images and hyperlinks (e.g. in http://tantek.com/t4t11) did not make it to the GitHub copy https://github.com/snarfed/bridgy/issues/333#issuecomment-366872578

It would be great if Bridgy Publish could support img and a href tags and convert them accordingly for GitHub!

(Originally published at: http://tantek.com/2018/052/b1/bridgy-github-support-images-hyperlinks)

**Comment by snarfed** [comment]
thanks again for filing. note to myself: html2text has a couple new releases since the version i'm using! https://github.com/Alir3z4/html2text/releases . (i'm still on 2016.9.19.) worth looking at first.
