### ISSUE TITLE
publish: ignore <style> tags in content

### ISSUE THREAD

**Issue by jernst** [snarfed/bridgy#795]
Feel free to delete this if you think this is a bad idea.

I just created a Wordpress post, which uses some just-for-this-post CSS. Which I have defined in a <style> section right at the beginning of my post. (This is most convenient as it is just for this post and won't ever be used for anything else.)

Bridgy posted the CSS between <style> and </style> as part of the content to FB and Twitter. Would it be useful to `s!<style>.*</style>!!g` first? There isn't really a good way of doing anything about this on the Wordpress side, as for Wordpress it is part of the post. And being able to add post-specific CSS right in the post is very convenient. Certainly beats the alternative ...

**Comment by snarfed** [comment]
interesting! thanks for filling!

i use https://github.com/Alir3z4/html2text to translate HTML to formatted text, maybe i or they) can teach it to handle `<style>`...

**Comment by snarfed** [comment]
note to myself: looks like we actually strip `<style>` tags out of AS1 `content` ok, and the root cause here may be AS1 `displayName` instead. e.g. the problematic post https://upon2020.com/blog/2018/02/how-to-be-evil-and-do-just-fine-in-the-21st-century/ results in this mf2 `content`:

```json
"content": [{
    "html": "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<style>\nspan.bizcard {\n  display: inline-block;\n  outline: 6px ridge rgba(170, 50, 220, .6);\n  ...",
    "value": "Being professionally evil used to be easier...."
}]
```

which we convert to this AS1 object:

```json
{
  "objectType": "note",
  "url": "https://upon2020.com/blog/2018/02/how-to-be-evil-and-do-just-fine-in-the-21st-century/",
  "displayName": "How to be Evil and Do Just Fine in the 21st Century\n\nJohannes Ernst\nFebruary 24, 2018\nBig Picture\n\n\n\n\n\nspan.bizcard {\n display: inline-block;\n outline: 6px ridge ...",
}
```

obviously problematic. it's even missing `content` entirely. 😕

**Comment by snarfed** [comment]
looks like recent mf2py bug fixes fixed this. it now parses the h-entry's properties on that page to:

```json
"properties": {
  "content": [
    {
      "html": "<style>\nspan.bizcard {\n  display: inline-block;\n  outline: 6px ridge rgba(170, 50, 220, .6);\n ...",
      "value": "Being professionally evil used to be easier. In Al Capone\u2019s time, ..."
    }
  ],
  "name": ["How to be Evil and Do Just Fine in the 21st Century"],
  "..."
}
```

which we convert to this AS1:

```json
{
  "objectType": "article",
  "displayName": "How to be Evil and Do Just Fine in the 21st Century",
  "content": "<style>\nspan.bizcard {\n  display: inline-block;\n  outline: 6px ridge rgba(170, 50, 220, .6);\n ...",
  "..."
}
```

previewing this page on https://brid.gy/twitter/Johannes_Ernst shows that it would publish:

> How to be Evil and Do Just Fine in the 21st Century: upon2020.com/blog/2018/02/h...

thanks again for reporting @jernst!
