### ISSUE TITLE
Brid.gy cannot find Instagram user :(

### ISSUE THREAD

**Issue by kReEsTaL** [snarfed/bridgy#801]
Hello!

I desperately try to connect my Instagram account to my Brid.gy account.

Everytime I try, I get the following error: “Couldn't find Instagram user '[_my account_]'. Please check your site's rel-me link and your Instagram account.”, although the said Instagram user does exist, and the link on my website leading to my Instagram profil does have the `rel="me"` attribute.

I did try logging off from everything, relogging, changing browsers, using private navigation, nothing changes, the error remains.

What's wrong? Is anybody else getting this error? Has anybody managed to fix it?

Thanks in advance for any tip/clue/help!

**Comment by snarfed** [comment]
hi marie, sorry for the trouble!

looks like instagram has changed their HTML recently, so we need to update our scraping to match. will do. i'll update this issue once that's fixed.

**Comment by snarfed** [comment]
@kReEsTaL thanks again for the heads up. this should be fixed now. feel free to try again!

**Comment by kReEsTaL** [comment]
Thank you so much @snarfed! Brid.gy can now connect to my Instagram account. However, it seems every attemps to send the webmentions coming from Instagram to my website is failing at the moment. I will try again later and keep you updated.

**Comment by snarfed** [comment]
sounds good! good luck.

**Comment by dixonge** [comment]
I'm getting this same exact error now. rel="me" link to Instagram is in footer, Instagram links back, but bridgy isn't seeing it...

https://glenn.thedixons.net
https://www.instagram.com/dixonge

**Comment by snarfed** [comment]
hrm. sorry for the trouble @dixonge!

weird. you're right, the mf2 on https://glenn.thedixons.net looks fine. seems like bridgy isn't getting anything when it fetches that. not sure why.

**Comment by snarfed** [comment]
seems site specific though. i'm able to sign in with http://snarfed.org/ fine, and it fetches and parses ok.

**Comment by dixonge** [comment]
retested a few different ways - removed other rel=me links, moved link into header, provided links with both www and without - indieauth.com (when refreshed) sees the links but says that instagram is not a valid authorization provider - but brid.gy then doesn't see the rel="me" links to instagram at all...

**Comment by dixonge** [comment]
was hoping the latest indieauth plugin update would fix this, but nothing has changed. my rel=me Instagram link is still invisible to Brid.gy.

**Comment by dshanske** [comment]
@dixonge The IndieAuth plugin is completely unrelated to Instagram. Indieauth.com doesn't use Instagram as a provider, but the IndieAuth plugin uses your WordPress site as one. Unrelated to this issue

**Comment by snarfed** [comment]
@dshanske not quite true. bridgy uses indieauth as part of its instagram signup flow, since instagram (effectively) shut down their API for non-business users.

**Comment by snarfed** [comment]
a few data points:

* pin13 can fetch https://glenn.thedixons.net ok: https://pin13.net/mf2/?url=https://glenn.thedixons.net/
* bridgy can't
* granary (same stack as bridgy, same libs, similar IP address range) can't fetch it either: https://granary.io/url?input=html&url=https://glenn.thedixons.net
* python app engine shell (same stack and IPs, slightly different libs) _can_ fetch it: https://shell-hrd.appspot.com/

    ```
    >>> import requests
    >>> resp = requests.get('https://glenn.thedixons.net', stream=True)
    >>> resp.status_code
    200
    >>> resp.headers
    ...
    ```

**Comment by snarfed** [comment]
my current theory is that brotli compression is the culprit. looking at the response headers, https://glenn.thedixons.net is serving all of the python app engine services above a brotli-compressed response with the `Content-Encoding: br` header, which the python requests library doesn't have built in support for.

i suspect app engine's HTTP fetching service is being a bit aggressive and adding something like `Accept-Encoding: */*` to its requests by default, which triggers this.

**Comment by snarfed** [comment]
sadly, requests _thinks_ it's sending `Accept-Encoding: gzip, deflate`. continuing the https://shell-hrd.appspot.com/ session above:

    ```
    >>> resp.request.headers
    {'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.4'}
    ```

**Comment by snarfed** [comment]
app engine docs don't say that the urlfetch services changes `Accept-Encoding`: https://cloud.google.com/appengine/docs/standard/python/outbound-requests#request_headers

**Comment by snarfed** [comment]
grr. even when i give requests an explicit `Accept-Encoding`, i still get `Content-Encoding: br` back. from https://shell-hrd.appspot.com/ :

```
>>> resp = requests.get('https://glenn.thedixons.net', stream=True, headers={'Accept-Encoding': 'gzip, deflate'})
>>> resp.request.headers
{'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.4'}
>>> resp.headers
{'content-length': '18765', 'content-encoding': 'br', 'vary': 'Accept-Encoding', ...}
```

...but when i do the same thing with curl, https://glenn.thedixons.net correctly sends back a non-brotli response:

```
curl -v https://glenn.thedixons.net -o /dev/null -H 'Accept-Encoding: gzip, deflate'
...
> Accept-Encoding: gzip, deflate
...  # no Content-Encoding, response body uncompressed
```

**Comment by snarfed** [comment]
@dixonge apologies for the stream of consciousness debugging here. i'm still investigating, but just fyi, if you turn off brotli compression in your web server (looks like nginx), or switch to gzip, that should fix this problem for you.

**Comment by dixonge** [comment]
No problem! Using Apache, will investigate gzip shortly

**Comment by snarfed** [comment]
ugh, figured it out. app engine urlfetch is adding `gzip,deflate,br` to outbound requests' `Accept-Encoding`. from https://shell-hrd.appspot.com/ :

```
>>> from google.appengine.api import urlfetch
>>> resp = urlfetch.fetch('https://httpbin.org/headers', headers={'Accept-Encoding': 'gzip, deflate, foo'})
>>> resp.status_code
200
>>> print(resp.content)
{
  "headers": {
    "Accept-Encoding": "gzip, deflate, foo,gzip,deflate,br",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "AppEngine-Google; (+http://code.google.com/appengine; appid: s~shell-hrd)",
    "X-Cloud-Trace-Context": "795505ff8141cf535fa9cf33afe59daa/1604381323415253803;o=1"
  }
}
```

clearly a problem, and not documented. i'll file a bug with them.

also, entertaining, we actually hit this before, a couple months ago: https://github.com/snarfed/bridgy/issues/829#issuecomment-393724931 . cc @aaronpk 😆.

**Comment by snarfed** [comment]
posted on the app engine mailing list: https://groups.google.com/d/topic/google-appengine/0BKwC_YQPQs/discussion

**Comment by dshanske** [comment]
Isn't it Indieauth.com? I apologise if I misunderstood

**Comment by snarfed** [comment]
> Isn't it Indieauth.com? I apologise if I misunderstood

definitely not hard coded, no. it uses the site's auth endpoint, whether it's indieauth.com or something else.

**Comment by dixonge** [comment]
I'm on shared hosting, but found an option for php.ini to enable gzip - did so, and tried brid.gy again. The only difference is that I got no errors for Instagram. However, it's not showing up on my brid.gy user page with my other services. will test the flow soon.

**Comment by snarfed** [comment]
thanks @dixonge! your site is still serving brotli though. to get the workaround to work, you'll actually need to turn that off.

i can work on adding brotli support to bridgy too, but that may be nontrivial, so i don't have an ETA for that.

**Comment by dixonge** [comment]
Found it! WAY too easy, actually. For future reference, add this to your .htaccess to disable brotli (should work with any shared hosting)

```SetEnv no-brotli```

Logged out of everything at brid.gy, logged back in, Instagram all good!

Thanks for your assistance on this, sorry for the hassle

**Comment by snarfed** [comment]
thanks again for all the debugging help! i've filed https://issuetracker.google.com/issues/112277350 for app engine.
