### ISSUE TITLE
Brid.gy fails to send webmentions from Instagram

### ISSUE THREAD

**Issue by kReEsTaL** [snarfed/bridgy#802]
Hello!

Brid.gy is now connected to my Instagram account. However, it fails to send webmentions from Instagram to my website.

Here is a sample log (I replaced my Instagram login and website URL with XXX for privacy):

`0.1.0.2 - - [19/Mar/2018:01:24:50 -0700] "POST /_ah/queue/propagate HTTP/1.1" 200 84 "https://brid.gy/retry" "AppEngine-Google; (+http://code.google.com/appengine)"`

`2018-03-19 08:24:43.739970 D Params: NestedMultiDict([('response_key', u'aglzfmJy...')])`
`2018-03-19 08:24:43.893240 I Source: XXX (Instagram) XXX, http://brid.gy/instagram/XXX`
`2018-03-19 08:24:43.893590 I Created by this poll: http://brid.gy/log?start_time=1521381599&key=aglzfmJyaWQtZ3lyGgsSCUluc3RhZ3JhbSILbGFsdW5lbWF1dmUM`
`2018-03-19 08:24:43.894000 I Starting Response like tag:instagram.com,2013:1736863473662476403_3867112098_liked_by_256128454 https://www.instagram.com/p/BgalCCDAMBz/#liked-by-256128454`
`2018-03-19 08:24:43.908390 I Webmention from https://brid-gy.appspot.com/like/instagram/XXX/1736863473662476403_3867112098/256128454 to https://XXX`
`2018-03-19 08:24:43.910360 I Sending...`
`2018-03-19 08:24:50.091470 I Giving up this target. {'body_json': {u'message': u'Lien destination introuvable', u'code': u'...', u'data': {u'status': 400, u'data': {u'comment_date': u'2018-03-19 09:24:51', u'comment_approved': 0, u'target': u'https://XXX', u'comment_type': u'webmention', u'comment_date_gmt': u'2018-03-19 08:24:51', u'comment_meta': {u'webmention_target_url': u'https://XXX', u'webmention_created_at': u'2018-03-19 08:24:51', u'webmention_source_url': u'https://brid-gy.appspot.com/like/instagram/XXX/1736863473662476403_3867112098/256128454'}, u'comment_author_IP': u'107.178.194.109', u'source': u'https://brid-gy.appspot.com/like/instagram/XXX/1736863473662476403_3867112098/256128454', u'comment_agent': u'Bridgy (https://brid.gy/about) AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)', u'comment_author_url': u'https://brid-gy.appspot.com/like/instagram/XXX/1736863473662476403_3867112098/256128454', u'comment_post_ID': 23164, u'comment_parent': u'', u'comment_author_email': u''}}}, 'code': '...', 'request': u'POST https://XXX/wp-json/webmention/1.0/endpoint (with source=https://brid-gy.appspot.com/like/instagram/XXX/1736863473662476403_3867112098/256128454, target=https://XXX)', 'http_status': 400}`

The log says "Lien destination introuvable'" which means "Destination link cannot be found", however my blog URL is working. I can't understand what's wrong.

NB: everything is working well with webmentions coming from Twitter and Facebook. 

Thanks a lot for your help! :)

**Comment by snarfed** [comment]
thanks for your persistence, and apologies again for the problems! looks like this is a similar problem, we need to update our code to handle Instagram's new HTML. will do.

**Comment by snarfed** [comment]
fixed. bridgy has now sent those webmentions to your site. thanks again for your patience!

**Comment by kReEsTaL** [comment]
Great, thank you so much!
