### ISSUE TITLE
Blogger domain localisation breaks webmentions via bridgy

### ISSUE THREAD

**Issue by kevinmarks** [snarfed/bridgy#805]
If I go to a blogger post while in  the  uk, instead of:
http://epeus.blogspot.com/2008/01/urls-are-people-too.html

I get redirected to:
http://epeus.blogspot.co.uk/2008/01/urls-are-people-too.html

When I link to this post eg from https://mastodon.social/@kevinmarks/99801691700756768

and then send a webmention using mention.tech things get confused. If I look up the .co.uk version, the webmention validates for mention.tech, but then bridgy gives a 400:

```
SendMention POST to https://www.brid.gy/webmention/blogger result.content { (/base/data/home/apps/s~mention-tech/1.408033659792851681/main.py:240)
  "error": "Could not find Blogger account for epeus.blogspot.co.uk. Is it registered with Bridgy?"
}
```
If I change the webmention target to the .com version, then the link is not found in the source post.

Not sure how to fix this - seems bridgy would need knowledge of blogger's idiosyncrasies here.

**Comment by kevinmarks** [comment]
There is a rel="canonical" link:
```
<link href='http://epeus.blogspot.com/2008/01/urls-are-people-too.html' rel='canonical'/>
 ```

**Comment by kevinmarks** [comment]
in the uk (presumably geoip) I gte a 302 on the canonical url:
```
curl --head http://epeus.blogspot.com/2008/01/urls-are-people-too.html
HTTP/1.1 302 Moved Temporarily
Location: http://epeus.blogspot.co.uk/2008/01/urls-are-people-too.html
```

**Comment by snarfed** [comment]
thanks for filing, and for the useful details! and sorry for the trouble.

bridgy already encodes lots of silo peculiarities, so I'd be fine with adding this one. any chance you know where they list their domain logic? if not i can see what i can find.

**Comment by snarfed** [comment]
ah! if rel canonical is consistent, that's perfect, and easy. I'll try it.

**Comment by snarfed** [comment]
(btw @kevinmarks, just fyi, your blogger auth on bridgy expired at some point: https://brid.gy/blogger/3200930 )

**Comment by snarfed** [comment]
ok, i think this is fixed. feel free to try again once you're re-authed!

**Comment by kevinmarks** [comment]
that did work, though the comment preview didn't come out that well - any
idea why it got ellipsised with so little text?
http://epeus.blogspot.co.uk/2008/01/urls-are-people-too.html

**Comment by snarfed** [comment]
no good reason! thanks for the nudge, i'll increase the snippet length.

**Comment by kevinmarks** [comment]
Was it measuring it in HTML rather than rendered text?

**Comment by snarfed** [comment]
nah, just 30 char limit for no good reason.
