### ISSUE TITLE
clean up mentions of instagram API

### ISSUE THREAD

**Issue by sknebel** [snarfed/bridgy#806]
on https://brid.gy/about, there is an embed of a screencast showing the flow with Instagram, using the API login. (we just had a user in #indieweb reference that video and being confused about why it looked differently for them)

and

> Instagram is the one exception. The Instagram API doesn't expose whether an account is private, so Bridgy handles all Instagram photos and comments. If your Instagram account is private, don't sign it up for Bridgy!

presumably bridgy doesn't work with private accounts instagram accounts at all now?

**Comment by snarfed** [comment]
thanks for the nudge! will do.
