### ISSUE TITLE
facebook no longer gives us users' web site URLs

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#807]
Facebook recently locked down or turned off access to a number of API fields and endpoints: https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/#4-4-2018

most of them don't matter to us, including the events and pages edges; we don't use them. the one that does matter is `user.website` (and `user.about`), which we used to match accounts with their web site(s) and domain(s). we use those for OPD and publish.

so, we need to either add UI to let facebook users tell us their web site(s), or warn loudly that OPD and publish won't work for new FB users. ugh. 😢

**Comment by snarfed** [comment]
confirmed on an example user who signed up after 4/4: https://brid.gy/facebook/555706984828608 . they have a web site in their facebook profile, and bridgy has the user_website permission, but [FB no longer returns the user.website field](https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/#user-4-4), and [the permission is deprecated](https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_website).

**Comment by snarfed** [comment]
@kevinmarks inspired an interesting (but painful) idea: scrape the user's public FB profile page and extract the website URL(s) from there. notably, the link on the main profile page, eg https://www.facebook.com/Thorsten.Konigorski , doesn't have `rel=me`, but the one one the about page, eg https://www.facebook.com/Thorsten.Konigorski/about , does.

*however*, we only get app-scoped user ids from the API, not profile URLs, nicknames, or global user ids. we construct profile URLs with app scoped user ids, https://www.facebook.com/555706984828608 , but those require FB login before they'll redirect to the real profile URL, so they're no good for scraping. 😢

**Comment by armingrewe** [comment]
I have a vague memory of FB occasionally "signing you out of bridgy" and having to link the account again? Will this problem hit then as well?

**Comment by snarfed** [comment]
@armingrewe yup, every two months: https://brid.gy/about#facebook-expired . fortunately bridgy remembers existing users' web sites, so this is fine.

**Comment by vthunder** [comment]
Possibly I don't understand how it's all meant to fit together, but why use the website field from Facebook at all? Personally, I don't have mine set, and am pretty ambivalent about setting it. I think I should still be able to set up any page of my choosing to be mirrored over to my Facebook profile.

**Comment by snarfed** [comment]
@vthunder website isn't required for basic [listen](https://brid.gy/about#listen) (aka [backfeed](http://indieweb.org/backfeed)) support. it's only needed for [original post discovery](https://brid.gy/about#link) and [publish](https://brid.gy/about#publish).

we originally pulled web sites from silo profiles (instead of asking users for them) because it made the initial setup UX easier, and because i'm not great at UI. :P we'll keep it for the other silos for now, but for facebook at least, this will indeed make us start asking for it explicitly instead.

**Comment by vthunder** [comment]
Oh yes - I understood it only applies to publishing. Just wanted to point out that at least for me, I don't necessarily want to rely on a link back to my personal homepage from each silo.

I get that it's less UI to write, though!
