### ISSUE TITLE
GitHub: publish tag-of posts to add labels to issues

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#811]
Problem: Currently you have to use GitHub’s web UI to add (and remove) labels from issues.

The indieweb has nascent ['tag-reply' post type](https://indieweb.org/tag-reply) using 'u-tag-of' markup. See [this minimal set of markup inside an h-entry](https://indieweb.org/tag-reply#How_to_simple_tag-reply).

I realize it would be even more helpful to have a real-live tag-of post permalink to refer to (preferably to a GitHub issue), so I will work on that next. I’m hoping this is enough to at least get started though.

It would be great if Bridgy Publish could 1. recognize that tag-of post to a GitHub issue, 2. add the respective label to the issue.

Label(s): publish

(Originally published at: http://tantek.com/2018/108/b1/bridgy-publish-should-posse-tag-of)

**Comment by tantek** [comment]
There is also the counterpart: 'untag-of' posts (<https://indieweb.org/untag>) which are more of a brainstorm at this point, but I figured worth pointing out as a future enhancement, in case that helps generalize the code for 'tag-of' support.

Problem: currently you have to use Github’s web UI to remove a label from an issue.

If you could post an 'untag-of' response to a GitHub issue, and Bridgy Publish recognized that, it could call the GitHub API to (attempt to) remove the respective label from that issue.

The current brainstormed markup is similar to that for a 'tag-of' post, but with class name 'untag-of' instead.

Feedback and contributions welcome on <https://indieweb.org/untag>

Also reasonable to consider 'untag-of' support a potential future separate issue rather than as part of implementing 'tag-of' support.

(Originally published at: http://tantek.com/2018/108/t2/untag-of-bridgy-publish-github-label)

**Comment by snarfed** [comment]
thanks! agreed.

add/remove label [aren't in the v4 GraphQL API](https://developer.github.com/v4/mutation/) afaict, but [are in the v3 REST API](https://developer.github.com/v3/issues/#edit-an-issue).

**Comment by snarfed** [comment]
interestingly, this would be the first bridgy publish feature for editing an existing post, in any silo, as opposed to creating a new one. (likes don't really count. :P)

**Comment by snarfed** [comment]
deployed!
