### ISSUE TITLE
Bridgy tweets link to Github profile instead of originating website

### ISSUE THREAD

**Issue by khurtwilliams** [snarfed/bridgy#816]
For some reason, bridgy tweets include a link to my Github instead of the originating web site. Example here: https://twitter.com/khurtwilliams/status/987739134788866048

**Comment by snarfed** [comment]
hey, sorry for the trouble! [looking at the list](https://brid.gy/log?start_time=1524330335&key=aglzfmJyaWQtZ3lybQsSDVB1Ymxpc2hlZFBhZ2UiRmh0dHBzOi8vaXNsYW5kaW50aGVuZXQuY29tL3RocmVlLW1hZ25ldHMtYnJld2luZy1jb21wYW55cy10aGUtZGFtLW1hZC8MCxIHUHVibGlzaBiAgICAgICACgw), it looks like your mf2 on that page has all of your profile `u-url`s in the `h-entry` itself. you probably want them either outside it or inside the `h-author`.

**Comment by khurtwilliams** [comment]
Ah ... yes, I see it. I may switch to a more MF2 friendly WordPress theme.

**Comment by snarfed** [comment]
sounds good!
