### ISSUE TITLE
publish for facebook is dead

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#817]
they're turning it off in the API altogether. RSVPs today, posts 8/1/2018. https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/

it's a brave new world.

**Comment by pierreozoux** [comment]
sad to see that :/ I'm leaving facebook anyway :)

**Comment by snarfed** [comment]
i used this `remote_api_shell` snippet to send FB notifications to all bridgy publish users:

```sh
$ setenv FACEBOOK_APP_ID `cat facebook_app_id`
$ setenv FACEBOOK_APP_SECRET `cat facebook_app_secret`
$ remote_api_shell.py brid-gy
```
```py
import traceback
from facebook import FacebookPage

for src in FacebookPage.query(
    FacebookPage.status == 'enabled',
    FacebookPage.features == 'publish',
  ).iter(offset=5):
  if src.auth_entity.get().type == 'user':
    print(src.label(), src.silo_url())
    try:
      src.gr_source.create_notification(
      src.key.id(),
      'Publish for Facebook will shut down in August. (Backfeed will still work.) So long, and thanks for all the fish!',
      'https://brid.gy/about#facebook-publish')
    except Exception as e:
      traceback.print_exc()
```

**Comment by snarfed** [comment]
F8 announcements today and Graph API v3.0 changes may mean facebook backfeed is dead too. not sure yet. details in https://github.com/snarfed/bridgy/issues/814#issuecomment-385749430.

**Comment by snarfed** [comment]
yup, backfeed is dead too. #826

**Comment by snarfed** [comment]
82d0b0cc9f9b6c3c30d0b04255636b9b0326a0b4

**Comment by snarfed** [comment]
facebook publish attempts now 400. closing.
