### ISSUE TITLE
Do not backfeed retweets of mentions

### ISSUE THREAD

**Issue by kaushalmodi** [snarfed/bridgy#819]
This issue is discussed on https://chat.indieweb.org/dev/2018-04-30, search for "retweet").

Summary:

1. There was a tweet that mentioned my Twitter handle: https://twitter.com/jxxf/status/990787587278295040
2. When I retweeted that, that tweet did not generate a "repost" webmention, but the exact same "link" webmention as the original tweet.
3. So I ended up with duplicate webmentions of the same tweet with just different time stamps (original tweet time stamp and retweet time stamp). The author, webmention type, etc. all was the exact same in the two.

This is WM created by bridgy for the retweet: https://brid-gy.appspot.com/post/twitter/kaushalmodi/990803136448253952. It should have looked like this instead: https://brid.gy/repost/twitter/kaushalmodi/990787587278295040/990803136448253952.

**Comment by snarfed** [comment]
thanks for filing!

**Comment by kaushalmodi** [comment]
Thanks!
