### ISSUE TITLE
Twitter like missed

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#821]
https://twitter.com/singpolyma/status/995345080037920768 has a like, but https://brid.gy/twitter/singpolyma does not show it having been sent, even though it is older than the retweet that *has* been sent

**Comment by snarfed** [comment]
Twitter responses are sadly best effort only for a whole host of reasons: https://brid.gy/about#Twitter+responses

**Comment by singpolyma** [comment]
Oh, interesting. I'm sure you've told me this before :P I guess I just assumed there would be a notifications API
