### ISSUE TITLE
Bridgy posting images and text to Twitter and Facebook but not link back to post

### ISSUE THREAD

**Issue by khurtwilliams** [snarfed/bridgy#822]
On my self-hosted WordPress [site](https://islandinthenet.com) running 4.9.6 and Bridgy 1.4.1 plugin, I have "Bridgy Publish to Twitter" enabled. The excerpt is left blank. Bridgy publishes the Tweet with the title text of the post along with the featured image for the post. However, the link to the post is not posted along with the tweet.

Post example here: https://islandinthenet.com/web-lost/
Tweet: https://twitter.com/khurtwilliams/status/997331562034352128
My manual tweet: https://twitter.com/khurtwilliams/status/997429855775084546
Bridgy Twitter user page: https://brid.gy/twitter/khurtwilliams
Bridgy log: http://bit.ly/2IPXef5

Another example is below. I posted an original u-in-reply-to via my website with the same content as this issue entry included here. See the bottom where it says *(Originally published at: Twitter)*

![screen shot 2018-05-18 at 7 21 05 am](https://user-images.githubusercontent.com/686971/40232602-73e2c276-5a6d-11e8-98ba-f1254078dc6e.jpg)

![screen shot 2018-05-18 at 7 29 45 am](https://user-images.githubusercontent.com/686971/40232610-7feaa3e0-5a6d-11e8-9fa2-517f57fe214d.jpg)

**Comment by khurtwilliams** [comment]
![Bridgy posting images and text to Twitter and Facebook but not link back to post #822 Screen Shot 2018 05 18 at 7.21.05 AM](https://islandinthenet.com/wp-content/uploads/2018/05/Screen-Shot-2018-05-18-at-7.21.05-AM.jpg)

On my self-hosted WordPress [site](https://islandinthenet.com) running 4.9, I have “Bridgy Publish to Twitter” enabled. The excerpt is left blank. Bridgy publishes the Tweet with the title text of the post along with the featured image for the post. However, the link to the post is not posted along with the tweet.

Post example here: https://islandinthenet.com/web-lost/
Tweet: https://twitter.com/khurtwilliams/status/997331562034352128
My manual tweet: https://twitter.com/khurtwilliams/status/997429855775084546
Bridgy Twitter user page: https://brid.gy/twitter/khurtwilliams
Bridgy log: http://bit.ly/2IPXef5

![Bridgy posting images and text to Twitter and Facebook but not link back to post #822 40232602 73e2c276 5a6d 11e8 98ba f1254078dc6e](https://user-images.githubusercontent.com/686971/40232602-73e2c276-5a6d-11e8-98ba-f1254078dc6e.jpg)

![Bridgy posting images and text to Twitter and Facebook but not link back to post #822 40232610 7feaa3e0 5a6d 11e8 9fa2 517f57fe214d](https://user-images.githubusercontent.com/686971/40232610-7feaa3e0-5a6d-11e8-9fa2-517f57fe214d.jpg)

(Originally published at: Twitter)

**Comment by snarfed** [comment]
huh. sorry for the trouble, and thanks for filing!

definitely looks like a bug. if you preview https://islandinthenet.com/web-lost/ on https://brid.gy/twitter/khurtwilliams with _Include link: yes_, that doesn't include the link either. will look.

**Comment by snarfed** [comment]
ah, it's because your mf2 is unhappy. you have `u-url` on the `<li>` tags around your `rel-me`s, eg (pretty-printed):

```html
<li id="menu-item-24102" class="u-url menu-item menu-item-type-custom menu-item-object-custom menu-item-24102">
  <a rel="me identity" href="https://twitter.com/khurtwilliams/">
    <span class="screen-reader-text">Twitter</span>
  </a>
</li>
...
```


...which results in this parsed mf2:

```json
{
  "type": ["h-entry"],
  "properties": {
    "url": [
      "Twitter",
      "Instagram", 
      "..."
    ],
    "..."
```

which says that your post's canonical URLs are `Twitter`, `Instagram`, etc. bridgy sees that, but also knows those aren't real urls, so it backs off.

if you drop the `u-url` from those `<li>`s, bridgy publish should include the url.

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!

**Comment by khurtwilliams** [comment]
Thank you. I'm using the [IndieWeb Twenty Sixteen](https://github.com/dshanske/twentysixteen-indieweb) theme with the author h-card widget. There might be an error in how that theme or the widget handles things.

**Comment by khurtwilliams** [comment]
Found the issue. As you suggested it was the u-url iin the li. This was being generated by the social profiles menu. Removed the u-url and the issue is resolved.

**Comment by khurtwilliams** [comment]
And ... the problem is back. I'm not sure how to troubleshoot these issues.

**Comment by sknebel** [comment]
@snarfed see also todays discussion in #indieweb-wordpress: https://chat.indieweb.org/wordpress/2018-07-29#t1532872500460200

The markup on @khurtwilliams page was broken in that way, and php-mf2 showed the same result. Right now it appears the page is fixed, the HTML is fine and both parsers see the same correct result for me, I guess @khurtwilliams changed things again?

**Comment by snarfed** [comment]
ah! thanks for the catch @sknebel. @khurtwilliams please do let us know if that fixed it!

on a related note, we're talking about a potential mf2 linter/validator in #indieweb-dev right now.

**Comment by khurtwilliams** [comment]
Yep.  It seems my update to the IndieWeb Twenty Sixteen theme reenabled the social profiles menu. Need to put in a reminder note For myself.

**Comment by snarfed** [comment]
thanks for confirming!
