### ISSUE TITLE
No webmention support message (where once it worked)

### ISSUE THREAD

**Issue by chrisjonesio** [snarfed/bridgy#825]
Greetings,

I once had a nice, working bridgy connection for both Twitter and Instagram but in the last couple of months I seemed to have lost it. I'm finally getting around to tracking down the issue and can't summon the correct debugging path to get at the issue.

Basically, bridgy shows me the "No webmention support" response for both Twitter and Instagram posts, the log of course shows the same thing. Bridgy finds the originals on my site but can't seem to detect my webmention endpoint and it is killing me.

**Site**: https://chrisjones.io/
**Twitter**: @chrisjonesio
**Instagram**: chrisjonesio
**Server**: Apache 2.4.33
**OS**: Ubuntu 18.04 LTS (GNU/Linux 4.15.0-22-generic x86_64)

I've been messing with _Service Workers_ and _brotli_ compression, not sure if that has anything to do with it. I have the webmention endpoint specified in both an HTTP Link header and in the HTML markup. Issuing `curl -i -s https://chrisjones.io/stream/501/canoe-trip-packing/ | grep 'rel="webmention"'` returns the expected value (my endpoint is at https://chrisjones.io/service/webmention/). Inspecting the headers with `curl --head -X GET https://chrisjones.io/stream/501/canoe-trip-packing/` also shows the correct webmention header.

So, any ideas? The only thing left I have to ponder over is that my header is "link" whereas most (all?) examples I see online the header is "Link" (notice the uppercase). I'm not doing that on purpose, it seems to just come out that way from Apache, it is "Link" in my Apache config. Is there some kind of case-sensitivity in the endpoint detection? For what it's worth, _Receiver Test 1_ over at https://webmention.rocks also fails to find my webmention endpoint.

Finally, I can manually send the webmentions so I think my receiving code is all good.

As a post to look at, https://chrisjones.io/stream/501/canoe-trip-packing/ is missing Instagram likes, the Twitter likes are there after I put them there manually.

Thanks! Let me know if I can provide any additional information, etc. I'm keen to figure this one out!

**Comment by chrisjonesio** [comment]
My logs are showing a 403 for the webmention.rocks test. I must have a config somewhere for some dumb reason. I'll get to the bottom of this. Closing.

**Comment by snarfed** [comment]
thanks for the thorough, detailed report! good luck debugging. let me know if i can help.
