### ISSUE TITLE
Update mf2py (waiting for next release)

### ISSUE THREAD

**Issue by sknebel** [snarfed/bridgy#828]
Exciting new features! E.g. improved implied name handling, which keeps cropping up. (e.g. http://twtr.io/1eNFR0C3voG )

**Comment by snarfed** [comment]
yes! this should fix or at least help with snarfed/granary#145 and snarfed/granary#142 too.

bridgy is pretty particular about mf2py's behavior, and some new changes are nontrivial, eg it adds `img` URLs to implied names in some (all?) cases, so this will take more work than just bumping the version. still, definitely worthwhile!

**Comment by snarfed** [comment]
the `img` URL thing did turn out to be a dealbreaker for mf2py 1.1.0. details in https://github.com/microformats/microformats2-parsing/issues/35 .

the good news is, it sounds like everyone agrees that we should revert that part of the spec, so hopefully I'll be able to upgrade to the next mf2py release!

**Comment by snarfed** [comment]
woo, thanks to @kartikprabhu for implementing the implied name change! https://github.com/microformats/mf2py/commit/71997eb1b18506506515ef41d20a19a186396eb4. can't wait for the next release!

**Comment by snarfed** [comment]
deployed this just now with https://github.com/snarfed/mf2py/tree/all , which has a number of pending mf2py bug fixes, eg microformats/mf2py#115 and microformats/mf2py#118. 🤞

**Comment by snarfed** [comment]
added microformats/mf2py#114 and it's no longer crashing. mf2py at head (with a bunch more unmerged bug fixes) is now live on bridgy prod.

**Comment by snarfed** [comment]
closing, yay. thanks again @sknebel!
