### ISSUE TITLE
No webmention support error

### ISSUE THREAD

**Issue by chrisjonesio** [snarfed/bridgy#829]
Alright, I used to have a working bridgy process sending webmentions but it hasn't worked in a while so I'm trying to figure it all out.

When issuing the curl request:
`curl --head --http1.1 https://chrisjones.io/writing/getting-titular/`

I get the following response:

```
HTTP/1.1 200 OK
Date: Thu, 31 May 2018 19:54:04 GMT
Server: Apache/2.4.33 (Ubuntu)
Link: https://chrisjones.io/service/webmention/; rel="webmention"
Server-Timing: api;dur=0.0003530159;desc="API requests"
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Upgrade: h2
Connection: Upgrade
Cache-Control: max-age=0, no-store, no-cache, must-revalidate
Expires: Thu, 1 Jan 1970 00:00:00 GMT
Vary: Accept-Encoding
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
```
As you can see, there's the webmention link in the response.

Log shows nothing out of the ordinary:

`35.187.132.91 - - [31/May/2018:16:45:53 -0300] "GET /writing/getting-titular/ HTTP/1.1" 200 12887 "-" "Bridgy (https://brid.gy/about) AppEngine-Google; (+http://code.google.com/appengine; appid: s~brid-gy)"`

And both the webmention.rocks receiver tests show green checkmarks all the way down and can find my webmention endpoint.

Anything else I can do to try and track down what might be happening here? Happening for both Twitter and Instagram, which is what I'd expect. It's gotta be something on my server that's misconfigured is all I can think of, but what exactly is beyond me at the moment.

Any direction would be much appreciated.

**Comment by snarfed** [comment]
hey again chris, sorry for the trouble! wow, this is an odd one. i found the problem, but i don't know what's going on yet.

your server is returning some odd binary data instead of HTML, but only to requests from app engine prod. here's how i reproduced it, on https://shell-hrd.appspot.com/ :

```
>>> import requests
>>> resp = requests.get('https://chrisjones.io/writing/getting-titular/', verify=False, headers={'User-Agent': 'Bridgy (https://brid.gy/about)'})
...
>>> resp.status_code
200
>>> resp.headers.get('content-type')
'text/html; charset=UTF-8'
>>> resp.headers.get('content-length')
'8313'
>>> resp.text
u'\x1b\ufffd{\ufffd\x11\ufffd\ufffd!A\ufffd\u055f\x15Q\x04\x1b\x07\x08d9\x00PO\x07\ufffd\ufffd\ufffdu\u0732W\x10#\x0bT\x18U\ufffd\u0568...
```

the entry from your server log seems to confirm. when i curl and get HTML, `Content-Length` is 47223, but the one from your log is 12887, and mine is 8313. when i repeated mine, i got 8317 and 8340. odd that it's changing.

**Comment by snarfed** [comment]
out of curiosity, i wrote one of these responses to a file and ran `file` on it, but it just reported `data`, so it's evidently not an obvious well-known file type.

**Comment by chrisjonesio** [comment]
Hmmm. I've got brotli compression on, but it *should* be falling back to gzip where unsupported. That was my first thought.

I did see a webmention go through a little earlier, must have been you poking and prodding 😃

Leave it to me to tinker to the point of breaking!

**Comment by aaronpk** [comment]
Sending a request with an accept-encoding header of the below makes it return regular HTML.

```
Accept-Encoding: br;q=0,deflate,sdch
```

Can you make it serve an uncompressed version by default if no `Accept-Encoding` header is present?

**Comment by aaronpk** [comment]
Actually it looks like app-engine is sending `Accept-Encoding: gzip, deflate`, so I'm confused why your site would send back a brotli response.

```
>>> resp.request.headers
{'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'Bridgy (https://brid.gy/about)'}
```

**Comment by chrisjonesio** [comment]
Yup, disabling the brotli module gets everything working again. It seems I need to take a closer look at the brotli and gzip module configurations. I can't figure out why an Accept-Encoding of gzip is getting sent br content. Maybe the module order is wrong, not sure. But for now I'm back in action, and appreciate the help in debugging and tracking the cause down. Very sorry for the noise!

**Comment by snarfed** [comment]
no worries! glad we figured it out. definitely entertaining. good luck!

**Comment by snarfed** [comment]
for the record, this turned out to be an App Engine bug: [it incorrectly adds `br` to `Accept-Encoding` in all outbound HTTP requests, regardless of the initial (app-provided) value.](https://issuetracker.google.com/issues/112277350) still open, almost a year later. ☹️  i've nudged them.
