### ISSUE TITLE
Error on webmention.io on like from bridgy

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy#830]
https://brid.gy/log?start_time=1527862621&key=aglzfmJyaWQtZ3lyTAsSCFJlc3BvbnNlIj50YWc6dHdpdHRlci5jb20sMjAxMzoxMDAyNTQ1MDY4ODM2NzE2NTQ1X2Zhdm9yaXRlZF9ieV8xNzI2OTQ4NAw

https://webmention.io/realize.be/webmention/pueABJKW5HLQkNSzgeo9

It's on a like, but it might not be a bridgy problem, but just wanted to log this.

**Comment by snarfed** [comment]
huh. cc @aaronpk. source URL is https://brid-gy.appspot.com/like/twitter/swentel/1002545068836716545/17269484 , which is serving fine.

notably, the webmention.io status page says the error is in parsing the source _URL_, but the URL itself seems fine too.

i know wm.io originally got a 400 from it though. maybe there's a bug in its retry logic?

**Comment by swentel** [comment]
got it again, now at https://brid.gy/log?start_time=1527952753&key=aglzfmJyaWQtZ3lySwsSCFJlc3BvbnNlIj10YWc6dHdpdHRlci5jb20sMjAxMzoxMDAyOTI1MzI1MzY0NDU3NDczX2Zhdm9yaXRlZF9ieV81MzM0MTYyDA

hoping for someone retweet or reply to see if those keep going well :)

**Comment by swentel** [comment]
Closing, everything is fine now again. It looked like something with a certification and/or upgrade on aaron's servers.
