### ISSUE TITLE
Respond with previous URL when a duplicate webmention is detected

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/bridgy#835]
When you send a second webmention, Bridgy replies with: Sorry, you've already published that page, and Bridgy Publish doesn't yet support updating or deleting existing posts.

It would help to add a "url" attribute that provides the url of the previous syndication. This would allow me to send webmentions for posts that had previously be syndicated and get the URL of that syndication into my system :)

(Originally published at: https://eddiehinkle.com/2018/07/18/7/reply/)

**Comment by snarfed** [comment]
interesting! good idea. in the short term, you can grab the last 10 publishes from bridgy's API: http://brid.gy/about#api . they're ordered chronologically, descending, so the most recent one will be first.

**Comment by snarfed** [comment]
we'd also have to figure out where exactly to return the url. human readable text messages for 400 errors are currently shared by both webmention and interactive publish, so i can't really change that one to return json. i guess maybe i could return it in the http `Location` header?

**Comment by EdwardHinkle** [comment]
Hmm, interesting. the 400 errors aren't JSON? I guess maybe Telegraph is transforming the response into JSON, because when Telegraph returns the http_body from a bridgy failure, it returns a JSON object with an error attribute.

HTTP location header could work. Might have to tweak Telegraph to return that value to webmention status. Currently it only passes through the http code and body

**Comment by snarfed** [comment]
[eddie says API sounds good.](https://chat.indieweb.org/dev/2018-07-23#t1532378547217300) tentatively closing. feel free to reopen!
