### ISSUE TITLE
twitter publish: posts unsupported markdown(?) formatting

### ISSUE THREAD

**Issue by sknebel** [snarfed/bridgy#837]
https://www.svenknebel.de/posts/2018/7/10/ posts as https://twitter.com/HeNeArXn/status/1023222087614386176 -> it appears bridgy tried to preserve the `<i>` tags on the species name and posted them as `_`, which Twitter doesn't recognize as formatting.

**Comment by snarfed** [comment]
heh, yes! this is expected,  bridgy's text to html conversation includes some formatting markdown-isms like this. you can prevent that with https://brid.gy/about#ignore-formatting or https://brid.gy/about#silo-content .

**Comment by snarfed** [comment]
yeah, understood. the primary value of that conversion is preserving whitespace, which you generally do want. hard to separate the two, at least the way I'm currently doing it, with html2text.
