### ISSUE TITLE
switch to twitter's new premium search API?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#838]
_copying from https://github.com/snarfed/granary/issues/136 for searchability_

we currently use [twitter's existing (legacy? :P) search API](https://developer.twitter.com/en/docs/tweets/search/overview/standard) that "searches against a sampling of recent Tweets published in the past 7 days." this incompleteness regularly causes problems and user confusion when we miss twitter replies, since twitter's REST API has no way to get a tweet's replies, so we get them by searching for them. 😡

twitter just launched their new [premium search API](https://developer.twitter.com/en/docs/tweets/search/overview/premium), which includes full history! both paid and free tiers. ([there's also an enterprise search API](https://developer.twitter.com/en/docs/tweets/search/overview/enterprise).)
* https://blog.twitter.com/developer/en_us/topics/tools/2018/access-the-full-history-of-tweets.html
* https://developer.twitter.com/en/docs/tweets/search/overview/premium

...except you have to [ask permission, tell them what you're building, and get approved.](https://developer.twitter.com/en/apply/user) :(

more importantly, [the premium API costs $0.25-$1/request/month](https://developer.twitter.com/en/pricing/search-30day), depending on volume and endpoint (30d vs full history), and the free tier is limited to 50-250 requests/month. neither option is doable.

**Comment by obetomuniz** [comment]
How did you deal with this @snarfed ?

**Comment by snarfed** [comment]
@obetomuniz heh, sorry, should have explained here. i didn't, i'm still on the old search API.
