### ISSUE TITLE
Support rel-alternate

### ISSUE THREAD

**Issue by dshanske** [snarfed/bridgy#839]
Because of the theme/microformats2 issue in WordPress, @pfefferle has released a plugin called mf2-feed that implements https://indieweb.org/rel-alternate

It is still filling in the remaining properties from Micropub and Post Kinds(PR is pending), but having Bridgy support this would be helpful for people who don't have a compatible theme.

**Comment by snarfed** [comment]
hmm! bridgy already supports this with `rel=feed`, https://brid.gy/about#link , which afaict fits just as well. @pfefferle mind adding `feed` to your plugin’s  `rel` too?

**Comment by snarfed** [comment]
friendly ping on `rel=feed` @pfefferle @dshanske?

**Comment by snarfed** [comment]
fwiw, [from #indieweb-dev today](https://chat.indieweb.org/dev/2018-10-19#t1539963469304400):

> jackjamieson: That said, I see what you mean petermolnar, I'm not quite clear on why rel=feed is better than rel=alternate -- Maybe because so h-feed is not framed as an "alternate" but rather a canonical feed?
> swentel: ok, so then I'd have to look in aperture or xray why my feed isn't found and do some coding maybe
> swentel: or at least propose
> aaronpk: alternate is supposed to be for an alternate version of the page
> aaronpk: so home page -> h-feed page doesn't make sense as rel=alternate

**Comment by sknebel** [comment]
@snarfed from my understanding the wordpress proposal is to have feeds containing microformats2 *JSON* or jf2, *not* HTML files with mf2 markup like bridgy supports. 

https://github.com/indieweb/wordpress-mf2-feed

**Comment by snarfed** [comment]
ahh ok. thanks @sknebel.

in that case, i don't plan to do this right now, but if i start hearing real demand from real users who legitimately can't get mf2 into their HTML but can serve these alternate feeds, i might consider it.

**Comment by snarfed** [comment]
@dshanske @pfefferle what's the status here? did you see any meaningful adoption of the rel-feed plugin? do you know of any real users who legitimately can't get mf2 into their HTML but can serve these alternate JSON feeds?

**Comment by dshanske** [comment]
The plugin has fewer than 10 active users.

**Comment by dshanske** [comment]
But the goal was to help people who couldn't change their themes.

**Comment by snarfed** [comment]
understood. do you know any of those users specifically? and whether this has helped them, and whether they actively need bridgy to support it?

**Comment by dshanske** [comment]
Not sure. I remember talking to one, but can't recall. We haven't really promoted it.

**Comment by snarfed** [comment]
ok! np. i'm going to tentatively close then. feel free to reopen if/when you all come back to this!
