### ISSUE TITLE
Not identifying syndicated OwnYourGram-generated content

### ISSUE THREAD

**Issue by scottmallinson** [snarfed/bridgy#842]
Having connected OwnYourGram to my Instagram account, posts, e.g. https://www.instagram.com/p/BnAVnXPlItf/ are being syndicated to my personal website, e.g. https://scottmallinson.com/blog/2018/08/28/1364/ but Brid.gy isn't sending webmentions to the post.

The post HTML contains, for example, `<a aria-label="instagram" class="u-syndication syn-link" href="https://www.instagram.com/p/BnAVnXPlItf/" rel="syndication"> </a>`

Oddly, it used to work for older posts, e.g. https://scottmallinson.com/blog/2018/08/18/1209/ but I don't recall having changed anything...

**Comment by snarfed** [comment]
hey Scott, sorry for the trouble! looks like your blog"s index page https://scottmallinson.com/blog/ no longer includes your ownyourgram posts? if it used to work, that may be what changed.

otherwise, I'm guessing you've already looked through https://brid.gy/about#missing ?

**Comment by scottmallinson** [comment]
Hi Ryan, thanks for the prompt response. That makes sense. I should have checked that first, sorry! I'll work on fixing my website.
