### ISSUE TITLE
Article syndicated to twitter is acting like a note

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/bridgy#844]
https://eddiehinkle.com/2018/09/26/16/article/

This article when inspected through pin13 is correctly showing an h-entry with a p-name that is the article’s title.

But for some reason when I preview in the UI or publish to Twitter through sending a webmention it displays a the beginning of the article content instead of the title of the article.

I think this is a change of behavior, and I’m not sure if the issue is on my end or Bridgy’s side?

**Comment by snarfed** [comment]
hey @EdwardHinkle, sorry for the trouble!

the catch here is that you also have `p-summary`, which bridgy prefers before either `p-name` or `p-content`. docs: https://brid.gy/about#microformats

if you don't want bridgy to use that, you could either drop it from your site's mf2, or add `p-bridgy-twitter-content` to your existing `p-name`. docs: https://brid.gy/about#silo-content

**Comment by EdwardHinkle** [comment]
Ohhh! That makes sense 👍
