### ISSUE TITLE
Feb 2019: turn off Google+

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#846]
[Google announced today that it's sunsetting consumer Google+, but keeping enterprise (aka G Suite aka Google Apps).](https://blog.google/technology/safety-security/project-strobe/) should we plan to drop it from bridgy then? or keep it for enterprise users? do we have many of those? any thoughts?

**Comment by snarfed** [comment]
i guess one key question is whether enterprise G+ users can and will post publicly much, since those are the only posts that bridgy will handle. i suspect they technically can, but Google sees non-public posts and data as the future and growth area:

> At the same time, we have many enterprise customers who are finding great value in using Google+ within their companies. Our review showed that Google+ is better suited as an enterprise product where co-workers can engage in internal discussions on a secure corporate social network. Enterprise customers can set common access rules, and use central controls, for their entire organization.

soo... 🤷‍♀️

**Comment by armingrewe** [comment]
The way I read it is that the corporate G+ version is going to be only an internal social network, ie not visible to the public. Similar to Jive or FB Business (or whatever that is called). In other words, no public posts and no need for Bridgy.
With FB already dead for Bridgy and Twitter beginning to smell if they don't start making serious money soon I'm wondering where this is all going to lead. A FB silo monopoly?

**Comment by snarfed** [comment]
> The way I read it is that the corporate G+ version is going to be only an internal social network, ie not visible to the public.

@armingrewe they definitely describe internal use as the more common and interesting use case...but did you see that they explicitly said _no public posts_ anywhere? i didn't see that.

**Comment by armingrewe** [comment]
OK, I have to concede that, it doesn't specifically exclude public posts. Yet the whole wording of that paragraph just screams intranet to me, not extranet. I don't see anyone running their customer service portal or PR hub on an instance of G+.

**Comment by funwhilelost** [comment]
I'm a "G Suite" user for my domain.  Essentially you just get Google Docs, Sheets, Gmail, etc. all hooked up to your domain by setting your MX records and a couple TXT records.  There's a modest monthly fee.  Think of it more like Office365.

With regard to the G+ for "G Suite" users: my interpretation is that they're just looking for a way to preserve a "Facebook Page" type of experience for business customers.  I have my windsurf shop listed on Google Local and they rely very heavily on the profile and posts you set up in G+.  So maybe it's best to think of "Enterprise Google+" as Facebook Pages type functionality, and preserve it for Webmention-able business domains.

**Comment by armingrewe** [comment]
The way I read it is more that they are going to offer something like "Workplace by Facebook" or "Jive Intranet" using the G+ platform. That's like a social network collaboration intranet. They could then have various internal communities for different projects or departments.

**Comment by snarfed** [comment]
i may actually need to do this sooner than august 2019. unrelated to G+, google is also going to turn off batch http requests, which i use in bridgy for G+, in march 2019: https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html

**Comment by armingrewe** [comment]
Just before Brexit day. Someone will find a way to blame the EU ;-)

**Comment by snarfed** [comment]
damn, evidently i need to do more than just that. seeing this warning ([example log](https://brid.gy/log?start_time=1544147387&key=aglzfmJyaWQtZ3lyKQsSDkdvb2dsZVBsdXNQYWdlIhUxMDM2NTEyMzE2MzQwMTgxNTg3NDYM)):

> You have constructed a BatchHttpRequest using the legacy batch endpoint https://www.googleapis.com/batch. This endpoint will be turned down on March 25, 2019. Please provide the API-specific endpoint or use service.new_batch_http_request(). For more details see https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.htmland https://developers.google.com/api-client-library/python/guide/batch.

**Comment by snarfed** [comment]
whee, they sped this up to april for the product, feb for apps, due to another breach: https://blog.google/technology/safety-security/expediting-changes-google-plus/

**Comment by snarfed** [comment]
when the time comes, use 82d0b0cc9f9b6c3c30d0b04255636b9b0326a0b4 (dropping facebook) as a template.

**Comment by snarfed** [comment]
https://developers.googleblog.com/2018/12/google-apis-shutting-down-march-7-2019.html

**Comment by snarfed** [comment]
today is the day! here's a `remote_api_shell` snippet to run as soon as the API is turned off:

```
$ remote_api_shell.py brid-gy

from googleplus import GooglePlusPage

for src in GooglePlusPage.query():
  src.features = []
  src.put()
```

**Comment by snarfed** [comment]
done! RIP G+, 2011-2019.

**Comment by armingrewe** [comment]
It was nice while it lasted. I first heard of Indieweb and Bridgy through G+
