### ISSUE TITLE
Allow multiple webmentions on same url for multiple response types ?

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy#849]
My example is this url: https://realize.be/repost/1632
It's a post which has a u-repost-of link and a u-in-reply-to link (hidden).

I was experimenting to see what would happen. In the end, it seems the reply won (maybe because it's lower in the HTML ?) See https://twitter.com/swentel/status/1062848420786909184
I manually did the retweet on Twitter though.

Now. Handling both response types in one webmention request seems like a bad idea. Especially if you need to return a response with the syndication link. More stuff to handle on our end as well. I don't want to go there.

I know brid.gy blocks publish for a URL that already send a webmention. I wonder whether it would be a good idea to allow it in case the response type is different. In short, 

- send webmention: bridgy parses, sees a reply, publishes reply - and should probably store that there are least two reponse types, setting reply to 1, repost to 0
- send another webmention for same url: bridgy parses, sees that reply is already done, now does repost

Just thinking out load. It seems doable - at least, in my head right now :)

Totally fine if you want to keep it 1 response type per url though!

(#635 is kind of related, but closed for the tag 'h-as-note')

**Comment by snarfed** [comment]
interesting! sounds more or less the same as #832?

you identified many of the reasons I'm reluctant to map a single source post to multiple silo actions. predictability, atomicity, and idempotence are other reasons. 
also (sadly) internal implementation details; more in that in #832.

your two step proposal is definitely clever! it's not exactly obvious from a user perspective though, and i definitely like the Principle of Least Surprise.

so yeah, you guessed right, I'm unlikely to do this. I'll happily keep this open for the record, though, or merge it into #832!

**Comment by swentel** [comment]
Right, the use case seems the same. I don't fully understand the technical impact, a bit confused about granary there .. however, that's totally fine :)

I then need to setup this on the site level. Luckily, within Drupal, it takes me about 5 minutes to create a new content type which has a field which can hold multiple references to other posts (one is a like, one is repost etc). And I then just send webmentions for each individual. And also setup redirects: if someone would go to the 'like' url, redirect to the parent post which has it as a reference. Something like that. Just need to make sure the redirect doesn't happen in communication with brid.gy when it's parsing the post for publishing, or sending a webmention for backfeed.

Ok, closing, the service works great anyway! It also seems that multiple response types hasn't been explored that much within the community, so that's totally fine!

Thanks for the response!

**Comment by swentel** [comment]
Note: it might be interesting though to document the behavior in case brid.gy does find multiple response types and which one takes precedence. You can even link to this issue temporarily. Once I have a setup in Drupal, I will document how I've done it and then we can link to that article!

**Comment by snarfed** [comment]
I'm generalizing this issue to cover all multi-type posts that Bridgy Publish would have to translate to more than one action inside a silo.

i don't plan to support those, for a few reasons beyond just the AS1 implementation details above. specifically:

* atomicity. right now, a bridgy publish request either succeeds completely or falls completely. multi-type parts could partially succeed, ie complete one action inside the silo but fail another.
* recovery.  when an attempt partially succeeds, and the user retries, what should we do? we can't always roll back the silo action, nor can we always safely retry just the failed part(s). more on that in #812.
* UX. it's harder to clearly preview a multi-type post or communicate about it to the user in error messages, etc.

this begs the question, what should we do with multi type posts? we could either return an error, which we currently do with the reply+tag posts described here, or we could pick a single part of them, which we currently do with all other multi-type posts. i documented that in b42365febb5e6be952a7620ee126e72d899081bc yesterday.

erroring out is probably safer, and follows the Principle of Least Surprise, but publishing a single part is more convenient and expected by current users. 🤷
