### ISSUE TITLE
Bridgy Not Picking up Latitude/Longitude as top level properties

### ISSUE THREAD

**Issue by dshanske** [snarfed/bridgy#852]
Will document this later in detail

**Comment by dshanske** [comment]
On my site, I use p-latitude and p-longitude directly inside h-entry instead of nested inside p-location. I use p-location as a textual description of the location.

This is considered acceptable if atypical, but Bridgy doesn't pick it up. As the dependent parsing library does, this suggests this is either a version issue or something else.

I am going to change my markup to something more standard to see if this will produce the desired result, but still want to debug the problem.

**Comment by snarfed** [comment]
huh. [looking at the example bridgy publish log you posted in IRC](https://brid.gy/log?start_time=1543256536&key=aglzfmJyaWQtZ3lySwsSDVB1Ymxpc2hlZFBhZ2UiJGh0dHBzOi8vdGlueS5uOW4udXMvMjAxOC8xMS8yNi81MzQwLwwLEgdQdWJsaXNoGICAgICAgIAKDA), bridgy did indeed find the lat/long in your post and send it to twitter:

```
D Converted to ActivityStreams object: {
"url": "https://tiny.n9n.us/?p=5340",
"location": {
  "latitude": 40.777164,
  "position": "+40.777164-073.527569/",
  "longitude": -73.527569,
  "objectType": "place"
  },
...
I urlopen POST https://api.twitter.com/1.1/statuses/update.json?lat=40.777164&long=-73.527569&status=Parked+and+testing+Bridgy+location+posse {}
```

**Comment by snarfed** [comment]
aha, [sknebel found it (in IRC).](https://chat.indieweb.org/dev/2018-11-26#t1543260988748700) @dshanske's twitter account doesn't currently have geolocation enabled. @dshanske if you turn that on, it should work.

[twitter also gives lots of caveats for the location part of their API.](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update#post-statuses-update) another notable one is that their reverse geocoding of lat/long is best effort; they don't always find a place to attach.

i'll update the bridgy docs for both of these issues.

**Comment by dshanske** [comment]
Thank you for updating the docs. It notes that the native apps will still let you post location and this only applies to the web and third party clients
