### ISSUE TITLE
No way to save publication preference for Twitter

### ISSUE THREAD

**Issue by jaranta** [snarfed/bridgy#853]
![kuvakaappaus - 2018-12-03 12-45-01](https://user-images.githubusercontent.com/5079912/49369160-6feea300-f6f9-11e8-813d-d4f6603739cb.png)

There is a way to change the preference on whether to include a link when sending posts to Twitter, but there seems to be no way to actually save that preference. "Include link" is selected whenever I open the page, regardless of what I selected previously.

How do I choose "no" and have that preference saved?

**Comment by jaranta** [comment]
I'm not actually using it regularly, but ended up playing with it while trying to figure out how syndication works. Somehow I thought that the dialog I posted above would affect how my posts syndicate by default, but I guess it's somehow controlled by the Known plugin I'm using -- which also doesn't have any options affecting that. Sorry about the confusion.

**Comment by snarfed** [comment]
aha, got it. makes sense! feel free to point the Known plugin's maintainer(s) to [these docs on how to support those options](https://brid.gy/about#omit-link).

**Comment by jaranta** [comment]
Thanks for the help!
