### ISSUE TITLE
Bridgy Fails to Send Webmentions for Stormlighttech.org

### ISSUE THREAD

**Issue by Cambridgeport90** [snarfed/bridgy#856]
Not entirely sure what is going on here, but ever since maybe around the 1st of this month, Twitter backfeed seems to have stopped working for this site, not entirely sure why. Every response I get from Twitter either says "failed:" or "no webmention targets". I've not done anything to change any of the settings, nor can I find an option to specify the URL of the webmention endpoint. I have both the Bridgy plugin as well as the webmention plugin installed into the site. Likes and posts via other forms of webmention seem to be working just fine, it's just Twitter. My site is running the latest version of Wordpress, and the link to the web site does indeed exist underneath the @Stormlighttech Twitter account. If you need more info, just let me know. Thanks in advance though for looking into this.

**Comment by Cambridgeport90** [comment]
Thank you for spotting that. I saw the disable rest API plugin in there, though I didn’t make any changes to it. I’ll go investigate some settings.

**Comment by Cambridgeport90** [comment]
So … after you mentioned it, I went into the REST API settings and checked the webmention check box, which in turn, caused all seventy or so other endpoints to also be checked. Ran another check with Bridgy. It’s still failing to send for some reason. Did I miss anything?

**Comment by snarfed** [comment]
damn, bridgy is still seeing the same "DRA: Only authenticated users can access the REST API." error from your site.

**Comment by Cambridgeport90** [comment]
I’m not surprised. Other plugins are throwing errors all over the place, too. I don’t have access to the actual server, so will have to have someone look into it who does. Is there anything else we need to be checking for? I’ve not changed much of anything when originally setting up the site, so not sure what might have gotten changed on the backend.

**Comment by snarfed** [comment]
@Cambridgeport90 sorry i don't know more about why your wordpress config is unhappy. hope it gets fixed soon!

tentatively closing this issue. feel free to reopen if you need to.
