### ISSUE TITLE
Bridgy publish should support POSSEing tag reply to Flickr

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#857]
Similar to https://github.com/snarfed/bridgy/issues/786 (but broader for any tag reply, and for Flickr instead of Facebook):

This is a feature request for POSSEing tag reply posts to Flickr.

I.e. if I post a [tag reply](https://indieweb.org/tag-reply) on my own site, like documented here:

[https://indieweb.org/tag-reply#How_to_simple_tag-reply](https://indieweb.org/tag-reply#How_to_simple_tag-reply)

where one (or more) of the reply-to URLs is to a Flickr permalink post (likely others's photos, but could be my own that I'm adding tags to after I published it), Bridgy Publish (of my tag reply) should propagate that tag reply to that Flickr permalink.

This is the publish equivalent of the following backfeed features, and may be easier to start with (consider implementing publish before implementing backfeed for equivalent interaction)

  * [776](https://github.com/snarfed/bridgy/issues/776)
  * [488](https://github.com/snarfed/bridgy/issues/488)

Labels: publish

(Originally published at: http://tantek.com/2019/007/b1/bridgy-support-tag-reply-flickr)

**Comment by snarfed** [comment]
done! @tantek let me know if you have any q's.
