### ISSUE TITLE
Backfeed comments/upvotes from HackerNews

### ISSUE THREAD

**Issue by mxstbr** [snarfed/bridgy#860]
It would be nice to backfeed comments (webmentions) and upvotes (likes) from HackerNews to my website.

More information: https://indieweb.org/Hacker_News

**Comment by snarfed** [comment]
sure! we're tracking this in #693. feel free to subscribe there.

**Comment by mxstbr** [comment]
I am so sorry for the duplicate, thanks! :pray:
