### ISSUE TITLE
Unable to add .dev domain

### ISSUE THREAD

**Issue by maxboeck** [snarfed/bridgy#862]
I seem to be unable to add my website URL (https://mxb.dev) to bridgy for twitter polling. After accepting the app on twitter, I can't enter the correct URL, the screen always says that "mxb.dev doesn't look like your website".

It is correctly set on my twitter profile at https://twitter.com/mxbck though. Could this be because of the new .dev TLD?

![screen shot 2019-03-02 at 8 26 58 pm](https://user-images.githubusercontent.com/3185993/53686638-0f87f580-3d2a-11e9-851c-cc49c7d12f12.png)

Thank you!

**Comment by snarfed** [comment]
hah, sorry for the trouble! good guess, .dev domains are indeed blacklisted, back from when Google originally bought the TLD and said they would keep it internal only. now that they're reversed that stance, I'll remove the blacklist entry.

**Comment by snarfed** [comment]
done! feel free to try again.

**Comment by maxboeck** [comment]
yup, works now! that must have been one of the fastest responses I've ever got ;)
thank you for your help!
