### ISSUE TITLE
how to install and use this w/ my blog/cms

### ISSUE THREAD

**Issue by cekvenich** [snarfed/bridgy#865]
I read, and I'm not the dumbest guy: but how do I install and use this?

**Comment by snarfed** [comment]
hi! apologies if it's confusing. you don't install it; it's a service you use. click on one or more of the social network buttons on https://brid.gy to connect your account(s).

your blog also needs to support webmentions. details: https://brid.gy/about#accept

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
