### ISSUE TITLE
Bridgy Has Stopped Working for Me

### ISSUE THREAD

**Issue by Changelingmx** [snarfed/bridgy#866]
I've been using Bridgy for a few months now, and it's just stopped working for me. When I crawl and pole the website, it shows my posts along with the links for that post, but I keep getting an error response. There's no code with the error, so I can't provide it.

**Comment by snarfed** [comment]
hi randy! sorry for the trouble. i assume you're https://brid.gy/twitter/ChangelingMx ? looks like webmentions on your site are unhappy. http POSTs to your webmention endpoint are returning HTTP 500 errors. [example log here.](https://brid.gy/log?start_time=1557177178&key=aglzfmJyaWQtZ3lyTQsSCFJlc3BvbnNlIj90YWc6dHdpdHRlci5jb20sMjAxMzoxMTI1NTAyODE2NDI3MDk4MTEzX2Zhdm9yaXRlZF9ieV82MDYzNzg2MjUM)

the HTML on the 500 page includes the message _**ERROR**: Please enter captcha value._ did you install a new anti-spam plugin recently? if so, it's interacting badly with your webmention plugin(s). cc @dshanske.

**Comment by dshanske** [comment]
@Changelingmx Happy to try to look at the interaction if you want

**Comment by Changelingmx** [comment]
The last thing I installed was WordFence, but that's not a spam
plugin, I think. The problems started before that installation,
though, since the last web mention was 30 days ago, and the last
syndication link was found three months ago. I know that it stopped
finding syndication links because I was using micro.blog for
cross-posting. I've since gone back to Bridgy for that, though.

On Mon, May 6, 2019 at 20:40 David Shanske <notifications@github.com> wrote:
@Changelingmx Happy to try to look at the interaction if you want

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub, or mute the thread.



































































































































-- 
Randy Reed
E-mail: randy@starshipchangeling.net
Webiste: https://www.starshipchangeling.net

**Comment by Changelingmx** [comment]
I fixed it. I just needed to adjust the settings for my capcha plugin.
