### ISSUE TITLE
Bridgy isn't recognizing my Website

### ISSUE THREAD

**Issue by Changelingmx** [snarfed/bridgy#867]
Bridgy isn't recognizing my website. When I log in, it prompts me to add a website. When I type in https://www.starshipchangeling.net, it says it doesn't look like that's my site. The site is in both my Instagram and Twitter profile, and the site has rel-me links.

**Comment by snarfed** [comment]
hi @Changelingmx, sorry for the trouble! https://brid.gy/instagram/changelingmx looks ok, so i assume this is for twitter, https://brid.gy/twitter/ChangelingMx .

when you logged into bridgy with twitter earlier today, your web site was evidently configured a bit differently. specifically, when bridgy did an HTTP HEAD request to `https://www.starshipchangeling.net/`, your site returned a redirect to `https://www.starshipchangeling.net/.well-known/host-meta*%20=%20https://fed.brid.gy/.well-known/host-meta*`. now it doesn't do that any more, but bridgy cached that redirect, even after your site stopped redirecting.

i've cleared that cache value. try logging in with twitter again, it should work now!

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
