### ISSUE TITLE
Manually reconstructed Bridgy URLs redirect to silos

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy#871]
It's mentioned in the [documentation that one can reconstruct URLs](https://brid.gy/about#source-urls) to allow manually resending webmentions for missed backfeed. However, it appears this may no longer work(?) as these reconstructed URLs, which used to be static are now automatically redirecting to their siloed instances.

Example: https://brid.gy/post/twitter/schnarfed/476408043819659264redirects to https://twitter.com/schnarfed/status/476408043819659264

Separately, though related, the example in the documentation for Instagram no longer seems to exist and could be replaced and the example for Google+ could be removed as the service no longer exists.

(Originally posted at https://boffosocko.com/2019/05/29/manually-reconstructed-bridgy-urls-redirect-to-silos/)

**Comment by snarfed** [comment]
bridgy's mf2 URLs redirect with HTML meta refresh. webmentions with them as sources should still work fine! (afaik webmention receivers don't/shouldn't follow meta refresh redirects, right?)

**Comment by snarfed** [comment]
i've updated the example URLs in the docs. thanks! tentatively closing. feel free to reopen.
