### ISSUE TITLE
Bridgy publish to GitHub should turn profile URL links into mentions

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#872]
When using Bridgy publish to GitHub, GitHub is smart enough to recognize issue links and repo links and provide short versions of them inline. However it fails to do so for profile URLs for some reason, just shows the full profile URL link instead of a mention, and does not notify the user mentioned.

It would be great if Bridgy Publish to GitHub (issues, comments) could recognize GitHub profile URL links of the form github.com followed by username, e.g. [https://github.com/snarfed](https://github.com/snarfed) and turn them into the profile mention equivalent, e.g. [@snarfed](https://github.com/snarfed) which I think also has the advantage that it will notify that GitHub user of that mention.

Recent real world Bridgy Publish example what would have benefited from this: [https://github.com/chrisdavidmills/mdn-and-frameworks/issues/1#issuecomment-497395828](https://github.com/chrisdavidmills/mdn-and-frameworks/issues/1#issuecomment-497395828)

Labels: publish

(Originally published at: https://tantek.com/2019/150/b1/bridgy-support-github-mentions)

**Comment by jamietanna** [comment]
I spotted this and may look at providing a fix.

One thing I'm wondering is about how we know it's a profile URL <code>/snarfed</code> not <code>/notifications</code>, so we'd probably want to do a lookup for everything that matches a regex that looks like it could be a profile URL (<code>/snarfed</code> and <code>/snarfed/</code>)

(Originally published at: https://www.jvt.me/mf2/2020/11/sqxc7/)

**Comment by snarfed** [comment]
Awesome!

And good catch on `/notifications`, but I actually think that's low priority. I'm totally fine with shipping an MVP that converts `https://github.com/notifications` to `@notifications`.

A couple more advanced possibilities here:
* detect profiles in links, eg `<a href="https://github.com/snarfed">this guy</a>`, and append ` (@snarfed)` to them
* do rel-me lookup on all URLs, or maybe just homepage URLs that aren't in bridgy's blocklist, look for GitHub rel-me links, and replace those too. obviously more work, and we'd cap it at the first 10 or so, but this would be especially cool.

**Comment by snarfed** [comment]
Done! in snarfed/granary@47efa337271ad829874de8cd7e874019cb2a9f04
