### ISSUE TITLE
400 Error to hosted WordPress 

### ISSUE THREAD

**Issue by BatchHeader** [snarfed/bridgy#877]
I am receiving 400 error on all mentions to our site and for the life of me can't see what is blocking it.
Setup: Self-hosted WordPress with IndieWeb and Webmention plugins installed. Brid.gy user: https://brid.gy/twitter/wpcoventry

Any help appreciated.

Example response:

> 0.1.0.2 - - [24/Jun/2019:14:06:50 -0700] "POST /_ah/queue/propagate HTTP/1.1" 200 84 "https://brid.gy/retry" "AppEngine-Google; (+http://code.google.com/appengine)"
> 
> 2019-06-24 21:06:48.544765 D Params: NestedMultiDict([('response_key', u'aglzfmJy...')])
> 2019-06-24 21:06:48.880929 I Source: wpcoventry (Twitter) wpcoventry, https://brid.gy/twitter/wpcoventry
> 2019-06-24 21:06:48.881170 I Created by this poll: https://brid.gy/log?start_time=1561405789&key=aglzfmJyaWQtZ3lyFwsSB1R3aXR0ZXIiCndwY292ZW50cnkM
> 2019-06-24 21:06:48.887216 I Starting Response repost tag:twitter.com,2013:1130602248432693248 https://twitter.com/nbatch_/status/1130602248432693248
> 2019-06-24 21:06:48.906887 I Webmention from https://brid-gy.appspot.com/repost/twitter/wpcoventry/1130602001379876867/1130602248432693248 to https://www.wpcoventry.co.uk/2019/05/wordcamp-bristol-2019/
> 2019-06-24 21:06:48.917979 I Sending...
> 2019-06-24 21:06:50.327659 I Giving up this target. {'body': u'\x13Y\x00\x00\x04"o\ufffd\ufffd.\x7f\x10\ufffd/Ihfc\ufffd\ufffdy\ufffdq\u0281C\x16\ufffdY[\x1a\ufffd\x01\ufffd\ufffd!\x0b\ufffdv\ufffd\ufffd\ufffd\ufffd\x17c\ufffd\ufffd=\ufffdV\x14S0\x12\ufffd\ufffd\ufffd$\x17\ufffd\u013d\ufffd\ufffdl\ufffd7\u030f=\ufffd\ufffds\x1d\ufffd!\ufffd\x0f', 'code': '...', 'request': u'POST https://www.wpcoventry.co.uk/wp-json/webmention/1.0/endpoint (with source=https://brid-gy.appspot.com/repost/twitter/wpcoventry/1130602001379876867/1130602248432693248, target=https://www.wpcoventry.co.uk/2019/05/wordcamp-bristol-2019/)', 'http_status': 400}

**Comment by snarfed** [comment]
hi @BatchHeader, sorry for the trouble! looks like that post has pingbacks (or comments) disabled, which includes webmentions:

```sh
$ curl https://www.wpcoventry.co.uk/wp-json/webmention/1.0/endpoint -d source=https://brid-gy.appspot.com/repost/twitter/wpcoventry/1130602001379876867/1130602248432693248 -d target=https://www.wpcoventry.co.uk/2019/05/wordcamp-bristol-2019/
{"code":"pings_closed","message":"Pings are disabled for this post","data":{"status":400}}
```

try enabling them, either on that post or site wide in _Settings => Discussion_ ? cc @dshanske for more debugging.

**Comment by BatchHeader** [comment]
@snarfed Thanks for that. Rookie mistake. Enabled them but older posts were still set manually. Have now amended and all working as expected. 👍

**Comment by dshanske** [comment]
I have a proposal to disable the global setting on the theory that installing the plugin means you want webmentions
