### ISSUE TITLE
JavaScript injection vulnerability

### ISSUE THREAD

**Issue by freekmurze** [snarfed/bridgy#880]
When somebody creates a webmention by tweeting some JavaScript code, that JavaScript code is actually being executed.

You can find an example on my account: https://brid.gy/twitter/freekmurze

Look for the interaction with this tweet: https://twitter.com/enunomaduro/status/1150157457664008192

![image](https://user-images.githubusercontent.com/483853/61176881-c6de2400-a5c8-11e9-8892-a3edce0bbe76.png)

**Comment by snarfed** [comment]
yow, thanks for finding and reporting! will fix.

**Comment by snarfed** [comment]
fortunately, bridgy has no login, user sessions, or any other browser-side credentials or state that could be employed with this.... but still, definitely worth fixing regardless.

**Comment by freekmurze** [comment]
Thanks for taking care of this and also thank you for having created this neat service 👍

**Comment by snarfed** [comment]
thanks again @freekmurze!

**Comment by snarfed** [comment]
example: https://brid.gy/twitter/freekmurze?responses_before=2019-07-14T01:08:21.055275#responses

note the escaped `<script>alert("Hey buddy")</script>` text.
