### ISSUE TITLE
usernames should be case insensitive

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#884]
twitter, instagram, and github usernames are case insensitive.  sadly, bridgy compares usernames _case sensitive_, which leads us to the bug where we have two accounts for some users. eg @RosemaryOrchard on twitter, https://brid.gy/twitter/RosemaryOrchard (active) and https://brid.gy/twitter/rosemaryorchard (inactive). ugh.

fix here is probably to update bridgy user accounts to lowercase all usernames, store (and render) the preferred capitalization separately (this may only apply to twitter), and lower case usernames during login before looking to see if the user already exists. whee.

(worse, the existing capitalized usernames are the bridgy user accounts' primary keys. begs the question of #766, handling when usernames change, which is a different problem.)

TODO:
- [x] for new account signups, store username separate from key id, normalize key id to all lower case
- [x] backfill username property in existing entities
- [x] handle existing duplicate entities
- [x] handle existing upper case key id entities

**Comment by snarfed** [comment]
looks like we have six of these right now, [based on this BigQuery query]( https://console.cloud.google.com/bigquery?sq=586366768654:a3f7bab8793e4d839f5f6216befb619e ):

first | second
-- | --
techlifeweb | TechLifeWeb
ManicGrant | MaNiCgrant
oddevan | oddEvan
rosemaryorchard | RosemaryOrchard
EUwatchers | EUWatchers
iamjeffperry | iamJeffPerry

**Comment by snarfed** [comment]
in practice i think this is only a problem for Twitter, since Instagram and GitHub always normalize usernames to lower case themselves.

**Comment by melanierichards** [comment]
I have the duplicate-account problem, happy to help test if you need folks to do so (I'm somelaniesaid => soMelanieSaid on Twitter).

**Comment by snarfed** [comment]
Checked the datastore just now, Instagram usernames are always lower case, but GitHub usernames aren't.

**Comment by snarfed** [comment]
Fixed for new users! Now, backfilling `username` and handling the dupes.

**Comment by snarfed** [comment]
Backfilling `username` in existing entities with:

```
$ env APP_ID=brid-gy GOOGLE_APPLICATION_CREDENTIALS=service_account_creds.json python
...
Type "help", "copyright", "credits" or "license" for more information.
>>> from oauth_dropins.webutil import appengine_info
appengine_info.DEBUG = False
appengine_info.APP_ID = os.environ['GAE_APPLICATION'] = 'brid-gy'

import appengine_config
from oauth_dropins.webutil import appengine_config
from github import *
from mastodon import *
from medium import *
from reddit import *
from twitter import *
from models import *
from google.cloud import ndb
import imp

>>> ndb_context = appengine_config.ndb_client.context()
>>> ndb_context.__enter__()
>>> @ndb.transactional()
def add_username(key):
  e = key.get()
  e.username = e.key.id()
  e.put()
>>> add_username(ndb.Key(Twitter, 'schnarfed'))
>>> for cls in (GitHub, Mastodon, Medium, Reddit, Twitter):
  print(cls.__name__)
  for key in cls.query().iter(keys_only=True):
    add_username(key)
    print('.', end='', flush=True)
```
```

**Comment by snarfed** [comment]
Current list of duplicate accounts, all Twitter except for one Medium:

silo | first | enabled | second | enabled
-- | -- | -- | -- | --
Twitter | ManicGrant | enabled | MaNiCgrant | disabled
Twitter | flobrinkmann | enabled | FloBrinkmann | enabled
Twitter | binyamingreen | enabled | BinyaminGreen | enabled
Twitter | nicmakesstuff | enabled | NicMakesStuff | enabled
Twitter | sprucekhalifa | disabled | SpruceKhalifa | disabled
Twitter | somelaniesaid | disabled | soMelanieSaid | enabled
Twitter | alexmingoia | disabled | AlexMingoia | enabled
Twitter | dreamseer | enabled | Dreamseer | disabled
Twitter | iamjeffperry | enabled | iamJeffPerry | enabled
Twitter | oddevan | enabled | oddEvan | disabled
Twitter | EUwatchers | disabled | EUWatchers | disabled
Twitter | rosemaryorchard | disabled | RosemaryOrchard | enabled
Twitter | techlifeweb | disabled | TechLifeWeb | enabled
Medium | @xab | enabled | @Xab | enabled

**Comment by snarfed** [comment]
Only five had both entities enabled:
- disabled https://brid.gy/medium/@Xab, left https://brid.gy/medium/@xab enabled
- disabled https://brid.gy/twitter/iamJeffPerry, left https://brid.gy/twitter/iamjeffperry enabled
- disabled https://brid.gy/twitter/NicMakesStuff, left https://brid.gy/twitter/nicmakesstuff enabled
- disabled https://brid.gy/twitter/FloBrinkmann, left https://brid.gy/twitter/flobrinkmann enabled
- disabled https://brid.gy/twitter/BinyaminGreen, left https://brid.gy/twitter/binyamingreen enabled

**Comment by snarfed** [comment]
Done! Left existing accounts with upper case usernames alone, but if/when they re-auth, they'll switch to lower case usernames.

**Comment by snarfed** [comment]
Oops, this is breaking OPD, we're comparing usernames across case, eg this from poll

```
Demoting original post links because user tag:twitter.com,2013:fastlaners1 doesn't match author id tag:twitter.com,2013:Fastlaners1 username Fastlaners1
```
