### ISSUE TITLE
Can not publish to Mastodon via webmention

### ISSUE THREAD

**Issue by bekoli** [snarfed/bridgy#893]
Trying to add custom POSSE provider to Syndication-Links (WordPress plugin) for Bridgy Mastodon but `https://brid.gy/publish/mastodon` (according to `https://brid.gy/about`) returns 404 (unlike e.g. `https://brid.gy/publish/twitter` having the `rel="webmention"` link) so the webmention endpoint can never be discovered.

Also on Bridgy `Preview` works but `Discover` fails "to fetch [...] or find a Mastodon syndication link" but the link is there (thanks to custom POSSE provider config): http://php.microformats.io/?url=https%3A%2F%2Fbeko.famkos.net%2F2019%2F10%2F23%2Fmastodon-posse%2F

```
                "syndication": [
                    "https://brid.gy/publish/mastodon",
                    "https://twitter.com/BekoPharm/status/1187014365163278337"
                ],
```

What am I missing?

**Comment by snarfed** [comment]
hey, thanks for poking at this! and good find, https://brid.gy/publish/mastodon should indeed work, but doesn't. i'll fix that now.

as for Discover, you actually need a syndication link to your POSSED post Mastodon, eg something under https://social.tchncs.de/@bekopharm.

**Comment by bekoli** [comment]
I see, usually don't use Discover at all. I was just poking at every option I found. You may see this in your `access.log` xD
