### ISSUE TITLE
"This action is outside the authorized scopes" error when syndicating to Mastodon

### ISSUE THREAD

**Issue by ngm** [snarfed/bridgy#894]
Trying the awesome new brid.gy <> Mastodon bridge! 

I got this error when POSSEing:

> 2019-10-23 19:20:00.276960 W Error 403, response body: u'{"error":"This action is outside the authorized scopes"}'
> 2019-10-23 19:20:00.277265 I Error: {"error":"This action is outside the authorized scopes"} 403 Client Error: None for url: https://social.coop/api/v1/statuses

The logs are here:

https://brid.gy/log?start_time=1571858400&key=aglzfmJyaWQtZ3lyTgsSDVB1Ymxpc2hlZFBhZ2UiJ2h0dHBzOi8vZG91YmxlbG9vcC5uZXQvMjAxOS8xMC8yMy82MzEyLwwLEgdQdWJsaXNoGICAwOHttpALDA

Everything seemed to go OK when authorizing brid.gy with the social.coop instance. 

social.coop is on v2.6.4 of Mastodon.

**Comment by ngm** [comment]
I disabled publish and re-enabled - works now :)

Not sure what happened the first time.

**Comment by bekoli** [comment]
It was fixed in that time :)

**Comment by snarfed** [comment]
thanks all! tentatively closing. feel free to reopen!
