### ISSUE TITLE
Reply-To other target when POSSE to Twitter fails

### ISSUE THREAD

**Issue by Ryuno-Ki** [snarfed/bridgy#896]
When I try to add [POSSE to a blog post after the fact](https://jaenis.ch/blog/2019/about-mentors/) and send a webmention to https://brid.gy/publish/twitter it fails with

```json
{                    
  "parsed":{                     
    "type":[
      "h-entry" 
    ],   
    "properties":{
      "content":[   
        {   
          "html":"<p>I'm subscribed to a handful of newsletters. Normally, they're quite marketing-heavy, but help me staying ahead of trends.</p><p>But a few of some ar
e quite \u2026 personal. Those I consider nuggets. One of them is written by <a href=\"https://sivers.org/\">Derek Sivers</a>.</p><p>A couple of weeks, he wrote down how
 to ask your mentors for help. Then he asked his newsletter subscribers for thoughts, so here we go!</p><p>Look, I'm preferring written communication whenever possible. 
Often you hear, that this is bad, because you're lacking additional input sources like mimics, tone of voice bla bla bla.</p><p>But I grew up on the web. I know <em>it i
s possible</em> to communicate effectively online. But you need to prepare more. Reflect more. Think more about a response was meant. It helps if you \u201eassume positi
ve intent\u201c.</p><p>Written communication has some major upsides:</p><ul><li>It is written. That is, recorded. You can go back and see. You can easily search and anal
yse it.</li><li>It is asynchronous. That is, you have more leeway to think about and improve over your words to make sure it carries the message in the way intended. Plu
s, you can deal with it when it fits your schedule best! Not to forget you have time to research so to make a better argument.</li><li>We have more tools available. Sure
, rhetorics is trained since thousands of years. But parsing voice and faces etc. with computers is only possible recently. On the other hand, we have quite some experie
nce with estimating understandability, tone etc.</li></ul><p>Who says, you can't apply lessons learned from rhetorics to written talk? Here also it is important to tell 
a story. That means, stating the audience, providing context (who is acting, what is the problem, what do you want to achieve, what did you try? What are the options?)</
p><p>Turns our this is exactly what Derek is doing, too. Plus, he experienced something, <a href=\"https://www.atlassian.com/team-playbook/about#-9\">Atlassian describes
 as Rubber Chicken</a>. I'm quite sure, you have experienced something similiar yourself, too: You're about to ask a friend or colleague for some help. Therefore, you th
ink about what to ask for. How to phrase it. By doing that it suddenly clicks and you found the answer to your question yourself!</p><p>Thinking about it, I will likely 
put up a <a href=\"/hobbies/coding/cheatsheets/\">cheatsheet</a> about what to keep in mind on writing. I have some links in my backlog for further reading, too ;-) Also
 it could cover some strategic approach about thinking logically.</p><p>Share your thoughts! This blog accepts WebMentions ;-)</p>",
          "value":"I'm subscribed to a handful of newsletters. Normally, they're quite marketing-heavy, but help me staying ahead of trends.\nBut a few of some are quite \u2026 personal. Those I consider nuggets. One of them is written by Derek Sivers.\nA couple of weeks, he wrote down how to ask your mentors for help. Then he asked his newsletter subscribers for thoughts, so here we go!\nLook, I'm preferring written communication whenever possible. Often you hear, that this is bad, because you're lacking additional input sources like mimics, tone of voice bla bla bla.\nBut I grew up on the web. I know it is possible to communicate effectively online. But you need to prepare more. Reflect more. Think more about a response was meant. It helps if you \u201eassume positive intent\u201c.\nWritten communication has some major upsides:It is written. That is, recorded. You can go back and see. You can easily search and analyse it.It is asynchronous. That is, you have more leeway to think about and improve over your words to make sure it carries the message in the way intended. Plus, you can deal with it when it fits your schedule best! Not to forget you have time to research so to make a better argument.We have more tools available. Sure, rhetorics is trained since thousands of years. But parsing voice and faces etc. with computers is only possible recently. On the other hand, we have quite some experience with estimating understandability, tone etc.\nWho says, you can't apply lessons learned from rhetorics to written talk? Here also it is important to tell a story. That means, stating the audience, providing context (who is acting, what is the problem, what do you want to achieve, what did you try? What are the options?)\nTurns our this is exactly what Derek is doing, too. Plus, he experienced something, Atlassian describes as Rubber Chicken. I'm quite sure, you have experienced something similiar yourself, too: You're about to ask a friend or colleague for some help. Therefore, you think about what to ask for. How to phrase it. By doing that it suddenly clicks and you found the answer to your question yourself!\nThinking about it, I will likely put up a cheatsheet about what to keep in mind on writing. I have some links in my backlog for further reading, too ;-) Also it could cover some strategic approach about thinking logically.\nShare your thoughts! This blog accepts WebMentions ;-)"
        }
      ],
      "published":[
        "2019-11-07T16:00:00Z"
      ],
      "name":[
        "About mentors"
      ],
      "in-reply-to":[
        "https://sivers.org/ment"
      ],
      "author":[
        {
          "type":[
            "h-card"
          ],
          "properties":{
            "name":[
              "Andr\u00e9 Jaenisch"
            ]
          },
          "value":"Andr\u00e9 Jaenisch"
        }
      ]
    }
  },
  "error":"Could not find a tweet to reply to."
}
```

(Unicode is not supported? I guess, my name is this way because Python 2…)
Anyway, it could be related to #221.

I was about to use bridgy to POSSE my blog post to Twitter.
I want also be able to WebMention another blog post (I discovered later on, that Derek has not implemented the API on his website).

I assume, the error message tries to explain me, that it [expected to be a reply to a tweet](https://brid.gy/about#reply).

**Comment by snarfed** [comment]
hi! yes, that's right. bridgy currently only allows POSSEing a reply if it replies to a post on the same silo. this is intentional; discussion in #362. from that issue:

> people also often try to use bridgy publish to POSSE a reply to a tweet but get the in-reply-to link wrong, or accidentally use brid.gy/publish/twitter when they meant to use brid.gy/publish/facebook, etc. this check helps them. i'm not sure yet how to reconcile the two use cases.  
> ...  
> sadly, there are dozens of bridgy publish attempts every day that are wrong in various ways, and mismatched in-reply-to and bridgy link is one of the most common. (i can tell because invariably the person fixes it and makes another attempt with the right in-reply-to or bridgy link minutes later.)

if we wanted to POSSE this kind of reply to twitter and show the [reply context](https://indieweb.org/reply-context) in a reasonable way, we'd need to start inventing our own microsyntax, which would be complicated, and might even end up being silo-specific. discussion in #527.

my overall approach has been to ["Keep Bridgy Publish dumb"](https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb) and avoid all this entirely. i'm open to more ideas though!

**Comment by snarfed** [comment]
oh, also,

> (Unicode is not supported? I guess, my name is this way because Python 2…)

no, that's JSON, they're just escaped. still valid. 😎 https://en.wikipedia.org/wiki/JSON#Data_portability_issues

**Comment by Ryuno-Ki** [comment]
If I got the article to reply-context right it would mean for me to use `.h-cite`. That would be part of that micro-syntax. How would the markup need to look like?

```html
<div class="u-in-reply-to h-cite">
  <a class="u-url" href="https://twitter.com/AndreJaenisch/status/123456789">Former tweet</a>
</div>
<div class="u-in-reply-to">
  <a class="u-url" href="https://example.com/">The article I replied to</a>
</div>
```
We should at least not demand the silos to be part of the markup. You would need to parse it from the URL.

The only reference (except tests) I found in your code is https://github.com/snarfed/bridgy/blob/69662a75f36eead25037c7c1c2ed69797b203948/templates/about.html#L927-L943

> no, that's JSON, they're just escaped. still valid. :sunglasses: https://en.wikipedia.org/wiki/JSON#Data_portability_issues

I got so used to blame Python2 for it. But yeah, `é` falls outside of the „safe range”.

**Comment by snarfed** [comment]
ah! if you also include a `u-in-reply-to` like this that points to a tweet, then yes, bridgy publish should work ok.

having said that, `u-in-reply-to` needs to go on the `<a>` tag. [details here.](http://microformats.org/wiki/microformats2-parsing#parsing_a_u-_property) [parsing your HTML example ends up with a composite object for the `in-reply-to` property](https://pin13.net/mf2/?id=20191108232359810), which afaik nothing will support, including bridgy.

**Comment by Ryuno-Ki** [comment]
I need to think about it.
What I want to have is to be able to „comment” on a blog post of someone else using WebMention + POSSE my blog post to Twitter.

So either I'm sit down and try to come up with something on my own (would share it with you then, of course) or just down apply the approach at all.

Can we keep this issue open for so long? Say, if I haven't come back to you by the end of this year, you can close it.

**Comment by snarfed** [comment]
understood! other people have definitely asked for this too.

do you know what you would want the reply on twitter to look like? have you read the discussion in https://github.com/snarfed/bridgy/issues/362? and https://indieweb.org/Twitter#original_lacks_POSSE_tweet? (cc @tantek) other people have thought about this pretty deeply, and it's trickier than it seems at first.

feel free to join us in https://chat.indieweb.org/chat btw! lots of people there would love to discuss this more.

**Comment by snarfed** [comment]
also, one workaround is to first publish your blog post _without_ the `in-reply-to`, use Bridgy to POSSE it, then add the `in-reply-to` afterward. that works now.

**Comment by Ryuno-Ki** [comment]
Okay, the workaround worked for me:
https://twitter.com/AndreJaenisch/status/1193088778338029569

From what I see, you also have an endpoint at /webmention.
Could I add that one, so that you can tell, that this article of mine is meant to be a reply to someone else's article AND POSSEd to Twitter?

Otherwise, feel free to close it. Will use the workaround for me.

Thanks for the link to the chat (although it should be https://chat.indieweb.org/ ).
I'd prefer IRC and irssi for it :-)

**Comment by snarfed** [comment]
this is a different idea, but are you sure your post https://jaenis.ch/blog/2019/about-mentors/ is actually a reply to https://sivers.org/ment , and not just a mention of it? `in-reply-to` is usually only meant for direct replies, what we'd usually call "comments." your post seems more like a full length, standalone post that references his post, but is more than just a reply.

> From what I see, you also have an endpoint at /webmention.
> Could I add that one, so that you can tell, that this article of mine is meant to be a reply to someone else's article AND POSSEd to Twitter?

interesting idea! i'm still not sure we should support this at all, but if we do, that would definitely be one way to know it's intentional. we'd still need a way to allow it in the interactive web UI though.

> Thanks for the link to the chat (although it should be https://chat.indieweb.org/ ).
> I'd prefer IRC and irssi for it :-)

heh, sorry, yes. i meant https://indieweb.org/discuss .

**Comment by Ryuno-Ki** [comment]
> this is a different idea, but are you sure your post https://jaenis.ch/blog/2019/about-mentors/ is actually a reply to https://sivers.org/ment , and not just a mention of it? `in-reply-to` is usually only meant for direct replies, what we'd usually call "comments." your post seems more like a full length, standalone post that references his post, but is more than just a reply.

I thought about this for a while now.

My „problem” is, I tend to write „long replies” (if space and time allows it). So, yeah, that's basically what I would have replied as e-mail. I add additional thoughts, which could make it qualify as a comment.

A fuzzy border, I guess :-)

**Comment by snarfed** [comment]
sure! that's all totally ok. one of my favorite things about the indieweb is that we each get to do whatever we want on our own web sites.

having said that, the open questions in https://github.com/snarfed/bridgy/issues/896#issuecomment-552032215 still apply.

you're definitely welcome to POSSE this kind of reply to Twitter manually, or with another tool! Bridgy itself can't right now, though, and based on https://snarfed.org/2015-11-29_keep-bridgy-publish-dumb and similar ideas, i don't really plan to take it in that direction.

**Comment by snarfed** [comment]
tentatively closing. thanks for the discussion! feel free to reopen if anything new comes up.

**Comment by Ryuno-Ki** [comment]
FYI: Just [tried out](https://jaenis.ch/blog/2019/web-dev-calendar-in-2019/) to use a [comment](https://indieweb.org/comments), but I need to adjust my markup somehow, I guess … At least Indiewebify.me does not recognise it.

But I don't want to hijack this post. Thanks for the lessons :-)

**Comment by snarfed** [comment]
ah, yes, comment markup is for _other_ people's replies on _your_ post. i expect you wanted `u-in-reply-to` instead here.

**Comment by Ryuno-Ki** [comment]
Now it's getting confusing.
Let me reread the wiki page.
I'd assume you mean the Webmentions I need below my sites to be marked up as comments now.

But that's something the recipient (= target/receiver of Webmention) has control over.

**Comment by snarfed** [comment]
right! specifically `u-comment`. but that's unrelated to writing (and POSSEing) your own reply to someone else's post.
