### ISSUE TITLE
POSSE links vs discussion links?

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy#897]
I use brid.gy to get notifications of my posts sent to mastodon/twitter/etc. Typical usage.

But sometimes bits of weird happen when brid.gy can't tell if a link was POSE/POSSE'd or if it was just mentioned. For example, I mentioned one of my blog posts at https://queer.party/@fluffy/103115386313137503 which caused all the following posts on that thread to appear as mentions to https://beesbuzz.biz/blog/1286-The-commoditization-of-free-time -- which wasn't intended at all.

I would think that if a link was posted in reply to another tweet/toot/etc., that it shouldn't count as a  POSE/POSSE and replies to that tweet/toot/etc. shouldn't be converted into webmentions to the link.

**Comment by fluffy-critter** [comment]
On the other hand I can see a use case for it behaving this way - say someone uses an IndieWeb site post as a means of replying to a Mastodon post, with specific `u-in-reply-to` POSSE logic.

So categorically choosing one behavior over the other isn't the answer.

**Comment by snarfed** [comment]
yes! this sounds like #154 and #51 (read past the initial description).

i've deliberately chosen to make bridgy "promiscuous," ie very liberal in how it interprets links to your site as POSSEd posts. when bridgy is occasionally too inclusive, users can always moderate its webmentions and remove any they don't want - with manual work, granted - but if bridgy is too narrow, it's impossible (or at least much harder) for users to manually generate and send webmentions that bridgy omitted. so, i make it err on the promiscuous side.

#241 is one possible solution. i'm not a fan of adding user visible settings, but i'd consider accepting a PR that adds it.

**Comment by snarfed** [comment]
tentatively closing this in favor of #241. (and maybe continuing to encourage moderation tools in receivers.) feel free to reopen!
