### ISSUE TITLE
Bridgy stuck with polling?

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#899]
When I go to my Bridgy Twitter page (https://brid.gy/twitter/islayblog) it seems to be stuck at "Polling now. Check back in a minute!". It's been like that for over an hour and also says "Last webmention sent 7 hours ago" when I know there have been well over a dozen mentions Bridgy should have picked up since.

Any idea what's happening?

**Comment by snarfed** [comment]
hey, sorry for the trouble! i'm rolling out a big change to bridgy's underlying infrastructure, and it's hitting some problems. hopefully they'll get ironed out soon. i'll keep this open until it's fixed.

**Comment by armingrewe** [comment]
Ah, sorry to hear that. Hope everything gets sorted and you don't have any further troubles. No worries, I'll just wait for all the mentions to roll in once it's all done.

**Comment by armingrewe** [comment]
Seems it's all done, at least I had a whole raft of mentions coming in a short while ago. Feel free to close if everything is fine from your side.

**Comment by snarfed** [comment]
true! glad to hear it.
