### ISSUE TITLE
Outdated Twitter Logo

### ISSUE THREAD

**Issue by edent** [snarfed/bridgy#900]
https://brid.gy/oauth_dropins/static/twitter_2x.png

The Twitter logo / bird has changed. Additionally, they don't use their old font.

Updated versions at https://about.twitter.com/en_us/company/brand-resources.html

Official buttons at the bottom of https://developer.twitter.com/en/docs/basics/authentication/guides/log-in-with-twitter

**Comment by snarfed** [comment]
hah, good eye, thanks for the nudge! i actually updated it a while back, but it regressed recently during a refactoring. i've put it back.

on an unrelated note, i loved [poking around your site](https://indiemap.org/docs.html#notable) when i discovered it for [indiemap.org](https://indiemap.org/). nice work!

**Comment by edent** [comment]
Cheers mate! Loving how easy it was to set up Bridgy.
