### ISSUE TITLE
Centred tables look a bit odd

### ISSUE THREAD

**Issue by edent** [snarfed/bridgy#901]
Currently, the table of responses looks a bit strange and hard to read.
![Screenshot_2019-12-23 edent (Twitter) - Bridgy](https://user-images.githubusercontent.com/837136/71382129-72ef5680-25ce-11ea-9a8b-7e6243d1b991.png)

I think it would look better like this
![Screenshot_2019-12-23 edent (Twitter) - Bridgy(1)](https://user-images.githubusercontent.com/837136/71382128-72ef5680-25ce-11ea-99dd-1669bf2c0d68.png)

Requires the removal of https://github.com/snarfed/bridgy/blob/master/static/style.css#L90

Doesn't seem to break anything else. What do you think?

**Comment by snarfed** [comment]
hey, sure! thanks for the idea. left aligning those columns sounds good to me, but we'd need a more targeted change. removing that line 90 applies to lots of the rest of the UI too, eg the front page:

![image](https://user-images.githubusercontent.com/778068/71383336-b4611100-2590-11ea-8f13-5e443b3ae479.png)

feel free to send a PR for something narrower though!
