### ISSUE TITLE
[Silo Request] Goodreads.com

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#905]
I noticed that today @edent has made some great progress on syndicating Schema.org data to Goodreads

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Finally got the code working! You can now syndicate book reviews from your blog to Goodreads.<br><br>Code: <a href="https://gitlab.com/edent/schema-to-goodreads/tree/master">https://gitlab.com/edent/schema-to-goodreads/tree/master</a> <br>Write up: <a href="https://shkspr.mobi/blog/2019/12/add-review-to-goodreads-from-schema-markup/">https://shkspr.mobi/blog/2019/12/add-review-to-goodreads-from-schema-markup/</a><br><br>Goodreads API is trash and their ISBN lookup is flaky. But it all (mostly) works!</p>&mdash; Terence Eden (@edent) <a href="https://twitter.com/edent/status/1210247446749687810?ref_src=twsrc%5Etfw">December 26, 2019</a></blockquote>

And it seems like it may be something cool to have handled by Brid.gy so folks don't have to manage it themselves.

**Comment by snarfed** [comment]
awesome! and ooh, it's in python, even better. agreed, i'd love to see someone tackle this! @edent's work is a great first step. here are [instructions for adding a new silo to bridgy.](https://bridgy.readthedocs.io/#adding-a-new-silo)

**Comment by snarfed** [comment]
[API TOS looks fine.](https://www.goodreads.com/api/keys#terms) looks like all calls support XML, and some also support JSON, either by URL path extension (`.xml` vs `.json`) and/or the `format` query param.

specific relevant calls:
* [get comments](https://www.goodreads.com/api/index#comment.list)
* [post a read status](https://www.goodreads.com/api/index#user_status.create)
* [post a review](https://www.goodreads.com/api/index#review.create)
* [like something](https://www.goodreads.com/api/index#rating.create)

haven't yet found a way to get individual likes aka ratings on a specific review or read status. here are examples in the UI though: [review](https://www.goodreads.com/rating/voters/534066213?resource_type=Review), [read status](https://www.goodreads.com/rating/voters/3356894464?resource_type=ReadStatus).

**Comment by snarfed** [comment]
Bad news, from an email I got just now:
> As of December 8th 2020, Goodreads will no longer issue new developer keys for our public developer API and plans to retire these tools.

https://help.goodreads.com/s/article/Does-Goodreads-support-the-use-of-APIs says basically the same thing.

**Comment by snarfed** [comment]
^ Closing due to this.
