### ISSUE TITLE
Bridgy source should rename blacklist and similar offensive terms

### ISSUE THREAD

**Issue by tantek** [snarfed/bridgy#908]
Bridgy had a file called [domain_blacklist.txt](https://github.com/snarfed/bridgy/blob/master/domain_blacklist.txt) which was renamed to domain_blocklist.txt in [a recent commit](https://github.com/snarfed/bridgy/commit/19312bf8f81784835c6ea323ac04e99150a9c87e). This issue is for searching / tracking any other similar terms as identified by Microsoft in [Chrome Issue 981129](https://bugs.chromium.org/p/chromium/issues/detail?id=981129).

While we don’t have access to Microsoft’s PoliCheck tool mentioned therein, we can at least use the results they came up with in their searches of Chrome source as a first level approximation of terms to search for. E.g.:

  * change "master"/"slave" to "writer"/"reader"

Other terms may require manual inspection for context to evalute whether they are offensive or not. E.g.:

  * cracker
  * ho

Feel free to note other text profanity, geopolitical, or diversity issues in comments on this issue as discovered by PoliCheck analysis or other tools. (Please refrain from general offensive brainstorming though, instead, link to existing work and lists by others. Thanks.)

(Originally published at: https://tantek.com/2020/008/b1/bridgy-source-rename-offensive-terms)

**Comment by snarfed** [comment]
thanks again for the nudge!

i've confirmed that none of the words mentioned here appear in bridgy, granary, oauth-dropins, or webutil. i've also checked for the standard english curse words, and only found a couple instances of _hell_ in test data in granary:

https://github.com/snarfed/granary/blob/2f62e7ff6ccfed5d65c2db09241a77698dfa2277/granary/tests/test_facebook.py#L1157
https://github.com/snarfed/granary/blob/2f62e7ff6ccfed5d65c2db09241a77698dfa2277/granary/tests/testdata/facebook.m.post.html#L226

as mentioned, PoliCheck is private, and similar public tools i've looked at focus more on profanity, as opposed to offensive words. so, i'm tentatively closing, but i'm happy to reopen if anyone wants to suggest a specific tool and usage details. (or even better, feel free to run it and send pull requests!)
