### ISSUE TITLE
Mastodon for Bridgy is not publishing and returns Page is Not Correct Response

### ISSUE THREAD

**Issue by Changelingmx** [snarfed/bridgy#909]
Hello,

I am attempting to set up the feature of Bridgy that allows for posting to my Mastodon account. I was able to successfully authorize and grant all of the necessary permissions, but posts don't publish. When I go through brid.gy and attempt to publish by inserting a URL, I click the send button and get an error from Mastodon saying that the page isn't correct and something went wrong on their end. Is this something I can fix? If so, how? Thank you,

P.S.: The instance where my account is tenforward.social.

**Comment by snarfed** [comment]
thanks for the report, and sorry for the trouble!

i haven't been able to reproduce this. i successfully used bridgy publish to interactively post to my mastodon account just now. could you post more details? eg a screenshot, the error text, the exact URL on your Mastodon instance that shows the error (with tokens, client id and secret, etc redacted!). or even better, feel free to jump into [indieweb chat](https://indieweb.org/discuss) and grab me there.

**Comment by snarfed** [comment]
i reproduced this tonight and suspect something wrong on mastodon's end: https://github.com/tootsuite/mastodon/issues/12915 . thanks again for reporting! let's keep tracking in #911 and see what the mastodon people say.
