### ISSUE TITLE
Error 500 when trying to connect Twitter

### ISSUE THREAD

**Issue by MrSunshyne** [snarfed/bridgy#910]
I think the issue is similar to #439 

See screenshot

![Screenshot 2020-01-18 at 10 34 05](https://user-images.githubusercontent.com/1721611/72660056-c3957c00-39e1-11ea-91de-b4eefe703410.jpg)

Connecting Github worked. Twitter is failing

**Comment by snarfed** [comment]
hey, sorry for the trouble! this is a rare bug triggered by the leading and trailing double underscores in your username, `__Sun__`, which aren't allowed in Google Cloud Datastore ids: https://cloud.google.com/datastore/docs/concepts/entities#kinds_and_identifiers

first time in right years that this has happened! 😆 i just need to escape them. I'll do that soon.

**Comment by MrSunshyne** [comment]
@snarfed ooohhh i see! Thanks for handling! 
i'll check again soon and get connected. Have a great Sunday 😎

**Comment by snarfed** [comment]
ok, i think i've fixed this. mind trying again?

**Comment by snarfed** [comment]
tentatively closing. thanks again for reporting!

**Comment by MrSunshyne** [comment]
Hi @snarfed, 

I retried the same process. It now works perfectly! Thanks for fixing


![Screenshot 2020-01-24 at 13 48 49](https://user-images.githubusercontent.com/1721611/73059939-415cfa00-3eb0-11ea-844e-0ad198ae18bc.jpg)
