### ISSUE TITLE
For the past few weeks, bridgy has been attemping to backfeed with the wrong...

### ISSUE THREAD

**Issue by CharlieRoseMarie** [snarfed/bridgy#912]
For the past few weeks, bridgy has been attemping to backfeed with the wrong source.
See the logs here:
[Example 1](https://brid.gy/log?start_time=1579293553&amp;key=agdicmlkLWd5clYLEghSZXNwb25zZSJIdGFnOnR3aXR0ZXIuY29tLDIwMTM6MTIxNDcwNjQ2ODAwOTcxMzY2Nl9mYXZvcml0ZWRfYnlfODcxNTMzMjU0NDY5Mjc1NjQ5DA)
[Example 2](https://brid.gy/log?start_time=1578690688&amp;key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTIxNTMzOTE3NDQyNjg5ODQzMgw)
[Example 3](https://brid.gy/log?start_time=1578709285&amp;key=agdicmlkLWd5cjYLEghSZXNwb25zZSIodGFnOnR3aXR0ZXIuY29tLDIwMTM6MTIxMzk1MDA5MDA0MzQxNjU3Ngw)

As you can see, the source is fine, but the body is pointing to the wrong link and source. In this example, it keeps trying to update twitter comments with a mastodon source, which are completely unrelated. It doesn’t seem to matter whether or not I have also syndicated the original post to mastodon.

**Comment by snarfed** [comment]
hmm! i'm guessing you mean the log lines like this?

```
I 2020-01-17 20:39:13.704716 Sent! {'request': 'POST https://charlotteallen.info/wp-json/webmention/1.0/endpoint (with source=https://brid-gy.appspot.com/like/twitter/CharlieRoseMari/1214706468009713666/871533254469275649, target=https://charlotteallen.info/2020/01/07/5267/)', 'http_status': 200, 'body': '{"link":"https:\\/\\/charlotteallen.info\\/2020\\/01\\/07\\/5268\\/#comment-508","source":"https:\\/\\/brid-gy.appspot.com\\/like\\/mastodon\\/@CharlotteRoseMati@todon.nl\\/103444973112980982\\/155409","target":"https:\\/\\/charlotteallen.info\\/2020\\/01\\/07\\/5268\\/","code":"...","message":"Webmention was successful"}'}
```

the `body` part of that is the response that bridgy got _back_ from your webmention endpoint. so you're right, something might be wrong, but i couldn't tell you what exactly, since it's on your end. cc @dshanske, looks like this is wordpress. any idea what's up?

**Comment by dshanske** [comment]
I am not quite sure. Will have a look

**Comment by CharlieRoseMarie** [comment]
Figured out the issue. There was a weird caching issue in nginx, which was caching API calls. Closing this issue.
