### ISSUE TITLE
Meetup.com: API errors on RSVPing should return friendlier error messages

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#921]
As per Ryan's comment on chat we should return the human-readable error in the payload to the user

**Comment by snarfed** [comment]
specifically, here are the example error messages i hit, [from 2020-02-17 #indieweb-dev](https://chat.indieweb.org/dev/2020-02-16#t1581893498557700):
* when i try to rsvp to a group's event that i'm not a member of: `Error: {"errors":[{"code":"member_error","message":"Invalid member"}]} HTTP Error 400: Bad Request`
* when i rsvp to a nonexistent url (that passes the regex): `Error: {"errors":[{"code":"group_error","message":"Invalid group urlname xyz"}]} HTTP Error 404: Not Found`

the catch is that these are `urllib.error.HTTPError`s that propagate all the way up to `publish.py`, where they're caught and returned as user-visible error messages:

https://github.com/snarfed/bridgy/blob/dea6fac32db7adc963e722ebf71e40f907d11959/publish.py#L268

the catch is, we want to parse the response body as JSON there and pull out the `message` field(s) and only show them, but that's specific to the meetup API. so maybe we'd do it here, in granary:

https://github.com/snarfed/granary/blob/d6846f0d1260dd4513464e481c46437cf813c77a/granary/meetup.py#L120-L123
