### ISSUE TITLE
Document how to get bootstrap for local testing

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#922]
As found in #906, Bootstrap isn't available locally for testing.

We should document how to get it set up in the README.md, to prevent confusion in the future.

**Comment by snarfed** [comment]
yes! sorry, this is a recent wart introduced by migrating to the app engine python 3 runtime, which is very different. background on the static file support issue: https://groups.google.com/d/topic/google-appengine/BJDE8y2KISM/discussion

i use a symlink in the root of the bridgy repo to oauth-dropins to expose the static files. try this:

```sh
ln -s local3/lib/python3.6/site-packages/oauth_dropins
```

ugly and undocumented. more background in 4fdc56fee42fa4e9b943753f51f15b9cbf80ac6c. i'd love to find something better, but you're right, apologies it's undocumented. i'd happily settle for docs!
