### ISSUE TITLE
Retweet with comment omits comment

### ISSUE THREAD

**Issue by drivet** [snarfed/bridgy#923]
Hi,

I have this post on my website:

https://desmondrivet.com/2020/02/20/201200

And I sent a corresponding webmention to Bridgy, which dutifully posted it to Twitter:

https://twitter.com/desmondrivet/status/1230670503016267778

Except that it got syndicated without the comment.  Am I missing something or is this normal behaviour?

Thanks for any help!

**Comment by snarfed** [comment]
hmm, sorry for any confusion! quote tweets aka retweets with comment use the `u-quotation-of` mf2 class, not `u-repost-of`. details: https://brid.gy/about#quote-tweet , https://indieweb.org/quotation#How_to_markup .

**Comment by drivet** [comment]
Ah! Thank you for clearing that up. I'll try it out soon.

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen if necessary!
