### ISSUE TITLE
Some missing steps in dev setup

### ISSUE THREAD

**Issue by fancypantalons** [snarfed/bridgy#924]
While configuring a new dev environment, I noticed a couple of steps missing.

First, at least on my Ubuntu 18.04 install, the `mox3` module is missing as a dependency, so that had to be added to the `pip install` command (though, it looks like one of the unit tests in that package fails...).

Second, to run the gcloud emulator, the project name must be set.  A call to `gcloud config set project <name>` does the job, but is missing from the setup instructions.

I confess, I don't know a dang thing about the actual technical details of developing for gcloud, so I don't know the proper value to set for the project name (i.e., are there namespacing issues that have to be considered, or, if you don't plan to deploy to gcloud, is any ol' name suitable?), otherwise I'd put together a pull request to fix these two issues.

Edit:

It also looks like the dev_appserver wrapper hasn't been updated to support python3?

**Comment by snarfed** [comment]
hey brett, sorry for the trouble, and thanks for the feedback! both great points. i didn't realize you needed to set the gcloud current project just to run the datastore emulator, but TIL.

these would both be great additions to the setup docs. any interest in filing a PR? `mox3~=0.28` would be the right addition to `requirements.txt`, to match granary and oauth-dropins, and you can set the project to `brid-gy`. (you're right though, bridgy doesn't do anything special with the current project, so any name should be fine.)

feel free to grab me in [indieweb chat](https://indieweb.org/discuss) too if you want!

**Comment by fancypantalons** [comment]
BTW, my life got a little crazy this week so I haven't had a chance to get back to this, but I can certainly throw a PR together to make those changes!

Should I file a separate issue around the lack of python3 support for dev_appserver, or is that already on the radar somewhere?

**Comment by snarfed** [comment]
thanks again @fancypantalons!
