### ISSUE TITLE
github poll demotes original post links due to author tag URI mismatch

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#928]
originally reported by @rretsiem (https://brid.gy/github/rretsiem) in https://github.com/snarfed/bridgy/issues/927#issuecomment-599969694. (thanks rené!) he isn't getting backfeed on that issue, even though it correctly links to his original post https://renem.net/notes/github/2020-03-16-1/ . looks like the problem is that bridgy's author and user tag URIs aren't matching. [from the poll log](https://console.cloud.google.com/logs/viewer?project=brid-gy&serviceId=false&minLogLevel=0&expandAll=false&timestamp=2020-03-17T14:26:25.241000000Z&customFacets=&limitCustomFacetWidth=true&interval=NO_LIMIT&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2F20200305t101818&logName=projects%2Fbrid-gy%2Flogs%2Fstdout&logName=projects%2Fbrid-gy%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2020-03-17T14:22:30.290452000Z&filters=text:https:%2F%2Fgithub.com%2Fsnarfed%2Fbridgy%2Fissues%2F927%23issuecomment-599807098):

```
discovering original posts for: https://github.com/snarfed/bridgy/issues/927
...
Original post discovery found original posts {'https://renem.net/notes/github/2020-03-16-1/'}, mentions {'https://docs.pixelfed.org/technical-documentation/api-v1.html#authorization', 'https://pixelfed.org/'}
Demoting original post links because user tag:github.com,2013:rretsiem doesn't match author tag:github.com,2013:MDQ6VXNlcjI0ODgzNg==
```

**Comment by rretsiem** [comment]
Even if this could be the issue, the main reason could also be the missing feed discovery for my h-feed on sub pages (e.g. /notes). I added proper rel="feed" links into the <head> element and let Brid.gy crawl the site again. It worked!

https://brid.gy/log?start_time=1584457161&key=agdicmlkLWd5chQLEgZHaXRIdWIiCHJyZXRzaWVtDA

According to this and the result on my Brid.gy user page, the backfeed looks complete! Sorry for any troubles, if this was the issue.

**Comment by snarfed** [comment]
good news! glad to hear it.

i think there's still a bridgy bug here, since your github issue had a link back to your original post, so you actually shouldn't have needed the feed discovery part at all. i'll look at that eventually, but i'm glad you have it working now!

**Comment by snarfed** [comment]
seeing this in other github accounts too, [eg this poll](https://brid.gy/log?start_time=1584937894&key=agdicmlkLWd5chILEgZHaXRIdWIiBnRhbnRlaww log):

```
discovering original posts for: https://github.com/mozilla/standards-positions/issues/271
...
Original post discovery found original posts {'https://tantek.com/2020/045/b1/'}, mentions {'https://github.com/mozilla/standards-positions/labels/wicg', 'https://github.com/w3ctag/design-reviews/issues/466', 'https://github.com/tQsW/webcrypto-curve25519/blob/master/explainer.md'}
I 2020-03-23 04:32:31.720280 Demoting original post links because user tag:github.com,2013:tantek doesn't match author tag:github.com,2013:MDQ6VXNlcjQ2NDE4
```

**Comment by snarfed** [comment]
argh, i totally forgot that [github backfeed requires `u-syndication` links](https://brid.gy/about#GitHub%20responses). right, ok then. never mind!
