### ISSUE TITLE
Webmentions are not received for twitter/mastadon actions

### ISSUE THREAD

**Issue by am1t** [snarfed/bridgy#929]
I do not receive any webmentions for actions on Twitter/Mastadon for the posts syndicated from [my website](https://www.amitgawande.com). The website is run on [Blot](https://blot.im). I do see the actions on [brid.gy dashboard](https://brid.gy/twitter/_am1t) with a status "No webmentions target".  This is primarily for posts with no explicit links to the post urls.

One possible reason I found was [here](https://brid.gy/about#profile-links), but Brotli compression is not enabled on the webserver. Only gzip. 

Is there any other reason why this might fail?

**Comment by am1t** [comment]
I was able to identify the issue by following [this helpful response](https://brid.gy/about#link). Apologies for raising the question, but I guess I would not have learnt this without raising the question.

**Comment by snarfed** [comment]
glad you figured it out!
