### ISSUE TITLE
[twitter] adding an optional flag to send "non-owner" tweets as mentions in addition to current POSSE replies

### ISSUE THREAD

**Issue by stedn** [snarfed/bridgy#930]
I'm interested in proposing an extension to bridgy outside the current use. To my understanding, bridgy is intended to be used only to capture social media replies directed at a POSSEd copy of an original blog post, (by POSSEd copy I mean the one posted by an individual whose blog rel="me" points directly to the social media account of the poster, see #51 (sorry if I'm not great with the indieweb jargon yet)).  

I am proposing to build an extension for twitter that will include the content of tweets that directly reference a blog post, provided that the blog post tweet does not come from the original poster (i'll call this other person a non-owner).  The intent is to gather sources for all the conversation on twitter about some blog content regardless of where the non-owner heard about it.  As an example, I posted a blog post to reddit and people found it there and tweeted it around. It'd be cool to pick up those conversations too. Note that as I'm currently intending it, this will cause only the individual tweet from non-owners to be sent, not replies to the non-owner tweet.

For similar applications, I believe that previous versions of Twitter Widgets allowed one to embed the results of a url search, but that is currently not possible using https://publish.twitter.com/.  I haven't had much luck in finding other APIs that allow this aggregation out-of-the-box.  And specifically for those using bridgy already, it would be nice to avoid the appearance of the POSSE tweet from the blog post author, and continue to only show replies there.

Does this plan sound reasonable? I don't yet have my twitter app credentials to start probing deeply, but I was poking around in `twitter.py`.  It seems that all of the tweets that reference a bridgy connected blog are pulled there, but that the filtering occurs in the `get_activities_response` in granary when the `user_id` is included.  The simplest change would be to make a boolean in the granary call that determines whether to include only replies to the POSSE tweet from that user_id or to take only the tweets that are NOT from that user_id.  Then perform two passes if the bridgy account has selected to collect all non-owner mentions.  

I'm starting to make some modifications, but let me know if any of this seems wildly incorrect or non-compatible with current roadmap.

**Comment by snarfed** [comment]
hi will! thanks for describing! and hmm, i think bridgy already does this. ie if i post a tweet that links to a post of yours, it currently finds that tweet and sends a webmention for it as a normal [mention](https://indieweb.org/mention). docs: https://brid.gy/about#which . feel free to try, it should work! (most of the time at least; [twitter's search API is best effort only](https://brid.gy/about#can%20be%20flaky). 😐)

we did also talk about _responses_ to other people's mentions, which bridgy definitely doesn't do right now. that could be a good extension in the future though!

**Comment by stedn** [comment]
oh good, that's what i'd originally thought, but mentions of my posts were not picked up.  i guess they were just too old to be picked up by twitter search.  the thing that tripped me up was when i tried retriggering them with "Resend for post" but it still didn't catch them.  thanks.

**Comment by snarfed** [comment]
ahh, yes, true. bridgy goes a bit back in time when you sign up, but not arbitrarily far. if you do have some of these tweets handy, the other thing you can try is to put their own URLs into "Resend for post."
