### ISSUE TITLE
"Resend for Post" box only sending replies and mentions for POSSEd content

### ISSUE THREAD

**Issue by stedn** [snarfed/bridgy#932]
Following up from https://github.com/snarfed/bridgy/issues/930, I realized that the issue I mentioned there only pertained to submissions through the "Resend for Post" box.  To summarize, I found an [old tweet](https://twitter.com/harlandduman/status/1226221748539944960) where someone mentions a blog post. When I drop the post URL in the "Resend for Post" box, it only gathers the likes and replies in the UI. 

![image](https://user-images.githubusercontent.com/6944278/78506602-8bbfea00-772f-11ea-9fd3-c34f55928079.png)

Then, since those likes and replies were not in response to my own tweet they aren't sent back either. 

It would be useful to trigger a "Resend for Post" and have it operate like the usual discovery.  I'm just logging this for now in case someone else hits the same thing.

**Comment by snarfed** [comment]
yes! thanks for filing, will look.

**Comment by snarfed** [comment]
yes! thanks for filing, will look.

**Comment by snarfed** [comment]
done! and confirmed with your example tweet.

**Comment by stedn** [comment]
Amazing! thank you.  I confirmed it worked on some other ones too.
