### ISSUE TITLE
[mastodon] bridgy sometimes misses replies when poster replies to themself

### ISSUE THREAD

**Issue by stedn** [snarfed/bridgy#933]
This may be the intended behavior, but it's surprising.  On this mastodon thread, https://fosstodon.org/web/statuses/103972016434753794 the top level comments and it's first reply are picked up, but the rest don't end up walking up to the original post.

![image](https://user-images.githubusercontent.com/6944278/78971408-58c77e80-7ac0-11ea-9d59-7f38000f780f.png)

They are discovered by the search, but they don't get associated with the link back to the original post.

**Comment by stedn** [comment]
btw, not high priority, I can investigate after working on reddit support if you want to assign to me as a reminder.

**Comment by snarfed** [comment]
hmm, interesting! definitely possible.

we use the [`statuses/[id]/context` API call](https://docs.joinmastodon.org/methods/statuses/) to get replies, which the docs there say is to _View statuses above and below this status in the thread._ that, and the fact that the responses field is `descendants`, makes/made me think it _should_ find indirect replies...but maybe not? i doubt i ever actually tested.

[here's our current code for fetching mastodon replies.](https://github.com/snarfed/granary/blob/178d5324df43931dd4679e4304f1654bde915277/granary/mastodon.py#L210-L214) hopefully we won't have to do anything like [all the extra manual work we currently do for twitter to get replies at all](https://github.com/snarfed/granary/blob/master/granary/twitter.py#L400-459).

thanks for offering to look! definitely not urgent.

**Comment by stedn** [comment]
I was curious so I looked into this a little more today.  (apologies for long update) You are right that `descendants` does include all of the replies.  I believe that the source of the issue might be that since I replied to myself, the same status will show up as a descendant for multiple of my statuses, but the webmention is only attempted for a subset of them.

I'm wondering if perhaps at the time of polling, it showed up as the descendant only to the closest ancestor? In my example, that appears to be the case. 

![image](https://user-images.githubusercontent.com/6944278/80039703-42042d00-84ad-11ea-8471-961914ae5848.png)

I replied to my "Woohoo📣..." post with "and it's working!...". The reply "@bonkerfield There you go :) " was in the descendants of both and it was sent to both.  However, this reply

![image](https://user-images.githubusercontent.com/6944278/80039911-c6ef4680-84ad-11ea-8bdc-921aa87745b4.png)

was only associated with the "and it's working!..." at the time, even though now it is in the descendants of "Woohoo📣.." as well.  I'm guessing in bridgy that once it is sent as a reply to one post it never gets resent if it's later found as a reply to another.

Would it be legit to make a small workaround that just ignores replies to my own replies to myself?

**Comment by snarfed** [comment]
> I'm wondering if perhaps at the time of polling, it showed up as the descendant only to the closest ancestor? In my example, that appears to be the case.

huh. you mean, mastodon only shows it as a reply to its direct parent, not all ancestors up the chain? if so, that makes sense, and is probably technically correct in a narrow sense. probably isn't specific to you ie the original post's author though, ie could happen to anyone, right?

i think the ideal indieweb solution to this is [salmentions](https://indieweb.org/Salmention), but those are not widely supported. bridgy probably does support them, but it's been hard to find test cases (or interest). see #458.

historically, twitter has been the only silo with this issue, and we handled it by making granary [manually find and include all descendants in the AS activity's `object.replies`](https://github.com/snarfed/granary/blob/ee244e2385e1248b644c05cf8e3e541423ccae43/granary/twitter.py#L400-L459), not just the direct replies.

maybe we should make mastodon do the same? alternatively, should we change this response de-duping logic to merge?

https://github.com/snarfed/bridgy/blob/bbf465b4b5ff0d20b06f699ff135f97c737da579/tasks.py#L315-L324

**Comment by stedn** [comment]
Sorry maybe I didn't make what I was trying to say clear. _Eventually_ it looks like all of the replies show up in the descendants of the top status.

But I'm wondering if there are no guarantees that this will happen right away (since the API for any instance has to be updated from other instances first).  So since bridgy doesn't send for the same status more than once, it sends it for the direct parent early, and then by the time the top reply is linked, it's too late.

Does that make sense?

Also, yeah wouldn't me specific to me, but it was easier to explain that way.

**Comment by snarfed** [comment]
yes! makes sense. i think that's what i understood, and i think my proposed changes would both still address it? or at least changing de-duping to merging would?

**Comment by stedn** [comment]
Cool, I think that walking up the tree might work.  The trick with this hypothesis is that it seems we'll need to see live examples as they happend.  

I'm not sure I understand the deduping->merging solution. Does line 319 look at all the statuses that have ever been returned or just the ones on that specific call to `backfeed`.

**Comment by snarfed** [comment]
good catch! you're right, i was looking at the wrong part of the poll code. line 319 only looks at duplicate responses within the ones fetched during this poll. that catches eg a reply that also has a link to your site, but isn't what we're talking about here.

i think the relevant code is actually this:

https://github.com/snarfed/bridgy/blob/bbf465b4b5ff0d20b06f699ff135f97c737da579/tasks.py#L382-L399

we construct a `Response` with the right id (eg tweet id), then call `get_or_save()` on line 399. if we've already seen the response with that id, we load it from the datastore and use that instead of creating a new one. `get_or_save` then tries to detect if the response has changed and needs to be re-sent, and if so, updates its data and restarts it:

https://github.com/snarfed/bridgy/blob/bbf465b4b5ff0d20b06f699ff135f97c737da579/models.py#L893-L907

we'd want to check if `activity_changed()` notice when the in-reply-to(s) in `response_json` change, and then we'd want to merge the new ones in, instead of replacing `resp.response_json` wholesale like we do now.

i'm only like 75% confident that this ^ is the right analysis and fix. still, that's something i guess. 😁

**Comment by stedn** [comment]
OK, I reran it locally with a clean DB and it did indeed pick up the one from that example.  
![image](https://user-images.githubusercontent.com/6944278/80271267-96f1a000-8673-11ea-9012-f3c758a16375.png)

So that gives me some confidence in the problem. I'll look into making the fix you suggested tonight.
