### ISSUE TITLE
[Twitter backfeed] Interactions from protected accounts are not registered

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#948]
My tweet https://twitter.com/JamieTanna/status/1265003671160528896 has received a reply from https://twitter.com/jna_sh/status/1265231376560926720 but is not picked up by Bridgy.

However, Granary has access to retrieve the post (as it has OAuth credentials to act as me, and I can see the post) so Bridgy _should_ too?

**Comment by snarfed** [comment]
ooohhhh no no no. bridgy is very careful to only backfeed fully public responses on fully public posts. it doesn't care if it technically has API access; it has to assume webmentions can and will be displayed publicly, and it should never expand the visibility of something beyond its original visibility inside the silo. that would be bad. so, it defaults to being safe and only ever handles fully public data. background: https://brid.gy/about#public

**Comment by jamietanna** [comment]
Ah gotcha, that makes sense. My bad 🙃
