### ISSUE TITLE
Twitter likes not being picked up?

### ISSUE THREAD

**Issue by armingrewe** [snarfed/bridgy#949]
Not sure what's going on, but it seems bridgy isn't picking up Twitter likes at the moment. It has picked up [this tweet](https://twitter.com/islayblog/status/1267686681689444352) from this morning as the original, but not any of the (so far) 6 likes.

All the likes for yesterday's tweet were sent as webmention (see [bridgy page for Twitter islayblog](https://brid.gy/twitter/islayblog))

Is that an issue with my account or a general issue with all Twitter likes?

**Comment by snarfed** [comment]
thanks for reporting! and oof, yup, looks like twitter broke our likes scraping. [from your poll log](https://brid.gy/log?start_time=1591122745&key=agdicmlkLWd5chYLEgdUd2l0dGVyIglpc2xheWJsb2cM):

```
I 2020-06-02 18:32:30.438961 urlopen GET https://twitter.com/i/activity/favorited_popup?id=1267686681689444352 {}
F 2020-06-02 18:32:30.684045 Non-JSON response! Returning synthetic HTTP 502.
b'<!DOCTYPE html>\n<html dir="ltr" lang="en">\n<meta charset="utf-8" />\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover" />...'
E 2020-06-02 18:32:30.686022 Error 502, response body: 'Non-JSON response! Returning synthetic HTTP 502.\nb\'<!DOCTYPE html>\\n<html dir="ltr" lang="en">\\n<meta charset="utf-8" />\\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover" />...''
```

notably, they're now browser (and/or JS) fingerprinting and serving an error instead of the likes JSON we need:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/778068/83561181-45d39800-a4cc-11ea-93ec-23ed5d227e5f.png">

ugh.

**Comment by armingrewe** [comment]
That doesn't sound good....

I'm guessing that will not only affect bridgy but also other services that use the likes JSON (I would guess there are some)?

**Comment by snarfed** [comment]
maybe? it's unofficial, not part of their developer API.

@jalcine found this (thanks jacky!), which looks like the cause: https://www.bleepingcomputer.com/news/technology/twitter-warns-of-legacy-site-theme-shutting-down-on-june-1/

**Comment by snarfed** [comment]
oof, what's worse, we may not be able to scrape likes at all now without being logged in. if you click on a tweet's _N likes_ link, you get this:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/778068/83563374-dd86b580-a4cf-11ea-8d02-9ee8c79d25ee.png">

**Comment by snarfed** [comment]
and of course, per-tweet likes still aren't available in the API.
https://twittercommunity.com/t/fetch-a-full-list-of-people-who-liked-my-tweet/133251
https://twittercommunity.com/t/fetch-the-user-id-of-the-user-who-have-liked-a-particular-tweet/135715

**Comment by snarfed** [comment]
this curl command works:

```sh
curl 'https://api.twitter.com/2/timeline/liked_by.json?tweet_mode=extended&include_entities=true&include_user_entities=true&tweet_id=1267686681689444352&count=80' \
  -H 'x-csrf-token: ...' \
  -H 'authorization: Bearer ...' \
  -H 'Cookie: auth_token=...; ct0=...'
```

**Comment by snarfed** [comment]
hacked in a logged in session. turning it on for all users now. god help us.

**Comment by armingrewe** [comment]
So far it seems to work, woke up to a good number of likes showing up.

As a side note, a reply and a mention came through yesterday already, do they use a different method to the likes and therefore were not impacted?

**Comment by snarfed** [comment]
> As a side note, a reply and a mention came through yesterday already, do they use a different method to the likes and therefore were not impacted?

right! they use the API for those. seems crazy, but in 2020 the twitter API still doesn't have a way to get a tweet's favorites, so we have to scrape those.

**Comment by snarfed** [comment]
logged in likes scraping is still working, 14h later. i wonder how long the access token expiration is. 🤣

**Comment by snarfed** [comment]
ok, this logged in scraping may be the new normal here. last task is to write a daily check that it's still working, so that when it inevitably expires, i can generate a new token. i'm guessing expiration is somewhere between 2w and 3 mos.

**Comment by snarfed** [comment]
added the daily logged in scraping test! tentatively closing this.

**Comment by tpsvld** [comment]
> ok, this logged in scraping may be the new normal here. last task is to write a daily check that it's still working, so that when it inevitably expires, i can generate a new token. i'm guessing expiration is somewhere between 2w and 3 mos.

Sorry How you generate new tokens?

**Comment by snarfed** [comment]
"i can generate a new token" was an internal bridgy thing, not for any specific users. twitter likes should be working now. if they're not for you, feel free to add more detail, including your bridgy user page URL!
