### ISSUE TITLE
"Resend for post" may not work for likes and retweets on reply tweets

### ISSUE THREAD

**Issue by RehanSaeed** [snarfed/bridgy#950]
_[See this comment below for the current state of this possible bug.](https://github.com/snarfed/bridgy/issues/950#issuecomment-640241573)_

According to the [Help](https://brid.gy/about#missing), Bridgy only looks at my 50 most recent Tweets (I'm unclear how the GitHub provider works, the code doesn't seem to indicate a number).

Since a lot of my blog posts are quite old, I have a lot of empty mentions. Is there a way to import all of my older tweets and GitHub comments?

Also, is it possible to also include tweets or GitHub comments from third parties and not just my personal account?

I'm using webmentions.io and have setup anchor links to social media on my home page only (not sure if I should add meta tags to each blog post page also).

**Comment by snarfed** [comment]
hey, yes! you can enter the URL for one of your old tweets, or blog posts if they have [syndication links](https://indieweb.org/u-syndication), into the _Resend for post_ box on your Bridgy user page, and it should try to discover and send mentions.

you have to do this for each post, though. #917 tracks a feature to backfill _all_ of your past posts, which is a great idea, but a very big project, so i don't have plans to implement it any time soon.

> Also, is it possible to also include tweets or GitHub comments from third parties and not just my personal account?

if the tweets link to your web site, sure! [Bridgy already does that automatically.](https://brid.gy/about#which)

**Comment by RehanSaeed** [comment]
If I've understood this correctly, syntication links to Twitter would be links on my blog post to Tweets. I'm trying to retrofit webmentions, so I don't have that.

I guess I'm looking for a tool that takes all the URL's for my site (via a sitemap.xml, rss.xml or even list a list of links), then searches on Twitter for those and pulls any Tweets containing the link.

**Comment by snarfed** [comment]
right! understood. for any tweet that links to any page on your site, you can enter the tweet's URL into the Resend for post box on your Bridgy user page, and Bridgy should send mention(s) for it.

#917 tracks the feature request to do that for all tweets, instead of one by one.

**Comment by RehanSaeed** [comment]
I've tried to use the 'Resend for post' feature for this blog post:

https://rehansaeed.com/what-dotnet-new-could-be/

However, I get an error message saying:

> Failed to fetch rehansaeed.com/what-dotnet-ne... or find a Twitter syndication link.

When I search Twitter with the above URL, there should be some Tweets that get picked up as web mentions:

https://twitter.com/search?q=https%3A%2F%2Frehansaeed.com%2Fwhat-dotnet-new-could-be%2F&src=typed_query

Have I configured something incorrectly?

**Comment by snarfed** [comment]
heh, yes. as mentioned, if your post doesn't have a syndication URL, put each _tweet URL_ into _Resend for post_.

i tried it with https://twitter.com/BryanWilhite/status/1212842573535989760 just now, and https://brid.gy/twitter/RehanSaeedUK shows that it sent successfully.

**Comment by RehanSaeed** [comment]
Ah, I feel silly now for not thinking of doing the reverse. I'm now seeing some new 'link' mention types which I've not seen before.

Final question. Why am I not getting any mentions for this tweet of mine which also clearly has the link to my post in it?

https://twitter.com/RehanSaeedUK/status/1212050257867137027

**Comment by snarfed** [comment]
> Final question. Why am I not getting any mentions for this tweet of mine which also clearly has the link to my post in it?
> 
> https://twitter.com/RehanSaeedUK/status/1212050257867137027

just because it was old. i plugged it into _Resend for post_, and all of its responses got sent.

**Comment by RehanSaeed** [comment]
I looks to me like brid.gy is ignoring tweets that are themselves replies to other tweets. I tried another old tweet that was not a reply and it went through. Is that a bug?

**Comment by snarfed** [comment]
i'm confused. you're right that the tweet you mentioned, https://twitter.com/RehanSaeedUK/status/1212050257867137027 , is a reply. it was too old for Bridgy to pick up automatically, but when i plugged it into _Resend for post_, all of its responses got sent, as expected.

were you talking about a different reply tweet? or other webmentions you think should have been sent?

**Comment by RehanSaeed** [comment]
This tweet of mine has a lot of likes and retweets, should these not be turned into web mentions? I'm getting zero being pushed into webmention.io.

![image](https://user-images.githubusercontent.com/2270364/83948425-11861180-a815-11ea-8c61-c389a4840513.png)

https://webmention.io/api/mentions?page=0&per-page=999&target=https://rehansaeed.com/what-dotnet-new-could-be/&sort-by=published&sort-dir=up

**Comment by snarfed** [comment]
ah, true! sorry about that, not sure why yet. will look.

**Comment by snarfed** [comment]
as a data point, other tweet replies do get backfed likes and retweets, so i suspect the issue here is the _Resend for post_ feature, or something related.

**Comment by RehanSaeed** [comment]
I tried another tweet which was a reply yesterday and the likes and retweets on it also didn't get through. Hard to say without more data points as you say but perhaps it's something to do with it being a reply maybe?

**Comment by snarfed** [comment]
bridgy definitely backfeeds likes and retweets to replies in general. here's an example: https://aaronparecki.com/2020/06/05/31/

so as mentioned, in this case, i expect it's a problem with _Resend for post_. maybe combined with the fact that these are replies; maybe something else entirely.

**Comment by snarfed** [comment]
Obsolete, Bridgy Twitter is dead. https://github.com/snarfed/bridgy/issues/1410#issuecomment-1497763725
