### ISSUE TITLE
read and store server specific character limit?

### ISSUE THREAD

**Issue by jk-na** [snarfed/bridgy#953]
Would it be possible when posting to the mastodon-api to adhere to the server's character limit before truncating?

Perhaps at account connection a lookup could be performed and the character count attribute saved.

I know the monolith of mastodon.social sticks with 500 characters but many other mastodon instances allow higher counts and other apps that use the api may also have higher counts.  My server has 5000 characters as it's limit.

**Comment by snarfed** [comment]
great idea, i'd love to! thanks for filing.

...except [there's no way to look up the character limit in the mastodon API](https://github.com/tootsuite/mastodon/issues/4915). [it's not even meant to be configurable at all](https://github.com/tootsuite/mastodon/pull/5697#issuecomment-345078582), at least not easily.

in your case, [it sounds like you're actually running pleroma](https://github.com/snarfed/bridgy/issues/952), not mastodon at all, right? which is totally fine, but i don't currently have plans to support pleroma explicitly. if you're interested, feel free to take a look at [how to add a new silo to bridgy!](https://bridgy.readthedocs.io/#adding-a-new-silo)

**Comment by jk-na** [comment]
OK, no worries, thanks.

I wasn't aware of the API restriction.  

I'll have a [how to add a new silo to bridgy](https://bridgy.readthedocs.io/#adding-a-new-silo) but probably I'll just work with the truncation at 500 characters as the new silo may be outwith the reaches of my skill set (we'll see)

**Comment by snarfed** [comment]
ok! sorry for the bad news. alternatively, if you can find a way to look up the server's character limit that works with both pleroma and mastodon - and doesn't depend on scraping that will break as soon as mastodon or pleroma change their HTML - i'd happily consider a PR!

**Comment by jk-na** [comment]
According to the [pleroma docs](https://docs-develop.pleroma.social/backend/API/differences_in_mastoapi_responses/#instance) it's implemented as an additional field on top of the mastodon api (max_toot_chars) but I'll not pretend to know the technicalities of implementing an additional api call or know what happens of you try to GET it from a mastodon instance.

**Comment by snarfed** [comment]
oh nice! that's totally usable. i can grab that field if it's available, and if not, default to 500. reopening this issue.

**Comment by jk-na** [comment]
Excellent, thank you!

**Comment by snarfed** [comment]
done! i think. feel free to try!

**Comment by jk-na** [comment]
Tested and confirmed [here](https://social.nipponalba.scot/notice/9wcE8SZ9Ot54lssnKK)

Many thanks!
