### ISSUE TITLE
GitHub syndication with blockquotes does not seem to quite work

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#957]
I'm not sure if this was an issue on my side, or on Bridgy's, but when I tried to publish [a reply](https://www.jvt.me/mf2/2020/07/hwj5l/) to a GitHub issue, the [syndicated comment](https://github.com/indieweb/indieauth/issues/38#issuecomment-657133370) originally had a <code>&amp;gt;</code>, not a <code>&gt;</code> indicating a blockquote, which meant I needed to manually edit the comment on GitHub to make it render nicer.

(Originally published at: https://www.jvt.me/mf2/2020/07/vgcq8/)

**Comment by snarfed** [comment]
hah, bridgy interprets HTML content as formatted, not raw Markdown, so it converts the HTML tags to Markdown with [html2text](https://pypi.org/project/html2text/) before sending to GitHub. you can disable that with https://brid.gy/about#ignore-formatting .

**Comment by snarfed** [comment]
oh wait nm i just realized you do actually use `<blockquote>`, you just render it with `>`s. funny. i'll keep looking then.

**Comment by nolith** [comment]
&gt; oh wait nm i just realized you do actually use <code>&lt;blockquote&gt;</code>, you just render it with &gt;s. funny. i’ll keep looking then.

Yes, same problem here.

<code>blockquote</code> tags are converted to markdown <code>&gt;</code> but then escaped to <code>&gt;</code>

(Originally published at: https://l0g.in/59U9xC)

**Comment by snarfed** [comment]
thanks for the nudge, and sorry for the trouble! i'll look at this again.

**Comment by snarfed** [comment]
fixed!
