### ISSUE TITLE
Twitter publish: weird behaviour

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy#959]
Not sure if it's a bug or I am doing something wrong.

[This post](https://evgenykuznetsov.org/posts/2020/no-future/) produced [this tweet](https://twitter.com/nekr0z/status/1284584786317709312) via Bridgy Publish, and this seems to be what's expected.

However, [this post](https://evgenykuznetsov.org/en/posts/2020/no-future/) produced [this tweet](https://twitter.com/nekr0z/status/1284584773588058113). The post are similar (actually, one is the translation of the other), but the tweets look very different, and I can't figure out why.

**Comment by snarfed** [comment]
Hmm! Sorry for the trouble. Bridgy's post type detection interpreted the first post as a note and the second at an article, even though their mf2 is basically the same. Not sure why yet.

Here's the AS1 that bridgy converted then both to. First/good tweet ([log](https://brid.gy/log?start_time=1595103854&key=agdicmlkLWd5clgLEg1QdWJsaXNoZWRQYWdlIjFodHRwczovL2V2Z2VueWt1em5ldHNvdi5vcmcvcG9zdHMvMjAyMC9uby1mdXR1cmUvDAsSB1B1Ymxpc2gYgIDQwtDShgoM)):

```
{
"objectType":"note",
"published":"2020-07-18T23:14:56+0300",
"displayName":"\u2022\u2022\u2022",
"content":"<p>\u041f\u043e\u0447\u0435\u043c\u0443 \u043c\u044b \u043d\u0435 \u0432\u0441\u0442\u0440\u0435\u0447\u0430\u0435\u043c \u043b\u044e\u0434\u0435\u0439, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u043f\u0440\u0438\u0431\u044b\u043b\u0438 \u0438\u0437 \u0431\u0443\u0434\u0443\u0449\u0435\u0433\u043e \u043d\u0430 \u043c\u0430\u0448\u0438\u043d\u0435 \u0432\u0440\u0435\u043c\u0435\u043d\u0438? \u041e\u0447\u0435\u043d\u044c \u043f\u0440\u043e\u0441\u0442\u043e: \u043d\u0435\u0442 \u0443 \u0447\u0435\u043b\u043e\u0432\u0435\u0447\u0435\u0441\u0442\u0432\u0430 \u0431\u0443\u0434\u0443\u0449\u0435\u0433\u043e.</p>\n<p><em>\u0410\u0432\u0442\u043e\u0440 \u043d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u0435\u043d.</em></p>",
"url":"https://evgenykuznetsov.org/posts/2020/no-future/",
"tags":[
{
"objectType":"hashtag",
"displayName":"lol"
},
{
"objectType":"hashtag",
"displayName":"\u043e\u0431\u0449\u0435\u0441\u0442\u0432\u043e"
}
],
"author":{
"objectType":"person",
"displayName":"\u0415\u0432\u0433\u0435\u043d\u0438\u0439 \u041a\u0443\u0437\u043d\u0435\u0446\u043e\u0432",
"url":"https://evgenykuznetsov.org",
"image":[
{
"url":"https://evgenykuznetsov.org/img/avatar.jpg",
"displayName":"\u0415\u0432\u0433\u0435\u043d\u0438\u0439 \u041a\u0443\u0437\u043d\u0435\u0446\u043e\u0432"
}
]
}
}```

Second/bad tweet ([log](https://brid.gy/log?start_time=1595140830&key=agdicmlkLWd5clwLEg1QdWJsaXNoZWRQYWdlIjVodHRwczovL2V2Z2VueWt1em5ldHNvdi5vcmcvZW4vcG9zdHMvMjAyMC9jYWRlLWRpZWhtLwwLEgdQdWJsaXNoGICA0IKWh5YKDA)):

```
{
"objectType":"article",
"published":"2020-07-19T09:37:31+0300",
"displayName":"\u2022\u2022\u2022",
"content":"<p>Found not one but two links to <a href=\"https://newdesigncongress.org/en/pub/this-is-fine/\" rel=\"\">Cade Diehm\u2019s article</a> in my RSS reader this morning: one <a href=\"https://v2.jacky.wtf/post/37fffcf2-762d-46c2-b771-09858ae9158e\" rel=\"\">by Jacky Alcin\u00e9</a>, another one <a href=\"https://www.zylstra.org/blog/2020/07/14707/\" rel=\"\">by Ton Z\u0133lstra</a>. Both seem to have enjoyed the article and speak highly of it, so I had to give it a read.</p>\n<p>Got up to the second sentence.</p>\n<blockquote>\n<p>From well-funded blockchain projects like IPFS to the emergence of large scale information networks such as Dat, Scuttlebutt and ActivityPub [\u2026]</p>\n<p><em>Cade Diehm \u201cThis is Fine: Optimism &amp; Emergency in the P2P Network\u201d</em></p>\n</blockquote>\n<p>This article may contain valuable thoughts, but I can\u2019t force myself to read it any further. I\u2019ve tried three times, I just cant get past this sentence. My brain starts screaming in agony: \u201cThis schmuck is calling IPFS a blockchain project and ActivityPub an information network. The schmuck has no idea what either IPFS or ActivityPub is, and didn\u2019t bother to research. The author has no clue about the things he\u2019s discussing. Complete waste of time! Close the tab! CTRL+W now!!!\u201d</p>\n<p>Note to self: if you don\u2019t get your facts straight in the first place, your ideas \u2014 though they might be brilliant \u2014 may fail to ever be heard.</p>",
"url":"https://evgenykuznetsov.org/en/posts/2020/cade-diehm/",
"author":{
"objectType":"person",
"displayName":"Evgeny Kuznetsov",
"url":"https://evgenykuznetsov.org",
"image":[
{
"url":"https://evgenykuznetsov.org/img/avatar.jpg",
"displayName":"Evgeny Kuznetsov"
}
]
}
}
```

**Comment by nekr0z** [comment]
Hmm, the tag hasn't been processed in the "bad" one either. I somehow am almost convince there's a error in the "bad" page somewhere, but can't figure it out.

**Comment by snarfed** [comment]
argh, sorry, the second example above was the wrong one. i've fixed it, it's right now.

**Comment by snarfed** [comment]
narrowed this down more. looks like a bug in `mf2util.post_type_discovery` that's triggered by Cyrillic (or non-English) characters in `content`.

```py
>>> mf2util.post_type_discovery({"properties": {
    "name":["foo"],
    "content":["abc xyz"],
  }}))
"article"

>>> mf2util.post_type_discovery({"properties": {
    "name":["foo"],
    "content":["\u041f\u043e\u0447"],
  }})
"note"
```

**Comment by snarfed** [comment]
ugh, yup, quite literally:

```py
        s = re.sub('[^a-z0-9]', '', s)
```

https://github.com/kylewm/mf2util/blob/b77ef860b83a2cfb3b6147f065902aefdd5d3601/mf2util.py#L420

**Comment by snarfed** [comment]
uh that was...a bit too eager on github's part. not merged or deployed yet.

**Comment by snarfed** [comment]
@nekr0z this is fixed, but probably not the way you expected. both posts will now be published like the second, as _•••: https://evgenykuznetsov.org/en/posts/..._, because they have `p-name`s, so [post type discovery](https://indieweb.org/post-type-discovery) says they're articles, not notes, and [Bridgy prefers `p-name` if it's provided](https://brid.gy/about#microformats). you can make it tweet the content instead by removing the `p-name` class entirely, or just [tell it explicitly what to tweet](https://brid.gy/about#silo-content).

**Comment by nekr0z** [comment]
Thank you for both the work on this and the detailed explanation! You’re awesome.

(Originally published at: https://evgenykuznetsov.org/en/reactions/2020/61-bridgy/)
