### ISSUE TITLE
Twitter likes and replies not working since morning

### ISSUE THREAD

**Issue by sparxsys** [snarfed/bridgy#972]
I tried posting a like and reply to twitter but it is not working for me today. It was working yesterday so I am not sure what went wrong. I am using Indieweb Drupal module.

Example like: https://www.ravisagar.in/like/httpstwittercomgitlabstatus1300433693174005768s09
Example reply: https://www.ravisagar.in/reply/reply-httpstwittercomrobertcastelostatus1300811243020836880

Like and replies to non twitter sites are working though.

Thanks

**Comment by snarfed** [comment]
hi ravi, sorry for the trouble! i don't actually see any requests to Bridgy to publish those two posts, either in bridgy's logs or [on your user page](https://brid.gy/twitter/ravisagar#publishes). maybe try again?

**Comment by sparxsys** [comment]
There was problem on Drupal side. I cleared the queue and it works now. Thanks for looking into this.

**Comment by snarfed** [comment]
No problem! Glad you figured it out.
