### ISSUE TITLE
Twitter - filter out reactions?

### ISSUE THREAD

**Issue by edent** [snarfed/bridgy#983]
Is it possible to configure my bridgy account so that it only sends *comments* not *reactions*?

For example, I don't want to get favourites or reposts. Just mentions.

Thanks!

**Comment by snarfed** [comment]
Interesting! Reminds me of https://github.com/snarfed/granary/issues/138.

Bridgy doesn't currently have a way to do this. It doesn't actually have any per-user settings at all yet. Your site is homegrown, right? Any chance you could filter them out on your side? You'll probably have better luck with that, at least in the short term.

**Comment by snarfed** [comment]
friendly ping! any luck filtering on your end?

**Comment by edent** [comment]
I'm trying to work out how to filter it using this WordPress plugin https://github.com/pfefferle/wordpress-webmention/issues/243

**Comment by snarfed** [comment]
got it! you're in good hands over there. tentatively closing here.
