### ISSUE TITLE
OPD: handle fragments in syndication URLs

### ISSUE THREAD

**Issue by nolith** [snarfed/bridgy#984]
Hello, when I tested brid.gy GitHub publish integration I got a strange webmention that I didn’t expected.

This is my original content [https://abisso.org/stream/2020/10/19/tor-in-vagrant/](https://abisso.org/stream/2020/10/19/tor-in-vagrant/) and it received 2 reply webmentions.

One is the legitimate reply from the issue author (shown as comment on my original post) and another one that is a reply pointing to my own comment (that I filtered out on the web page).

Is this behavior expected?

Thank you for this wonderful project :pray:

(Originally published at: https://l0g.in/59S74i)

**Comment by snarfed** [comment]
sorry for the trouble, and thanks for filing! looks like this is a bug. your post's `u-syndication` correctly points to https://github.com/rootzoll/raspiblitz/issues/1671#issuecomment-712288548 , but we then lose the fragment at some point, so we think your post is for the original issue, and so every comment then turns into a webmention, including yours. will fix.

relevant snippet from the poll log where this posse post discovery happened:
```
processing permalink: https://abisso.org/stream/2020/10/19/tor-in-vagrant/
requests.head https://abisso.org/stream/2020/10/19/tor-in-vagrant/
u-syndication links on the h-feed h-entry: ['https://github.com/rootzoll/raspiblitz/issues/1671#issuecomment-712288548']
requests.head https://github.com/rootzoll/raspiblitz/issues/1671
saving discovered relationship https://github.com/rootzoll/raspiblitz/issues/1671 -> https://abisso.org/stream/2020/10/19/tor-in-vagrant/
discovered relationships {'https://github.com/rootzoll/raspiblitz/issues/1671': [SyndicatedPost(key=Key('GitHub', 'nolith', 'SyndicatedPost', 5674191645573120), created=datetime.datetime(2020, 10, 19, 17, 53, 50, 853789), original='https://abisso.org/stream/2020/10/19/tor-in-vagrant/', syndication='https://github.com/rootzoll/raspiblitz/issues/1671', updated=datetime.datetime(2020, 10, 19, 17, 53, 50, 853795))]}
```

**Comment by snarfed** [comment]
😆 😢 

https://github.com/snarfed/bridgy/blob/b472fd7bf7469755f63d707d4538699a9752d57e/github.py#L27-L39

**Comment by nolith** [comment]
&gt; I’m lazy, though, so I’m leaving this as is for now.

Thank you for your answer and the funny excerpt from the code comment 😆

May I ask you what’s the meaning of _OPD_?

(Originally published at: https://l0g.in/59SMNU)

**Comment by Ryuno-Ki** [comment]
My guess: OPD stands for original_post_discovery (as this is a common pattern in Python).

**Comment by snarfed** [comment]
fixed, deploying now. thanks again for filing!
