### ISSUE TITLE
No twitter webmentions for abisso.org

### ISSUE THREAD

**Issue by nolith** [snarfed/bridgy#985]
Hello, I noticed that my twitter account no longer receives webmentions from bridgy.

It picks the reply but shows the “no webmention support” text, followed by my canonical post (both shortlink and permalink).

Today I was able to get a screenshot of when bridgy fetched replies for the first time:

![bridgy sending webmentions](/images/uploads/bridgy-no-twitter/sending-d74a15fb.png)

But nothing was received on webmention.io and now bridgy tells me “no webmention support”

![bridgy sending webmentions](/images/uploads/bridgy-no-twitter/no-webmention-ad518802.png)

The reply in the screenshots is [this tweet](https://twitter.com/zarel_it/status/1323589138168180737).

I already checked [https://brid.gy/about#missing](https://brid.gy/about#missing) but it seems not relevant in my case as the original post is discovered.

Could someone help me figure out if it’s a problem on my side or a legitimate bug? :pray:

(Originally published at: https://l0g.in/59VCxN)

**Comment by snarfed** [comment]
interesting bug! sorry for the trouble. you're advertising your webmention endpoint on some of your URLs, eg https://abisso.org/stream/2020/11/03/e-ora-che-sono-dentro-e-tocca-a-me-lo-spid-di-siel/ , but not others, eg https://abisso.org/59VC3V . bridgy caches webmention endpoints by domain, and it sends wms in a deterministic order, so it tries https://abisso.org/59VC3V first, sees that it has no endpoint, caches that, and skips the other one.

you can work around this in the short term by advertising your endpoint on all of your posts. not ideal if you deliberately chose not to, though, i know. bridgy's caching webmention endpoints by domain isn't ideal either - details in #601 - but it has to do webmention endpoint discovery on hundreds of thousands of URLs per day, so it's a tradeoff.

**Comment by nolith** [comment]
&gt; sorry for the trouble!

Please don’t feel sorry for this, you made a lot available for free to all of us.

Thanks for checking.

My site is statically generated and I implemented newbase60 deterministic short links with javascript redirects (not the best option).

I have 2 options I can apply easily:

  1. add webmention links in <code>&lt;head&gt;</code> in the shortlink pages, but then will brid.gy send mentions to my canonical URL or to the permashortlink?
  2. this is more complex to implement, but I could generate a config file that will force the webserver to issue 302 redirects for the permashortlinks.



Will option n. 1 be enough for fixing this?

(Originally published at: https://l0g.in/59VH0G)

**Comment by snarfed** [comment]
Yes, #1 should fix this. And Bridgy follows redirects when it serves wms, but not rel=canonical or anything else, so it will probably send the wms to your shortlinks.

(I'd recommend setting up redirects anyway, we generally find that serving content on shortlinks instead of redirecting causes problems like this over time, but up to you!)

**Comment by nolith** [comment]
Thank you. It’s working now 🎊

(Originally published at: https://l0g.in/59VK55)
