### ISSUE TITLE
GitHub: relative image URLs should become absolute once syndicated

### ISSUE THREAD

**Issue by nolith** [snarfed/bridgy#986]
Canonical post images with a relative <code>src</code> attribute are syndicated on GitHub with a relative path (i.e. `![alt text](/path/to/thre/image.png)`).

This can be seen in [https://github.com/snarfed/bridgy/issues/985](https://github.com/snarfed/bridgy/issues/985) and it’s [canonical post](https://abisso.org/stream/2020/11/03/no-backfeed/).

I suggest we convert image paths to absolute URL during the syndication.

(Originally published at: https://l0g.in/59VDGN)

**Comment by snarfed** [comment]
thanks for reporting! definitely a bug, i'll take a look.

**Comment by snarfed** [comment]
fixed. thanks again for filing!
