### ISSUE TITLE
Backfeed show failures but no log found

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy#992]
https://brid.gy/twitter/singpolyma all recent ones show failure, but when I retry I just get "no log found"

**Comment by snarfed** [comment]
Hey Stephen! Sorry for the trouble. Logs are currently unhappy due to https://github.com/googleapis/python-logging/issues/110, hopefully that will get ironed out soon.

**Comment by snarfed** [comment]
We still haven't quite fixed the logging library side of this, so in the meantime I just downgraded so that Bridgy logs work again.
