### ISSUE TITLE
Multiple tweets syndicated for a single note (but no logs)

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy#996]
The note https://www.jvt.me/mf2/2020/12/tqgvk/ was syndicated twice by Bridgy:

- https://twitter.com/JamieTanna/status/1338495985320910848
- https://twitter.com/JamieTanna/status/1338495986143006721

It appears that there are no logs for either syndication on the Bridgy side.

(I've not yet been able to check my logs, but will have a look later when I get a chance)

**Comment by snarfed** [comment]
True! Interesting. Sorry for the trouble! Looks like a straightforward race condition due to two publish webmentions arriving just a second apart. I should be able to make it handle that correctly!

**Comment by snarfed** [comment]
Specifically, I think the fix is to check for `status == 'new'` here as well as `'complete'`:

https://github.com/snarfed/bridgy/blob/6e9b606c0d73eb755ece6414b2c6fab1460170a4/publish.py#L564-L567
