### ISSUE TITLE
Browser extension for IG/FB backfeed

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#997]
Indieweb integration with Instagram is currently going the way of Facebook, due to IG recently ramping up their efforts to block scraping. IG support in both OwnYourGram and Bridgy degraded pretty badly and is currently pretty much dead, at least as is.

@aaronpk and I have been discussing working around this with browser extensions. They would fetch the data we need from IG in the users' browsers, with their session cookies, IP, user agent, etc, and then either send it to OYG/Bridgy to do the rest, or implement that functionality (micropub, backfeed) in the extension directly.

I'm starting this issue just as a place to keep notes on how I might do this with Bridgy. Right now, I'm thinking a Bridgy extension would just make the HTTP fetches to IG for a user's profile page, individual post permalinks, and likes JSON, and then forward that HTML and JSON directly to Bridgy for parsing and processing.

**Comment by snarfed** [comment]
First pass at this is working! Alpha browser extensions:
* https://addons.mozilla.org/en-US/firefox/addon/bridgy/
* https://chrome.google.com/webstore/detail/bridgy/lcpeamdhminbbjdfjbpmhgjgliaknflj

**Comment by chrismaverick** [comment]
Awesome. Works perfectly. I don't know much about browser extensions. So my two immediate questions are 

1) could this work for FB as well as IG
2) could it work in safari?

**Comment by snarfed** [comment]
Glad it's working! And yes, this could definitely work for FB too. I haven't looked into it yet, but I might.

Safari, I know less about. Historically their extensions API had been proprietary, but they recently added WebExtension support: https://developer.apple.com/news/?id=kuswih5l . You evidently still have to package it as a Mac OS app though? Which I'm not very familiar with. PRs welcome though!

**Comment by chrismaverick** [comment]
right now I'm just happy to have IG back. It was annoying when that broke. So thanks!

**Comment by timnolte** [comment]
I installed the extension, I got prompted to login to Instagram, and authenticated with my website, but when I go to the extension options it's not showing my Instagram account. Is there some way to get it to pickup the account?

**Comment by timnolte** [comment]
Do Instagram accounts need to be public for this to work?

**Comment by snarfed** [comment]
@timnolte sorry for the trouble! Yes, Bridgy only handles fully public accounts and data. https://brid.gy/about#post+fully+public

**Comment by snarfed** [comment]
Launched this for Facebook a few days ago. @chrismaverick feel free to try it! https://brid.gy/about#browser-extension
